feat: unquote valid js identifier property keys
rome/tools pull request #1235
Opened 2020-12-15 15:21 UTC by pradel

## Summary

Hey all (first-time contributor to rome), to get a bit more familiar with the codebase I decided to try to fix issue https://github.com/rome/tools/issues/982.

I managed to get the code working for property keys but I didn't succeed to apply the same for computed members. If you can point me out where I should make the changes for computed members that would be really helpful :). Maybe the computed members change can be made in a separate pull request?

A lot of changes in this pr are related to this new formatting applied to the codebase. The 2 important files are:
- `internal/formatter/builders/js/objects/JSStaticPropertyKey.ts` this is where the change is located.
- `internal/formatter/test-fixtures/objects/property-key/input.test.md` test output.

From the snapshots, this is how the change looks like:

### `Input`

```js
const foo = {
  "bar": true,
};
```

### `Output`

```js
const foo = {
	bar: true,
};
```

## Test Plan

Tests are passing properly ✅ 

```
➜ ./rome check --apply
 Building trunk 
! This command has been hidden. Consider its usage to be experimental and do not expect support or
ℹ 1_731 files linted
✔ No known problems!
```

```
➜ ./rome test         
 Building trunk 
! This command has been hidden. Consider its usage to be experimental and do not expect support or
✔ 3_838 tests passed!
```

2020-12-22 13:53 UTC, ematipico commented
Hi @pradel , thank you for looking into this!

Regarding your issue, here's the steps you can follow to understand where to look:
- create a dummy file e.g. `test.js`
- inside the file you can write:

```js
a["b"] = "bew";
a.b = "bew"	
```

which are the two cases that you want to analyze (format from the first case to the second case)

- run the command `./rome parse test.ts`

The output should contain something like this:

```js
JSExpressionStatement {
  expression: JSAssignmentExpression {
    operator: "="
    right: JSStringLiteral {value: "bew"}
    left: JSMemberExpression {
      object: JSReferenceIdentifier {name: "a"}
      property: JSComputedMemberProperty {value: JSStringLiteral {value: "b"}}
    }
  }
}
JSExpressionStatement {
  expression: JSAssignmentExpression {
    operator: "="
    right: JSStringLiteral {value: "bew"}
    left: JSMemberExpression {
      object: JSReferenceIdentifier {name: "a"}
      property: JSStaticMemberProperty {value: JSIdentifier {name: "b"}}
    }
  }
}

```

From here, you can understand that we want to apply a different formatting inside the `JSMemberExpression` node. So you can open the file `JSMemberExpression.ts` insider the formatter package.

As we want create new nodes (and replace with the existing ones), you can use the function `jsStaticMemberProperty` that you can export from the file `ast/js/expressions/JSStaticMemberProperty.ts`.

I hope it helps.

2020-12-24 10:43 UTC, pradel commented
@ematipico thanks for the help I managed to make it work 🎉 
I updated the description of the pull request to point to the important parts of the changes. Let me know if something is missing or wrong :)

2020-12-26 12:47 UTC, ematipico requested changes
It looks good to me! I would add some more test case inside the tests

2020-12-26 12:47 UTC, ematipico commented on internal/formatter/test-fixtures/objects/computed-member/input.js
> +const foo = {};
I might make sense to add some mixed/more cases, e.g.:

```js
foo.bar["bar"]["lorem_ispsum"]["lorem-ipsum"]
```

And so on. Let's try to cover some edge case.

2020-12-27 17:41 UTC, pradel commented on internal/formatter/test-fixtures/objects/computed-member/input.js
> +const foo = {};
Added some edge cases 👍

2020-12-28 11:57 UTC, ematipico approved these changes

2020-12-28 11:58 UTC, merged