test: add test for parser-core/ParserCore.ts
rome/tools pull request #1261
Opened 2020-12-25 04:46 UTC by jer3m01

## Summary
Part of #1023 

Adds test for parser-core/ParserCore.ts

## Test Plan

`rome check` is successful.
`rome test` passes all tests.

2020-12-26 12:53 UTC, ematipico requested changes
Not sure about the nature of these tests

2020-12-26 12:53 UTC, ematipico commented on internal/parser-core/ParserCore.test.ts
> +import {test} from "rome";
I am not sure this test makes sense. `ParserCore` is used to create new parsers, let's see it as an abstract class, and in this test we are testing the JS parser. 

Shouldn't we test its methods like `nextToken`, `getToken`, etc.?

2020-12-27 18:11 UTC, jer3m01 commented on internal/parser-core/ParserCore.test.ts
> +import {test} from "rome";
Totally, my oversight, will test ParserCore itself.

2020-12-31 05:07 UTC, jer3m01 commented
Looks like I am using a too old fork of rome locally, will rebase tomorrow.

2021-01-06 10:28 UTC, ematipico approved these changes
Great, much better now. If you made a rebase, we could merge it! (CI is now fixed)

2021-01-06 17:33 UTC, merged