feat(css-parser): support universal selector
rome/tools pull request #1290
Opened 2021-01-08 12:56 UTC by yeonjuan

## Summary

This PR is for support parsing universal selector (`*`).

## Test Plan

test case.

2021-01-08 12:57 UTC, yeonjuan commented on internal/css-parser/parser/selectors.ts
> -		const token = readToken(parser, "Delim") as Tokens["Delim"];
It was a bug. "Delim" token should not be consumed before parsingSelector

2021-01-08 15:27 UTC, ematipico requested changes
It looks good, I would review the part where we check the token

2021-01-08 15:27 UTC, ematipico commented on internal/css-parser/parser/selectors.ts
> +	parser.expectToken("Delim");
`expectToken` should be avoided because it throws an hard error, making the parser not recoverable. A better strategy would be to return `CSSUniversalSelector | undefined` and use `parser.matchToken()`

2021-01-08 15:46 UTC, yeonjuan commented on internal/css-parser/parser/selectors.ts
> +	parser.expectToken("Delim");
>  it throws an hard error, making the parser not recoverable

Oh got it. Thanks for the kind explanation :)

2021-01-10 08:47 UTC, ematipico approved these changes

2021-01-10 08:47 UTC, merged