feat(css-parser): support attribute selector
rome/tools pull request #1292
Opened 2021-01-09 13:38 UTC by yeonjuan

## Summary

## Test Plan

2021-01-10 12:22 UTC, ematipico requested changes
Thank you for looking into this! Added few suggestions on making the errors a bit more descriptive and few considerations around the code

2021-01-10 12:22 UTC, ematipico commented on internal/css-parser/parser/selectors.ts
> +		readToken(parser, "Whitespace");
Just noticed now but the implementation of `readToken` uses `parser.eatToken`. Should we call this function `eatToken` instead?

2021-01-10 12:22 UTC, ematipico commented on internal/css-parser/parser/selectors.ts
> +				if (ident.value === "i") {
We should add `s` too

2021-01-10 12:22 UTC, ematipico commented on internal/css-parser/parser/selectors.ts
> +		if (matchToken(parser, "Ident")) {
Here too, having:
```ts
if (!matchToken(parser, "Ident")) {
  parser.unexpectedDiagnostic();
  return undefined;
}
```

would help the reading of the code.

2021-01-10 12:22 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +	UNKNOWN_ATTRIBUTE_MODIFIER: {message: markup`Unknown attribute modifier`},
I would transform this into a function and pass the incorrect value and show it with `<emphasis>`.

Also, I would add another log telling to the user that the only correct values are `s` and `i`.

2021-01-10 12:22 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +		message: markup`Expected a left bracket <emphasis>{</emphasis>`,
```suggestion
		message: markup`Expected a left curly bracket <emphasis>{</emphasis>.`,
```

We could show the character that we actually get instead of the bracket

2021-01-10 12:22 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +		message: markup`Expected to close attribute selector with a right bracket <emphasis>]</emphasis>`,
```suggestion
		message: markup`Expected to close attribute selector with a right square bracket <emphasis>]</emphasis>.`,
```

We could add the character we got instead of the square bracket

2021-01-10 12:22 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +		message: markup`Unknown attribute matcher`,
We could suggest the available/correct attribute matchers. We have an utility called `buildSuggestionAdvice`

2021-01-10 12:22 UTC, ematipico commented on internal/formatter/builders/css/selectors/CSSAttributeSelector.ts
> +	return concat(tokens);
I am not sure if this suggestion is correct (I don't have extensive knowledge of the formatter yet), but should we _group_ the whole attribute selector? We should add a test with long strings and make sure that the whole attribute selector is not broken on multiple lines.

2021-01-10 12:22 UTC, ematipico commented on internal/css-parser/test-fixtures/selectors/input.css
> +a[title~="title" i] {
Could we add another example with multiple attribute selectors?

```css
a[title = "title"][href="image/*"] { // let's keep the asterisk and make sure is parsed as string
  color: purple;
}
```

2021-01-10 13:53 UTC, yeonjuan commented on internal/formatter/builders/css/selectors/CSSAttributeSelector.ts
> +	return concat(tokens);
@ematipico Thanks, I added a test case :) - [test case](https://github.com/rome/tools/pull/1292/files#diff-2436033c538e80c8f5af882dbc7b5076fa7078b3b192090777c83c748fa5a5beR130) .As far as I know, what "group" does is grouping the node's indent level :)

2021-01-10 15:04 UTC, yeonjuan commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +		message: markup`Unknown attribute matcher`,
@ematipico Thanks! I added `buildSuggestionAdvice` but I'm not sure but it does not work. It seems a bug in `buildSuggestionAdvice`.

```js
buildSuggestionAdvice("*", ["*="]); // it returns []
```

2021-01-12 10:29 UTC, yeonjuan commented on internal/css-parser/parser/selectors.ts
> +	let matcher: string | undefined;
@ematipico Thanks :)
The matcher could include two tokens so it should be concatenated (`+=`) - [line](https://github.com/rome/tools/pull/1292/files/4da2e99128903604e6514c3a324691bff318547b#diff-0a2350dfc20a66ba1dc400464afaa6c9da34949e8238042903dc7513cf5f8d1eR163)

That's why I use `string` here :) Any good typing Idea?

2021-01-12 10:37 UTC, ematipico commented on internal/css-parser/parser/selectors.ts
> +	let matcher: string | undefined;
I do have an idea, we can use the new template literal types:

```ts
export type Matcher = "~" | "|" | "^" | "$" | "*" | "";

export type AttributeMatcher = `${Matcher}=`;
```

So now we have two types. `matcher` can start with type `Matcher` and when we do the concatenation we can cast it to `AttributeMatcher`. How does it sound? It's not the best but we can narrow down the type from `string` to `Matcher`

2021-01-12 11:26 UTC, yeonjuan commented on internal/css-parser/parser/selectors.ts
> +	let matcher: string | undefined;
@ematipico 
Thanks, nice Idea 👍
but actually, the template literal type does not make type checking strong for concatenated string - [demo](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCyBDGBjAFsKOAXjgCIA-UuAHzOqttID0GyASV0gKk9IG4AUANCRYCZKgCCMGFACWAIwCuMYJhz5CJAAZsA3urwEAvkW2CBAG2DwAtliNQAXOgeaLcgGZwAFAEYASjg9AXsNAmIyfgFjOGBLAGdUELhUuDDHSO5otPS3CIBqElJPCFLyssrS6OMhbAgAOwSIawA6SwgAcx8MzQCLASA) It's a part where ts cannot handle well

Hmm. what about an user defined type guard ?
```ts
function isAttributeMatcher(value: string): value is AttributeMatcher {
	return ATTRIBUTE_SELECTOR_MATCHERS.includes(value);
}
```

2021-01-12 11:59 UTC, ematipico commented on internal/css-parser/parser/selectors.ts
> +	let matcher: string | undefined;
Sounds like a nice idea!

2021-01-19 09:18 UTC, ematipico approved these changes

2021-01-19 09:19 UTC, ematipico commented
Hi @yeonjuan if the PR is ready, could you please rebase it? After that, we can merge it

2021-01-19 11:11 UTC, yeonjuan commented
@ematipico  Thanks for the review:) I rebased it

2021-01-19 11:12 UTC, ematipico approved these changes

2021-01-19 11:12 UTC, merged