feat(css-formatter): support number and percentage
rome/tools pull request #1296
Opened 2021-01-13 16:55 UTC by yeonjuan

## Summary

## Test Plan

2021-01-13 17:12 UTC, yeonjuan commented on internal/formatter/builders/css/core/CSSPercentage.ts
> +	return concat([String(node.value), "px"]);
Wrong

2021-01-13 17:14 UTC, ematipico requested changes

2021-01-13 17:14 UTC, ematipico commented on internal/formatter/builders/css/core/CSSPercentage.ts
> +	return concat([String(node.value), "px"]);
I think the correct implementation should be `%`
```suggestion
	return concat([String(node.value), "%"]);
```

Also, we should implement a test, so we should add something like:
```css
width: 80%;
```

2021-01-13 17:16 UTC, yeonjuan commented on internal/formatter/builders/css/core/CSSPercentage.ts
> +	return concat([String(node.value), "px"]);
@ematipico Yes. right I found that while double check. Thanks 👍

2021-01-14 08:52 UTC, ematipico approved these changes

2021-01-14 08:52 UTC, merged