feat: add new internal/browsers-db
rome/tools pull request #1317
Opened 2021-02-03 01:30 UTC by jer3m01

## Summary
`internal/browsers-db` #1297

This adds a new internal package containing browser data, currently only contains data about css features.

The data is generated from caniuse.com using `scripts/generated-files/browsers-db.ts`
## Test Plan
`rome check --apply`

2021-02-03 18:06 UTC, ematipico requested changes
I left some feedback. Also, github doesn't allow me to comment on the big file as result.

Do you think it's worth save the file as `.ts` or should we consider a `.json` format?

2021-02-03 18:06 UTC, ematipico commented on scripts/generated-files/browsers-db.ts
> +	let regionsUsage = (<regionsFormat>{});
```suggestion
	let regionsUsage: RegionsFormat = {};
```

2021-02-03 18:06 UTC, ematipico commented on scripts/generated-files/browsers-db.ts
> +		const rawRegionUsage = await get<{
Could we move this inline type inside an interface?

2021-02-03 18:06 UTC, ematipico commented on scripts/generated-files/browsers-db.ts
> +	let regionsUsage = (<regionsFormat>{});
This could be a `Map`

2021-02-03 18:06 UTC, ematipico commented on scripts/generated-files/browsers-db.ts
> +			let temp = (<dataFormat["data"]>{});
This could be a `Map`

2021-02-03 18:06 UTC, ematipico commented on scripts/generated-files/browsers-db.ts
> +				let temp = (<usage>{});
This could be a `Map`. What do you think about having a better name? `temp` is not really a `temp` variable because we actually put data in there and we return it at the end.

2021-02-03 19:05 UTC, jer3m01 commented on scripts/generated-files/browsers-db.ts
> +			let temp = (<dataFormat["data"]>{});
`Pick<DataFormat, "data">` would resolve as
```ts
{
    data: Map<string, Feature>
}
``` 
where as `DataFormat["data"]` is
```ts
Map<string, Feature>
```

2021-02-03 22:08 UTC, ematipico commented on scripts/generated-files/browsers-db.ts
> +			let temp = (<dataFormat["data"]>{});
We would need to create an interface for that

2021-02-03 23:01 UTC, sebmck requested changes
Nice! I added some nits just around the package name and data validation.

I think updating the database and the generation of the files should be separate. Right now in order to generate the files we also need network access. I know you didn't add the script to `generate-all-files`, so it wont be ran in CI. But it'd be good to have this added there too.

We could have a separate `scripts/update-browser-feature-database` that actually does the fetching and writing to disk. And then `scripts/generated-files/browsers-db` can do any generation that actually needs to take place.

2021-02-03 23:29 UTC, jer3m01 commented on internal/browsers-db/README.md
> +# `browsers-db`
This package is just the data, there will be another package called `browser-features` that will convert this data into nice implementations. 
As discussed in #1297

2021-02-03 23:39 UTC, jer3m01 commented
@sebmck 
> We could have a separate `scripts/update-browser-feature-database` that actually does the fetching and writing to disk. And then `scripts/generated-files/browsers-db` can do any generation that actually needs to take place.

Can't really split it as this fetches the data from `Fyrd/caniuse` and strips it down. 
There are some modifications to reduce the size of the data such as using "undefined" (removing it form the json) instead of `"<version>": "n"` and using booleans for features that require a prefix since that's the only thing we care about.

The data is never written as fetched only kept in memory then modified.
If you see a way to split it into different steps tell me.

2021-02-04 00:41 UTC, jer3m01 commented
@ematipico Huge thanks for the the review, should all be done!

As for generating it as json instead of ts, last I tried `modifyGeneratedFile` didn't work with json files (can't put comments).

2021-02-07 17:10 UTC, jer3m01 commented
Got it to save as `.rjson` 🚀 

@ematipico @sebmck If everything is ok for you I'll merge it.

2021-02-07 19:41 UTC, ematipico approved these changes
Great addition to the codebase! There's an issue with `rome ci`.

2021-02-08 20:20 UTC, sebmck commented
Looks good to me! There's some small improvements with the data validation that can be done but I can do them in a follow up PR. Thank you @jer3m01!

2021-02-08 20:20 UTC, merged