feat: add new package internal/codec-browsers
rome/tools pull request #1364
Opened 2021-02-12 23:32 UTC by jer3m01

## Summary
`internal/codec-browsers` #1297

Package to parse target browser strings *à la* `firefox >= 84` into browser implementations.

## Todo

- [ ] Finish it

2021-03-02 09:28 UTC, ematipico reviewed
Amazing work here! Truly outstanding! Especially all the test fixtures! 

I left some suggestions.

Overall I would avoid things like

```js
parser.nextToken();
parser.nextToken();
```

Because it makes the parser a little bit too loose (and we don't want that inside a non-recoverable parser). I would use methods such as `eatToken` or `expectToken`. With these methods we are more explicit and help the developer and the parser to understand what tokens should be there.

If possible, I would break down some portions of code into small functions.

2021-03-02 09:28 UTC, ematipico commented on internal/codec-browsers/parse.ts
> +								| "LE",
Maybe we could create a new type out of them

2021-03-02 09:28 UTC, ematipico commented on internal/codec-browsers/parse.ts
> +				if (parser.lookaheadToken().type !== "In") {
We should avoid the usage of `lookaheadToken` as much as possible. The reason is because this function does a tokenization without moving forward with the parsing. Which we could be expensive.

2021-03-02 09:28 UTC, ematipico commented on internal/codec-browsers/parse.ts
> +					parser.nextToken();
What would happen if we don't have `Hyphen`? Should we have use `expectToken` instead? It matches a token and if does, it moves forward. If it doesn't match, it throws an error.

2021-03-02 09:28 UTC, ematipico commented on internal/codec-browsers/parse.ts
> +export function parseBrowserQuery(options: ParserOptions): AnyTargetBrowser[] {
This file has become really long. What do you think if we broke down various parts of  this function in small functions? e.g. `parseCover`, `parseLast`, etc.

If we use this approach, eventually we will be able to avoid the mutation `newTarget =` and return directly the object returned by these functions.

2021-03-02 09:28 UTC, ematipico commented on internal/codec-browsers/resolve.ts
> +	operator: "GT" | "LT" | "GE" | "LE";
Yeah we probably should make a new type out of this chars. We are repeating them inside a bunch of places. We could call it `Operator`.

```ts
export type Operator = "GT" | "LT" | "GE" | "LE";
```

2021-03-02 09:28 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/browserquery.ts
> +import {createDiagnosticsCategory} from "@internal/diagnostics";
We should add a full stop to all the sentences.

2021-03-03 12:59 UTC, ematipico approved these changes
Looks good! Great work again :)

2021-03-03 19:56 UTC, sebmck requested changes
This is awesome, thank you @jer3m01! Just have some small nits around the usage of `forEach` and null assertions. I was worried that my changes in #1384 would conflict, but there doesn't appear to be much overlap. I can rebase this for you once it's ready to merge if my PR lands before this.

2021-03-03 19:56 UTC, sebmck commented on internal/browser-features/Browser.ts
> +		).get(this.getId()).get(this.getVersion().toString()).asNumberOrVoid();
In #1384 I just added a new method to `Consumer` called `getPath` so in the future this could be simplified to:

```
return consumeUnknown(regions, DIAGNOSTIC_CATEGORIES.parse).getPath([region, "data", this.getId(), this.getVersion().toString()]).asNumberOrVoid();
```

2021-03-03 19:56 UTC, sebmck commented on internal/browser-features/index.ts
> +	});
No reason not to use `for of` here instead of `forEach`.

```suggestion
	for (const name of getAllBrowserNames()) {
		for (const version of getBrowser({name})!.getVersions()) {
			const browser = getBrowser({name, version})!;
			usages.push({
				id: browser.getId(),
				version,
				usage: region
					? browser.getRegionUsage(region) ?? 0
					: browser.getGlobalUsage(),
			});
		}
	}
```

2021-03-03 19:56 UTC, sebmck commented on internal/browser-features/index.ts
> +		getBrowser({name})!.getVersions().forEach((version) => {
I notice there's a lot of null assertions here around using the `getBrowser` method. Could we add another method called `getBrowserAssert` that always returns the type and throws if the browser doesn't exist?

We lose out on a lot of type safety and I believe the only places we currently use null assertions like this in Rome are around array methods (like `pop()`) that we're sure are being done on a populated array.

Alternatively it could be renamed to `getOptionalBrowser` and the assertion method could be called `getBrowser`. The `Assert` suffix is used throughout the codebase to refer to this kind of behaviour but both conventions are used so it's up to you.

2021-03-03 19:56 UTC, sebmck commented on internal/codec-browsers/README.md
> +Thanks to [browserslist ](https://github.com/browserslist/browserslist) for the idea and syntax.
```suggestion
Thanks to [browserslist](https://github.com/browserslist/browserslist) for the idea and syntax.
```

2021-03-03 19:56 UTC, sebmck commented on internal/diagnostics/descriptions/parsers/browserquery.ts
> +import {createDiagnosticsCategory} from "@internal/diagnostics";
I don't think there should be full stops. We don't currently have good conventions on writing diagnostic message text, but we only use full stops when there's more than one sentence, and that's rare as I try to break up additional context into additional `advice`.

2021-03-03 22:28 UTC, jer3m01 commented on internal/browser-features/Browser.ts
> +		).get(this.getId()).get(this.getVersion().toString()).asNumberOrVoid();
Awesome! I'll change that once you merge #1384.

2021-03-03 23:38 UTC, jer3m01 commented on internal/browser-features/index.ts
> +		getBrowser({name})!.getVersions().forEach((version) => {
I'll just throw an error on the base function as I can't see anywhere I would use it without checking if its undefined.

2021-03-06 19:49 UTC, merged

2021-03-06 19:49 UTC, sebmck commented
Awesome, thank you @jer3m01! This is a great addition 💃🏻