chore: add codeowners file
rome/tools pull request #1386
Opened 2021-03-04 16:47 UTC by ematipico

## Summary

Closes #1089 

I filled the file with the latest information left in that PR, plus I added the new core contributors based on their last area of work. 

I'd like to have some feedback about the format. Later on, we could add/modify sections based on our needs.

@yeonjuan @jer3m01 @sebmck could you please review it?

## Test Plan

CI

2021-03-04 17:47 UTC, jer3m01 requested changes
Good for me, one to add.

2021-03-04 17:47 UTC, jer3m01 commented on CODEOWNERS
> +/internal/browser-db/* @jer3m01
Can also add me to `codec-browsers`

2021-03-07 00:15 UTC, sebmck commented
Looks good to me! Why so many newlines though?

2021-03-07 10:39 UTC, ematipico commented
> Looks good to me! Why so many newlines though?

Thought it was more readable. Just changed it

2021-03-07 10:39 UTC, ematipico commented
The paths are not in alphabetical order

2021-03-07 14:02 UTC, jer3m01 approved these changes
Great! Just one small typo but everything looks good.

2021-03-07 14:02 UTC, jer3m01 commented on CODEOWNERS
> +/internal/code-js-manifest/* @ematipico
Forgot a `c` on codec.

2021-03-08 07:18 UTC, sebmck commented on CODEOWNERS
> +/internal/code-js-manifest/* @ematipico
```suggestion
/internal/codec-js-manifest/* @ematipico
```

2021-03-08 07:18 UTC, merged

2021-03-08 07:18 UTC, sebmck commented
Thanks @ematipico! Anyone feel free to PR any changes, including removing or adding yourself wherever.