feat(lint): noAccessKey for HTML & JSX
rome/tools pull request #1387
Opened 2021-03-06 04:29 UTC by mainangethe

## Summary

Implements #1345 

Ported the rule `noAccessKey` to the new category `a11y`
- Migrated the JXS linting rules
-  Added HTML rules

## Test Plan

- Migrated the existing JSX tests
- Added HTML tests
- Confirmed `./rome tests & ./rome ci` passes

2021-03-06 08:10 UTC, ematipico requested changes
Looks good. Just one small thing

2021-03-06 08:10 UTC, ematipico commented on internal/compiler/lint/rules/a11y/noAccessKey.test.rjson
> +	"<input accesskey='key />"
This is not valid HTML. If you check the snapshot, there's a parse error. We should just remove it, it's not needed.

2021-03-06 13:41 UTC, mainangethe commented on internal/compiler/lint/rules/a11y/noAccessKey.test.rjson
> +	"<input accesskey='key />"
Kept it in the JSX side, removed it in the HTML side of things..

2021-04-02 10:43 UTC, ematipico commented
Hi @mainangethe , any chance to get this merged?

2021-04-27 09:37 UTC, ematipico commented
@mainangethe I am going to close this PR in favour of #1442 

I cherry picked your commits, so your changes are still visible.

2021-04-27 09:37 UTC, closed without merging