feat(css-prefix): cursor support
rome/tools pull request #1457
Opened 2021-05-06 13:55 UTC by ktfth

## Summary

Included cursor on the css-prefix

## Test Plan

rome test internal/compiler/transforms/compile/index.test.ts --update-snapshots

2021-05-06 16:10 UTC, ematipico commented
@jer3m01 is it correct to have a prefix rule that doesn't create any prefix? Like in this case.

2021-05-06 19:22 UTC, jer3m01 commented
For `cursor` the values are prefixed:

![image](https://user-images.githubusercontent.com/33844379/117353595-99a2ea00-aeb0-11eb-988e-2387d32f2d86.png)

https://github.com/postcss/autoprefixer/blob/main/data/prefixes.js#L538-L554

You can have a look at https://github.com/rome/tools/blob/main/internal/compiler/transforms/compile/css-handler/prefix/prefixes/display.ts which prefixes values.

2021-05-06 21:09 UTC, jer3m01 requested changes
There's a simpler way then using a condition to find the browserFeaturesKey, linked an example in the review and to prefix values `prefixCSSValue` should be used, hope this is clearer.

2021-05-06 21:09 UTC, jer3m01 commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/cursor.ts
> +export default ["zoom-in", "zoom-out", "grab", "grabbing"].map((value) => {
`zoom-in` and `zoom-out` have a different key from `grab` and `grabbing`, a better example of how this should be done is https://github.com/rome/tools/blob/main/internal/compiler/transforms/compile/css-handler/prefix/prefixes/transform.ts.
With `prefixCSSValue` instead of `prefixCSSProperty`.

2021-05-06 21:11 UTC, jer3m01 requested changes

2021-05-06 21:11 UTC, jer3m01 commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/cursor.ts
> +				return prefixCSSProperty({
`prefixCSSValue` should be used to prefix values instead of `prefixCSSProperty`.

2021-05-06 21:35 UTC, ktfth commented
@jer3m01 Updated following your guidance, thank you

2021-05-06 21:43 UTC, jer3m01 requested changes
Great! Just missing tests and one can be removed.

2021-05-06 21:43 UTC, jer3m01 commented on internal/compiler/transforms/compile/test-fixtures/css-handler/prefix/cursor/input.test.md
> +	cursor: none;
Could you add test cases for zoom-in, zoom-out, grab and grabbing

2021-05-06 21:43 UTC, jer3m01 commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/cursor.ts
> +	}),
Manually checked the data and it doesn't seem to do anything for rome, this can be removed.

2021-05-06 22:16 UTC, ktfth commented
@jer3m01 New modification following your review comments, check it out

2021-05-07 18:42 UTC, jer3m01 approved these changes
Awesome! One last thing, could you run `./script generated-files/css-prefix` to fix the CI.

2021-05-07 18:45 UTC, ktfth commented
> Awesome! One last thing, could you run `./script generated-files/css-prefix` to fix the CI.

Ok

2021-05-07 18:54 UTC, merged

2021-05-07 18:55 UTC, jer3m01 commented
Thanks!