feat(css-prefix): gradient support
rome/tools pull request #1471
Opened 2021-05-08 21:59 UTC by ktfth

## Summary

Included gradient on the css-prefix

## Test Plan

rome test

2021-05-08 23:25 UTC, jer3m01 requested changes
You can avoid duplicates (see review) and add missing tests.

2021-05-08 23:25 UTC, jer3m01 commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/gradient.ts
> +export default [
Instead of writing each one you can use `flatMap()` & `map()`:

```ts
export default [
		"background",
		"background-image",
		"border-image",
		"mask",
		"list-style",
		"list-style-image",
		"content",
		"mask-image",
	].flatMap((propertyName) => [
	    "linear-gradient",
	    "repeating-linear-gradient",
	    ...
	    ].map((value) => {
			   ...
			  prefixCSSValue({
					propertyName,
					value
				});
				...
		})
);

2021-05-08 23:25 UTC, jer3m01 commented on internal/compiler/transforms/compile/test-fixtures/css-handler/prefix/gradient/input.test.md
> +	gradient: none;
Can you add tests cases for all of them (might be long).

2021-05-09 15:15 UTC, ktfth commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/gradient.ts
> +export default [
Awesome, i can do that

2021-05-09 15:15 UTC, ktfth commented on internal/compiler/transforms/compile/test-fixtures/css-handler/prefix/gradient/input.test.md
> +	gradient: none;
Count with me

2021-05-18 23:01 UTC, jamiebuilds commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/gradient.ts
> +				});
We shouldn't quite merge this yet until `prefixCSSValue` works with complex css values such as the case with the `background` shorthand

2021-05-18 23:17 UTC, jer3m01 commented
Would have to dig in deeper as the list in the source (https://github.com/postcss/autoprefixer/blob/main/data/prefixes.js#L170-L194)
doesn't match with the output from autoprefixer.
Some are [defined](https://github.com/postcss/autoprefixer/blob/main/data/prefixes.js#L180) but not actually prefixed?:

![image](https://user-images.githubusercontent.com/33844379/118735009-d91dee80-b83f-11eb-94c5-11707c4850b7.png)

2021-05-18 23:31 UTC, ktfth commented
> Would have to dig in deeper as the list in the source (https://github.com/postcss/autoprefixer/blob/main/data/prefixes.js#L170-L194)
> doesn't match with the output from autoprefixer.
> Some are [defined](https://github.com/postcss/autoprefixer/blob/main/data/prefixes.js#L180) but not actually prefixed?:
> 
> ![image](https://user-images.githubusercontent.com/33844379/118735009-d91dee80-b83f-11eb-94c5-11707c4850b7.png)

I don't know exactly what this mean

2021-05-18 23:36 UTC, jer3m01 commented
> 
> I don't know exactly what this mean

No problem, this comment is more aimed towards me for later or others members of the team. 

Essentially the code says that they should be prefixed (as you've coded) but autoprefixer doesn't actually do it. Which is really strange, if anyone else has an explanation to why they're welcomed!

2021-09-22 22:56 UTC, jamiebuilds commented
Hi! Thank you so much for your contribution!

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. But while we're closing this, we'd love to have your involvement in the future.

Thanks again!

2021-09-22 22:56 UTC, closed without merging