feat(css-prefix): add unicode-bidi support
rome/tools pull request #1506
Opened 2021-05-17 14:06 UTC by imskr

## Summary

- Added `unicode-bidi` support
- Contributes to #1423 

## Test Plan

- `./rome test`

2021-05-17 15:41 UTC, ematipico requested changes
Thank you! Please check the CI, there's some problem. Launch the command `./rome ci` next time. `./rome test` is not enough.
Also, if you check the snapshot test, it didn't add any prefix. Are you use it's correct?

2021-05-17 21:08 UTC, alewin commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/unicode-bidi.ts
> +		name: `${propertyName}/unicode-bidi`,
`isolate`, `plaintext` and `isolate-override` are values, so probably it's better to have something like:
`unicode-bidi/${propertyValue}/`

2021-05-17 21:11 UTC, alewin commented on internal/compiler/transforms/compile/test-fixtures/css-handler/prefix/unicode-bidi/input.css
> +	unicode-bidi: isolate;
it would probably be better to have the other two cases as well: `unicode-bidi: isolate-override;` and `unicode-bidi: plaintext;` and run again `rome test internal/compiler/transforms/compile/index.test.ts --update-snapshots` to update the test-snapshots

2021-05-18 03:41 UTC, imskr commented
@ematipico The discord link in contributing.md file is expired. Can I get the new link?

2021-05-18 05:28 UTC, ematipico commented
> @ematipico The discord link in contributing.md file is expired. Can I get the new link?

Use the one from the website ;)

2021-05-18 06:10 UTC, imskr commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/unicode-bidi.ts
> +		name: `${propertyName}/unicode-bidi`,
Thanks

2021-05-18 06:10 UTC, imskr commented on internal/compiler/transforms/compile/test-fixtures/css-handler/prefix/unicode-bidi/input.css
> +	unicode-bidi: isolate;
Thanks

2021-05-18 07:02 UTC, imskr commented
@ematipico I'm following the correct steps but I'm not getting the correct test output

2021-05-18 07:43 UTC, ematipico commented
@imskr I strongly suggest to check how other existing rules are implemented. Your rule is not correct: https://github.com/rome/tools/blob/main/internal/compiler/transforms/compile/css-handler/prefix/prefixes/image-set.ts

2021-05-18 07:45 UTC, ematipico requested changes

2021-05-18 07:45 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/unicode-bidi.ts
> +	propertyValue,
`propertyValue` doesn't exist. You're calling `.map` on an array of string, so you have only `propertyName`, which contains the single values: "isolate", "plaintext", etc.

2021-05-20 07:16 UTC, imskr commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/unicode-bidi.ts
> +	propertyValue,
Like this @ematipico :
```ts
import {
	createPrefixVisitor,
	prefixCSSValue,
} from "@internal/compiler/transforms/compile/css-handler/prefix/utils";

// https://github.com/Fyrd/caniuse/blob/main/features-json/css-unicode-bidi.json
export default ["isolate", "plaintext", "isolate-override"].map((
	propertyName
) =>
	createPrefixVisitor({
		name: `${propertyName}/unicode-bidi`,
		enter(path) {
			return prefixCSSValue({
				path,
				propertyName,
				value: "unicode-bidi",
				browserFeaturesKey: "css-unicode-bidi",
			});
		},
	})
);
```

2021-05-20 07:17 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/unicode-bidi.ts
> +	propertyValue,
Yes, give it a try

2021-05-20 07:17 UTC, imskr commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/unicode-bidi.ts
> +	propertyValue,
This also doesn't update the test snapshot

2021-05-20 07:23 UTC, imskr commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/unicode-bidi.ts
> +	propertyValue,
output not matching from autoprefixer

2021-05-21 09:56 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/unicode-bidi.ts
> +	propertyValue,
That's because `unicode-bidi` is not present inside `browsers-db/data.json`. I will try to update the data and see it's there.

2021-05-21 10:01 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/unicode-bidi.ts
> +	propertyValue,
For now, leave this PR on idle; I suggest to focus on some other property in the meantime.

2021-05-21 13:14 UTC, imskr commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/unicode-bidi.ts
> +	propertyValue,
okay

2021-09-22 22:58 UTC, jamiebuilds commented
Hi! Thank you so much for your contribution!

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. But while we're closing this, we'd love to have your involvement in the future.

Thanks again!

2021-09-22 22:58 UTC, closed without merging