WIP: feat(cli): interactive yes/no and suggestion selection for cli commands
rome/tools pull request #1508
Opened 2021-05-17 22:25 UTC by UsamaHameed

## Summary
This pr resolves #974. 

## Test Plan

1. `rome chekc` suggests the following and the user can interactively select one
```
❯ Unknown command. Found matching commands: 
ℹ Use arrow keys and then enter to select an option
  ◉ check
  ◯ cache dir
  ◯ cache clear
```

2. `rome losg` suggests `rome logs` and the user can choose to execute `rome logs` or not
```
❯ Did you mean logs
ℹ Use arrow keys and then enter to select an option
  ◉ No (shortcut n)
  ◯ Yes (shortcut y)
```

3. throws error if it can't find a relevant match.

```
argv:1:9 flags/invalid  FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Unknown command kjsahdaslkjdlkasjdlksajldjkaslkdjalskjda

    dev-rome kjsahdaslkjdlkasjdlksajldjkaslkdjalskjda
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  ℹ To see all available commands run

    dev-rome --help

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

```

2021-05-18 23:22 UTC, jamiebuilds commented
The double `: : check` here looks weird. Is it supposed to be removing the line entirely?

![Screen Shot 2021-05-18 at 4 21 16 PM](https://user-images.githubusercontent.com/952783/118735354-1dd06800-b7f5-11eb-8745-aa5b637f220a.png)

2021-05-19 14:46 UTC, ematipico requested changes
Nice PR! I left few comments around code/logic

2021-05-19 14:46 UTC, ematipico commented on internal/cli-reporter/Reporter.ts
> +				stdin: process.stdin,
I don't think this is the correct approach. `Reporter` has already a `private stdin` (line 138) and it has a method called `getStdin`. We should use that one.

2021-05-19 14:46 UTC, ematipico commented on internal/cli-flags/Parser.ts
> +				});
We try to stay away from this syntax. We always use `for..of` when dealing with iterators.

2021-05-19 14:46 UTC, ematipico commented on internal/cli-flags/Parser.ts
> +				});
BTW, you could use `.reduce`, which seems to be a better fit

2021-05-19 14:46 UTC, ematipico commented on internal/cli-flags/Parser.ts
> +					markup`Unknown command. Found matching commands: `,
```suggestion
					markup`Unknown command <emphasis>${commandName}</emphasis>. Found matching commands: `,
```

2021-05-19 14:46 UTC, ematipico commented on internal/cli-flags/Parser.ts
> +				}
What would happen if the user didn't confirm?

2021-05-19 14:48 UTC, ematipico commented on internal/cli-flags/Parser.test.ts
> +			return new Promise((resolve) => resolve(res as any));
```suggestion
			return Promise.resolve(res as any)
```

2021-05-19 14:49 UTC, ematipico commented on internal/cli-flags/Parser.test.md
> +## `command required with wrong command and suggestion`
I think the tests are a bit off

2021-05-19 17:42 UTC, jamiebuilds commented on internal/cli-flags/Parser.ts
> +				});
Personally I dislike `Array#reduce` I think it makes code unnecessarily confusing only to avoid local mutation which I think is perfectly fine

2021-05-19 17:43 UTC, jamiebuilds commented on internal/cli-flags/Parser.ts
> +				}
Should probably fall back to `throw new DiagnosticsError("Unknown command", [diag]);`

2021-05-19 17:57 UTC, UsamaHameed commented on internal/cli-reporter/Reporter.ts
> +				stdin: process.stdin,
@ematipico that stdin field is what I am defining with `process.stdin` through the constructor when creating a `Reporter` on line 150. This reporter is returned by the `fromProcess` static method inside the Reporter class.

2021-05-19 17:59 UTC, UsamaHameed commented on internal/cli-flags/Parser.ts
> +				});
I avoided `reduce` for the same reason. I don't mind using it if thats what we follow. I like `for of` as well.

2021-05-19 18:01 UTC, UsamaHameed commented
> The double `: : check` here looks weird. Is it supposed to be removing the line entirely?
> 
> ![Screen Shot 2021-05-18 at 4 21 16 PM](https://user-images.githubusercontent.com/952783/118735354-1dd06800-b7f5-11eb-8745-aa5b637f220a.png)

The `confirm` method on `Reporter` does not clear the line but I can remove that double `:`

2021-05-19 18:01 UTC, ematipico commented on internal/cli-flags/Parser.ts
> +				});
Then, we should switch to `for..of` 💪

2021-05-20 16:45 UTC, UsamaHameed commented on internal/cli-flags/Parser.test.md
> +## `command required with wrong command and suggestion`
These snapshots only capture diagnostic output, if there is none, the `Output` is empty. I don't know how much value do those tests provide us.

2021-05-21 09:45 UTC, ematipico approved these changes

2021-05-25 13:58 UTC, UsamaHameed commented
@jamiebuilds I have applied the suggestions. Please let me know if I can apply further improvements. 🙏

2021-06-10 10:33 UTC, ematipico commented
@jamiebuilds This looks good to me. Could you please do a last check? I think we can merge it.

2021-06-10 15:14 UTC, merged