WIP: feat(css-prefix): pseudo-classes
rome/tools pull request #1522
Opened 2021-05-20 16:13 UTC by JustBeYou

## Summary

Related to issue #1423

## Test Plan

2021-05-24 09:40 UTC, ematipico requested changes
Thank you for the PR! I left some comments and questions. I'm still not sure where we're heading though. I think this refactor makes sense but these are not utils anymore. I think we should start thinking to implement a compiler context for CSS and handle there the state. Not part of this PR of course, just putting my thoughts here.

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +export function __visitorTransformer<
Is there a reason why put a double underscore in  the name of this function?

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +export interface PrefixCSSRootVisitor<State extends UnknownObject> extends __TypedVisitor<
I would suggest to start creating a type for this `State`. We could call it `CompilerPrefixerState`

```ts
export type CompilerPrefixerState = UnknownObject;
```

And replace all the occurrences where we have `State extends UnknownObject`

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +	return selector.patterns.reduce(
We are trying to stay away from `.reduce`. Let's use `for..of`.

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +) {
I think using an object is way better than passing four arguments:
- order doesn't matter
- easily extendable

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +) {
I think using an object is way better than passing four arguments:
- order doesn't matter
- easily extendable

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +function prefixCSSRule(
This function prefixes the `prelude` of the rule, so maybe it's worth changing its name? `prefixCSSRulePrelude`?

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +	const newSelectors = rule.prelude.map((selector) =>
`newPrelude`?

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +) {
Could you add the return type please?

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +export function prefixPseudoInCSSRoot(
I don't understand this function. Why do we need to replace the entire root node?

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +	return rule.prelude.reduce(
We can avoid `.reduce` here. If we're worried about possible duplicates, we can create a new `Set` at the very end of the function by giving it an array where we accumulates all the prefixes.

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +	const newValue = [];
We should type this guy. Inside `internal/ast/css/unions.ts` we can create a new type called `CSSBlockValue`:

```ts
export type CSSBlockValue =  Array<AnyCSSValue | CSSRule | CSSAtRule | CSSDeclaration>;
```

Use it inside `internal/ast/css/core/CSSBlock.ts` where we have the `value` property.

And use it to type it:

```ts
const newValue: CSSBlockValue = []
```

2021-05-24 09:40 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +	if (newValue.length !== path.node.value.length) {
`newValue.length` will always be equals or greater than `path.node.value.length`. Perhaps we should narrow down the condition to `>`?

2021-05-25 05:47 UTC, JustBeYou commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +export function __visitorTransformer<
To remember that I did not like the naming so I would change it later :joy: Also, I had the same feeling that those are not utils anymore. 
I think after making this feature work we could think to move the code away from `utils`? I could do a PR afterward

2021-05-25 05:50 UTC, JustBeYou commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +export function prefixPseudoInCSSRoot(
`CSSRoot` contains multiple `CSSRules`. When prefixing we end up with newly generated rules. Is there any other way to add them to the root node than to replace it?

2021-05-25 05:51 UTC, JustBeYou commented
For the rest of the comments (where I did not reply), I will simply do the requested changes as it looks totally fine to me.

2021-05-25 08:25 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +export function prefixPseudoInCSSRoot(
I think it's just sufficient to return `siglan.replace(newPrelude)` when you need to add new prefixes to a selector. That's what we do inside lint rules where we apply an autofix: we just tell to the compiler, using a signal, to "replace this specific node". The compiler does the rest.

2021-05-25 10:28 UTC, JustBeYou commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +export function prefixPseudoInCSSRoot(
@ematipico Well, I'm not really sure it's that simple. If we replace only the prelude this would be an example result:
```
/* input */
.example:any-link {}

/* output */
.example:any-link:-moz-any-link:-webkit-any-link {}
```

And I think that the correct output should be (that's what autoprefixer does too):
```
.example:any-link {}
.example:-moz-any-link {}
.example:-webkit-any-link {}
```

Am I missing something?

2021-05-25 10:30 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +export function prefixPseudoInCSSRoot(
Ooooooh I see now! I completed missed that part! Yes it makes total sense now! Thank you for your answer

2021-06-08 13:38 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +) {
Return type is missing

2021-06-08 13:38 UTC, ematipico commented on internal/compiler/transforms/compile/test-fixtures/css-handler/prefix/pseudo-selectors/input.css
> +/* Single pseudo selectors */
What do think if we moved every category of selectors in their own test file? The reason I am suggesting is because it's really difficult to keep track of what's changed and if that's correct. What I would suggest: 

```
- `pseudo-selectors/`
--- `single/`
------ `input.css
--- `multiple-classes/`
------ `input.css
--- `multiple-elements/`
------ `input.css`
```

2021-06-08 13:38 UTC, ematipico commented on internal/compiler/transforms/compile/test-fixtures/css-handler/prefix/pseudo-selectors/input.test.md
> +}
In this case we should prefix only once, ideally. 

Also, do you think it would be possible to change from:

```css
.example6:any-link {
	width: 10px;
}
.example6:-moz-any-link {
	width: 10px;
}
.example6:-webkit-any-link {
	width: 10px;
}
```
To

```css
.example6:any-link,
.example6:-moz-any-link,
.example6:-webkit-any-link {
	width: 10px;
}
```

2021-06-08 15:54 UTC, JustBeYou commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +			return new Set([...prefixes].filter((x) => allowedPrefixes.has(x)));
That's the proposed way of intersecting sets in MDN, but now looking closer I think it's just useless. I'll remove it.

2021-06-08 15:59 UTC, JustBeYou commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +	array: AnyNode[],
I tried to do this but TS compiler was not so cooperative. The thing is I am applying these rules to two kinds of arrays:
1. `(CSSRule | CSSAtRule)[]` for `CSSRoot`
2. `CSSBlockValue` which is a long union of types
I couldn't find a way to define a type like: `Array<thing that inherits AnyNode | CSSRule>` and work with both `CSSBlockValue` and the other. I saw something about conditional type inference, so I could extract the type of any array and extend it but it looked complicated.

Do you have any idea or should I look at the inference thing?

2021-06-08 16:02 UTC, JustBeYou commented on internal/compiler/transforms/compile/test-fixtures/css-handler/prefix/pseudo-selectors/input.test.md
> +}
Not quite. If a rule is duplicated there's a big chance that the content itself is not duplicated and it's either a programming mistake or a choice. I've seen this before (it's not a good practice but some programmers still do this). I think we should focus on not having duplicated CSS rules in another feature (probably a rome lint rule), not here. What do you think?

2021-06-08 16:02 UTC, JustBeYou commented
The comments I did not respond to I will simply change.

2021-06-08 16:06 UTC, JustBeYou commented on internal/compiler/transforms/compile/test-fixtures/css-handler/prefix/pseudo-selectors/input.test.md
> +}
About the style change: maybe it would be useful to do the same everywhere? I think this will simplify the code. Initially, I was thinking that throwing all the prefixed selectors in the same rule looks ugly but maybe it's not that bad. What do you think?

2021-06-11 14:29 UTC, JustBeYou commented on internal/compiler/transforms/compile/css-handler/prefix/utils.ts
> +			return new Set([...prefixes].filter((x) => allowedPrefixes.has(x)));
`prefixes` is a set. `[...prefixes]` is the short form of `Array.from(prefixes.values())` so I could use `.filter()`

2021-06-11 14:31 UTC, JustBeYou commented on internal/compiler/transforms/compile/test-fixtures/css-handler/prefix/pseudo-selectors/input.test.md
> +}
Solved on discord.

2021-06-11 16:17 UTC, ematipico approved these changes

2021-06-11 16:18 UTC, merged

2021-06-11 16:18 UTC, ematipico commented
Amazing PR! Thank you very much, that was a huge contribution!