feath(css-parser): import
rome/tools pull request #1536
Opened 2021-06-07 17:17 UTC by ktfth

## Summary

Implementation of css import

## Test Plan

./rome test

2021-06-07 20:47 UTC, jamiebuilds requested changes

2021-06-07 20:47 UTC, jamiebuilds commented on internal/css-parser/test-fixtures/import/input.test.md
> +				CSSSelector {
Why are all of these being parsed as `CSSSelector`s?

2021-06-07 20:47 UTC, jamiebuilds commented on internal/css-parser/test-fixtures/import/input.css
> +}
Why the `@supports` in this file?

2021-06-07 20:47 UTC, jamiebuilds commented on internal/css-parser/parser/at-import.ts
> +// https://www.w3.org/TR/css-cascade-4/#conditional-import
Looks like there are a bunch of missing imports in these files

2021-06-07 21:08 UTC, ktfth commented on internal/css-parser/test-fixtures/import/input.test.md
> +				CSSSelector {
I'm not founded the command to create tests and I have created manually

2021-06-07 21:09 UTC, ktfth commented on internal/css-parser/test-fixtures/import/input.css
> +}
I'm gonna remove that

2021-06-07 21:10 UTC, ktfth commented on internal/css-parser/parser/at-import.ts
> +// https://www.w3.org/TR/css-cascade-4/#conditional-import
Working on that

2021-06-08 10:33 UTC, ematipico requested changes
Thank you for your PR!

There are some things to review, I try to write all of them here:

- ~the PR is not ready yet, I would suggest move it to a "draft" state~ (I did myself)
- to properly start seeing what want to implement, create a file called `test.css` in the root of the project and put a simple CSS that you want to start parsing. Run the command `./rome parse test.css --tokenize` to see all the tokens that belong to the syntax inside your file;
- to start parsing the new rule, you need to understand **where** to start parsing the specific new syntax; the place is [here](https://github.com/rome/tools/blob/main/internal/css-parser/parser/rules.ts#L108-L132)

You should add a new `if` to check against the work `"import"`. Inside the new check, we can call you new function `parseAtImport` and start your new parsing.

- once you're happy with your implementation, you can run the command `./rome parse test.css` (without `--tokenize`). This command will print in command line the AST of your input file. Use this command to verify that your code is correct;

- for tests, use the command `./rome test ./internal/css-parser/index.test.ts`; add `--update-snapshots` when you need to update the snapshots of your tests. Inside `css-parser` folder there's a folder called `test-fixtures`. The way it works is that you want to create a folder with a file called `input.css` and add the cases you want to test. Run the `test` command and it will automatically create the snapshot test. No need to create it yourself (you can delete the one you created)

2021-06-08 10:33 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +	const token = parser.expectToken("AtKeyword");
We should not use `.expectToken` because it throws an hard error. If you need to check the existence of token, use `matchToken` and use `parser.unexpectedDiagnostic`

2021-06-08 10:33 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +		}
Does `"keyframes"` exist inside the official spec? I didn't see it. If it's not supported, we should remove it

2021-06-08 10:33 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +		}
`"font-face"` doesn't exist inside `@import`, we should remove it

2021-06-08 10:33 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +		}
I don't think `"page"` is inside the `@import` rule. We should remove it.

2021-06-08 10:33 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +		}
There aren't any blocks inside `@import` syntax, we should remove it.

2021-06-08 10:33 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +): CSSAtImport {
This function should return `undefined` too.

2021-06-08 10:33 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +	while (true) {
I don't think a loop is needed. The spec doesn't says there could be multiple values of the same token: there's only one "supports" or  one "url" or one "string":

```
@import [ <url> | <string> ]
        [ supports( [ <supports-condition> | <declaration> ] ) ]?
        <media-query-list>? ;
```

I'd suggest to read again the spec and try to understand every bit of it.

2021-06-08 10:33 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +			break;
In case of errors we should exit from the function and return `undefined`. That's how we do it inside the rest of the functions.

2021-06-09 22:36 UTC, jamiebuilds commented on internal/css-parser/test-fixtures/import/input.test.md
> +	]
This is all valid CSS code and shouldn't have any diagnostics

2021-06-10 10:15 UTC, ematipico requested changes
The changes are better than before! Thank you! There's still some work to do though. I left some comments.

What I **strongly suggest** is to **test manually your changes before creating the tests**. Running `./rome parse test.css` with some code sample is enough to make sure that your code is correct or not.

2021-06-10 10:15 UTC, ematipico commented on internal/ast/css/unions.ts
> +export type CSSAtImportValue = string[] | CSSUrlFunction;
The spec doesn't expect an array of strings. Probably the square bracket in the spec confused you. [Check this link](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#formal_syntax). If you click on the square bracket, it brings you to the explanation. 

It should be only a `string`

2021-06-10 10:15 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +	let token = parser.getToken() as Tokens["String"];
You don't need to do a cast with `as`. It's not needed.

2021-06-10 10:15 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +		return parser.finishNode(
Before calling `parser.finishNode`, you need to advance with the position, this means that you need to call `nextToken`:

```js
nextToken(parser);
return parser.finishNode();
```

This is needed so the parser can correctly determine the end location of the node.

2021-06-10 10:15 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +		value = [token.value];
As pointed out, value needs to be a normal string.

2021-06-10 10:15 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +	return undefined;
We can't return `undefined` without creating a diagnostic. If we arrive here it means that something went wrong. We need to tell the user why. Remember that these diagnostic will appear also on the VSCode plugin, which means we have to be careful about developer experience too.

2021-06-10 10:15 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +		token = parser.getToken() as Tokens["String"];
Don't override a previous variable. Create a new one.

You can't use a cast here. It's really unsafe, why? Because you cheat the compiler and yourself to expect a token that probably would be wrong.

Take the following example:

```css
@import url(3);
```

`3` in this case is not a `"String"` token. This means that the following code should be like this:

```js
const functionArgumentToken = parser.getToken();

if (functionArgumentToken.type === "String") {
	nextToken(parser);
	return parser.finishNode();
}
parser.unexpectedDiagnostic({
	description: descriptions.CSS_PARSER.AT_IMPORT_INVALID_ARGUMENT, // we need to create this diagnostic,
	token: functionArgumentToken
});
return undefined;
```

2021-06-10 10:15 UTC, ematipico commented on internal/formatter/builders/css/import/CSSAtImport.ts
> +	return JSON.stringify(node.value);
We have to create a test also for this. The way formatters tests are created and executed are the same of the CSS parser. You can follow the same process.

2021-06-10 10:16 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +	let token = parser.getToken() as Tokens["String"];
It should be `const token`

2021-06-10 15:37 UTC, ktfth commented on internal/formatter/builders/css/import/CSSAtImport.ts
> +	return JSON.stringify(node.value);
I have created the tests and running then they not passed with this error:

"Expected a left curly bracket {"

Can you help me understand that?

2021-06-10 15:45 UTC, ematipico commented on internal/formatter/builders/css/import/CSSAtImport.ts
> +	return JSON.stringify(node.value);
It means there's an issue while while parsing the CSS you put inside the test fixture. You will be able to see more information if you try to parse the code using `./rome parse` command.

2021-06-11 13:11 UTC, ematipico requested changes

2021-06-11 13:11 UTC, ematipico commented on internal/css-parser/parser/at-import.ts
> +		value = token.value;
This is not correct. In this case `value` should be a `CSSFunction`. Remember the type `CSSAtImport`. Its value is `export type CSSAtImportValue = string | CSSUrlFunction;`

This is the case where we need a function

```js
const functionStart = parser.getToken();
nextToken(parser);
value = parser.finishNode(functionStart, {
	type: "CSSUrlFunction",
	name: "url",
	params: [token.value]
});
```

2021-06-11 13:11 UTC, ematipico commented on internal/css-parser/test-fixtures/import/input.test.md
> +		}
@ktfth please check also this fixtures when you generate them. Did you notice that we lost information here? `"something.css"` is not there anymore.

2021-06-11 17:32 UTC, jamiebuilds commented
FYI I've updated the base branch of this PR to a feature branch that other work can be merged into

2021-06-11 17:47 UTC, merged

2021-06-11 17:47 UTC, ematipico commented
Thank you for your contribution!