WIP: feat(resolver): support for path aliases
rome/tools pull request #1569
Opened 2021-06-15 22:06 UTC by JustBeYou

## Summary
Fix for #1555 . I've implemented "naive" support for aliases. It allows only one wildcard at the end of the pattern (eg. `some/path/*`). Probably it would be nice to support almost any glob-like expression but I think the effort and performance impact is not worth it. Also, in Typescript's documentation, there are no examples of a more complex expression. 

I'm waiting for a review of this draft. If it is ok, I think we could add some caching and improve where the code is placed. After that I will also implement the `auto-configuration`.

## Test Plan
I added some integration tests for the resolver, enabled them temporarily and tested the new feature.

2021-06-15 22:19 UTC, JustBeYou commented
Note: When resolving aliased paths we need to set `origin` to the root path of the project, otherwise it won't work as expected. I couldn't yet find a way to get the root of the project btw.

2021-06-15 23:38 UTC, jamiebuilds commented
Here's the actual documented code for how TypeScript's `"paths"` patterns work: https://github.com/microsoft/TypeScript/blob/6bb1f0792ba19b662ac0384ad1db824c5de43bd3/src/compiler/moduleNameResolver.ts#L880-L939

2021-06-16 10:31 UTC, ematipico requested changes

2021-06-16 10:31 UTC, ematipico commented on internal/project/load.ts
> +		base: b.base,
I would create an object called `aliases`, and there we can have `paths` and `base`.

Doing so, would allow us to correctly doing a merge like:

```js
aliases: {
	...a.aliases,
	...b.aliases
}
```

And we are aligned with the rest of the configurations

2021-06-16 10:31 UTC, ematipico commented on internal/project/load.ts
> +		paths: [...a.paths, ...b.paths],
To merge two arrays, you can use the function `mergeArrays`. Although don't do it here, apply the merge strategy inside the function `extendProjectConfig`

2021-06-16 10:31 UTC, ematipico commented on internal/project/load.ts
> +		paths: [...a.paths, ...b.paths],
I think the merging strategy should be more accurate.

Let's say we have something like:

```
"@components" => ["./a" "./b"],
"@components" => ["./a", "./c"]
```

It should result in:

```
"@components" => ["./a" "./b", "./c"],
```

If we just spread, we lose at least one mapping ("./b" or "./c" depending on the order of the merging)

2021-06-16 10:31 UTC, ematipico commented on internal/project/utils.ts
> +		throw new Error("Empty path aliases are not allowed.");
Errors should be throw in a different way. In order to do that, other than passing `path`, pass also the `Consumer`.

When you have an error, you can do:

```js
throw consumer.unexpected();
```

The consumer is returned by the `.asMap` method, which was `targets`.

Alternatively, you can wrap your function like this:

```js
consumer.handleThrownDiagnostics(() => {
	parsePathAliasPattern();
})
```

I would go for the first solution though, because you will need to throw `DiagnosticError` anyway, which is something that `consumer.unexpected` already does.

As thumb rule, never throw a `Error` inside Rome unless we are inside some internals (the binary transport for example)

2021-06-16 10:31 UTC, ematipico commented on internal/project/utils.ts
> +		throw new Error(`Too many wildcards in ${path}`);
When creating a diagnostic, as pointed out in the previous comment, let's try to advice the developer with possible solutions. In this way, we improve also the developer experience. We should always offer a way to fix bugs.

2021-06-16 10:31 UTC, ematipico commented on internal/project/utils.ts
> +		return path === pattern.parts[0] ? path : undefined;
Should we save `pattern.parts[0]` and `pattern.parts[1]` in some variable? We avoid accessing to those vars too many times.

2021-06-16 10:31 UTC, ematipico commented on internal/core/server/fs/Resolver.ts
> +				for (const aliasPath of this.getAliasedPaths(query, project.config)) {
Here we could only pass `aliases` instead of the whole project configuration. Or, directly `project.config.aliases.base`.

2021-06-16 11:14 UTC, JustBeYou commented on internal/project/utils.ts
> +		throw new Error("Empty path aliases are not allowed.");
I did not know how to handle diagnostics and I was expecting that someone will point me in the right direction. Thank you!

2021-06-17 11:25 UTC, JustBeYou commented on internal/project/load.ts
> +		aliases.enforceUsedProperties("aliases config property");
I don't know if this is necessary or not but I see it is used everywhere. If it should be removed please tell me.
Also, it would be nice if you could tell me what's this function used for :)

2021-06-18 15:22 UTC, ematipico commented on internal/project/load.ts
> +		aliases.enforceUsedProperties("aliases config property");
This function should be used yes. And it makes sure that the properties that belong to a mapped object are actually used.

For example, in your case, we have `paths` and `base` inside `aliases`. If we use `asMap` and decided to use only `base` - and ignore `paths`, this function will throw an error saying that `paths` hasn't been used.

It makes sure that all the configuration is actually parsed, used and passed to Rome's internals.

2021-06-20 23:06 UTC, JustBeYou commented
I've been thinking about how should `auto-config` handle path aliases but I couldn't really decide on something. I have the following options in my mind:
1. Check if there are custom aliases configured, if yes check if there is any `tsconfig.json`. If it does not exists, suggest creating it. If it exists and the aliases differ from Rome's configuration, suggest changing it.
2. Add a proper way of handling `tsconfig.json` that would allow auto-fixes. Something similar to what Rome is already doing for `package.json` (I see that it is already managed)

Personally, I think implementing 1 as a dirty fix or leaving `auto-config` out of the discussion, for now, would be ok. I think implementing 2 should be done in a different PR. 

@ematipico @jamiebuilds I'd be glad to know what you two think.

2021-06-21 10:04 UTC, ematipico commented
Honestly, I wouldn't put too much work around `tsconfig.json`. It shouldn't be put at the same level of `package.json`.

What I would expect from `auto-config` is the following:
1. check existence of `tsconfig.json`;
2. if not present, bail without saying nothing to the user; if present, confirm with the user that following "a", "b", etc. aliases will be imported. (if they exist) 

Other properties will be handled via official integration (like prettier and eslint).

2021-06-22 09:41 UTC, JustBeYou commented
I've added autoconfiguration. The only problem is that if I try to answer "yes" to both questions below Rome hangs. I couldn't find the cause, maybe you have a suggestion about how should I debug this. 

![3](https://user-images.githubusercontent.com/10727813/122902185-f4a47980-d356-11eb-900e-6ad023566230.png)
![2](https://user-images.githubusercontent.com/10727813/122902190-f53d1000-d356-11eb-94f0-c2302ef1ddf3.png)
![1](https://user-images.githubusercontent.com/10727813/122902195-f5d5a680-d356-11eb-8030-4d0f199053d2.png)

2021-06-22 09:56 UTC, JustBeYou commented
Also, `auto-config` does not display any diagnostic if it fails. It just prints "something went wrong" or nothing at all. Which would be the right way to display them?

I was thinking about 
```typescript
if (result.type === "DIAGNOSTICS" && result.hasDiagnostics) {
  throw new DiagnosticsError("Couldn't auto-configure", result.diagnostics)
}
```
This is how the output would look like: 
![4](https://user-images.githubusercontent.com/10727813/122904679-3cc49b80-d359-11eb-8135-166640d30455.png)

2021-06-22 10:41 UTC, ematipico commented
> Also, `auto-config` does not display any diagnostic if it fails. It just prints "something went wrong" or nothing at all. Which would be the right way to display them?
> 
> I was thinking about
> 
> ```ts
> if (result.type === "DIAGNOSTICS" && result.hasDiagnostics) {
>   throw new DiagnosticsError("Couldn't auto-configure", result.diagnostics)
> }
> ```
> 
> This is how the output would look like:
> ![4](https://user-images.githubusercontent.com/10727813/122904679-3cc49b80-d359-11eb-8135-166640d30455.png)

That's how we are doing so far. You could create a new object under `INIT_COMMAND` and have all the logs, advises, etc. that you want.  

```js
throw createSingleDiagnosticsError({
	location: req.getDiagnosticLocationForClientCwd(),
	description: descriptions.INIT_COMMAND.UNCOMMITTED_CHANGES,
});
```

> I've added autoconfiguration. The only problem is that if I try to answer "yes" to both questions below Rome hangs. I couldn't find the cause, maybe you have a suggestion about how should I debug this.

About this one, I've had a look at your new changes so far. Without checking out your branch I don't really know what could be wrong. Does it occur even with just one answer? (try to comment the second one). 

I will look into it later in the afternoon.

2021-06-23 07:33 UTC, JustBeYou commented
> That's how we are doing so far. You could create a new object under INIT_COMMAND and have all the logs, advises, etc. that you want.
That's how diagnostics are created in the server command. But they should also be thrown on the local command, otherwise, we don't receive any output. At the moment, if you have uncommited files you won't receive any useful information about why the command fails. See https://github.com/rome/tools/blob/a88c94a92ffc4283eb72df963d06f6ba688d4fb7/internal/core/client/commands/autoConfig.ts#L55
That's why I was suggesting rethrowing. 

> About this one, I've had a look at your new changes so far. Without checking out your branch I don't really know what could be wrong. Does it occur even with just one answer? (try to comment the second one).
It does not occur with just one answer. Only if both are present and I try to answer "yes" to both of them.

2021-06-24 07:42 UTC, JustBeYou commented
This feature is done, but I think it should be merged after #1588 is unconfirmed or fixed and #1587 is merged.

2021-06-24 15:49 UTC, ematipico commented
> That's how diagnostics are created in the server command. But they should also be thrown on the local command, otherwise, we don't receive any output.

It's definitely a regression. I confirmed that with Sebastian.

2021-06-28 13:39 UTC, closed without merging