Fix/keep comments when formatting case less switch statement
rome/tools pull request #1586
Opened 2021-06-23 17:01 UTC by Xiaohanxu1996

## Summary

## Test Plan

2021-06-24 15:03 UTC, ematipico requested changes
Thank you for your PR! There are few bits to review, I left some comment.

2021-06-24 15:03 UTC, ematipico commented on internal/formatter/builders/js/statements/JSSwitchStatement.ts
> +		builder.tokenizeInnerComments(node, true),
We should check if `node.innerComments` exists and then we can call `builder.tokenizeInnerComments`.

2021-06-24 15:03 UTC, ematipico commented on internal/parser-core/comments.ts
> +					trailingComments = state.leadingComments;
Shouldn't it be `innerComments`?

2021-06-24 16:51 UTC, nickxiaohk01 commented
ok I see

2021-09-22 22:57 UTC, jamiebuilds commented
Hi! Thank you so much for your contribution!

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. But while we're closing this, we'd love to have your involvement in the future.

Thanks again!

2021-09-22 22:57 UTC, closed without merging