feat(css-grid-support): fit-content
rome/tools pull request #1599
Opened 2021-06-28 16:05 UTC by ktfth

Base content for fit-content

./rome test

2021-06-28 18:04 UTC, ematipico requested changes
Thank you for your PR!

Something important missing are the tests. Can you implement some please? Good cases and bad cases. Bad cases should be at least one for each diagnostic you created.

2021-06-28 18:04 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/index.ts
> +import fitContent from "./prefixes/fit-content";
Why did you create a prefixer for `fit-content`? Is it needed? I didn't find anything

2021-06-28 18:04 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +		message: markup`Uknown behavior in fit content function.`,
This message is too cryptic. What does it mean? It would be great to have a better message... but the look of it, I can't understand what error we are handling here. Can you help?

2021-06-28 21:56 UTC, ktfth commented on internal/ast/css/unions.ts
> +	| CSSFitContent;
The spec have not information about that, is better to remove.

2021-06-28 21:57 UTC, ktfth commented on internal/compiler/transforms/compile/css-handler/prefix/index.ts
> +import fitContent from "./prefixes/fit-content";
Has no need for that, just following the procedure of contribution but on the implementation this have changed

2021-06-28 22:00 UTC, ktfth commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +		message: markup`Uknown behavior in fit content function.`,
I have filled an empty diagnostic part from fit content with that message. I can change to something better

2021-06-29 07:32 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/index.ts
> +import fitContent from "./prefixes/fit-content";
Yes please, let's delete everything around the prefixer, it's outside the scope of this PR.

2021-06-29 07:33 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +		message: markup`Uknown behavior in fit content function.`,
Yes please, let's a have a better message. What kind of error are you trying to handle here?

2021-06-30 16:40 UTC, ktfth commented
How to create tests for diagnosis?

2021-06-30 16:52 UTC, ematipico commented
> How to create tests for diagnosis?

I am writing some documentation, in the meantime [you can check this preview](https://github.com/ematipico/rome/blob/chore/better-internal-testing/CONTRIBUTING.md#creating-tests)

2021-07-01 12:42 UTC, ematipico commented on internal/ast/css/unions.ts
> +	| CSSFitContent;
Can we remove it please?

2021-07-01 16:38 UTC, ktfth commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +		message: markup`Uknown behavior in fit content function.`,
Maybe an unknown value for fit content

2021-07-02 13:34 UTC, ematipico requested changes
Again, let's please remove everything around the prefixer. It's out of the scope of this PR and we don't need it.

Also, we need to create a failing test for each diagnostic you created. You created two diagnostics, meaning that we need to have at least two tests, one for each new diagnostic. 

Also, [please address this comment](https://github.com/rome/tools/pull/1599/files#r660002800). I keep seeing resolved but it is not.

2021-07-02 13:34 UTC, ematipico commented on internal/compiler/transforms/compile/css-handler/prefix/prefixes/fit-content.ts
> +import {
We have to delete this file

2021-07-02 13:34 UTC, ematipico commented on internal/css-parser/test-fixtures/fit-content/input.css
> +}
This is not part of what we are doing here. We can delete it.

2021-07-02 13:34 UTC, ematipico commented on internal/css-parser/test-fixtures/invalid/fit-content/input.test.md
> +  ✖ Uknown unit on the fit content function.
We should suggest what units a developer can provide. This means we need to add an advice to the diagnostic.

2021-07-02 13:34 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +		message: markup`Uknown unit on the fit content function.`,
```suggestion
		message: markup`Uknown unit on the <emphasis>fit-content()</emphasis> function.`,
```

2021-07-02 13:34 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +	},
Let's add an advice where we tell the developer what values are supported.

2021-07-02 13:34 UTC, ematipico commented on website/src/docs/css-handler/prefix/fit-content.md
> +---
This file has to be deleted.

2021-07-02 13:34 UTC, ematipico commented on internal/css-parser/test-fixtures/invalid/fit-content/input.css
> +.style {
Let's rename the directory `fit-content` with something else. Ideally we will need to replicate more than one invalid case. 

We could call this directory `fit-content/invalid-unit`

2021-07-02 17:13 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +	},
@ktfth an advice is something more specific, I didn't mean to add more text. [This is an advice](https://github.com/rome/tools/blob/main/internal/diagnostics/descriptions/parsers/cssParser.ts#L51-L57).

Please next time leave a question here and I would be happy to answer

2021-07-02 17:18 UTC, ematipico commented on internal/css-parser/test-fixtures/fit-content/input.test.md
> +								loc: SourceLocation fit-content/input.css 2:36-2:39
There's an issue in your parsing strategy.

Line 38 says `2:36-2:39` 
Line 35 says `2:36-2:39`

This mean that both tokens have the same location in terms of row/column and it's not correct. The `CSSDimension` token should have a different location.

2021-07-02 17:22 UTC, ematipico commented on internal/css-parser/parser/fit-content.ts
> +	const start = parser.getPosition();
This `start` should be used for `value` but it should not be used for when you create `CSSFitContent` token.

[Use this strategy](https://github.com/rome/tools/blob/main/internal/css-parser/parser/minOrMax.ts#L17-L19) to get the correct position for `CSSFitContent`

2021-07-02 17:23 UTC, ematipico commented on internal/formatter/builders/css/function/CSSFitContent.ts
> +import {CSSFitContent as CSSFitContentType} from "@internal/ast";
We have to create a new test for the formatter. Check the existing tests to get an idea of how it works

2021-07-02 17:52 UTC, ematipico commented on internal/css-parser/parser/fit-content.ts
> +	const start = parser.getPosition();
@ktfth you still need `const start = parser.getPosition();` for when you actually create the value node.

You need to use **two different positions**.

2021-07-02 17:56 UTC, ematipico requested changes

2021-07-02 17:56 UTC, ematipico commented on internal/ast/css/unions.ts
> +
```suggestion
	| CSSNumber;

```

2021-07-02 17:56 UTC, ematipico commented on internal/css-parser/parser/fit-content.ts
> +	const start = parser.getPositionFromIndex(previousToken.start);
```suggestion
	// prepare variables needed for the final node
	const previousToken = parser.getPreviousToken() as Tokens["Ident"];
	const functionStart = parser.getPositionFromIndex(previousToken.start);
	const start = parser.getPosition();
	
```

2021-07-02 17:56 UTC, ematipico commented on internal/css-parser/parser/fit-content.ts
> +			start,
```suggestion
			functionStart,
```

2021-07-02 17:56 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +				text: markup`The only valid values are dimension or percentage or a number.`,
```suggestion
				text: markup`The only valid values are dimensions, percentages or numbers.`,
```

2021-07-02 18:01 UTC, ktfth commented on internal/css-parser/parser/fit-content.ts
> +	const start = parser.getPositionFromIndex(previousToken.start);
Where i use the functionStart? I don't get it

2021-07-02 18:04 UTC, ktfth commented on internal/formatter/builders/css/function/CSSFitContent.ts
> +import {CSSFitContent as CSSFitContentType} from "@internal/ast";
I have not founded tests for formatter on the resources who i looked, do you have one?

2021-07-02 18:22 UTC, ktfth commented on internal/formatter/builders/css/function/CSSFitContent.ts
> +import {CSSFitContent as CSSFitContentType} from "@internal/ast";
I'm looking for something here to delivery a solution

2021-07-05 08:48 UTC, ematipico approved these changes
I think the feature is ready to be merged! There's just one leftover to remove and we're good!

2021-07-05 08:48 UTC, ematipico commented on internal/diagnostics/descriptions/parsers/cssParser.ts
> +	},
This diagnostic is not used anymore, we can delete it

2021-07-05 13:17 UTC, merged