Macro to automatically generate expected/snapshot tests from files
rome/tools pull request #1684
Opened 2021-10-05 18:37 UTC by xunilrj

Automatically generate unit tests from files. 

# Usage

First argument: glob that will passed to https://github.com/gilnaa/globwalk. Crate's cargo.toml will be the base directory.  
Second argument: method that will be called.

```
tests_macros::gen_tests!{"tests/*", run_test}

fn run_test<S: AsRef<str> + std::fmt::Debug>(a: S, b: S) {
    println!("{:?} {:?}", a, b);
}
```

this will generate the following for each file:
Test name is the "snake case" version of the file name.

```
#[test]
pub fn sometest()
{
    let test_file = "<SOMEDIR>/tests/sometest.txt";
    let test_expected_file = "<SOMEDIR>/tests/sometest.expected.txt";
    run_test(test_file, test_expected_file);
}
```

2021-10-05 19:02 UTC, jamiebuilds commented on crates/tests_macros/Readme.md
> +tests_macros::gen_tests!{"tests/*", run_test}
Should this be `gen_tests!(...)` with parens instead?

2021-10-06 07:14 UTC, xunilrj commented on crates/tests_macros/Readme.md
> +tests_macros::gen_tests!{"tests/*", run_test}
For some reason they allowed both on proc_macros.

```
 Compiling fs-macros-tests v0.1.0 (C:\pocs\fs-macros\fs-macros-tests)
error: macros that expand to items must be delimited with braces or followed by a semicolon
  |
1 | fs_macros::gen_tests!("tests/*", run_test)
  |                      ^^^^^^^^^^^^^^^^^^^^^
  |
help: change the delimiters to curly braces
  |
1 | fs_macros::gen_tests!{"tests/*", run_test}
  |                      ^                   ^
help: add a semicolon
  |
1 | fs_macros::gen_tests!("tests/*", run_test);
  |                                           ^
```

2021-10-06 07:19 UTC, xunilrj commented on crates/tests_macros/Readme.md
> +    let test_expected_file = "<SOMEDIR>/tests/sometest.expected.txt";
Yeah, we can. For example:

```
fs_macros::gen_tests!("tests/*.{json,js}", run_test);
```

I'm using https://docs.rs/globwalk/0.8.1/globwalk/ which promises: "gitignore's extended glob syntax".

2021-10-06 07:20 UTC, xunilrj commented on crates/tests_macros/src/lib.rs
> +			.map_err(|_| "Cannot find CARGO_MANIFEST_DIR. What we using cargo?")?;
Done.

2021-10-06 07:32 UTC, xunilrj commented on crates/tests_macros/src/lib.rs
> +		let test_full_path = path.display().to_string();
That is another strange bit of Rust Path api... it has a method called display(), but Path does not impl std::fmt::Display. https://doc.rust-lang.org/std/path/struct.Path.html

I believe it is because .display() is lossy. They wanted this conversion to be explicit.

2021-10-06 08:00 UTC, ematipico commented on crates/tests_macros/Readme.md
> +    let test_expected_file = "<SOMEDIR>/tests/sometest.expected.txt";
I think it's worth adding this example to the `README.md`.

2021-10-06 08:13 UTC, ematipico requested changes
Nice PR! I think we should add some module documentation at the top of `lib.rs`

2021-10-06 08:13 UTC, ematipico commented on crates/tests_macros/Readme.md
> +```
```suggestion
```rust

```

2021-10-06 11:51 UTC, xunilrj commented on crates/tests_macros/Readme.md
> +    let test_expected_file = "<SOMEDIR>/tests/sometest.expected.txt";
done.

2021-10-06 11:53 UTC, xunilrj commented on crates/tests_macros/src/lib.rs
> +	fn get_variables<P: AsRef<Path>>(path: P) -> Option<(String, String, String)> {
done.

2021-10-06 11:53 UTC, xunilrj commented on crates/tests_macros/Readme.md
> +```
done

2021-10-06 11:54 UTC, xunilrj commented on crates/tests_macros/Readme.md
> +```
done

2021-10-06 11:57 UTC, xunilrj commented on crates/tests_macros/src/lib.rs
> +	f: syn::Path,
done

2021-10-06 11:58 UTC, xunilrj commented on crates/tests_macros/src/lib.rs
> +		// println!("{}", q);
Done.

2021-10-06 11:59 UTC, xunilrj commented on crates/tests_macros/src/lib.rs
> +		};
I went if a "match". I think is simpler.

2021-10-06 11:59 UTC, xunilrj commented on crates/tests_macros/Readme.md
> +Second argument: method that will be called.
done.

2021-10-06 12:29 UTC, MichaReiser commented on crates/tests_macros/Readme.md
> +    let test_expected_file = "<SOMEDIR>/tests/sometest.expected.txt";
Should the file endings of `test_file` and `test_expected_file` now be `js` or `json` because you changed the glob?

2021-10-06 12:47 UTC, ematipico approved these changes
I think we can merge it after we resolve the conflict!

2021-10-06 12:51 UTC, merged