feat: unknown statements
rome/tools pull request #1794
Opened 2021-11-17 14:48 UTC by ematipico

## Summary

This PR does the following:

- created a new struct called `RecoveryBag` where information the information needed for recovery are created passed to the parser;
- unified the functions `err_recover` and `err_recover_no_err` in one single function;
- the new function `recover_on_unexpected_node` now accepts a `RecoveryBag` as payload;
- fixed a bug inside the switch statement parsing;
- created new test cases to track errors that were not tracked before;
- removed `ERROR` and added `JS_UNKNOWN_STATEMENT` in some particular case;

## Test Plan

```
cargo lint
cargo format
cargo test
```

2021-11-17 14:51 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +			break;
Here we have an error, meaning that we haven't found `case` or `default`, so we need to `break` from the `while` loop otherwise we fall into a loop.

2021-11-17 15:33 UTC, yassere commented
What’s the advantage of combining these parameters into a `RecoveryBag` struct? It feels like it’s adding more boilerplate at the error recovery call sites in the parser.

2021-11-17 15:55 UTC, MichaReiser commented on crates/rslint_parser/src/recovery_bag.rs
> +	mysterious_node: SyntaxKind,
That sounds mysterious...

How about unknown_node_kind?

2021-11-17 15:55 UTC, MichaReiser commented on crates/rslint_parser/src/recovery_bag.rs
> +pub struct RecoveryBag {
Nit: `RecoveryBag` isn't telling readers much about what it is. Is it a `RecoveryConfiguration`?

2021-11-17 15:55 UTC, MichaReiser commented on crates/rslint_parser/src/recovery_bag.rs
> +	}
Nit: I find boolean flags hard to understand. Should we remove the `include_braces` and initialize it with the most common default and then expose a `with_braces_included` and `without_braces_included` functions to toggle the flag?

2021-11-17 15:55 UTC, MichaReiser commented on crates/rslint_parser/src/recovery_bag.rs
> +	}
Nit: To align with the `is_at_token_set`: Rename to `is_at_braces`. 

We may not need both these operations and just exposing a `is_at_recovery_token` could be sufficient.

2021-11-17 16:30 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +				}
Nit: can the `if` / `else` be unified into a single `else if`?

```
} else if range.is_empty() {
  first_default = Some(range);
}
```

It may also improve readability if we rename `range` to `default_range` inside of the `if let Some(range) = switch_clause(...)` to make it clear what kind of range this is.

2021-11-17 16:30 UTC, ematipico commented on crates/rslint_parser/src/recovery_bag.rs
> +pub struct RecoveryBag {
Configuration doesn't attract me... What about a simple `Recovery`? Or `RecoveryKit`? `AidKit`? Trying to use some fantasy lol

2021-11-17 16:32 UTC, ematipico commented on crates/rslint_parser/src/recovery_bag.rs
> +	}
Yes, that should improve the usability of the API

2021-11-17 16:38 UTC, ematipico commented
> What’s the advantage of combining these parameters into a `RecoveryBag` struct? It feels like it’s adding more boilerplate at the error recovery call sites in the parser.

The parameters of the functions we use to recover from errors were becoming too many. Micha suggested to revisit it with a `struct` and I agree to. Also, it allows us to unify some logic in one single place

2021-11-17 18:25 UTC, ematipico commented on crates/rslint_parser/src/lossless_tree_sink.rs
> +						.unwrap_or_else(|| self.text.get(start - 1..end).unwrap_or("")),
This part of the code is still obscure to me, but when I swap `ERROR` with `JS_UNKNOWN_*`, it triggers the `unwrap` error. The `unwrap_or` fixes the panic.

2021-11-17 18:37 UTC, xunilrj commented on crates/rslint_parser/src/recovery_bag.rs
> +pub struct RecoveryBag {
```ParseRecoverer```?

2021-11-17 18:39 UTC, xunilrj commented on crates/rslint_parser/test_data/inline/err/switch_stmt_no_cases.rast
> +  LIST@0..0
This node with this range makes sense?

2021-11-17 18:42 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/switch_stmt_no_cases.rast
> +  LIST@0..0
Yeah [I asked the same thing on discord](https://discord.com/channels/678763474494423051/841927329265090590/910520914574209024).

It is intended, that's the list that contains the directives, e.g. `"use strict"`

2021-11-17 18:46 UTC, xunilrj commented on crates/rslint_parser/test_data/inline/err/switch_stmt_no_cases.rast
> +    JS_UNKNOWN_STATEMENT@32..33
hum... I would expect the ```*_UNKNOWN_*``` node in this case to surround the whole statement; but looking at its range, it seems its pointing only to new line after the semicolon.

2021-11-17 18:52 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/switch_stmt_no_cases.rast
> +    JS_UNKNOWN_STATEMENT@32..33
Me too! That's what I am trying to understand. Although, also TS parser highlights the same:
<img width="348" alt="Screenshot 2021-11-17 at 15 52 07" src="https://user-images.githubusercontent.com/602478/142263904-f43376dd-12fb-4573-9c60-268481e7d704.png">

2021-11-17 22:11 UTC, MichaReiser commented on crates/rslint_parser/src/lossless_tree_sink.rs
> +						.unwrap_or_else(|| self.text.get(start - 1..end).unwrap_or("")),
@xunilrj do you know where this might be coming from?

2021-11-17 23:48 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +			p.recover_on_unexpected_node(
I think the best recovery here could be to insert a case clause where the unknown statement is the body. The recovery set should contain semicolon, }, new line and eof

This should also remove the need for the added break in the outer loop

2021-11-17 23:48 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	unknown_node_on_error: SyntaxKind,
I don't understand tha unknown parameter here. Shouldn't a non parsable statement always become an unknown statement. Because only unknown statements are allowed in places of a statement

2021-11-18 07:31 UTC, MichaReiser requested changes
I like the `RecoveryBag` and overall great improvements! 

There are some cases where we now insert invalid children (e.g. expressions instead of statements). 

Would you mind listing in the PR summary for parser rules your changing the error recovery?

2021-11-18 07:31 UTC, MichaReiser commented on crates/rslint_parser/src/parser.rs
> +		m.complete(self, recovery_bag.get_unknown_node_kind());
I believe we can reduce the number of branches for the error handling

```

if let Some(error) = error {
  self.error(error);
}

if !recovery_bag.parsing_is_recoverable(self) {
 	let m = self.start();  
	self.bump_any();
	m.complete(self, recovery_bag.get_unknown_node_kind());
}

2021-11-18 07:31 UTC, MichaReiser commented on crates/rslint_parser/src/recovery_bag.rs
> +pub struct RecoveryBag {
Like that, or `ParseRecovery`

2021-11-18 07:31 UTC, MichaReiser commented on crates/rslint_parser/src/recovery_bag.rs
> +	}
Nit: It's a bit confusing that `with_error` is a factory function whereas these `with` functions are instance methods. 

How about `enable_braces_recover()` and `disable_braces_recovery()` (is the disable used anywhere?)

2021-11-18 07:31 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +			));
For example, these handlers insert error nodes in places where otherwise a statement would have been. Shouldn't it then always insert an `UnknownStatement`?

2021-11-18 07:31 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
>  		return Some(m.complete(p, JS_LABELED_STATEMENT));
The body of a labeled statement must be a stmt. Why is it that we pass expression here?

2021-11-18 07:31 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	// p.recover_on_unexpected_node(recovery_bag)
Delete?

2021-11-18 07:31 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/do_while_stmt_err.rast
> +                JS_UNKNOWN_EXPRESSION@42..42
An expression in the place of the `While` statement's body isn't valid. This should be a `UnknownStatement`

2021-11-18 07:31 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/while_stmt_err.rast
> +      JS_UNKNOWN_EXPRESSION@50..51
The body of a while statement must be a statement and not an expression

2021-11-18 08:54 UTC, xunilrj commented on crates/rslint_parser/src/lossless_tree_sink.rs
> +						.unwrap_or_else(|| self.text.get(start - 1..end).unwrap_or("")),
No. But I will remove this code in my next PR, today. So I would not care too much.

2021-11-18 12:13 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +	stmt(
Actually, this is needed. As the comment says, it allows the parser to recover in case the the `if` is missing the needed curly brackets. We are not parsing the consequent yet. 

Here, we are telling to the parser that it should recover if it sees a `TokenSet` that includes the `else` too. But, if we have, for example:

```js
if (true)) else {}
-------^
```

The additional bracket will be marked as `JS_UNKNOWN_STATEMENT`

2021-11-18 12:15 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +			return Some(0..0);
I thought that too. I guess I am still too concerned about changing too much the parser 😓 
I will apply the change :)

2021-11-18 12:18 UTC, ematipico commented on crates/rslint_parser/src/parser.rs
> +		m.complete(self, recovery_bag.get_unknown_node_kind());
So easy! Thank you!

2021-11-18 12:18 UTC, ematipico commented on crates/rslint_parser/src/recovery_bag.rs
> +pub struct RecoveryBag {
Thank you all for the suggestions!

2021-11-18 12:28 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +			p.recover_on_unexpected_node(
> Is this inserting the UnknownStatement as a child of a switch? 

The error recovery here handles cases like this:

```js
switch (foo) {
	var bar = true;
}
```

I didn't understand the rest of the comment though, sorry.

2021-11-18 12:31 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/switch_stmt_no_cases.rast
> +    JS_VARIABLE_DECLARATION_STATEMENT@16..31
Let's tackle this in a different PR. Now that we have a test case, we can refine it later

2021-11-18 12:34 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +			p.recover_on_unexpected_node(
Yes, what's the output it generates in this case? 

One thing we could do to recover from this case is to generate the following tree

```
SWITCH_STATEMENT
  SWITCH_CASE_CLAUSE
    MISSING (case keyword)
    MISSING (test node)
    MISSING (:)
    VARIABLE_DECLARATION_STATEMENT
```

So we would parse the statement and insert a non existing switch case clause. This is fine, because we add an error to the case and passes will see that it's broken when they visit the test node / case keyword...

2021-11-18 12:36 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
>  		return Some(m.complete(p, JS_LABELED_STATEMENT));
Probably the fact that we are inside function called `expr_stmt` led me to this mistake. Will change

2021-11-18 12:42 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +			));
It is true, although, as we didn't have enough test cases, I wanted to make sure that the parent passed the unknown node, so I knew who passed it. 

I am going to refactor the change now

2021-11-18 12:50 UTC, MichaReiser commented on crates/rslint_parser/src/parse_recoverer.rs
> +impl ParseRecoverer {
nit: When this is called `ParseRecoverer`, should it then have a `recover(p: &mut Parser)` method, so that it handles all recovery logic?

2021-11-18 12:59 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +			p.recover_on_unexpected_node(
Here's the output:

```
    JS_SWITCH_STATEMENT@0..16
      SWITCH_KW@0..6 "switch"
      WHITESPACE@6..7 " "
      L_PAREN@7..8 "("
      JS_REFERENCE_IDENTIFIER_EXPRESSION@8..11
        IDENT@8..11 "foo"
      R_PAREN@11..12 ")"
      WHITESPACE@12..13 " "
      L_CURLY@13..14 "{"
      WHITESPACE@14..16 "\n\t"
      LIST@16..16
    JS_VARIABLE_DECLARATION_STATEMENT@16..31
      JS_VARIABLE_DECLARATION@16..30
        VAR_KW@16..19 "var"
        WHITESPACE@19..20 " "
        LIST@20..30
          JS_VARIABLE_DECLARATOR@20..30
            SINGLE_PATTERN@20..23
              NAME@20..23
                IDENT@20..23 "bar"
            WHITESPACE@23..24 " "
            JS_EQUAL_VALUE_CLAUSE@24..30
              EQ@24..25 "="
              WHITESPACE@25..26 " "
              JS_BOOLEAN_LITERAL@26..30
                TRUE_KW@26..30 "true"
      SEMICOLON@30..31 ";"
    WHITESPACE@31..32 "\n"
    JS_UNKNOWN_STATEMENT@32..33
      R_CURLY@32..33 "}"
```

> So we would parse the statement and insert a non existing switch case clause

We can't assume we have a `case` clause. It could be a `default` clause too. I believe this is a particular case that requires a particular strategy to recover from the error. I think we should do it in a different PR. It's good that we a test case now.

2021-11-18 13:02 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +			p.recover_on_unexpected_node(
Does that mean that it is inserting the `JS_UNKNOWN_STATEMENT` if it finds any unexpected token? 

Does that mean that we can end up in a situation where the parser inserts two statements into the parent, first the `switch` statement and then the `UnknownStatement` for any unexpected content?

2021-11-18 14:57 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +			p.recover_on_unexpected_node(
> Does that mean that it is inserting the JS_UNKNOWN_STATEMENT if it finds any unexpected token?

Yes

> Does that mean that we can end up in a situation where the parser inserts two statements into the parent, first the switch statement and then the UnknownStatement for any unexpected content?

Yes. And this is valid not for just a switch statement, but all similar situations:

```js
function foo() } } } } { }
```

Will emit:

```
    JS_FUNCTION_DECLARATION@0..14
      FUNCTION_KW@0..8 "function"
      WHITESPACE@8..9 " "
      JS_IDENTIFIER_BINDING@9..12
        IDENT@9..12 "foo"
      JS_PARAMETER_LIST@12..14
        L_PAREN@12..13 "("
        LIST@13..13
        R_PAREN@13..14 ")"
    JS_UNKNOWN_STATEMENT@14..15
      R_PAREN@14..15 "}"
    JS_UNKNOWN_STATEMENT@15..16
      R_CURLY@15..16 "}"
    JS_UNKNOWN_STATEMENT@16..17
      R_PAREN@16..17 "}"
    JS_UNKNOWN_STATEMENT@17..18
      R_CURLY@17..18 "}"
    JS_BLOCK_STATEMENT@18..25
      L_CURLY@18..19 "{"
      LIST@19..25
        JS_BLOCK_STATEMENT@19..25
```

2021-11-18 14:59 UTC, ematipico commented
I reverted the changes I did around the parsing of `switch`. It fixed a infinite recursion inside the parser but it lowered the coverage, meaning that we'd need to spend more time around it.

2021-11-18 18:22 UTC, ematipico commented
> There are some cases where we now insert invalid children (e.g. expressions instead of statements).

Errors, now fixed.

> Would you mind listing in the PR summary for parser rules your changing the error recovery?

Done

2021-11-19 03:39 UTC, yassere commented on crates/rslint_parser/src/parse_recoverer.rs
> +	/// Checks if the parsing phase is recoverable by checking curly braces and toke set
toke -> token

2021-11-19 03:39 UTC, yassere commented on crates/rslint_parser/src/parse_recoverer.rs
> +	/// It return the unknown node kind that will be used to complete the parsing
return -> returns

2021-11-19 03:39 UTC, yassere commented on crates/rslint_parser/src/parser.rs
> +	// }
Is this just an outdated version that will be removed?

2021-11-19 07:12 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	// FIXME: in this case
TODO?

2021-11-19 07:14 UTC, MichaReiser approved these changes
Looks good. Please take a look at the comments from @yassere before merging.

2021-11-19 12:59 UTC, merged