LosslessTreeSinker attaching trivia to tokens
rome/tools pull request #1801
Opened 2021-11-18 14:03 UTC by xunilrj

# Tasks

- [x] LosslessTreeSink
- [ ] LossyTreeSink

I also needed to make some formatter changes.

- [x] Trim leading and trailing trivia from ```SynyaxNode``` with error. See ```if_stmt_err.js```

2021-11-18 14:05 UTC, xunilrj commented on crates/rome_formatter/src/ts/statements/mod.rs
> +				.unwrap_or_else(|_| formatter.format_raw(stmt.syntax()).trim_start().trim_end())
When we insert a problematic statement into the formatter, we are trimming all "whitespace" from the start and from the end. Is that what we want to do?

2021-11-18 14:29 UTC, MichaReiser commented on crates/rome_formatter/src/ts/statements/mod.rs
> +				.unwrap_or_else(|_| formatter.format_raw(stmt.syntax()).trim_start().trim_end())
I don't know. Can we add a todo and mention it in the the formatter tracking task?

2021-11-18 14:38 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +			FormatElement::ConditionalGroupContent(_) => todo!(),
This should call `trim_start` on the content

2021-11-18 14:38 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +			FormatElement::ConditionalGroupContent(_) => todo!(),
Same, traverse into content

2021-11-18 14:38 UTC, MichaReiser commented on crates/rslint_parser/src/tests.rs
> +	let m = parse_module(text, 0);
Would you mind adding a test for

```
// only a comment
```

I'm wondering where we attach the comment to.

2021-11-18 14:38 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/async_arrow_expr_await_parameter.rast
> +JS_ROOT@0..25
What's the reason that the root contains a character less? What happens with the trailing whitespace?

2021-11-18 16:43 UTC, xunilrj commented on crates/rslint_parser/test_data/inline/err/async_arrow_expr_await_parameter.rast
> +JS_ROOT@0..25
Fixed.

2021-11-18 16:54 UTC, xunilrj commented on crates/rslint_parser/src/tests.rs
> +	let m = parse_module(text, 0);
Done. See "just_trivia_must_be_appended_to_eof" below.

2021-11-18 16:56 UTC, xunilrj commented on crates/rome_formatter/src/ts/statements/mod.rs
> +				.unwrap_or_else(|_| formatter.format_raw(stmt.syntax()).trim_start().trim_end())
https://github.com/rome/tools/issues/1726#issuecomment-973051032

2021-11-18 17:27 UTC, ematipico commented on crates/rome_formatter/src/format_element.rs
> +pub fn token_from_string(text: String) -> FormatElement {
Wasn't changing the existing function to `token(text: Into<&str>)` enough?

2021-11-18 17:27 UTC, ematipico commented on crates/rome_formatter/src/format_element.rs
> +	/// Remove all empty, space, line breaks, idents from the start of
I think that "empty" are not removed. On line 752, they are the same. Probably we should remove the "empty" part from the doc?

2021-11-18 17:27 UTC, ematipico commented on crates/rome_formatter/src/format_element.rs
> +						FormatElement::Space => true,
```suggestion
						FormatElement::Empty |
						FormatElement::Space => true,
```

2021-11-18 17:27 UTC, ematipico commented on crates/rome_formatter/src/format_element.rs
> +				}
What exactly is happening here?

2021-11-18 17:27 UTC, ematipico commented on crates/rome_formatter/src/format_element.rs
> +	/// Remove all empty, space, line breaks, idents from the end of
"empty" can be removed from the doc

2021-11-18 17:27 UTC, ematipico commented on crates/rome_formatter/src/ts/statements/mod.rs
> +				.unwrap_or_else(|_| formatter.format_raw(stmt.syntax()).trim_start().trim_end())
Prettier at the moment removes all "whitespace" if there are more than one - meaning at least 2 new lines.  As we want to mimic their behaviour, I think we should Prettier as starting point in case we have some decision to take.

2021-11-18 17:27 UTC, ematipico commented on crates/rome_rowan/src/api.rs
> +		let start = self.offset - self.raw.offset();
What's this change about?

2021-11-18 17:27 UTC, ematipico commented on crates/rome_rowan/src/api.rs
> +	/// Returns all pieces of this trivia.
Should we link "pieces" to the correct `struct`? If it's read without context and without reference, it might cause some confusion

2021-11-18 17:27 UTC, ematipico commented on crates/rome_rowan/src/api.rs
> +		self.descendants_with_tokens()
Why don't we use the `self.raw` here? Like in the other APIs

2021-11-18 17:27 UTC, ematipico commented on crates/rslint_parser/src/lossless_tree_sink.rs
> +	needs_eof: bool,
Can we document the new property please?

2021-11-18 17:27 UTC, ematipico commented on crates/rslint_parser/src/lossless_tree_sink.rs
> +	/// Trivia start Offset and its pieces.
Can we link "pieces" please? And "Offset" too I think

2021-11-18 17:29 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/binary_expressions_err.rast
> +  LIST@0..35
Is it normal that some trees are wider?

2021-11-18 18:00 UTC, xunilrj commented on crates/rome_formatter/src/format_element.rs
> +			FormatElement::ConditionalGroupContent(_) => todo!(),
Done.

2021-11-18 18:00 UTC, xunilrj commented on crates/rome_formatter/src/format_element.rs
> +			FormatElement::ConditionalGroupContent(_) => todo!(),
Done.

2021-11-18 18:01 UTC, xunilrj commented
> Can we delete these now?

I think we can. I will create another PR to clean everything we don't need anymore.

2021-11-18 19:57 UTC, xunilrj commented on crates/rslint_parser/test_data/inline/err/binary_expressions_err.rast
> +  LIST@0..35
I think yes, it is.
Indentation is not helping here... but this is happening because the trailing whitespace now is part of the node as trailing trivia, for example.

For example, a smaller example:

Before
```
              JS_REFERENCE_IDENTIFIER_EXPRESSION@4..7
                IDENT@4..7 "foo"
              WHITESPACE@7..8 " "
``` 

After

```
              JS_REFERENCE_IDENTIFIER_EXPRESSION@4..8
                IDENT@4..8 "foo "
```

2021-11-18 20:04 UTC, xunilrj commented on crates/rome_formatter/src/ts/statements/mod.rs
> +				.unwrap_or_else(|_| formatter.format_raw(stmt.syntax()).trim_start().trim_end())
hum.. I think we can keep what we have now, and revisit if it does not makes sense.

2021-11-18 21:33 UTC, xunilrj commented on crates/rome_formatter/src/format_element.rs
> +pub fn token_from_string(text: String) -> FormatElement {
No because I actually want to move the String, so I can create a ```Token``` without any extra allocation.

Places where you only have a &str, there is nothing we can do. You will need to call ```.to_string()``` and allocate.

But places where you own a String, and don't need it, you can move it to the Token. If this string is "casted" to ```&str```, I will need to ```to_string()``` it, what I am trying to avoid here.

I could do the inverse actually ```Into<String>```.

Complete example:

```rust

#[derive(Debug)]
pub struct Token(String);

pub fn token_into_str<'a, T: Into<&'a str>>(s: T) -> Token {
    Token(s.into().to_string())
}

pub fn token_into_string<T: Into<String>>(s: T) -> Token {
  Token(s.into())
}

pub fn token_as_ref<'a, T: AsRef<str>>(str: T) -> Token {
    Token(str.as_ref().to_string())
}

pub fn token_with_move(s: String) -> Token {
    Token(s)
}

fn main() {
    let allocations = allocation_counter::count(|| {
        let s = "a".to_string();
        println!("{:?}", token_into_str(s.as_str()));
    });
    println!("token_into_str: {}", allocations);

    let allocations = allocation_counter::count(|| {
        let s = "a".to_string();
        println!("{:?}", token_into_string(s.as_str()));
    });
    println!("token_into_string(&str): {}", allocations);

    let allocations = allocation_counter::count(|| {
        let s = "a".to_string();
        println!("{:?}", token_into_string(s));
    });
    println!("token_into_string(String): {}", allocations);

    let allocations = allocation_counter::count(|| {
        let s = "a".to_string();
        println!("{:?}", token_as_ref(&s));
    });
    println!("token_as_ref(&String): {}", allocations);

    let allocations = allocation_counter::count(|| {
        let s = "a".to_string();
        println!("{:?}", token_as_ref(s.as_str()));
    });
    println!("token_as_ref(&str): {}", allocations);

    let allocations = allocation_counter::count(|| {
        let s = "a".to_string();
        println!("{:?}", token_with_move(s));
    });
    println!("token_with_move: {}", allocations);
}
```

```
Token("a")
token_into_str: 3
Token("a")
token_into_string(&str): 2
Token("a")
token_into_string(String): 1
Token("a")
token_as_ref(&String): 2
Token("a")
token_as_ref(&str): 2
Token("a")
token_with_move: 1
```

https://replit.com/@xunilrj/MutedDimTest#src/main.rs

2021-11-18 22:01 UTC, xunilrj commented on crates/rome_formatter/src/format_element.rs
> +pub fn token_from_string(text: String) -> FormatElement {
Done.

2021-11-18 22:03 UTC, xunilrj commented on crates/rome_formatter/src/format_element.rs
> +	/// Remove all empty, space, line breaks, idents from the start of
Done.

2021-11-18 22:06 UTC, xunilrj commented on crates/rome_formatter/src/format_element.rs
> +				}
Because tokens have leading trivia now, at the formatter we can have:

```
   Indent(Token("\t\tlet"))
```

When we call ```.trim_start()" for example, these three lines are trimming the token to Token("let").

2021-11-18 22:07 UTC, xunilrj commented on crates/rome_formatter/src/format_element.rs
> +	/// Remove all empty, space, line breaks, idents from the end of
Done.

2021-11-18 22:14 UTC, xunilrj commented on crates/rome_rowan/src/api.rs
> +		let start = self.offset - self.raw.offset();
Each ```SyntaxTriviaPiece``` has its offset in the document. But to slice the token text, I need the offset from within the token text (including trivia).

For example

```rust
function foo() {\n/*hi*/let a = 0;}
```

The token ```let``` has:
leading trivia: "\n/*hi*/"
trailing trivia: " "

When you ask for the SyntaxTriviaPiece of the comments, it has a global offset of 17..23. But to get the text of the trivia piece, we need to slice the token text, that is "\n/*hi*/let"; The comments offset of 17..23, actually is 1..7.

2021-11-18 22:16 UTC, xunilrj commented on crates/rome_rowan/src/api.rs
> +	/// Returns all pieces of this trivia.
Done.

2021-11-18 22:18 UTC, xunilrj commented on crates/rome_rowan/src/api.rs
> +		self.descendants_with_tokens()
Because using ```self.raw``` would return a ```cursor::SyntaxToken``` and I would need to create the correct ```api::SyntaxToken<L>``` from them. This method is doing this for me.

2021-11-18 22:24 UTC, xunilrj commented on crates/rslint_parser/src/lossless_tree_sink.rs
> +	needs_eof: bool,
Done.

2021-11-18 22:26 UTC, xunilrj commented on crates/rslint_parser/src/lossless_tree_sink.rs
> +	/// Trivia start Offset and its pieces.
Piece link: Done.
Offset, no idea where to link this to.

2021-11-19 05:10 UTC, yassere commented on crates/rome_formatter/src/format_element.rs
> +				}
Rather than allocating a vector and then reversing it in place, could we find the `position` of the first non-whitespace element in reverse iteration so we can `take` up to that position in forward iteration and collect that into a new vector?

2021-11-19 07:11 UTC, MichaReiser requested changes
I really love this change, excellent work!

There are two last things that I think we should improve before moving forward.

## Debug Format:

I find it a bit misleading. It looks as if an identifier was parsed as `foo ` or keywords/punctuations as `\n!`. 

Would it make sense to format the trivia more explicitly, for example

```
IDENT@4..8 text: (trivia) (text="foo") (trivia whitespace: " ")
```

Swift actually prints tokens more like nodes since they now can contain rather bulky content like comments

```
IDENT@4..8 
  (trivia newline "\n")
  (trivia whitespace "    ")
  (text: "foo")
  (trivia whitespace: " ")
```

Printing the trivia pieces one by one has the benefit that changes to the trivia parsing are tested as well. In that spirit. Would you mind adding an integration test for some trivia (single line comment, mutliline comment etc.)

## EOF

I believe we shoulnd't append the EOF token conditionally, only when needed. Authors would see, oh, there's an EOF token I can test for and then bum, it isn't there in some cases. 

We should also make it clear where EOF tokens can appear in our grammar. I think it's sufficient to add it to the `JsRoot` rule for now. We can figure out the `parse_text` use case later (probably best to introduce a "fake" node for parsed text.

2021-11-19 07:11 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/binary_expressions_err.rast
> +                IDENT@4..8 "foo "
This format is a bit misleading. It reads as if the identifier name is `foo ` (with trailing space). Would it make sense to format the trivia more explicitly, for example

```
IDENT@4..8 text: (trivia) (text="foo") (trivia whitespace: " ")
```

Printing the trivia pieces one by one has the benefit that changes to the trivia parsing are tested as well.

2021-11-19 07:11 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/conditional_expr_err.rast
> +            IDENT@36..40 "bar\n"
Shouldn't we see the `EOF` token as part of the test files?

2021-11-19 09:04 UTC, xunilrj commented on crates/rome_formatter/src/format_element.rs
> +				}
Done. But this ```trim_start()``` and ```trim_end()``` are a little bit naive. If we decide to stick with them, I would try to improve them: code-wise, performance-wise and make them work with more cases.

2021-11-19 12:48 UTC, ematipico commented on crates/rome_formatter/src/format_element.rs
> +pub fn token_from_string(text: String) -> FormatElement {
Great explanation! Thank you! :)

2021-11-19 12:49 UTC, ematipico commented on crates/rome_rowan/src/api.rs
> +		let start = self.offset - self.raw.offset();
Thank you! Makes sense now

2021-11-19 12:50 UTC, ematipico commented on crates/rslint_parser/src/lossless_tree_sink.rs
> +	/// Trivia start Offset and its pieces.
probably offset is the `TextRage`?

2021-11-19 13:07 UTC, yassere commented on crates/rome_formatter/src/format_element.rs
> +					.next();
For getting rid of the lint error, I think you could replace these three method calls with a [position](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.position)

2021-11-19 13:24 UTC, xunilrj commented on crates/rslint_parser/src/lossless_tree_sink.rs
> +	fn get_trivia(&mut self, break_on_newline: bool) -> (TextRange, Vec<TriviaPiece>) {
For all cases but the first and the last trivia of the file ```break_on_newline = false``` is for the trailing. That is why I prefer this name, because it is what the method is doing.

2021-11-19 13:25 UTC, xunilrj commented on crates/rslint_parser/test_data/inline/err/binary_expressions_err.rast
> +                IDENT@4..8 "foo "
What about now?

```
JS_VARIABLE_DECLARATION@0..13
        LET_KW@0..8 "let" [Comments("/**/")] [Whitespace(" ")]
```

2021-11-19 13:33 UTC, xunilrj commented on crates/rome_formatter/src/format_element.rs
> +				}
Done.

2021-11-19 13:36 UTC, xunilrj commented on crates/rome_formatter/src/format_element.rs
> +					.next();
Makes sense. Done.

2021-11-19 13:41 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/binary_expressions_err.rast
> +                IDENT@4..8 "foo "
Works for me. It might be helpful to be a bit more descriptive, especially because the leading/text are now out of order

```
        LET_KW@0..8 "let" (leading: COMMENTS("/**/")) (trailing: WHITESPACE(" "))
```

I would be OK not printing the trivia if it's empty.

Anyhow, that's more my personal taste now.

2021-11-20 16:20 UTC, xunilrj commented on crates/rslint_parser/src/lossless_tree_sink.rs
> +
I am forcing a EOF at the tree sink for now. This way is easier and we never loose the last trivia of the file.

2021-11-20 16:21 UTC, xunilrj commented on crates/rslint_parser/test_data/inline/err/conditional_expr_err.rast
> +            IDENT@36..40 "bar\n"
...and now you can see.

2021-11-22 07:00 UTC, MichaReiser approved these changes
Thanks! 

Can we remove the `hidden` from `EOF`. 

https://github.com/rome/tools/blob/8adc8b5dcd1777e45204a1401f9d595619dee6eb/crates/rslint_syntax/src/generated.rs#L11-L12

As this is now a public visible token.

2021-11-22 09:22 UTC, merged