chore: rename parse methods
rome/tools pull request #1822
Opened 2021-11-25 16:45 UTC by ematipico

## Summary

This PR changes the signature of some methods from `Option<CompletedMarker>` to `ParsedSyntax`

## Test Plan

```
cargo lint
cargo format
cargo test
```

Waiting for coverage result

2021-11-25 16:46 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +					parse_formal_param_pat(p).or_missing(p);
@MichaReiser this is a case where the compiler warned where the `ParsedSyntax` needed to be handled. Is it the correct approach?

2021-11-25 16:49 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +					parse_formal_param_pat(p).or_missing(p);
I think that probably in this case the `.ok()` was the better approach 🤔

2021-11-25 17:50 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +					parse_formal_param_pat(p).or_missing(p);
You want to use `or_missing_with_error` here because it's an error if a setter has no parameter. 

`ok` should always never be used because it doesn't handle the error at all.

2021-11-25 17:52 UTC, MichaReiser commented
Would you mind explaining in more detail what the goal of this PR is. Which parse functions have now been completely migrated to the new parsing logic? 

I would recommend to only rename fully migrated functions to `parse_` so that we can track what uses the new logic and what isn't.

It's hard to do a proper review otherwise (and keep track of what has been done and what not).

2021-11-26 09:59 UTC, ematipico commented
> Would you mind explaining in more detail what the goal of this PR is. Which parse functions have now been completely migrated to the new parsing logic?
> 
> I would recommend to only rename fully migrated functions to `parse_` so that we can track what uses the new logic and what isn't.
> 
> It's hard to do a proper review otherwise (and keep track of what has been done and what not).

I expanded the description of the PR.

Please check the error handling part and please let me know if you're OK to leave it as is for the time being. It will be properly fixed once the `pattern()` function will be migrated.

2021-11-26 11:18 UTC, MichaReiser commented
> Please check the error handling part and please let me know if you're OK to leave it as is for the time being. It will be properly fixed once the `pattern()` function will be migrated.

The pattern part is fine. I'll probably rewrite it from scratch (by merging it with the assignment target implementation)

2021-11-26 11:32 UTC, ematipico commented
> > Please check the error handling part and please let me know if you're OK to leave it as is for the time being. It will be properly fixed once the `pattern()` function will be migrated.
> 
> The pattern part is fine. I'll probably rewrite it from scratch (by merging it with the assignment target implementation)

I don't think it's fine (maybe the error is somewhere else), please check this part of the snapshot:

```
--
error[SyntaxError]: expected a parameter but instead found '{'
  ┌─ setter_class_member.js:2:13
  │
2 │   set foo() {}
  │             ^ Expected a parameter here


```

As you can see the range is not correct, it seems that the parser has been advanced too much.

2021-11-26 11:34 UTC, MichaReiser commented
> > > Please check the error handling part and please let me know if you're OK to leave it as is for the time being. It will be properly fixed once the `pattern()` function will be migrated.
> > 
> > 
> > The pattern part is fine. I'll probably rewrite it from scratch (by merging it with the assignment target implementation)
> 
> I don't think it's fine (maybe the error is somewhere else), please check this part of the snapshot:
> 
> ```
> --
> error[SyntaxError]: expected a parameter but instead found '{'
>   ┌─ setter_class_member.js:2:13
>   │
> 2 │   set foo() {}
>   │             ^ Expected a parameter here
> ```
> 
> As you can see the range is not correct, it seems that the parser has been advanced too much.

I mean fine in... maybe broken but pattern parsing will change completely... that's why it's fine :)

2021-11-26 11:41 UTC, ematipico commented
Perfect, thank you!

2021-11-26 12:37 UTC, MichaReiser requested changes
Can we give this PR a more descriptive title? 
I know, it's hard because it changes many different methods. But even something like `use new parse API for simple statements`. 

* `parse_parameter_list` You only changed the name but it still returns a `CompletedMarker`. 

We should add tests for every migrated statement testing the valid and error cases. This also allows us to verify if we're adding the right amount of missing markers.

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +						.or_missing_with_error(p, js_parse_error::expected_parameter);
This is correct on your side. If the pattern code is inserting nodes even if it isn't able to parse a pattern than the bug is in `parse_formal_param_pat` and not how you call it! 

I'll have a look when working on patterns.

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/decl.rs
> +pub(super) fn parse_parameter_list(p: &mut Parser) -> CompletedMarker {
You mentioned in the summary that you migrated `parameters_list` but it still returns `ParsedSyntax`. OK with me, but can you remove it from the summary?

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
>  	let m = p.start();
Do I understand this correctly that all modifiers are parsed into this `m`. Can we rename it to `modifiers_marker`? 

Makes the code a bit more clearer.

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +		if let Some(ref mut pat) = parse_formal_param_pat(p).ok() {
You can use 

```
if let Present(mut pat) = parse_formal_param_pat(p) {
    ...
}
```

No need to convert it to a `Option` first.

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/decl.rs
> +		return ParsedSyntax::Absent;
This won't be correct in case there was any typescript modifier. But we can leave it for now because it's patterns.

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/decl.rs
> +			if let Some(res) = parse_param(p).ok() {
`if let Present(res) = parse_param(p) {`

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +			parse_arrow_body(p).ok()
`ok` is mainly there for compatibility but is rarely what you want. 

We're fairly confident that this is an arrow function at this point and an arrow function always must have a body. That's why you need to use `or_missing_with_err` here to add an error if the arrow function body is missing. 

Maybe add a test as well?

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +	if let Some(m) = parse_literal_expression(p).ok() {
`if let Present(m) = parse_literal_expression(p) {`

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/object.rs
> +	// TODO: review error handling once the pattern functions is refactored
This is correct. I don't think we need the TODO here. We just need to fix the `parse_formal_param_pat` implementation.

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
>  	p.expect_required(T![return]);
Nit: `bump` or `bump_any`?

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
>  		p.expr_with_semi_recovery(false);
This is actually incorrect to my understanding. It adds an error if the parser is at a `;`. But `return;` is valid JS. 

This should be simply

```rust
!p.has_linebreak_before_n(0) {
    parse_expression(p).or_missing();
} else {
    p.missing();
}
```

But don't think this can easily be done when `expr` isn't returning `ParsedSyntax`

We certainly want the `p.missing()` in the `else` branch to make sure we add a missing marker if the `return` argument is missing.

Sitenote: We should probably have helpers `is_at_expression` instead of `p.at_ts(STARTS_EXPR)`.

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
>  		p.bump_any();
Err... not sure why GitHub doesn't allow me to comment on line 338. 

We need to add a `missing` marker if the label is missing to ensure we always have the same number of children.

Add `p.missing()` on line 338

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
>  	}
You need to convert the `break` statement to a `JS_UNKNOWN_STATEMENT` if used outside of a `switch`, `loop`, or `labeled statement`.

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	Present(m.complete(p, JS_CONTINUE_STATEMENT))
Same as for break: Add missing marker for label. Return `Unknown_STMT` if used outside of a loop.

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	Present(complete)
You need to return a `UnknownStatement` if used outside of a function.

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
>  }
You must add a missing marker if the else clause is missing

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +pub fn parse_with_stmt(p: &mut Parser) -> ParsedSyntax {
Can we rename all the functions to match the name in the grammar

* `parse_if_stmt` -> `parse_if_statement`
* `parse_with_stmt` -> `parse_with_statement`
* ...

2021-11-26 12:37 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +pub fn parse_switch_stmt(p: &mut Parser) -> CompletedMarker {
* Should this return `ParsedSyntax`?
* We shouldn't allow for two `default` cases. It may be easier to pass `first_default` to `switch_clause` (parse_switch_clause) so that it then can create a `SwitchCase` where we stuff the whole `default` case into an `UnknownStatement`.
* We should do error recovery in case no case was found.

2021-11-26 13:02 UTC, ematipico commented on crates/rslint_parser/src/syntax/decl.rs
> +pub(super) fn parse_parameter_list(p: &mut Parser) -> CompletedMarker {
It's still part of the work: rename methods and and use new API. I will update the description.

2021-11-26 13:05 UTC, ematipico commented on crates/rslint_parser/src/syntax/decl.rs
> +		return ParsedSyntax::Absent;
I will add a TODO

2021-11-26 13:06 UTC, ematipico commented on crates/rslint_parser/src/syntax/decl.rs
> +pub(super) fn parse_parameter_list(p: &mut Parser) -> CompletedMarker {
API changed

2021-11-26 13:38 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
>  		p.expr_with_semi_recovery(false);
I'd prefer to leave it as it is, and review it in another PR. I think that `expr_with_semi_recovery` should go away, but not in this PR

2021-11-26 14:25 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +pub fn parse_switch_stmt(p: &mut Parser) -> CompletedMarker {
> We should do error recovery in case no case was found.

You mean if no `case` or `default` was found?

2021-11-26 15:52 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +						temp.error(err);
Here the error has to be added manually. We can't do `clause.or_missing_with_error` because `clause` is actually `Present`.

2021-11-26 17:28 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +						temp.error(err);
Just changing it to a default statement isn't valid here. YOu then get the structure 

```
switch
 - unknown statement
```

I would pass the `first_default` to `parse_switch_clause` like this `parse_switch_clause(&mut *temp, first_default)`. 

The `parse_switch_clause can then test if the `default` clause is already present. If that's the case, then start a new case clause with:

* 'case' token missing
* test node missing
* consequent: The whole `default clause`.

2021-11-29 09:53 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +						temp.error(err);
> Just changing it to a default statement isn't valid here

Could you tell us why?

I don't understand the final result.  Why do we need to mark a `case_clause` while it actually is a `default_clause`? And why do we need to mark the first two tokens as missing? I may understand the first one (`default` VS `case`), but why also the `:`? It's actually present, I can't understand why we need to mark it as missing.

Wouldn't be better like this?

```
switch
	- default_clause: 
		...
	- case_clause:
		- unknown // it's not missing; it exists but it's wrong
		- colon
		- unknown_statement
			- list
		- 
```

2021-11-29 12:02 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +						temp.error(err);
There are only specific places where unknown nodes are allowed to appear and this is specified in our grammar. Unknown nodes are only allowed if you find a grammar rule of the format `left => JsUnknown*`. 

There's no such rule for `JsAnySwitchClause` that allows any `unknown` node. That's why having an unknown node as a direct child of `JsSwitchStatement` is invalid. 

We can argue whatever we should keep it as a `JsDefaultClause`. I believe that we should have a single rule what to do with nodes that aren't valid in this context and this is to wrap them as `Unknown` to make it clear that this syntax isn't valid. We need to do the same if we find a `with` statement in strict mode, `import/export` statements inside scripts or not at the top of the file.

I do like your suggestion to not put it into the statement but instead interpret the `default` as the `discriminant` of the `case` clause. I wasn't aware that JS allows expressions for case clause discriminates: 

```
- switch
  - default_clause:
    - ...
   - case_clause:
     - missing "catch" token
     - discriminant: 
       - JsUnknownExpression
         - default token
       - colon: ':'
       - body (if any)
```

2021-11-29 13:40 UTC, MichaReiser commented
Can we give this PR a more descriptive title? 
I know, it's hard because it changes many different methods. But even something like `use new parse API for simple statements`. 

* `parse_parameter_list` You only changed the name but it still returns a `CompletedMarker`. 

We should add tests for every migrated statement testing the valid and error cases. This also allows us to verify if we're adding the right amount of missing markers.

2021-11-29 13:43 UTC, MichaReiser reviewed
There are some more places where I believe we should use `or_missing_with_err` and the switch structure isn't correct yet (having the AST facade as part of the tests will help verify the correctness, especially #1829 )

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/decl.rs
> +	parse_parameters_list(p, parse_formal_param_pat);
Should this return `Absent` if the current token isn't `(`?

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/decl.rs
> +			if let Present(res) = parse_param(p) {
Can we use our new error recovery here? 

```
let result = parse_param(p).or_recover(p, ParseRecovery::new(
    JS_UNKNOWN_PATTERN,
    token_set![
		T![ident],
		T![await],
		T![yield],
		T![,],
		T!['['],
		T![...],
		T![')'],
    ]).enable_recovery_on_line_break());

if let Ok(result) {
    if result.kind() == ASSIGN_PATTERN && p.state.in_binding_list_for_signature ... 
} else {
    break;
}
```

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +				parse_parameter_list(p).or_missing(p);
Isn't the parameter list mandatory?

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +						parse_parameter_list(p).or_missing(p);
Isn't the parameter list mandatory? At the other hand, it can never be missing if we're at a `(` token. So `or_missing` should be fine (or even `ok()`)

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/function.rs
> +	parse_parameter_list(guard).or_missing(guard);
The parameter list is mandatory

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/object.rs
> +	parse_parameter_list(p).or_missing(p);
The parameter list is required.

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +				p.bump_remap(JS_UNKNOWN_PATTERN);
This isn't valid. A token can never have the type `JS_UNKNOWN_PATTERN`. 

I liked your suggestion to create a `JS_CASE_CLAUSE` in that case where we interpret the `default` keyword as the `discriminant`. 

```
let case_kind = if first_default.is_some() {
    p.missing(); // Missing 'case' clause
    let discriminant = p.start();
    p.bump_any(); // interpret `default` as the discriminant
    discriminant.complete();
    JS_CASE_CLAUSE
} else {
    p.bump_any();
    JS_DEFAULT_CLAUSE
}
```

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	// switch { var i = 0 }
Can we add a test case for multiple `default` clauses?

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/paren_or_arrow_expr_invalid_params.rast
> +4 │
This looks a bit weird. Do you know why it isn't pointing to any valid source? Is it because it is at the EOF?

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/setter_class_member.rast
> +error[SyntaxError]: expected a parameter but instead found '{'
This recovery looks weird but I guess it's becaues pattern contains some code to do error recovery which then moves the parser position till after the `)` (and adds two errors)

2021-11-29 13:43 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/switch_stmt_err.rast
> +error[SyntaxError]: expected `'}'` but instead found `var`
Do you know why we generate two errors pointing to the `var`? 

Is it because the var eats over the switch? 

Would it result in better error recovery if we wrap any statements inside of a `CASE_CLAUSE`?

Let's say we could do this (maybe not today, but in the future)

```
match p.cur() {
    T![default] => ... 
    T![case] => ...
    _ => {


        // We found some content that isn't a case nor default clause. Let's assume the author forgot the default/case or deleted it
        // Ideally, loop and eat all statements but eating a statement one by one works to

        let m = p.start();
        p.missing(); // case
        p.missing(); // discriminant
        p.missing(); // colon

        let recovered = statement(p).or_recover(p, ParseRecovery::new(JS_UNKNOWN_STATEMENT, token_set![T![default], T![case], T!['}']]));

        if recovered.is_err() {
            // Can only happen at the EOF or when we reached T![}] but this method should never be called for those positions
            // Maybe use `unreachable` instead?
            m.abandon();
            return None;
        }
    }
}
```

2021-11-29 14:55 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/paren_or_arrow_expr_invalid_params.rast
> +4 │
I strongly believe that the issue is the function `pattern`, which moves the parser forward too much

2021-11-29 15:00 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/setter_class_member.rast
> +error[SyntaxError]: expected a parameter but instead found '{'
Exactly

2021-11-29 15:22 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/switch_stmt_err.rast
> +error[SyntaxError]: expected `'}'` but instead found `var`
Your suggestion was really useful! I managed to fix a couple of issues!

2021-11-30 07:07 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/decl.rs
> +pub(super) fn parse_parameter_list(p: &mut Parser) -> ParsedSyntax {
Not related to your changes but took me an awfully long time to spot the difference between `parse_parameter_list` and `parse_parameters_list`. 

Not sure what other names we could use for the generic one: Maybe `parse_parameter_list_impl`, `parse_parameter_list_common`. Or we rename `parse_parameter_list` to `parse_function_parameter_list` but that may be confusing because it then no longer matches the name in the grammar file.

2021-11-30 07:09 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +							.or_missing_with_error(p, js_parse_error::expected_parameters);
You won't need the `or_missing_with_error` because the `if parsed_parameters.is_absent` already covers the case where it is missing.
```suggestion
					let parsed_parameters = parse_parameter_list(p);
					if parsed_parameters.is_absent() {
						let m = p.start();
						// test_err async_arrow_expr_await_parameter
						// let a = async await => {}
						p.bump_remap(T![ident]);
						m.complete(p, JS_IDENTIFIER_BINDING);
					} 
```

2021-11-30 07:18 UTC, MichaReiser approved these changes
Looks all good. There are mostly a few nits. The only thing that needs to be fixed before landing is the type of the `discriminant` in the case of multiple default clauses.

2021-11-30 07:18 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +				discriminant.complete(p, IDENT);
This must be a `JsUnknownExpression`. The `discriminant` must be a `expression`.

2021-11-30 07:18 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
>  				.precede(p)
Nit: You can use `parse_literal_expression(p).precede_or_missing()`
```suggestion
			parse_literal_expression(p)
				.precede_or_missing(p)
```

2021-11-30 07:18 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/switch_stmt_err.rast
> +        1: JS_CASE_CLAUSE@65..80
Nice!

2021-11-30 08:49 UTC, ematipico commented on crates/rslint_parser/src/syntax/decl.rs
> +pub(super) fn parse_parameter_list(p: &mut Parser) -> ParsedSyntax {
I would personally remove one of the functions. It's too confusing

2021-11-30 08:54 UTC, ematipico commented
Thank you @MichaReiser for your patience!

2021-11-30 09:07 UTC, merged