Implement formatter todos
rome/tools pull request #1845
Opened 2021-12-02 09:00 UTC by Boshen

## Summary
This PR implements most of the todos in `rome_formatter/src/ts/expressions/expression.rs`
And fixes:
* incorrect `import.meta` syntax
* incorrect `/=` `**=` for JsAssignmentExpression

This PR is rebased onto https://github.com/rome/tools/pull/1843 for passing tests for `a >> b`
## Test Plan
See updated formatter tests

2021-12-02 09:06 UTC, Boshen commented
btw I can't figure out what syntax `TsAssertion` and `TsConstAssertion` is 😿 , rslint gives no hint either
```
TsAssertion = expr:JsAnyExpression ident: Ident '<' ty:TsType '>'
TsConstAssertion = expr:JsAnyExpression ident: Ident '<' 'const' '>'
```

2021-12-02 09:38 UTC, ematipico commented
> btw I can't figure out what syntax `TsAssertion` and `TsConstAssertion` is 😿 , rslint gives no hint either
> 
> ```
> TsAssertion = expr:JsAnyExpression ident: Ident '<' ty:TsType '>'
> TsConstAssertion = expr:JsAnyExpression ident: Ident '<' 'const' '>'
> ```

You ignore anything related to TypeScript at the moment. We need to review it and probably it will change drastically.

2021-12-02 09:42 UTC, MichaReiser reviewed
This is amazing, thank you!

I believe private names aren't printed correctly yet. 

There's also the question how far you wanna go. There are some expressions that should break if exceeding the line width but I'm fine if we leave this as is for now and tackle it in later PRs.

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/any_reference_member.rs
> +		formatter.format_token(&self.name_token()?)
Private names have the form `#name` where the `#` is its own token inside private member. So you need to visit (format) the `#` token too to make sure it doesn't get lost. I'm a bit surprised that the test is passing

2021-12-02 09:42 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/ok/import_meta.rast
> +                meta_token: missing (required),
Seems like the parser isn't parsing the meta token. I'll be working on `import` soon. Should we defer adding the meta token until then?

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +		// TODO handle `+` `-` `~` `!`
Why do they need special handling?

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +		};
Oh, the return-type of `right` on `BinaryExpression` is incorrect. `right` should return a `SyntaxResult<JsAnyExpression>` Would you mind changing the implementation?

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +		])
Can you add a test case that exceeds the 80 character line width?  We then want to wrap the condition over multiple lines. Similar to rome classic

https://github.com/rome/tools/blob/c76ccc0345fe00ea4b3f684424065d05c3ab3abe/internal/formatter/builders/js/expressions/JSConditionalExpression.ts#L48-L68

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +	}
This is fine for now but we probably want to print binary expressions across multiple lines if they get very long, similar to what rome classic

https://github.com/rome/tools/blob/8edbed0c3505c8ed3724015df83817c2a92acce8/internal/formatter/builders/js/expressions/JSBinaryExpression.ts#L19-L81

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +	}
We may want to make sure that assignments can break if they're very long (or concatenated)

https://github.com/rome/tools/blob/8dcd9dde2b0c3d850f24279c472e0e2fd90bb0af/internal/formatter/builders/js/utils.ts#L271-L285

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
I just checked the grammar and this seems to be a dead node. The `ImportMeta` node is never used on the right-hand side of any other rule. I think we can delete this.

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +	}
Same as for binary expression, we probably want to indent the right hand side if the expressions are very long

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/conditional.js
> +	: (g + h)
I think it should be fine to print these on a single line because the whole expression isn't exceeding the line width. 

Can we add another example for a conditional that exceeds 80 character line width? Maybe even with nesting?

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/expression.js
> +x && y
Can we add some examples that exceed the line width? Maybe even with nesting?

2021-12-02 09:42 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/static_member.expected.js
> +e.#f
Shouldn't there be a `;` too?
```suggestion
e.#f;
```

2021-12-02 12:39 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/static_member.expected.js
> +e.#f
Hah! I thought this was a bug somewhere, and then I printed the diagnostics and saw ”private identifiers are unsupported“. I'll remove this test for now.

2021-12-02 13:11 UTC, Boshen commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +		// TODO handle `+` `-` `~` `!`
We need to handle spacing for `+` `-` `~` `!` vs `void` `delete` `typeof`, fixed in 1936dd0

2021-12-02 13:12 UTC, Boshen commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +		};
fixed in 0b01cd5

2021-12-02 13:13 UTC, Boshen commented on crates/rslint_parser/test_data/inline/ok/import_meta.rast
> +                meta_token: missing (required),
We can leave it here and fix later I think.

2021-12-02 13:15 UTC, Boshen commented on crates/rome_formatter/src/ts/expressions/any_reference_member.rs
> +		formatter.format_token(&self.name_token()?)
fixed in e311e73, although the parser hasn't implemented this yet :-( (which is why the test looked strange ... removed the test for now)

2021-12-02 13:17 UTC, Boshen commented
@MichaReiser All actionable items are done, we can work on the finer details later, let's put more focus on the parser for now 😀

2021-12-02 13:31 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/ok/import_meta.rast
> +                meta_token: missing (required),
We shouldn't have any parsing errors in any file inside of the `ok` folder and this is a parsing error. The easiest will be to just remove the whole grammar for now since it isn't supported anyway.

2021-12-03 09:04 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/static_member.expected.js
> +c?.d;
"private identifiers are unsupported" in the parser 😢 
https://github.com/rome/tools/blob/main/crates/rslint_parser/src/syntax/expr.rs#L531

I should probably look into outputting all the error diagnostics from the parser when running formatter tests, the formatter currently can give the wrong result which looks correct...

2021-12-03 09:08 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/static_member.expected.js
> +c?.d;
Makes sense, you have to create a snippet with a class:

```js
class B {
	foo() { #a.b }
}
```

etc.

2021-12-03 09:29 UTC, ematipico requested changes
Thank you for tackling this! :)

I would expand the test base with long names and see how the formatter behaves.

We use Prettier as reference, so use it in case you don't know how to format something!

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
Would you mind moving this inside a `class.rs` file? Ideally we should move there all formatters related to `class`

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
To move to a `class.rs` file

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
Let's move it into a `template.rs` file. This will change and probably might have some custom logic

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
Let's move it inside a `function.rs` file. There we will have also `JsFunctionDeclaration`

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
It's worth moving this inside a `import/meta.rs` file

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
Inside a `import/mod.rs` file

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
Can we just have a `todo!()` here?

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
We could move these inside a `update_expressions.rs` file. What do you think?

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/class.expected.js
> +x = class foo extends Boar {};
Let's add a test with a veeeery long names, both the class name and the super class.

If you're not sure what to do, we use Prettier as a reference

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/function.js
> +  yield* x
Let's add a couple of tests where `argument` (`x`) is really long

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/import.js
> +import(x)
Let's add a test with an argument that has a long name

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/new.expected.js
> +new b(x);
Let's add a test with an argument that has a long name. Same for function name

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/parenthesized.js
> +(1)
Let's add a test with an argument that has a long name

2021-12-03 09:29 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/unary.js
> +x = !1
Let's test with long names too

2021-12-03 09:30 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/static_member.expected.js
> +c?.d;
Shall we skip `#` for now? I played around a bit and the parser just breaks when it sees `#`

2021-12-03 13:14 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/static_member.expected.js
> +e.#f
Should work fine after  #1851 landed

2021-12-03 13:14 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/static_member.expected.js
> +c?.d;
#1851  enables class field support

2021-12-03 17:04 UTC, Boshen commented
@MichaReiser @ematipico 
Rebased and updated with e534c7a and f4d5a2e

The formatter tests need a lot more work after looking at the prettier tests,
I'm currently just using the tests for TDD and guiding me through the parser.

2021-12-03 17:13 UTC, Boshen commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
done

2021-12-03 17:15 UTC, Boshen commented on crates/rslint_parser/test_data/inline/ok/import_meta.rast
> +                meta_token: missing (required),
> We shouldn't have any parsing errors in any file inside of the ok folder and this is a parsing error. The easiest will be to just remove the whole grammar for now since it isn't supported anyway.

I have reverted the change.

2021-12-08 07:24 UTC, MichaReiser reviewed
Looks good. Would you mind rebasing your changes and address the last two comments?

2021-12-08 07:24 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/expression.rs
> +}
Delete, empty implementations are misleading. It's better to get a compile error in that case

2021-12-08 07:24 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/module.expected.js
> +import.
This doesn't seem to do any formatting. Can we delete this test (and the format implementation?)

2021-12-08 08:25 UTC, Boshen commented
@MichaReiser rebased and squashed, removed:
* Template
* TsNonNull
* JsStaticMemberExpression (this introduced JsAnyName which is also a todo)

2021-12-08 08:59 UTC, merged