refactor: parse class
rome/tools pull request #1846
Opened 2021-12-02 14:56 UTC by ematipico

## Summary

This PR moves all methods inside `class.rs` to use the new syntax `ParsedSyntax`

- all methods that return `ParsedSyntax` now have the prefix `parse_` in their name
- applied error recovery inside the creation of the list of members
- split up some errors into two different files because the line of code highlighted was causing issues
	```js
	class extends {}  // <=== this one
	class B {}
	```
	Basically everything after the `{}` was being parsed - as expected - as an expression, causing loads of errors that were not related to what we wanted to test
- renamed boolean function with `is_at`
- added new tests
- fixed some range issue inside existing tests

## Test Plan

Existing CI

2021-12-02 14:57 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +					.primary(class_token.start..guard.cur_tok().range.start, "");
This error was pointing to a single token, now it shows better

2021-12-02 14:58 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/block_stmt_in_class.rast
> +          0: L_CURLY@8..9 "{" [] []
This is still weird and I need to understand what's going on

2021-12-02 14:59 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/class_decl_err.rast
> +      1: (empty)
We are now adding a missing token for the name of the class (which matches our AST)

2021-12-03 07:20 UTC, MichaReiser requested changes
Thanks for extending the test cases and tackling classes in the first place! 

The parse methods still add many `ERROR` nodes in places they're not permitted. I suggest adding test cases for all of them and then figure out a way how to avoid them

The `parse_members` method often *progresses* parsing and then returns `Absent`. This violates the contract of `ParsedSyntax` that guarantees a caller that a parse method eats no tokens nor produces any errors if it returns `Absent`. This is important because we otherwise loose tokens.

2021-12-03 07:20 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +	parse_class_member_name(p).or_missing_with_error(p, js_parse_error::expected_function_body);
These functions don't strictly comply to the `-> ParsedSyntax` protocol. For example, they don't test if they can parse any valid node and otherwise return `Absent`. That's why I'm not sure if these methods should not instead return a `CompletedMarker` to make this clear (at least all the ones that are internal). 

This would also simplify the code above because you don't need to test if the result is `Present`.

2021-12-03 07:20 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +	Absent
That's not valid. A `parse_*` method should either return `Absent` AND not progress parsing (completing a node progresses parsing) or progress parsing. You can return an `Invalid` ConditionalSyntax hear that the caller then must handle

2021-12-03 07:20 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +	// TODO: these two functions should return `ParsedSyntax`, so we can handle possible errors/missing/etc.
TODO?

2021-12-03 07:20 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +	parse_class_members(&mut *guard).or_missing(&mut *guard);
These can never be missing because it's a list.

2021-12-03 07:20 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +fn parse_class_members(p: &mut Parser) -> ParsedSyntax {
I would leave the method return type as a `CompletedMarker` (does it even need to return a marker at all? It isn't used by any caller)

* It's an internal `parse_` method
* It never returns `Absent`

2021-12-03 07:20 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +fn parse_class_member(p: &mut Parser) -> ParsedSyntax {
I think this method should return a `ConditionalParsedSyntax` in case it parsed a member but it turned out to be invalid.

2021-12-03 07:20 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
>  			let msg = if p.typescript() {
This `else` branch will eat the `declare` keyword and wrap it in an `Error` for JS. I don't think we should do this and instead should return `Invalid` in that case (at the very end of parsing the member). Not sure how to do that best without having too much repetitive code because this method has so much branching. ... 

Another option could be to create a checkpoint at the begining of the parse method and rewind whenever you find an error and then return `Absent` so that the error recovery of the loop kicks in. 

Downside, we'll end up with two errors: 1) expected a member, 2) declare modifiers not valid.

Same for all the other errors created in this method.

2021-12-03 07:20 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +				Absent
I believe returning `Absent` here isn't valid because the `parse_` method has already consumed some tokens that are now lost (e.g. all modifiers).

2021-12-03 07:20 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +) -> ParsedSyntax {
I wouldn't change the return type of these internal methods because

* parse_members expects that they succeed parsing the child. `parse_members` is a special union rule because it "consumes" tokens itself. So, it would be invalid if `parse_members` eat all modifiers and then this method returns `Absent`
* The function also accepts an already started marker
* The method never returns `Absent`

2021-12-03 09:37 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +	// TODO: these two functions should return `ParsedSyntax`, so we can handle possible errors/missing/etc.
I don't know how to reply to this comment

2021-12-03 09:39 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +fn parse_class_members(p: &mut Parser) -> ParsedSyntax {
Yeah makes sense, I see now that it's a recurring pattern

2021-12-03 09:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +	// TODO: these two functions should return `ParsedSyntax`, so we can handle possible errors/missing/etc.
haha... I was wondering if this is something you want to address later or if it's something that should be done as part of this PR

2021-12-03 11:28 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +	// TODO: these two functions should return `ParsedSyntax`, so we can handle possible errors/missing/etc.
LOL! It's something I want to address later and added a TODO about what should be done

2021-12-03 12:26 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
>  			let msg = if p.typescript() {
Would it be OK to leave a `TODO` here? It's more related to the typescript parsing and not to the whole refactor to `ParsedSyntax`. I mean, the bug it's been there for some time and can be fixed anytime we want

2021-12-03 13:44 UTC, MichaReiser reviewed
Can we give this PR a more descriptive title: 

Refine class error recovery (altough, we don't do this completely)

2021-12-03 13:44 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/class_constructor_err.rast
> +1 │ class B { static constructor() {} }
Can we add a suggestion, remove the `static` keyword here?

2021-12-03 13:44 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/class_decl_err.rast
> +                    body: JsFunctionBody {
Nice, Thanks!

2021-12-03 16:03 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +				conditional_syntax.abandon(p);
This doesn't work as you expect. It will expect all that has currently been parsed to the list instead of wrapping it inside a `UNKNOWN_MEMBER`. See my comment above on how to do error recovery in this case.

2021-12-03 16:03 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +/// The method can panic if [parse_class_member] returns [ParsedSyntax::Absent]
Is this still the case?

2021-12-03 16:05 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +		//  Not that if we get a [ParsedSyntax::Absent], we want to panic
Is this still true? 

What you could do instead (instead of the complicated error recovery I suggest above) is to create a checkpoint right before parsing the member and then restore it in the case the parsed member is invalid (to rewind the parser and throw away any errors). The next step is then to trigger the error recovery as you're used to.

2021-12-06 11:06 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
>  			let msg = if p.typescript() {
> I don't feel super comfortable about this because it is not TypeScript specific.

Actually, it is. All the errors where we have `ERROR` here are due to TypeScript syntax, and the use of particular keyword like `declare` inside a JavaScript file.  

In order to properly fix all these errors, we have to rethink few stuff:

- proper use of `ParsedSyntax<ConditionalSyntax>` inside logic where we expect TS or not;
- re think the grammar of the modifiers. I think we can use the same logic we proposed for class names, and introduce something like `JsAnyModifier` (`static` falls under the modifier definition). In this way, we can better invalidate the green without invalidating the whole class member. I did this change and it will be included in this PR for handling the `declare` keyword;

> My issue with that is that it is difficult to know what progress we make.

We're both in the same both, but this PR has already loads of feedback and it requires more changes, in the logic too.

2021-12-06 11:30 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
>  			let msg = if p.typescript() {
Agree on the outcome. It's just that the current recovery will "break" js files as well.

2021-12-06 11:32 UTC, MichaReiser commented on xtask/js.ungram
> +	modifiers: JsAnyModifier?
Should modifiers be a list? If so, should access, abstract, static and so on be modifiers too?

2021-12-06 11:46 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +				m.complete(p, JS_UNKNOWN_MEMBER);
Why does this create a new member?

2021-12-06 11:46 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +	) -> Self {
Nit: Initializing (some/most) fields with defaults and instead have `setters` may simplify the code a bit? Mainly because it's hard to guess the parameters when reading something like: `true, false, false, true`

2021-12-06 11:46 UTC, MichaReiser commented on xtask/js.ungram
> +	modifiers: JsAnyModifier?
I just saw your explanation in the summary. 

I'm a bit undecided if a `modifiers` list is a good idea. Certainly, there's the advantage that we can recover from invalid modifiers but there's the downside that we can't enforce the correct order, a transformer could construct `static declare public test()`; 

What's the main benefit of changing the declaration here even if we don't support ts?

Why is this only for properties and not all other members?

2021-12-06 11:46 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +	let mut declare_diagnostic = None;
Nit. It seems `declare_remapped` always seems to be true when `declare_diagnostic` is some. Is it sufficient to only track one state variable?

2021-12-06 11:46 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +			declare_remapped = true;
It doesn't seem like `declare` gets remapped here. What's the meaning of `remapped?`

2021-12-06 13:28 UTC, ematipico commented on xtask/js.ungram
> +	modifiers: JsAnyModifier?
> the downside that we can't enforce the correct order

I don't think it will be an issue. I think there aren't rules around ordering. If so, we can have a lint rule for that.

> What's the main benefit of changing the declaration here even if we don't support ts?

I wanted to address your previous feedback and ended up starting this solution, which I didn't want to revert. My next PR will apply this new grammar to all the modifiers.

> Why is this only for properties and not all other members?

It will be for all members

2021-12-06 14:37 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +				m.complete(p, JS_UNKNOWN_MEMBER);
Good catch, it should be a `JS_UNKNOWN_MODIFIER`

2021-12-06 14:59 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +			declare_remapped = true;
That was not needed anymore, removed it.

2021-12-07 06:54 UTC, MichaReiser approved these changes
Let's go!

Would you mind adding a TODO to the modifier in the grammar to make it clear, this isn't finalized yet?

2021-12-07 06:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
>  	}
You can derive `default` with `#[derive(Default)]` because all type implement default

2021-12-07 06:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +	// }
Delete?

2021-12-07 06:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +	}
Nit: I would probably create two methods, because `dont_remap_static(true)` is a bit confusing. Or just name all of them `set_remap_static`, `set_accessibility`, etc (`has_accessibility` is also a bit confusing because `has` is often used to query a `boolean` value, not to set one)

2021-12-07 09:11 UTC, merged