Binding, Patterns, and Identifier naming
rome/tools pull request #1854
Opened 2021-12-06 11:55 UTC by MichaReiser

## Summary

Part of the naming improvements #1819 suggested by @jamiebuilds and a preparation to implement `import`/`export`

* Refines naming of `Binding`s:
  * `JsAnyBinding` is only a `JsIdentifierBinding` or a `JsUnknownBinding`. 
  * Change `id`s to use `JsAnyBinding` instead of `JsUnknownBinding` to allow local error-recovery
  * Rename object and array bindings to `JsArrayBindingPattern` and `JsObjectBindingPattern`
* Refines naming of assignment targets
  * `JsAnyAssignment` now is a union over `StaticMemberAssignment`, `ComputedMemberAssignment`, `UnknownAssignment`, and `IdentifierAssignment`
  * Rename the array and object patterns to `JsArrayAssignmentPattern` and `JsObjectAssignmentPattern`
* Introduce `JsReferenceIdentifier` for identifiers referencing a variable from the current scope. Main reason is to avoid using `IdentifierExpression` in `ShorthandProperties` and `export { name, name2 }` because these names aren't expressions
* Replace `MemberReference` with `JsName`. `JsName` will be used anywhere where an identifier is neither a binding nor a reference (member expression, `import {x as name}`, ...).

## Test Plan

2021-12-06 11:59 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/assignment.rs
> +		JS_PARENTHESIZED_EXPRESSION
Hmm, unclear why git doesn't recognise this as the same file as `assignment_target`. I mainly changed this method. I only did renames in the other methods.

2021-12-06 12:06 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	if p.nth_at(1, T![:]) {
No need to first parse an expression and then test if this is a labelled statement. We can simply look if the next token is the colon and if so, treat it as a labelled statement.

2021-12-06 14:18 UTC, xunilrj approved these changes

2021-12-07 11:20 UTC, ematipico requested changes

2021-12-07 11:20 UTC, ematipico commented on crates/rslint_parser/src/parser.rs
> +		}
What are we fixing here?

2021-12-07 11:20 UTC, ematipico commented on crates/rslint_parser/src/syntax/expr.rs
> +				| "interface" | "static"
`"protected"`, for example, will emit a false negative. Meaning that the usage of that keyword is illegal only in a TypeScript context but JavaScript can use it and it should emit no errors.

We have to revisit the logic and reduce the check only to JS keywords if TS is not enabled.

2021-12-07 11:20 UTC, ematipico commented on crates/rslint_parser/src/syntax/object.rs
> +fn is_nth_at_object_member_name(offset: usize, p: &Parser) -> bool {
```rust
fn is_nth_at_object_member_name(p: &Parser, offset: usize) -> bool {
```

nit: I would swap the arguments; most of the times we put the parser in the first place

2021-12-07 12:28 UTC, MichaReiser commented on crates/rslint_parser/src/parser.rs
> +		}
Let's revert this change. I thought it's needed to use `split_off` in the `rewrite_events` but that's not the case (I must have had another bug in the implementation).

2021-12-07 12:30 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +				| "interface" | "static"
`protected` is not a valid JS identifier in strict mode

>  It is a Syntax Error if this phrase is contained in strict mode code and the StringValue of IdentifierName is: "implements", "interface", "let", "package", "private", "protected", "public", "static", or "yield". 

Source: https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-identifiers-static-semantics-early-errors

You can also see this from the number of fixed tests

```
xtask/src/coverage/test262/test\language\future-reserved-words\implements-strict.js
xtask/src/coverage/test262/test\language\future-reserved-words\interface-strict.js
xtask/src/coverage/test262/test\language\future-reserved-words\package-strict.js
xtask/src/coverage/test262/test\language\future-reserved-words\private-strict.js
xtask/src/coverage/test262/test\language\future-reserved-words\protected-strict.js
xtask/src/coverage/test262/test\language\future-reserved-words\public-strict.js
xtask/src/coverage/test262/test\language\future-reserved-words\static-strict.js
```

> We have to revisit the logic and reduce the check only to JS keywords if TS is not enabled.

It should be fine even in TS context. We only need to make sure to first eat all accessibility modifiers before calling `parse_identifier` (if we then expect any accessibility modifiers).

2021-12-07 13:34 UTC, ematipico commented on crates/rslint_parser/src/syntax/expr.rs
> +				| "interface" | "static"
OK this is new to me 😱

2021-12-07 13:35 UTC, ematipico approved these changes

2021-12-07 14:01 UTC, merged