Parse Import module item
rome/tools pull request #1856
Opened 2021-12-07 16:48 UTC by MichaReiser

## Summary

Implements the parsing of `import` module items as specified in #1819. 

## Test Plan

2021-12-07 16:53 UTC, MichaReiser commented on xtask/js.ungram
> +JsUnknownAssignment = SyntaxElement*
@jamiebuilds any feedback on the grammar changes

2021-12-08 11:36 UTC, MichaReiser commented on xtask/js.ungram
> +JsUnknown = SyntaxElement*
I introduced the generic `JsUnknown` because it feels like having an `Unknown` node for every case where we have a list feels a bit overkill but not having an unknown node otherwise results in invalid syntax bubbling up quite far up the tree (for example, an invalid specifier inside of a named import invalidates the specifier list, the named import clause and the import statement).

2021-12-08 13:39 UTC, ematipico requested changes

2021-12-08 13:39 UTC, ematipico commented on crates/rslint_parser/src/syntax/module.rs
> +	parse_module_source(p).or_missing_with_error(p, expected_module_source);
Should we add an error test case for `import "a" from 4`?

2021-12-08 13:39 UTC, ematipico commented on crates/rslint_parser/src/syntax/module.rs
> +			.or_invalid_to_unknown(p, JS_UNKNOWN)
Why not `JS_UNKNOWN_EXPRESSION`?

2021-12-08 13:39 UTC, ematipico commented on crates/rslint_parser/src/syntax/module.rs
> +fn parse_import_assertion(p: &mut Parser) -> ParsedSyntax<CompletedMarker> {
I think the whole assertion syntax should be `ParsedSyntax<ConditionalSyntax>` because it's still a language feature that is not supported by all runtimes/browsers.

2021-12-08 13:39 UTC, ematipico commented on crates/rslint_parser/src/syntax/module.rs
> +				expected_any(&["identifier", "string literal"], p.cur_tok().range).to_diagnostic(p),
We can move this error inside `js_parse_errors.rs`

2021-12-08 13:39 UTC, ematipico commented on crates/rslint_parser/src/syntax/module.rs
> +fn expect_keyword(p: &mut Parser, keyword_name: &str, kind: SyntaxKind) {
I think this function can be moved inside `util.rs`, it seems a function that other parts of the parser can benefit from

2021-12-08 13:39 UTC, ematipico commented on crates/rslint_parser/src/syntax/module.rs
> +}
Should we move these little fellas inside `js_parse_errors.rs`

2021-12-08 13:39 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/import_assertion_err.rast
> +  │          ^^^^ a second use of `type` here is not allowed
I think this error is not correct... or is it? 🤔

2021-12-08 13:39 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/import_assertion_err.rast
> +8 │ import foo from "foo.json" assert { type: "json", lazy: true, startAtLine: 1 };
This error is not correct, we are showing an internal `SyntaxKind`

2021-12-08 13:39 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/import_assertion_err.rast
> +  │                                                                            ^ unexpected
We're printing an internal `SyntaxKind`

2021-12-08 13:39 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/import_err.rast
> +  │          ^^^^^^^- add `as identifier` here
The backtick \` should finish after `as`

2021-12-08 14:12 UTC, MichaReiser commented on xtask/js.ungram
> +	assertion: JsImportAssertion?
The semicolon is part of the `JsImport` rule

2021-12-08 14:16 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/module.rs
> +			.or_invalid_to_unknown(p, JS_UNKNOWN)
Because `expressions` arent' allowed in an assertion entry. That's why I added the `JS_UNKNOWN` so that I don't need to add a `JsUnknownAssertionEntry` and `JsUnknownNamedImportSpecifier`

2021-12-08 14:17 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/module.rs
> +fn parse_import_assertion(p: &mut Parser) -> ParsedSyntax<CompletedMarker> {
Let's leave it as is until we revisit our syntax features. There's currently no way to enable / disable features in inline tests.

2021-12-08 14:24 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/import_assertion_err.rast
> +  │          ^^^^ a second use of `type` here is not allowed
This is actually correct, I mean, as correct as error recovery can be. We could probably still do better by adding custom recovery from `\u{61}assert` or when the assert is on the next line. 

The reason why we get this error is that the assert expressions for these two statements are parsed as block statements, each containing a labelled statement. 

```
import "foo" \u{61}ssert { type: "json" };
assert { type: "json" }
```

2021-12-08 14:27 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/module.rs
> +				expected_any(&["identifier", "string literal"], p.cur_tok().range).to_diagnostic(p),
I so far added errors to `js_parse_errors` if they appeared in different places throughout the program, potentially in different rust files but kept other errors local in the same rust file (if used multiple times) or inline if used only once.

2021-12-08 14:50 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/module.rs
> +// import foo from "test";
I have some generic test cases on `parse_import` where I added this example too. The parser recovers but not very nice. The problem is that we can't stuff the number literal 4 somewhere into the import statement. This will only be possible if we introduce something like a `GarbageTrivia`

2021-12-08 14:53 UTC, MichaReiser commented
> Would you mind revert this change, please? It doesn't seem this change is related to this PR and it also goes in conflict with what I've done in #1859

It is related to this change because I unified all these one-off `Unknown` nodes into one generic `Unkown` . This diff otherwise needs to introduce a `JsUnknownNamedImportSpecifier` and `JsUnknownImportAssertionEntry` and I believe that a generic `Unknown` is as good in these places as having separate ones (you can still see in the grammar where they might appear). 

But I'm open to go back to specific unknown nodes but would love to understand your reasoning behind it.

2021-12-08 15:04 UTC, ematipico commented on crates/rslint_parser/src/syntax/module.rs
> +				expected_any(&["identifier", "string literal"], p.cur_tok().range).to_diagnostic(p),
In old RomeJS we had all diagnostics stored in one single place and I kind liked it.

2021-12-08 15:09 UTC, MichaReiser commented on xtask/js.ungram
> +JsUnknownAssignment = SyntaxElement*
@jamiebuilds is off. Let's move on with what we have and revisit if needed

2021-12-08 15:14 UTC, ematipico commented
> > Would you mind revert this change, please? It doesn't seem this change is related to this PR and it also goes in conflict with what I've done in #1859
> 
> It is related to this change because I unified all these one-off `Unknown` nodes into one generic `Unkown` . This diff otherwise needs to introduce a `JsUnknownNamedImportSpecifier` and `JsUnknownImportAssertionEntry` and I believe that a generic `Unknown` is as good in these places as having separate ones (you can still see in the grammar where they might appear).
> 
> But I'm open to go back to specific unknown nodes but would love to understand your reasoning behind it.

I think having specialized unknown nodes help:

- to understand what kind grammar was supposed to be there (expression, statement, binding, etc.)
- to understand what grammar we are parsing while we write code
- analyzers might, in the future, to act differently based on the type of unknown nodes (visit children VS do nothing)


I think having a broad unknown node could increase uncertainty of when using using a generic unknown node or a specialized one. For example you used it here in this PR but suggested its use in another one. Where's bar? When should we use it? I really liked specialized unknown nodes.

2021-12-08 15:46 UTC, MichaReiser commented
> > > Would you mind revert this change, please? It doesn't seem this change is related to this PR and it also goes in conflict with what I've done in #1859
> > 
> > 
> > It is related to this change because I unified all these one-off `Unknown` nodes into one generic `Unkown` . This diff otherwise needs to introduce a `JsUnknownNamedImportSpecifier` and `JsUnknownImportAssertionEntry` and I believe that a generic `Unknown` is as good in these places as having separate ones (you can still see in the grammar where they might appear).
> > But I'm open to go back to specific unknown nodes but would love to understand your reasoning behind it.
> 
> I think having specialized unknown nodes help:
> 
>     * to understand what kind grammar was supposed to be there (expression, statement, binding, etc.)
> 
>     * to understand what grammar we are parsing while we write code
> 
>     * analyzers might, in the future, to act differently based on the type of unknown nodes (visit children VS do nothing)
> 
> 
> I think having a broad unknown node could increase uncertainty of when using using a generic unknown node or a specialized one. For example you used it here in this PR but suggested its use in another one. Where's bar? When should we use one or the other? I really liked specialized unknown nodes.

I reverted the change. Mainly because it shouldn't be part of this PR. We can decide to introduce a generic `Unknown` if we see that things go over board and introduce it in a dedicated PR

2021-12-09 13:26 UTC, ematipico approved these changes

2021-12-09 16:11 UTC, merged