feat: parse class members
rome/tools pull request #1859
Opened 2021-12-08 11:24 UTC by ematipico

## Summary

This PR fixes all the issues that we were having inside error handling inside classes.

The majority of errors were around TypeScript syntax, although the handling wasn't correct and that was resulting in tokens that were skipped and green tree incorrect.

In order to fix all these errors, I had to change a bit the current grammar, here's the list of changes:

- now all class members and properties, inside the grammar, will have a `JsAnyModifier` that will include `static`, `declare` and `abstract`. This will allow us to invalidate only those words without invalidating the whole member/property. This change of grammar includes a `JsUnknownModifier` node. The fix node includes a `missing` token when the modifier is not there;
- `extends` and `implements` clauses are now correctly marked as missing in case they are not there; in case of errors we mark them as `JS_UNKNOWN_EXPRESSION`, this is because we don't have specific nodes. Although this results in a decent solution because the parser invalidates only the portion `extends A, B, C`, leaving the rest of the class in a correct state; 
- the operators `?` and `!` are now correctly marked as `missing` when they are not there;
- the access modifiers `readonly` and `private` are now wrapped inside a node called `TsAnyAccessibility`, which follows the same principle of `JsAnyModifier`. This will allow us to invalidate only those words. Because of the fact that these modifiers belong to TS only, errors are wrapped into an unknown node called `TsUnknownAccessibilityModifier`;
- update the formatter implementation;

## Test Plan

Current CI

2021-12-08 11:44 UTC, MichaReiser reviewed
I only reviewed the grammar changes and will need to spend some time thinking about what we're trying to solve here. 

There are still cases where this change won't be sufficient to correctly recover from incorrectly ordered modifiers and the API allows for code fixes to build up invalid ASTs without any error.

2021-12-08 11:44 UTC, MichaReiser commented on xtask/src/codegen/kinds_src.rs
> +		"TS_UNKNOWN_ACCESSIBILITY_MODIFIER",
I introduce da `JS_UNKOWN` in #1856 so that we don't need an unknown for every single list

2021-12-08 11:44 UTC, MichaReiser commented on xtask/js.ungram
>  	| JsUnknownModifier
What if we have `static declare abstract a() {}`? This won't be a valid `modifier` because the modifiers are out of order, meaning, we would still need to wrap the whole member as an "UnknownMember".

2021-12-08 11:44 UTC, MichaReiser commented on xtask/js.ungram
> +JsModifier = 'declare'? 'static'? 'abstract'?
Should we have different modifiers for each kind to avoid an empty modifier?

2021-12-08 11:44 UTC, MichaReiser commented on xtask/js.ungram
> +	access_modifier: TsAnyAccessibility?
Should we merge these? Like, making `access_modifier` part of the `modifiers`?

2021-12-08 11:53 UTC, MichaReiser commented on xtask/js.ungram
> +TsAccessibility = 'private' | 'readonly'
`private` and `readonly` can be used together, which this grammar wouldn't support?

```
class Test {
  private readonly test;
}
```

2021-12-08 11:55 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +		}
Will this not invalidate the AST because it generates

```
- class
  - identifier: A
  - UNKNOWN EXPRESSION
  - {
```

Same goes for implements.

You can use `extends_clause(&mut guard).or_invalid_to_unknown(guard, JS_UNKNOWN_EXPRESSION).or_missing(guard)`

2021-12-08 11:57 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +			syntax.or_to_unknown(p, JS_UNKNOWN_EXPRESSION);
Same here. The parent of the `proprty_class_member_body` is a member and a member doesn't allow expressions as it's direct children.

2021-12-08 11:57 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/class_member_bang.rast
> +          4: JS_UNKNOWN_EXPRESSION@13..14
As you can see... this expression doesn't show up in the AST because it's not a valid member of `JS_PROPERTY_CLASS_MEMBER`

2021-12-08 12:59 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +		}
I spend some time thinking about what should happen in the case that TS syntax is used inside of an `extends` clause or if there's an `implements` clause. 

I believe the right thing to do is to mark the whole class as `invalid` because it contains invalid syntax. This isn't as bad as it may sound. Analysers can still retrieve all class members by using `root.descendants().of_type::<JsAnyClassMember>()` 

This also aligns the behavior with what we do in case a function contains any TS syntax outside of a TS file.

2021-12-08 13:14 UTC, MichaReiser commented
Regarding `declare`. I just played around with typescript and `declare` and it seems `declare` is only valid for property members. That's why I would apply the same rule as for `implements` and `extends`

* Use of `declare` for property in a `JS` file -> becomes an unknown member
* Use of `declare` for any other member -> becomes an unknown member.

2021-12-08 13:26 UTC, MichaReiser commented
Regarding the `modifiers`. I would keep explicit fields on the members and bail-out to an unknown member if the syntax contains a TS only modifier or if the modifiers are out of order.  This aligns the behaviour with what we do in other places and:

* We can restrict the modifiers to exactly the set of modifiers supported by this member
* We can enforce the ordering of the modifiers in our AST mutation API
* It makes it clear that the member is invalid. Let's say we have `private readonly m(` The `readonly` tells us that this is a `field` but the `(` suggests that this is a method. Whatever assumption isn't correct and `UnknownMember` represents this the most accurately.

2021-12-08 13:44 UTC, ematipico commented on xtask/src/codegen/kinds_src.rs
> +		"TS_UNKNOWN_ACCESSIBILITY_MODIFIER",
Personally, I don't see the value of having a generic unknown node. It doesn't hint anything and doesn't help to understand what's the supposed type in that position.

2021-12-08 13:46 UTC, ematipico commented on xtask/js.ungram
>  	| JsUnknownModifier
Isn't the ordering something that we could fix with fixed slots? #1721

2021-12-08 13:48 UTC, ematipico commented on xtask/js.ungram
> +JsModifier = 'declare'? 'static'? 'abstract'?
What do you mean when you say "to avoid an empty modifier"?

2021-12-08 13:49 UTC, ematipico commented on xtask/js.ungram
> +	access_modifier: TsAnyAccessibility?
I don't know to be honest 🤔 let me see what RomeJS does. It might make sense merge them.

2021-12-08 13:52 UTC, ematipico commented on xtask/js.ungram
> +TsAccessibility = 'private' | 'readonly'
I don't know. It might have been a mistake. `abstract` and `readonly` can't be used together.

We will fix it when we will review the TS parsing

2021-12-08 13:54 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +		}
OK, let's do that

2021-12-08 14:07 UTC, MichaReiser commented on xtask/js.ungram
>  	| JsUnknownModifier
We can use fixed slots but what if the `abstract` appears in the position of `static`? We can't just swap the slots because re-printing the parsed CST would then result in a different tree than what we originally parsed.

2021-12-08 14:08 UTC, MichaReiser commented on xtask/js.ungram
> +JsModifier = 'declare'? 'static'? 'abstract'?
`""` is a valid production of the `JsModifier` rule because all modifiers can be absent.

2021-12-08 14:08 UTC, ematipico commented on xtask/js.ungram
> +	access_modifier: TsAnyAccessibility?
Just checked Rome. It keeps them separate. Normal modifiers are cumulative (can be one or all of them at the same time), but the accessibility is only one (`private`, `protected` or `public`)

2021-12-09 16:10 UTC, MichaReiser requested changes
Much better. I believe there are still a few cases where we construct an invalid AST structure. 

I would further try to move the `member_is_valid` as close as possible to where it isn't guaranteed to always be true.

2021-12-09 16:10 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +	let parsed_syntax = optional_member_token(p);
This method must return a `ConditionalSyntax` as well because it is invalid as soon as it uses any typescript syntax. 

* `abandoning` isn't valid because it then puts the token into the member, in a place where it's not expected
* Using a `JS_UNKNOWN_EXPRESSION` is not a valid solution here because a property has no direct `child` that accepts an expression.

2021-12-09 16:10 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +		let completed_marker = Present(m.complete(p, QUESTION));
Question is a token kind, isn't it? I don't think it's valid to create a node with that kind. The AST Facade expects a token and not a node.

2021-12-13 14:37 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
>  			}
Unfortunately no, we still need the `Absent` in order to recover. There are still cases where the parser doesn't advance.

If we remove it, the parser doesn't progress and it doesn't recover either.

2021-12-13 15:25 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
>  			}
Then this is a problem with the error recovery. The contract of `ParsedSyntax` is that we return `Present` if the parser progresses, or return `Absent` otherwise. Can you investigate why recovery isn't working in that case? I mean, the parser should progress because it adds an unknown member containing all processed tokens thus far and we then continue whatever tokens follows immediately after

2021-12-13 16:00 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
>  			}
The recovery kicks in if `ParsedSyntax` is `Absent`. That's why I had to return `Absent` from my `match`. 
https://github.com/rome/tools/blob/de73a963c897962b6e633d16d47146b58cba16cd/crates/rslint_parser/src/parser/parsed_syntax.rs#L224-L239

2021-12-13 16:14 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
>  			}
Can you return `ConditionalSyntax` then? Because it means that the node is invalid and we did parse something.

2021-12-13 16:19 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
>  			}
No, there are cases where we don't parse anything.

Take this example that is currently what's failing:

```js
class B {{}}
```

We don't parse anything and the parser gets stuck at the second `{`. I am looking how to avoid that.

2021-12-14 11:04 UTC, MichaReiser requested changes
The overall handling looks good but there are some unaddressed comments from previous reviews related to what we return from `parse_class_*` and how to handle members with TS syntax.

2021-12-14 11:04 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/class_extends_err.rast
>                      },
Can we convert the `JsExtendsClause` to an `Error` node (in the future `UNKNOWN)` if there's more than one super class. As you can see, the `extends foo` disappeared.

2021-12-14 11:04 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/class_extends_err.rast
> +                JsExtendsClause {
Same here, the `,foo` is part of the `JsExtendsClause` but not accessible through the Ast facade. Can we convert it to an `Error` node instead

2021-12-14 11:04 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/class_member_bang.rast
> +                JsPropertyClassMember {
This should become an `UnknownMember` in JS because the `excl_token` is otherwise missing.

2021-12-14 11:04 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/class_member_modifier.rast
> +            0: ABSTRACT_KW@10..19 "abstract" [] [Whitespace(" ")]
Should `abstract` really be part of `TS_ACCESSIBILITY`? Isn't it it's own field?

2021-12-14 11:04 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/optional_member.rast
> +                JsPropertyClassMember {
This should become an `unknown` node (see other comments inside the code)

2021-12-14 11:44 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/class_member_modifier.rast
> +            0: ABSTRACT_KW@10..19 "abstract" [] [Whitespace(" ")]
No, this is wrong. Accessibility modifiers are: `private`, `protected` and `public`

I will fix it later in another PR. I don't want to change the grammar for now

2021-12-14 12:51 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/class_extends_err.rast
>                      },
Doing so would break:

```
'Tried to cast node ERROR@8..32 as `"rslint_parser::ast::generated::nodes::AnyNode"` but was unable to cast',
```

2021-12-14 12:57 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/class_extends_err.rast
> +                JsExtendsClause {
Doing so would break:

```
'Tried to cast node ERROR@8..32 as `"rslint_parser::ast::generated::nodes::AnyNode"` but was unable to cast',
```

2021-12-14 14:48 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/class_constructor_parameter_readonly.rast
> +                1: IDENT@31..32 "b" [] []
Fixing this one...

2021-12-15 06:57 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/program.rs
> +				.or_invalid_to_unknown(p, JS_UNKNOWN_EXPRESSION)
Can we add a todo here. An `expression` isn't valid in this position.

2021-12-15 06:57 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/program.rs
> +			.or_invalid_to_unknown(p, JS_UNKNOWN_EXPRESSION)
Same here. Can we add a todo. An expression isn't valid in this position.

2021-12-15 06:59 UTC, MichaReiser approved these changes
Thanks for working on this. This turned out to be far more complicated than expected. We need to keep in mind to revisit the implementation once we have a generic `UNKNOWN` node to mark TS syntax errornous.

2021-12-15 09:37 UTC, merged