refactor: use parse list
rome/tools pull request #1869
Opened 2021-12-10 13:51 UTC by ematipico

## Summary

This PR is part of #1725

It implements the traits `ParseNodeList` and `ParseSeparatedList` for the majority of lists we have inside our parser.

Some lists where not refactored because it involived great changes or were part of some code that will be changed anyway.

The changes of `.rast` files were because now the lists are marked as empty if no children were found.

## Test Plan

No regressions.

2021-12-11 11:32 UTC, MichaReiser requested changes
Nice! There's a lot of code that simply is gone when adopting the new parse list. 

Ideally, this PR shouldn't change the way the parser recovers and it seems that it now recovers worse than before. Can you have a look at it?

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +		p.at(T!['}'])
Unrelated to this PR. I'm wondering if we should use the `STMT_RECOVERY_SET` as well. So that it recovers when it sees a 

```
class Foo {

function test() {}
```

Because the function likely doesn't belong to the class.

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +			}
Nit: `expr_or_assignment(p).into()`

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +		p.at(T![')'])
Nit: Should we include `STMT_RECOVERY_SET` here to recover from

```js
function test(a

class Test {}
```

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +		}
Nit
```suggestion
			expr_or_assignment(p).into()
	}
```

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +		p.at(T![']'])
Same with `STMT_RECOVERY_SET`

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +}
What's the reason for overriding `parse_list`. Can't we handle `JS_ARRAY_HOLE` inside of `parse_element`?

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/object.rs
> +		p.at(T!['}'])
Nit: Include `STMT_RECOVERY_SET`?

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +}
I'm not sure if it makes sense to use `ParseList` for directives because we won't need any error recovery for directives (we only parse as long as it's a string literal... if not, we abort. 
```suggestion
	fn recover(
		&mut self,
		p: &mut Parser,
		parsed_element: ParsedSyntax<Self::ParsedElement>,
	) -> RecoveryResult {
		Err(RecoveryError::AlreadyRecovered)
	}
}
```

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	pub fn at_directives(&mut self, p: &mut Parser) -> bool {
Can we make this private? 
```suggestion
	fn is_at_directive(&mut self, p: &mut Parser) -> bool {
```

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	}
This isn't correctly handling the comma after the first declarator, isn't it? 

You can also leave the variable declarations, I rewrote them to use `ParseList` in #1870

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +		}
```suggestion
		parse_statement(p, None).into()
```

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	// 			first_default = Some(marker);
Delete?

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +impl ParseNodeList for SwitchStatementList {
Nit: `SwitchCaseList`... It's parsing the cases, not the statements.

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/src/tests.rs
> +}
Revert?

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/invalid_arg_list.rast
> +                        },
What we had before seemed more accurate..

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/invalid_arg_list.rast
> +  │ ^^^ Expected a default, or a case here
why do we now have these additional errors?

2021-12-11 11:32 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/object_expr_err.rast
> +--
The old implementation seemed to have better recovery than the new one.

2021-12-13 09:13 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +		p.at(T!['}'])
I would create a different const for these cases. It might work though

2021-12-13 09:17 UTC, ematipico commented on crates/rslint_parser/src/syntax/object.rs
> +		p.at(T!['}'])
I won't do it in this PR. This will change some logic that is not related to this PR. As you said, this PR should not change the way we do stuff.

2021-12-13 10:04 UTC, ematipico commented on crates/rslint_parser/src/syntax/expr.rs
> +}
It's the custom logic that we have inside the parsing of the list. I tried normal means but it wouldn't work. Feel free to take stab at it. 

2021-12-13 11:55 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +}
I managed to get it working by moving the `progressing` assertion before `parse_element`. So that empty elements still progress if they're followed by a separator.I'll push soon.

2021-12-13 12:04 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/object.rs
> +			}
I added support for missing members to the separated list parsing.

2021-12-13 12:07 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/invalid_arg_list.rast
The old behaviour looked more correct. an we restore it?

2021-12-13 21:20 UTC, MichaReiser approved these changes

2021-12-14 09:14 UTC, merged