feature(rslint_parser): For in/of and Variable facade
rome/tools pull request #1870
Opened 2021-12-10 16:56 UTC by MichaReiser

## Summary

- Renames `EqualValueClause` to `JsInitializerClause`
- Renames `JsVariableDeclarationStatement` to `JsVariableStatement`
- Renames `JsVariableDeclaration` to `JsVariableDeclarationList`
- Rename `JsVariableDeclarator` to `JsVariableDeclaration`
- Rename `ForInStmt` to `JsForInStatement`
- Rename `ForOfStmt` to `JsForOfStatement`
- Delete `ForStmtInit`
- Introduce `JsForVariableDeclaration` that only allows a single variable declaration.

Deletes the `parse_marker` from the `Parser`.
## Test Plan

2021-12-13 07:10 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> -		};
It seems I really messed up the merging in #1856

2021-12-13 10:52 UTC, ematipico requested changes
I left some comments on the PR.

I would personally revert the changes on the `ParseSeparatedList`. We can retrieve the list marker in other ways and would prefer the way where we change the API signature, just for one case.

2021-12-13 10:52 UTC, ematipico commented on xtask/js.ungram
> +// TODO Inline when AST facade uses fixed offsets
Can we add the issue number of the fixed offsets?

2021-12-13 10:52 UTC, ematipico commented on crates/rome_formatter/src/ts/declarators/variable_declaration_statement.rs
> +			),
I don't think we have at test where have long lists of declarations and by looking at the code, it doesn't seem we handle it. We should add a `TODO` as reminder or fix it now.

2021-12-13 10:52 UTC, ematipico commented on crates/rslint_parser/src/parser/parse_lists.rs
> +		m.complete(p, SyntaxKind::LIST)
What's the reason of change the API signature? Personally I would leave the API like this and I would introduce some new flag and API to retrieve the list marker on demand. 

Doing so would have a waterfall effect where every list needs a `.unwrap`, which goes against what we designed before.

2021-12-13 10:52 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +			!p.at(T![,])
```suggestion
			!p.at(self.separating_element_kind())
```

2021-12-13 10:52 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +			!p.at(T![,])
Isn't `;` the list end?

2021-12-13 10:52 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +	for_in_or_of: bool,
The name of the variable and the type are misleading. Is should start with `is_*` or be a `enum`. 

```rs
enum For {
	In,
	Of
}
```

2021-12-13 10:52 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +		let is_of = p.cur_src() == "of";
Can't we use `T![of]`?

2021-12-13 10:52 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +				declarations_list.undo_completion(p).abandon(p);
What's happening here?

2021-12-13 10:52 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +					.primary(additional_declarations_range, "additional declarations"),
If with `declaration` we mean **variable declaration**, then it's wrong. We can have multiple declarations (I tried various parsers and they don't emit errors). And I think the changes we applied to the grammar reflect that.

2021-12-13 10:52 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +				p.err_builder("await can only be used in conjunction with for of statements")
```suggestion
				p.err_builder("await can only be used in conjunction with `for..of` statements")
```

2021-12-13 10:52 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +					.secondary(completed.range(p), "or convert this to a for of statement"),
```suggestion
					.secondary(completed.range(p), "or convert this to a `for..of` statement"),
```

2021-12-13 10:52 UTC, ematipico commented on crates/rslint_parser/test_data/inline/err/for_stmt_err.rast
> +  │             ^^^^^ additional declarations
We should not have this error

2021-12-13 11:01 UTC, MichaReiser commented on crates/rslint_parser/src/parser/parse_lists.rs
> +		m.complete(p, SyntaxKind::LIST)
What do you have in mind? 

There's no waterfall effect because there's no need to call `unwrap` on `CompletedMarker` nor `Option`.

2021-12-13 11:02 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +			!p.at(T![,])
`T![,]` seems cleaner to me... one less interaction. It's testing if we're currently add a comma, which separates two declarations.

```
let a, b
      ^
```

2021-12-13 11:03 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +				declarations_list.undo_completion(p).abandon(p);
The `JsForVariableDeclaration` directly contains the variable declaration without an intermediate `JsVariableDeclarationList`. That's why I need to abandon it. I can add a comment.

2021-12-13 11:04 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +					.primary(additional_declarations_range, "additional declarations"),
`for of` and `for in` can only have one... Try

```
for (let a, b of c) {}
for (let a, b, in c) {}
```

This is different for `for in`, where `for (let a, b = 1;;) {}` works perfectly fine.

2021-12-13 11:05 UTC, ematipico commented on crates/rslint_parser/src/parser/parse_lists.rs
> +		m.complete(p, SyntaxKind::LIST)
Then we should apply this change to the other list too.

2021-12-13 11:05 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/for_stmt_err.rast
> +  │             ^^^^^ additional declarations
See comment above.

2021-12-13 11:14 UTC, MichaReiser commented on crates/rslint_parser/src/parser/parse_lists.rs
> +		m.complete(p, SyntaxKind::LIST)
This change is automatically applied for other lists as long as they don't override `finish_list`. I can update the documentation to mention that it now returns the completed marker if the list isn't empty

2021-12-13 11:18 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +					.primary(additional_declarations_range, "additional declarations"),
Oh yeah, I used the normal `for()` lol. Sorry about that!

2021-12-13 11:19 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +				declarations_list.undo_completion(p).abandon(p);
Yes please, it's a strange path. A comment would help to understand

2021-12-13 11:20 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +			!p.at(T![,])
I know, but we wouldn't need to maintain `T![,]` twice :) 
I think using the API is better

2021-12-13 12:28 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +			!p.at(T![,])
I prefer the current solution because I doubt there's ever anything to maintain. It's super unlikely that the separator for variable declarations will ever change and I find the inline `T![,]` easier to read than having to jump to the method definition.

2021-12-13 12:56 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +		let is_of = p.cur_src() == "of";
Nope, `of` is a contextual keyword and the lexer returns it as an identifier.

2021-12-13 12:58 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	for_in_or_of: bool,
I introduced a `VariableDeclarationContext` that can either be a `for` or `variable statement`

2021-12-13 13:57 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +			!p.at(T![,])
The separator of the variable won't change, but one day the macro might. 

> easier to read than having to jump to the method definition.

Then, let's remove the `separating_element_kind` :)

2021-12-13 14:04 UTC, ematipico requested changes

2021-12-13 14:04 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +) -> ParsedSyntax<CompletedMarker> {
The quantity of arguments here is too much I think. Wouldn't it better to use a `struct` as this point? Doing so, we can also document the arguments. `is_first` doesn't say much to me

2021-12-13 14:04 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +				// for a ForInOrOfInitializer
I was hoping to have some explanation of _why_ we are removing the list.

2021-12-13 21:21 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +				// for a ForInOrOfInitializer
Lol sorry, there's a *not* missing... *that is not needed for a `ForInOrOfInitializer`

2021-12-14 09:35 UTC, ematipico approved these changes

2021-12-14 09:41 UTC, merged