refactor: super
rome/tools pull request #1880
Opened 2021-12-15 17:08 UTC by ematipico

## Summary

## Test Plan

2021-12-16 17:13 UTC, MichaReiser requested changes
Overall looking good. There are some cases where we are still advancing the parser even though we return `Absent`. Would you mind having a look at it.

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +				if parse_expr_or_assignment(p).is_absent() {
`or_missing_with_error`?

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +			// TODO: remove it and delegate recovery to parent
Can we already delete it?

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +			T![...] => spread_element(p),
`parse_spread_element`?

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +pub fn array_expr(p: &mut Parser) -> ParsedSyntax<CompletedMarker> {
Nit: `parse_array_expression`?

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +pub fn lhs_expr(p: &mut Parser) -> ParsedSyntax<CompletedMarker> {
Can we make this private? 

`parse_lhs_expr`?

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +	if let Present(m) = lhs {
Nit:

if lhs.kind() == Some(JS_ARROW_FUNCTION_EXPRESSION) {
    return lhs;
}

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +		Present(lhs) => {
Use `map`

lhs.map(|lhs| {
    ...
})

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +pub fn postfix_expr(p: &mut Parser) -> ParsedSyntax<CompletedMarker> {
`parse_postfix_expr` (and make it private?)

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +	match lhs {
Use `map`

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
>  			m.abandon(p);
We're not allowed to return `Absent` here because we parsed a token on line 1518.

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +pub(super) fn is_at_name(p: &Parser) -> bool {
This is the same as `is_at_identifier_name`?

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/object.rs
> +					if parse_expr_or_assignment(p).is_absent() {
`or_missing_with_error`

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/pattern.rs
> +			if parse_expr_or_assignment(p).is_absent() {
`or_missing_with_error`

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +		// TODO: review this part when error recovery is fixed
What part of error recovery must be fixed?

I think we can just mark it as `missing` if the recovery failed.

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +		p.expr_with_semi_recovery(false).ok();
We can probably just mark it as `missing` if the recovery failed`.

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +	if parse_expression(p).is_absent() && pos == p.token_pos() {
Can we remove the `pos` hack now and just use `parse_expression(p).or_missing_with_error`?

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +		if init_expr.is_absent() && p.token_pos() == checkpoint.token_pos {
Can we remov the `token_pos` hack now and just use `p.or_missing_with_error`

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +		if parse_expression(p).is_absent() {
`or_missing_with_error`

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/stmt.rs
> +		if parse_expr_or_assignment(p).is_absent() {
`or_missing_with_error`

2021-12-16 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/parse.rs
> +	crate::syntax::expr::parse_expression(&mut parser).or_missing(&mut parser);
The `missing` here won't work. Because building the tree will fail on line `245`. I think it should be fine to just use `unwrap` for now (I introduced a `ExpressionSnipped` which fixes this problem).

2021-12-17 08:24 UTC, ematipico commented on crates/rslint_parser/src/syntax/expr.rs
> +		return Present(yield_expr(p));
Yeah, it's fine. It's an internal function used only once and there's a check on the `yield` keyword before calling it. There are no risks

2021-12-17 08:28 UTC, ematipico commented on crates/rslint_parser/src/syntax/expr.rs
> +	}
This suggestion is not correct. The `mapper` has to return `CompletedMarker` or `ConditionalSyntax` because `.map` already applies `Present`.. and `parse_assign_expr_recursive` already returns `ParsedSyntax`

2021-12-17 08:32 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +	}
Oh, you can use `and_then` in that case

2021-12-17 09:30 UTC, ematipico commented on crates/rslint_parser/src/syntax/expr.rs
> +		Absent
I think the whole logic is wrong and it needs to be reviewed. Not sure if we have to do it now or not. 
Inside the tests we have this errored test `foo + * 2` and generate the following AST/tree:

```
  0: JS_BINARY_EXPRESSION@11..21
    0: JS_IDENTIFIER_EXPRESSION@11..16
      0: JS_REFERENCE_IDENTIFIER@11..16
        0: IDENT@11..16 "foo" [Whitespace("\n")] [Whitespace(" ")]
    1: PLUS@16..18 "+" [] [Whitespace(" ")]
    2: JS_BINARY_EXPRESSION@18..21
      0: (empty)
      1: STAR@18..20 "*" [] [Whitespace(" ")]
      2: JS_NUMBER_LITERAL_EXPRESSION@20..21
        0: JS_NUMBER_LITERAL@20..21 "2" [] []
```

```
left: JsIdentifierExpression {
    name: JsReferenceIdentifier {
        value_token: IDENT@11..16 "foo" [Whitespace("\n")] [Whitespace(" ")],
    },
},
operator: PLUS@16..18 "+" [] [Whitespace(" ")],
right: JsBinaryExpression {
    left: JsNumberLiteralExpression {
        value_token: JS_NUMBER_LITERAL@20..21 "2" [] [],
    },
    operator: STAR@18..20 "*" [] [Whitespace(" ")],
    right: missing (required),
},

```

As you can see they are out of sync. I also think we should mark a missing right hand.

2021-12-17 09:44 UTC, ematipico commented on crates/rslint_parser/src/syntax/expr.rs
> +pub fn parse_static_member_expression(
Good catch!  Yes this should return `ParsedSyntax` too

2021-12-17 11:10 UTC, ematipico commented on crates/rslint_parser/src/syntax/expr.rs
> +	if let Some(NodeMarker(params)) = params_marker {
> GitHub should really allow you to comment on unchanged lines:

If you press "." while opening a PR, github will enter in editor mode and it allows you to see the **whole** file with its differences. And you can add comments in any part of the file :)

This is really handy for big PRs. Give it a try!

> Do we need to add a missing marker in the case the parenthesized_expression is empty on line 892?

I really don't know to be honest. We don't have test error cases so it's hard to tell for me

2021-12-17 11:23 UTC, ematipico commented on crates/rslint_parser/src/syntax/expr.rs
> +			// TODO: remove it and delegate recovery to parent
We're not ready yet. I will look into it later

2021-12-17 11:48 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +		p.expr_with_semi_recovery(false).ok();
The missing marker is already created inside function `expr_with_semi_recovery`. This will create an additional empty slot that won't match the AST

2021-12-17 12:08 UTC, ematipico commented on crates/rslint_parser/src/syntax/expr.rs
> +// TODO: review the left missing expression, the green tree might be better
Check the test `assign_expr_left.rast`. Even though we have a correct `JsParenthesizedExpression`, we don't actually arrive at the end of the expression. Instead we mark `=` as unknown expression. 

Not sure if it's possible, but I think we should have a `JsAssignmentExpression` instead where the left hand is missing. Do you think it's possible to achieve that?

2021-12-17 12:12 UTC, ematipico commented on crates/rslint_parser/src/syntax/assignment.rs
>  		AssignmentExprPrecedence::Unary => unary_expr(p),
`unary_expr` returns a `JsUnknownExpression` in case of error. This will result into a panic because `JsUnknownExpression` can't be casted in `JsAnyArrayAssignmentPatternElement`.

How do you think we should proceed?

2021-12-17 12:41 UTC, ematipico commented on crates/rslint_parser/src/syntax/assignment.rs
>  	// TODO remove the rewind inside of the error handle once the `unary_expr` returns a ParsedSyntax
Not yet

2021-12-20 06:54 UTC, MichaReiser commented on crates/rslint_parser/src/parser.rs
> +		)
This is no longer the same behaviour as before and the message no longer matches. The old implementation crated a diagnostic only in the case if the parser currently is at a semicolon. The new recovery logic creates a diagnostic whenever the expression is absent and only recovers if there's a semicolon (but e.g. not if we're at the start of a new statement, e.g. this will happily eat over the function in 

```
a + 
function test() {}
```

which is not what we want.

we should revisit this logic and improve the error message

2021-12-20 06:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +// TODO: review the left missing expression, the green tree might be better
We should improve the comment here and explain that.

2021-12-20 06:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +		Absent
I would argue we should look into this now since this PR is trying to "fix" the expr parsing or we should at least add a todo

2021-12-20 06:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +	parse_expression(p).or_missing(p);
```suggestion
	parse_expression(p).or_missing_with_error(p);
```

2021-12-21 08:35 UTC, MichaReiser commented
I'll look into the remaining issues so that we can then merge the changes

2021-12-21 09:41 UTC, merged