test(formatter): add tests to cover the whole syntax
rome/tools pull request #1882
Opened 2021-12-16 09:24 UTC by Boshen

closes #1878

## Summary
I used [grcov](https://github.com/mozilla/) to generate the coverage, and filled in all uncovered lines, it's currently sitting at 92% (increased from 90%). The missing pieces are TypeScript, Unknown* and Holes.

<img src="https://user-images.githubusercontent.com/1430279/146343271-64f4511b-408a-453d-ae40-4deb800a4c20.png" width="400" />

## Test Plan
`cargo test` passes

## What's next
https://github.com/rome/tools/pull/1876#pullrequestreview-833798471
> Now that we have the tests from the old Rome, I think one important thing that we should do is to actually match its formatting style to the new formatter.
>
> Rome's old formatter was pretty stable (exception for comments and some JSX case), so I think it's worth using its formatting style whereas possible.

I'll work on this branch until everything conforms to old Rome.

2021-12-16 11:19 UTC, xunilrj commented on crates/rome_formatter/src/ts/assignment/array_assignment_pattern.rs
> +			}
silly but we can do: 

```rust
JsAnyArrayAssignmentPatternElement::JsArrayHole(array_hole) => array_hole.to_format_element(formatter)
```

2021-12-16 11:22 UTC, xunilrj commented on crates/rome_formatter/tests/specs/js/arrow/arrow_function.js
> +(foo) => {}
Can we test more than one parameter?

```rust
(foo,bar) => {}
```

2021-12-16 12:58 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/binding/array_binding.js
> +let [a="b"]=c
This test covers the array bindings, so this test is not needed here (which is already covered somewhere else)

2021-12-16 13:01 UTC, ematipico requested changes

2021-12-16 13:01 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/object/getter_setter.js.snap
> +	{}
Found a bug

2021-12-16 13:03 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/arrow/arrow_function.js
> +(foo) => {}
Function arguments are already covered inside `function/function_args.js`

2021-12-16 13:04 UTC, ematipico commented on crates/rome_formatter/src/ts/assignment/array_assignment_pattern.rs
> +			}
I think this is the formatter 🤔

2021-12-17 15:24 UTC, Boshen commented
@ematipico I am in the right direction for this: https://github.com/rome/tools/pull/1882/commits/d6a1c94082d4ea0e090d800b32a04a3c96d22b26

To align with prettier, we collapse new lines appropriately, but I couldn't find a general place to add the code, so I added it to JsStatementList to test it out, can you point me in the right direction on where to collapse new lines?

2021-12-17 15:25 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/object/getter_setter.js.snap
> +	{}
This is syntax error, I have removed it.

2021-12-17 15:27 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/class/class.js.snap
> +	c = d) {
Fixed in 6877d63, I see there are few places that have this pattern, perhaps I can refactor them.

2021-12-17 15:27 UTC, Boshen commented on crates/rome_formatter/src/ts/assignment/array_assignment_pattern.rs
> +			}
Yep it's the formatter :-/

2021-12-17 15:51 UTC, ematipico commented
> @ematipico Am I in the right direction for this: [d6a1c94](https://github.com/rome/tools/commit/d6a1c94082d4ea0e090d800b32a04a3c96d22b26)
> 
> To align with prettier, we collapse new lines appropriately, but I couldn't find a general place to add the code, so I added it to JsStatementList to test it out, can you point me in the right direction on where to collapse new lines?

I think this fix requires its own PR and its own issue, mainly because this change involves `rome_rowan` as well. Myself and Micha were discussing about having a `new_line_trivia` but this still up in the air and not sure if this is the right direction. That's why it's worth a small discussion first.

Generally, I think this logic should live inside the formatter (or even inside the printer) BUT the single nodes should not be aware of this. We might also check what old Rome was doing.

2021-12-17 16:09 UTC, Boshen commented
I see, I'll drop the commit and clean up this PR and leave the formatter as is for now.

2021-12-18 07:44 UTC, Boshen commented
Fixed some spacing issues, ready to review and merge

2021-12-18 07:57 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/expression/new_expression.js.snap
> +new c(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccccccccccccccc);
This needs special treatment, adding normal breaking logic will break things, for example passing arrow functions.

2021-12-21 08:32 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/object/getter_setter.js.snap
> +let b = {set foo(a) {}};
Can we add spaces after the `{` and right before the `}` of the object expressoin?

2021-12-21 08:34 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/script.js.snap
> +#!/usr/bin/env node
It's impossible to tell if this is indeed working. Can we add a `"use strict"` directive as well and some additional statements?

```
"use strict"

let a =    "b";
```

2021-12-21 08:34 UTC, MichaReiser commented
Nice, thanks for adding all these new tests. I've found two small improvements, and we should then be ready to merge this.

2021-12-22 04:50 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/script.js.snap
> +#!/usr/bin/env node
done in 89315cd

2021-12-22 04:52 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/object/getter_setter.js.snap
> +let b = {set foo(a) {}};
Good catch! Fixed in 31fceb9. We only need special treatment for single line object expression :-)

2021-12-22 04:54 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/object/property_key.js.snap
> +	"bar": { "lorem_ispsum": { "lorem-ipsum": true } },,
This extra comma comes from the original input + `if_group_breaks(token(","))`.
I think this issue should be addressed in another place.

2021-12-22 04:57 UTC, Boshen commented
@MichaReiser Ready to merge.

There are some issues and API improves that can be triaged, I'll add them to the "Formatter API improvements" umbrella.

2021-12-22 07:52 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/script.js.snap
> +var express = require("express");
Whoops, the `use strict` is gone...

2021-12-22 07:55 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/object/property_key.js.snap
> +	"bar": { "lorem_ispsum": { "lorem-ipsum": true } },,
`object_expression` uses `format_separated` which already inserts the trailing `,` if it breaks across multiple lines. 

I think the right thing to do here is to remove it from `format_separated` and leave it up to the `format_separated` call sites to decide whatever they want to have a trailing separator (some of which may not even support it, for example, a variable declaration statement).

2021-12-22 07:58 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/object/property_key.js.snap
> +	"bar": { "lorem_ispsum": { "lorem-ipsum": true } },,
These are the relevant lines

https://github.com/rome/tools/blob/497abd0a74a0f1dd656b0e357e6d2ca686db919d/crates/rome_formatter/src/formatter.rs#L141-L143

 I think we can just change it to 

```
		for (index, element) in list.elements().enumerate() {
			let node = self.format_node(element.node()?)?;
			if let Some(separator) = element.trailing_separator()? {
				let formatted_separator = self.format_token(&separator)?;
				if index == list.len() - 1 {
					result.push(node)
				} else {
					result.push(format_elements![node, formatted_separator]);
				}
			} else {
				result.push(node);
			}
		}
```

2021-12-22 14:38 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/object/property_key.js.snap
> +	"bar": { "lorem_ispsum": { "lorem-ipsum": true } },,
Fixed in 5c1b0e7, so nice to see all the extras trailing commas gone!

2021-12-22 14:39 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/script.js.snap
> +var express = require("express");
Fixed in 3f028d4, JsDirectiveList was never rendered 🤣

2021-12-22 14:42 UTC, MichaReiser approved these changes
Amazing, thank you so much for working on this

2021-12-22 14:42 UTC, MichaReiser commented on crates/rome_formatter/src/ts/directive.rs
> +			hard_line_break()
Won't this add two hard-line breaks if joined together with what we have in `scripts.rs`. I just had a look at expression statement and we don't add any line break there.

2021-12-22 14:44 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/array/spaces.js.snap
> +let b = [,];
@MichaReiser Super annoying edge case here, the parser should give 3 `JsArrayHole`s for the input `let b = [,,];`, but we were given 2:
```
                  1: JS_ARRAY_EXPRESSION@8..12
                    0: L_BRACK@8..9 "[" [] []
                    1: JS_ARRAY_ELEMENT_LIST@9..11
                      0: JS_ARRAY_HOLE@9..9
                      1: COMMA@9..10 "," [] []
                      2: JS_ARRAY_HOLE@10..10
                      3: COMMA@10..11 "," [] []
                    2: R_BRACK@11..12 "]" [] []
```

2021-12-22 14:59 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/array/spaces.js.snap
> +let b = [,];
Two holes should be correct for `let b = [,,];` 

```
let b = [,,];
undefined
b
Array [ <2 empty slots> ]
```

array holes are inserted if there was no element between two commas. The last comma is a *trailing comma, and thus, doesn't create an array hole.

2021-12-22 15:25 UTC, Boshen commented on crates/rome_formatter/src/ts/directive.rs
> +			empty_element()
Both issues fixed in d3995f1

2021-12-22 15:27 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/array/spaces.js.snap
> +let b = [,];
Oh I was confused with who prettier is handling with "manual" vs "auto" inserted trailing commas ...

The formatting here is correct then, except we are not handling the manual case for now

2021-12-22 15:31 UTC, Boshen commented
@MichaReiser Ready to merge again 😁 

I think I'll start comparing prettier outputs and jot down all the things we should add to the formatter in the umbrella issue.

2021-12-22 15:41 UTC, merged