feat(rome_formatter): retain trivias in the formatter output
rome/tools pull request #1916
Opened 2022-01-10 13:16 UTC by leops

## Summary

Two kind of trivias are detected and emitted in the formatter IR: comments and empty lines.
Comments are mostly self-explanatory, while an empty line is emitted when at least two consecutive line breaks are found in a whitespace trivia.

Since trivias are attached to tokens they are emitted from the `format_token` method, which means any token not consumed by the formatter may see its trivias dropped from the output. I tried to refactor a number of cases where the formatting code was creating new tokens instead of recycling them from the inputs, however I may have missed some.
I'm not sure if there's a way we can check the formatter has consumed all the tokens from the input at least in debug mode, and then in addition to this it would need a formatter method for consuming a token's trivias without emitting the token itself (like what's done in `format_separated` for the trailing separator).

## Test Plan

This changes a number of test snapshot results since they previously had their comments and newlines dropped. Most of these look sensible considering many of them have complex newline patterns, except for the empty object expression in `js/object/object.js` that doesn't look right

2022-01-10 14:58 UTC, Boshen commented
If you look closely, some of the snapshots are a bit off. 
You can copy the snapshots into the Prettier Playground to test things out.

I did a small commit with this and here is the discussion: https://github.com/rome/tools/pull/1882#issuecomment-996828249

2022-01-10 17:14 UTC, MichaReiser reviewed
This is a big improvement to what we had so far. 

I'm not sure if we can implement the collapsing of new lines generically, or at least, if we would need yet another IR element to do the collapsing. 

The problem is, there are some new lines that we want to remove completely, for example, any new line before the closing parentheses (so that these get deleted when I removed 1-2 elements). 

It probably makes sense to split this PR into two: One for comments and another for new lines

2022-01-10 17:14 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/array/empty_lines.js.snap
> +
In my view, the empty line after the last element should be removed.

2022-01-10 17:14 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/arrow/arrow_nested.js.snap
> + false,// generatePreview
It seems we're losing the whitespace between the token and the comment.

2022-01-11 08:55 UTC, leops commented on crates/rome_formatter/src/formatter.rs
> +			let is_single_line = comments_text.starts_with("//");
With this version comments are pretty much dropped in place in the output. I'm currently revising this behavior, and for "multiline comments" it will depend on whether they are actually multiline (contain at least one linebreak):

- single line comments will be preceded with a `soft_line_break_or_space` and followed by a `hard_line_break`
- single line block comments will be preceded and followed by a `soft_line_break_or_space`
- multi line block comments will be preceded and followed by a `hard_line_break`

(Also I'd probably want this check to rely on the new `MULTILINE_COMMENT` instead of looking up the text content)

2022-01-11 10:27 UTC, Boshen commented on crates/rome_formatter/tests/specs/js/number/number.js.snap
>  ;
This `;` ended up on a new line

2022-01-11 10:45 UTC, ematipico requested changes

2022-01-11 10:45 UTC, ematipico commented on crates/rome_formatter/src/formatter.rs
> +			let is_multi_line = !is_single_line && comments_text.contains("\n");
What about `/** **/` comments? How should we treat them? Consider that such comment can also on a single line

2022-01-11 10:45 UTC, ematipico commented on crates/rome_formatter/src/ts/class/property_class_member.rs
> +		};
We have this pattern which is repeated in different places. Can't we have a function `format_semicolon` inside `formatter`?

2022-01-11 10:45 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/arrow/currying.js.snap
> +};
I think, in this case, we should move the comment in a newline and indent it.

2022-01-13 16:38 UTC, ematipico approved these changes

2022-01-13 16:38 UTC, ematipico commented on crates/rome_formatter/src/formatter.rs
> +	/// such as a function body delimited by '{' and '}' tokens
```suggestion
	/// such as a function body delimited by '{' and '}' tokens.
```

2022-01-13 16:38 UTC, ematipico commented on crates/rome_formatter/src/formatter.rs
> +	pub fn format_or_create_token(
Doc missing

2022-01-13 16:38 UTC, ematipico commented on crates/rome_formatter/src/formatter.rs
> +					// last token depends on the group being borken or not
This comment is really hard to read, is there some punctuation missing?

2022-01-13 16:38 UTC, ematipico commented on crates/rome_formatter/src/formatter.rs
> +}
Will this struct have 0 size when it's compiled with the `--release` flag?

2022-01-13 17:16 UTC, leops commented on crates/rome_formatter/src/formatter.rs
> +					// last token depends on the group being borken or not
I think I edited the content of this comment a few times and it got really confusing, I'll just completely rewrite it. The idea is that in the current design, the formatter for a node is responsible for adding for example a `if_group_breaks(token(","))` after the separated elements, so if there was a trailing separator at the end it gets discarded but we still want to print the comments that were attached to it

2022-01-13 17:19 UTC, leops commented on crates/rome_formatter/src/formatter.rs
> +}
Yes that's the general idea, the snapshoting system is only needed to handle the logic backtracking on invalid nodes so that tokens don't get processed twice, but it will compile to nothing in release mode and the optimizer should remove it entirely

2022-01-13 17:29 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +pub fn line_suffix(element: impl Into<FormatElement>) -> FormatElement {
Documentation

2022-01-13 17:29 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +	}
For what do we need the `snapshot` and `restore` when formatting? Can you add some documentation explaining its use case?

2022-01-13 17:29 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +	pub fn format_comment<L: Language>(
Must this be public or can it be private?

2022-01-13 17:29 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +	pub fn format_or_create_token(
I'm wondering if this is something that we could implement as an extension to `Option<SyntaxToken>`

2022-01-13 17:29 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +			)?,
Should the content always be ut inside a `group`? At least the method name says it's a group? Or should the outer content be grouped?

I need to review this again tomorrow. It's still not entirely clear to me why we need this method vs just using `groups`. It could help to explain in the comment why we need this method.

2022-01-13 17:58 UTC, leops commented on crates/rome_formatter/src/formatter.rs
> +			)?,
Most of the time this will be inside a group but this isn't always the case (for instance `JsFunctionBody` doesn't create a group)

Generally this is needed for cases like this:
```js
while (true) { // comment
	break;
}
```

If the `curly_token` are left outside the indent group the comment is printed exactly where it was in the input,
while if both `curly_token` are pushed into the indent group the result becomes this:
```js
while (true)
  { // comment
  break;}
```

With this change only the trailing comment for the opening `curly_token` will be pushed inside the indent group giving:
```js
while (true) {
  // comment
  break;
}
```

2022-01-14 09:42 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/arrow/call.js.snap
> +// .toThrowError(/Required parameter/);
Delete?

2022-01-14 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/printer.rs
> +						.collect()
You need to explain this line to me. Where's the side effect happening? All we do is to empty the `line_suffices` (`.clear()` might be faster) and then add a `PrintElementCall`. But I don't see where these events are being processed.

2022-01-14 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/printer.rs
> -		self.state.buffer.reserve(content.len());
Any reason you removed the `reserve` call?

2022-01-14 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +			.map_or(false, |first_token| *token == first_token);
Nit: This is probably a bit more expensive because it calls into `descendants`

```
NodeA [
  NodeB [
    token
  ] 
] 
```

meaning, it would return `token` even if called on `NodeA`. 

`let is_leading_token = token.prev_sibling_or_token().is_none()`

But it depends on the behaviour you want. Almost all nodes have at least one token as its children, not so `JsArrayHole`

```
JsArrayExpression [
  JsArrayHole
  ','
  ]
```

Should `is_leading_token` be true for the `,` or not?

2022-01-14 09:42 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +			)?,
I'm wondering if we can replicate the same with `if_group_breaks` and `if_group_fits_on_single_line` (which we probably should rename because it also gets printed if it isn't inside a group).

2022-01-14 09:56 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/comments.js.snap
> +);
> It isn't really changing any semantic.

That's because they don't have editor in mind. Try to think about this situation:

```js
expression(  // line comment |
);
```

The pipe is where is the position of the cursor of the IDE. If we format it as Prettier does, we basically changing the whole semantic! The user wanted to continue write after the comment, assuming that they were inside the parenthesis. But nope, they save, they continue to write code and it is... wrong.

2022-01-14 11:21 UTC, leops commented on crates/rome_formatter/src/printer.rs
> +						.collect()
The difference between drain and clear is that drain returns an iterator containing the removed elements, this iterator gets chained with a single PrintElementCall and collected into the vector that's returned from `print_element` to be added back on the stack. So these events will eventually be processed by the next few calls to `print_element` when they're popped off the stack

2022-01-14 11:28 UTC, leops commented on crates/rome_formatter/src/printer.rs
> +		while let Some(newline) = content.find('\n') {
I should just revert this bit, it was part of a test I did on to allow comments to be pushed off to the previous line but I deemed this too complex. The idea was that it would not be too inefficient because find is implemented on top of memchr and printing the line content boils down to a reserve + memcpy, all of which are highly optimized

2022-01-14 11:30 UTC, MichaReiser commented on crates/rome_formatter/src/printer.rs
> +						.collect()
Ah, it gets added to the stack... I missed that. Sorry

2022-01-14 11:30 UTC, leops commented on crates/rome_formatter/src/formatter.rs
> +			if piece.as_newline().is_some() {
Currently multiline comments are represented as `TriviaPiece::Comments` so all types of comments are covered by the previous condition

2022-01-14 11:36 UTC, leops commented on crates/rome_formatter/src/ts/statements/mod.rs
> +			let snapshot = formatter.snapshot();
In the current state of things the formatter state is only used to keep track of the tokens that were seen during the current formatting process in debug mode to detect cases where a token is skipped over by a formatter. In practice forgetting to snapshot and restore the state isn't too dangerous as it will not break anything, but the formatter will likely panic in debug mode because it asserts that tokens do not get formatted twice (a first time in format_node and a second time in the fallback call to format_raw)

2022-01-14 11:41 UTC, leops commented on crates/rome_formatter/src/formatter.rs
> +	pub fn format_or_create_token(
That's possible but it might look inconsistent to have `formatter.format_token(token)` and `token.format_or_create(formatter, factory)`

2022-01-14 11:45 UTC, leops commented on crates/rome_formatter/src/formatter.rs
> +					// last token depends on the group being borken or not
That as the case because some callers may never want the trailing separator (variable declarators) or may want to conditionally print it (array expression with holes). But I think it's probably better to have `format_element` handle the general case, and have special cases implement their own logic as required

2022-01-14 11:50 UTC, leops commented on crates/rome_formatter/src/formatter.rs
> +			if piece.as_newline().is_some() {
I'm not sure if this code path is actually useful, I think for trailing trivias if there is newline piece it's always the last one so the line count might always be 0

2022-01-14 12:04 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +			if piece.as_newline().is_some() {
It can happen if the comments are attached to the EOF token. For example if you have

```
let a = 10;

// Some trailing comma
// and another

// and some more
````

2022-01-14 12:33 UTC, leops commented on crates/rome_formatter/src/formatter.rs
> +			if piece.as_newline().is_some() {
Oh I thought these were leading trivias, I was thinking that the EOF token couldn't have trailing trivias since that would be "content after the end of the file"

2022-01-14 13:16 UTC, leops commented on crates/rome_formatter/src/formatter.rs
> +			.map_or(false, |first_token| *token == first_token);
Actually with the changes I've made to the semantics of whitespace tokens this isn't needed anymore, I think the comment formatter can just emit space or newline tokens unconditionally and doesn't need to handle "inner" comments in any special way

2022-01-14 17:32 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +			if piece.as_newline().is_some() {
Oh right. These are leading trivia.

2022-01-17 08:35 UTC, MichaReiser reviewed
This is a huge improvement from what we had before. Thanks for tackling this!

The overall approach looks good to me. I've a few more comments related to the API and usage inside of the formatter. But we should then be good to go :)

2022-01-17 08:35 UTC, MichaReiser commented on crates/rome_formatter/src/ts/class/method_class_member.rs
> +		let star_token = formatter.format_or_create_token(self.star_token(), empty_element)?;
It seems that this is a normal optional token because `format_or_crate` token with an `empty_element` is a no-op if the element isn't present?

```rs
let star_token = if let Some(star_token) = self.star_token() {
    formatter.format_token(&star_token) 
} else {
    empty_element()
}
```

2022-01-17 08:35 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/array_expr.rs
> +							// If the previous element was empty or this is not the last element, always print a separator
Using `node.is_empty` works but isn't very semantic. How about matching on `element.node()?` because the case your describing here is if the last element is a `JsArrayHole` for which we could test explicitly.

2022-01-17 08:35 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/call_expression.rs
> +		let option =
This is an optional token, we shouldn't need to use `format_or_create_token` (a helper on `Option<FormatElement>` or implement `ToFormatElement` for `Option<ToFormatElement>` might be helpful tough)). 

```
let optional = if let Some(optional) = self.optional_chain_token() {
    formatter.format_token(&optional)?
} else { 
    empty_element()
};
```

2022-01-17 08:35 UTC, MichaReiser commented on crates/rome_formatter/src/ts/statements/break_statement.rs
> +		let semicolon = formatter.format_or_create_token(self.semicolon_token(), || token(';'))?;
Lol, I get it now... the `||` is for a lambda function. It reads as if it's the or operator.

2022-01-17 08:35 UTC, MichaReiser commented on crates/rome_formatter/src/ts/statements/debugger_statement.rs
> +			formatter.format_or_create_token(self.semicolon_token(), || token(';'))?
Nit: Something we can track in a future PR

Would be nice if the `formatter` doesn't require different methods to support inserting a token or adding a new one if it's missing but that this are helpers defined elsewhere. However, I don't know a good place right now. Ideally, it would be something like `formatter.format_token(self.semicolon_token()).or_else(|| token(';'))` but that would require changing `format_token` to return an `Option` instead and implement `ToFormatElement` for `Option<T> where T: ToFormatElement`. Let's leave this for another PR / improvement.

2022-01-17 08:35 UTC, MichaReiser commented on crates/rome_formatter/src/ts/statements/empty_statement.rs
> +		formatter.format_replaced_token(&self.semicolon_token()?, empty_element())
```
if let Some(semicolon) = self.semicolon_token() {
    formatter.format_token(semicolon)
} else {
    empty_element()
}
```

or implement `ToFormatElement` for `Option<T> where T: ToFormatElement`

2022-01-17 08:35 UTC, MichaReiser commented on crates/rome_formatter/src/ts/statements/mod.rs
> +			let snapshot = formatter.snapshot();
Yeah. I also don't know of a better approach right now. I considered changing `token` to accept a `SyntaxToken` but it would then require additional IR elements to model `ReplacedToken` and `SkippedToken`. Let's go with what we have for now and re-visit it, for example, when working on CST to CST printing (maybe something you're interested in?)

2022-01-17 08:35 UTC, MichaReiser commented on crates/rome_formatter/src/ts/statements/variable_declaration_statement.rs
> +		let items = items
What's the reason we can't use `format_separated` for variable declarations?

2022-01-17 08:35 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +	pub fn format_or_create_token(
What I'm thinking of is

```
impl<T> ToFormatElement for Option<T> where T: ToFormatElement {
    fn to_format_element(&self, formatter: &Formatter) -> FormatElement {
        match self {
            Some(item) => item.to_format_element(formatter),
            None => empty_element()
        }
    }
}
```

This is still consistent in my view because formatting an `Option` becomes formatting any other *formattable* content.

2022-01-17 08:35 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +			if piece.as_newline().is_some() {
Right, but is it important to test if the comment contains a line breeak and if so, increase `line_count`?

Ah, no, it isn't needed. Can we change the `if piece.as_newline` into an `else if...` to make that clear. Would have been nice if `SyntaxTriviaPiece` is an `enum` so that you could match but this isn't the case.

2022-01-17 08:49 UTC, ematipico commented on crates/rome_formatter/src/formatter.rs
> +	pub fn format_or_create_token(
I like Micha's suggestion! And we should be safe because an optional element should always be replaced by an empty element, which is "fixed".

2022-01-17 08:49 UTC, leops commented on crates/rome_formatter/src/ts/bindings/array_binding_pattern.rs
> +		Ok(group_elements(formatter.format_delimited_group(
I agree the naming here is tricky: `group` doesn't necessarily mean an actual `FormatElement::Group` but a number of elements that are "semantically grouped" inside a block delimited by an opening and closing token, and these tokens can be parenthesis (arguments lists), brackets (array expressions) or curlies (object expression)

2022-01-17 10:06 UTC, leops commented on crates/rome_formatter/src/ts/statements/variable_declaration_statement.rs
> +		let items = items
Besides never wanting a trailing separator to be printed, the variables declarations after the first one are put in an indent group (the first declaration is printed inline after the var/let/const keyword)

2022-01-17 10:44 UTC, MichaReiser approved these changes

2022-01-17 10:53 UTC, leops commented on crates/rome_formatter/src/ts/statements/debugger_statement.rs
> +			formatter.format_or_create_token(self.semicolon_token(), || token(';'))?
I solved this by introducing a `FormattableToken` trait implemented by `SyntaxToken` and `Option<SyntaxToken>` so that `format_token` returns a `FormatElement` and `Option<FormatElement>` respectively depending on what type it's called with. I also implemented `From<Option<FormatElement>>` for `FormatElement` to turn `None` into `FormatElement::Empty`

2022-01-17 10:56 UTC, leops commented on crates/rome_formatter/src/ts/statements/break_statement.rs
> +		let semicolon = formatter.format_or_create_token(self.semicolon_token(), || token(';'))?;
This one is especially ambiguous since there is an "or" operation at work, hopefully with the new generic `format_token(optional).unwrap_or_else(fallback)` it should be clearer

2022-01-17 10:57 UTC, leops commented on crates/rome_formatter/src/ts/bindings/array_binding_pattern.rs
> +		Ok(group_elements(formatter.format_delimited_group(
I ended up renaming it to `format_delimited` (and `format_replaced_token` to `format_replaced`) so that they line up with the existing `format_separated`

2022-01-17 14:11 UTC, merged