fix(rslint_parser): binding redeclaration
rome/tools pull request #1929
Opened 2022-01-12 10:10 UTC by ematipico

## Summary

## Test Plan

2022-01-12 10:22 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +	blocks: VecDeque<HashMap<String, Range<usize>>>,
Do we need to keep a queue of hash maps? Isn't it sufficient to store the existing `HashMap` in the place where we start a new scope, replace it with an empty hash map, and then, when we leave the scope to replace it with the original one?

```
fn block_impl(p: &mut Parser) {
  let last = std::mem::take(&mut p.state.bindings);
  ....
  p.state.bindings = last;
}
```

2022-01-12 10:42 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +	blocks: VecDeque<HashMap<String, Range<usize>>>,
I still need to put more thought into the implementation. Even though your suggestion makes totally sense, new blocks are not confined only confined to `block_impl`. 

We might end up to have repeated code... I will try and see if we can make your solution more generic.

2022-01-13 15:38 UTC, MichaReiser reviewed
What's the impact on performance?

I'm a bit surprised that this is only fixing 4 tests. Shouldn't this fix much more tests?

2022-01-13 15:38 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +	blocks: VecDeque<HashMap<String, Range<usize>>>,
I don't think we need to track a `VecDequeue`. It seems all we need are two maps: 

1. To track the hoisted declarations 
2. To track the block-scoped declarations

The 1. must be re-set whenever we enter a function. You can achieve that by storing the existing map in `EnterFunction` and restoring it when we leave the function.

You can define a new `EnterBlock` `ChangeParserState` that does the same for the block-scoped variables: Stores away the existing map when entering and restores it when leaving. You can then add it to `parse_block`, that should be it. 

I would then add helper methods to the `ParserState` to test if a variable has already been declared and to register a new one `register_scoped_variable`, `register_hoisted_variable`. That should be sufficient.

2022-01-13 15:38 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +	hoisted_scopes: [HoistedVars; 2],
Why two? What are the two states?

2022-01-13 15:38 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +		} else if self.blocks.len() > 2 {
```
let a;
var a;
```

The `var a` clashes with the `let a`;

2022-01-13 15:38 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +	is_inside_block: bool,
Shouldn't this be `is_inside_function` in which case we must test against the hoisted vars in the function scope? You can use `in_function`  from the `ParserState`

2022-01-13 15:46 UTC, ematipico commented
> I'm a bit surprised that this is only fixing 4 tests. Shouldn't this fix much more tests?

The majority of redeclarations are around functions and classes.

I will make a separate PR for them

2022-01-13 15:51 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +	hoisted_scopes: [HoistedVars; 2],
We have a top-level scope and a scope defined by a block.

This is a valid syntax:

```js
var a;
{
 	let a;
}
```

This is invalid and the redeclaration is around the second `var`:

```js
var a;
{
  	var a;
 	let a;
}
```

And this is also invalid: 

```js
var a;
{
  	{ var a; }
 	let a;
}
```

Even though the second `var` is inside a block, it gets hoisted to the first one and `let` should fire a syntax error.

2022-01-13 15:55 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +	is_inside_block: bool,
A function is not the only one that can create a new scope. There are more cases:

- curly brackets `{  }`
- loops such as `while`, `for..`, etc.

2022-01-13 15:58 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +	is_inside_block: bool,
That's right. These could all use the `EnterScope` `ChangeParserState` helper.

2022-01-13 16:08 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +	blocks: VecDeque<HashMap<String, Range<usize>>>,
> The 1. must be re-set whenever we enter a function. You can achieve that by storing the existing map in EnterFunction and restoring it when we leave the function.

The solution proposed is only applicable to functions but not to other cases, for example:

```js
{
  function f() { var b; } 
  let b
}
```

In this case the solution would work and each scope would have its map of hoisted variables.

Unfortunately it's not the same for the following code:

```js
{
  { var b; }
  let b;
}
```

Here `{ var b; }`, the variable gets hoisted to the first block and `let b` can't be declared again.

2022-01-13 16:10 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +	blocks: VecDeque<HashMap<String, Range<usize>>>,
```
{
  { var b; }
  let b;
}
```

The `var b` gets hoisted into the global scope. Which is the default `hoisted_scope` if the parser isn't inside of a function.

2022-01-13 16:13 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +	blocks: VecDeque<HashMap<String, Range<usize>>>,
> The var b gets hoisted into the global scope.
I should have added some variable afterwards 😱 you're right!

2022-01-13 16:17 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +	hoisted_scopes: [HoistedVars; 2],
Yes, that was an error in my implantation. One scope for hoisted variables should be enough

2022-01-14 11:33 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +		is_var: bool,
Should we add an enum with the variants `Lexical` and `Hoisted` and then expose a single `register_name(name, VariableKind)` and `get_existing_name(name, VariableKind)` methods?

2022-01-14 11:35 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +	// parsing_context: ParsingContextFlags,
Delete?

2022-01-14 11:36 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +	scoped_variables: HashMap<String, Range<usize>>,
We need to capture the hoisted variables too.

2022-01-14 11:36 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/binding.rs
> +// var a; let a;
Can we add a test that bindings correctly respect function boundaries?

2022-01-14 11:45 UTC, MichaReiser commented
Do you know why your changes arent fixing for example 

```
language/block-scope/syntax/redeclaration/function-name-redeclaration-attempt-with-var.js
```

Is it because we only register `let/const/var` bindings for now?

2022-01-14 11:46 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/binding.rs
> +			let id = identifier_name.clone();
Can we replace the `name_map` above with your solution.

2022-01-14 11:47 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/binding.rs
> +			let is_var = parent == "var";
It may make sense to introduce an enum for `duplicate_binding_parent`, something like `BindingContext`. Because there can be more (`function`, `class`, ...)

2022-01-14 11:47 UTC, MichaReiser commented
I really like the implementation :)

2022-01-14 12:02 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +			scoped_variables: std::mem::take(&mut state.scoped_variables),
You'll need to change where we call `EnterFunction`. The problem is, that it's currently only wrapping the body of the function but not its parameters, meaning, parameters get declared in the outer scope which isn't correct. 

You need to change this for functions, methods, arrow functions etc.

2022-01-14 12:06 UTC, ematipico commented on crates/rslint_parser/src/syntax/binding.rs
> +			let is_var = parent == "var";
What  `duplicate_binding_parent` used for?

2022-01-14 12:09 UTC, ematipico commented
> Do you know why your changes arent fixing for example
> 
> ```
> language/block-scope/syntax/redeclaration/function-name-redeclaration-attempt-with-var.js
> ```
> 
> Is it because we only register `let/const/var` bindings for now?

Exactly that. The issue I am facing is that, the very moment we track also bindings for functions, we start having a lot of regressions due to the issue I explained in the description of the PR.

2022-01-14 12:11 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +	pub fn register_scoped_variable(&mut self, identifier_name: String, range: Range<usize>) {
Yeah, let's follow the spec. Thank you!

2022-01-14 12:21 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +			scoped_variables: std::mem::take(&mut state.scoped_variables),
If we decided to move `EnterFunction` before the parsing its body, would that break existing functionality?

2022-01-14 12:45 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +		is_var: bool,
We could even decide to re-use the same enum in the this weird `binding_parent` state (forgot its exact name). The enum could then have methods like `is_lexical()` and `is_hoisted` to determine how the binding must be declared. This way, the API become as simple as

```
get_binding(name, BindingParent::Function)
get_binding(name, BindingParent::Parameter)
register_binding(name, BindingParent::Function)
```

2022-01-14 12:46 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/binding.rs
> +			let is_var = parent == "var";
You use it here :D To track if we're inside a `var`, `let` or `const` declaration. But we should extend it to support any possible binding parent / context.

2022-01-14 12:47 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +			scoped_variables: std::mem::take(&mut state.scoped_variables),
Using `EnterScope` might be the best solution because arguments are always declared as lexical scoped, right?

2022-01-14 13:16 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +			scoped_variables: std::mem::take(&mut state.scoped_variables),
Yes

> Using `EnterScope` might be the best solution because arguments are always declared as lexical scoped, right?

Yes they are:

```js
var a = "3";

function f(a = "f") {
    console.log(a)
}

const d = (a = "33333") => {
    console.log(a)
}
f(); // logs "f"
d(); // logs "33333"
```

2022-01-19 15:31 UTC, leops commented on crates/rslint_parser/src/state.rs
> +                                if self.in_function_block() || self.strict().is_none() {
If I'm reading this correctly if self.strict() returns None this will always enter the first branch (and always return None in that case), and the program can only enter the second branch if strict returns Some(_) so the two gets could be directly chained without calling self.strict() again

2022-01-19 15:59 UTC, yassere commented on crates/rslint_parser/src/state.rs
> +                - ParsingContextFlags::IN_FUNCTION_BLOCK,
What's the purpose of subtracting the flag here? Isn't that a no-op since the `IN_FUNCTION_BLOCK` flag isn't part of the union?

2022-01-19 17:13 UTC, MichaReiser requested changes
Wow, this turned out to be a lot of changes. 

I spotted a few logical errors and believe that we can simplify the design even further. Mainly, I have the feeling that there's a lot of overlap between `BindingContext` and `NameType`. My understanding is that `NameType` says what kind of binding it is. Ideally, we would only have `Hoisted` and `Lexical` but, unfortunately, the type of binding sometimes differs depending on the `BindingContext`. One such example are function ids, where the id either gets lexically bound or is hoisted. 

That's why I think that `BindingContext` should only hold the values `TopLevel`, `Block`, `FunctionBlock`. 

`NameType` then lists the different bindings. The generic ones `Hoisted` and `Lexical` for the cases where the binding type doesn't depend on the `BindingContext`. But it also has variants for when it is less clear, like `FunctionId` (and maybe others).

2022-01-19 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +pub enum NameType {
I get the impression that `NameType` and `BindingContext` are overlapping. 

My understanding is that there it's relevant to know the context in which a binding appears because there are different rule depending if you are:

* Top-Level
* Inside a Function body
* Inside a block statement

I believe that's what we want to represent with `BindingContext`.

Then, there's `NameType` (or `BindingType`?). It specifies what kind of binding it is. The different bindings seem to be

```
  Var
  Let,
  Const,
  Argument,
  FunctionId,
  CatchDeclaration,
  Import,
  // Exports?
```

I think it would make sense to restructures the enum in that way and pass `NameType` directly to the register/clash functions

(We can also use `Lexical(LexicalType)` for all cases where the binding always is a lexical binding and only list the ones where the binding type depends on the binding context).

2022-01-19 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +        if let Some(binding_context) = self.binding_context() {
I recommend calling `expect()` on the `binding_context` to prevent that we miss any registrations. Not setting the binding context and then calling this method is a logic error.

2022-01-19 17:13 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +                BindingContext::Arguments => self
I find this whole block hard to read. It seems that a lot of the validation depends if strict mode is enabled or not. 

It may help to split the logic then: 

* Validation that must always be done regardless if it's strict mode or not
* Validation that only must be done in strict-mode. 

Or use ` NameType::Hoisted if self.strict.is_some() => ` instead of the `and_then` might help as well.

It could also improve readability if you collapse match arms that have the same behaviour.

2022-01-19 17:16 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +                - ParsingContextFlags::IN_FUNCTION_BLOCK,
Yes, that change was not meant to be there. Fixed!

2022-01-19 17:20 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +                                if self.in_function_block() || self.strict().is_none() {
Good catch, it was a copy/paste gone wrong. Do you agree with me that we can write like this?

```rs
if self.in_function_block() || self.strict().is_none() {
    self.lexical_names.get(identifier_name)
} else {
    self.lexical_names
        .get(identifier_name)
        .or_else(|| self.hoisted_names.get(identifier_name))
}
```

2022-01-19 17:27 UTC, ematipico commented on crates/rslint_parser/src/syntax/function.rs
> +        p.with_state(EnterLexicalScope(BindingContext::FunctionBlock), |p| {
I explained in the description why it's not possible to join the two:

- https://github.com/rome/tools/blob/main/crates/rslint_parser/src/syntax/function.rs#L248-L249
- https://github.com/rome/tools/blob/main/crates/rslint_parser/src/syntax/function.rs#L380-L382

We can't apply a new lexical scope when we are inside the body, we have to do that before we enter the parameters. When we enter the function body, we need to create a new name scope.

2022-01-19 17:32 UTC, ematipico commented on crates/rome_formatter/tests/specs/js/array/binding_pattern.js
> +let [d,...e]=c;
How would you suggest to do that? All tests will fail if I don't update the snapshots

2022-01-19 17:36 UTC, yassere commented on crates/rslint_parser/src/state.rs
> +                BindingContext::Arguments => self
Another possible readability improvement here is to reduce rightward drift by using the `?` operator in match expressions and replacing constructs like:
```rs
if let Some(binding_type) = self.binding_type() {
    match binding_type {
        // …
    }
} else {
    None
}
```
with
```rs
match self.binding_type()? {
    // …
}
```

2022-01-19 17:38 UTC, ematipico commented on crates/rslint_parser/src/syntax/binding.rs
> +        let err = if binding_context.is_some() {
Small error of mind, we should always have a binding context, I will remove the `Option<>`.

2022-01-19 17:55 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +                        let p =
> The BindingContext::Arguments is misleading because the body won't be parsed in an Arguments context.

It's actually the whole point, but I can see why it can be misleading. The thing is that they must be parsed in two different context because parameters behave differently: they are hoisted but can't clash in strict mode.


> I propose to remove the BindingContext arguments from EnterHoistedScope and instead set the BindingContext as part of EnterParameters.

Please read the description of the issue, where I explained why we can't do that, unless we can make the snapshot changes of `EnterParamters` last until the function body is parsed.

> Nit: Can we rename BindingContext::Arguments to Parameters to align it with EnterParameters. Arguments are what we pass in a call expressions. Parameters are the variables defined in a function signature (parametrises the functions behaviour)

Makes sense!

2022-01-19 18:01 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/js/array/binding_pattern.js
> +let [d,...e]=c;
Split out the change in another PR and land that first

2022-01-19 18:04 UTC, ematipico commented on crates/rslint_parser/src/syntax/module.rs
> +    p.with_state(EnterVariableDeclaration(NameType::Module), |p| {
Yeah this will be gone

2022-01-19 18:05 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +            parse_block_stmt(p)
We can't, because this function is also used inside to parse the function body, where we need to create a `BindingContext::FunctionBlock` instead. Do you want to add a second argument to `parse_block_stmt`?

2022-01-19 18:09 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +    let p = &mut *p.with_scoped_state(EnterHoistedScope(BindingContext::LoopStatements));
Probably you executed some other code before which conflicted with that snippet. That is valid code

2022-01-19 18:11 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +    let p = &mut *p.with_scoped_state(EnterLexicalScope(BindingContext::Block));
Good catch, not needed!

2022-01-19 18:13 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +    let p = &mut *p.with_scoped_state(EnterHoistedScope(BindingContext::Block));
Yes, `switch` creates a new hoisted scope. You probably run some other snippet before, which caused some conflict.

2022-01-19 18:15 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +    p.with_state(EnterLexicalScope(BindingContext::Block), |p| {
`parse_block_stmt` is used for normal blocks and function blocks too. This won't work. Do you want to add a new parameter to `parse_block_stmt`?

2022-01-19 18:17 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +    let p = &mut *p.with_scoped_state(EnterHoistedScope(BindingContext::Block));
`try/catch/finally` all create a new lexical scope. `catch` also creates a hoisted scope:

This code will fail:

```js
try {} catch (e) { let e; }
```

Because we can't redeclare `e`

2022-01-19 18:18 UTC, ematipico commented on crates/rslint_parser/src/syntax/stmt.rs
> +    p.with_state(EnterLexicalScope(BindingContext::Block), |p| {
See https://github.com/rome/tools/pull/1929#discussion_r788011748

2022-01-19 18:18 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +    binding_type: Option<NameType>,
See https://github.com/rome/tools/pull/1929#discussion_r788011748

2022-01-19 18:20 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +    Arguments,
Unfortunately not, because parameters need a special treatment: even though they are hoisted, they can't be duplicated. Whilst normal hoisted names can be re-declared without issue.

2022-01-19 18:24 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +pub enum NameType {
I like the suggestion, I think we can cover all the cases with this naming convention. I knew e different pair of eyes would have helped :) 

Thank you

2022-01-19 18:25 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +        if let Some(binding_context) = self.binding_context() {
This won't be needed anymore, I will remove the `Option`

2022-01-19 18:33 UTC, MichaReiser commented on crates/rslint_parser/src/state.rs
> +        const IN_FUNCTION_BLOCK = 1 << 12;
How's that different from function body

Is it possible to derive it from in_function and BindingContext::Blick

2022-01-19 18:35 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/function.rs
> +        p.with_state(EnterLexicalScope(BindingContext::FunctionBlock), |p| {
It may then make sense to split EnterFunction and EnterFunctionBody

2022-01-20 08:20 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +        const IN_FUNCTION_BLOCK = 1 << 12;
`EnterFunction` is the snapshot that sets the `IN_FUNCTION` bitflag, and `EnterFunction` at the moment, it's not what I need.

2022-01-20 10:18 UTC, ematipico commented
I am going to pause the works around this PR. It needs some decisions because:
- there still, probably some false positives and some false negatives
- it requires some more engineering works to the whole parsing infrastructure
- this solution could be achieved easily with a second pass

2022-05-09 07:23 UTC, MichaReiser commented
@ematipico is it OK to close this PR now that @xunilrj is working on scope resolution?

2022-05-22 11:22 UTC, closed without merging