Arrow function and assignment line breaking
rome/tools pull request #1993
Opened 2022-01-24 20:55 UTC by NicholasLYang

## Summary

Added line breaking after `=>` and `=` in arrow functions and assignments respectively.

## Test Plan
We already have some tests in place for arrow functions and assignments.

2022-01-25 07:26 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +/// otherwise. Does not insert a new line at the end, as this messes up semicolon placement
Nit: The `messes up` semicolon placement is to be specific to one use case and out of context in this documentation (what semicolon?). 

Can we describe this more conceptually. It inserts an optional line break and indents the content if the group doesn't fit on a new line. Inserts a space otherwise.

2022-01-25 07:26 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +pub fn soft_indent_or_space<T: Into<FormatElement>>(content: T) -> FormatElement {
nit: Wdyt of `soft_line_indent`?

2022-01-25 09:06 UTC, leops commented on crates/rome_formatter/src/ts/expressions/import_meta_expression.rs
> +impl ToFormatElement for ImportMeta {
I think the AST nodes that implement `ToFormatElement` must be added to the match in `cst.rs`, as I understand it cannot be automatically generated yet because not every node is supported by the formatter

2022-01-25 09:49 UTC, MichaReiser commented on crates/rome_formatter/src/ts/expressions/import_meta_expression.rs
> +impl ToFormatElement for ImportMeta {
We could generate the file if the code gen generates empty boilderplates for every node (that call into `format_verbatim`). It's just that no one implemented the code gen part yet ;)

2022-01-25 12:29 UTC, NicholasLYang commented on crates/rome_formatter/src/format_element.rs
> +pub fn soft_indent_or_space<T: Into<FormatElement>>(content: T) -> FormatElement {
Sure! I added the `or_space` to match `soft_line_break_or_space`. Do you think we should keep it?

2022-01-25 13:00 UTC, ematipico requested changes
There are two files: `checker.js` and `format-folder.patch` that don't belong to this PR, I think

2022-01-25 13:00 UTC, ematipico commented on format-folder.patch
> +From 8a724165569993b942bec7ea63cac375faa54881 Mon Sep 17 00:00:00 2001
This file should not be here

2022-01-25 13:33 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +pub fn soft_indent_or_space<T: Into<FormatElement>>(content: T) -> FormatElement {
Probably makes sense to have it explicit: `soft_line_indent_or_space`.

2022-01-25 16:54 UTC, NicholasLYang commented on crates/rome_formatter/src/ts/auxiliary/any_function.rs
> +        let body_has_soft_line_break = matches!(
Honestly I ported this from the old Rome, but the general idea seems to be that we don't want to line break too early. We don't know that these nodes have line breaks other than their implementation because there's no real overarching rule about which nodes have line breaks.

I'll try to flesh out the explanation and provide some examples

2022-01-25 17:00 UTC, NicholasLYang commented on crates/rome_formatter/tests/specs/js/arrow/params.js.snap
> +		dispatch(action),
Oooh yeah good catch! Forgot to group at the end of the function formatting

2022-01-26 16:07 UTC, NicholasLYang commented on crates/rome_formatter/src/ts/auxiliary/any_function.rs
> +        let body_has_soft_line_break = matches!(
According to prettier, chained arrow functions are not broken until it's so long that they're all line broken. I've noticed that pattern in prettier where there's a bail for extremely long lines where it vertically stacks everything. We can implement that in the future. As for now, we shouldn't break after a `=>` if it's followed by another arrow function.

2022-01-31 13:12 UTC, MichaReiser approved these changes

2022-01-31 14:44 UTC, merged