Feature/ts types
rome/tools pull request #2001
Opened 2022-01-25 15:29 UTC by MichaReiser

## Summary

Adds parsing for typescript types

## Test Plan

2022-01-26 16:58 UTC, MichaReiser commented
lol, this fixes the last panic. Nice ;)

2022-01-26 17:05 UTC, MichaReiser commented on crates/rome_rowan/src/syntax_factory.rs
> +struct SeparatedListWithMissingNodesOrSeparatorSlotsIterator<'a, K: SyntaxKind, S: Separator<K>> {
TypeScript allows `,` and `;` as separator between object type members: `{ a: string, b: number; c: "test" }`

2022-01-26 17:05 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +        TypeScript
I didn't add the `TypeScript` gating code everywhere it is needed. That's something we must do when working on the remaining TS syntax.

2022-01-27 10:25 UTC, ematipico requested changes
The PR is too big and I am having hard time to check all of it, especially `typescript.rs`. I left some comments around the grammar. 

I believe the majority of the functions should require some documentation, so other developers can piggyback the code without too much friction

2022-01-27 10:25 UTC, ematipico commented on xtask/codegen/js.ungram
> +	']'
Arrays types can also be defined like this: `Array<string>`. Should we add this to the grammar?

2022-01-27 10:25 UTC, ematipico commented on xtask/codegen/js.ungram
> +TsArrayType =
Small example please?

2022-01-27 10:25 UTC, ematipico commented on xtask/codegen/js.ungram
> +	']'
Small example please?

2022-01-27 10:25 UTC, ematipico commented on xtask/codegen/js.ungram
> +	']'
Small example please?

2022-01-27 10:25 UTC, ematipico commented on crates/rslint_parser/src/parser.rs
> +    #[inline]
Small documentation please?

2022-01-27 10:25 UTC, ematipico commented on crates/rslint_parser/src/parser/parsed_syntax.rs
> +    pub fn marker(&self) -> Option<&CompletedMarker> {
Can't find this function. Probable it's not used?

2022-01-27 10:25 UTC, ematipico commented on crates/rslint_parser/src/state.rs
> +pub(crate) struct EnterType;
Small documentation please?

2022-01-27 10:25 UTC, ematipico commented on crates/rslint_parser/src/syntax/function.rs
> +pub(super) fn skip_parameter_start(p: &mut Parser) -> bool {
Can we document the function please? I'm having hard time to understand what's used for

2022-01-27 10:25 UTC, ematipico commented on crates/rslint_parser/src/syntax/typescript.rs
> +#[inline]
Why are we ` #[inline]` this function?

2022-01-27 10:25 UTC, ematipico commented on crates/rslint_parser/src/syntax/typescript.rs
>  use super::expr::{
`typescript.rs` has grown too much I think. Can we break it down into separate files and make is a folder `typescript/` instead? Not necessarily  now, maybe later

2022-01-27 10:25 UTC, ematipico commented on crates/rslint_parser/src/syntax/util.rs
> +pub(crate) fn is_at_contextual_keyword(p: &Parser, name: &str) -> bool {
Small documentation?

2022-01-27 10:25 UTC, ematipico commented on crates/rslint_parser/src/syntax/util.rs
> +pub(crate) fn is_nth_at_contextual_keyword(p: &Parser, n: usize, name: &str) -> bool {
Small documentation?

2022-01-27 10:25 UTC, ematipico commented on crates/rslint_parser/src/syntax/util.rs
> +pub(crate) fn eat_contextual_keyword(
Small documentation?

2022-01-27 10:25 UTC, ematipico commented on crates/rslint_parser/src/syntax/util.rs
> +pub(crate) fn expect_contextual_keyword(
Small documentation?

2022-01-27 11:30 UTC, MichaReiser commented
> I believe the majority of the functions should require some documentation, so other developers can piggyback the code without too much friction

The functions are all named after the grammar rules. I don't know what else to document other than that they parse the syntax after which they're named. But that's already given by the function name.

2022-01-27 11:31 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	binding_identifier: JsIdentifierBinding
Good catch. That's a bit surprising but makes sense. I can introduce a `TsIdentifierBinding`

2022-01-27 11:37 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	keys_type: TsType
That's correct but it would requires different union types for all cases where only a limited set of types is needed. This is the same as for `BinaryExpression` where not any expressions are valid left- or right-hand sides. Nevertheless, the expression is typed as any expression. 

Allowing more syntax provides more flexibility and allows to mark nodes as invalid in specific context if we have a second pass. Overall, the parser's recovery stands in direct conflict with a strict AST because it limits it's options. 

I believe that using the more generic type is better than having a over detailed AST which requires a ton of additional nodes and unions and naming is hard.

2022-01-27 11:37 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	']'
This is a `TsReferenceType` with type parameters.

2022-01-27 11:38 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +TsArrayType =
I'm not sure if it makes sense to add examples to all rules. Many are fairly obvious from the grammar. It's `type[]`

2022-01-27 11:39 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
>  use super::expr::{
Could make sense to split it as part of it's own PR

2022-01-27 11:42 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript.rs
>  use super::expr::{
Agreed. I was actually planning on doing this already on my PR.

2022-01-27 12:15 UTC, ematipico commented on crates/rslint_parser/src/syntax/typescript.rs
>  use super::expr::{
> Could make sense to split it as part of it's own PR

Starting here might help to understand what actually is new and what actually has been modified/refactored. Unless everything was already there 🤔

Anyway, not a blocker

2022-01-28 10:31 UTC, ematipico commented on xtask/codegen/js.ungram
> +	keys_type: TsType
Sure, no problem

2022-01-28 12:00 UTC, ematipico commented
I was wondering if we can split this PR in two/three parts? Maybe one with just the new grammar (and auto generated code), one with the new implementation?

2022-01-28 12:22 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
>  use super::expr::{
That's easy. I deleted all existing type parsing and replaced it with a new one. So all is new :D #

2022-01-28 12:24 UTC, MichaReiser commented
> I was wondering if we can split this PR in two/three parts? Maybe one with just the new grammar (and auto generated code), one with the new implementation?

I don't think that splitting it that way adds a lot of value

* Generated code is generated. No need to review it
* The grammar and parser logic go hand in hand or we need to keep the old grammar around as well, which makes the changes more difficult. 

The only option I could see is to split by different parsing rules but the parsing rule code doesn't add anything fancy and are heavily inspired by the TypeScript parser. 

That's why I would focus the review on the grammar changes, as you already did!

2022-01-28 14:07 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
> +#[inline]
To avoid that the parser repetitively calls into the `IntersectionOrUnionType` methods that match on self. There are only two call-sites. So inlining should be fine.

2022-01-28 14:07 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
>  use super::expr::{
Moved it out into its own `types.rs`

2022-01-28 14:10 UTC, MichaReiser commented
@ematipico I addressed your review feedback and wrote additional documentation.

2022-01-31 08:46 UTC, ematipico approved these changes

2022-01-31 09:15 UTC, merged