typescrip enum parsing
rome/tools pull request #2039
Opened 2022-02-02 11:46 UTC by xunilrj

2022-02-02 12:12 UTC, ematipico commented on xtask/codegen/js.ungram
> +	name: JsName
It seems that it's valid to have 

```ts
enum a {}
enum a {}
```

But it's not valid 
```ts
enum a {}
type a = string;
```

The TS compiler doesn't complain about double binding, but something else. I wonder if it makes sense to map the name of the `enum` as binding or not. `JsName` might be too broad

2022-02-02 12:26 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	name: JsName
The enum `id` should be a `JsAnyBinding` because it binds a value in the current scope. For example, the following is valid 


```
enum TestEnum {
    A,
    B
}

console.log(TestEnum);
```

Meaning, enums are different from type aliases because they not only introduce a type but also a name in the current scope. And this is our definition of bindings.

2022-02-02 18:08 UTC, xunilrj commented on xtask/codegen/js.ungram
> +	name: JsName
hum... the error ```ts``` gives is about merging: https://www.typescriptlang.org/docs/handbook/declaration-merging.html
This rule is more complex than just name binding. I think this makes more sense in a semantic validation.

2022-02-02 19:44 UTC, xunilrj commented on xtask/codegen/js.ungram
> +	name: JsName
> The enum id should be a JsAnyBinding

Done.

2022-02-03 20:46 UTC, xunilrj commented
The regression seem to be error edge cases. I think it makes sense to postpone them.

2022-02-04 08:54 UTC, MichaReiser requested changes

2022-02-04 08:54 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +TsEnum =
Can we rename the node to `TsEnumStatement`

2022-02-04 08:54 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	name: JsAnyBinding
Can we rename the field to `id` to align it with `class`. It also makes it clearer that it doesn't allow arbitrary names, only ids

2022-02-04 08:54 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	(initializer: JsInitializerClause)?
Nit: You don't need the parenthesizes here
```suggestion
	initializer: JsInitializerClause?
```

2022-02-04 08:54 UTC, MichaReiser commented on xtask/codegen/src/ast.rs
> +                dbg!(&name, &element_name, &separator);
Delete?

2022-02-04 08:54 UTC, MichaReiser commented on xtask/codegen/src/ast.rs
> +                println!("{:?}", comma_list);
Delete?

2022-02-04 08:54 UTC, MichaReiser commented on xtask/codegen/src/ast.rs
> +    // println!("2: {}", matches!(rules, [Rule::Node(node), Rule::Rep(repeat)]));
Delete?

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
> +            Present(m.complete(p, TS_TYPE_ASSERTION_EXPRESSION))
My understanding is that you can have multiple decorators, pass arguments, etc. We would also need to add the decorators to all nodes that potentially support decorators (and introduce the right node type). 

I would leave this for it's own PR if we decide to support it.

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
> +        _ => Absent,
You aren't allowed to return `Absent` here because the function has eaten one token, the `@`. Either lookahead two tokens at the top of the function or simply complete the marker in this case. The `decorator.ident()` then returns `Err`

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +pub(super) fn parse_literal_member_name(p: &mut Parser) -> ParsedSyntax {
Nit: Make private?

You can simplify this method to avoid copying most of the `parse_literal_member_name` function from `object.rs`. 

```rs
if p.at(JS_NUMBER_LITERAL) {
   let err = p
                .err_builder("An enum member cannot have a numeric name")
                .primary(p.cur_tok().range(), "");
            p.error(err);
}

parse_literal_member_name(p)
```

Nit: Please rename the method. It's now clashing with the `parse_literal_member_name` from `object.rs`. For example to `parse_ts_enum_member_name`

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +    }
You aren't allowed to return `Absent` here because the function may already have parsed a decorator out which now gets attached to the parent. You need to test that neither name nor decorator are present.

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +    let _ = parse_initializer_clause(p, ExpressionContext::default());
Nit
```suggestion
    parse_initializer_clause(p, ExpressionContext::default()).ok();
```

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +    }
Changing the `enum` to `Unknown` isn't needed. The grammar doesn't specify a decorator field. Thus, the `JsSyntaxFactory` will mark the node as unknown because it detects that the enum has more children than it's supposed to have

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                token_set![JsSyntaxKind::IDENT, T![,], T!['}']],
You may want to include `STMT_RECOVERY_SET` to recover from

```
enum A {
  test

function a() {
}
```

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +}
Same as `is_reserved_type_name`?

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +pub fn ts_enum(p: &mut Parser) -> CompletedMarker {
Nit: pub(crate) 

Can we rename it to `parse_ts_enum_statement` and return a `ParsedSyntax`

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +fn parse_name(p: &mut Parser, enum_token_range: Range<usize>) {
Nit: `parse_enum_id`

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +    };
This check isn't needed. `parse_binding` returns `Absent` if the parser is positioned at `{`

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +            if p.nth_at(1, L_CURLY) {
Please add tests for the error recovery

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                p.bump_remap(T![ident]);
Don't remap the whatever it is as an `ident` or a `JsIdentifierBinding`. You can create a `JsUnknownBinding` if you want to have this kind of error recovery here.

2022-02-04 08:54 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                            "`{}` cannot be used as a enum name because it is already reserved as a enum",
already reserved as a type name?

2022-02-04 10:25 UTC, xunilrj commented on xtask/codegen/js.ungram
> +TsEnum =
Done.

2022-02-04 10:25 UTC, xunilrj commented on xtask/codegen/js.ungram
> +	name: JsAnyBinding
Done.

2022-02-04 10:25 UTC, xunilrj commented on xtask/codegen/js.ungram
> +	(initializer: JsInitializerClause)?
Done.

2022-02-04 10:25 UTC, xunilrj commented on xtask/codegen/src/ast.rs
> +                dbg!(&name, &element_name, &separator);
Done.

2022-02-04 10:26 UTC, xunilrj commented on xtask/codegen/src/ast.rs
> +                println!("{:?}", comma_list);
Done.

2022-02-04 10:26 UTC, xunilrj commented on xtask/codegen/src/ast.rs
> +    // println!("2: {}", matches!(rules, [Rule::Node(node), Rule::Rep(repeat)]));
Done.

2022-02-04 10:31 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript.rs
> +            Present(m.complete(p, TS_TYPE_ASSERTION_EXPRESSION))
Yes. I went with the simplest possible implementation just to start. I can remove it.

2022-02-04 10:33 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript.rs
> +        _ => Absent,
I removed the decorator for now.

2022-02-04 10:35 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +pub(super) fn parse_literal_member_name(p: &mut Parser) -> ParsedSyntax {
Done.

2022-02-04 10:35 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +    }
Removed the decorator.

2022-02-04 10:37 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                token_set![JsSyntaxKind::IDENT, T![,], T!['}']],
The problem is that ```STMT_RECOVERY_SET``` has `;`.

2022-02-04 10:38 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +}
Done.

2022-02-04 10:38 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +pub fn ts_enum(p: &mut Parser) -> CompletedMarker {
Done.

2022-02-04 10:39 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +fn parse_name(p: &mut Parser, enum_token_range: Range<usize>) {
Done.

2022-02-04 10:39 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +    };
Done.

2022-02-04 13:32 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +            if p.nth_at(1, L_CURLY) {
Done.

2022-02-04 14:12 UTC, ematipico requested changes

2022-02-04 14:12 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +        _ => parse_binding(p),
We should be careful because when we have `implements`, what comes after can be also a `TsIdentifierBinding`.

For example, this is a valid syntax:

```ts
type A = {};
class B implements A {}
```

We should add a `TODO`, revert the logic or take this into account.

2022-02-04 14:12 UTC, ematipico commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                .err_builder("An enum member cannot have a numeric name")
If this is a new error, should we have an error case to cover it?

2022-02-04 14:12 UTC, ematipico commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                .err_builder("An enum member cannot have a numeric name")
```suggestion
                .err_builder("An `enum` member cannot have a numeric name")
```

2022-02-04 14:12 UTC, ematipico commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                .err_builder("An enum member cannot be private")
```suggestion
                .err_builder("An `enum` member cannot be private")
```

2022-02-04 14:12 UTC, ematipico commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +}
Can we move this function inside a `ts_parse_error.rs` file?

2022-02-04 14:12 UTC, ematipico commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                let err = p.err_builder("invalid enum name").primary(range, "");
```suggestion
                let err = p.err_builder("Invalid `enum` name").primary(range, "");
```

2022-02-04 14:12 UTC, ematipico commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                    .err_builder("enum declarations must have a name")
```suggestion
                    .err_builder("`enum` statements must have a name")
```

2022-02-04 14:12 UTC, ematipico commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +    let m = p.start();
Shouldn't this return `Absent` if `enum` is not found? This means that if we find

```ts
const e;
```

The parser should not advance because it's not a enum statement, and return `Absent`.

2022-02-04 14:12 UTC, ematipico commented
@xunilrj the PR contains a `.txt` file that should not be there

2022-02-04 15:04 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                .err_builder("An enum member cannot be private")
Done.

2022-02-04 15:09 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +}
Done.

2022-02-04 15:10 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                let err = p.err_builder("invalid enum name").primary(range, "");
Done.

2022-02-04 15:10 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                    .err_builder("enum declarations must have a name")
Done.

2022-02-04 15:51 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +    let m = p.start();
Done.

2022-02-04 15:52 UTC, xunilrj commented
> @xunilrj the PR contains a `.txt` file that should not be there

Fixed.

2022-02-04 18:31 UTC, xunilrj commented on crates/rslint_parser/src/syntax/class.rs
> +        _ => parse_binding(p),
Did the "TODO".

2022-02-04 18:33 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                            "`{}` cannot be used as a enum name because it is already reserved as a enum",
Makes more sense.

2022-02-05 21:07 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +    let _ = parse_initializer_clause(p, ExpressionContext::default());
I actually prefer the ``let _ =```` because it is easier to find, and it is guaranteed to not generate any code by the compiler.

2022-02-05 21:46 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +                p.bump_remap(T![ident]);
Makes sense. I am now ```bump_any``` and producing a ```JS_UNKNOWN_BINDING```

2022-02-07 07:21 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +}
Nit: Passing in `t` (which seems to be the current token?) and using offsets is error prone. There's no guarantee that `t` is the current token. 

It may further help readability to split this into a few more if statements

```rust
if p.cur_at(T![enum]) && (is_l_curly1 || is_l_curly2) { 
  return true;
}

if p.cur_at(T![const]) && p.nth_at(T![enum]) && (is_l_curly_2 || p.nth_at(3, T!['{']))
```

Is the test for the curly needed? What if someone wrote `enum id`, shouldn't we parse this as enum too? Isn't it sufficient to test for the `enum` keyword only because neither of these two statements are valid

```
enum;
const enum;
```

2022-02-07 07:21 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +        return Absent;
Returning `Abandon` here violates the contract that a parse method doesn't eat any token when returning `Abandon`. 

The problem is, that the parse method may have eaten the `const` keyword already and now attaches it to an arbitrary parent node. 

I suggest either calling `is_at_ts_enum_statement` first or testing `p.cur_at(T![enum]) || p.nth_at(1, T![enum]))`

2022-02-07 07:56 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +        T!['['] => syntax::object::parse_computed_member_name(p),
The regressions are all related to computed property names not being valid. But that seems to be something that applies across classes, enums, interfaces, objects... Maybe something for another PR?

2022-02-07 12:32 UTC, xunilrj commented on crates/rslint_parser/src/syntax/stmt.rs
> +        t if is_at_ts_enum_statement(p, &t) => parse_ts_enum_statement(p),
hum... that is an interesting question...

The generated asm is wild, but it looks like it is first comparing itself with L_CURLY (token 6)

```rust
> cargo asm --rust rslint_parser::syntax::stmt::parse_statement
...
.LBB666_229:
 #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)] (C:\github\rome\tools\crates\rslint_syntax\src\generated.rs:6)
    cmp     word, ptr, [rbp, +, 638], 6
 t if is_at_ts_enum_statement(p, &t) => parse_ts_enum_statement(p),
    je      .LBB666_320
    cmp     word, ptr, [rbp, +, 424], 6
    jne     .LBB666_436
    jmp     .LBB666_320
...
```

If I help the compiler a little bit we have a comparison with token 73, which I think is ```ENUN_KW```

```rust
self.nth_tok(n).kind == kind (src\parser.rs:196)
     lea     rdx, [rcx, +, 2*rcx]
     #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)] (C:\github\rome\tools\crates\rslint_syntax\src\generated.rs:6)
     cmp     word, ptr, [r14, +, 4*rdx, +, 8], 73
t if is_at_ts_enum_statement(p, &t) => parse_ts_enum_statement(p),
    jne     .LBB666_499
    or      al, bl
    je      .LBB666_499
.LBB666_320:
    mov     rcx, r12
    call    rslint_parser::syntax::typescript::enums::parse_ts_enum_statement
    jmp     .LBB666_53
```

So I think the compiler does need a little bit of help here.
Your suggestion does make sense!

2022-02-07 13:21 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +        }
You can do

```
let is_number = p.at(JS_NUMBER_LITERAL);

parse_literal_member_name(p).map(|literal| {
  if is_number {
    ... errror
  }
})
```

It's shorter and avoids a lot of repetition. But go with your preferred approach.

2022-02-07 13:23 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +        return Absent;
Done.

2022-02-07 13:25 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +        T!['['] => syntax::object::parse_computed_member_name(p),
Yes. They also seem to be changing the compiler target ``es`` version. We may need to discuss what to do with these.

2022-02-07 15:01 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/enums.rs
> +}
Did the changes.
I have also created some more ```test_err``` files.

2022-02-07 15:30 UTC, MichaReiser approved these changes

2022-02-07 15:56 UTC, ematipico approved these changes

2022-02-07 16:08 UTC, merged