feature(rslint_parser): TypeScript parameter extensions
rome/tools pull request #2040
Opened 2022-02-02 16:12 UTC by MichaReiser

## Summary

Implements the parsing for TypeScript's function and cosntructor parameter extensions.

## Test Plan

2022-02-03 10:50 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	'this'
I'm torn if this should be a binding identifier or not

Pros: 
* `JsAnyParameter` can implement a `binding` accessor that returns `SyntaxResult`. This isn't possible if `this` is a token
* `this` appears in a binding context

Cons:
* The identifier should ever only be `this`. Thus, it should be safe to encode it
* `this` isn't binding a new variable in the function scope because `this` is a valid binding in all functions. It may drip analyzers if they introduce a `this` binding for a function.

2022-02-03 12:44 UTC, ematipico requested changes
I noticed that there are error case, I think we should add error cases where we attempt to use `this` as parameter inside an arrow function.

2022-02-03 12:44 UTC, ematipico commented on xtask/codegen/js.ungram
> +// (this) => {}
Can we change the example? `this` is not allowed in a arrow function (in TS),  it could be misleading.

2022-02-03 12:44 UTC, ematipico commented on xtask/codegen/js.ungram
> +	'this'
Typescript AST marks `this` [as an identifier](https://ts-ast-viewer.com/#code/GYVwdgxgLglg9mABAQwBRQBYwM4C5HZQBOMYA5gDSIBGcc+YIAttQKZECUiA3gL4BQQA).

I suspect that they do the binding check during a second pass.

2022-02-03 12:44 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +						.primary(range, "");
It seems there's some issue with the formatting here (I see tabs)

2022-02-03 12:44 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +    __LAST = 5,
What does it represent? Does it require some doc?

2022-02-03 12:44 UTC, ematipico commented on crates/rslint_parser/src/syntax/class.rs
> +                    assert!(index < ModifierKind::__LAST as usize);
What's a situation where we could incur in an error here? Is it safe to use `assert` instead of `debug_assert`?

2022-02-03 12:55 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	'this'
TypeScript uses a single `Parameter` node to represent all possible parameters. That kind of forces them to use an `Identifier`. They also don't have the concept of binding identifiers.

2022-02-03 12:56 UTC, MichaReiser commented
> I noticed that there are error case, I think we should add error cases where we attempt to use `this` as parameter inside an arrow function. It's not valid in TS.

Argh, why xD I mean... it does make sense but it adds another invariant.

2022-02-03 13:08 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +						.primary(range, "");
Our editorconfig isn't correct. It selects `*.rs` instead of `**.rs`.

2022-02-03 13:14 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +                    assert!(index < ModifierKind::__LAST as usize);
The `modifiers` array has a fixed-length set to the value of `ModifierKind::__LAST` (the last variant of the enum). It's, therefore, guaranteed that the index is always less than `ModifierKind::__LAST`. 

We could make this a `debug_assert` but it shouldn't matter much.

2022-02-03 13:15 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/function.rs
> +pub(crate) enum ParameterContext {
Nice catch. I'm wondering if we should split out a `JsAnyArrowFunctionParameter` union that doesn't include the `TsThisParameter` but I'm worried that this is a bit overkill and will lead to a bit of duplication.

2022-02-03 13:47 UTC, ematipico commented on crates/rslint_parser/src/syntax/function.rs
> +pub(crate) enum ParameterContext {
Yeah, we should draw a line for when using a new union. Honestly I don't know 😅 
It surely allows us to handle different cases nicely, but if leads to much duplication, maybe it's not worth it

2022-02-04 08:32 UTC, MichaReiser commented
I explored a few options but decided to not split the arrow and function parameters.

* Option a) Add `this parameter` as a field to `JsFunctionParameters`. The main issue is that the generated code of the `SyntaxFactory` is no longer able to verify if a node has the right amount of commas or elements. For example for `function a(this: string a)` where the comma between `string` and `a` is missing. 
* Option b): Having separate `Parameters`, `ParametersList`, and `AnyParameter` types for `functions`/methods, arrow functions, and constructors. The main issue I faced was that it would then be desired to have a `JsAnyParameters` union type but arrow functions are the weird ones when it comes to functions because they support a single parameter and we don't yet have a way to construct an `AstSeparatedList` containing a single element (without a backing syntax list).
 
That's why I would leave it as is for now. It comes at the cost that a transformer or refactor may convert a function expression to an arrow function without noticing the `TsThisParameter` which is something that was also possible in rome classic.

2022-02-04 08:38 UTC, ematipico approved these changes

2022-02-04 10:21 UTC, merged