chore(website): core contributors to alumni
rome/tools pull request #2074
Opened 2022-02-08 13:34 UTC by ematipico

## Summary

This PR introduces the definition of `Alumni` to suggest past core contributors on the website.

This is a change we already done on the Discord server.

I also removed the link to the governance, which we don't have anymore for the time being.

## Test Plan

Current CI

2022-02-08 14:20 UTC, yassere commented on website/src/credits.md
> +## Alumni (past core contributors)
This section still contains active members of staff, so this feels a bit odd. At some point, we'll need to come up with a new governance document that clarifies the relationship between core contributors and staff. But for now, maybe we could create a new "Staff" section with all active employees and then have an "Alumni" section (without the qualifier) that would include past core contributors and any former employees.

2022-02-08 14:25 UTC, ematipico commented on website/src/credits.md
> +## Alumni (past core contributors)
So is it a suggestion that we can do later or is it a change you want to apply to this PR?

2022-02-08 14:40 UTC, yassere commented on website/src/credits.md
> +## Alumni (past core contributors)
It's a suggestion for this PR so that we don't leave active staff under the Alumni section. And it's also nice to credit our new staff who weren't previously core contributors.

2022-02-09 09:19 UTC, ematipico commented
@rome/staff please review your section and make sure that your same is correctly spelled. If not, feel free to commit a suggestion

2022-02-09 09:20 UTC, MichaReiser commented on website/src/credits.md
> +	</li>
I believe you mixed up the names/images here

2022-02-09 09:35 UTC, ematipico commented on website/src/credits.md
> +	</li>
that's what happens when I copy+paste 😆

2022-02-09 09:36 UTC, ematipico commented
FYI, the names are in alphabetic order, using the name of the person

2022-02-09 12:36 UTC, MichaReiser commented
Looks good to me. Let's wait with merging until everyone had a look or by tomorrow morning (should have been enough time for everyone to have a look).

2022-02-09 12:36 UTC, MichaReiser approved these changes

2022-02-09 15:44 UTC, yassere requested changes
Left some comments about images not showing up. Let's also remove me, you, and Sebastian from the "Alumni" section.

2022-02-09 15:44 UTC, yassere commented on website/src/credits.md
> +			<img src="https://github.com/xunilrj?s=176">
This is missing the `.png` extension so the image doesn't show up.

2022-02-09 15:44 UTC, yassere commented on website/src/credits.md
> +			<img src="https://github.com/leops?s=176">
Missing `.png` extension.

2022-02-09 15:44 UTC, yassere commented on website/src/credits.md
> +			<img src="https://github.com/NicholasLYang?s=176">
Missing `.png` extension.

2022-02-09 16:18 UTC, yassere approved these changes

2022-02-10 15:26 UTC, merged