index member for classes
rome/tools pull request #2133
Opened 2022-02-17 15:54 UTC by xunilrj

2022-02-17 16:08 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/types.rs
>          return Absent;
This will throw if the Marker is `Some`. I suggest to change the method to always accept a `Marker` and return `CompletedMarker`. Doing so delegates the responsibility for checking if the parser is indeed at an index signature to the caller (I sometimes called this methods `expect_ts_index_signature_type`)

2022-02-17 16:08 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/ok/ts_indexer_signature.rast
> +                TsIndexSignatureTypeMember {
Classes and type members so far didn't share any of the members. I'm somewhat undecided if this is good. The benefit of disjoint members is that a caller knows when something is a class member without probing the parent. However, it obviously leads to many similar nodes. 

What was your reasoning?

2022-02-17 16:51 UTC, xunilrj commented on crates/rome_formatter/src/js/any/class_member.rs
> +            Self::TsIndexSignatureTypeMember(_) => todo!(),
Done.

2022-02-19 13:50 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/types.rs
>          return Absent;
Done.

2022-02-19 15:23 UTC, xunilrj commented on crates/rslint_parser/test_data/inline/ok/ts_indexer_signature.rast
> +                TsIndexSignatureTypeMember {
I am going with specific members per context: Type, Class etc...
My reasoning here is that, if we find out this is overwhelming, we can come up with solutions; and in the worst-case scenario we can merge some in common nodes later, and the compiler will help us. 

The other way is less safe. We may end up with consumers "forgetting" about a node.

2022-02-21 08:56 UTC, MichaReiser requested changes
```
conformance/classes/indexMemberDeclarations/privateIndexer.ts
conformance/classes/indexMemberDeclarations/publicIndexer.ts
```

Can we add a check to disallow accessiblity modifiers for index accessors?

2022-02-21 08:56 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	'readonly'?
It seems that index accessors can be static too

```
staticIndexSignature2
```

2022-02-21 08:56 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/class.rs
> +        // }
The tests for `interface`s seem out of place. This logic is related to class parsing.

2022-02-21 08:56 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
> +pub(crate) fn is_at_ts_index_signature_member(p: &Parser) -> bool {
There can be more modifiers. Ideally, we would eat away all class modifiers and then see if what comes next is a valid index signature. This should simplify the logic here a bit and also provide better error recovery if someone uses an invalid modifier.

2022-02-21 08:56 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
> +}
Nit: Using `bitflags` here makes the code harder to understand than it must be. There are really only two situations

* `Comma` (for classes)
* `CommaOrSemicolon` 

Or you can even pass more information to the implementation so that it can decide itself to do the right thing by telling it what the parent is

```
enum IndexSignatureContext {
  Class,
  Type,
  Interface,
}
```

The enum could then even implement `expect_separator()`, `Into<JsSyntaxKind>`, ..

2022-02-21 08:56 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript/types.rs
> +        return Present(expect_ts_index_signature_member(
The error messages for semicolons now differs between index signatures and any other member.

2022-02-21 08:56 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
> +        if qty > 1 {
What does `qty` stand for?

2022-02-21 08:56 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/typescript.rs
> +            }
Nit: Would be nice if it's possible to `match`

2022-02-21 17:58 UTC, xunilrj commented on xtask/codegen/js.ungram
> +	'readonly'?
Only for classes; not for interfaces and types.
Done.

2022-02-21 17:58 UTC, xunilrj commented on crates/rslint_parser/src/syntax/class.rs
> +        // }
Done.

2022-02-21 18:38 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript.rs
> +pub(crate) fn is_at_ts_index_signature_member(p: &Parser) -> bool {
The strange part now is that class members "eat" their modifiers outside of this method. "interfaces" and "types" eat them here.
We can try to unify this later.

2022-02-21 19:30 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript.rs
> +}
I think it is better now.

2022-02-21 19:31 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript/types.rs
> +        return Present(expect_ts_index_signature_member(
Done.

2022-02-21 19:32 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript.rs
> +            }
Done.

2022-02-21 19:32 UTC, xunilrj commented on crates/rslint_parser/src/syntax/typescript.rs
> +        if qty > 1 {
I removed.

2022-02-21 19:32 UTC, xunilrj commented
!bench_parser

2022-02-21 21:25 UTC, xunilrj commented
> ```
> conformance/classes/indexMemberDeclarations/privateIndexer.ts
> conformance/classes/indexMemberDeclarations/publicIndexer.ts
> ```
> 
> Can we add a check to disallow accessiblity modifiers for index accessors?

Done.

2022-02-22 08:47 UTC, MichaReiser approved these changes

2022-02-22 08:47 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/index_signature_class_member_in_js.rast
> +                JsUnknown {
Have you added the mapping for `IndexSignatureMember` to `JsUnknownMember` in `JsSyntaxKind.to_unknown_member`?

2022-02-22 09:32 UTC, xunilrj commented on crates/rslint_parser/test_data/inline/err/index_signature_class_member_in_js.rast
> +                JsUnknown {
Done.
Also put ```UNKOWN_MEMBER```as valid interface member.

2022-02-22 09:45 UTC, merged