feat(rome_formatter): implement suppression comments and improve the formatting of verbatim nodes
rome/tools pull request #2164
Opened 2022-02-23 16:57 UTC by leops

## Summary

This PR introduces two complementary changes. The first one is a revision of how whitespace and newlines are printed around verbatim nodes: as the formatter already inserts line breaks and empty lines between statements based on the trivias attached to the nodes, verbatim nodes are now printed with their first leading and last trailing trivias trimmed up to the first comment or token. This brings the printing behavior of verbatim trivias in line with how trivia pieces are printed for non-verbatim nodes. This also means the use of `trim_start` and `trim_end` in `format_list` has become redundant, and since this was the only usage of these functions and their implementation added an additional cost to the maintenance and evolution of `FormatElement` I opted to remove them.

The second revision is the implementation of suppression comments in the formatter, using the same syntax found in Rome Classic (`// rome-ignore formatter: reason`). The parsing of this comments is currently implemented only for the formatter but it should be possible to move this utility to a common crate for it to be reused in other parts of the project. One limitation that's imposed by the current implementation of the suppression detection code is that these comments must be on a separate line (specifically be a leading trivia for the node they want to suppress formatting on), this is to limit the overhead of the detection and make reasoning about the formatting of these nodes easier but we may be able to lift that limitation in the future. As part of this I also removed the `format_node_start` and `format_node_end` placeholders as there doesn't seems to be any use for them at the moment (trivias and sourcemaps are all handled at the token level) and the cost of adding them back if needed should be minimal.

2022-02-23 16:57 UTC, leops commented
!bench_formatter

2022-02-23 17:19 UTC, MichaReiser commented
> This PR introduces two complementary changes. The first one is a revision of how whitespace and newlines are printed around verbatim nodes: as the formatter already inserts line breaks and empty lines between statements based on the trivias attached to the nodes, verbatim nodes are now printed with their first leading and last trailing trivias trimmed up to the first comment or token. This brings the printing behavior of verbatim trivias in line with how trivia pieces are printed for non-verbatim nodes. This also means the use of trim_start and trim_end in format_list has become redundant, and since this was the only usage of these functions and their implementation added an additional cost to the maintenance and evolution of FormatElement I opted to remove them.

I love it! Nice work.

2022-02-23 17:35 UTC, MichaReiser approved these changes

2022-02-23 17:35 UTC, MichaReiser commented on crates/rome_formatter/src/formatter.rs
> +            piece.as_newline().is_some() || piece.as_whitespace().is_some()
Nit: Would it make sense to add a `piece.is_whitespace()` method? Seems to be a concept that may be useful in other sue cases too.

2022-02-23 17:35 UTC, MichaReiser commented on crates/rome_formatter/src/utils/mod.rs
> +        _ => panic!(),
Nit: maybe some nice message what's happening here?

2022-02-23 17:35 UTC, MichaReiser commented on crates/rome_formatter/src/utils/mod.rs
> +        JsSyntaxKind::JS_MODULE | JsSyntaxKind::JS_SCRIPT => return false,
You want to add `JS_EXPRESSION_SNIPPED` to. Ideally, you can use `JsAnyRoot::can_cast(node.kind())`

2022-02-23 19:06 UTC, ematipico requested changes

2022-02-23 19:06 UTC, ematipico commented on crates/rome_formatter/src/utils/mod.rs
> +                    if category == "format" {
We could have this `"format"` inside a `const`

2022-02-23 19:06 UTC, ematipico commented on crates/rome_formatter/src/utils/mod.rs
> +				  */"
1. This file seems to have tabs
2. Should we test against multiple categories? e.g. `// rome-ignore lint format: explanation`

2022-02-23 19:07 UTC, ematipico commented on crates/rome_formatter/src/utils/mod.rs
> +        }
I mean, it's a nice thing that you thought about! I haven't honestly.

2022-02-24 07:01 UTC, MichaReiser commented on crates/rome_formatter/src/utils/mod.rs
> +        }
I also spent some more time thinking about this and agree. There might not even be reason to keep them because the main reason I added them in the past was when prettier screwed up and e.g. dropped some tokens.

2022-02-24 08:51 UTC, leops commented on crates/rome_formatter/src/utils/mod.rs
> +        _ => panic!(),
This was actually supposed to be `unreachable!()` instead of `panic!()` but I forgot to change when cleaning up the parsing code. The reasoning behind this is simply that its not currently possible for a comment to not start with `/*` or `//`

2022-02-24 09:10 UTC, leops commented on crates/rome_formatter/src/utils/mod.rs
> +        }
Honestly I implemented this bit mostly to be able to process the prettier tests for ignore comments without modifying them, and was considering adding `cfg!(test) &&` to the condition.

In my own experience I mostly used prettier-ignore comments when I want a node formatted in a specific way (the matrix I added in the test cases is real code), so from that perspective it makes sense to preserve those comments. One thing I had in mind for the migration would have been to check that the output of the formatter with and without the suppression is actually different, and drop the comment (with a warning) if it isn't

2022-02-24 09:19 UTC, leops commented on crates/rome_formatter/src/utils/mod.rs
> +				  */"
Ah yes these are test cases I ported straight over from Rome Classic, since these are string literals the tabs remained. The `parse_multiple_suppression` test does have categories but not without values, all add an additional test for that

2022-02-24 11:07 UTC, leops commented on crates/rome_formatter/src/utils/mod.rs
> +    categories: Vec<(&'a str, Option<&'a str>)>,
There definitely should be some amount of validation around these comments, not only should it emit a diagnostic for categories or values that don't make sense but I think it would also make sense for these to behave like `@ts-expect-error` by default and warn if they are not actually suppressing anything (formatter suppression where the output would be the same without the comment, or lint suppression where the associated lint isn't raising any diagnostic for the associated node). However for now I'm not really sure where these diagnostics would be emitted (at least it seems awkward for the formatter to emit diagnostics) nor what the actual category and values will end up being hence why I'm currently parsing everything as strings instead of narrower enums

2022-02-24 11:16 UTC, ematipico commented on crates/rome_formatter/src/utils/mod.rs
> +    categories: Vec<(&'a str, Option<&'a str>)>,
All right then, surely this will have a second iteration!

2022-02-24 13:57 UTC, leops commented on crates/rome_formatter/src/utils/mod.rs
> +        }
I ended up removing the `prettier-ignore` case for now and implemented the replacement logic in the prettier test suite instead which seems to work well enough (except for `js/ignore/ignore-2.js` but that's because JSX is confusing the parser and the comment ends up being parsed as a regexp instead)

2022-02-28 14:16 UTC, ematipico approved these changes

2022-02-28 15:03 UTC, merged