Adding playground to tools repo
rome/tools pull request #2215
Opened 2022-03-08 19:40 UTC by NicholasLYang

## Summary

## Test Plan

2022-03-09 08:09 UTC, xunilrj commented on Cargo.toml
> +	"playground",
Any reason to not have this inside crates?

2022-03-09 08:09 UTC, xunilrj commented on playground/Cargo.toml
> +name = "rome-playground"
Maybe we could match folder and package name?

2022-03-09 09:52 UTC, ematipico requested changes
Overall it looks good to me. One important thing that I would do before merging it, would be to move the playground crate inside the `crates/` directory and change its version to `0.0.0`

2022-03-09 09:52 UTC, ematipico commented on playground/package.json
> +    "@types/prettier": "^2.4.3",
This should be a dev dependency

2022-03-09 09:52 UTC, ematipico commented on playground/package.json
> +    "tailwindcss": "^3.0.19",
Isn't `tailwindcss` supposed to be a direct dependency? 🤔 If yes, it should be moved. If not, then also `@tailwindcss/forms` should be a dev dependency

2022-03-09 09:52 UTC, ematipico commented on playground/src/lib.rs
> +    indent_width: u8,
This should be an `Option<u8>`.  If we choose tabs, we aren't supposed to have this value

2022-03-09 09:52 UTC, ematipico commented on playground/src/LineWidthInput.tsx
> +          htmlFor="number"
This should be `lineWidth`

2022-03-09 09:52 UTC, ematipico commented on playground/src/IndentStyleSelect.tsx
> +        <label className="block text-sm font-medium text-gray-700">
`htmlFor` is missing

2022-03-09 09:52 UTC, ematipico commented on playground/src/IndentStyleSelect.tsx
> +          id="location"
`name` is missing

2022-03-09 09:52 UTC, ematipico commented on playground/src/LineWidthInput.tsx
> +      </button>
Let's have an aria label on these buttons. Having just numbers on these buttons doesn't help to understand what they do

2022-03-09 09:52 UTC, ematipico commented on Cargo.toml
> +	"playground",
I agree too, I think we should move the this crate under the folder `crates/`

2022-03-09 09:52 UTC, ematipico commented on playground/Cargo.toml
> +version = "0.1.0"
As internal standard, crates that are not published should have `0.0.0` as version

2022-03-09 09:52 UTC, ematipico commented on playground/src/App.css
> +  min-height: 100vh;
Why is the header so high?

2022-03-09 09:52 UTC, ematipico commented on playground/src/App.css
> +  font-size: calc(10px + 2vmin);
We should really use `rem` for font-size

2022-03-09 09:52 UTC, ematipico commented on playground/src/App.css
> +  font-size: calc(10px + 2vmin);
Let's use `rem`

2022-03-09 17:41 UTC, NicholasLYang commented on playground/package.json
> +    "@types/prettier": "^2.4.3",
Let's remove this entirely. Gonna try to use Rome now

2022-03-09 18:25 UTC, NicholasLYang commented
Ahh, we might have to cancel this PR because we can't have multiple sites on a single repo for Cloudflare Pages

2022-03-09 18:36 UTC, ematipico commented
> Ahh, we might have to cancel this PR because we can't have multiple sites on a single repo for Cloudflare Pages

We can still have the playground web app in a different folder (not `website/`) and do a ad-hod deployment

2022-03-09 18:51 UTC, NicholasLYang commented
Yeah I think I have a solution. We can just use an action to manually publish to a Cloudflare Worker site. Not too hard.

2022-03-10 09:11 UTC, ematipico commented
Could you please update the template of the PR and add some description of that we're trying to achieve? It seems that we are now doing more than just adding the playground to the main repository.
Also, could you please link this PR to the relative umbrella issue?

One question: is there a reason why the web app and the crate are together? Can they be separated?

2022-03-15 14:20 UTC, NicholasLYang commented
@ematipico the crate and the web app are connected because the crate is just a tiny wrapper around a few Rome APIs. It's really not worth separating in my opinion. We gain more by colocating it with the web app code than we do by having it separate. We could put the JS in a different folder from the Rust within the same crate I suppose

2022-03-15 17:31 UTC, ematipico approved these changes
Let's merge it and give it a shot! :)

2022-03-15 20:47 UTC, merged