Fixed minor logic bug with formatting with errors setting
rome/tools pull request #2216
Opened 2022-03-08 20:02 UTC by NicholasLYang

## Summary

## Test Plan

2022-03-08 20:22 UTC, yassere commented
Looks like there's a similar mistake in the `format_range` and `format_on_type` functions too.

2022-03-08 20:40 UTC, yassere requested changes

2022-03-08 20:40 UTC, yassere commented on crates/rome_lsp/src/handlers/formatting.rs
> +        && !parse_result.has_errors()
This would mean we return early if "format_with_syntax_errors" is enabled but there aren't any syntax errors. I assume we only want to bail for the same condition you changed the `format` handler to:
`!workspace_settings.formatter.format_with_syntax_errors && parse_result.has_errors()`

2022-03-08 20:40 UTC, yassere commented on crates/rome_lsp/src/handlers/formatting.rs
> +        && !parse_result.has_errors()
Same here. I don't think the condition here should be any different than what you changed the `format` handler to.

2022-03-09 08:22 UTC, ematipico approved these changes

2022-03-09 09:29 UTC, ematipico approved these changes

2022-03-09 09:29 UTC, merged