Feature/jsx simple attributes
rome/tools pull request #2224
Opened 2022-03-11 14:37 UTC by xunilrj

Support for simple attributes

```jsx
function f() {
    let a = <div id="a" name="b" checked></div>;
    return <div id="a" name="b" checked/>;
}
```

2022-03-14 16:45 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +}
I would expect that any `expect_` method would add an error if the node isn't present. 

Why not call this `parse_` and return `Absent` if they're missing. For example, the initializer is optional.

2022-03-14 16:45 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    p.bump(JsSyntaxKind::IDENT);
Nit: The majority of the code uses `T![ident]` for tokens and the `JsSyntaxKind::*` names only for nodes.

2022-03-14 16:45 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +        let jsx = Jsx.parse_exclusive_syntax(p, maybe_parse_jsx_expression, |p, assertion| {
Is it safe to parse out `JSX` even if `JSX` is disabled?

2022-03-14 16:45 UTC, MichaReiser commented on crates/rome_formatter/tests/specs/prettier/js/ternaries/nested.js.snap
> +<<<<<<< HEAD
You have a merge issue here.

2022-03-14 20:40 UTC, xunilrj commented on crates/rome_formatter/tests/specs/prettier/js/ternaries/nested.js.snap
> +<<<<<<< HEAD
Ah sorry. You were faster than me.

2022-03-14 20:41 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +}
that is what I am doing now.

2022-03-15 07:47 UTC, MichaReiser requested changes
The parsing now abandons nodes even if outside of a `CheckpointedParser`. This isn't valid. I think we have to rewrite the speculative parsing mode similar to what we do with parenthesized functions.

2022-03-15 07:47 UTC, MichaReiser commented on crates/rome_js_syntax/src/generated/kind.rs
>      JSX_ELEMENT_EXPRESSION,
Please add the `JSX_ELEMENT_EXPRESSION` to `JS_UNKNOWN_EXPRESSION` in `SyntaxKind.to_unknown`

2022-03-15 07:47 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +fn parse_jsx_element(p: &mut Parser) -> ParsedSyntax {
Does it still make sense to have the `CheckpointParser` abstraction as it's no longer used here (which was the main use case)? 

Please add some documentation to this method when it's safe to call it and when not. I think it would make sense to do something as in `try_parse_arrow_function_head` where the signature makes it clear that parsing might fail and that it's the responsiblity of the caller to abandon the marker in that case. 

https://github.com/rome/tools/blob/dc0ef1ef9e38e929f8ac64c31fe3af9ea46e01a8/crates/rslint_parser/src/syntax/function.rs#L445-L500

2022-03-15 07:47 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    if name.is_absent() {
Abandoning here isn't safe if you call in from `expect_jsx_attribute_value`. I believe you need to rewrite all these functions to have a `try_parse` version and a normal version.

2022-03-15 07:47 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +                token_set![T![/], T![>], T![<], T!['{'], T!['}'],],
You probably want to recover on identifiers too, because they mark the start of a  new attribute

2022-03-15 07:47 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +fn expect_jsx_attribute_initializer_clause(p: &mut Parser) -> ParsedSyntax {
`expect` methods on the parser generate a diagnostic if the parser isn't at that position and return a bool. However, this method panics if the parser is positioned anywhere but an initializer. Also, returning `ParsedSyntax` only makes sense if the parser may not be at that given position, which can never happen here. 

That's why I would change this method to `parse_jsx_attribute_initializer_clause` and add the `if !p.at(T![=]) { return Absent }` at a check. You can then remove the `p.at(T![=])` check in the attribute parsing.

2022-03-15 07:47 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +fn expect_jsx_attribute_value(p: &mut Parser) -> ParsedSyntax {
Rename to `parse_jsx_attribute_value`.

2022-03-15 07:47 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    let _ = expect_jsx_attribute_value(p);
You need to add a diagnsotic if the attribute value is missing after the `=` or is `<abcd a= />` valid?

2022-03-15 18:51 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    p.bump(JsSyntaxKind::IDENT);
Done.

2022-03-15 20:00 UTC, xunilrj commented on crates/rome_js_syntax/src/generated/kind.rs
>      JSX_ELEMENT_EXPRESSION,
Done.

2022-03-16 07:25 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/expr.rs
> +        let jsx = Jsx.parse_exclusive_syntax(p, maybe_parse_jsx_expression, |p, assertion| {
I just checked how this is implemented in TS and see the following issues

* JSX expressions are part of the primary expression rule and not of the unary expression rule. Thus, they shouldn't be parsed out here or we risk incorrect precedence handling (Typescript implements it as part of [`parseUpdateExpression`](https://github.com/microsoft/TypeScript/blob/4013271cd84f2766c0e8aaa813e719fc4a355ec8/src/compiler/parser.ts#L4900-L4903)
* `<test> <b>a</b>` would parse as a valid TS type assertion if we support parsing out type assertions and JSX at the same time because `<type>` would parse as the type and `<b>a</b>`. Yes, we would emit an error that one of them isn't allowed but the error message should really be that `<test>` has no corresponding close tag.
* Overall, our error recovery isn't good and this is mainly due to the fact that we do speculative JSX parsing where it isn't needed. We know that anything starting with a `<a` in a primary expression context should be parsed as a JSX expression and we should provide the best possible error recovery.
* I don't think we should even parse out JSX in JS only mode or we risk parsing `a<b>c` as invalid syntax tough it's perfectly valid  (we probably shouldn't parse out type assertions for the very same reason)

2022-03-16 09:08 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    let _ = expect_jsx_attribute_value(p);
Yeah. I plan to deal with diagnostics in another PR.

2022-03-16 09:10 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    let _ = expect_jsx_attribute_value(p);
I think it would make sense to do it now for this case. Because you're intentionally suppressing the compiler warning about the `must_use` of the `ParsedSyntax` which isn't correct here.

2022-03-16 09:10 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +                token_set![T![/], T![>], T![<], T!['{'], T!['}'],],
Done.

2022-03-16 09:25 UTC, MichaReiser commented on xtask/codegen/src/kinds_src.rs
> +        "JSX_ANY_ATTRIBUTE_VALUE",
You don't need to add kinds for any nodes because these are just unions and not any real "nodes". Same for `JsxAnyAttributeName`

2022-03-16 11:12 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +        let _ = super::expr::parse_expression(p, ExpressionContext::default());
this should call into `parse_assignment_expression_or_higher` according to the [spec](https://facebook.github.io/jsx/#prod-JSXAttributeValue)

The following isn't allowed: `a={test, more}` maybe worth adding a test

2022-03-16 11:18 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +        let _ = super::expr::parse_expression(p, ExpressionContext::default());
Yeah. I prefer parsing the whole expression and emitting an error.

2022-03-16 11:20 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +fn expect_jsx_attribute_value(p: &mut Parser) -> ParsedSyntax {
Done.

2022-03-16 11:21 UTC, xunilrj commented on xtask/codegen/src/kinds_src.rs
> +        "JSX_ANY_ATTRIBUTE_VALUE",
Done.

2022-03-16 11:21 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +fn expect_jsx_attribute_initializer_clause(p: &mut Parser) -> ParsedSyntax {
done.

2022-03-16 11:26 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +fn parse_jsx_element(p: &mut Parser) -> ParsedSyntax {
I will address this in another PR. See https://github.com/rome/tools/issues/2153.

2022-03-16 11:26 UTC, xunilrj commented on crates/rslint_parser/src/syntax/expr.rs
> +        let jsx = Jsx.parse_exclusive_syntax(p, maybe_parse_jsx_expression, |p, assertion| {
I will address this in another PR. See https://github.com/rome/tools/issues/2153

2022-03-16 11:26 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    if name.is_absent() {
Done.

2022-03-16 11:27 UTC, xunilrj commented
> The parsing now abandons nodes even if outside of a `CheckpointedParser`. This isn't valid. I think we have to rewrite the speculative parsing mode similar to what we do with parenthesized functions.

THis will be addressed in another PR. See https://github.com/rome/tools/issues/2153.

2022-03-16 12:16 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    dbg!(&name);
Please delete the `dbg` here

2022-03-16 12:16 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    if name.is_absent() {
Not really done, but will be dealt as part of another PR.

2022-03-16 12:16 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +            dbg!(parse_jsx_name(p)).or_add_diagnostic(p, expected_identifier);
Remove `dbg`

2022-03-16 12:16 UTC, MichaReiser commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    let _ = parse_jsx_attribute_value(p);
Please add a TODO here to add a diagnostic if it is missing or add it now.

2022-03-16 12:16 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/err/jsx_namespace_member_element_name.jsx
> +<dashed-namespace:a.b></dashed-namespace:a.b>
You need to add semicolons at the end of every statement or it will parse this as binary expressions
```suggestion
<namespace:a></namespace:a>;
<namespace:a.b></namespace:a.b>;
<dashed-namespace:a.b></dashed-namespace:a.b>;
```

2022-03-16 12:16 UTC, MichaReiser commented on crates/rslint_parser/test_data/inline/ok/jsx_any_name.jsx
> -<dashed-namespaced:dashed-name />;
Why did you remove this test case?

2022-03-16 12:34 UTC, xunilrj commented on crates/rslint_parser/test_data/inline/err/jsx_namespace_member_element_name.jsx
> +<dashed-namespace:a.b></dashed-namespace:a.b>
Done.

2022-03-16 12:35 UTC, xunilrj commented on crates/rslint_parser/test_data/inline/ok/jsx_any_name.jsx
> -<dashed-namespaced:dashed-name />;
I got confused and thought we could not have dashed namespaces here.... but the problem is different.
Done.

2022-03-16 12:38 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +    let _ = parse_jsx_attribute_value(p);
Done.

2022-03-16 12:39 UTC, xunilrj commented on crates/rslint_parser/src/syntax/jsx/mod.rs
> +            dbg!(parse_jsx_name(p)).or_add_diagnostic(p, expected_identifier);
Done.

2022-03-16 12:42 UTC, MichaReiser approved these changes

2022-03-16 13:09 UTC, merged