feature(playground): Deploy every commit to subdomain
rome/tools pull request #2357
Opened 2022-04-05 20:18 UTC by NicholasLYang

## Summary

It can be annoying to play around with people's changes to the formatter. By deploying on every commit and storing in a subdomain, we can try out people's changes to the formatter in the playground.

The only issue I could see is that too many commits can clog up the actions pipeline.

## Test Plan

2022-04-06 09:32 UTC, ematipico requested changes
There's something important missing in the workflow.

Few questions:
- if there are two commits, does the new deploy override previous one?
- when do we delete old deploys? what's the policy around it? As we're using AWS, it's up to us to clear the bucket from old files

2022-04-06 09:32 UTC, ematipico commented on .github/workflows/deploy_playground.yml
>    push:
I would add 

```yml
    paths:
      - 'crates/rome_playground'
```

2022-04-06 09:53 UTC, leops commented
Would it be possible to use the same deployment process as the website ? In particular I think having auto-generated deploys of the playground for each pull request would be a great tool to help us trying out the changes to the parser or formatter

2022-04-06 14:43 UTC, NicholasLYang commented on .github/workflows/deploy_playground.yml
> +      - run: npm run build --prefix crates/rome_playground -- --base=/$GITHUB_SHA/
When we build, we assume that the js files will be hosted off of a subdomain that is the commit hash, i.e. play.rome.tools/e2bd79ed0e66acb2049436837ee6e4c6594ec549/index.html

2022-04-06 14:45 UTC, ematipico commented
> Would it be possible to use the same deployment process as the website ? In particular I think having auto-generated deploys of the playground for each pull request would be a great tool to help us trying out the changes to the parser or formatter

This is already in place. Every time you open a PR, there's a cloudflare hook that adds a comment to the PR with a URL to the built website: 
![Screenshot 2022-04-06 at 15 45 42](https://user-images.githubusercontent.com/602478/162001911-a43a5bb7-c012-4838-a10d-dc9e3631e0d9.png)

2022-04-06 14:46 UTC, NicholasLYang commented
@leops Unfortunately Cloudflare Pages doesn't allow multiple sites in the same repository. This is effectively mimicking CF Pages by building on every commit

2022-04-06 14:47 UTC, NicholasLYang commented
If we kept the playground as a separate repo, we could just use pages. We could try having everything built at once I suppose, website and playground, but we'd need to embed the playground in the website.

2022-04-06 14:48 UTC, ematipico commented
> @leops Unfortunately Cloudflare Pages doesn't allow multiple sites in the same repository. This is effectively mimicking CF Pages by building on every commit

That's because we assume we have a different domain for the playground. What about a `/playground` directory where we copy over the built playground? Once we have that, we just need to update the the npm commands on cloudflare

2022-04-06 16:15 UTC, NicholasLYang commented
@ematipico  Just spent some time trying to set this up. I remembered that Cloudflare Pages doesn't support wasm-pack. Before when I was using pages with the playground, I had to manually run wasm-pack on my local machine. This might be our best option for now, until pages adds wasm-pack

2022-04-06 16:38 UTC, ematipico commented on .github/workflows/deploy_playground.yml
> +      - run: npm run build --prefix crates/rome_playground -- --base=/$GITHUB_SHA/
Who's the consumer of `base`? I can't understand

2022-04-06 16:39 UTC, ematipico commented
Do you plan to print a git comment later? Because as it is now, it's really hard to understand what's the published url

2022-04-06 16:45 UTC, NicholasLYang commented
yeah I was thinking of making a bot

2022-04-06 18:07 UTC, ematipico commented
> yeah I was thinking of making a bot

There's no need. We already have a bunch of actions and publish and update the comments. We just to copy it and personalise the message. I wanted to know when do you plan to do that: this PR or another one

2022-04-07 12:28 UTC, ematipico commented on .github/workflows/deploy_playground.yml
>    push:
Sorry, I am not sure I follow. How does my suggestion prevent that?

2022-04-07 12:31 UTC, ematipico commented
> @ematipico Just spent some time trying to set this up. I remembered that Cloudflare Pages doesn't support wasm-pack. Before when I was using pages with the playground, I had to manually run wasm-pack on my local machine. This might be our best option for now, until pages adds wasm-pack

Just leaving a suggestion. Another way might be to track in the repository the built wasm file. So we have to build it ourselves and commit the changes.

2022-04-07 15:55 UTC, NicholasLYang commented on .github/workflows/deploy_playground.yml
> +      - run: npm run build --prefix crates/rome_playground -- --base=/$GITHUB_SHA/
`vite`. The flag is telling vite to write all the urls with the offset of the commit hash

2022-04-07 15:56 UTC, NicholasLYang commented
@ematipico  That's what I did before. It's not really ideal because it's very easy to forget. We could have a git hook installed but people would need to add it manually to their local setups.

2022-04-08 08:49 UTC, ematipico approved these changes

2022-04-08 16:00 UTC, merged