feature(rome_js_formatter): Add support for printing single quotes
rome/tools pull request #2380
Opened 2022-04-09 13:30 UTC by cpojer

## Summary
This PR adds a `--quote-style` option to the Rome Formatter so that users can choose between single and double quotes. Arguably, template literals should also be an available option, but that can be discussed later.

## Test Plan

* `cargo test`
* I have no idea what I'm doing, or how to test every flow to ensure it is working.

2022-04-09 13:31 UTC, cpojer commented on crates/rome_js_formatter/src/utils/mod.rs
> +            }
How do I make this look nice?

2022-04-09 13:32 UTC, cpojer commented on crates/rome_js_formatter/tests/specs/js/module/string/string.js.snap
> +	"type": "js",
Any idea why only the first two strings are reprinted with single-quotes in asserts?

2022-04-09 13:33 UTC, cpojer commented on crates/rome_js_formatter/tests/specs/js/module/array/array_nested.js.snap
> -
I don't know what I did to trigger this removal across all files.

2022-04-09 14:11 UTC, Boshen commented on crates/rome_js_formatter/tests/specs/js/module/array/array_nested.js.snap
> -
You have the latest insta, which removed this line, no worries. https://github.com/mitsuhiko/insta/commit/5ab9f4093f6d62d8889918a8a84c99b386f1c816

2022-04-09 23:49 UTC, kassens commented on crates/rome_js_formatter/src/utils/mod.rs
> +            }
👋 was just taking a look at Rome and surprise do see you around.

start with this, then use the them in the code to avoid the duplication.
```
let (primary_quote_char, secondary_quote_char) = match quote_style {
  Style::Double => ('"', '\''),
  Style::Single => ('\'', '"'),
};
```

2022-04-10 00:16 UTC, cpojer commented on crates/rome_js_formatter/src/utils/mod.rs
> +            }
Nice to see you here ❤️ Thanks, nice destructuring syntax. I cleaned it up.

2022-04-10 18:30 UTC, ematipico requested changes
That's a great contribution! I would be great to add new test cases to make sure we propertly test the "single quote" case. Please follow this guide to how to add new tests: https://github.com/rome/tools/blob/main/crates/rome_js_formatter/docs/write_tests.md

2022-04-10 18:30 UTC, ematipico commented on website/playground/src/lib.rs
> +        quote_style: QuoteStyle::from_str(&quote_style).unwrap_or_default(),
Here we can use use `quote_style.try_into()` like we do on line 115

2022-04-10 18:30 UTC, ematipico commented on crates/rome_cli/src/commands/format.rs
> +        .opt_value_from_str("--quote-style")
The help message of the command should be updated with the new option

2022-04-10 18:30 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/js/module/string/string.js.snap
> +	"type": "js",
Because this code is not valid. https://play.rome.tools/?lineWidth=80&indentStyle=tab&indentWidth=2&typescript=false&jsx=false&sourceType=module#aQBtAHAAbwByAHQAIABmAG8AbwAyACAAZgByAG8AbQAgACcAZgBvAG8ALgBqAHMAbwBuACcAIABhAHMAcwBlAHIAdAAgAHsACgAJACcAdAB5AHAAZQAnADoAIAAnAGoAcwBvAG4AJwAsAAoACQB0AHkAcABlADoAIAAiAGgAdABtAGwAIgAsAAoACQAiAHQAeQBwAGUAIgA6ACAAIgBqAHMAIgAsAAoACQB9AA==

Check the errors tab. Broken code won't be formatted

2022-04-11 00:59 UTC, cpojer commented on crates/rome_cli/src/commands/format.rs
> +        .opt_value_from_str("--quote-style")
Just added the comment. Would be awesome to auto-generate the help text somehow so this will always be kept in sync.

2022-04-11 01:01 UTC, cpojer commented on website/playground/src/lib.rs
> +        quote_style: QuoteStyle::from_str(&quote_style).unwrap_or_default(),
I didn't implement TryInto for QuoteStyle though, mainly because indentStyle doesn't have it either and I thought this is probably fine. It's only implemented for the u16 → LineWidth conversion.

Let me know if you'd like me to add it, though.

2022-04-11 01:01 UTC, cpojer commented on crates/rome_js_formatter/tests/specs/js/module/string/string.js.snap
> +	"type": "js",
Ohhh I see. Well, glad to know my code works but also time for me to learn the ES assert syntax ;)

2022-04-11 01:02 UTC, cpojer commented
@ematipico thanks for the review! I updated the help text.

Re tests, I added one test (which you commented on) where I copy-pasted some other examples together. Please let me know which other tests you'd like me to add.

2022-04-11 07:29 UTC, MichaReiser commented
> @ematipico thanks for the review! I updated the help text.
> 
> Re tests, I added one test (which you commented on) where I copy-pasted some other examples together. Please let me know which other tests you'd like me to add.
> 
> If you have instructions on how to try out the cli and VSCode extension in development for testing I can test those flows too!

Thanks @cpojer for this amazing contribution! 

You can run the CLI with `cargo run -p rome_cli -- <args>` I defer to @ematipico for how to test the VS code extension.

2022-04-11 07:29 UTC, MichaReiser commented on crates/rome_lsp/src/handlers/formatting.rs
> +    let custom_ident_style =
`custom_quote_style`?

2022-04-11 08:27 UTC, leops commented on crates/rome_cli/src/commands/format.rs
> +    match quote_style {
The `indent_style` had to use a match expression in order to inject the number of spaces into the option, but for this one `if let Some(quote_style) = quote_style { options.quote_style = quote_style; }` should be enough

2022-04-11 08:34 UTC, leops commented on website/playground/src/lib.rs
> +        quote_style: QuoteStyle::from_str(&quote_style).unwrap_or_default(),
Since string-to-type conversion is impemented with the `FromStr` trait instead of the generic `TryFrom`, it can be called as a method using `parse` instead of `try_into`: `quote_style.parse().unwrap_or_default()`

2022-04-11 09:00 UTC, ematipico reviewed
At the moment we don't have tests for VSCode, this is something we still need to set up. For now I think it's fine. 

We need to add this option to the [`package.json`](https://github.com/rome/tools/blob/main/editors/vscode/package.json#L84-L102). The name of the option has to be same that has been added to `rome_lsp/src/config.rs`, in camel case, and it should be an enum like `indentStyle`

2022-04-11 09:01 UTC, cpojer commented on crates/rome_lsp/src/handlers/formatting.rs
> +    let custom_ident_style =
Oops, fixing.

2022-04-11 09:03 UTC, cpojer commented on website/playground/src/lib.rs
> +        quote_style: QuoteStyle::from_str(&quote_style).unwrap_or_default(),
Ah, yay `parse` works!

2022-04-11 09:05 UTC, cpojer commented on crates/rome_js_formatter/tests/specs/js/module/string/string.js
> +import foo2 from "foo.json" assert { "type": "json", type: "html", "type": "js" };
I actually think this is a good test to have though because it will ensure that we don't break this invariant of not formatting strings in broken code.

2022-04-11 09:06 UTC, cpojer commented on crates/rome_lsp/src/handlers/formatting.rs
> +        QuoteStyle::from_str(workspace_settings.quote_style.as_str()).unwrap_or(QuoteStyle::Double);
Ah good point. I changed that for ident style above as well.

2022-04-11 09:18 UTC, cpojer commented
Thanks for all the thorough feedback. I must admit, I haven't written a single line of Rust in more than two years and as you can clearly see I just started writing code on a Saturday night to solve my own problems so I can start adopting the formatter. Really appreciate all the help here, next up is an option for `bracketSpacing`, after which I can finally start using the Rome formatter :)

2022-04-11 11:36 UTC, ematipico approved these changes
I think we're good with this option. We will take care of the documentation of the website

2022-04-11 14:24 UTC, cpojer commented
Added the option to the playground, see screenshot:
<img width="1190" alt="Screen Shot 2022-04-11 at 23 23 48" src="https://user-images.githubusercontent.com/13352/162760710-d9c17464-c183-46c0-aa4b-7623fe6f94f2.png">

2022-04-11 14:26 UTC, cpojer commented on website/playground/src/App.tsx
> +										}
`formatWithPrettier` is called on every render, but the `<CodeEditor>` component does not re-render when options change. You can see this by changing one of the dropdowns and you'll see that the prettier window does not change until the code is changed again. Here I'm just concatenating all the variables to make it look like a poor-mans's `useEffect`.

2022-04-11 14:54 UTC, MichaReiser commented on website/playground/src/App.tsx
> +										}
Nit: Can we exclude `code` because the editor is already updating when the `code` change. This would avoid one full unmount & mount (may be noticeable for large files).

2022-04-11 14:54 UTC, MichaReiser approved these changes

2022-04-11 15:00 UTC, ematipico approved these changes

2022-04-11 15:00 UTC, merged