fix(rome_js_formatter): line break before assignment
rome/tools pull request #2428
Opened 2022-04-13 16:24 UTC by ematipico

## Summary

Fixes #2417

This actually fixes a loads of stuff, although I would to know from @leops if my change actually makes sense.

I know that not having a soft line break as a small repercussion on how comments are printed.

## Test Plan

Updated snapshots and checked if they make sense

2022-04-13 16:49 UTC, MichaReiser reviewed
Would you mind adding a few tests for the cases mentioned in the issues and also testing other edge cases (e.g. all other expressions should begin on a new line)

2022-04-13 16:49 UTC, MichaReiser commented on crates/rome_js_formatter/tests/specs/prettier/js/assignment/binaryish.js.snap
> +computedDescriptionLines = (focused && !loading && descriptionLinesFocused) || descriptionLines;
This doesn't look right

2022-04-14 06:15 UTC, MichaReiser commented on crates/rome_js_formatter/tests/specs/prettier/js/assignment/issue-1966.js.snap
> +this.someObject.someOtherNestedObject = this.someOtherObject.whyNotNestAnotherOne.someLongFunctionName();
The issue here is that member expressions don't implement grouping.

2022-04-14 06:29 UTC, MichaReiser requested changes
While this seems to fix some of the issue, it also introduce many news. I suggest you to create the prettier report on main, then on your branch and then compare the reports to see the regressions. 

Some notable regressions:

* https://gist.github.com/MichaReiser/147a7c787f8cbaaa43c92dd8ceb3060f#jsassignment-commentsnumberjs
* https://gist.github.com/MichaReiser/147a7c787f8cbaaa43c92dd8ceb3060f#jsassignment-commentsstringjs
* https://gist.github.com/MichaReiser/147a7c787f8cbaaa43c92dd8ceb3060f#jsassignmentbinaryishjs
* https://gist.github.com/MichaReiser/147a7c787f8cbaaa43c92dd8ceb3060f#jsassignmentissue-2482-1js
* https://gist.github.com/MichaReiser/147a7c787f8cbaaa43c92dd8ceb3060f#jsassignmentissue-3819js

I believe the main issue is that your condition, testing for `AssignmentExpression` only is too open. You probably must check if the right hand side is a `FunctionExpression`, `ClassExpression`, `ArrayLIteral` or `ObjectLiteral` instead. 

Overall, please add new tests covering these cases. Also tests that verify the logic if either the left hand or right hand sides are very long, and potentially nested.

2022-04-14 06:29 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/expressions/assignment_expression.rs
> +
Nit: You can write this as 
```suggestion
        let right = right?;

        let right = if let JsAnyExpression::JsAnyAssignmentExpression(right)) = right?  {
            soft_line_indent_or_space(right.format(formatter)?)
        } else {
            format_elements![space_token(), right.format(formatter)?]
        };

```

2022-04-14 07:07 UTC, ematipico commented on crates/rome_js_formatter/src/js/expressions/assignment_expression.rs
> +
No I can't because `right` gets moved and can't be inside the `else` branch

2022-04-14 07:08 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/prettier/js/assignment/binaryish.js.snap
> +computedDescriptionLines = (focused && !loading && descriptionLinesFocused) || descriptionLines;
What should we expect instead?

2022-04-14 07:10 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/prettier/js/assignment/issue-1966.js.snap
> +this.someObject.someOtherNestedObject = this.someOtherObject.whyNotNestAnotherOne.someLongFunctionName();
I think this should be fixed in a separate PR because it's not related to assignment expression

2022-04-14 07:14 UTC, ematipico commented
> and potentially nested.

I will try but I would prefer doing it in a different PR because it involves a different logic. It's also tracked in a different PR which make things better.

2022-04-14 07:37 UTC, MichaReiser commented
> > and potentially nested.
> 
> I will try but I would prefer doing it in a different PR because it involves a different logic. It's also tracked in a different PR which make things better.

I think we should at least have tests to see how your PR changes the nesting. Ideally, create the tests first, then make your changes.

2022-04-14 10:07 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/prettier/js/assignment/binaryish.js.snap
> +computedDescriptionLines = (focused && !loading && descriptionLinesFocused) || descriptionLines;
I just double checked. This is correct for the right-hand part of the `JsAssignmentExpression`. The parenthesized expression should de responsible of doing the breaking, which is not covered in this PR

2022-04-14 13:29 UTC, ematipico commented
Closing. I am hitting a limitation of the printer, which requires a different fix.

2022-04-14 13:29 UTC, closed without merging