fix(rome_js_formatter): group and break sequence expressions
rome/tools pull request #2453
Opened 2022-04-14 16:31 UTC by ematipico

## Summary

Fixes #2413

The algorithm is borrowed from the binary like expression with a simple recursion where we flat the chain of sequence expressions. 

We pass the comma token to the next node which will be in charge of formatting it.

## Test Plan

Added new tests that cover short and long expressions.

There's a prettier test that still doesn't look like the original because now the grouping affects subsequent breaking. That is issue is already tracked in another issue, so it's not part of this PR goal.

2022-04-14 19:19 UTC, MichaReiser requested changes
Please add the test cases from the issue and paste the expected output from prettier into the snapshot to ensure Rome produces the exact same formatting as prettier.

2022-04-14 19:19 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/expressions/sequence_expression.rs
> +}
Do we need to go over `FlattenItem` here or can we just create the correct `FormatElement` instead? Because you aren't using the information if the node is a nested sequence expression or not inside of the `into_format_element` function. 

The reason why it would be better to construct the `FormatElement` right away is because this avoids the allocation of another vector for `FormatItems`.

2022-04-14 19:19 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/expressions/sequence_expression.rs
> +    node: JsSyntaxNode,
I would change this to only accept a `JsSequenceExpression` and handle the non sequence expression when trying to format the left hand side.

2022-04-14 19:19 UTC, MichaReiser commented on crates/rome_js_formatter/tests/specs/js/module/expression/sequence_expression.js
> +abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqr
This doesn't match prettiers formatting

```
abcdefghijklkmnopqrstufwkdsf,
	abcdefghijklkmnopqrstufwkdsf,
	abcdefghijklkmnopqrstufwkdsf,
	abcdefghijklkmnopqrstufwkdsf,
	abcdefghijklkmnopqrstufwkdsf,
	abcdefghijklkmnopqrstufwkdsf,
	abcdefghijklkmnopqrstufwkdsf,
	abcdefghijklkmnopqrstufwkdsf;
```

2022-04-14 19:19 UTC, MichaReiser commented on crates/rome_js_formatter/tests/specs/prettier/js/sequence-break/break.js.snap
> +    argument1
This doesn't match prettier's formatting

```
const f = (argument1, argument2, argument3) => (
	doSomethingWithArgument(argument1),
	doSomethingWithArgument(argument2),
	argument1
);
```

2022-04-14 19:32 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/js/module/expression/sequence_expression.js
> +abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqrstufwkdsf, abcdefghijklkmnopqr
This is not the snapshot, so I think you're something else.

2022-04-17 15:19 UTC, ematipico commented on crates/rome_js_formatter/src/js/expressions/sequence_expression.rs
> +    node: JsSyntaxNode,
Could you provide an explanation please?

2022-04-17 15:28 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/expressions/sequence_expression.rs
> +    node: JsSyntaxNode,
You do 

```
fn flat_sequence_expression(
    list: &mut FlattenItemList,
    node: JsSequenceExpression,
)
```

You can then remove the inner match, but you'll have to change 

```
let left = sequence_expression.left()?;
let right = sequence_expression.right()?;
let comma = sequence_expression.comma_token()?;
flat_sequence_expression(list, left.syntax().clone(), formatter, Some(comma))?;
let formatted =
    format_elements![space_token(), right.format(formatter)?, formatted_comma];
list.push(FlattenItem::SequenceExpression(
    sequence_expression,
    formatted,
))
```

to 

```
let left = sequence_expression.left()?;
let right = sequence_expression.right()?;
let comma = sequence_expression.comma_token()?;

if let Some(JsSequenceExpression(left)) = JsSequenceExpression::cast(left) {
   flat_sequence_expression(list, left, formatter, Some(comma))?;  
} else {
  let formatted = format_elements![left.to_format_element(formatter)?, formatted_comma];
  list.push(FlattenItem::OtherNode(left.syntax(), formatted))
}

flat_sequence_expression(list, left.syntax().clone(), formatter, Some(comma))?;
let formatted =
    format_elements![space_token(), right.format(formatter)?, formatted_comma];
list.push(FlattenItem::SequenceExpression(
    sequence_expression,
    formatted,
))
```

2022-04-17 15:32 UTC, ematipico commented on crates/rome_js_formatter/src/js/expressions/sequence_expression.rs
> +    node: JsSyntaxNode,
I didn't want to know how, I wanted to know why. To me they seems two ways to achieve the same thing

2022-04-17 16:09 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/expressions/sequence_expression.rs
> +    node: JsSyntaxNode,
It encodes the constraint that `flat_sequence_expression` only gets called on `JsSequenceExpression`. I find it a bit  confusing that the method can be called with any expression even though it's called `flat_sequence_expression`. 
This helps the reader to understand the code because it encodes more information

It also avoids one additional function call if the left hand side isn't a `JsSequenceExpression`, making it easier to reason about the recursion (and potentially replacing it wth an iterator). 

It also simplifies the method's code because you no longer need that match (that is kind of expensive if we already know it's a `JsSequenceExpression).

2022-05-05 17:03 UTC, ematipico commented
Closed in favour of https://github.com/rome/tools/pull/2541

The algorithm changed a lot so it was best to start from scratch.  I addressed also @MichaReiser 's feedback

2022-05-05 17:03 UTC, closed without merging