feature: JSX Spread Attribute
rome/tools pull request #2454
Opened 2022-04-14 21:09 UTC by NicholasLYang

## Summary

Closes #2278

## Test Plan

2022-04-25 17:41 UTC, NicholasLYang commented
The JS formatting fails because we need to update the action to use the latest version of the formatter.

2022-04-25 19:30 UTC, NicholasLYang commented
Okay reverted the jsx changes. Perhaps we need a CI workflow that builds a nightly Rome CI workflow haha.

2022-04-26 06:57 UTC, ematipico requested changes

2022-04-26 06:57 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/jsx/attributes.jsx.snap
> +/>;
This output is [different from prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBDTBeTAHngGctgA6KgdQEsYALAQQDU4AnATwBloBzAGIBXKGBi1ojbDAD6cAB5g4cACYkZjODNS0oWgO60VjGfobSZ5gA5WE6wyfoNaJABQBKAL6YA9AD4AbhAAGhAIK3FoEmRQbHZ2CH0ABTi7ZBBsVH1sTmjQgCN2bDAAawwAZWwAWzhuXThkADNMkjgCotKKq2LdPmQYdiE2kDgq-NUVVW5sKD4hbD44AQh2KulxWfTsIRgIEJAGGCrUamdSbqVyu3paADd6TnSwEjyQXVb2GCSivjWmluGACsSPJyr10ABFIQQeD-VCtULddgfdL5bDjVD7KzsXQwOjGBjIAAcAAZEQlWtQilZ0ti4B9bg1QgBHaHwb7haIobAkAC0elUqn27DgrNoIu+Cz+SGa8OGrSqtH6g3l4LgUJhDRlANCMHR+MYyAATLqirQdLMAMIQKrSkYkACs+yErQAKuiuQMhqFbkMAJJQSawcpgHERJiB8owTjoOGtTyeIA)

I believe they use this heuristic to add the parenthesis: https://github.com/prettier/prettier/blob/a9de2a128cc8eea84ddd90efdc210378a894ab6b/src/language-js/needs-parens.js

We don't have one yet, but we can start.

2022-04-26 14:37 UTC, NicholasLYang commented on crates/rome_js_formatter/tests/specs/jsx/attributes.jsx.snap
> +/>;
Yeah prettier tends to put JSX in parentheses. Perhaps we can open an issue for this? It feels out of scope for this PR

2022-04-26 15:15 UTC, NicholasLYang commented on crates/rome_js_formatter/tests/specs/jsx/attributes.jsx.snap
> +/>;
#2497

2022-04-26 18:34 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/jsx/attributes.jsx.snap
> +/>;
Why is it out of scope? The parentheses are part of this PR. 

How do you plan to fix this? Will you create a new PR just for that? 

The entire heuristic of the parentheses is very big, so wouldn't be better starting it as part of this PR, instead of leaving for later and implement the whole logic?

The output doesn't match, so I wouldn't want to merge something that is halfway there without a plan of how to implement the whole solution.

2022-04-27 18:11 UTC, NicholasLYang commented on crates/rome_js_formatter/tests/specs/jsx/attributes.jsx.snap
> +/>;
Parenthesizing JSX expressions does not involve JSX spread attributes. That is a separate part of JSX formatting. Sure, it doesn't match, but it's not relevant for this specific issue. For instance, we can have a jsx expression that has no spread attribute that still has this issue: https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=true&sourceType=module#bABlAHQAIABmAG8AbwAgAD0AIAA8AEwAaQBuAGUAVwBpAGQAdABoAEEAbgBkAFEAdQBvAHQAZQBTAHQAeQBsAGUAQQBuAGQATABhAG4AZwB1AGEAZwBlAEYAbwByAG0AIABjAGwAYQBzAHMATgBhAG0AZQBzAD0AewBbACIAcAAtADUAIgAsACAAIgBmAGwAZQB4ACIALAAgACIAaQB0AGUAbQBzAC0AYwBlAG4AdABlAHIAIgAsACAAIgBiAGcALQBzAGwAYQB0AGUALQA1ADAAMAAiACwAIAAiAHQAZQB4AHQALQB4AGwAIgBdAH0AIAAvAD4A

2022-04-27 18:48 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/jsx/attributes.jsx.snap
> +/>;
What do you think if we remove the case that doesn't create the parentheses? 

So there are no parentheses , as you correctly said  that the parentheses are not part of this node

2022-04-27 19:33 UTC, NicholasLYang commented on crates/rome_js_formatter/tests/specs/jsx/attributes.jsx.snap
> +/>;
Sounds reasonable!

2022-04-27 20:27 UTC, ematipico approved these changes

2022-04-27 23:43 UTC, merged