Fix(rome_js_formatter): named import
rome/tools pull request #2498
Opened 2022-04-26 16:32 UTC by IWANABETHATGUY

## Summary
1. Fixed #2441 ,   

main: 
```bash
**File Based Average Prettier Similarity**: 71.96%  
**Line Based Average Prettier Similarity**: 65.15%  
```
pr: 
```bash
**File Based Average Prettier Similarity**: 71.97%  
**Line Based Average Prettier Similarity**: 65.16%  
```

## Test Plan
see the snapshot testing result, which should match the prettier formatting result of the linked issue

2022-04-29 09:28 UTC, ematipico commented
@IWANABETHATGUY you could please add a comment to the issue you want to try to fix? Doing so, other people know that you're working on it and there won't be double PRs.

2022-04-29 10:36 UTC, IWANABETHATGUY commented
> 

Yeah, I forget about that, thanks for reminding me.

2022-04-29 16:16 UTC, IWANABETHATGUY commented on crates/rome_formatter/src/lib.rs
> +    pub fn with_line_width(mut self, line_width: LineWidth) -> Self {
add builder style api , could be convenient when debugging the format code, you could write some code like this
```rust
 println!(
        "{}",
        Formatted::new(elements, FormatOptions::default().with_line_width(113.try_into().unwrap()))
            .print()
            .as_code()
    );
```

2022-04-29 16:18 UTC, IWANABETHATGUY commented
!bench_formatter

2022-05-01 00:54 UTC, cpojer commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +        // see: https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#aQBtAHAAbwByAHQAIABzAG8AbQBlAHQAaABpAG4AZwBTAHUAcABl
Let's not embed long urls like this, there is a high chance that this will get outdated.

Instead, maybe link to this PR or a GitHub issue that contains the link to the playground? That one is mutable, so we could edit the link in the future.

2022-05-02 07:30 UTC, MichaReiser reviewed
Thanks for working on this. 

Have you checked [Prettier's](https://github.com/prettier/prettier/blob/d13feed42b6478710bebbcd3225ab6f203a914c1/src/language-js/print/module.js#L81-L91) implementation of the formatting. It seems to apply more rules than your implementation to determine if and when to break import statements. Can you explain how the two implementations differs and if your changes address all cases outlined in the issue. 

Please add some formatter tests that, at least, cover all the test cases of the linked issue.

2022-05-02 07:30 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +              // }
Delete commented out code?

2022-05-02 07:30 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/module/named_import_specifiers.rs
> +        // )
Delete commented out code?

2022-05-02 07:30 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +            }
You can directly work on the `AstNode`s here, no need to use the `SyntaxNode`

```suggestion
            match named_improt? {
                JsAnyImportName::JsNamedImportSpecifiers(named_specifiers) => {
                    named_specifiers.specifiers.len() > 1 || !default.is_empty()
                }
                _ => true,
            }
```

Also, the `AstSeparatedList` offers a `len` method.

2022-05-02 07:30 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +        // only wrap the name_and_rest elements when named_specifiers is bigger than 1,
The comment doesn't mention the case where the `default ` is empty.

2022-05-02 07:30 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +                    specifiers.specifiers.syntax().children().count() > 1 || !default.is_empty()
We should avoid inspecting the formatter IR if possible and ideally, only make formatting decisions based on the shape of the AST. 

That's why I recommend using `default_specifier.is_none()` rather than `default.is_empty()`. 

I also find this easier to understand because I can reason about the formatting logic without having to know how `default` gets formatted.

2022-05-02 07:30 UTC, MichaReiser commented on crates/rome_js_formatter/src/formatter.rs
> +    pub(crate) fn format_delimited_without_group(
Would you mind adding additional documentation of how this function is different from the others and in what situations it should be used?

2022-05-02 07:49 UTC, IWANABETHATGUY commented
> 
Yeah, the prettier test case is already here https://github.com/rome/tools/pull/2498/files#diff-7903e95e4beeaeb0515e82814fac55ef523efb3d0336f775dd848db1a0a63becR16-R26, so I think I don't need to add any more, right?

2022-05-02 08:12 UTC, leops commented on crates/rome_js_formatter/tests/specs/prettier/js/import/inline.js.snap
>  import { somethingSuperLongsomethingSuperLong1 } from "somethingSuperLongsomethingSuperLongsomethingSuperLong";
This test isn't verifying the case where the import specifier itself goes over the line length, we should add it to our own test suite:
```js
import {somethingSuperLongsomethingSuperLoooooooooooooooooooooooooooooooooooooooooooong} from 'source'
```

2022-05-24 10:05 UTC, ematipico commented
Hi @IWANABETHATGUY , are there any updates on this PR? If you want and don't have time, we can take over the PR and try to finish it.

2022-05-24 10:20 UTC, IWANABETHATGUY commented
> 

This was blocked by IR problem before, i would like to have a look today.

2022-05-25 16:42 UTC, IWANABETHATGUY commented
@ematipico I am ready for review

2022-05-26 12:41 UTC, ematipico requested changes
Thank you for looking into this! I'd request some changes, because we would like to document these particular formatting rules, especially if they come from prettier:

- document the new logic, especially with example and edge cases (comments?)
- add new tests that cover the new logic and new conditions

2022-05-26 12:41 UTC, ematipico commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +        // if `can_break` is true we just use the previous format strategy, otherwise we use the new format strategy.
I believe this comment is outdated. What's `can_break`? Probably it has to be revisited

2022-05-26 12:41 UTC, ematipico commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +                                || syntax_node.has_trailing_comments()
You can use `has_comments_direct` instead

2022-05-26 12:41 UTC, ematipico commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +                            let syntax_node = specifiers.clone().into_syntax();
Do you need to consume `specifiers`? Isn't `specifiers.syntax()` enough?

2022-05-26 12:41 UTC, ematipico commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +        // if `can_break` is true we just use the previous format strategy, otherwise we use the new format strategy.
Could you please add some comment about the new format strategy? How does it work? 
Maybe some snippet inside the documentation would help.

It might be helpful to move this new logic inside a private function, so we you can add documentation comments,

2022-05-26 12:41 UTC, ematipico commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +                    let first_specifier = specifiers.specifiers().iter().next().unwrap();
Could you please add a `// SAFETY` comment, saying why it's safe to call `unwrap` here?

2022-05-26 12:41 UTC, ematipico commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +        let formatted_named_import = if default_specifier.is_some() {
You could write this

```rs
if let Some(JsAnyNamedImport::JsNamedImportSpecifiers(ref specifiers)) = default_specifier {
    if specifiers.specifiers().len() == 1 {
        // .. rest of code
    } else {
       named_import.format().format(formatter) 
    }
} else {
    named_import.format().format(formatter)
}
```

Like this we remove a `match`

2022-05-26 14:23 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +        let formatted_named_import = if default_specifier.is_some() {
It seems your code snippet is different from mine, `default_specifier` will never match `JsNamedImportSpecifiers` due to `default_specifier`'s type is `JsDefaultImportSpecifier`

2022-05-26 15:59 UTC, IWANABETHATGUY commented
!bench_formatter

2022-05-27 07:07 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/module/import_named_clause.rs
> +            named_import.format().format(formatter)
Nit: You can use `formatted![formatter, [named_import.format()]]` reads a bit nicer.

2022-05-31 13:44 UTC, ematipico commented
@IWANABETHATGUY how's the PR going? We would like to merge this PR for the next release, which is next week. Do you think you'll be able to address the CI failure and the feedbacks in the next few days?

If not, please let us know, so we can help.

2022-06-06 11:49 UTC, ematipico approved these changes
Looks good! Let's fix the conflict and then we can merge it

2022-06-06 11:49 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/prettier/js/import/comments.js.snap
> +assertion_line: 181
This change can be reverted

2022-06-06 15:13 UTC, merged