fix(rome_js_formatter): elide quotes inside members
rome/tools pull request #2502
Opened 2022-04-27 13:33 UTC by ematipico

## Summary

Closes https://github.com/rome/tools/issues/2405

I also update `insta` to the latest.

## Test Plan

Added new tests to cover cases where it's safe to elide quotes VS cases where it's not safe.

2022-04-27 14:04 UTC, leops reviewed
It was mentioned in the options discussion that we would eventually add a "preserve quotes" option for the formatter, is this something we'd want to introduce in this PR or add back in later (since preserving quotes used to be the default behavior of the formatter before this change) ?

2022-04-27 15:00 UTC, ematipico commented
> It was mentioned in the options discussion that we would eventually add a "preserve quotes" option for the formatter, is this something we'd want to introduce in this PR or add back in later (since preserving quotes used to be the default behavior of the formatter before this change) ?

The plan is to add the option after this PR lands: https://github.com/rome/tools/issues/2482

Essentially eliding quotes will be the **default behaviour** (which mimic "as-needed" from Prettier) and we will have a boolean option to mimic the "preserve" from Prettier: https://github.com/rome/tools/discussions/2465#discussioncomment-2614130

2022-04-27 15:19 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +                    Cow::Owned(new_text.to_string()),
Internally there's a check, making sure that the string was preserved. I have to allocate a new string, unfortunately:

```
---- specs::prettier::js::object_prop_break_in::long_value stdout ----
thread 'specs::prettier::js::object_prop_break_in::long_value' panicked at 'assertion failed: `(left == right)`
  left: `"ABC"`,
 right: `"\"AB"`: The borrowed string doesn't match the specified token substring. Does the borrowed string belong to this token and range?', /Users/emanuele/www/rometools/rome/crates/rome_formatter/src/format_element.rs:1190:17
```

2022-04-27 15:20 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +                    Cow::Owned(new_text.to_string()),
Maybe we can cheat it by passing a new range...

2022-04-27 15:30 UTC, leops commented on crates/rome_js_formatter/src/utils/mod.rs
> +                    Cow::Owned(new_text.to_string()),
Looking at the code for `Token::from_syntax_token_cow_slice` I think offsetting the start of the token by 1 should work, it will only change the way sourcemap markers are emitted, and even then the marker probably just be more accurate since the output identifier will start at the correct position inside the original string literal

2022-04-27 15:42 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +                    Cow::Owned(new_text.to_string()),
That worked :)

2022-04-28 06:18 UTC, IWANABETHATGUY requested changes

2022-04-28 06:18 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/utils/mod.rs
> +            PropertyNameCheckMode::Alphabetic => !text_to_check.chars().any(|c| !c.is_alphabetic()),
`text_to_check.chars().all(char::is_alphabetic)` would be more  efficient and point free

2022-04-28 06:18 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/utils/mod.rs
> +                !text_to_check.chars().any(|c| !c.is_alphanumeric())
same, `text_to_check.chars().all(char::is_alphanumeric)` would be more efficient and point free

2022-04-28 06:18 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/prettier/typescript/compiler/ClassDeclaration22.ts.snap
> -  "bar"() {}
https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#YwBsAGEAcwBzACAAQwAgAHsACgAgACAAIgBmAG8AbwAiACgAKQA7AAoAIAAgACIAYgBhAHIAIgAoACkAIAB7AH0ACgB9AA==
It seems that prettier don't remove the quotes

2022-04-28 06:19 UTC, IWANABETHATGUY commented
Also `clippy` need to pass

2022-04-28 06:55 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/prettier/typescript/compiler/ClassDeclaration22.ts.snap
> -  "bar"() {}
You have to enable typescript. That is not a valid JS syntax (there's a syntax error)

2022-04-28 07:16 UTC, leops commented on crates/rome_js_formatter/src/utils/mod.rs
> +                !text_to_check.chars().any(|c| !c.is_alphanumeric())
In fact it's possible to return the function pointers to `char::is_alphabetic` or `char::is_alphanumeric` from the match expression and use that as the argument to `.all()`

2022-04-28 18:11 UTC, ematipico commented
> We should handle the case where the key is an empty string: [Playground](https://play.rome.tools/dd62e8f/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#bABlAHQAIABhACAAPQAgAHsAIAAiACIAOgAgADEAMAAsACAAIgBjAF8AZAAiADoAIAAzADAAIAB9AA==)

Nice catch Nicholas!!! Will do that

2022-04-29 16:18 UTC, NicholasLYang submitted a review, later dismissed

2022-04-29 16:18 UTC, NicholasLYang commented on crates/rome_js_formatter/src/utils/mod.rs
> +    fn replace_node(
Is there a reason why this is nested inside another function?

2022-04-29 16:18 UTC, NicholasLYang commented on crates/rome_js_formatter/src/utils/mod.rs
> +    fn text_can_be_replaced(&self, text_to_check: &str) -> bool {
Should we not allow underscore as well? Prettier appears to allow underscore when unquoting: [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#bABlAHQAIABmAG8AbwAgAD0AIAB7ACAAIgBiAGEAcgBfAGIAYQB6ACIAOgAgADIAMAAgAH0A)

2022-05-02 07:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +    fn text_can_be_replaced(&self, text_to_check: &str) -> bool {
Isn't prettier unquoting all strings that form valid identifiers according to the spec? 

I'm wondering if we should, therefore, 

* rename `PropertyNameCheckMode` to `MemberContext` which is either `Type` or `Member`
* Or extend the `PropertyName` enum to have additional viarants for the `Type` cases. 

Nit: Rename method to `is_valid_identifier_name`?

2022-05-02 07:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +        // is higher than 2, it means that the text has something in it
```suggestion
        // is higher than 2, it means that the identifier name isn't empty
```

It might be worth to move this test into the `text_can_be_replaced`. It then becomes a simple `ident.is_empty()`.

2022-05-02 07:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +                        name.text_trimmed_range().start().add(TextSize::from(1)),
You're adding ` to the start of the range to skip over the start quote. Isn't it necessary to subtract 1 from the end as well?

2022-05-02 07:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +        },
Would it be simpler to restructure the `PropertyName` enum to have the following variants:

```
ComputedMemberName
LiteralMemberName
```

2022-05-03 13:34 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +    fn replace_node(
No particular reason, would you prefer it outside? I didn't want to make visible because it's exclusive  to this logic, but used multiple times.

2022-05-03 13:43 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +                        name.text_trimmed_range().start().add(TextSize::from(1)),
Probably yes

2022-05-03 13:45 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +                        name.text_trimmed_range().start().add(TextSize::from(1)),
It seems not: 

```
---- specs::prettier::js::object_prop_break_in::long_value stdout ----
thread 'specs::prettier::js::object_prop_break_in::long_value' panicked at 'assertion failed: `(left == right)`
  left: `"ABC"`,
 right: `"\"AB"`: The borrowed string doesn't match the specified token substring. Does the borrowed string belong to this token and range?', /Users/emanuele/www/rometools/rome/crates/rome_formatter/src/format_element.rs:1190:17

````

2022-05-03 13:50 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +    fn text_can_be_replaced(&self, text_to_check: &str) -> bool {
> Isn't prettier unquoting all strings that form valid identifiers according to the spec?

I don't know

> I'm wondering if we should, therefore,
> 
>     * rename `PropertyNameCheckMode` to `MemberContext` which is either `Type` or `Member`
> 
>     * Or extend the `PropertyName` enum to have additional viarants for the `Type` cases.
> 

`MemberContext` is a better suggestion, thank you!

> Nit: Rename method to `is_valid_identifier_name`?

I don't know, maybe? But this logic is applied to properties only, I would like to keep it that way for now.

2022-05-03 14:12 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +    fn text_can_be_replaced(&self, text_to_check: &str) -> bool {
> Should we not allow underscore as well?

True, I had that in my initial implementation then forgot to put it. I tried to implement a KISS solution, it should cover all the cases.

2022-05-04 06:15 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +    fn text_can_be_replaced(&self, text_to_check: &str) -> bool {
> > Isn't prettier unquoting all strings that form valid identifiers according to the spec?

> I don't know

Can you please verify with the prettier implementation.

2022-05-04 06:15 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +                        name.text_trimmed_range().start().add(TextSize::from(1)),
Ah, this is only the start offset and not the full range. Yes, then this is correct.

2022-05-04 06:15 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +pub(crate) enum PropertyName {
Nit: `MemberName`?

2022-05-04 06:15 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +pub(crate) fn format_property_name<Member: Into<PropertyName>>(
Nit: `format_member_name`

2022-05-04 06:15 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +        }
This check is now redundant because of the check on line 727.

2022-05-04 07:03 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +    fn text_can_be_replaced(&self, text_to_check: &str) -> bool {
> Can you please verify with the prettier implementation.

If you meant identifiers that contain `_`, then yes, prettier removes the quotes.

2022-05-04 07:25 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +        }
We still needed to cover cases where we have empty strings:

```js
const a = { "": something }
```

2022-05-04 07:42 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +    fn text_can_be_replaced(&self, text_to_check: &str) -> bool {
This is the JS spec defining what a valid identifier is: https://tc39.es/ecma262/multipage/ecmascript-language-lexical-grammar.html#prod-IdentifierName

Now try the different production with prettier to see when it removes the quotes. For example, prettier removes the quotes for `$a`. Does rome do so too?

2022-05-04 07:42 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +        if text.starts_with(QUOTES_TO_OMIT) && text.ends_with(QUOTES_TO_OMIT) {
Let's keep the check for `text.len() >= 2` to not remove quotes from `"` (not sure if that gets turned into an error token or not)

2022-05-04 07:49 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +        if text.starts_with(QUOTES_TO_OMIT) && text.ends_with(QUOTES_TO_OMIT) {
It seems redundant. `text.len() > 2` and `text_to_check.is_empty()` do the same thing

2022-05-04 08:05 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +    fn text_can_be_replaced(&self, text_to_check: &str) -> bool {
It should be done, I think

2022-05-04 08:12 UTC, MichaReiser approved these changes

2022-05-04 08:12 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +            }
Nit: can't this be written as

```suggestion
        match self {
            MemberContext::Type => {
                text.chars().all(|c| matches!(c, '_', '$') || c.is_alphabetic)
            }
            MemberContext::Member => {
                text.chars().all(|c| matches!(c, '_', '$') || c.is_alphanumeric)
            }
```

2022-05-04 08:15 UTC, MichaReiser commented
Please address 

> Don't remove quotes from numeric properties in TypeScript because that can result in type checker errors (prettier doesn't remove the quotes as well).

In it's own PR

2022-05-04 08:17 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +            }
Not sure, an identifier can be "_&£_foo", and this case we can't elide the quotes.

Would your suggestion cover  case?

2022-05-04 08:24 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +            }
The problem here is that you can't remove the quotes because of £ and not because of the `_`. For example, prettier removes the quotes for `let a = {"_f_$$_oo": 1 }`

2022-05-04 09:47 UTC, ematipico commented
@NicholasLYang I am going to merge this one. If you have some concerns feel free to leave a comment and I will address them later on

2022-05-04 09:53 UTC, merged