Fix(rome_js_formatter): 🎸 basic finish
rome/tools pull request #2514
Opened 2022-04-28 14:46 UTC by IWANABETHATGUY

## Summary

## Test Plan

2022-04-28 16:37 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/prettier/js/arrays/issue-10159.js.snap
>  {
Those are some changes since I modified the https://github.com/IWANABETHATGUY/tools/blob/c2a467e1a01bb0fc01283f2eb43b2c52e48f7dfb/crates/rome_js_formatter/src/js/statements/block_statement.rs#L37.
The block statement behavior should match to prettier, 
https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#ewBmAG8AcgAgACgAYwBvAG4AcwB0ACAAcwByAGMAUABhAHQAaAAgAG8AZgAgAFsAcwByAGMALAAgAGAAJAB7AHMAcgBjAH0ALgBqAHMAYAAsACAAYAAkAHsAcwByAGMAfQAvAGkAbgBkAGUAeABgACwAIABgACQAewBzAHIAYwB9AC8AaQBuAGQAZQB4AC4AagBzAGAAXQApACAAewB9AH0ACgB7AGYAbwByACAAKABjAG8AbgBzAHQAIABzAHIAYwBQAGEAdABoACAAbwBmACAAWwAxADIAMwAsACAAMQAyADMAXwAxADIAMwBfADEAMgAzACwAIAAxADIAMwBfADEAMgAzAF8AMQAyADMAXwAxACwAIAAxADMAXwAxADIAMwBfADMAMQAyADMAXwAzADEAXwA0ADMAXQApACAAewB9AH0ACgB7AGYAbwByACAAKABjAG8AbgBzAHQAIABzAHIAYwBQAGEAdABoACAAbwBmACAAWwAxADIAMwAsACAAMQAyADMAXwAxADIAMwBfADEAMgAzACwAIAAxADIAMwBfADEAMgAzAF8AMQAyADMAXwAxACwAIAAxADMAXwAxADIAMwBfADMAMQAyADMAXwAzADEAXwA0ADMAMgBdACkAIAB7AH0AfQAKAHsAZgBvAHIAIAAoAGMAbwBuAHMAdAAgAHMAcgBjAFAAYQB0AGgAIABvAGYAIABbADEAMgAzACwAIAAxADIAMwBfADEAMgAzAF8AMQAyADMALAAgADEAMgAzAF8AMQAyADMAXwAxADIAMwBfADEALAAgADEAMwBfADEAMgAzAF8AMwAxADIAMwBfADMAMQBfADQAMwAyADEAXQApACAAewB9AH0A

2022-04-28 16:37 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/prettier/js/babel-plugins/decimal.js.snap
>  .1m
Those changes are due to changes of https://github.com/IWANABETHATGUY/tools/blob/c2a467e1a01bb0fc01283f2eb43b2c52e48f7dfb/crates/rome_js_formatter/src/js/statements/block_statement.rs#L37, Since those `blockStatement` parent are `JS_MODULE_ITEM_LIST`. According to https://github.com/prettier/prettier/blob/main/src/language-js/print/block.js#L19, should insert a new line after `{`

2022-04-28 16:37 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/prettier/js/comments/switch.js.snap
>  }
Align to prettier behavior

2022-04-28 16:37 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/prettier/js/module-blocks/module-blocks.js.snap
> -{}
parent is `JS_MODULE_ITEM_LIST`, should insert a new line

2022-04-28 16:37 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/prettier/js/module-blocks/non-module-blocks.js.snap
> -{}
The same as above

2022-04-28 16:37 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/prettier/js/optional-catch-binding/optional_catch_binding.js.snap
> -try {} catch {} finally {}
align to prettier

2022-04-28 16:37 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/prettier/js/throw_expressions/throw_expression.js.snap
>  )
parent is `JS_MODULE_ITEM_LIST`, should insert a new line

2022-04-29 03:43 UTC, IWANABETHATGUY commented
```bash
test specs::prettier::typescript::webhost::webtsc ... ok

failures:

---- specs::prettier::js::try_::try_ stdout ----
Differences (-input|+output):
                         Line(Hard),
                         SyntaxTokenSlice("/* missing comment */"),
                         Line(Hard),
                     ],
                 ),
-                Group(
-                    List [
-                        SyntaxTokenSlice("{"),
-                        SyntaxTokenSlice("}"),
-                    ],
-                ),
+                SyntaxTokenSlice("{"),
+                Line(Hard),
+                SyntaxTokenSlice("}"),
                 Space,
                 SyntaxTokenSlice("finally"),
                 Space,
                 SyntaxTokenSlice("{"),
                 Line(Hard),

thread 'main' panicked at 'assertion failed: `(left == right)`'
  left: `"try\n/* missing comment */\n{} finally {\n}\n"`
 right: `"try\n/* missing comment */\n{\n} finally {\n}\n"`

Differences (-left|+right):
 try
 /* missing comment */
-{} finally {
+{
+} finally {
 }

', crates/rome_js_formatter/tests/check_reformat.rs:60:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: prettier_tests::check_reformat::check_reformat
             at ./tests/check_reformat.rs:60:9
   3: prettier_tests::test_snapshot
             at ./tests/prettier_tests.rs:95:17
   4: prettier_tests::specs::prettier::js::try_::try_
             at ./tests/prettier_tests.rs:23:1
   5: prettier_tests::specs::prettier::js::try_::try_::{{closure}}
             at ./tests/prettier_tests.rs:23:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    specs::prettier::js::try_::try_
```
@ematipico This is the only test case I failed, but I don't know how to change the test case, 
actually, the new test result should be alright, according to prettier 
https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#dAByAHkACgAvACoAIABtAGkAcwBzAGkAbgBnACAAYwBvAG0AbQBlAG4AdAAgACoALwAKAHsAfQAgAGYAaQBuAGEAbABsAHkAIAB7AH0A

2022-04-29 08:04 UTC, ematipico requested changes
Thank you for looking after it!

Could please create a new test case in our test suite and use the prettier code that Micha pasted in the issue? 

We want to use Prettier's output and make sure it doesn't change. If it's different, it means that we did something wrong. If it doesn't, we reached the compability!

2022-04-29 08:05 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/prettier/js/throw_expressions/throw_expression.js.snap
>  )
You can check the prettier snapshot and see what they do there

2022-04-29 08:08 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/js/auxiliary/default_clause.rs
> +            hard_line_break()
> The comment is really difficult to read... could you please revisit it, or use some commas or dots?

Sorry, this PR is still WIP, I will rewrite the comments after I passed the test case

2022-04-29 08:10 UTC, ematipico commented
> ```shell
> test specs::prettier::typescript::webhost::webtsc ... ok
> 
> failures:
> 
> ---- specs::prettier::js::try_::try_ stdout ----
> Differences (-input|+output):
>                          Line(Hard),
>                          SyntaxTokenSlice("/* missing comment */"),
>                          Line(Hard),
>                      ],
>                  ),
> -                Group(
> -                    List [
> -                        SyntaxTokenSlice("{"),
> -                        SyntaxTokenSlice("}"),
> -                    ],
> -                ),
> +                SyntaxTokenSlice("{"),
> +                Line(Hard),
> +                SyntaxTokenSlice("}"),
>                  Space,
>                  SyntaxTokenSlice("finally"),
>                  Space,
>                  SyntaxTokenSlice("{"),
>                  Line(Hard),
> 
> thread 'main' panicked at 'assertion failed: `(left == right)`'
>   left: `"try\n/* missing comment */\n{} finally {\n}\n"`
>  right: `"try\n/* missing comment */\n{\n} finally {\n}\n"`
> 
> Differences (-left|+right):
>  try
>  /* missing comment */
> -{} finally {
> +{
> +} finally {
>  }
> 
> ', crates/rome_js_formatter/tests/check_reformat.rs:60:9
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
>    1: core::panicking::panic_fmt
>              at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
>    2: prettier_tests::check_reformat::check_reformat
>              at ./tests/check_reformat.rs:60:9
>    3: prettier_tests::test_snapshot
>              at ./tests/prettier_tests.rs:95:17
>    4: prettier_tests::specs::prettier::js::try_::try_
>              at ./tests/prettier_tests.rs:23:1
>    5: prettier_tests::specs::prettier::js::try_::try_::{{closure}}
>              at ./tests/prettier_tests.rs:23:1
>    6: core::ops::function::FnOnce::call_once
>              at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
>    7: core::ops::function::FnOnce::call_once
>              at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> 
> 
> failures:
>     specs::prettier::js::try_::try_
> ```
> 
> @ematipico This is the only test case I failed, but I don't know how to change the test case, actually, the new test result should be alright, according to prettier [play.rome.tools/?lineWidth=80&indentStyle=tab"eStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#dAByAHkACgAvACoAIABtAGkAcwBzAGkAbgBnACAAYwBvAG0AbQBlAG4AdAAgACoALwAKAHsAfQAgAGYAaQBuAGEAbABsAHkAIAB7AH0A](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#dAByAHkACgAvACoAIABtAGkAcwBzAGkAbgBnACAAYwBvAG0AbQBlAG4AdAAgACoALwAKAHsAfQAgAGYAaQBuAGEAbABsAHkAIAB7AH0A)

It seems that the `try {}` part is not correct yet, probably because your new code it's not handling it. If you added it, maybe it should fix the issue

2022-04-29 12:59 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/js/auxiliary/default_clause.rs
> +        };
It can't, `can_cast` must pass a `LanguageKind`. first_child return a `Option<SyntaxNode>`, you need to `unwrap` it.

2022-04-29 13:00 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/js/auxiliary/default_clause.rs
> +        };
I change it to `let first_child_is_block_stmt = matches!(syntax_node.first_child().map(|n| n.kind()), Some(JsSyntaxKind::JS_BLOCK_STATEMENT));`

2022-04-29 13:34 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/js/statements/block_statement.rs
> +    // ```
I explain here why the test would fail before

2022-04-29 13:38 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/prettier/js/throw_expressions/throw_expression.js.snap
>  )
> You can check the prettier snapshot and see what they do there

They would do nothing since this code snippet has a syntax error

2022-04-29 14:03 UTC, ematipico commented on crates/rome_js_formatter/src/js/auxiliary/default_clause.rs
> +        };
Also this works, we use it across the board :)

2022-04-29 14:09 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/js/module/statement/switch.js
> +
@ematipico The code snippet of https://github.com/rome/tools/issues/2407, I have added here

2022-04-29 14:32 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/js/statements/block_statement.rs
> +    }
According to prettier code logic, try_statement is not needed.

2022-04-29 14:35 UTC, IWANABETHATGUY commented
!bench_formatter

2022-04-30 14:23 UTC, IWANABETHATGUY commented
> 
I have dded here
https://github.com/rome/tools/pull/2514/files/cffe4b0aab04dac6f7c766d466497a9143eedcc1#diff-045304d54c7a2918b16b74ec1b51504113cb8479c67a7d6e28b54502078d44c6R16-R19

2022-05-02 08:09 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/auxiliary/case_clause.rs
> +        };
You can use a match here. `matches!(consequent, JsAnyStatement::JsBlockStatement(_))`

2022-05-02 08:09 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/auxiliary/default_clause.rs
> +
Same here, use a `match` that tests directly on the `JsAnyStatement`

2022-05-02 08:09 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/statements/block_statement.rs
> +    // reference https://github.com/prettier/prettier/blob/main/src/language-js/print/block.js#L19
This link will point to an invalid line if the `block.js` file ever changes. 

Open the link, click on the three dots button shown next to line 19 and select: "Copy permalink". Use that link instead.

2022-05-02 08:09 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/statements/block_statement.rs
> +    // here is a example:
```suggestion
    // here is an example:
```

2022-05-02 08:09 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/statements/block_statement.rs
> +            .any(|s| !matches!(s, JsAnyStatement::JsEmptyStatement(_)))
What's the formatted output of the case you explain in the example above with this branch in place?

2022-05-02 08:19 UTC, leops commented on crates/rome_js_formatter/src/js/auxiliary/default_clause.rs
>              // no line break needed after because it is added by the indent in the switch statement
Nit: this outdated comment can be removed

2022-05-02 08:25 UTC, leops commented on crates/rome_js_formatter/src/js/auxiliary/default_clause.rs
>              // no line break needed after because it is added by the indent in the switch statement
Nit: this outdated comment can be removed

2022-05-04 10:28 UTC, ematipico approved these changes
It seems that the formatting is consistent with prettier! I double checked in their playground because it's not easy to see it from this test suite

2022-05-04 12:04 UTC, mrkldshv commented on crates/rome_js_formatter/tests/specs/prettier/typescript/catch-clause/type-annotation.ts.snap
> +}
@ematipico I guess we have minor divergence from prettier in this case. Should we handle this case?

Prettier output: 
```js
try {
} catch (e: any) {}

try {
} catch (e: unknown) {}
```
Playground link: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMBOBPABMAOlAXyzAEMYwALLACjiSxKgwEod8D991s9DizKNOlgCuUANZQIAdyiteBEABoQEAA4wAltADOyUCTRoZABUMI9KEgBtpJDHpUAjNCTDi4MAMokAtnAAZTSg4ZAAzGx04Z1d3Ty81N2CAc2R0EWiQOF8nOAATPPyAxmSREmS4ADEINF8yLShUqxEYCGUQChhfawB1Ck14HUSwOC8LAc0ANwGMZHAdRxBgqLQYE1dkuvDIzIArHQAPLxTrOABFEQh4besolUS0FbmYDDU4HTA0TQ12tS-YHqaPIwCjIAAcAAZ7sYoj1XGo5n93nA0JNQioAI6XeDrdSWEAkHQAWhC+Xy7TQcCxmkp63KWyQEVumSivk0aTQGRUOhO52xoUZOxUMBITkBwNBSAATMLXJprCkAMIQXwMrI6ACs7REUQAKqLLEy7iBJhkAJJQQqwLyfb4wACClq8L1ONyiBAIQA

2022-05-04 13:06 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/js/statements/block_statement.rs
> +            .any(|s| !matches!(s, JsAnyStatement::JsEmptyStatement(_)))
add an extra branch to avoid formatting the same code twice and generating different code,
 here is an example:
```js
try
 /* missing comment */
 {;}
finally {}
```

 if we don't add the extra branch, this function will return false, because  `block.statement` has one empty statement,
 and would be formatted as :
```js
 try
/* missing comment */
{}
finally {}
```
 for the second time, the function would return true, because the block is empty and `parent.syntax.kind` is  `JS_TRY_FINALLY_STATEMENT`, which would hit the branch `Some(_) => true`,
     finally, the code would be formatted as:

```js
 try
/* missing comment */
 {
 } finally {
 }
```

I also commented on codebase

2022-05-04 13:08 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/js/statements/block_statement.rs
> +            .any(|s| !matches!(s, JsAnyStatement::JsEmptyStatement(_)))
https://github.com/IWANABETHATGUY/tools/blob/7b560b65da1ca22d6bab1fbb63c8a948f081a1c8/crates/rome_js_formatter/src/js/statements/block_statement.rs#L48

2022-05-05 15:09 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/specs/prettier/typescript/catch-clause/type-annotation.ts.snap
> +}
Fixed

2022-05-05 15:24 UTC, ematipico commented
Amazing work @IWANABETHATGUY ! Thank you very much for your contribution!

2022-05-05 15:24 UTC, merged