fix(rome_js_formatter): don't add spaces to comments
rome/tools pull request #2515
Opened 2022-04-28 15:22 UTC by ematipico

## Summary

Fixes https://github.com/rome/tools/issues/2447

No big changes in this one, I had to make the iterator a `peekable` as it needs to check if there's a trailing trivia and keep the whitespace in that case.

## Test Plan

Added two test cases that cover the cases we want to fix

2022-04-28 15:24 UTC, ematipico commented on crates/rome_js_formatter/src/formatter.rs
> +                        space_token()
I am thinking that maybe we can do another optimisation here, where we create a new token out of the trivia, by keeping the same text.

It would an optimization similar to what Micha did recently. This would work only for comments, as they are the only ones that contain actual strings.

2022-04-28 16:06 UTC, leops commented on crates/rome_js_formatter/src/formatter.rs
> +                let trailing_trivia = if let Some(next_piece) = next_piece {
Nit: this could be written as `if next_piece.map_or(false, SyntaxTriviaPiece::is_whitespace) { space_token } else { empty_element }`

2022-04-28 17:29 UTC, yassere commented
!bench_formatter

2022-04-28 17:47 UTC, yassere commented on crates/rome_js_formatter/src/lib.rs
> +        let src = r#"strOrNum = unionWithRestParameter3(); // error no call signature
Is this just from local testing?

2022-04-28 18:06 UTC, ematipico commented on crates/rome_js_formatter/src/lib.rs
> +        let src = r#"strOrNum = unionWithRestParameter3(); // error no call signature
Yes. Ignored on purpose

2022-04-28 18:54 UTC, NicholasLYang requested changes

2022-04-28 18:54 UTC, NicholasLYang commented on crates/rome_js_formatter/src/formatter.rs
> +        while let Some(piece) = pieces.next() {
If I'm reading this correctly, we should be checking for the pieces that are not comments to see if they are whitespace and changing `has_seen_whitespace` to true, no? Because currently we do not print a space when there's a line of code followed by a space then a single line comment: [Playground](https://play.rome.tools/1d07d6a/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#bABlAHQAIABhACAAPQAgADEAMAAgACAAIAAgACAALwAvACAAZgBvAG8ACgA=)

2022-04-29 08:08 UTC, ematipico commented on crates/rome_js_formatter/src/formatter.rs
> +                let trailing_trivia = if next_piece.map_or(false, SyntaxTriviaPiece::is_whitespace)
I hoped this could have been consistent but it seems that the spacing of the comments depends on where they are placed.. meaning in which nodes they are.

2022-05-02 08:11 UTC, MichaReiser commented on crates/rome_js_formatter/src/formatter.rs
> +                let trailing_trivia = if next_piece.map_or(false, SyntaxTriviaPiece::is_whitespace)
Yes, the formatting is specific to what the previous/next token is. See the related issue, I outlined the rules.

2022-05-16 13:10 UTC, MichaReiser commented
Prettier categories comments as:

* Leading: In front of a node `class /* in front of identifier Test */ Test {}
* Trailing: After a node, but not followed by a whitespace and only if it is the first comment: `class Test {} /* Trailing for class node */` 
* Dangling: Between two tokens: `function test(/*no arguments*/) {}` 

And Prettier has an extensive rules on when it diverges from these simple rules 

https://github.com/prettier/prettier/blob/1dffa0f9dac571bf0e03969c11fd4548efd44d7a/src/language-js/comments.js#L1-L1036

2022-05-21 19:04 UTC, MichaReiser commented on crates/rome_js_formatter/src/formatter.rs
> +                let trailing_trivia = if next_piece.map_or(false, SyntaxTriviaPiece::is_whitespace)
I'm currently looking into how we should format comments. I do like this implementation but believe that we should instead test if the next/previous token is a punctuation token and, if so, not insert a space. I haven't yet figured out how to do this best in here with skipped token trivia but I'm honestly inclined to just bail out formatting for skipped token trivia

2022-06-13 13:19 UTC, MichaReiser commented
I'm closing this PR because #2701 implements the spacing before/after inline comments based on the previous/next token.

2022-06-13 13:19 UTC, closed without merging