fix(rome_js_formatter): number with trailing whitespace
rome/tools pull request #2519
Opened 2022-04-29 09:03 UTC by mrkldshv

## Summary

Fixes #2501.

This PR adds conditional to `JsStaticMemberExpression` that checks if its value is a number literal expression that has trailing whitespace.

## Test Plan

Added new test that covers the case.

2022-04-29 09:13 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js
> +123 .toString
The issue here is that the formatter emitted `123.toString();` which is not a valid JS program, in fact it shows a syntax error.

2022-04-29 09:26 UTC, ematipico requested changes
Thank you for picking up this! There are some edge cases that we have to cover (thank you JS), I added them to the comments.

2022-04-29 09:26 UTC, ematipico commented on crates/rome_js_formatter/src/js/expressions/static_member_expression.rs
> +            .is_whitespace();
Yes, there's a better way.

1. Look at the [playground](https://play.rome.tools/1d07d6a/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#MQAyADMAIAAuAHQAbwBTAHQAcgBpAG4AZwA=) and check the "AST" tab, you will see that the `value_token` has trivia token attached (`Whitespace`)
2. We have APIs to retrieve those trivias, so you don't need to check the actual text
3. Use the API `object_syntax.trailing_trivia().pieces()` which will give you the iterator of trivias

Now, in this case, we don't need to check for white spaces because we need to cover the following case:
```js
123/****/.toString();

123
.toString();
```
Which means that you just need to check if `pieces().len() > 0`. If so, then we add parenthesis.

2022-04-29 09:26 UTC, ematipico commented on crates/rome_js_formatter/src/js/expressions/static_member_expression.rs
> +                token(")"),
I would suggest to use `hard_group_elements` here, so possible comments are kicked outside of the parenthesis.

```suggestion
				hard_group_elements(format_elements![
        	        token("("),
    	            formatted_object,
	                token(")"),				
				]),
```

2022-04-29 09:26 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js
> +123 .toString
Could you add more cases? 

```js
123
/****/.toString;
123/**/.toString;
123
.toString;
```

2022-04-29 12:07 UTC, ematipico commented
> @ematipico Thank you for your review and suggestions!
> 
>     * As for getting trailing trivia from object (referring to this [comment](https://github.com/rome/tools/pull/2519#discussion_r861636117)): `object_syntax` is `SyntaxNode` and it has `last_trailing_trivia` on it. Do we need to use this API or we should get first token of `object_syntax` and use `trailing_trivia` on it?

Yeah `last_trailing_trivia` is totally fine :) I missed that API

2022-04-29 12:53 UTC, mrkldshv commented on crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js
> +123 .toString
Sure, will add them. Although, when I use `hard_group_elements` it doesn't kick comments outside of parenthesis. 
For example:
```js
123/**/.toString;
```
gets formatted to:
```js
(123 /**/ ).toString;
```

2022-04-29 14:56 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js
> +123 .toString
Oh yeah, so in this case you have to use a specific API for this edge case. No need for hard group then. 

```rust
let (leading, content, trailing) = formatted_object.split_trivia();
```

This API will split the formatted element, by giving you leading triva, content and trailing trivia.

Then you can decide the order of the formatting:
```rs
Ok(format_elements![
	leading,
	trailing,
	token("("),
	content,
	token(")"),
])
```

2022-05-03 11:02 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js.snap
> +(123) /**/ .toString;
@rome/staff 

Could you please leave your feedback here? Prettier is not consistent about how the trailing/leading comments are placed between the number and the operator, [check the link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGATAZgPQCpfYB0MEAyjAE4CWUA5gDpSOMaaN4HFmU20gA0ICAAcYVaAGdkoAIYUKEAO4AFOQikoZAG0UyAnlMEAjCjLABrODFIyAtnAAyNOMgBm2iXGOmLV0sLNeZEoAVy8QOFsjOAATGNiHGToQmVo4ADEIClsZGDE6ZBAZEJIBEAALGFstAHVyqngJALA4UnUGqgA3Br1CsAlDEBpPChhlU1octw9wgCsJAA9SXi04AEUQiHhprU9BAIoRwpg9YTgJMGpRMuFqWBqqGJhy5AAOAAZ9hU8a02FC27nOAUTouQQAR028HGIg0RQkAFooHBYrEyhQ4JCqBjxqkpkh3Ltwp5bFRghQwoIJCt1lCXASZoIYDIjA8ni8kOgmaYqFpeABhCC2fERCQAVjKIU8ABUWRpQuFOmEAJJQeKwUiXKiiACCavIelWO08AF8TUA).

Could you please choose your preference?
1. move comments on the very left, before the opening `(`
2. leave the comments between the number and the operator

2022-05-03 11:29 UTC, MichaReiser commented on crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js.snap
> +(123) /**/ .toString;
It seems to me that prettier is consistent:

* If there's no new line, leave it as is
* If there's a newline before the comment, move it to the front. 

And this logic isn't specific to number formatting, it also happens for `a /* */ .toString()`. 

I would probably tackle that separately if it's something we want to change.

2022-05-03 11:59 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js.snap
> +(123) /**/ .toString;
> And this logic isn't specific to number formatting, it also happens for a /* */ .toString().

I just used this on prettier playground and the behaviour doesn't match. Did mean something else by any chance?

2022-05-03 12:13 UTC, MichaReiser commented on crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js.snap
> +(123) /**/ .toString;
[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA9AKk+gdDCAZRgCcBLKAcwB0pbbVasd8jSLKQAaECABxhloAZ2ShUJEhADuABQkJRKVABtpqAJ6ieAIxKowAazgxCqALZwAMhTjIAZquFxd+oycJ8DHZKQCuLiBw5jpwACZh4VaoVH6olHAAYhAk5qgwglTIaH4E3CAAFjDmKgDqBWTwwl5gcISKlWQAbpUa2WDC2iAUziQwsvqUaQ5OgQBWwgAehBwqcACKfhDwIyrOPF4kvdkwGnxwwmDkAvl85LClZGEwBcgAHAAMG1LOpfp82WcHcCRNdjwARyW8AG-CUaGEAFooHBwuF8iQ4ECyIiBvFhkhHGtAs5zGRfCQAjxhLMFsC7JjRjwYKgdJdrrckAAman6MgqDgAYQg5gxQWEAFZ8n5nAAVWlKfyBJoBACSUEisEIRzIAgAggriBo5qtnABfPVAA)

Input:

```
a/**/.toString


a
/**/.toString
```

Output:

```
a /**/.toString;

/**/ a.toString;
```

Or is this about inserting the parentheses? It then probably is a problem with all expressions that must be parenthesized.

2022-05-03 13:28 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/js/module/number/number-with-space.js.snap
> +(123) /**/ .toString;
It's wasn't the same code you pasted 😅 [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA9AKgASfdgOhggGUYAnASygHMAKASgB0oWMc9sWjSLr7mrIahZZc+HmSq0QAGhAQADjErQAzslCpy5CAHcACtoQaUqADZ7UATw3yARuVRgA1nBglUAWzgAZanDIAGYWanAOTq7uJIrO-MgUAK7hIHBe9nAAJplZvqi0iag0cABiEOReqDAqMmaJxHIgABYwXuYA6k2U8GqxYHAkJt2UAG7d1sjganYg1GHkMAZONJXBoSkAVmoAHiT85nAAiokQ8GvmYfKx5POTMNaKcGpgVMqNitIw7ZSZME3IAA4AAxXXRhdpORSTD5PODkEaBeQARxO8CWSlMaDUAFooHAsllGuQ4CjKMSlkVVkgQhcUmEvJQEuRkvI1PsjqjAtT1vIYKh7N9fv8kAAmXlOSjmfgAYQgXipqTUAFZGokwgAVfmmJIpEbJACSUBysBIL0oygAgkayNYDucwgBfB1AA)

2022-05-03 13:28 UTC, ematipico approved these changes

2022-05-04 09:48 UTC, merged