fix(rome_js_formatter): keep quotes for numeric members
rome/tools pull request #2536
Opened 2022-05-04 10:17 UTC by ematipico

## Summary

This PR closes #2405

It implements the numeric part of the algorithm. 
It turns out that prettier applies the same logic to both JS and TS.

Members that starts with a number are not eligible to be quoteless.

## Test Plan

Unfortunately it's not easy to compare it with Prettier  output, that's why I suggest to [compare their playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAGtgXm2AB0psLsSQBbOGgIzgCdqlsBnGZgSygHMA3GUrYA9GOxoIAV04wAhmmwAbHgGscMABY8OIytTqMWAWmNNWybFBknmAGgMVqAFjY27lp+UMgA7jw6APoyUAAmLByQzHAetvbOVCAADACMAJwA7PFeLD6i1ADMULn2BX5FGGXeSdQYGTUsdSDBACTBAGadHTQQzFB8-MFQEDDBAI4yY3D61gm1vi6tHd29-YMCwWizk9PwHMEAAk2sUAC+wqXXfPDMnQpgOACaxC0WzdZcvAJXohJSWTyJSqDRaXT6JbJD7Mcz0SynCrLdzzPKOFqBEJhSLMaL9OKoxJQ6jpbKIlolcnEkBVKmFEANU4tdpdHrBPoDIYjMZ7GZzdgLfLM1ZsjmbYY7Q5TPnHJkXMhkFRwGBvakwjzfIZI8SSaRyLggtSabA6PTveFmdWExb0lECtHa6iY7ShCJRGIE+3lFqknLWoXUyn+9GB6rBx0Mxrh4Ws9acrajcbSg50vwstbsjZcyW8g6y6MXQjYABuChUMjgghADhAEAwMB40A4yFACmYzAg-gACm2EM2UGX-EpmzWGMxHpoYABlBR0AAyfDgyAeKg4cFH47Ak6nGEeQ2Q3ArNYt4Ui4TnCgEMgU-DgADF+jQFDAGwJkCAFDIYBBqyBtDAaBUAB1XQDl3J4pz7IIeGLII0HfMAOBHEA+DXZgYC7cd+CfZcyzXGsACsOAADynIYlQARX2JckBXfCGTbND33QLBol4etfwwH4YCAnhwh0ZAAA4UhrLiIDXIDxwwd8uNmFhiyXGtkzgTC637D8OFMKA4DgM9f1iKYeFiTCbxw2i8PXEA1xoHgD2YI8rPIuAqJmXDV0sxQGF4-jtGQAAmGtuAUHg1AEABhCAaDMkBZgAVl-GQ1wAFQUBh+0PSziwrABJN1YCnMB2JgABBCIp3QJU3LXc5ziAA) with our snapshots.

2022-05-04 10:19 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/prettier/typescript/custom/computedProperties/string.ts.snap
> +type B = { string: "B" };
This matches prettier's output

2022-05-05 07:45 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/src/utils/mod.rs
> +        })
in most case property-name would be `alphanumeric`, so I guess it would be more efficient change   the code to ` c.is_alphanumeric() ||  matches!(c, '_' | '$')  `

2022-05-05 13:27 UTC, MichaReiser reviewed
>  It turns out that prettier applies the same logic to both JS and TS.

This isn't the case for all number

2022-05-05 13:27 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +        text_to_check.chars().enumerate().all(|(index, c)| {
Do we still need the `MemberContext` now that the rule seems to be the same for types and regular members.

2022-05-05 13:27 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +            if index == 0 && c.is_numeric() {
I just checked this again and we forgot that we're talking about members, not identifiers. 

A all digits string member can be turned into a number literal that.

```
{
  "123": true,
  // same as
  123: true
}
```

However, Prettier doesn't unquote all number members in TypeScript.

So the rule must support:

* string forming a valid identifier -> print as identifier
* string forming a valid number -> print as number literal (only for JS)

2022-05-05 14:55 UTC, ematipico commented
> This isn't the case for all number

Could you please share some cases that I might have missed? I couldn't find one

2022-05-05 14:56 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +            if index == 0 && c.is_numeric() {
That is true, but prettier doesn't seem to the quotes from numeric like members (that can be valid members):  [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAExMB0QCMATAMz5KYBmmAvpgLxUDcmIANCBAA4wCW0AZ2SgAhgCcxEAO4AFcQiEoRqKSICeQjgCMxIsAGsMAZREBbOABleUOMkrKBcbboPGue6wHNkMMQFcnEDhTLTgAEzDwixEoTz8RTzgAMQgxUxEYPljkEBE-GAh2EAALGFNUAHVi3ngBdzA4IwUa3gA3GrUcsAFNEGtHMRgZXU90uwdAgCsBAA8jL3QART8IeHHURw53MQGcmDUuOAEwMV4eIq5T2AreMJhi5AAOAAYtyUcK3S4cy6O4MVatg4AEcVvBhtxFLkBABaGzhcJFMRwUG8ZHDBJjJD2DaBRymXg+fx4hZwZarWzYiYcGAiLQ3O4PJBEGm6XioLwAYQgpixQQEAFYin5HAAVOmKXwBDitAIASSgkVgRhOZxgAEFFUZ9uh1o4aDQgA)

2022-05-06 06:23 UTC, MichaReiser commented
> > This isn't the case for all number
> 
> Could you please share some cases that I might have missed, please? I couldn't find one

Sorry, I didn't intend to submit that comment. I first started this comment before I then wrote the more detailed comment in `utils/mod.rs`

2022-05-06 06:30 UTC, MichaReiser requested changes

2022-05-06 06:30 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
>              }
My understanding is that the difference isn't based on whether this is a type or not but IF typescript is enabled or not. 

In my view, the algorithm must be something along the following lines:

Create two booleans: `validIdentifier` and `validNumberLiteral` and initialize both to true

Then iterate over all characters:
* If you encounter any non-numeric value, set `validNumberLiteral` to `false`
* If you encounter a number and it's the first character, set `validIdentifier` to `false`
* If you encounter any non-alphanumeric character that isn't `_` or `$` set `validIdentifier` to false

If `source_language != TypeScript` && `validNumberLiteral` || `validIdentifier`, remove the quotes. Otherwise don't. 

You should then also be able to remove the `MemberContext`

2022-05-06 06:30 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +            if index == 0 && c.is_numeric() {
You need to change the parser to `babel`.

2022-05-06 07:15 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
>              }
To add two examples:

## JavaScript file

**Input**

```js
({
  "1": test
})
```

**Output**

```js
({
  1: test,
});
```

## Typescript file

**Input**

```ts
({
  "1": test
})
```

**Output**

```ts
({
  "1": test,
});
```

2022-05-06 07:32 UTC, ematipico commented
PR on hold as at the moment the formatter doesn't have the understanding if it's parsing a TS file or a JS file. 

In order to give this information to the formatter, we have to extract it from the `SourceType`. We will need to pass this information first, and then we might be able to achieve this.

2022-05-31 17:03 UTC, ematipico commented on crates/rome_js_formatter/src/utils/mod.rs
> +            if index == 0 && c.is_numeric() {
This should be flagged now, I added a new test that should cover the case

2022-05-31 17:31 UTC, MichaReiser reviewed
I'll need to review the rest tomorrow. This is some sophisticated stuff that my brain isn't capable of handling at this time of a day :D

2022-05-31 17:31 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +pub(crate) fn format_member_name<Member: Into<MemberName>>(
Nit: Can we implement `Format` on `MemberName` instead. This will fit nicer into the new architecture. 

`write!(f, [MemberName::from(member)])?`

And I would recommend renaming this struct to `FormatMemberName` to make sure it's an object that can format a member name.

2022-05-31 17:31 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/string_utils.rs
> +    ///
Delete or document?

2022-06-02 07:38 UTC, MichaReiser reviewed
Looks good. One thing that I'm wondering is if it would be better to have small helper functions for the string cleaning but then have different

* `FormatLiteralMemberName` 
* `FormatDirectiveLiteral` 
* ... 

Functions that call into this helpers. It could help to remove some branching and may help to split this code into some smaller files. 

I'm considering this because it feels like it's becoming this one string manipulation that is able to handle ALL cases which makes it harder to reason about how the code works (for a specific case)

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/assignments/object_assignment_pattern_property.rs
> +                FormatMemberName::from(member?).format(formatter),
Nit: You can remove the `.format` here. 
```suggestion
                FormatMemberName::from(member?),
```

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/classes/constructor_class_member.rs
> +                FormatMemberName::from(name?).format(formatter),
```suggestion
                FormatMemberName::from(name?),
```

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/classes/getter_class_member.rs
> +                FormatMemberName::from(name?).format(formatter)?,
```suggestion
                FormatMemberName::from(name?),
```

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/classes/method_class_member.rs
> +                FormatMemberName::from(name?).format(formatter),
```suggestion
                FormatMemberName::from(name?),
```

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/classes/setter_class_member.rs
> +                FormatMemberName::from(name?).format(formatter),
```suggestion
                FormatMemberName::from(name?),
```

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/ts/auxiliary/property_signature_type_member.rs
> +                FormatMemberName::from(name?).format(formatter),
```suggestion
                FormatMemberName::from(name?),
```

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/ts/classes/method_signature_class_member.rs
> +                    FormatMemberName::from(name?).format(formatter),
```suggestion
                    FormatMemberName::from(name?),
```

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +    Literal(JsLiteralMemberName),
The formatting seems to mainly depend on the kind of the member name and less on whatever the parent is an object, class or literal. How about 

```rust
pub(crate) FormatMemberName {
  LiteralMemberName(JsLiteralMemberName),
  ComputedMemberName(JsComputedMemberName),
  PrivateClassMemberName(JsPrivateClassMemberName),
}
```

This adds a bit more complexity to `from` but simplifies the formatting (removes a lot of duplication)

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/string_utils.rs
> +}
Nit: `SourceFileKind`? and maybe write out `TypeScript` and `JavaScript` (or add documentation but I would prefer more descriptive names in favour of documentation).

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/string_utils.rs
> +    pub fn new(token: &'token FormatLiteralStringToken<'_>, chosen_quote: QuoteStyle) -> Self {
I think you can make all these types private (`FileSource`, `LiteralStringNormalizer`, `StringInformation`) as well as all the functions. Or are they called from outside this module?

2022-06-02 07:38 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/string_utils.rs
> +impl<'token> LiteralStringNormaliser<'token> {
What's the motivation of splitting this out into its own struct. Seems like most methods are only operating on the `FormatStringLiteralToken`

2022-06-02 07:54 UTC, ematipico commented on crates/rome_js_formatter/src/utils/string_utils.rs
> +impl<'token> LiteralStringNormaliser<'token> {
I allows me to have a better testing suite, because I don't need to have a fully fledged AST. Like this I can just create a token out of a tree builder and then pass the options I need for the cleaning.

2022-06-02 08:29 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/string_utils.rs
> +impl<'token> LiteralStringNormaliser<'token> {
You can use `parse` to get tokens or maybe even @leops mutation API?

2022-06-02 08:58 UTC, ematipico commented on crates/rome_js_formatter/src/utils/string_utils.rs
> +impl<'token> LiteralStringNormaliser<'token> {
Still, the testing is **easier this way**, because even though I could use the parser, I would need to assert it against the final IR, which is not the point of the testing. Testing against IR is more error prone because it relies on how the parents are formatted. I am happy with current setup.

2022-06-03 11:30 UTC, ematipico commented
> Looks good. One thing that I'm wondering is if it would be better to have small helper functions for the string cleaning but then have different
> 
>     * `FormatLiteralMemberName`
> 
>     * `FormatDirectiveLiteral`
> 
>     * ...
> 
> 
> Functions that call into this helpers. It could help to remove some branching and may help to split this code into some smaller files.
> 
> I'm considering this because it feels like it's becoming this one string manipulation that is able to handle ALL cases which makes it harder to reason about how the code works (for a specific case)

Makes sense. Allow me to address these concerns in the next PR. The works on these PR are not finished yet. The cases are not over unfortunately. At this point it might make more sense to also have a small module for each case (directive, member, literal string)

2022-06-03 11:52 UTC, MichaReiser commented
> > Looks good. One thing that I'm wondering is if it would be better to have small helper functions for the string cleaning but then have different
> > ```
> > * `FormatLiteralMemberName`
> > 
> > * `FormatDirectiveLiteral`
> > 
> > * ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Functions that call into this helpers. It could help to remove some branching and may help to split this code into some smaller files.
> > I'm considering this because it feels like it's becoming this one string manipulation that is able to handle ALL cases which makes it harder to reason about how the code works (for a specific case)
> 
> Makes sense. Allow me to address these concerns in the next PR. The works on these PR are not finished yet. The cases are not over unfortunately (we still have the escaping of other chars) . At this point it might make more sense to also have a small module for each case (directive, member, literal string)

I'm not opposed to it. Is this something you're planning to work on soon?

2022-06-03 14:28 UTC, ematipico commented
> I'm not opposed to it. Is this something you're planning to work on soon?

Yes, it's in my bucket list :)

2022-06-03 15:09 UTC, MichaReiser approved these changes

2022-06-03 15:19 UTC, merged