feature(formatter): JSX Element
rome/tools pull request #2542
Opened 2022-05-05 17:50 UTC by NicholasLYang

## Summary

## Test Plan

2022-05-23 20:51 UTC, NicholasLYang commented
Finally done haha. Took a bit to fix all the issues. Unfortunately because I now track the separator in fill, we have to create a `Fill` struct that's boxed to avoid making `FormatElement` too big. If there's an alternative, I'd be open to ideas. We can't just create a list with the separators inside, because of how fill printing is implemented.

2022-05-24 06:41 UTC, MichaReiser requested changes
Please add a summary and a test plan to your PR. What syntax is this PR covering? What is it not covering? How does it change our metric, etc.

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +/// let expr = fill_elements(space_token(), [token(a), token(b), token(c), token(d)]);
Please add another test case with a separator that prints differently in flat/expanded mode (e.g. `soft_line_break_or_space`) and verify that the printer correctly handles the cases:

* The element, separator, and next element fit on the same line
* The element and separator, but not the next element fit on the same line
* Neither the element nor the separator ,nor the next element fit on the same line.

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +    pub fn is_empty_string(&self) -> bool {
Please document this new method

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +            FormatElement::Empty => true,
Is this necessary because `token("")` returns `empty_element`?

I otherwise don't think the method should return `true` for `Empty` because empty means that the element has no content but it doesn't mean that it is a token. Can we move the `is_empty` check to the call site?

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +                    || fill.separator.will_break()
You may be able to make use of the `Fill` semantics here. 

Checking the separator shouldn't be necessary, at least not in a correctly constructed `FillElement`. `will_break` returns `true` if the element is a `HardLineBreak` or `ExpandParent`. Now, using `fill` with a hardline break or `expand parent` separator is kind of useless and should then not be used. 

But, this is certainly the safer implementation.

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_formatter/src/printer/mod.rs
> +                        format_elements![token("2"), token(",")],
It could have made sense to split the `Fill` addition into its own PR as it is substantial on its own and there are a few different design decisions to be made.

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/formatter.rs
> +    /// joins the result together with [join_elements_hard_line].
What's the meaning of *not separated*. It will join the elements with a hard line break?

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/formatter.rs
> +    fn format_list<List, Node>(&self, list: &List) -> Vec<(SyntaxNode<JsLanguage>, FormatElement)>
I think we should rename this method because its main purpose is about formatting a list with a fallback to verbatim printing

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/formatter.rs
> +        formatted_list.collect()
Have you profiled the performance penalty of this change? The downside is that this now always requires an additional `Vec` allocation that wasn't necessary before. 

It could make sense to extract this into a `FormatListWithRecovery` struct (see `FormatDelimited`) that allows setting a mode for the line separator.

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/classes/static_initialization_block_class_member.rs
> +                formatter.format_list_with_hard_line(&statements),
I believe this method is used by the code gen by default. Make sure to update the code gen

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/expressions/parenthesized_expression.rs
> +        else if JsStringLiteralExpression::can_cast(kind) {
Nit, matching on the expression directly might be faster

```
match expression {
  JsAnyExpression::JsStringLiteralExpression(...) => ,
  JsAnyExpression::JsxTagExpression(..) => 

```

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/js/lists/array_element_list.rs
> +use rome_formatter::{FormatResult, GroupId};
`FormatResult` should be part of the `prelude`. If not, please add it.

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/auxiliary/text.rs
> +            Cow::Borrowed(text.trim_matches(&WHITESPACE[..]))
Shouldn't `&WHITESPACE` work because `..` selects the whole slice?

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/tag/closing_element.rs
> +                line_suffix_boundary(),
Not sure about this line suffix boundary. Won't this result in `<a>test</a // comment>`?

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/tag/opening_element.rs
> +                    line_suffix_boundary(),
Is it necessary to have two line suffix boundaries here or should instead the formatting differ if there are any comments inside of a JSX opening element (that e.g. breaks it across multiple lines? My impression is that they are now mainly used because you discovered them and it can help to fix stability issue but they should really only be used in cases where it otherwise risks to create invalid syntax.

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +pub fn jsx_space(formatter: &Formatter<JsFormatOptions>) -> FormatElement {
Can we please add some documentation to these methods.

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +            has_non_whitespace = true;
You should be able to early return here because it is `!has_newline`

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +        if c == '\n' {
Nit: `else if`

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +type PredicateFn = Box<dyn Fn(SyntaxNode<JsLanguage>) -> bool>;
Why is it necessary that the predicate fn are boxed?

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/mod.rs
> +    predicates: Vec<Option<PredicateFn>>,
I'm not sure if I understand this predicate function. Is it a list for the `nth` ancestor? @xunilrj looked into this too. 

Please document this method

I think it would be better to pass a slice instead of a vector `&[FnOnce(&SyntaxNode<JsLanguage>)]` to avoid an allocation if the number of predicates is constant (You can then pass `&[Some(...)]`)

2022-05-24 06:41 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +    match_ancestors(
The name is misleading because it isn't really matching. But it might be nice to make this a macro, I just don't know how to make it clear that it is matching the anchestor chain

```
match_anchestors!(node, [
  ..,  // To ignore
  node => node.syntax() == JsSyntaxKind::JS_...,
  node => 
]);
```

2022-05-24 06:44 UTC, MichaReiser commented
!bench_formatter

2022-05-24 09:26 UTC, leops commented on crates/rome_js_formatter/src/utils/mod.rs
> +type PredicateFn = Box<dyn Fn(SyntaxNode<JsLanguage>) -> bool>;
These functions have to be boxed to be stored in a `Vec` since each entry into the array is a closure with its own unique type, however if these closure do not capture any context they could be simplified to `fn()` function pointers instead of boxed `Fn()` traits

2022-05-24 09:26 UTC, leops commented on crates/rome_js_formatter/tests/specs/prettier/js/ternaries/nested-in-condition.js.snap
> +) ? <Element>
Shouldn't this be parenthesized ?

2022-05-24 09:26 UTC, leops commented on crates/rome_formatter/src/format_element.rs
> +            FormatElement::Fill(fill) => fmt
Nit: derive `Debug` on `Fill` instead

2022-05-24 10:39 UTC, ematipico requested changes
Could you please create a separate PR with the `Fill` changes? They are difficult to review, together with JSX elements changes.

2022-05-24 10:39 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +/// Takes in a syntax node because we need to handle both JsxElement and JsxSelfClosingElement
This is not the kind of documentation we want to write 😅 
I think this was a normal comment? 

Maybe the function should be name `should_wrap_jsx_element_in_parens`? As it should handle only JSX elements

2022-05-24 10:39 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +    // We skip 1 for the current node
Could you add the "why" we skip the first one? The comment is not useful like this.
Can't we use `skip` instead? It seems more appropriate

2022-05-24 10:39 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +        .next()
Why are we skipping also the second node too? Should we have a comment explaining it?

2022-05-24 10:39 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +}
How does this state related to `should_wrap_element_in_parens`? In my head "should wrap" seems more a boolean (two options) but instead we have three options. It would be great to have some doc to explain each variant.

2022-05-24 10:39 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +/// which is itself inside a JSX expression child.
Maybe a small snippet might help the developer to understand what's described here. (I have difficulties to visualize the case).

We could move the snippet that is the function inside here?

2022-05-24 10:39 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +pub fn contains_multiple_expressions(children: &JsxChildList) -> bool {
`contains_at_least_two_expressions`? Because one expression is considered "multiple"

2022-05-24 10:39 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +    false
You could use `any` here.

```rs
children.iter().any(|child| {
	...
})
```

2022-05-24 10:39 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +pub fn contains_text(children: &JsxChildList) -> bool {
`contains_meaningful_jsx_text`?

You could use `Iter::any`

2022-05-24 10:39 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +pub fn is_jsx_whitespace_expression(child: JsxAnyChild) -> bool {
It might help to have some documentation here. What's a "whitespace expression"?

2022-05-24 10:39 UTC, ematipico commented on crates/rome_formatter/src/format_element.rs
> +pub struct Fill {
Could you document this new struct, please?

2022-05-24 10:39 UTC, ematipico commented on crates/rome_formatter/src/printer/mod.rs
>          args: PrintElementArgs,
I wonder if this should be a `struct` now? We have too many arguments and having a struct would allow us to document each argument.

2022-05-24 12:06 UTC, MichaReiser commented on crates/rome_formatter/src/printer/mod.rs
>          args: PrintElementArgs,
In my view, this is still fine. `self` is implicit and all arguments have different types.

2022-05-24 16:40 UTC, NicholasLYang commented on crates/rome_formatter/src/format_element.rs
> +/// let expr = fill_elements(space_token(), [token(a), token(b), token(c), token(d)]);
Hmm actually that raises a good point. What should a separator that prints differently do in a fill? Because if we're breaking using the fill, it wouldn't make sense to also break with the separator, no?

2022-05-24 16:55 UTC, NicholasLYang commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +        .next()
I'm confused. When are we skipping the second node?

2022-05-24 19:31 UTC, NicholasLYang commented on crates/rome_js_formatter/src/formatter.rs
> +    /// joins the result together with [join_elements_hard_line].
I don't actually know. I copied this from the original `format_list` doc comment.

2022-05-24 19:32 UTC, NicholasLYang commented on crates/rome_js_formatter/src/formatter.rs
> +        formatted_list.collect()
I thought about this and yeah, that could be an issue, although I suspect rustc might be smart enough to realize that we're collecting a vector that we immediately iterate.

2022-05-24 19:38 UTC, NicholasLYang commented on crates/rome_js_formatter/src/jsx/auxiliary/text.rs
> +            Cow::Borrowed(text.trim_matches(&WHITESPACE[..]))
It doesn't work unfortunately:

```
error[E0277]: the trait bound `CharArrayRefSearcher<'_, '_, 4_usize>: DoubleEndedSearcher<'_>` is not satisfied
    --> crates/rome_js_formatter/src/jsx/auxiliary/text.rs:187:45
     |
187  |             Cow::Owned(format!(" {} ", text.trim_matches(&WHITESPACE)))
     |                                             ^^^^^^^^^^^^ the trait `DoubleEndedSearcher<'_>` is not implemented for `CharArrayRefSearcher<'_, '_, 4_usize>`
     |
note: required by a bound in `core::str::<impl str>::trim_matches`
    --> /Users/nicholas/.rustup/toolchains/1.61.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/str/mod.rs:2052:34
     |
2052 |         P: Pattern<'a, Searcher: DoubleEndedSearcher<'a>>,
     |                                  ^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `core::str::<impl str>::trim_matches`
```

2022-05-24 19:39 UTC, NicholasLYang commented on crates/rome_js_formatter/src/jsx/tag/closing_element.rs
> +                line_suffix_boundary(),
Won't it force a line break after the comment? So we'd get:
```
<a>
  test
</a \\ comment
>
```

2022-05-24 19:43 UTC, NicholasLYang commented on crates/rome_js_formatter/src/jsx/tag/opening_element.rs
> +                    line_suffix_boundary(),
Well if we're following prettier, the line suffix boundaries [make sense](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=0&isTypeScript=false&isJsx=true#bABlAHQAIABhACAAPQAgADwAIAAvAC8AIAB0AGUAcwB0AGkAbgBnAAoAZABpAHYAIAAvAC8AIAB0AGUAcwB0AGkAbgBnACAAMgAKAD4AIAA8AC8AZABpAHYAPgA=). I'm open to other ways, but I'm not really familiar with how we could format differently that wouldn't just emulate a line suffix boundary.

2022-05-24 21:33 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +        .next()
Sorry, my mistake!

2022-05-27 06:55 UTC, MichaReiser commented on crates/rome_js_formatter/src/formatter.rs
> +        formatted_list.collect()
I'm not so sure about this if you look at the latest benchmark results. It would be best to bench this separately to narrow it down if the regressions are because of this change or not.

2022-05-27 06:55 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/lists/child_list.rs
> +            .format_list(node)
Do you want to get the error recovery here. You can otherwise just use `format_all`

```
formatter.format_all(node.iter().formatted())
```

2022-06-01 18:18 UTC, NicholasLYang commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +pub fn contains_text(children: &JsxChildList) -> bool {
Ehh the `Iter::any` version is not that much less verbose
```
    children.iter().any(|child| {
        if let JsxAnyChild::JsxText(jsx_text) = child {
            if let Ok(token) = jsx_text.value_token() {
                if is_meaningful_jsx_text(token.text()) {
                    return true;
                }
            }
        }

        false
    })
```

2022-06-01 19:18 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +pub static WHITESPACE: [char; 4] = [' ', '\n', '\t', '\r'];
Did you mean to add a `const` too? Also, we don't need the `pub`, maybe `pub(crate)`? Also, it seems that this array doesn't contain only white spaces. Maybe we should change its name. Something like `NON_MEANINGFUL_CHARS`?

2022-06-01 19:18 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +/// Checks if a JSX Element should be wrapped in parentheses. Returns a WrapState which
```suggestion
/// Checks if a JSX Element should be wrapped in parentheses. Returns a [WrapState] which
```

2022-06-01 19:18 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +/// only when it's line broken, or should not be wrapped at all.
"it's line broken", is it grammatically correct?

2022-06-01 19:18 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +}
Sure, but please highlight each option and example with each variant, so it's easier to spot for future developers.

2022-06-01 19:18 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/jsx/element.jsx.snap
> +				>
I am not sure this is correct. I am trying to [replicate in prettier](https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=1&typescript=false&jsx=true#CQAJAAkAPABUAGEAYgBQAGEAbgBlAGwAPgAJAAkACQA8AFQAYQBiAFAAYQBuAGUAbAA+AAkACQAJADwAVABhAGIAUABhAG4AZQBsAD4ACQAJAAkAPABUAGEAYgBQAGEAbgBlAGwAPgA8AFQAYQBiAFAAYQBuAGUAbAA+ADwAVABhAGIAUABhAG4AZQBsAD4ACgAJAAkACQAJADwAcAByAGUACgAJAAkACQAJAAkAYwBsAGEAcwBzAE4AYQBtAGUAPQAiAGgALQBzAGMAcgBlAGUAbgAgAGYAZQBlAGYAZgBlAGYAZQBmAGUAZgBlAGYAZQAgAGUAZgAgAGYAZQAgAGYAZQAgAGUAZgAgAGYAZQBmAGUAZgBlAGYAZQBmAGUAIABmAGUAIABmAGUAIABmAGUAIABmAGUAIABmAGUAIABvAHYAZQByAGYAbABvAHcALQB5AC0AcwBjAHIAbwBsAGwAIAB3AGgAaQB0AGUAcwBwAGEAYwBlAC0AcAByAGUALQB3AHIAYQBwACAAdABlAHgAdAAtAHIAZQBkAC0ANQAwADAAIAB0AGUAeAB0AC0AeABzACIACgAJAAkACQAJAD4ACgAJAAkACQAJAAkAewBlAHIAcgBvAHIAcwB9AAoACQAJAAkACQA8AC8AcAByAGUAPgAKAAkACQAJADwALwBUAGEAYgBQAGEAbgBlAGwAPgAJAAkACQA8AC8AVABhAGIAUABhAG4AZQBsAD4ACQAJAAkAPAAvAFQAYQBiAFAAYQBuAGUAbAA+AAkACQAJADwALwBUAGEAYgBQAGEAbgBlAGwAPgAJAAkACQA8AC8AVABhAGIAUABhAG4AZQBsAD4ACQAJAAkAPAAvAFQAYQBiAFAAYQBuAGUAbAA+AA==), but it seems that prettier doesn't break the attribute on a newline, even when there's a high level of indentation.

2022-06-01 19:18 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/jsx/element.jsx.snap
> +}
This involves `JsxChildList`. We should remove it. In fact, the formatting is not correct

2022-06-01 20:03 UTC, MichaReiser commented on crates/rome_js_formatter/src/formatter.rs
> +        formatted_list.collect()
My refactor will solve this for you. Because you can then build the lists yourself and the logic for gracefully recover if the formatting of a node fails is a single helper function. So you may just want till after the refactor. 

But the other question is. Do you need / want the error recovery? We so far mainly applied it in situations where we are sure that we don't introduce new syntax errors and I'm not sure if that's the case when formatting JSX.

2022-06-02 13:56 UTC, NicholasLYang commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +pub static WHITESPACE: [char; 4] = [' ', '\n', '\t', '\r'];
What values are non-whitespace? If anything it's a subset of characters that are considered whitespace. In which case perhaps `JSX_WHITESPACE` would make sense. `NON_MEANINGFUL_CHARS` is not quite right because the characters can be meaningful if they do not contain a newline.

2022-06-02 13:57 UTC, NicholasLYang commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +/// only when it's line broken, or should not be wrapped at all.
I think so? "line broken" here is an adjective, although if it's unclear, I can certainly change it

2022-06-02 19:36 UTC, NicholasLYang commented on crates/rome_js_formatter/src/jsx/tag/opening_element.rs
> +                    line_suffix_boundary(),
They handle single line comments inside an opening element. It's important that they get printed here, as otherwise they might get printed inside the body.

2022-06-03 11:32 UTC, ematipico commented on crates/rome_js_formatter/src/jsx/tag/opening_element.rs
> +                    line_suffix_boundary(),
Could we add a test case so we are covered and we know it's doing what it's supposed to?

2022-06-03 11:36 UTC, ematipico commented on crates/rome_js_formatter/tests/specs/jsx/element.jsx.snap
> +}
Agree to disagree then. 

In my view, the introduced test is not correct. Unless it's explicitly stated somewhere (PR description, comment, TODO, etc.) that this code is there for a reason, then I can't see a reason to keep it.

2022-06-03 11:41 UTC, ematipico requested changes
Almost there. We should add some test case for the edge cases covered in this PR (line suffix boundaries and `WrapState`)

2022-06-03 11:41 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +///    {foo(() => <div> the quick brown fox jumps over the lazy dog </div>)}
Could we add a test case for this snippet?

2022-06-03 11:41 UTC, ematipico commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +pub fn get_wrap_state(node: &SyntaxNode<JsLanguage>) -> WrapState {
Could we add some test case that cover these wrap states? The snippets in the documentation are really helpful, but we should back them with some test.

2022-06-03 21:02 UTC, NicholasLYang commented on crates/rome_js_formatter/src/utils/jsx_utils.rs
> +pub fn get_wrap_state(node: &SyntaxNode<JsLanguage>) -> WrapState {
Added in `element.jsx`

2022-06-08 07:16 UTC, MichaReiser reviewed
Nice work! I would like to better understand why the change inside of the `Printer` is necessary before merging and have a few proposal on how the code could be simplified.

2022-06-08 07:16 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs
> +                };
This should work regardless if the programmer used the preferred quotes or not [Prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBDTBeTAHmwD5gByTcgX0IHpSAdKdLAI3yNOEZE19oMSIADQgIABxgBLaAGdkobACdlEAO4AFFQgUpsqddgCeCsW2XYwAawwBlbAFs4AGWlQ4yAGYG5cc5Y29hJW7gDmyDDKAK7+IHCObHAAJskpLthQYdHYYXAAYhDKjtgwMlnIINjRMBCiIAAWMI6oAOoN0vByIWBwdrqd0gBuncaVYHJmIO5+yjCalmEl3r5xAFZyAB524egAitEQ8CuofmIhyrOVMMYScHJgytJS9RJPsK3SyTANyAAcAAZzmo-K1LBJKm97nBlENPGIAI6HeALSR6KpyAC0HhSKXqyjgSOkBIWuWWSB8pzifkc0kiMWpuzgByOngpqzEMGwbE+31+SAATJzLNJUOEAMIQRzk+JyACs9WifgAKty9FFYmIhrEAJJQNKwOyPZ4wACC+rsN3QJz81GoQA)

`JsStringLiteralExpression` has a `inner_string_text` method (@leops is changing it to return a string slice instead) that gives you the quoted text. You can then test if the inner text matches the empty space.

2022-06-08 07:16 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs
> +                    let r_curly = format_replaced(&r_curly_token, &empty);
I got confused why the final output contains the `space` and the `JsxSpace::default`. I think it would be easier to understand if you rewrite this to 

```
let space = JsxSpace::default();
format_replaced(&str_token, &space); 
```

You can avoid all the temporary variables by inlining the arguments directly inside the `write` call

```
return write!(f, [
  format_replaced(&l_curly_token, &empty_element()), 
  format_replaced(&str_token, &JsxSpace::default()),
  format_repalced(&r_curly_token, &empty_element())
]);
```

2022-06-08 07:16 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/auxiliary/space.rs
> +                if_group_breaks(&format_args![token(jsx_space), soft_line_break()]),
Nit: You can use a hardline_break here. You already know that the group will break.

2022-06-08 07:16 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/tag/opening_element.rs
> +                    type_arguments.format(),
What's the reason you're writing the `type_arguments` and `attributes` if we know that they are `None` / `empty`? 

Overall, I get the impression that it should be possible to simplify this a great deal because the only conditional content seems to be that there must be a `space_token` in front of `attributes` if `attributes`  and `type_arguments` aren't empty

```
write!(f, [
  l_angle_token.format(),
  name.format(),
  type_arguments.format(),
  line_suffix_boundary(),
])?;

if let Some(attributes) = attributes {
    write!(f, [space_token(), attributes, line_suffix_boundary()])?;
}

write!(f, [
    r_angle_token.format()
])
```

2022-06-08 13:55 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs
> +                if str_token.text() == space_str {
I think we need to add a check here to test that the string literal has no comments or skipped trivia attached because comments aren't valid inside of JSX text.

2022-06-21 18:10 UTC, ematipico commented on crates/rome_formatter/src/builders.rs
> +            let item = buffer.into_element();
So I tried to apply your suggestion, but we incur into a regression:

```diff
+`"let array = [1 , 2 ];\n    }\n\n    function func2() {\n        const no_format = () => {};\n    }"`,
-`"let array = [1, 2];\n    }\n\n    function func2() {\n        const no_format = () => {};\n    }"`',
```

The red was is **before** and the green one is **after** applying your suggestion

2022-06-21 18:20 UTC, ematipico commented on crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs
> +                };
It seems that this method `inner_string_text` still returns something different and the methods cover only chars but not strings. For now  I will keep the current implementation

2022-06-21 18:27 UTC, ematipico commented on crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs
> +                if str_token.text() == space_str {
Could you add a test to cover you suggestion? This would help to understand what I am supposed to do

2022-06-21 18:28 UTC, ematipico commented on crates/rome_formatter/src/printer/mod.rs
> +
You were right, I removing this code doesn't trigger any regression

2022-06-21 18:30 UTC, ematipico commented on crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs
> +                    let r_curly = format_replaced(&r_curly_token, &empty);
Does the new code address your feedback?

2022-06-21 18:32 UTC, ematipico commented on crates/rome_formatter/src/builders.rs
> +    pub fn flatten_entries<F, I>(&mut self, entries: I) -> &mut Self
What's your suggestion? What's the best course of action?

2022-06-21 18:34 UTC, ematipico commented
@MichaReiser I addressed some of you comments. If you're able to provide more info on the others, I might be able to implement them and merge this PR.

2022-06-21 18:41 UTC, ematipico commented
!bench_formatter

2022-06-22 06:28 UTC, MichaReiser commented on crates/rome_formatter/src/builders.rs
> +            let item = buffer.into_element();
This doesn't make sense to me. `into_vec` returns a list with the elements and all that line 1664-1668 does is adding all elements while flattening lists. 

You'll have to do some debugging here. I recommend logging `self.items` before/after the change.

2022-06-22 06:28 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs
> +                };
I see. Changing that would be good at some time.

But the feedback that this should also work regardless of the used quote still remains.

2022-06-22 06:28 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs
> +                if str_token.text() == space_str {
```
{ /* comment */ " " }
{
  " "
  /* comment */
}
```

Comments associated with the token itself shouldn't be an issue because `text` includes` the trivia. Ideally, we wouldn't just test for comments but also skipped trivia (I'm unable to come up with an example)

2022-06-22 06:28 UTC, MichaReiser commented on crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs
> +                    let r_curly = format_replaced(&r_curly_token, &empty);
Can we use `format_replaced(&str_token, &JsxSpace::default())`? It has slightly better comment placement.

2022-06-22 06:28 UTC, MichaReiser commented on crates/rome_formatter/src/builders.rs
> +    pub fn flatten_entries<F, I>(&mut self, entries: I) -> &mut Self
Hard to say. I'm not very familiar with this is now implemented. My main concern is that this is hard to reason about. The alternative would be to do something similar to binarish (and assignment etc) where we first map the children into a intermediate struct depending on the ways we want to format the entries and then do the formatting.

However, I don't think we should spend too much time on this right now. But could we add some documentation to discourage the use of this method?

2022-06-22 09:24 UTC, ematipico commented on crates/rome_js_formatter/src/jsx/auxiliary/expression_child.rs
> +                };
Yes, that had been applied and a test added

2022-06-22 14:50 UTC, MichaReiser approved these changes

2022-06-22 14:57 UTC, merged