feature(website): Toggle Tree Style
rome/tools pull request #2563
Opened 2022-05-09 17:46 UTC by NicholasLYang

## Summary

As some have pointed out, the JSON view is not optimal for some situations. This allows users to toggle between the text and JSON view.

## Test Plan

2022-05-09 19:17 UTC, mrkldshv commented on website/playground/src/TreeStyleSelect.tsx
> +			style={{ width: "fit-content" }}
Is it possible to use tailwind css `w-fit` class here?

2022-05-09 19:17 UTC, mrkldshv commented on website/playground/src/TreeStyleSelect.tsx
> +					style={{ display: "none" }}
Is it needed?

2022-05-10 02:44 UTC, IWANABETHATGUY commented
Could you add some screenshots or videos about the change of this pr?

2022-05-10 03:40 UTC, IWANABETHATGUY commented
> Could you add some screenshots or videos about the change of this pr?

Sorry, I didn't see the preview playground

2022-05-10 06:03 UTC, MichaReiser commented
> > Could you add some screenshots or videos about the change of this pr?
> 
> Sorry, I didn't see the preview playground

I would still find it useful to have a proper test summary because it safes me time as a reviewer:
* No need to open the playground and go searching for the new option
* It helps me understand how you tested your change. Thish enables me to make suggestion in case I'm aware of something that needs testing too.
* It acts as documentation for the future. Assume Rome continues to grow and some PR that you haven't been aware of breaks one of your features. Proper test cases are useful in this scenario because it makes it easier for you do understand what changed and indeed, check if what you're looking into was tested or should have been tested.

2022-05-10 06:12 UTC, MichaReiser requested changes
The label seems to be missing on mobile

![image](https://user-images.githubusercontent.com/1203881/167560184-ec89f5f2-355a-4d15-bcfe-1204b036c350.png)

2022-05-10 06:12 UTC, MichaReiser commented on website/playground/src/DesktopPlayground.tsx
> +								setTreeStyle={setTreeStyle}
Events are commonly called `onTreeStyleChanged` to align it with HTML event handlers.

2022-05-10 06:12 UTC, MichaReiser commented on website/playground/src/TreeStyleSelect.tsx
> +	setTreeStyle: Dispatch<SetStateAction<TreeStyle>>;
This type signature may be correct but I would argue that it doesn't help future readers to understand the code. 

```
onTreeStyleChanged(newStyle: TreeStyle): void
```

Is more readable in my view and even less to type (and no need for type imports)

2022-05-10 06:12 UTC, MichaReiser commented on website/playground/src/TreeView.tsx
> +				<ReactJson style={{ zIndex: "10 " }} src={JSON.parse(tree)} />
Why is it needed to set an explicit zIndex?

2022-05-10 06:12 UTC, MichaReiser commented on website/playground/src/types.ts
> +	setTreeStyle: Dispatch<SetStateAction<TreeStyle>>;
Nit: Change to plain function

2022-05-10 06:12 UTC, MichaReiser commented on website/playground/src/utils.ts
> +		setTreeStyle,
This is becoming hard to navigate. Separating this into a single state object with a reducer that allows changing single fields would remove the fields by about 50%. 

Another alternative is to store the values in a context and having a provider + consumer hook.

2022-05-10 14:19 UTC, MichaReiser commented on website/playground/src/DesktopPlayground.tsx
> +								setTreeStyle={setTreeStyle}
The main reason why I would change it is because `TreeView` now makes very specific assumption in what context its used. The signature implies that `setTreeStyle` must set the tree style. It kind of takes the choice from the parent what it want's to do in that case.

2022-05-10 15:31 UTC, NicholasLYang commented on website/playground/src/DesktopPlayground.tsx
> +								setTreeStyle={setTreeStyle}
I'm confused, how does `TreeView` make an assumption about the context in which it's used?

2022-05-10 15:38 UTC, MichaReiser commented on website/playground/src/utils.ts
> +		setTreeStyle,
I don't think you need to add Redux just for that. A simple `useContext` should do to have shared state or change it to `useDispatcher`.

2022-05-10 16:33 UTC, NicholasLYang commented on website/playground/src/SettingsMenu.tsx
> +	setPlaygroundState: Dispatch<SetStateAction<PlaygroundState>>;
@MichaReiser I'm using the complicated type signature here because I'm making use of the `setPlaygroundState(state => ...)` pattern

2022-05-11 10:09 UTC, MichaReiser commented on website/playground/src/utils.ts
> +	const [playgroundState, setPlaygroundState] = useState({
You may want to move this into a lambda so that the initialize code only runs for the first render:

```
const [..] = useState(() => ({....}))
```

2022-05-11 10:09 UTC, MichaReiser commented on website/playground/src/utils.ts
> +		setPlaygroundState((state) => ({ ...state, [field]: param }));
I think what you're trying to replicate is [`useReducer`](https://reactjs.org/docs/hooks-reference.html#usereducer)

The idea is to have one `action` for each field. 

Overall, what you're trying to do here feels complicated with passing down the `setPlaygroundState` and then having a `createSetter`. For someone to understand the code they must first understand what `setPlaygroundState` is, then what `createSetter` does` for something that's otherwise relatively simple. 

I think what you want here is `useContext` which helps you avoid the prop drilling (passing down many props multiple level-deep). 

The provider doesn't need to accept any props because it initializes the state from the URL params. 

They consumer can then expose the state + a method to change a single field 

```
const [{ code }, dispatchPlaygroundAction] = usePlaygroundState();

dispatchPlaygroundAction("change_code", code); 
```

2022-05-11 11:52 UTC, MichaReiser commented
We can do the refactor changes as part of another PR. Please update your test plan with a screenshot for Mobile/Desktop.

2022-05-11 15:21 UTC, NicholasLYang commented on website/playground/src/utils.ts
> +	const [playgroundState, setPlaygroundState] = useState({
Ah yeah my bad, forgot to do that

2022-05-11 20:28 UTC, MichaReiser approved these changes

2022-05-11 21:46 UTC, merged