(website): add a button to copy rome_ir to clipboard
rome/tools pull request #2604
Opened 2022-05-22 09:42 UTC by IWANABETHATGUY

## Summary
add a button to copy rome_ir to clipboard

## Test Plan
No

2022-05-22 09:50 UTC, IWANABETHATGUY commented on website/playground/package.json
> +		"format:rome": "rome format src --write"
Also add another npm scripts `format:rome` because our CI `rome format --ci editors website` use the latest published binary, if we use the latest main branch rome may have some different format result

2022-05-23 06:37 UTC, MichaReiser reviewed
Thanks for this contribution. 

What are the use cases that you see for the new  button? To copy the `document` into a PR summary?

2022-05-23 06:37 UTC, MichaReiser commented on website/playground/package.json
> +		"react-toastify": "^9.0.1"
What's the increase of the bundle size? I'm starting to worry about the size of our playground and the amount of dependencies we have.

2022-05-23 06:43 UTC, IWANABETHATGUY commented
> Thanks for this contribution.
> 
> What are the use cases that you see for the new button? To copy the `document` into a PR summary?
As this issue said, https://github.com/rome/tools/issues/2587. It would be help full when you want to debug `rome_ir` locally, especially when the `IR` is very long that the `IR` textarea need a `scrollbar` to hold it. 
I have been finished a nearly finished here, https://iwanabethatguy.github.io/romeir-to-rs/.

2022-05-23 06:44 UTC, IWANABETHATGUY commented on website/playground/package.json
> +		"react-toastify": "^9.0.1"
How could I get the  bundle size locally?

2022-05-23 10:50 UTC, ematipico commented
I am not sure I understand the use case. Can't you select all the text and copy it? What's the benefit of having a button in this case?

2022-05-23 10:52 UTC, ematipico commented on website/playground/package.json
> +		"format:rome": "rome format src --write"
Maybe this change can its own PR?

2022-05-23 11:45 UTC, IWANABETHATGUY commented
> I am not sure I understand the use case. Can't you select all the text and copy it? What's the benefit of having a button in this case?

This is more like a DX optimization? try to copy this rome IR https://play.rome.tools/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&sourceType=module&treeStyle=0&isTypeScript=false&isJsx=false#aQBtAHAAbwByAHQAIABSAGUAYQBjAHQATAB5AG4AeAAsACAAewAgAEMAbwBtAHAAbwBuAGUAbgB0ACAAfQAgAGYAcgBvAG0AIAAiAEAAYgB5AHQAZQBkAC0AbAB5AG4AeAAvAHIAZQBhAGMAdAAtAHIAdQBuAHQAaQBtAGUAIgA7AAoAaQBtAHAAbwByAHQAIAB7AHAAYQBzAGMAYQBsAEMAYQBzAGUATgBhAG0AZQB9ACAAZgByAG8AbQAgACIAewB7AHAAYQBjAGsAYQBnAGUATgBhAG0AZQB9AH0ALwBjAG8AbQBwAG8AbgBlAG4AdABzAC8AewB7AGsAZQBiAGEAYgBDAGEAcwBlAE4AYQBtAGUAfQB9ACIAOwAKAAoAZQB4AHAAbwByAHQAIABkAGUAZgBhAHUAbAB0ACAAYwBsAGEAcwBzACAARABlAG0AbwAgAGUAeAB0AGUAbgBkAHMAIABDAG8AbQBwAG8AbgBlAG4AdAAgAHsACgAgACAAcgBlAG4AZABlAHIAIAAoACkAIAB7AAoAIAAgACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgACAAIAA8AHYAaQBlAHcAPgAKACAAIAAgACAAIAAgACAAIAA8AHAAYQBzAGMAYQBsAEMAYQBzAGUATgBhAG0AZQAgAHAAYQByAGEAbQBzAEEAPQB7ACcAdABoAGkAcwAgAGkAcwAgAHAAcgBvAHAAcwAnAH0AIAAvAD4ACgAgACAAIAAgACAAIAA8AC8AdgBpAGUAdwA+AAoAIAAgACAAIAApAAoAIAAgAH0ACgB9AAoA, you would somehow know why this is useful, if you think this button is overkill, I would like to close this.

2022-05-23 12:01 UTC, IWANABETHATGUY commented on website/playground/package.json
> +		"react-toastify": "^9.0.1"
> What's the increase of the bundle size? I'm starting to worry about the size of our playground and the amount of dependencies we have.
before:
```bash
vite v2.7.13 building for production...
✓ 843 modules transformed.
dist/assets/favicon.5e112f83.svg               1.10 KiB
dist/assets/rome_playground_bg.e0d4fdb6.wasm   2407.94 KiB
dist/index.html                                0.61 KiB
dist/assets/vendor.f761b4ed.css                3.99 KiB / gzip: 0.59 KiB
dist/assets/index.657b682d.js                  19.84 KiB / gzip: 5.42 KiB
dist/assets/index.c9552bfc.css                 15.29 KiB / gzip: 3.98 KiB
dist/assets/vendor.1cb152e5.js                 1995.12 KiB / gzip: 627.31 KiB

```
after: 
```bash
vite v2.7.13 building for production...
✓ 845 modules transformed.
dist/assets/favicon.5e112f83.svg               1.10 KiB
dist/assets/rome_playground_bg.e0d4fdb6.wasm   2407.94 KiB
dist/index.html                                0.61 KiB
dist/assets/vendor.f761b4ed.css                3.99 KiB / gzip: 0.59 KiB
dist/assets/index.d8debf39.js                  20.23 KiB / gzip: 5.62 KiB
dist/assets/index.e43f5365.css                 31.66 KiB / gzip: 6.18 KiB
dist/assets/vendor.3f43fe8f.js                 2011.86 KiB / gzip: 633.55 KiB

```

increase 10KB after gzip

2022-05-23 12:10 UTC, ematipico commented
I can see the use case and the additional feature, but I can't see adding a new dependency (the toast) to the project. It seems an overkill to me... I mean, it's nice, but I don't think it's necessary for the time being.

2022-05-23 19:58 UTC, NicholasLYang reviewed
Nice! I was considering adding this too, actually for the formatted output more than the IR. Would it be possible to add this to multiple views?

2022-05-23 19:58 UTC, NicholasLYang commented on website/playground/package.json
> +		"react-toastify": "^9.0.1"
The issue by far is the WASM and I'm not sure we can reduce that easily. We can look into it in the future I suppose.

2022-05-23 19:58 UTC, NicholasLYang commented on website/playground/src/DesktopPlayground.tsx
> +	const handleClickCopyRomeIrToClipBoard = () => {
This is a pretty awkward name. Perhaps we can do `handleCopy` or `copyToClipboard`?

2022-05-23 19:58 UTC, NicholasLYang commented on website/playground/src/DesktopPlayground.tsx
> +			.then(
Could we not use an async function for this? It might be cleaner with less nesting.

2022-05-23 21:03 UTC, NicholasLYang commented
Perhaps we could do without the toast? And just show an error inline or even an old school alert

2022-05-24 05:14 UTC, IWANABETHATGUY commented on website/playground/src/DesktopPlayground.tsx
> +			.then(
But `(method) Clipboard.writeText(data: string): Promise<void>` return a `Promise`, I could change it to async function and use`await`, what do you think.

2022-05-24 07:46 UTC, MichaReiser commented
> Perhaps we could do without the toast? And just show an error inline or even an old school alert

Does an old school `title` attribute work? Or does it not get triggered if it gets added after the user hovers with the mouse.

2022-05-24 20:04 UTC, NicholasLYang commented on website/playground/src/DesktopPlayground.tsx
> +			toast("RomeIR has been successfully copy to your clipboard", {});
nit: `"Rome IR has been successfully copied to your clipboard"`

2022-05-25 05:56 UTC, IWANABETHATGUY commented
https://user-images.githubusercontent.com/17974631/170190181-ea8a5a4b-cb32-42e9-8aaa-7a0d71146130.mov

2022-05-25 05:57 UTC, IWANABETHATGUY commented
I remove toast and use this little svg icon instead, it should not have bundle size issue here.

2022-05-25 08:11 UTC, ematipico commented on website/playground/package.json
> +		"format:rome": "rome format src --write ."
I still can see the new command. Can we remove it for now? Ideally we want to use the internal crate as a way to dogfood rome. We don't want to use the npm package.

2022-05-25 08:12 UTC, ematipico approved these changes

2022-05-25 08:12 UTC, ematipico commented on website/playground/src/DesktopPlayground.tsx
> +				"Your browser does not support clipboard, could not copy text",
```suggestion
				"Your browser does not support clipboard, could not copy the text",
```

2022-05-25 08:14 UTC, IWANABETHATGUY commented on website/playground/src/DesktopPlayground.tsx
> +				"Your browser does not support clipboard, could not copy text",
Thanks, forgive my poor English

2022-05-25 08:15 UTC, IWANABETHATGUY commented on website/playground/package.json
> +		"format:rome": "rome format src --write ."
Also add another npm scripts format:rome because our CI rome format --ci editors website use the latest published binary, if we use the latest main branch rome may have some different format result.
This is why I use npm binary, because use local rome format may lead a CI failed which I meet before.

2022-05-25 23:45 UTC, NicholasLYang requested changes
Sorry to keep nitpicking, but the design is a little awkward. The check mark goes away after a few seconds, which is confusing, and leads to flickering if someone clicks the button multiple times in a row.

I'd also lean towards an [clipboard-copy icon](https://heroicons.com) instead of a `Copy to Clipboard` button which takes up width and potentially covers the IR output:

<img width="359" alt="Screen Shot 2022-05-25 at 6 44 04 PM" src="https://user-images.githubusercontent.com/7357863/170387047-11063b7b-242d-423d-a73f-a9b71d522154.png">
.

That said, I'd be open to merging if the flickering issue and my above comments are fixed.

2022-05-25 23:45 UTC, NicholasLYang commented on website/playground/src/DesktopPlayground.tsx
> +								Copy to ClipBoard
Clipboard not ClipBoard

2022-05-25 23:45 UTC, NicholasLYang commented on website/playground/src/DesktopPlayground.tsx
> +							<button className="bg-slate-500 px-4 py-1 text-white absolute right-0 mr-5 flex items-center" onClick={copyToClipboard}>
nit: our other buttons have rounded corners, any chance you could add that?

2022-05-26 05:30 UTC, IWANABETHATGUY commented on website/playground/src/DesktopPlayground.tsx
> +								Copy to ClipBoard
I prefer your icon solution, I replace these text with a copy icon

2022-05-26 05:39 UTC, IWANABETHATGUY commented
https://user-images.githubusercontent.com/17974631/170423484-b84de409-0668-41e8-8a33-f9ce4def0628.mov

2022-05-26 05:41 UTC, IWANABETHATGUY commented
> Sorry to keep nitpicking, but the design is a little awkward. The check mark goes away after a few seconds, which is confusing, and leads to flickering if someone clicks the button multiple times in a row.
> 
> I'd also lean towards an [clipboard-copy icon](https://heroicons.com) instead of a `Copy to Clipboard` button which takes up width and potentially covers the IR output:
> 
> <img alt="Screen Shot 2022-05-25 at 6 44 04 PM" width="359" src="https://user-images.githubusercontent.com/7357863/170387047-11063b7b-242d-423d-a73f-a9b71d522154.png">
> 
> .
> That said, I'd be open to merging if the flickering issue and my above comments are fixed.

2022-05-26 17:14 UTC, NicholasLYang approved these changes

2022-05-26 20:31 UTC, merged