feat(rome_analyze): add a fix file command to the CLI and LSP
rome/tools pull request #2615
Opened 2022-05-25 15:38 UTC by leops

## Summary

This PR adds a new auto-fix workflow to the analysis toolchain, with the following changes:
- The callback injected into the `analyze` entrypoint function for the analyzer now returns an `std::ops::ControlFlow` enum. This lets the callback interrupt the analysis process by returning `ControlFlow::Break(value)`, with the value being returned by the analyze function as an `Option`
- The `Workspace` now has a `fix_file` method that applies all safe fixes to a given file and returns the resulting code. This is implemented by repeatedly calling into `analyze` and breaking for each emitted action signal with `Applicability::Always` to mutate the syntax tree with the code action, then restart the analysis until no more code actions are emitted
- The CLI now has a `fix` command reusing the same traversal infrastructure shared with `format`, `check` and `ci`, and calling `fix_file` on each processed file then writing the resulting code back to the disk
- The Language Server can now emit a "Fix all auto-fixable issues" code action when requested by the language client (for instance when using the "Fix all" command in VS Code), the `TextEdit` backing this action is also generated from the result of `fix_file`
- The code action emitted by the `useSingleVarDeclarator` rule has been marked as "always applicable", and the implementation of the fix has been changed to support variable statements in `JsModuleItemList` as well as `JsStatementList`

## Test Plan

New tests have been added to the CLI test suite to check the `rome fix` command

2022-05-26 08:27 UTC, xunilrj commented on crates/rome_analyze/src/analyzers/use_single_var_declarator.rs
>      }
Would be possible to write some unit tests for each rule? Sometimes is not clear what the rule is flagging or doing.

2022-05-26 08:30 UTC, xunilrj commented on crates/rome_analyze/src/lib.rs
> +/// Utility type to be used as a debault value for the `B` generic type on
"debault" -> "default"

2022-05-26 15:06 UTC, ematipico requested changes
Sorry to interject your PR but I am a little confused about where we are headed with the commands. 

I would like to understand the requirements first (is there been a discussion?). Could you please create an issue first? 

The reason why I am concerned is because I don't have any idea of where we are headed with the commands.

In Rome classic we had:
- `rome ci`, in line with the rewrite
- `rome format`, in line with the rewrite
- `rome check`, **not in line with the rewrite**. The former command applied linting and formatting. `--apply` was the argument to have safe fixed and formatting applied. Like `--write` in the current `rome format --write`

2022-05-26 15:06 UTC, ematipico commented on crates/rome_cli/src/commands/fix.rs
> +/// Handler for the "fix" command of the Rome CLI
Why the `fix` is a command and not an argument of `check` command?

[In rome classic we called it `--apply`]( https://github.com/rome/tools/blob/archived-js/internal/core/server/commands/check.ts#L46-L51) and it was an argument of the command `rome check`. That's because `check` wasn't just about "fixing" the code, but also apply formatting.

2022-05-26 15:41 UTC, leops commented on crates/rome_cli/src/commands/fix.rs
> +/// Handler for the "fix" command of the Rome CLI
Having two different commands was mostly because the check and fix commands had mostly different backing implementations, but I could as well change it to have the fix behavior be implemented by the `check` command with an `--apply` flag instead to be consistent with how the CLI worked in Rome JS

2022-05-30 07:24 UTC, leops commented on crates/rome_analyze/src/lib.rs
> +/// Type alias of [ops::ControlFlow] with the `B` generic type defaulting to [Never]
By default the analysis loop never breaks, so it behaves mostly like `let b = loop {};` and has a "break type" of `!` (the `!` type isn't stable yet so I'm using an empty enum instead but they're identical for this purpose)
In practice it's not really a `loop` but a `for` because it's iterating on all nodes in the syntax tree, so when it reaches the end of the iterator the loop will exit but without producing a value of type `B`: for this reason the `analyze` function returns an `Option<B>` that's set to `Some(B)` if the callback did break, and `None` if the analysis reached the end of the file.
Most consumers of the analyzer will want to analyze the entire file at once and never break, so using `Never` as the type of `B` in this case lets the compiler know the `ControlFlow::Break` branch will never be taken and can be optimized out, as well as completely remove the `return Some` case (`Option<Never>` has a size of 0 and can be elided, while `Option<()>` has a size of 1 as it still need to store a discriminant)

2022-05-30 07:29 UTC, leops commented on crates/rome_analyze/src/lib.rs
> +    mut callback: impl FnMut(&dyn AnalyzerSignal) -> ControlFlow<B>,
Most of the arguments for the analysis have already been pushed into the `AnalysisFilter` struct, and I don't expect to add many more arguments to the `analyze` function at this stage except an eventual `&mut self` to let the analyzer keep some state / cache between runs, along some global-level settings

2022-05-30 07:53 UTC, leops commented on crates/rome_analyze/src/analyzers/use_single_var_declarator.rs
>      }
There are snapshots tests for each rules under `crates/rome_analyze/tests/specs`. I went with snapshots since it captures the diagnostic or code action diff in a readable form close to what the end user will actually see on the CLI, rather than running individual asserts on things like the syntax tree resulting from a refactor since I found it to be easily unclear.

2022-05-30 07:55 UTC, leops commented on crates/rome_analyze/src/lib.rs
> +#[derive(Default, Clone, Copy)]
It is currently possible to filter rules by name (that's used for the snapshot tests to enable only the rule being tested for instance), but since the name of each rules are statically known they can be represented with `&'static str` string slices that implement `Copy`

2022-06-03 15:48 UTC, MichaReiser approved these changes

2022-06-03 15:48 UTC, MichaReiser commented on crates/rome_analyze/src/lib.rs
> +    mut callback: impl FnMut(&dyn AnalyzerSignal) -> ControlFlow<B>,
It may make sense to define a type alias for the `Callback` type and copy some of the explanations you gave in the other comments into its documentation so that future me will know what I need to return in the control flow.

2022-06-03 15:48 UTC, MichaReiser commented on crates/rome_analyze/src/registry.rs
> +        callback: &mut impl FnMut(&dyn AnalyzerSignal) -> ControlFlow<B>,
Nit: Use the type alias here too?

2022-06-03 15:48 UTC, MichaReiser commented on crates/rome_analyze/src/registry.rs
> +        callback: &mut impl FnMut(&dyn AnalyzerSignal) -> ControlFlow<B>,
Nit: Use the type alias here too?

2022-06-03 16:03 UTC, leops commented
> It may make sense to define a type alias for the Callback type and copy some of the explanations you gave in the other comments into its documentation so that future me will know what I need to return in the control flow.

Unfortunately it's not possible to move that declaration in a type alias since `impl Trait` is not stable in type aliases (and it's not possible to alias the `FnMut(&dyn AnalyzerSignal) -> ControlFlow<B>` trait under another name either)

2022-06-03 16:38 UTC, ematipico commented
Maybe we should wait to merge this PR until we do the release next week?

2022-06-03 16:39 UTC, ematipico approved these changes

2022-06-09 15:44 UTC, merged