chore: 🤖 support report as a json file
rome/tools pull request #2626
Opened 2022-05-29 05:55 UTC by IWANABETHATGUY

## Summary

## Test Plan

2022-05-30 12:04 UTC, ematipico commented
Could you add few lines in the description of the PR about:
- why you're adding this to the tests and what kind of problem we're trying to solve;
- a reference to an issue where this new addition was discussed;

2022-05-31 17:03 UTC, yassere reviewed
Thanks for working on this! I agree that it makes sense to have a json option so that changes can be compared more easily in CI.

Currently, this PR duplicates a lot of the report calculations, which makes it more likely to fall out of sync if we modify our metrics in the future. Could you extract those calculations so that the `report_json` and `report_markdown` methods are only directly responsible for the differences that are specific to that report type?

Maybe there could be a method that produces a `PrettierReport` that the individual `report_X` methods know how to print into different formats?

2022-05-31 17:05 UTC, IWANABETHATGUY commented
> 

agree

2022-05-31 17:36 UTC, yassere commented
We could also update the `.gitignore` to ignore `crates/rome_js_formatter/report.*` rather than just the markdown file.

2022-06-01 13:55 UTC, MichaReiser requested changes
Agree with Yasser. I think it would be good to factor out the computation into a helper function that returns the numbers and the markdown/json functions only print the results differently.

2022-06-01 13:55 UTC, MichaReiser commented on crates/rome_js_formatter/tests/prettier_tests.rs
> +struct PeerFileJsonReport {
Is this the report per file? `PerFileJsonReport`

2022-06-20 13:55 UTC, IWANABETHATGUY commented
I have refactored the code, I think I am ready for reviewing.

2022-06-20 15:13 UTC, MichaReiser approved these changes
Thanks for doing the refactor. That should help us to keep the implementations in sync in the future. 

I've a small comment that may help to reduce some code. Let me know if you want to address it before merging or prefer to keep it as is.

2022-06-20 15:13 UTC, MichaReiser commented on crates/rome_js_formatter/tests/prettier_tests.rs
> +#[derive(Debug, PartialEq, Serialize, Default)]
Nit: It could be an option to merge this struct with `SingleFileMetricData` and use `#[serde(skip)] ` on the `diff` field.

You can then also merge the `PrettierCompatibilityMetricData` struct with the `ReportJson` struct

2022-06-20 15:15 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/prettier_tests.rs
> +#[derive(Debug, PartialEq, Serialize, Default)]
That's very useful, thanks.

2022-06-20 15:15 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/prettier_tests.rs
> +#[derive(Debug, PartialEq, Serialize, Default)]
I would like to address this.

2022-06-20 15:21 UTC, IWANABETHATGUY commented on crates/rome_js_formatter/tests/prettier_tests.rs
> +#[derive(Debug, PartialEq, Serialize, Default)]
Done

2022-06-20 15:37 UTC, merged