feat: 🎸 feat/(rome_analyze):no-debugger
rome/tools pull request #2643
Opened 2022-06-02 15:12 UTC by IWANABETHATGUY

## Summary
1. Add new analyze rule `noDebugger` , part of https://github.com/rome/tools/issues/2642

## Test Plan
1. should pass `noDebugger.js`

2022-06-02 15:53 UTC, NicholasLYang commented
We should probably have a guide on proper error message style and conventions. For now, how about we imitate ESLint?
```
Unexpected 'debugger' statement.
```

2022-06-02 15:54 UTC, IWANABETHATGUY commented
I copy from here, https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/noDebugger.md
```
This is an unexpected use of the debugger statement.
```

2022-06-02 16:03 UTC, IWANABETHATGUY commented
> Thanks for this contribution. For the Rome linter we aim to have as many rules as possible coming with automated fixes, Could you add a code action to the rule along with the diagnostic ? Unfortunately the analyzer is still in a very early stage and it's missing many helpers around mutating syntax trees, in this case the fix means removing the debugger statement from it's parent node but I think that might need to be handled through a new helper function to either splice it out from the parent statement list or replace it with an empty statement in the `if(cond) debugger` case for instance

I just found ESlint doesn't have a code action, so I keep the code action as is, which a None. If we want to port other rule, how could I know if it has a code action or not?

2022-06-02 16:47 UTC, leops commented
> I just found ESlint doesn't have a code action, so I keep the code action as is, which a None. If we want to port other rule, how could I know if it has a code action or not?

In #2642 I tried to reference rules that have an auto-fix available when possible, so for instance the source for the `noDebugger` rule there is Rome JS since it has a fixable diagnostic

2022-06-03 09:21 UTC, IWANABETHATGUY commented
> Thanks for this contribution. For the Rome linter we aim to have as many rules as possible coming with automated fixes, Could you add a code action to the rule along with the diagnostic ? Unfortunately the analyzer is still in a very early stage and it's missing many helpers around mutating syntax trees, in this case the fix means removing the debugger statement from it's parent node but I think that might need to be handled through a new helper function to either splice it out from the parent statement list or replace it with an empty statement in the `if(cond) debugger` case for instance

It seems `root.replace_node` can't replace a `DebuggerStatement`  with a `EmptyStatement` due to they have different type.
```rs
pub fn replace_node<N>(self, prev_node: N, next_node: N) -> Option<Self>
where
    N: AstNode<Language = Self::Language>,
    Self: Sized,
```

2022-06-03 09:29 UTC, leops commented
> It seems `root.replace_node` can't replace a `DebuggerStatement` with a `EmptyStatement` due to they have different type.

You can use the `JsAnyStatement` union to replace statements with a different type: `.replace_node(JsAnyStatement::JsDebuggerStatement(prev), JsAnyStatement::JsEmptyStatement(next))`

2022-06-03 09:58 UTC, leops commented on crates/rome_analyze/src/analyzers/no_debugger.rs
> +        let root = root.replace_node(
If the parent node for the debugger statement is a list (`JsStatementList` or `JsModuleItemList`) it's better to simply remove the node

2022-06-03 09:58 UTC, leops commented on crates/rome_analyze/src/analyzers/no_debugger.rs
> +            message: markup! { "Replace with emptyStatement" }.to_owned(),
"emptyStatement" is an internal term users of the linter may not be familiar with, using "Remove debugger statement" as the action message for the quick fix might be easier to understand

2022-06-03 09:58 UTC, leops commented on crates/rome_analyze/tests/specs/noDebugger.js
> +if (foo) debugger
Can we add additional tests for statement list and module item list ?

2022-06-03 09:59 UTC, IWANABETHATGUY commented on crates/rome_analyze/src/analyzers/no_debugger.rs
> +        let root = root.replace_node(
I don't find an api to do that

2022-06-03 10:13 UTC, leops commented on crates/rome_analyze/src/analyzers/no_debugger.rs
> +        let root = root.replace_node(
Right there isn't (yet ?) a method to remove a node from a list, instead it's done by using splice to replace a range with an empty iterator:
```rust
let prev_parent = node.syntax().parent()?;

if JsStatementList::can_cast(prev_parent.kind()) || JsModuleItemList::can_cast(prev_parent.kind()) {
    let index = prev_parent
        .children()
        .position(|slot| &slot == node.syntax())?;

    let next_parent = prev_parent.clone().splice_slots(
        index..=index,
        std::iter::empty(),
    );

    root = JsAnyRoot::unwrap_cast(
        root.into_syntax()
            .replace_child(prev_parent.into(), next_parent.into())?,
    );
}
```

2022-06-03 12:46 UTC, leops approved these changes

2022-06-06 23:19 UTC, NicholasLYang commented
I'm not really clear on why the error message is better. From my perspective it's a little more verbose, but honestly a minor difference. I can go either way.

A bigger issue I have is that there's no explanation or context around why this rule exists. With linting, I think it should be pretty important to have an explanation of why we are not allowing something.

2022-06-07 07:12 UTC, leops commented
> > A bigger issue I have is that there's no explanation or context around why this rule exists. With linting, I think it should be pretty important to have an explanation of why we are not allowing something.
> 
> This is a good point! We should always try to explain why we deny something. Care to venture a suggestion?

This is probably not the best place to discuss this, but besides improving to `RuleDiagnostic` to bring it inline with `rome_diagnostic` (and probably merge all diagnostics into a single unified system eventually) which will allow for richer diagnostics with more and better information, for the release of the analyzer rules will need to come with their documentation. Initially I think this will simply be in the form of documentation pages for each rule on the website, with a `Hyperlink` markup in the diagnostic header to make the code of the lint rule clickable (in terminal clients that support it), but we could also introduce a `rome explain <lint rule>` (similar to the `rustc --explain` command) to let users read the documentation for a rule directly through the command line (in offline usage scenarios for instance)

2022-06-10 13:38 UTC, IWANABETHATGUY commented
This pull request is ready to merge @ematipico

2022-06-10 14:24 UTC, ematipico requested changes

2022-06-10 14:24 UTC, ematipico commented on crates/rome_analyze/tests/specs/noDebugger.js.snap
> +  7 | +   let a = 3;;
There's an additional `;` that should not be there

2022-06-12 13:04 UTC, ematipico commented on crates/rome_analyze/tests/specs/noDebugger.js.snap
> +  2 | + if (foo) ;
Is this correct? We're adding a `;`

2022-06-12 14:54 UTC, leops commented on crates/rome_analyze/tests/specs/noDebugger.js.snap
> +  2 | + if (foo) ;
Yes this change here is correct, the debugger statement is the `consequent` of the parent if statement so it can't be removed (the consequent is required, so it would create an invalid tree with missing children errors), instead it has to be replaced with an empty statement
The same problem exists with other similar statement like for, while, do-while, ... Alternatively we could consider replacing the removed statement with an empty block, or removing the entire if statement (but it may be unsafe if the test condition has side effects)

2022-06-13 12:12 UTC, ematipico commented on crates/rome_analyze/tests/specs/noDebugger.js.snap
> +  2 | + if (foo) ;
> The same problem exists with other similar statement like for, while, do-while, ... Alternatively we could consider replacing the removed statement with an empty block, or removing the entire if statement (but it may be unsafe if the test condition has side effects)

Thank you for the explanation,  I think it makes sense. I am just curious to know how this will play out with different rules. You have to consider that we will have a rule that will be called `lint/js/useBlockStatements`, which will add blocks instead of empty statements. 

I wonder now if we should prepare a test suite to actually run multiple rules on the same snippet and see how it will be the end result? 

<img width="398" alt="Screenshot 2022-06-13 at 09 12 03" src="https://user-images.githubusercontent.com/602478/173350832-15cce2e4-beb2-42ff-a760-e30dec922e47.png">

2022-06-13 12:13 UTC, ematipico approved these changes

2022-06-13 15:55 UTC, leops requested changes

2022-06-13 15:55 UTC, leops commented on crates/rome_analyze/src/analyzers/no_debugger.rs
> +        })
```suggestion
        Some(RuleDiagnostic::warning(
            node.syntax().text_trimmed_range(),
            markup! {
                "This is an unexpected use of the "<Emphasis>"debugger"</Emphasis>" statement."
            },
        ))
```

2022-06-13 18:57 UTC, leops approved these changes

2022-06-13 18:58 UTC, merged