feat(rome_analyze): implement the validTypeof rule
rome/tools pull request #2649
Opened 2022-06-03 15:20 UTC by leops

## Summary

This PR implements the [valid-typeof](https://eslint.org/docs/rules/valid-typeof) rule from ESLint verifying the result of `typeof` unary expressions is being compared to a valid expression (either a string literal that's a valid type name or another `typeof` expression)

## Test Plan

I added test cases for the rule based on the examples found in the ESLint docs

2022-06-03 16:07 UTC, MichaReiser approved these changes

2022-06-03 16:07 UTC, MichaReiser commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +impl Rule for ValidTypeof {
Please add some documentation of what the rule is testing for.

2022-06-03 16:07 UTC, MichaReiser commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +pub(crate) enum ValidTypeof {}
An empty enum... that's interesting. What's the reason behind using an empty enum over `struct ValidTypeof;`

2022-06-03 16:07 UTC, MichaReiser commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +                        .trim_end_matches(['"', '\''])
You can do `literal.inner_string_text()`

2022-06-03 16:07 UTC, MichaReiser commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +                if let JsAnyLiteralExpression::JsStringLiteralExpression(literal) = literal {
what if the right-hand side is a template literal? 

```
>> typeof "a" ===  `string`
true
```

2022-06-03 16:14 UTC, ematipico requested changes
This rule should follow the naming convention: https://github.com/rome/tools/blob/main/CONTRIBUTING.md#naming-patterns

Hence, it should be called `useValidTypeof` or `noInvalidTypeof`

2022-06-03 16:18 UTC, ematipico commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +            message: markup! { "Compare the result of `typeof` with a valid type name" }.to_owned(),
This message should provide the list valid of type names as a suggestion. Essentially, we should suggest the user how can we fix the error

2022-06-03 16:18 UTC, ematipico commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +                "Invalid typeof comparison value"
We should tell **why** the comparison is invalid.

```suggestion
                "Invalid `typeof` comparison value"
```

2022-06-03 16:20 UTC, MichaReiser commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +            message: markup! { "Compare the result of `typeof` with a valid type name" }.to_owned(),
Do we have a max message length? Listing all potential types may get rather long.

2022-06-03 16:44 UTC, ematipico commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +            message: markup! { "Compare the result of `typeof` with a valid type name" }.to_owned(),
We do, we had a algorithm in Rome classic, here's the diagnostic was: https://github.com/rome/tools/blob/archived-js/internal/compiler/lint/rules/a11y/useValidLang.test.md#3

2022-06-03 16:46 UTC, ematipico commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +            message: markup! { "Compare the result of `typeof` with a valid type name" }.to_owned(),
This is the function in charge of creating suggestions: https://github.com/rome/tools/blob/archived-js/internal/diagnostics/helpers.ts#L27

2022-06-07 12:17 UTC, leops commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +pub(crate) enum ValidTypeof {}
It doesn't make a huge difference, we just need a type to implement the `Rule` trait on but that type will never be instantiated and this is made clear by using a type that actually can't be instantiated at all (while an empty struct can be instantiated, but will be zero-sized)

2022-06-07 12:48 UTC, leops commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +                if let JsAnyLiteralExpression::JsStringLiteralExpression(literal) = literal {
This is currently unsupported, I could probably add some code to handle the simple case with a single chunk / no interpolation, but it may not be needed eventually depending on how this rule interacts with the [noUnusedTemplateLiteral](https://github.com/rome/tools/blob/archived-js/website/src/docs/lint/rules/js/noUnusedTemplateLiteral.md) rule

2022-06-07 12:57 UTC, leops commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +            message: markup! { "Compare the result of `typeof` with a valid type name" }.to_owned(),
Here the message is attached to a code action, meaning it will ultimately be displayed either as the name of a quick fix in the editor:
![code_action](https://user-images.githubusercontent.com/1895119/172384772-b01f1f20-b2ed-4bd9-8402-9f7bc598964b.png)
Or alongside a diff of the actual change to the user like this:
```
Compare the result of `typeof` with a valid type name

12    | - typeof foo === undefined
   12 | + typeof foo === "undefined"
```
So the message is meant more as a general explanation of what the actual action is doing, rather than an exhaustive suggestion on how to fix the code

2022-06-07 13:21 UTC, leops commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +                "Invalid typeof comparison value"
To make a note on diagnostics here, in the context of a Rust-like diagnostic with rich codespan information it would be possible to attach context-specific messages to the actual label:
```
error[useValidTypeof]: Invalid typeof comparison value
   ┌─ useValidTypeof.js:10:1
   │
10 │ typeof bar !== "fucntion"
   │                ^^^^^^^^^^ not a valid type name
   
error[useValidTypeof]: Invalid `typeof` comparison value
   ┌─ useValidTypeof.js:14:1
   │
14 │ typeof bar == Object
   │               ^^^^^^ not a string literal
```
However I'm not entirely certain how to represent this information in the context of the LSP where we have a lot less control on how these diagnostics are rendered

2022-06-07 13:30 UTC, MichaReiser commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +                        .trim_end_matches(['"', '\''])
There are no current usages of it. Should we change the implementation to return a string slice instead? Sounds like it's the more practical.

2022-06-07 13:39 UTC, leops commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +                        .trim_end_matches(['"', '\''])
Yes that would make sense, the only downside I see to that is that a `&str` slice doesn't have any associated range information but it shouldn't be too much of a problem

2022-06-07 13:48 UTC, ematipico commented on crates/rome_analyze/src/analyzers/valid_typeof.rs
> +                "Invalid typeof comparison value"
Probably we should provide two messages/diagnostics: one for the CLI/CI and one for the LSP

2022-06-08 17:00 UTC, ematipico approved these changes

2022-06-09 16:22 UTC, merged