feat/(rome_analyze): noUnusedTemplateLiteral rule
rome/tools pull request #2653
Opened 2022-06-04 06:39 UTC by IWANABETHATGUY

## Summary
1. add new analysis rule `noUnusedTemplateLiteral`

## Test Plan
1. should pass new test file `noUnusedTemplateLiteral.js`

2022-06-06 12:33 UTC, ematipico approved these changes

2022-06-06 12:33 UTC, ematipico commented on crates/rome_analyze/src/analyzers/no_unused_template_literal.rs
> +        // We want to test if any templateElement has violated rule that can convert to string literal
Here you mention "rule" but this "rule" is not explained anywhere. Maybe we should describe this rule in a doc comment of `can_convert_to_string_literal`?

2022-06-10 12:34 UTC, ematipico reviewed
Looks good to me. You need to run the codegen command: https://github.com/rome/tools/blob/main/CONTRIBUTING.md#cargo-codegen-analyzer

2022-06-13 15:01 UTC, IWANABETHATGUY commented
@ematipico , This pull request has been approved three days long, could it be merged?

2022-06-13 15:04 UTC, ematipico commented
I leave the merging to @leops because he's still working on the internal infrastructure.

2022-06-13 15:53 UTC, leops requested changes
The diagnostics just need to be updated to the latest changes and we'll be able to merge it

2022-06-13 15:53 UTC, leops commented on crates/rome_analyze/src/analyzers/no_unused_template_literal.rs
> +        })
```suggestion
        Some(RuleDiagnostic::error(
            node.range(),
            markup! {
                "Do not use template literals if interpolation and special-character handling are not needed."
            },
        ))
```

2022-06-13 18:57 UTC, leops approved these changes

2022-06-13 18:58 UTC, merged