feat(rome_rowan): implement `DoubleEndedIterator` for node lists
rome/tools pull request #2672
Opened 2022-06-07 15:51 UTC by ematipico

## Summary

This PR adds the ability to consume an `AstSeparatedList` from the back by implementing `DoubleEndedIterator`.

The reason why I implemented this is because there have been cases where I needed to retrieve the last elements of a list. This will be useful, for example, inside the formatter when implementing the formatting of call arguments.

## Test Plan

Created new tests to cover the cases

2022-06-07 16:03 UTC, MichaReiser commented
!bench_formatter

2022-06-08 06:43 UTC, MichaReiser requested changes

2022-06-08 06:43 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +}
Nit: Maybe implement `nth_back` too?

2022-06-08 06:43 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +        let slot = self.slots.next_back();
You can use the `try` operator here so that the implementation returns immediately if you reached the start of the list
```suggestion
        let slot = self.slots.next_back()?;
```

2022-06-08 06:43 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +                        let node = match self.slots.next_back()? {
Using the try operator here isn't safe because you then swallow the separator if there's no preceding node. I don't think this should ever be the case but it's better to be explicit about it.

2022-06-08 06:43 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +                        Err(SyntaxError::MissingRequiredChild),
I don't think this is correct. Let's say you have `[node1, missing_sep node 2]`. Only the separator between `missing_sep` and `node` is missing but `missing_sep` isn't. So we should still return it.

2022-06-08 06:43 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +        let (node, separator) = match slot {
I think it would help to structure the code similar to the `next` implementation:

```
let token = match self.slots.next_back()? {
  ...
}

let node = match self.slots.next_back() {
  .. 
}

Some(AstSeparatedElement {
  node, 
  trailing_separator: separator
})
```

It reduces the nesting which simplifies reasoning about the code AND someone who needs to make a change to one method will recognise the structure and know how they need to make the change to the other method too.

2022-06-08 06:43 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +    fn separated_list_backwards_with_separator() {
Can we please add some test cases for malformed lists. Similar to `separated_with_two_successive_separators`, `separated_with_leading_separator`, and `separated_with_two_successive_nodes`

2022-06-08 06:43 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +        assert_eq!(element, None);
Adding a helper similar to `assert_elements` for asserting the elements from the back could greatly improve the readability of the tests.

2022-06-08 08:37 UTC, xunilrj commented
Not sure we are implementing the ```std::iter::DoubleEndedIterator``` contract correctly. For example

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8e1cc1b755357cdd5546c3d270335d4d
```rust 
fn main() {
    let list = vec![1,2,3,4];
    
    let mut iter = list.iter();
    println!("{:?}", iter.next());
    println!("{:?}", iter.next_back());
    
    println!("{:?}", iter.next());
    println!("{:?}", iter.next_back());
    
    println!("{:?}", iter.next());
    println!("{:?}", iter.next_back());
}
```

outputs
```
Some(1)
Some(4)
Some(2)
Some(3)
None
None
```

This happens because: 

> It is important to note that both back and forth work on the same range, and do not cross: iteration is over when they meet in the middle.
https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html


I tried the following test and failed:
```rust
 #[test]
  fn double_iterator_meet_at_middle() {
      let list = build_list(vec![
          (Some(1), Some(",")),
          (Some(2), Some(",")),
          (Some(3), Some(",")),
          (Some(4), None),
      ]);

      let mut iter = list.elements();

      let element = iter.next().unwrap();
      assert_eq!(element.node().unwrap().text(), "1");
      let element = iter.next_back().unwrap();
      assert_eq!(element.node().unwrap().text(), "4");

      let element = iter.next().unwrap();
      assert_eq!(element.node().unwrap().text(), "2");
      let element = iter.next_back().unwrap();
      assert_eq!(element.node().unwrap().text(), "3");

      assert!(iter.next().is_none());  // line 701
      assert!(iter.next_back().is_none());
  }
```

and failed with:
```
---- ast::tests::double_iterator_meet_at_middle stdout ----
thread 'ast::tests::double_iterator_meet_at_middle' panicked at 'assertion failed: iter.next().is_none()', crates\rome_rowan\src\ast\mod.rs:701:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2022-06-08 10:51 UTC, ematipico commented
> It is important to note that both back and forth work on the same range, and do not cross: iteration is over when they meet in the middle.
[doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html](https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html)

Damn I missed that part! Thank you for looking into this!

2022-06-08 10:54 UTC, ematipico commented on crates/rome_rowan/src/ast/mod.rs
> +        let slot = self.slots.next_back();
I can't here, because I might be at the end of the list where the separator isn't there and we have a node instead: `vec![Some(1), Some(","), Some(1)]`.

2022-06-08 10:58 UTC, ematipico commented on crates/rome_rowan/src/ast/mod.rs
> +        let (node, separator) = match slot {
You think I haven't tried? :) 
Using the same code structure from `next` won't fit `next_back` because we are facing different situations that `next` doesn't have. The situation is mainly the fact that consuming a token from the back, especially at the very beginning, can yield a separator or a node and we have to check it (and it's not an error).

2022-06-08 11:23 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +        let (node, separator) = match slot {
> You think I haven't tried? :)

No, I didn't think that but glad you tried. I wasn't aware of this case. Thanks for explaining.

2022-06-08 19:47 UTC, ematipico commented
Please re-read the description, there's more context now

2022-06-09 11:25 UTC, MichaReiser reviewed
Looking good. I'm a bit surprised by the amount of special case handling that is necessary and are wondering if we can simplify that a bit. But you will know better because you looked into all edge cases

2022-06-09 11:25 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +        let mut slots = self.slots.clone().rev().peekable();
What's the reason that you need to peek the next element here? The syntax factory should guarantee that each element takes two slots, with the sole exception of the last node. It should, therefore be safe to retrieve the next node?

2022-06-09 11:25 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +                // panic!("Malformed list, node expected but found token {:?} instead. You must add missing markers for missing elements.", token);
I think this case should panic because what I understand from your comment is that this is the case when the trailing separator is missing (marked with a missing marker).

2022-06-09 11:25 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +            ),
This is a malformed case in my view. There shouldn't be an element if both element and the token are missing.

2022-06-09 11:25 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +
I'm a bit surprised that there are so many additional rules that must be handled when navigating backwards where significantly fewer cases are required when navigating forwards. 

The situations I see:

* The last element is a node -> Return the node
* In all other cases, the last element must be the separator token or missing. 
* After the separator, the next element must be the node

```rust
let separator = match self.inner.next_back()? {
  SyntaxSlot::Node(node) => {
    return AstSeparatedElement { node: Ok(Some(separator)), separator: Ok(None)
  },
  SyntaxSlot::Empty => {
    Err(Missing)
  },
  SyntaxSlot::Token(separator) => Ok(separator)
};

let node = match self.inner.next() {
  ...
}
```

The one case I'm not sure about is about the last case. Do we need some internal state tracking if the iterator is positioned at the last element because if not, then the case is invalid.

2022-06-09 11:25 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +        let element = iter.next_back().unwrap();
Can we rewrite these tests to use the new utility functions?

2022-06-09 11:25 UTC, MichaReiser commented on crates/rome_rowan/src/cursor/node.rs
> +            < self.parent.green().slots().len()
My understanding is that `next` and `next_back` need to return `None` once the `back` and `front` position crossed in which case testing for `self.front_next_position > self.back_next.position` should be sufficient, I think

2022-06-09 12:31 UTC, ematipico commented on crates/rome_rowan/src/cursor/node.rs
> +            < self.parent.green().slots().len()
Yes, this is correct if `back_next_position` would start from end of the iterator (its value would be `slots.len() - 1`). But this means that I would need to make `back_next_position` a `i32` because `0` is a correct value.

So I decided to give `back_next_position` the value of `0` and use the [`nth_back`](https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html#method.nth_back) when picking the next slot. This simplified by a lot the internal logic by making the implementation of `next` and `next_back` almost the same. The only caveat is the line that you pointed!  (I made the same mistake when I wrote it 😆 )

2022-06-09 12:35 UTC, ematipico commented on crates/rome_rowan/src/ast/mod.rs
> +        let mut slots = self.slots.clone().rev().peekable();
It's exactly because of the last node that we can't consume twice regardless.

When consuming the iterator from the front, the operation is simple because the first node of each tuple **must be a node** and the second **can be a separator or be empty**. This means that once we consume the entire iterator keep getting `None` regardless and we safely process the information.

From the back, unfortunately we don't have  the luxury to consume the iterator twice regardless. Let's get these two examples:

```
// 1
["1", separator, "2", separator, "3"]
// 2
["1", separator, "2", separator, "3", separator]
```

If we consume `// 1` from the front with `.next` we should get 3 items, where the last one is `("3", missing_sep)`. This means that we should have the same result when consuming items from the back. If we decided always consume two items at each iteration, we would receive something like this:
```
[separator, "3"] -> [separator, "2"] -> ["1"]
```

Which is not correct, that's why I had to make the second slot a peekable and make to consume the item only when there aren't edge cases.

2022-06-10 16:17 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +        let mut slots = self.slots.clone().rev().peekable();
Shouldn't it be sufficient to match on the first element

* Node -> You can assume that it was the last element because the list must otherwise have an empty element for the separator -> Return immediately 
* Empty -> The separator is missing, call next again
* Token -> Separator is present, call next again

You can then match on the next value: 
* `None` -> Uhm, that's an invalid state, there should have been a node
* Some(Token) -> Invalid list, should have been a node
* Some(Node) -> Ok 
* Some(Empty) -> Err(Missing Node)

I personally find this a bit easier to reason about the code.

2022-06-10 16:17 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +
> Using the try operator would return None and this is not correct, because the end of a list might have a node with a missing trailing separator.

I don't understand why this is so. If calling `self.inner_next_back()` returns `None`, then calling it again will always return from that point onwards (knowing that the inner iterator is a `FusedIterator`). 

A missing separator should have been marked by the syntax factory with `Missing` and shouldn't return `None`.

2022-06-10 16:17 UTC, MichaReiser commented on crates/rome_rowan/src/cursor/node.rs
> +            < self.parent.green().slots().len()
Would you mind adding some documentation to `back_next_position` that it's the offset from the end and not the next slot's index.

2022-06-10 16:23 UTC, ematipico commented on crates/rome_rowan/src/ast/mod.rs
> +
OK, that helps a lot, thank you. Unfortunately that wasn't clear to me

2022-06-10 18:01 UTC, ematipico commented
@MichaReiser I addressed your concerns, your help was really helpful, thank you! Now the code should be clear and better to read. I believe we are ready to ship it!

2022-06-10 18:02 UTC, ematipico commented on crates/rome_rowan/src/cursor/node.rs
> +            < self.parent.green().slots().len()
It was already there, I added a bold 😆

2022-06-11 13:43 UTC, MichaReiser approved these changes
Awesome!

2022-06-11 20:16 UTC, merged