feature(parser): JSX support in .js files
rome/tools pull request #2674
Opened 2022-06-07 16:49 UTC by NicholasLYang

## Summary
Addresses #2625. Because TypeScript allows JSX in `.js` files by default, we allow the same.

## Test Plan
The existing tests for JSX should suffice.

2022-06-08 06:03 UTC, MichaReiser requested changes

2022-06-08 06:03 UTC, MichaReiser commented
!bench_parser

2022-06-08 16:59 UTC, NicholasLYang commented on crates/rome_analyze/tests/specs/flipBinExp.js
> -const a = b <<< c;
It now parses as `const a = b << <c`, i.e. as if `c` is a JSX element that is not terminated. It seemed to me that the analyzer would not be able to give a diagnostic for such a case. Do you think it should?

2022-06-09 07:04 UTC, MichaReiser commented on crates/rome_analyze/tests/specs/flipBinExp.js
> -const a = b <<< c;
Hmm, I think this is incorrect. We should fix this in the parser

2022-06-14 06:39 UTC, MichaReiser commented on crates/rome_analyze/tests/specs/flipBinExp.js
> -const a = b <<< c;
The issue here is that `<<<` isn't a valid binary expression operator, it should be `>>>`

2022-06-14 06:46 UTC, MichaReiser approved these changes
I address the review feedback. We should be good to merge now

2022-06-14 06:46 UTC, merged