feat(rome_js_analyze): preferShortHandType
rome/tools pull request #2745
Opened 2022-06-20 16:22 UTC by IWANABETHATGUY

## Summary
1. Resolved #2744 

## Test Plan
1. cargo test

2022-06-20 16:29 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/useShorthandArrayType.ts
> +let valid: Array<foo>;
These are valid cases:

```ts
let valid: Array<Foo | Bar>;
let valid: Array<keyof Bar>;
let valid: Array<foo | bar>;

```

2022-06-21 10:04 UTC, IWANABETHATGUY commented on xtask/lintdoc/src/main.rs
>          } else {
This is used for telling author which inline doc caused an issue

2022-06-21 17:15 UTC, ematipico approved these changes

2022-06-21 17:30 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/use_shorthand_array_type.rs
> +                }
Wouldn't it be better to use 

```rs
if let Some(type_arguments) = ty.type_arguments() {
	if  is_array_reference(&ty).unwrap_or(false) {
		convert_to_array_type(ty.type_arguments())
	}
}
```

So we extract and check `type_arguments` without using the unsafe `unwrap`

2022-06-21 17:30 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/use_shorthand_array_type.rs
> +        for param in type_arguments.ts_type_argument_list().iter() {
I believe we can use `filter_map` here, so we don't need to create the new vector `array_types`. 

The reason why Rome classic did have a separate array is mostly because there's no `filterMap` there 😛

2022-06-22 14:51 UTC, ematipico requested changes
CI is failing

2022-06-22 14:58 UTC, ematipico approved these changes

2022-06-22 15:00 UTC, IWANABETHATGUY commented
> CI is failing

Addressed

2022-06-24 09:18 UTC, leops approved these changes

2022-06-24 16:27 UTC, IWANABETHATGUY commented
@ematipico , I think this pr is ready to merge.

2022-06-27 07:25 UTC, merged