feat(rome_rowan): expose the kind of AstNode as a constant
rome/tools pull request #2774
Opened 2022-06-24 10:23 UTC by leops

## Summary

This PR adds a new `KIND_SET` associated constant to the `AstNode`, representing the set of `SyntaxKind` values that can be cast into this node (the `can_cast` function would return true for these values). This allows code to statically list out all node types that match a certain node type, to optimize query matching in the analyzer for instance.

## Test Plan

This is mostly a codegen change, and with most operations on `SyntaxKindSet` being `const` almost all these operations are checked at compile time (adding enough variants to `JsSyntaxKind` to make it overflow the 64 bytes of the bitfield would cause a compilation error for instance).
The changes to the rule registry are tested indirectly through the integration tests of the analyzer, ensuring that queries are still matched correctly

2022-06-24 10:34 UTC, MichaReiser approved these changes

2022-06-24 10:34 UTC, MichaReiser commented on crates/rome_rowan/src/ast/mod.rs
> +pub struct SyntaxKindSet<L: ?Sized + Language>([u128; 4], PhantomData<L>);
Would the solution be to increase the array length if it happens that we encounter a union that has more than 32 (4*128/32) variants?

2022-06-24 10:34 UTC, MichaReiser commented on crates/rome_rowan/src/green.rs
> +    pub(crate) const fn as_bits(self) -> [u128; 4] {
Can you add some documentation to this part that explains what is happening here? I wouldn't know what to make of this function or how to change it in the future.

2022-06-24 11:52 UTC, leops commented on crates/rome_rowan/src/ast/mod.rs
> +pub struct SyntaxKindSet<L: ?Sized + Language>([u128; 4], PhantomData<L>);
The length of the array would need to be increased if any `SyntaxKind` ever got more than 512 (128*4) variants, currently the largest one is `JsSyntaxKind` with 481 variants

2022-06-24 12:51 UTC, leops commented on crates/rome_rowan/src/green.rs
> +    pub(crate) const fn as_bits(self) -> [u128; 4] {
I've inlined the `as_bits` function in the 2 places it's used in `SyntaxKindSet` to make it easier to understand what it's doing in context. I also modified how the function is implemented to make easier to extend the size of the bitfield without having to introduce additional branches (I wasn't sure Rust's constant folding would be able to statically check it for error like this, but it turned out to work just as well)

2022-06-24 13:20 UTC, ematipico requested changes
Could you please add some example, somewhere, of how to use this new feature?

2022-06-24 13:20 UTC, ematipico commented on crates/rome_analyze/src/registry.rs
> +struct KindRules<L: Language> {
What's a `KindRules`? Should it be a `RuleKind`? Could you add some doc?

2022-06-24 14:39 UTC, ematipico commented
> > Could you please add some example, somewhere, of how to use this new feature?
> 
> The new feature is being used in [registry.rs](https://github.com/rome/tools/blob/7ff535932b53e1a3b294646a166c9a5bb271a632/crates/rome_analyze/src/registry.rs#L29) to store rules in a flat vector, with each index of the vector being associated with the corresponding `RawSyntaxKind` value allowing for constant-time lookup of lint rules during traversal. That's a real-world use case though, I don't know if a more synthetic example would be easier to understand

That's exactly why I think having a documented example would be beneficial for us. I looked at it and honestly I didn't understand some parts of it (for example the `.to_raw().0` seemed quite hacky, and a documentation that explains it might help).

2022-06-27 08:11 UTC, ematipico commented on crates/rome_analyze/src/registry.rs
> +struct KindRules<L: Language> {
@leops I think you missed this comment. I believe this should be `RulesKind`. `KindRules` had a different meaning 😝

2022-06-27 08:53 UTC, leops commented on crates/rome_analyze/src/registry.rs
> +struct KindRules<L: Language> {
Interesting, I added some documentation to this struct but it's not showing in the code block attached to the comment in the conversation tab.
I think `KindRules` feels more natural to read left-to-right since it maps a single `SyntaxKind` to multiple `Rule`, whereas `RulesKind` feels more ambiguous: the `-Kind` suffix is generally used for enums, so it could be understood as "the kind of a collection of rules" when it's in fact a struct holding said collection of rules

2022-06-27 10:49 UTC, ematipico commented on crates/rome_analyze/src/registry.rs
> +struct KindRules<L: Language> {
It's more about english grammar here 😅 "kind rules" is like "kind person", which is the adjective to address a person that is "sweet, gentle, etc.", which is not the meaning we want to have. I'd suggest to find another wording

2022-06-27 12:08 UTC, leops commented on crates/rome_analyze/src/registry.rs
> +struct KindRules<L: Language> {
I guess then `SyntaxKindRules` would work, it makes it clearer that "kind" refers to the `SyntaxKind` trait

2022-06-28 07:03 UTC, merged