feat: 🎸 init
rome/tools pull request #2803
Opened 2022-07-01 05:45 UTC by IWANABETHATGUY

## Summary

## Test Plan

2022-07-05 06:20 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/utils.rs
> -use rome_js_syntax::JsAnyExpression;
`is_boolean_literal` isn't used anywhere so I removed it.

2022-07-05 15:44 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_template.rs
> +        })
Done

2022-07-06 14:08 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/Cargo.toml
> +snailquote = "0.3.1"
Done

2022-07-07 10:44 UTC, leops commented on crates/rome_js_analyze/src/analyzers/use_template.rs
> +        if binary_expr.parent::<JsBinaryExpression>().is_some() {
Doesn't this mean the rule would not trigger for `1 + "2" - 3` ?

2022-07-07 11:48 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_template.rs
> +        if binary_expr.parent::<JsBinaryExpression>().is_some() {
Would trigger on `1 + "2" - 3`, but would not trigger on `"2" - 3`

2022-07-07 11:54 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_template.rs
> +        if binary_expr.parent::<JsBinaryExpression>().is_some() {
I think I misunderstood your advice in https://github.com/rome/tools/pull/2803#discussion_r913922567

2022-07-07 12:14 UTC, leops commented on crates/rome_js_analyze/src/analyzers/use_template.rs
> +        if binary_expr.parent::<JsBinaryExpression>().is_some() {
What I had in mind was to return `None` if the parent node is a binary expression that would emit a signal (`UseTemplate::run` returns `Some`), but skipping the match for all parent binary expressions will result in false negatives

2022-07-07 14:12 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_template.rs
> +        if binary_expr.parent::<JsBinaryExpression>().is_some() {
But how could I know if parent emit a `Some` signal by `UseTemplate::run` ?

2022-07-08 06:07 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_template.rs
> +        if binary_expr.parent::<JsBinaryExpression>().is_some() {
This method is nice, but it increases the times to execute `run` method, although it is still `O(n)`. 
But `run` will execute `2 * n` times compare to `n` times before. We may want to optimize this until we found this is a performance bottleneck in production usage.

2022-07-08 06:09 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_template.rs
> +        if binary_expr.parent::<JsBinaryExpression>().is_some() {
Done

2022-07-08 08:38 UTC, leops approved these changes

2022-07-08 16:19 UTC, IWANABETHATGUY commented
@ematipico , I guess this pull request is ready to merge, I have addressed all issues. Would you mind having a look?

2022-07-08 16:25 UTC, ematipico requested changes
A couple of things before merging:
1. could you rebase your fork? we fixed the CI failures and it should be fine now;
2. could you add invalid case where strings have spaces?
	  
  An example:
	  ```js
	  0;
	  foo() + " bar"; // before
	  `${foo()} bar`; // after
	  ```

2022-07-08 16:56 UTC, IWANABETHATGUY commented
> 

I have rebased the main branch and added an extra test case.

2022-07-11 07:40 UTC, ematipico approved these changes

2022-07-14 06:14 UTC, IWANABETHATGUY commented
@xunilrj would you mind helping review this pr?

2022-07-14 06:59 UTC, xunilrj commented on crates/rome_js_analyze/src/utils.rs
> +pub enum MyError {
Can we have a better name?

2022-07-14 07:05 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/js/use_template.rs
> +            result.extend(collect_binary_add_expression(&left)?);
I think you can ```result.append(...)``` here, which will be faster.
SAme thing below.

2022-07-14 07:09 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/js/use_template.rs
> +                // drop the trivia of original expression make the generated `JsTemplate` a little nicer, if we don't do this
Can we drop trivia if they are comments?

2022-07-14 07:13 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/js/use_template.rs
> +            if interpret_escaped_string(&string_literal.text())
How about moving all this to a function and calling it here with a clearer name?

```rust
if has_newline_or_tick(...) {
    ...
}
```

2022-07-14 07:14 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/js/use_template.rs
> +    is_un_necessary_string_concat_expression(expr).and_then(|result| {
You can exchange the ```and_then``` by the ```?``` operator.

2022-07-14 07:15 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/use_template.rs
> +                // drop the trivia of original expression make the generated `JsTemplate` a little nicer, if we don't do this
I think we should keep the comments.

2022-07-14 07:27 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/js/use_template.rs
> +        if binary_expr
I think this call needs to be cheaper. For example;

This is what I mean. We are analyzing the red ```BinaryExpr```. Then we call ```emit_signal``` on our parent, the green node. This recursively processes the red node again.

![image](https://user-images.githubusercontent.com/83425/178924930-64ba322b-7894-4b2d-9d1c-90b93a383855.png)

If this call returns ```Some(...)``` we throw everything away and do everything again when the lint rule calls the green node, which probably already happened, given that it is higher in the tree.

In deeper expressions, this will grow exponentially. One way to check this is to print something on the ```run``` and something in the ```is_un_necessary_string_concat_expression``` and other recursive calls and use something like https://github.com/nnethercote/counts to see if their count spread exponentially as the expression grows.

Can´t we just check if the parent is a ```BinaryExpr``` and assume that it was dealt with?

2022-07-14 07:28 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/js/use_template.rs
> +fn is_un_necessary_string_concat_expression(node: &JsBinaryExpression) -> Option<bool> {
I think ```is_unnecessary_string_concat_expression``` is fine.
Also, some comments explaining when is unnecessary would be fine.

2022-07-14 07:29 UTC, xunilrj commented on crates/rome_js_analyze/src/utils.rs
> +pub fn interpret_escaped_string(s: &str) -> Result<String, MyError> {
I would name this as the comments. Easier to understand what is doing.

2022-07-14 07:34 UTC, xunilrj commented
> @xunilrj would you mind helping review this pr?

Done. I would also test this with a very big binary expression, because we already had problems with recursive algorithms.
I will search later, I think the Typescript test suite has one file to test this.

2022-07-14 07:36 UTC, IWANABETHATGUY commented
> > @xunilrj would you mind helping review this pr?
> 
> Done. I would also test this with a very big binary expression, because we already had problems with recursive algorithms. I will search later, I think the Typescript test suite has one file to test this.

Thanks, your review mesage is very helpful, I will have a look later on.

2022-07-19 02:00 UTC, IWANABETHATGUY commented
!bench_analyzer

2022-07-19 05:01 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/use_template.rs
> +        if binary_expr
Done, this should be a linear algorithm `is_unnecessary_string_concat_expression` should be executed `2 * N` times, 
`N` is the number of `BinaryExpression`. 
I will paste the output later.

2022-07-19 07:56 UTC, IWANABETHATGUY commented
!bench_analyzer

2022-07-19 08:12 UTC, ematipico approved these changes

2022-07-19 08:13 UTC, merged