feat(rome_js_analyze): useTsExpectError
rome/tools pull request #2811
Opened 2022-07-04 06:24 UTC by IWANABETHATGUY

## Summary
1. Resolved #2753 

## Test Plan
1. Checking the new snapshot result

2022-07-04 14:49 UTC, ematipico requested changes
Would it be possible to have some description in the PR that explains the implementation please? There's a lot going on and the description is poor compared to the actual logic. Without context, the review is really hard to do

2022-07-04 14:49 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +    /// Enforce use `@ts-expect-error` instead of `@ts-ignore` to get notified when suppression is no longer necessary.
```suggestion
    /// Enforces the use of `@ts-expect-error` instead of `@ts-ignore` to get notified when a suppression is no longer necessary.
```

2022-07-04 14:49 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +    type State = Vec<(usize, String)>;
Why not an `HashMap`?

2022-07-04 14:49 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +                        // I use this `strip_prefix` just because of clippy not happy
This comment should actually say *why* clippy is not happy, so we can understand why `strip_prefix` is used instead. What did you try to use before?

2022-07-04 14:49 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +    type State = Vec<(usize, String)>;
Creating a new string for each `@ts-ignore` is really expensive. Wouldn't be better to return, instead, all the information needed to compute the string? 

`@ts-expect-error` should be a `const` of this file instead.

2022-07-04 14:49 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +                        //
remove?

2022-07-04 14:49 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +                        let original = item.text();
Why using `.replace()` is not enough?

2022-07-04 15:05 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +    type State = Vec<(usize, String)>;
> Why not an `HashMap`?

Because the iteration of comment is always ordered, whether checking phase or replacing phase.

2022-07-04 16:01 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +                        // I use this `strip_prefix` just because of clippy not happy
I write code like this before:
```rs
if let Some(stripped) = original.starts_with("/**") {
    &original[3..]
} else if original.starts_with("//") || original.starts_with("/*") {
    &original[2..]
} else {
    original
}
.trim_start();
```

2022-07-04 16:23 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +    type State = Vec<(usize, String)>;
> 

Do you mean deferring the string replacement until the user triggers the code action?

2022-07-04 16:38 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +    type State = Vec<(usize, String)>;
> > 
> 
> Do you mean deferring the string replacement until the user triggers the code action?

Yes exactly

2022-07-05 16:49 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +                        let original = item.text();
What do you mean by `replace`,  `Trivia` seems not to be replaceable

2022-07-06 12:39 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +                        let original = item.text();
> OK, probably I need to wait for a better description of the PR. It's really hard to understand what's going on

Yeah, I am writing the doc

2022-07-11 16:32 UTC, ematipico requested changes
Sorry to reject the PR, but the whole algorithm should be reviewed.

The suppression comment works only on single line comments: https://www.typescriptlang.org/play?ssl=7&ssc=19&pln=1&pc=1#code/PQKhCgQAgAQFwM4FoCmAPADigxnVAnfAe30mHABsU4oBDALigCMiiraA7KAXigGZw4YMFiJUmHHhSESlas0Ys2KTj35A

2022-07-11 16:32 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/use_ts_expect_error.rs
> +    /// we use a [Vector] to store the range because the `@ts-ignore` could exist multiple time in single trivia piece.
```suggestion
    /// `ts-ignore` could be used in multiple places inside a comment, we need to track the state of each `@ts-ignore`.
    /// In order to track these comments, we shape the state with a [Vec] of tuples, where a tuple contains:
    /// - the first element is the position  of the original leading trivia that needs to be replaced;
    /// - the second element of the tuple is a [vector](Vec) of the [ranges](Range) of the string `"@ts-ignore"` found in the original trivia piece text;
    /// 
    /// We use a [Vector] because the string `"@ts-ignore"` can be present multiple times inside a comment.
```

1. "track the state" is a bit generic, what is "a state"? Maybe we can say "track the position"

2022-07-19 12:19 UTC, ematipico commented
@IWANABETHATGUY are there any progress on this PR?

2022-07-19 12:32 UTC, IWANABETHATGUY commented
> @IWANABETHATGUY are there any progress on this PR? Do you need any help?

Nope, I will address issues this week.

2022-07-23 11:24 UTC, IWANABETHATGUY commented
!bench_analyzer

2022-07-23 11:32 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/tests/specs/js/noLabelVar.js.snap
> +---
move this test file to the right place.

2022-07-26 11:58 UTC, ematipico approved these changes
@leops @xunilrj could you please add your review?

2022-07-26 11:58 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/ts/use_ts_expect_error.rs
> +                    normalized_string.push_str(&text[(state.1 + 10)..]);
What's 10 in this case? Can we store it in a `const` so we know what's the meaning of it?

2022-07-26 12:16 UTC, leops reviewed
I think the main issue I have with this rule is that it only matches on `JsAnyStatement`, so it would catch these cases:

```typescript
const
    // @ts-ignore
    value1: boolean = 3;
    
const value2 = 
    // @ts-ignore
    true + 4;
```

Unfortunately in order to detect these, the rule would have to inspect the leading trivia of all the tokens in the file, and the performance cost of doing that seems prohibitively high at the moment

2022-07-26 12:16 UTC, leops commented on crates/rome_js_analyze/src/analyzers/ts/use_ts_expect_error.rs
> +        first_token.trailing_trivia().pieces().for_each(|item| {
Nit: use a `for-in` loop here instead of `for_each`

2022-07-26 12:16 UTC, leops commented on crates/rome_js_analyze/src/analyzers/ts/use_ts_expect_error.rs
> +                    let mut normalized_string = String::with_capacity(text.len());
This text could be pushed directly into the `next_leading_trivia_string` buffer without having to allocate an intermediate `String` (or even better, only allocate a single string holding the data for `next_leading_trivia_string`, `first_token.text_trimmed()` and `next_trailing_trivia_string`)

2022-07-26 13:53 UTC, ematipico commented
> I think the main issue I have with this rule is that it only matches on `JsAnyStatement`, so it would not catch these cases:
> 
> ```ts
> const
>     // @ts-ignore
>     value1: boolean = 3;
>     
> const value2 = 
>     // @ts-ignore
>     true + 4;
> ```
> 
> Unfortunately in order to detect these, the rule would have to inspect the leading trivia of all the tokens in the file, and the performance cost of doing that seems prohibitively high at the moment

Given this premise, should we put on hold this PR? I doesn't make much sense to release an half working rule.

2022-07-26 13:59 UTC, IWANABETHATGUY commented
> 

Unfortunately, in order to detect these, the rule would have to inspect the leading trivia of all the tokens in the file, and the performance cost of doing that seems prohibitively high at the moment. As @leops said, the main trade-off is the performance,.
If you agree to the trade-off for the performance, I would like to fix these edge issues.

2022-07-26 15:20 UTC, leops commented
> Unfortunately, in order to detect these, the rule would have to inspect the leading trivia of all the tokens in the file, and the performance cost of doing that seems prohibitively high at the moment. As @leops said, the main trade-off is the performance,. If you agree to the trade-off for the performance, I would like to fix these edge issues.

At the moment the linter lacks two capabilities requires to implement this, the first and most important is the ability for lint rules (and visitors) to inspect syntax tokens (currently lint rules can only query AST nodes), while a secondary one would be to allow rules to be enabled or disabled on a per-language basis: currently the existing JSX and TS rules are enabled all the time which isn't really a problem since they only query node for their language and thus never match in incompatible files, but if this rule needs to inspect all tokens we would want it to be disabled on non-TS files.

2022-07-27 06:34 UTC, ematipico commented
I think we should have this PR on hold until we figure out a better way to implement it. 

> we would want it to be disabled on non-TS files.

Unfortunately this is not always true. It's possible to avail of the TS compiler even in JS files, there's option called `checkJs` in the `tsconfig.json` file that enables the compiler to check JS files. Regardless, it seems we don't have enough tools to implement this rule at the moment.

2022-08-10 12:31 UTC, ematipico commented
@leops should we just close the PR until we have the tools to be able to implement this rule?

2022-08-10 12:45 UTC, leops commented
> @leops should we just close the PR until we have the tools to be able to implement this rule?

Yes I think in general it could make sense to close PRs that are on hold, it's probable that by the time we resume working on these it'll be easier to start again from scratch than trying to rebase the previous attempt and handle all the possible merge conflicts

2022-08-10 12:52 UTC, closed without merging