chore(rome_*):reduce parking_lot usage
rome/tools pull request #2818
Opened 2022-07-05 09:00 UTC by IWANABETHATGUY

## Summary
1. Since we use upgrade toolchain to 1.62.0 stable which has been stablized the new 

## Test Plan
1. cargo test

2022-07-05 09:20 UTC, xunilrj commented
Will be interesting to see the differences.

2022-07-05 09:35 UTC, IWANABETHATGUY commented
> 

I don't benchmark this pull request, You could see the detailed benchmark made by rust core team https://github.com/rust-lang/rust/pull/95035#issuecomment-1073966631

2022-07-05 09:43 UTC, IWANABETHATGUY commented
This pull request more likely to be a compile-time improvement

2022-07-05 16:59 UTC, ematipico requested changes
I know it's annoying, but each `unwrap` should be documented with a `// SAFETY` comment

2022-07-05 16:59 UTC, ematipico commented on crates/rome_js_formatter/Cargo.toml
> +parking_lot = "0.12.0"
I am not sure what's this change for.

2022-07-06 07:51 UTC, IWANABETHATGUY commented
The const *constructor* of `{Mutex, Condvar, RwLock}`  would be stable until 1.63, https://github.com/rust-lang/rust/pull/97791/files#diff-3ec0c54e5f945521d425d023283b935edaa5c16fe7e2c0f675b07f35e65f639bR125, So i am going to close this pr for now

2022-07-06 07:51 UTC, closed without merging