feat(playground): Sync rome config to local storage
rome/tools pull request #2853
Opened 2022-07-09 07:43 UTC by IWANABETHATGUY

## Summary
1. Resolve https://github.com/rome/tools/issues/2846

## Test Plan
1. Check out if the new feature of the playground is expected.

2022-07-09 10:14 UTC, IWANABETHATGUY commented
https://user-images.githubusercontent.com/17974631/178101372-68fdc7ac-b07a-4b02-84d9-91555963164f.mp4

2022-07-11 16:00 UTC, ematipico requested changes

2022-07-11 16:00 UTC, ematipico commented on website/playground/src/utils.ts
> +	let interested_keys: Array<keyof RomeConfiguration> = ['treeStyle'];
We already have `persistKeys` which has the same type. We should not repeat code. Also, `const` is enough.

2022-07-11 16:14 UTC, ematipico commented on website/playground/src/utils.ts
> +// Only save prop of `PlaygroundState` that we interested, making `localStorage.setItem` which is file IO a bit faster
This line should have stayed where we use `localStorage.setItem` and you have to add "faster than..." something. I don't know what though... you have to tell us 😛

2022-07-12 06:29 UTC, IWANABETHATGUY commented on website/playground/src/utils.ts
> +// Only save prop of `PlaygroundState` that we interested, making `localStorage.setItem` which is file IO a bit faster
Done

2022-07-12 08:05 UTC, ematipico approved these changes

2022-07-12 08:05 UTC, merged