feat(rome_js_analyze): noExtraBooleanCast
rome/tools pull request #2868
Opened 2022-07-12 14:44 UTC by IWANABETHATGUY

## Summary
1. Resolved #2660 

## Test Plan
1. cargo test

2022-07-13 10:07 UTC, xunilrj commented on crates/rome_js_analyze/tests/specs/noExtraBooleanCast.js.snap
> +=  note: It is not necessary to use double-negation when a value will already be coerced to a boolean.
Is this true in all cases?
I thought there are cases in which ```!!``` is not redundant.

2022-07-13 10:10 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +            .and_then(|stmt| Some(stmt.test().ok()?.syntax() == node)),
Do you need ```and_then``` here? You are returning ```Option<>```.

2022-07-13 10:12 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +    if JsCallArgumentList::can_cast(node.kind()) {
Same thing here. I think you can use "?" and simplify the logic.

2022-07-13 10:13 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +fn is_in_boolean_context(node: &JsSyntaxNode, parent: &JsSyntaxNode) -> Option<bool> {
This is the only method without comments.

2022-07-13 10:13 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +    JsUnaryExpression::cast(node.clone()).and_then(|expr| {
Same thing with ```and_then```

2022-07-13 10:15 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +        // Convert `!!x` -> `x` if parent `SyntaxNode` in any boolean `Type Coercion` context
Silly, but would you match ```!(!a)```?

2022-07-13 10:16 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +            if is_negation(&syntax).unwrap_or_default() {
Makes sense to extract to ```is_double_negation``` method?

2022-07-13 10:21 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/noExtraBooleanCast.js.snap
> +if (!!Boolean(foo)) {
@leops @xunilrj quick question on how the fixes are displayed/applied. In this example, as you may noticed from the snapshots, we have two diagnostics with two difference code fixes. Although, the snapshot shows the fixes **for the single** diagnostic but it's hard to understand **the final result of the code**.

For example, Rome classic was better at displaying that: https://github.com/rome/tools/blob/archived-js/internal/compiler/lint/rules/js/noExtraBooleanCast.test.md#1 (eventually only `foo`) should remain.

So my question is: what's the final result of the code?

2022-07-13 13:04 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +            .and_then(|stmt| Some(stmt.test().ok()?.syntax() == node)),
Yes, I do. Because I need to get the `test` of `JsIfStatement`, and I need to use this `?` for early returning.
Do you mean I could write this code like this:
```rs
JsSyntaxKind::JS_IF_STATEMENT => {
  let stmt = parent.cast::<JsIfStatement>()?;
  Some(stmt.test().ok()?.syntax() == node)
},
```

2022-07-13 13:15 UTC, leops commented on crates/rome_js_analyze/tests/specs/noExtraBooleanCast.js.snap
> +if (!!Boolean(foo)) {
Unfortunately merging diagnostics and code actions isn't supported yet at the analyzer infrastructure level. It could be possible to support this by applying code actions on the fly to mutate the tree in place as its being analyzed, but that will probably require some work to get it right. In the meantime it's possible to handle this at the rule level by manually checking for the recursive case in the run function, this is what the `useTemplate` rule does for instance

2022-07-13 13:18 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +            .and_then(|stmt| Some(stmt.test().ok()?.syntax() == node)),
Yes.

2022-07-13 13:30 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +            .and_then(|stmt| Some(stmt.test().ok()?.syntax() == node)),
LGTM

2022-07-13 13:43 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +            .and_then(|stmt| Some(stmt.test().ok()?.syntax() == node)),
I am so old, I had to look at what "LGTM" stands for! :smile:

2022-07-13 13:44 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +            .and_then(|stmt| Some(stmt.test().ok()?.syntax() == node)),
It means **Looks Good To Me**

2022-07-13 17:05 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +        // Convert `!!x` -> `x` if parent `SyntaxNode` in any boolean `Type Coercion` context
Nope, I am still not sure if checking this case is necessary. Using double-negation is more commongly, but I have nevery saw someone write code like this. 🤣

2022-07-14 05:15 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +        // Convert `!!x` -> `x` if parent `SyntaxNode` in any boolean `Type Coercion` context
@ematipico @leops , any thought about this? Do we need to support this?

2022-07-14 05:28 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/tests/specs/noExtraBooleanCast.js.snap
> +if (!!Boolean(foo)) {
I prefer handle this in infrastructure level. 
I have a simple algorithm for now, maybe not efficient.
1. run `rome_js_analyze`, this should emit some diagnostic with code action.
2. If there are any code action emitted by `rome_js_analyze`, apply them and go to `1`.
3. If there are no code action found , break.
Also, we need to set a threshhold like `10`, avoiding infinite loop.

2022-07-14 10:22 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/no_extra_boolean_cast.rs
> +        // Convert `!!x` -> `x` if parent `SyntaxNode` in any boolean `Type Coercion` context
Got it, I will fix this.

2022-07-14 10:50 UTC, ematipico requested changes

2022-07-14 10:53 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/noExtraBooleanCast.js.snap
> +if (!!Boolean(foo)) {
> So what is the conclusion?

I'd suggest to leave the diagnostic like this and not trying to improve it. This is something that has to be fixed in the core of the analzyer.

2022-07-14 10:54 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +    Some(JsUnaryExpression::cast(node.clone())?.operator().ok()? == JsUnaryOperator::LogicalNot)
That what how i wrote first time, you could see https://github.com/rome/tools/pull/2868#discussion_r920068039

2022-07-14 10:55 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +    Some(JsUnaryExpression::cast(node.clone())?.operator().ok()? == JsUnaryOperator::LogicalNot)
I missed that comment :)

2022-07-14 10:56 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +            .unwrap_or_default()
I guess this because is clippy not happy, let me check it.

2022-07-16 03:26 UTC, IWANABETHATGUY commented
!bench_analyzer

2022-07-19 12:20 UTC, ematipico commented
@IWANABETHATGUY are there any progress on this PR? Do you need any help?

2022-07-19 12:32 UTC, IWANABETHATGUY commented
> @IWANABETHATGUY are there any progress on this PR? Do you need any help?

Nope, I will address issues this week.

2022-07-23 03:37 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +    let parent = parent.clone();
1. Done,
2. It is not redundant, because the `node` pass into `is_in_boolean_context` is just a `JsAnyExpression`, the expression could be any where, 
**Example** 
```
while (test) {
          ^^^^ Only here is valid, so we need to check 
                   if the expression SyntaxNode is equal to the parent's `test` clause SyntaxNode
}
```

2022-07-23 03:38 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +            .unwrap_or_default()
Done

2022-07-23 03:51 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +        let parent_node_in_boolean_cast_context = is_in_boolean_context(&syntax, &parent_syntax)
No, we can't have this early return.
Because the `is_in_boolean_context` only check the scenario that `SyntaxNode` equals to the parent's `test` clause `SyntaxNode` like :
```js
if (xxx) {
    ^^^
}
while (xxx) {
          ^^^
}
//...............and so on.
```
But it could be possible to have an extra boolean cast like: 
```js
new Boolean(xxx);
                      ^^^
// Because when you write something like this
new Boolean(!!xxx)
// the new Boolean `NewExpression` is redundant
```

2022-07-23 03:55 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +            // Convert `Boolean(x)` -> `x` if parent `SyntaxNode` in any boolean `Type Coercion` context
That would be another case, which I will add below

2022-07-23 04:04 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +            return JsCallExpression::cast(syntax).and_then(|expr| {
Done

2022-07-23 06:11 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +/// Check if this node is in the position of `test` slot of parent syntax node.
![image](https://user-images.githubusercontent.com/17974631/180592929-7df274ee-0965-4c1d-b40d-1fa8845b6080.png)
Would it be better if I rename it to `test clause of the parent `

2022-07-23 06:58 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +/// Check if this node is in the position of `test` slot of parent syntax node.
I think ```JsWhileStatement::test``` would be quite clear.

2022-07-23 07:33 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +/// Check if this node is in the position of `test` slot of parent syntax node.
It's not about the name of the node, it's about the whole comment. When I read it without checking the code of function, I don't understand what it means.

2022-07-23 07:35 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +    let parent = parent.clone();
I understand now, thank you.

2022-07-23 09:38 UTC, IWANABETHATGUY commented
!bench_analyzer

2022-07-23 09:57 UTC, IWANABETHATGUY commented
I think there should be a more performant way to implement this, let me try.

2022-07-26 11:48 UTC, ematipico commented
@xunilrj @leops could you please review and merge once you see fit?

2022-07-26 12:00 UTC, ematipico approved these changes

2022-07-26 13:06 UTC, leops approved these changes

2022-07-26 13:06 UTC, leops commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +                markup! {
Nit: markup is redundant here since the `RuleDiagnostic` constructors accept any type implementing `Display` as a message, just pass `title` directly instead

2022-07-26 13:06 UTC, leops commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +            message: markup! { ""{message}"" }.to_owned(),
Nit: The two empty string literals `""` are not needed, those will just create formatting nodes with an empty content

2022-08-03 07:12 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +        version: "0.8.0",
This should be `0.9.0` now. Once updated, we can merge it

2022-08-03 08:58 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs
> +        version: "0.8.0",
Done

2022-08-03 09:25 UTC, merged