feat(rome_js_ananlyze): noImportAssign
rome/tools pull request #2922
Opened 2022-07-24 11:43 UTC by IWANABETHATGUY

## Summary
1. Resolved #xxx

## Test Plan
1. cargo test

2022-07-25 07:51 UTC, ematipico requested changes

2022-07-25 07:51 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_import_assign.rs
> +    /// ```js,expect_diagnostic
Could you add a case with `import { a } from "b"`?

2022-07-25 07:51 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_import_assign.rs
> +    /// ```js,expect_diagnostic
Could you add a case with `import a, * as b from "d"` and we re-assign `b`?

2022-07-25 07:51 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_import_assign.rs
> +    type State = (JsSyntaxNode, JsSyntaxNode);
Wouldn't it be better to use `JsAnyBinding` in the first element of the tuple? Or even using an union to identify the local names. Using `JsSyntaxNode` is very loose and error prone.

Same thing for the second element of the tuple, we should use an existing AST node or a new union node.

2022-07-25 14:57 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_import_assign.rs
> +    type State = (JsSyntaxNode, JsSyntaxNode);
Done

2022-07-25 15:27 UTC, IWANABETHATGUY commented
!bench_analyzer

2022-07-25 15:49 UTC, IWANABETHATGUY commented
@xunilrj , would you mind helping with reviewing?

2022-07-29 12:44 UTC, IWANABETHATGUY commented
!bench_analyzer

2022-07-29 12:55 UTC, IWANABETHATGUY commented
The performance looks good now.

2022-07-30 12:28 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_import_assign.rs
> +                for reference in model.all_references(ident_binding) {
You can do ```all_writes``` here. They should be rare.

2022-07-30 21:05 UTC, xunilrj approved these changes

2022-08-02 06:52 UTC, ematipico approved these changes

2022-08-02 06:53 UTC, ematipico commented
Let's hold the merging of this PR until this PR https://github.com/rome/tools/pull/2980 lands

2022-08-03 07:15 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_import_assign.rs
> +        version: "0.8.0",
This should be `0.9.0` now

2022-08-03 07:50 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_import_assign.rs
> +        version: "0.8.0",
Done

2022-08-03 08:48 UTC, IWANABETHATGUY commented
Since https://github.com/rome/tools/pull/2980 has landed, I thinks this pull request is good to merge now.

2022-08-03 09:45 UTC, merged