feat(playground): display the control flow graph in the playground
rome/tools pull request #2969
Opened 2022-07-29 14:39 UTC by leops

## Summary

This PR add a new "Control Flow Graph" tab in the playground displaying the control flow graph for the currently selected function (the function that contains either the cursor or the start of the current selection) using mermaid.js

In order to extract the CFG from the analyzer I introduced a concept of "matcher layer" that can wrap an existing query matcher and intercept incoming query matches from the visitors. Calling the analyzer through the existing `analyze` entry point simply uses an empty layer function, this is all statically dispatched so it should all get inlined and come out as zero-cost in the end.

2022-07-30 13:04 UTC, xunilrj approved these changes

2022-07-30 16:18 UTC, ematipico commented
The new tab can't been seen on mobile

2022-08-02 07:25 UTC, ematipico requested changes

2022-08-02 07:25 UTC, ematipico commented on crates/rome_analyze/src/matcher.rs
> +}
We should document the struct and the functions. And how to use them.

2022-08-02 07:25 UTC, ematipico commented on crates/rome_analyze/src/matcher.rs
> +    fn match_query(&mut self, params: MatchQueryParams<L>) {
How does this function differ from `match_query` of `QueryMatcher`?

2022-08-02 07:25 UTC, ematipico commented on crates/rome_js_analyze/src/lib.rs
> +pub fn analyze_with_matcher_layer<'a, V, F, B>(
I think the documentation should be updated, now that this function has been renamed and it accepts a new argument.

2022-08-02 07:25 UTC, ematipico commented on website/playground/src/DesktopPlayground.tsx
> +		);
nit: I think there's no need to update the state if the cursor hasn't changed, meaning I think we should do like:
```js
if state.cursorPosition !== cursorPosition {
	setPlaygroundState()
}
```

2022-08-02 07:45 UTC, leops commented on crates/rome_analyze/src/matcher.rs
> +    fn match_query(&mut self, params: MatchQueryParams<L>) {
The `MatcherLayer` struct is an "adapter type" that implements the `QueryMatcher` trait on top of another, generic type also implementing this trait. It's similar to `Iterator` adapters like `Inspect<T>` that implements the iterator trait by calling through to the underlying `T: Iterator` object, then passing the items returned by `next` to the provided callback (the difference is that `MatcherLayer` calls the `layer` callback function before calling the implementation of `match_query` for the underlying matcher type)

2022-08-02 07:53 UTC, leops commented on website/playground/src/DesktopPlayground.tsx
> +		);
This would require to get rid of the memoization on the `onUpdate` function, or at least reattach a new event handler every time the state changes. This should have more or less the same effect anyway, it's my understanding of React that it will abort a state update if the updater function returns the same object unmodified but I could be wrong about that

2022-08-02 09:04 UTC, ematipico approved these changes

2022-08-02 09:26 UTC, ematipico commented
@leops could you check why the deployment on CloudFlare fails? Hopefully it's their fault

2022-08-02 09:33 UTC, MichaReiser approved these changes

2022-08-02 09:33 UTC, MichaReiser commented on crates/rome_analyze/src/matcher.rs
> +}
Nit: `Inspect` seems to be an important concept, how about naming this an `InspectMatcher`?

2022-08-02 09:33 UTC, MichaReiser commented on crates/rome_js_analyze/src/lib.rs
> +        MatcherLayer::new(build_registry(&filter), matcher_layer),
Would it be an option to add this functionality instead on `Analyzer` as `inspect`?

2022-08-02 09:33 UTC, MichaReiser commented on website/playground/src/MermaidGraph.tsx
> +			mermaid.contentLoaded();
How much processing time does this add for large files?

2022-08-02 09:33 UTC, MichaReiser commented on website/playground/src/MermaidGraph.tsx
> +			mermaid.contentLoaded();
An alternative could be to link to [mermaid's playground](https://mermaid.live/edit#pako:eNpVkE1qw0AMha8itEohvoAXhcZOsgm00Ow8WQiPnBma-WEsU4Ltu3ccU0i0kvS-JwmN2AbNWOI1UTRwrpWHHB9NZZLtxVF_gaJ4n44s4ILn-wS7zTFAb0KM1l_fVn63QFCNpwVjEGP9z7xK1cP_6XmCujlRlBAvz8r5N0ywb-yXyeNfFZM4uw5NR2VHRUsJKkoPBLfoODmyOp8-Lh2FYtixwjKnmjsabqJQ-TmjQ9QkvNdWQsJS0sBbpEHC9923__XK1JbyIxzmfbee5z-A61yS) (or take the JPG link) but
* likely to be unstable because it's not a real API
* unclear what params must be passed to the playground

2022-08-02 13:19 UTC, leops commented on website/playground/src/MermaidGraph.tsx
> +			mermaid.contentLoaded();
I tried to paste some of the very complex test cases we have for the CFG into the playground, with a large graph the processing can block the page for approximately 1 second. The alternative that GitHub or Notion seem to be using is to display the graph in a dedicated page embedded using an iframe, this way the rendering happens in its own dedicated process isolated from the main app

2022-08-02 13:24 UTC, leops commented on crates/rome_js_analyze/src/lib.rs
> +        MatcherLayer::new(build_registry(&filter), matcher_layer),
That would work, but in the end the `rome_js_analyze` library would probably still need to expose two functions since the internal `Analyzer` is not part of the public API

2022-08-02 13:25 UTC, MichaReiser commented on website/playground/src/MermaidGraph.tsx
> +			mermaid.contentLoaded();
Does this also block if you're tying and the CFG page is open? I'm not too concerned about the impact if it only happens on the CFG page (and ideally, doesn't affect typing).

2022-08-04 11:46 UTC, ematipico requested changes
I think we have to do something with the build process (or the upload of static files). The playground is not able to load the iframe:

![Screenshot 2022-08-04 at 12 46 13](https://user-images.githubusercontent.com/602478/182839353-a5d741dd-0c8a-4643-8c0a-14ed74a265aa.png)

2022-08-04 12:18 UTC, leops commented
> I think we have to do something with the build process (or the upload of static files). The playground is not able to load the iframe:

Ah I think it's an issue with the temporary deployment (it tries to load the content page for the iframe at `play.rome.tools/mermaid.html` when it should be `play.rome.tools/10cc478/mermaid.html`), it would correctly on the main playground deployment but I'll try to fix it so it works in PRs too

2022-08-08 07:55 UTC, leops commented
The CI check is failing on false positives for the `noUnusedVariables` rule introduced in the latest release, but this seems like an unrelated issue and this PR could be merged anyway ?

2022-08-08 09:05 UTC, ematipico commented
> The CI check is failing on false positives for the `noUnusedVariables` rule introduced in the latest release, but this seems like an unrelated issue and this PR could be merged anyway ?

I don't mind merging the PR

2022-08-08 10:28 UTC, ematipico approved these changes

2022-08-08 11:15 UTC, merged