feat(rome_js_analyze): useDupeArgs
rome/tools pull request #2972
Opened 2022-07-30 09:13 UTC by IWANABETHATGUY

## Summary

## Test Plan

2022-07-30 09:58 UTC, IWANABETHATGUY commented
Wait #2973 to be merged.

2022-07-31 07:44 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                    let model = ctx.model();
Do you need the Semantic Model? 

I thought iterating the names of the arguments was enough in this case. Maybe just ```BTreeSet::insert```ing them and checking the return value.

2022-07-31 07:45 UTC, xunilrj approved these changes

2022-07-31 07:49 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                    let model = ctx.model();
Iterate the arguments may be a method to handle this issue, but you need to check the scenario below:
```js
function test(a, {a, b, ...a}, [a, b]) {
  
}

function test2(a, ...args ) {
  
}
```
So that's why I am using the semantic model.

2022-07-31 11:09 UTC, IWANABETHATGUY commented
!bench_analyhzer

2022-07-31 11:40 UTC, IWANABETHATGUY commented
!bench_analyzer

2022-08-02 07:37 UTC, ematipico requested changes

2022-08-02 07:37 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +    type State = JsSyntaxNode;
Using `JsSyntaxNode` is not recommended, because we can't understand which nodes are are involved. We should use an union is we have to include different nodes.

2022-08-02 07:37 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                    .descendants()
This is expensive... is it needed? Imagine if we had something like this:

```js
function f(
 	a = () => false,
	{ b = "something" },
) {}
```

It means that we have traverse all nodes contained in the arguments?

2022-08-02 10:59 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                    .descendants()
Nope. Actually, it use `find_map` so it will terminate when it meet the first `JsidentifierBinding`.
That means it will stop at `a` in this case, which pretty fast.

2022-08-02 11:24 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                    .descendants()
But it won't if it doesn't find a `JsidentifierBinding`. This is a case where we might have `JsUnknownParameter` instead of `JsFormatParameter`. Because of the fact that it's an `unknown` node, it might contain more valid nodes that could cause false positives.

I think it's best to surgically query the nodes you need.

```rust
args.map(|arg| {
	// here check the type of argument and query the biding
});
```

2022-08-03 07:16 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +        version: "0.8.0",
This should be `0.9.0` now

2022-08-06 11:57 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +    type State = JsSyntaxNode;
The `SyntaxNode` is cloned from `binding.syntax()`, and `binding` has no method to return a specific `JsAstNode`

2022-08-06 12:52 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +    type State = JsSyntaxNode;
If you know the type you need, you can use `cast`, `can_cast`, `cast_unwrap` to retrieve a typed node from a `JsSyntaxNode`

2022-08-06 13:34 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                    .descendants()
Your example is a function call expression, not Any JsFunction

2022-08-06 15:33 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                    .descendants()
As I reply to @xunilrj , https://github.com/rome/tools/pull/2972#discussion_r933942507, we could iterate the args list, but the implementation would be pretty complex since we need to handle all kinds of parameter, 
```
function test(a, {a, b, ...a}, [a, b]) {
  
}

function test2(a, ...args ) {
  
}
function foo([[a, b], [c, d]]) {}
function foo([[[a, b], [c, d]]]) {} // the array binding pattern could be recursively, 
function foo([[[a = function(d, g, f) {}, b], [c, d]]]) {} // the array binding pattern could be recursively, 
```
And also, according to the benchmark, my implementation is not bad.
Maybe we could optimize this rule after we found it has performance issues. What do you think?

2022-08-08 11:23 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                    .descendants()
Unfortunately we can't rely on the current benchmark that much, because it doesn't reflect the benches we are interested with. (this is a separate issue, we're working on it)

What about this real case: https://github.com/rome/tools/blob/main/crates/rome_js_formatter/tests/specs/prettier/js/performance/nested-real.js

2022-08-08 11:25 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                    .descendants()
> Maybe we could optimize this rule after we found it has performance issues. What do you think?

I would then move it `recommended: false`, unfortunately I am not really confident about the current implementation

2022-08-08 15:55 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                    .descendants()
It could even be that this yields incorrect results. Let's say you have

```
function test(a  = function(a) {}) {}
```

`descendents` descents into the inner `function`, reporting both `a` identifiers.

2022-08-11 07:44 UTC, IWANABETHATGUY commented
!bench_analyzer

2022-08-11 09:32 UTC, IWANABETHATGUY commented
@ematipico I rewrite the algorithm as you said before, using a recursive pattern matching algorithm to find the duplicate params. Would you mind helping with reviewing?

2022-08-11 10:06 UTC, leops commented
So this may be more of a discussion we could have in the corresponding issue for this rule rather than in the PR, but I'm wondering if there's a way we could make the implementation for this rule more generic, into a `noNameShadowing` rule that would disallow duplicate binding names in the same scope whether that's two arguments, variables, functions, object / class member ...

2022-08-15 14:39 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +/// Traverse the parameter recursively and check if it is duplicated.
Could you update the comment and explain what "traverse a parameter recursively" mean, please? It's clear, because it's not something that a developer does every day. Maybe adding some snippet in the documentation can help to understand

2022-08-15 14:39 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +            rome_js_syntax::JsAnyFormalParameter::JsUnknownParameter(_) => {}
We can remove `rome_js_syntax` here, as we already use it.

2022-08-15 14:39 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +    res: &mut Vec<JsIdentifierBinding>,
Let's avoid abbreviations, at  least for `set` and `res`. Sometimes it's difficult for someone's brain to understand what they stand for

2022-08-15 14:39 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +fn traverse_binding(
Could you add some documentation to this function and explain what it does?

2022-08-15 14:39 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +fn check_binding(
`check_binding` doesn't do any check... Maybe we can call it `track_binding`? And document what happens, we should explain why sometimes we do `res.push` or `set.insert`. By looking at the code I can't understand it.

2022-08-15 14:39 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +                // reuse the `HashSet` and `Vec` to avoid extra allocations.
```suggestion
                // reuse the `FxHashSet` and `Vec` to avoid extra allocations.
```

2022-08-15 14:39 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/js/noDupeArgs.js
> +// valid
Would you mind adding more tests, please?
- arrow functions
- class methods
- object methods

We can replace the ones you already added, for example:

`function d(a, b, a) {}` => `var d = (a, b, a) => {}`. So we test the error case with arrow functions

Could you add this cases too:

```js
export function f(a, b, c = (a, b, b) => {}) {
  
}
```

It should fail in the arrow function

2022-08-16 09:05 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +        Some(vec![])
What's the reason for using `Some(vec![])` here? Seems like it's always used?

2022-08-16 09:05 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +            for ele in inner_binding.elements().into_iter() {
```suggestion
            for element in inner_binding.elements().into_iter() {
```

2022-08-16 09:09 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +        Some(vec![])
Because I want to use the handy `?`, but the return type of `run` is `Vec<Self::State>` which I can't use the `?` operator.

2022-08-18 07:53 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +    binding_set: &mut FxHashSet<String>,
Ok, with the documentation now I understand better what we're doing. I would suggest to change the name of the variables: `binding_set` => `tracked_bindings` and `identifier_vec` => `duplicated_arguments` (the name reminds the name of the rule)

2022-08-18 07:53 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +        identifier_vec.push(id_binding);
Don't we need to remove `id_binding` from `binding_set` here? The old rule bailed once it found just one.

2022-08-18 07:53 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +        Some(vec![])
Do we need to track the names in a vector? The old rule used to bail once it found at least one duplicate. Can't we do the same here or there's a reason why we should do it for all the parameters?

2022-08-18 08:10 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +        Some(vec![])
Typescript using this behavior 
![image](https://user-images.githubusercontent.com/17974631/185344404-e737abe4-4198-4c0e-8a65-a92c9cb6ee00.png)

2022-08-18 08:10 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +        Some(vec![])
I am ok with both.

2022-08-19 05:14 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +        Some(vec![])
@ematipico, which one do you prefer? This maybe the last issue this pr has

2022-08-19 06:07 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +        Some(vec![])
I would go for the simplest approach. It also requires less AST navigation

2022-08-19 06:57 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_dupe_args.rs
> +        Some(vec![])
Done

2022-08-19 06:57 UTC, IWANABETHATGUY commented
!bench_analyzer

2022-08-19 09:41 UTC, ematipico approved these changes
@xunilrj would you mind a give a second view and merge if you think it's fine?

2022-08-22 08:07 UTC, xunilrj commented
> @xunilrj would you mind a give a second view and merge if you think it's fine?

Done.

2022-08-22 08:07 UTC, merged