no shadow restricted lint rule
rome/tools pull request #2975
Opened 2022-07-31 09:10 UTC by xunilrj

## Summary

Implements https://github.com/rome/tools/issues/2897.

## Test Plan

```
> cargo rome_cli -- check crates/rome_js_analyze/tests/specs/js/noShadowRestrictedNames.js 
```

2022-07-31 09:25 UTC, IWANABETHATGUY commented
iai result here: 
```
contains_hashset_setup
  Instructions:                9904
  L1 Accesses:                13511
  L2 Accesses:                  114
  RAM Accesses:                 149
  Estimated Cycles:           19296

contains_hashset
  Instructions:               11612
  L1 Accesses:                15644
  L2 Accesses:                  116
  RAM Accesses:                 162
  Estimated Cycles:           21894

contains_btreeset_setup
  Instructions:                8303
  L1 Accesses:                11537
  L2 Accesses:                  108
  RAM Accesses:                 125
  Estimated Cycles:           16452

contains_btreeset
  Instructions:                9743
  L1 Accesses:                13255
  L2 Accesses:                  111
  RAM Accesses:                 161
  Estimated Cycles:           19445

contains_bloom_setup
  Instructions:                7871
  L1 Accesses:                10439
  L2 Accesses:                  114
  RAM Accesses:                 151
  Estimated Cycles:           16294

contains_bloom
  Instructions:                9774
  L1 Accesses:                12717
  L2 Accesses:                  118
  RAM Accesses:                 165
  Estimated Cycles:           19082

contains_trie_setup
  Instructions:                8822
  L1 Accesses:                12334
  L2 Accesses:                  111
  RAM Accesses:                 139
  Estimated Cycles:           17754

contains_trie
  Instructions:                9430
  L1 Accesses:                13060
  L2 Accesses:                  115
  RAM Accesses:                 145
  Estimated Cycles:           18710

contains_slice_setup
  Instructions:                5886
  L1 Accesses:                 8125
  L2 Accesses:                  102
  RAM Accesses:                  84
  Estimated Cycles:           11575

contains_slice
  Instructions:                6230
  L1 Accesses:                 8526
  L2 Accesses:                  103
  RAM Accesses:                  98
  Estimated Cycles:           12471

contains_fst_setup
  Instructions:              965769
  L1 Accesses:              1334632
  L2 Accesses:                15578
  RAM Accesses:               15369
  Estimated Cycles:         1950437

contains_fst
  Instructions:              969867
  L1 Accesses:              1340279
  L2 Accesses:                15594
  RAM Accesses:               15395
  Estimated Cycles:         1957074

contains_binary_search_setup
  Instructions:                6356
  L1 Accesses:                 8756
  L2 Accesses:                   99
  RAM Accesses:                  95
  Estimated Cycles:           12576

contains_binary_search
  Instructions:                7445
  L1 Accesses:                10067
  L2 Accesses:                  100
  RAM Accesses:                 127
  Estimated Cycles:           15012

     Running benches/to_camel_case.rs (/home/hxj/Documents/rust/github/tools/target/release/deps/to_camel_case-03878c2b337402e6)
to_camel_case_rome_all_lowercase
  Instructions:                 239
  L1 Accesses:                  276
  L2 Accesses:                    1
  RAM Accesses:                  10
  Estimated Cycles:             631

to_camel_case_case_all_lowercase
  Instructions:                 569
  L1 Accesses:                  685
  L2 Accesses:                    1
  RAM Accesses:                  14
  Estimated Cycles:            1180

to_camel_case_rome_already_camel_case
  Instructions:                 239
  L1 Accesses:                  275
  L2 Accesses:                    2
  RAM Accesses:                  10
  Estimated Cycles:             635

to_camel_case_case_already_camel_case
  Instructions:                 569
  L1 Accesses:                  685
  L2 Accesses:                    2
  RAM Accesses:                  13
  Estimated Cycles:            1150

to_camel_case_rome_pascal_case
  Instructions:                 564
  L1 Accesses:                  723
  L2 Accesses:                    3
  RAM Accesses:                  25
  Estimated Cycles:            1613

to_camel_case_case_pascal_case
  Instructions:                 569
  L1 Accesses:                  684
  L2 Accesses:                    2
  RAM Accesses:                  14
  Estimated Cycles:            1184
```

2022-07-31 09:27 UTC, IWANABETHATGUY commented
Would you mind adding `memchr` to your benchmark suite? https://github.com/BurntSushi/memchr, `memchr` using the simd to accelerate your search routine.

2022-07-31 09:49 UTC, IWANABETHATGUY commented
And also I would recommend benching our suite using `criterion` again, because `memory` allocation is also a critical factor that will impact performance, It seems `iai` could not inspect the memory allocation.

2022-07-31 10:29 UTC, xunilrj commented
Results using criterion

```
contains_hashset        time:   [102.34 ns 102.40 ns 102.47 ns]   
contains_btreeset       time:   [127.64 ns 130.65 ns 134.23 ns] 
contains_bloom          time:   [336.88 ns 337.71 ns 338.64 ns]  
contains_trie           time:   [48.507 ns 48.907 ns 49.405 ns]  
contains_slice          time:   [32.514 ns 32.878 ns 33.340 ns]   
contains_fst            time:   [378.70 ns 384.44 ns 392.06 ns]  
contains_binary_search  time:   [98.531 ns 99.631 ns 100.95 ns]   
```

2022-07-31 11:00 UTC, IWANABETHATGUY commented
> Results using criterion
> 
> ```
> contains_hashset        time:   [102.34 ns 102.40 ns 102.47 ns]   
> contains_btreeset       time:   [127.64 ns 130.65 ns 134.23 ns] 
> contains_bloom          time:   [336.88 ns 337.71 ns 338.64 ns]  
> contains_trie           time:   [48.507 ns 48.907 ns 49.405 ns]  
> contains_slice          time:   [32.514 ns 32.878 ns 33.340 ns]   
> contains_fst            time:   [378.70 ns 384.44 ns 392.06 ns]  
> contains_binary_search  time:   [98.531 ns 99.631 ns 100.95 ns]   
> contains_memchr         time:   [395.70 ns 397.14 ns 399.21 ns]
> ```
> 
> and running
> 
> ```
> > cargo run -p rome_js_analyze --bin contains_iai
> ```
> 
> ```
> contains_trie
>         diff inst: 608 is 9292 - 8684
>         diff l1: 723 is 12809 - 12086
>         diff l2: 6 is 110 - 104
>         diff ram: 7 is 148 - 141
>         diff cycles: 998 is 18539 - 17541
> contains_hashset
>         diff inst: 1695 is 11465 - 9770
>         diff l1: 2121 is 15375 - 13254
>         diff l2: 0 is 115 - 115
>         diff ram: 13 is 168 - 155
>         diff cycles: 2576 is 21830 - 19254
> contains_slice
>         diff inst: 344 is 6110 - 5766
>         diff l1: 397 is 8320 - 7923
>         diff l2: 3 is 102 - 99
>         diff ram: 16 is 102 - 86
>         diff cycles: 972 is 12400 - 11428
> contains_binary_search
>         diff inst: 1089 is 7326 - 6237
>         diff l1: 1309 is 9861 - 8552
>         diff l2: 5 is 104 - 99
>         diff ram: 30 is 127 - 97
>         diff cycles: 2384 is 14826 - 12442
> contains_bloom
>         diff inst: 1903 is 9657 - 7754
>         diff l1: 2278 is 12510 - 10232
>         diff l2: 4 is 110 - 106
>         diff ram: 14 is 173 - 159
>         diff cycles: 2788 is 19115 - 16327
> contains_btreeset
>         diff inst: 1434 is 9606 - 8172
>         diff l1: 1717 is 13019 - 11302
>         diff l2: 1 is 105 - 104
>         diff ram: 33 is 161 - 128
>         diff cycles: 2877 is 19179 - 16302
> contains_fst
>         diff inst: 4154 is 949559 - 945405
>         diff l1: 5760 is 1319441 - 1313681
>         diff l2: 23 is 15577 - 15554
>         diff ram: 30 is 15410 - 15380
>         diff cycles: 6925 is 1936676 - 1929751
> contains_memchr
>         diff inst: 5975 is 12212 - 6237
>         diff l1: 7088 is 15639 - 8551
>         diff l2: 10 is 110 - 100
>         diff ram: 13 is 110 - 97
>         diff cycles: 7593 is 20039 - 12446
> ```

Nice

2022-07-31 13:50 UTC, xunilrj commented
> Nice

but quite boring! I was expecting to use fst with transducers and SIMD running in multiple GPU with Raytracing. Everything mega fast. In the end: ```slice::contains```. :smile:

2022-07-31 13:54 UTC, IWANABETHATGUY commented
> > Nice
> 
> but quite boring! I was expecting to use fst with transducers and SIMD running in multiple GPU with Raytracing. Everything mega fast. In the end: `slice::contains`. smile

lol

2022-08-01 08:16 UTC, leops commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_shadow_restricted_names.rs
> +    type Query = Semantic<JsIdentifierBinding>;
Since the rule doesn't access the semantic model it doesn't have to be scheduled in the semantic pass, it could run in the syntax pass instead

2022-08-01 08:16 UTC, leops commented on crates/rome_js_analyze/Cargo.toml
> +memchr = "2.5.0"
These are only used in the benchmark, they could be moved to the dev-dependencies

2022-08-01 08:18 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/Cargo.toml
> +memchr = "2.5.0"
Maybe this benchmark is temparory? We could remove this after verifying the performance

2022-08-01 12:05 UTC, xunilrj commented on crates/rome_js_analyze/Cargo.toml
> +memchr = "2.5.0"
Done.

2022-08-02 06:39 UTC, ematipico requested changes
I just realized now that this rule was removed from rome classic (the documentation was not deleted). I can't remember why it was removed though. Should we keep the rule?  @sebmck , do you remember why it was removed?

2022-08-02 06:39 UTC, ematipico commented on crates/rome_js_analyze/Cargo.toml
> +regex = { version = "1.6.0" }
This crate should be moved in `dev-dependencies`

2022-08-02 06:39 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_shadow_restricted_names.rs
> +const RESTRICTEDNAMES: [&str; 9] = [
`RESTRICED_NAMES`

2022-08-02 06:39 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_shadow_restricted_names.rs
> +    "JSON",
I believe the list of restricted names is not enough. Here's what we had in rome classic: https://github.com/rome/tools/blob/archived-js/internal/compiler/scope/globals.ts

2022-08-02 06:50 UTC, MichaReiser reviewed
Woah, awesome work on the extensive benchmark !

2022-08-02 06:50 UTC, MichaReiser commented on crates/rome_js_analyze/Cargo.toml
> +regex = { version = "1.6.0" }
Is it necessary to add regex as a prod dependency. Isn't it only used as part of the benchmarks?

2022-08-02 06:50 UTC, MichaReiser commented on crates/rome_js_analyze/Cargo.toml
> +bench = false
This is adding a lot of dependencies only for the sake fo the benchmark. How about you split out the benchmark out into its own PR and close it (without merging). This would keep the benchmark around for historic sake (you could e.g. add a link in a comment) without pulling in a large number of new dependencies.

2022-08-02 06:53 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/Cargo.toml
> +bench = false
agree

2022-08-03 11:49 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_shadow_restricted_names.rs
> +    type Query = Semantic<JsIdentifierBinding>;
Done.

2022-08-03 11:54 UTC, xunilrj commented on crates/rome_js_analyze/Cargo.toml
> +bench = false
I can move this to xtask/bench, given that this is a generic benchmark. I think will be nice to keep this around, as we will have multiple cases of these "micro benchmarks"

2022-08-03 14:05 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/js/no_shadow_restricted_names.rs
> +    "JSON",
And which version do we want? Does the configuration file have the version?

2022-08-03 14:06 UTC, xunilrj commented on crates/rome_js_analyze/Cargo.toml
> +regex = { version = "1.6.0" }
I moved everything to another crate.

2022-08-03 14:35 UTC, xunilrj commented
!bench_analyzer

2022-08-03 16:05 UTC, leops approved these changes

2022-08-03 17:03 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_shadow_restricted_names.rs
> +    "JSON",
We don't have it yet, I suppose it will become more important once we have transformations.

So for the moment we should use the latest version, because we target/support up to ES2022.

2022-08-03 17:04 UTC, ematipico approved these changes

2022-08-03 21:40 UTC, merged