feat(playground): embbed codemirror-lang-rome-ast
rome/tools pull request #2977
Opened 2022-07-31 13:41 UTC by IWANABETHATGUY

## Summary
1. From https://github.com/rome/tools/pull/2974#pullrequestreview-1056350592

## Test Plan
1. Testing locally

2022-07-31 13:41 UTC, IWANABETHATGUY commented
@MichaReiser , I think this is what you want.

2022-08-01 06:03 UTC, IWANABETHATGUY commented
I build successfully locally,  I have no idea what's going on with CI, I give up now.
Feel free to close this pull request.

2022-08-02 07:11 UTC, ematipico requested changes
Could you please check the CI? It's failing

2022-08-02 07:11 UTC, ematipico commented on website/playground/package.json
> +		"codemirror-lang-rome-ast": "file:./lang-rome-ast",
pnpm has support for workspaces, which we should use for this  particular case: https://pnpm.io/pnpm-workspace_yaml

2022-08-02 07:11 UTC, ematipico commented on website/playground/lang-rome-ast/package.json
> +    "rome": "0.7.0-next.f6510d6"
```suggestion
    "rome": "next"
```

2022-08-02 07:11 UTC, ematipico commented on website/playground/lang-rome-ast/package.json
> +    "url": "https://github.com/IWANABETHATGUY/lang-rome-ast"
I presume this is a leftover of your repo?

2022-08-02 07:11 UTC, ematipico commented on website/playground/lang-rome-ast/.gitignore
> +dist
So we know they are folders

```suggestion
node_modules/
dist/
```

2022-08-02 07:13 UTC, IWANABETHATGUY commented on website/playground/package.json
> +		"codemirror-lang-rome-ast": "file:./lang-rome-ast",
I will check this out when I have time, converting it to draft now.

2022-08-05 03:30 UTC, IWANABETHATGUY commented
This pull request is too messy, I would open it again once I found a solution.

2022-08-05 03:30 UTC, closed without merging