feat(rome_js_analyze): no unused variable
rome/tools pull request #2987
Opened 2022-08-02 09:22 UTC by xunilrj

## Summary

Closes https://github.com/rome/tools/issues/2979.

## Test Plan

```
>  cargo run -p rome_cli -- check crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js 
```

2022-08-02 09:35 UTC, xunilrj commented
!bench_analyzer

2022-08-02 13:21 UTC, ematipico requested changes
There are few issues with functions, we have diagnostics when in reality they are valid cases.

2022-08-02 13:21 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js.snap
> +8   | - }
I think this incorrect? `f2` is actually used, inside itself (recursion)

2022-08-02 13:21 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js.snap
> +16    | -
`f3` is actually used, so we can't remove it.

2022-08-02 13:21 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js.snap
> +21 │ function f42(a, b) {
Could we add a test case where we have a trailing comma? `function f(a,b,){}`

2022-08-02 13:21 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js.snap
> +27    | - const f6 = () => {
`f6` is actually used

2022-08-02 13:22 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs
> +            Some(())
Why `Some` instead of `None`?

2022-08-02 13:48 UTC, xunilrj commented on crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js.snap
> +8   | - }
This is on purpose because is not called from the outside.

2022-08-02 13:48 UTC, xunilrj commented on crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js.snap
> +16    | -
Same thing here. ```f3``` is never called from the outside.

2022-08-02 13:58 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs
> +            Some(())
If there are no references, so it is unused.

2022-08-02 15:44 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs
> +            category: ActionCategory::Refactor,
Why is this a `Refactor` and not a `QuickFix`? Just asking because I don't know yet the difference

2022-08-02 15:44 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs
> +            message: markup! { "Remove dead code." }.to_owned(),
The message might be misleading, because we also have a rule called `noDeadCode`. Would it be possible to have better messaging?

2022-08-03 06:01 UTC, xunilrj commented on crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js.snap
> +21 │ function f42(a, b) {
I create more tests for the "remove_*" methods, instead of polluting this one here.
https://github.com/rome/tools/pull/2987/files#diff-0902796fee286e39e6f27f612b14a08a77e0af0dee55c59871e1a0292707c0faR110

2022-08-03 06:49 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs
> +            applicability: Applicability::Unspecified,
> what does it mean for the end user? Can an user apply the change via CLI?
No.

I am torn apart between ```Unspecified```and ```MaybeIncorrect```. I assumed that removing unused code is not the "best" solution.

2022-08-03 06:51 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs
> +            category: ActionCategory::Refactor,
You are right. I think "Quickfix" makes more sense.

2022-08-03 06:51 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs
> +            message: markup! { "Remove dead code." }.to_owned(),
Done.

2022-08-03 06:52 UTC, xunilrj commented on crates/rome_js_analyze/tests/specs/js/noUnusedVariables.js.snap
> +27    | - const f6 = () => {
Same thing as above. It is only used internally. Which means it is never called.

2022-08-03 07:11 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs
> +        version: "0.8.0",
This should be `0.9.0` now

2022-08-03 07:34 UTC, leops commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs
> +            applicability: Applicability::Unspecified,
The semantics of `Applicability` is something we'll need to review when we rework the diagnostics, the current version of the enum is inherited directly from `rslint` and indirectly `rustc`, but those tools are using text-based suggestions instead of tree-based.
In this case I think the `Unspecified` applicability comes from `rustc`, where the concept of "applicability" was added when the compiler already has a bunch of existing suggestions, so all those diagnostics were set to `Unspecified` in the refactor to be manually reviewed later on.
In our case though we should always document if a suggestion is safe to apply or not, so in practice the only variants of `Applicability` we should be using a `MaybeIncorrect` and `Always` (the difference is that `Unspecified` can never be applied automatically, while `MaybeIncorrect` can after the has the user has reviewed it)

2022-08-03 09:10 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/js/no_unused_variables.rs
> +        version: "0.8.0",
Done.

2022-08-03 09:30 UTC, ematipico approved these changes
Looks good to me. We should address the applicability of the rule.

2022-08-03 10:37 UTC, merged