fix: 🐛 codemirror grammar for Rome Ast
rome/tools pull request #3020
Opened 2022-08-06 09:52 UTC by IWANABETHATGUY

## Summary
1. FIx serval grammar cases see video below: 
**before:** 
https://user-images.githubusercontent.com/17974631/183243914-6d092090-b7a6-40e5-851c-a63411b9cf94.mp4
**after:** 
https://user-images.githubusercontent.com/17974631/183243908-c7f9e751-0f47-4874-a7c7-b1b5dfa25d3d.mp4

## Test Plan

2022-08-06 10:49 UTC, IWANABETHATGUY commented on rome.json
> +{
This is just a workaround due to our `rome ci` command will not recursive merge `rome.json` config when meet a directory, only look up the `${cwd}/rome.json`

2022-08-06 10:50 UTC, IWANABETHATGUY commented on rome.json
> +          "noUnusedVariables": "off"
Disable `noUnusedVariables` for now, due to too much false positive cases.

2022-08-06 10:55 UTC, IWANABETHATGUY commented on website/playground/package.json
> -		"rome": "^0.7.0-next",
I remove it because we already install `rome` at the parent directory `website`

2022-08-06 11:54 UTC, MichaReiser commented on website/playground/package.json
> -		"rome": "^0.7.0-next",
That will mean that anyone building the playground first must run `pnpm install` in the `website` directory and in the `playground` directory as well. 

I think we should either:
* Move the playground dependencies into the website package.json
* Change the module structure so that `website` and `playground` become siblings 
* Leave it as is

I would recommend to keep it as is and push any improvements in another PR

2022-08-08 07:10 UTC, MichaReiser requested changes

2022-08-08 07:10 UTC, MichaReiser commented on editors/vscode/package-lock.json
> +	"version": "0.12.0",
Can we move unrelated changes to its own PR? It otherwise makes it difficult to understand what this change is about.

2022-08-08 07:10 UTC, MichaReiser commented on rome.json
> +          "noUnusedVariables": "off"
CC: @xunilrj

2022-08-08 07:10 UTC, MichaReiser commented on website/package.json
> +		"@types/node": "^18.6.1",
Would you mind undoing all the changes to this file?

2022-08-08 07:10 UTC, MichaReiser commented on website/pnpm-lock.yaml
> +  rome: 0.8.0-next.ff4153b
This should be undone now that the package json has been reverted too

2022-08-09 05:03 UTC, IWANABETHATGUY commented
Closed, will reopen it in another pr.

2022-08-09 05:03 UTC, closed without merging

2022-08-09 05:45 UTC, IWANABETHATGUY commented
Reopen here https://github.com/rome/tools/pull/3032