fix: 🐛 error
rome/tools pull request #3022
Opened 2022-08-06 16:44 UTC by IWANABETHATGUY

## Summary

## Test Plan

2022-08-06 16:48 UTC, IWANABETHATGUY commented
!bench_parser

2022-08-07 02:18 UTC, IWANABETHATGUY commented
!bench

2022-08-07 02:24 UTC, IWANABETHATGUY commented
!bench_parser

2022-08-08 07:07 UTC, MichaReiser requested changes
I find it difficult to understand what this PR is changing. 

Please add a more descriptive summary explaining which syntax was invalid before and is valid now.

2022-08-08 07:07 UTC, MichaReiser commented on crates/rome_js_parser/src/syntax/function.rs
> +                binding.or_add_diagnostic(p, expected_binding);
Does that mean that the binding is required in none `export` context and is otherwise optional. 

Our AST strictly encodes optionality. E.g. see `JsFunctionExportDefaultDeclaration` for a function where the `id` is optional opposed to `JsFunctionDeclaration` where it is not. 

We may need to apply the same approach here but I must first better understand what this PR is solving/ changing.

2022-08-10 13:00 UTC, IWANABETHATGUY commented on crates/rome_js_parser/src/syntax/function.rs
> +                binding.or_add_diagnostic(p, expected_binding);
> Does that mean that the binding is required in none `export` context and is otherwise optional.
> 
> Our AST strictly encodes optionality. E.g. see `JsFunctionExportDefaultDeclaration` for a function where the `id` is optional opposed to `JsFunctionDeclaration` where it is not.
> 
> We may need to apply the same approach here but I must first better understand what this PR is solving/ changing.

Sorry for the late replay, 
1. For the first question yes.
2. I like your idea.

2022-09-14 12:04 UTC, closed without merging