feat(rome_js_formatter): implement option preserve_quotes
rome/tools pull request #3065
Opened 2022-08-16 10:26 UTC by bhbs

## Summary

This PR implements option preserve_quotes following Prettier. ([docs](https://prettier.io/docs/en/options.html#quote-props))
I referred to `--quote-style` for the implementation of the option.

Close #2482 

## Test Plan

- Check new snapshots
  - crates/rome_js_formatter/tests/specs/js/module/string/properties_quotes.js.snap
  - crates/rome_js_formatter/tests/specs/ts/string/parameter_quotes.ts.snap

2022-08-16 10:36 UTC, bhbs commented on crates/rome_js_formatter/tests/specs/js/module/assignment/assignment.js.snap
> -assertion_line: 259
`assertion_line` is no longer retained in snapshots after cargo-insta v1.13.0
https://github.com/mitsuhiko/insta/issues/215

2022-08-16 10:38 UTC, bhbs commented on crates/rome_js_formatter/tests/specs/js/module/assignment/assignment.js.snap
> -assertion_line: 259
`assertion_line` is no longer retained in snapshots after cargo-insta v1.13.0
https://github.com/mitsuhiko/insta/issues/215

2022-08-16 10:39 UTC, bhbs commented
After this PR is merged, I’d like to implement this option to VSCode Extension and playground!

2022-08-16 10:51 UTC, ematipico commented
> After this PR is merged, I’d like to implement this option to VSCode Extension and playground!

The VSCode extension now always reads the configuration from `rome.json`. We removed all the beta options. Only the playground needs it

2022-08-16 11:12 UTC, MichaReiser reviewed
Overall looking good to me. My main suggestion is to change the option to an enum so that it can be extended in the future

2022-08-16 11:12 UTC, MichaReiser commented on crates/rome_js_formatter/src/context.rs
> +    preserve_quotes: bool,
I would prefer an enum over a bool so that it becomes possible to support all variants that prettier supports without a breaking change:

* preserve
* as-needed (what Rome does today. Default)
* consistent (out of scope)

I would also rename the setting to `quote-properties` to closer match prettier's naming

2022-08-16 11:49 UTC, bhbs commented on crates/rome_js_formatter/src/context.rs
> +    preserve_quotes: bool,
Thanks for the review. I will change it!

2022-08-16 14:00 UTC, ematipico requested changes

2022-08-16 14:00 UTC, ematipico commented on crates/rome_service/src/configuration/javascript.rs
> +    pub preserve_quotes: bool,
Could you add some documentation, please?

2022-08-16 14:00 UTC, ematipico commented on website/src/_includes/docs/project-config.md
> +
Same here, this change should be reverted.

2022-08-16 14:30 UTC, bhbs commented
@MichaReiser @ematipico 
Thank you for reviewing!
I addressed your feedback👍

2022-08-17 07:51 UTC, ematipico reviewed
Could you add a new test inside `rome_cli/tests/` where we test an error when passing a wrong value for `--quote-properties`? The test should go inside `mod formatter`. And we can have a snapshot of it, so we can actually see the error message

2022-08-17 07:51 UTC, ematipico commented on crates/rome_service/src/configuration/javascript.rs
> +}
```suggestion
#[derive(Deserialize, Default, Serialize, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase", remote = "QuoteProperties")]
pub enum PlainQuoteProperties {
    #[default]
    AsNeeded,
    Preserve,
}
```

We can now use macros to assign defaults to enum!

2022-08-17 13:30 UTC, bhbs commented on crates/rome_service/src/configuration/javascript.rs
> +}
Cool 🦀

2022-08-17 16:33 UTC, MichaReiser commented on crates/rome_service/src/configuration/javascript.rs
> +}
It may be better to call `QuoteStyle::default` here to make sure these two are always in sync. Not sure if there's a `From` implementation that easily allows you to do so.

2022-08-17 16:34 UTC, bhbs commented
@ematipico 
Did you intend like this? a6a89ab

2022-08-17 17:46 UTC, ematipico commented
> @ematipico 
> Did you intend like this? a6a89ab

Yes, that's it :)

It's okay if it's empty, I plan to change it soon. At least it's ready and there

2022-08-17 17:54 UTC, bhbs commented on crates/rome_service/src/configuration/javascript.rs
> +}
Sorry, I'm not sure, please tell me how to do it

2022-08-18 05:55 UTC, MichaReiser approved these changes

2022-08-18 06:47 UTC, ematipico approved these changes
This is a great contribution! Thank you very much!

2022-08-18 06:48 UTC, merged