feat(rome_js_analyze): no new Symbol
rome/tools pull request #3201
Opened 2022-09-12 02:44 UTC by magic-akari

## Summary

Add new lint rule: noNewSymbol

https://eslint.org/docs/latest/rules/no-new-symbol

## Test Plan

```
cargo test -p rome_js_analyze
```

2022-09-12 09:25 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +        version: "0.7.0",
This should be `0.10.0`

2022-09-12 09:25 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +        let name = ident.text();
We should use `text_trimmed`. `text_trimmed` returns the text **without** the trivias, while `text` returns the text with its trivias attached.

2022-09-12 09:25 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/js/noNewSymbol.js
> +var foo = new Symbol('foo');
Can we add few more tests?

One without arguments:

```js
var bar = new Symbol();
```

One with comments:
```js
var lorem = new Symbol() // comment
```

2022-09-12 09:49 UTC, magic-akari commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +        let name = ident.text();
get error:
```
no method named `text_trimmed` found for reference `&rome_js_syntax::JsIdentifierExpression` in the current scope
method not found in `&rome_js_syntax::JsIdentifierExpression`
```

2022-09-12 09:57 UTC, magic-akari commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +        let name = ident.text();
https://github.com/rome/tools/blob/737551c9fd4eb56ea9af26fbc56415c7360a27d1/crates/rome_rowan/src/ast/mod.rs#L236-L239

Looks like it's already be `trimmed`.

2022-09-12 10:02 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +        let name = ident.text();
Ah yes, you should call `ident.syntax().text_trimmed()`. Here's an example of how it's used inside another rule: https://github.com/rome/tools/blob/main/crates/rome_js_analyze/src/analyzers/js/no_extra_boolean_cast.rs#L114

2022-09-12 10:03 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +        let name = ident.text();
> https://github.com/rome/tools/blob/737551c9fd4eb56ea9af26fbc56415c7360a27d1/crates/rome_rowan/src/ast/mod.rs#L236-L239
> 
> Looks like it's already be `trimmed`.

That's great! I completely missed that API :)

2022-09-12 17:29 UTC, MichaReiser requested changes

2022-09-12 18:00 UTC, magic-akari commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +        let name = ident.text();
@MichaReiser I love this idea.

2022-09-13 06:23 UTC, magic-akari commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
You are right. The `/* test */` is removed.
What's the expected behaviour? Should it be preserved?
And how to move the comments?

2022-09-13 06:55 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
Because `/*test*/` is part of trailing trivia of `new` token, removing the `new` token will lead the comments to be dropped. You should take the trailing trivia of `new` token and put them at the front of the leading trivia of `callee`

2022-09-13 06:56 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
FYI, https://github.com/rome/tools/blob/584c468c6d9bdd2a0c425a19b8b192a08dc7e7a8/crates/rome_js_analyze/src/analyzers/js/use_block_statements.rs#L172-L183

2022-09-13 09:39 UTC, magic-akari commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
There is something strange, leading_trivia is not being output.

code:
```rust
fn convert_new_expression_to_call_expression(expr: &JsNewExpression) -> Option<JsCallExpression> {
    let JsNewExpressionFields {
        new_token,
        callee,
        arguments,
        ..
    } = expr.as_fields();

    let new_token = new_token.ok()?;
    let callee = callee.ok()?;
    let arguments = arguments?;

    let trivia = new_token.trailing_trivia();

    dbg!(&trivia);

    let first_token = callee.syntax().first_token()?;
    dbg!(&first_token);
    dbg!(&callee);

    let callee = callee.replace_token_discard_trivia(
        first_token.clone(),
        first_token.with_leading_trivia_pieces(trivia.pieces()),
    )?;

    dbg!(&callee);

    Some(make::js_call_expression(callee, arguments).build())
}
```

test file
```JavaScript 
var s = /* prefix_cmt */ new /* suffix_cmt */ Symbol() // comment
```

test log
```
[crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs:108] &trivia = [Whitespace(" "), Comments("/* suffix_cmt */"), Whitespace(" ")]
[crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs:111] &first_token = IDENT@46..52 "Symbol" [] []
[crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs:112] &callee = JsIdentifierExpression {
    name: JsReferenceIdentifier {
        value_token: IDENT@46..52 "Symbol" [] [],
    },
}
[crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs:119] &callee = JsIdentifierExpression {
    name: JsReferenceIdentifier {
        value_token: IDENT@0..24 "Symbol" [Whitespace(" "), Comments("/* suffix_cmt */"), Whitespace(" ")] [],
    },
}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/rome_js_analyze/tests/specs/js/noNewSymbol.js.snap
Snapshot: noNewSymbol.js
Source: crates/rome_js_analyze/tests/spec_tests.rs:97
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: noNewSymbol.js
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+new results
────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          0 │+# Input
          1 │+```js
          2 │+var s = /* prefix_cmt */ new /* suffix_cmt */ Symbol() // comment
          3 │+```
          4 │+
          5 │+# Diagnostics
          6 │+```
          7 │+warning[js/noNewSymbol]: Symbol cannot be called as a constructor.
          8 │+  ┌─ noNewSymbol.js:1:26
          9 │+  │
         10 │+1 │ var s = /* prefix_cmt */ new /* suffix_cmt */ Symbol() // comment
         11 │+  │                          -----------------------------
         12 │+
         13 │+Suggested fix: Remove new.
         14 │+    | @@ -1 +1 @@
         15 │+0   | - var s = /* prefix_cmt */ new /* suffix_cmt */ Symbol() // comment
         16 │+  0 | + var s = /* prefix_cmt */ Symbol() // comment
         17 │+
         18 │+
         19 │+```
         20 │+
────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

The `/* suffix_cmt */` has been moved into Symbol's leading_trivia. But I cannot find it in the output.

2022-09-13 09:41 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
@leops , Would you mind having a look?

2022-09-13 09:46 UTC, magic-akari commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
And `with_trailing_trivia_pieces` works well.

```rust
  let callee = callee.replace_token_discard_trivia(
      first_token.clone(),
      first_token.with_trailing_trivia_pieces(trivia.pieces()),
  )?;
```

This will move the new_token trailing_trivia into `Symbol` trailing_trivia.

test log
```
────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          0 │+# Input
          1 │+```js
          2 │+var s = /* prefix_cmt */ new /* suffix_cmt */ Symbol() // comment
          3 │+```
          4 │+
          5 │+# Diagnostics
          6 │+```
          7 │+warning[js/noNewSymbol]: Symbol cannot be called as a constructor.
          8 │+  ┌─ noNewSymbol.js:1:26
          9 │+  │
         10 │+1 │ var s = /* prefix_cmt */ new /* suffix_cmt */ Symbol() // comment
         11 │+  │                          -----------------------------
         12 │+
         13 │+Suggested fix: Remove new.
         14 │+    | @@ -1 +1 @@
         15 │+0   | - var s = /* prefix_cmt */ new /* suffix_cmt */ Symbol() // comment
         16 │+  0 | + var s = /* prefix_cmt */ Symbol /* suffix_cmt */ () // comment
         17 │+
         18 │+
         19 │+```
         20 │+
────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

2022-09-13 09:49 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
Yes, you are right, that was a trailing trivia. In case you have doubts, you can use the playground. Each token/keyword usually have two `[] []` where we print trivias. The first `[]` contains leading trivias that belong to that token/keyword, the second `[]` contains the trailing trivia that belong to that token/keyword.

As golden rule, always use the playground to make sure how trivias are categorized by our parser.

2022-09-13 09:52 UTC, magic-akari commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
@ematipico Is `leading_trivia` being ignored in the output?

2022-09-13 09:57 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
No, usually they are not ignored

2022-09-13 09:58 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
Same issue here, I am not sure if this is a problem with our SyntaxTree mutation.

2022-09-13 10:12 UTC, leops commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
I'm not exactly sure what the issue is here, but in this case I think manually handling the trivia requires some extra care to not drop any trivia piece: specifically, using `replace_token_discard_trivia` and `with_trailing_trivia_pieces` this way will replace the trivia of the `first_token` with the trivia of the `new_token`, dropping any trivia this token may have had previously. In order to be safe the token being replace must include all the trivia pieces from the new token as well as its own:
```rust
callee.replace_token_discard_trivia(
    first_token.clone(),
    first_token.with_leading_trivia(
        new_token.leading_trivia().pieces()
            .chain(new_token.trailing_trivia().pieces())
            .chain(first_token.leading_trivia().pieces()),
    ),
);
```

2022-09-13 10:21 UTC, magic-akari commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
Yes, I did merge them.
And call `new_token.has_trailing_comments()` before merge.
But when I found that the output was not what I expected.
Therefore I removed the unimportant code line by line to make it easier to debug.

2022-09-13 10:26 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
> I'm not exactly sure what the issue is here, but in this case I think manually handling the trivia requires some extra care to not drop any trivia piece: specifically, using `replace_token_discard_trivia` and `with_trailing_trivia_pieces` this way will replace the trivia of the `first_token` with the trivia of the `new_token`, dropping any trivia this token may have had previously. In order to be safe the token being replace must include all the trivia pieces from the new token as well as its own:
> 
> ```rust
> callee.replace_token_discard_trivia(
>     first_token.clone(),
>     first_token.with_leading_trivia(
>         new_token.leading_trivia().pieces()
>             .chain(new_token.trailing_trivia().pieces())
>             .chain(first_token.leading_trivia().pieces()),
>     ),
> );
> ```

Panic after using your snippet code.
```
thread 'specs::js::no_new_symbol_js' panicked at 'assertion failed: `(left == right)`
  left: `"// valid\nvar bar = Symbol('bar');\nfunction baz() {\n    function Symbol() { }\n    new Symbol();\n}\n// invalid\nvar foo = Symbol('foo');\nvar foo2 = new Symbol();\nvar lorem = new Symbol() // comment\nvar s = /* prefix_cmt */ new /* suffix_cmt */ Symbol() // comment\n\nnew \n  /** test */ Symbol();"`,
 right: `"// valid\nvar bar = Symbol('bar');\nfunction baz() {\n    function Symbol() { }\n    new Symbol();\n}\n// invalid\nvar foo = new Symbol('foo');\nvar foo2 = new Symbol();\nvar lorem = new Symbol() // comment\nvar s = /* prefix_cmt */ new /* suffix_cmt */ Symbol() // comment\n\nnew \n  /** test */ Symbol();"`', crates/rome_js_analyze/tests/spec_tests.rs:156:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test specs::js::no_new_symbol_js ... FAILED
```

Would you mind pulling his branch? It seems really weird, I never meet this issue before.

2022-09-13 10:37 UTC, magic-akari commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
@IWANABETHATGUY 

I didn't fix the type for now, so this is the code I used.

```rust
let mut trivia = vec![];
trivia.extend(new_token.leading_trivia().pieces());
trivia.extend(new_token.trailing_trivia().pieces());
trivia.extend(first_token.leading_trivia().pieces());

let callee = callee.replace_token_discard_trivia(
    first_token.clone(),
    first_token.with_leading_trivia_pieces(trivia),
)?;
```

but nothing changed.

2022-09-13 11:04 UTC, IWANABETHATGUY commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
I use your code and still panic.

2022-09-13 14:46 UTC, leops commented on crates/rome_js_analyze/src/analyzers/js/no_new_symbol.rs
> +    let arguments = arguments?;
Oh right since you're handling trivia manually, you also need to use the `replace_node_discard_trivia` method of `BatchMutation` to replace the new expression with a call expression, otherwise the mutation will overwrite the leading and trailing trivia of the node

2022-09-13 15:59 UTC, ematipico commented
@magic-akari we just merged a PR that changes how the rules are grouped. Could you please update the PR and move this rule under the `nursery` group?

2022-09-14 09:33 UTC, leops approved these changes

2022-09-14 09:59 UTC, ematipico approved these changes
The PR looks good to me!

In order to make the CI pass, you will need to run the following commands:
- `cargo codegen-bindings`
- `cargo codegen-configuration`
- `cargo codenge-schema`

We probably add some other alias to run all these commands all together

2022-09-15 09:44 UTC, MichaReiser approved these changes

2022-09-15 09:44 UTC, merged