feat(rome_js_analyzer): `useButtonType`
rome/tools pull request #3238
Opened 2022-09-16 11:32 UTC by ematipico

## Summary

## Test Plan

2022-09-19 07:30 UTC, MichaReiser approved these changes
What's the motivation behind renaming `util` to `shared`. I don't think it solves any of the problems that I see with a `util`/`shared`/`common`/`arbitrary`.... folder

I also think that it would be helpful to split the utils refactor into its own PR if we want to move forward with it as it is unrelated to the other changes in this PR.

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                // we bail early the current tag is not a button; case sensitive is important
I think it would be important to explain why `case sensitive` is important rather than just saying that it is.

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                if name.syntax().text_trimmed() == "button" {
`text_trimmed` is somewhat expensive on a node because it must:

* find the first and last token
* Allocate a `SyntaxNodeText` and then do the comparison

The good thing is, you can simplify this (and remove the case sensitiveness as well) by explicitly matching on the `JsxAnyElementName`. The only variant that is of importance for this rule is `JsxName` 

```
fn is_button(name: &JsxAnyElementName) -> bool {
  match name {
    JsxAnyElementName::JsxName(name) => {  
      name.value_token().map_or(false, |name| name.text_trimmed() == "button")
    },
    _ => false
  }
}
```

You can then access the `name` token directly which should be significantly faster

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                    if attributes.len() == 0 {
Nit
```suggestion
                    if attributes.is_empty() {
```

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                        }
Nit: I would find it clearer to read if this is split into two:

1. Finding the `type` attribute (using `find`)
2. Handling the value of a potentially invalid type attribute


What is the expected outcome for repeated `type` attributes or when used with jsx spread where it is unclear if the type will be overridden. 

```js
<button type="test" type="button" />
<button type="button", type="test" />
<button type="button" {...rest} />
```

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                            let name = jsx_name.syntax().text_trimmed();
Same here: Can you access the `value_token` instead and get the trimmed text from their

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                if is_create_element {
The caller of `is_create_element` still needs a lot of knowledge about how `is_react_create_element` works internally. 

Would it make sense to change `is_react_create_element` to instead return a `struct` with the information necessary for the caller and it would be possible to pass any `JsAnyExpression` to `is_react_create_element`

```rust
fn is_react_create_element(expression: &JsAnyExpression) -> Option<ReactCreateElementCall> {
  .. 
}

struct ReactCreateElementCall { 
  typeName: JsAnyExpression,
  props: JsObjectExpression,
  children: Option<JsArrayExpression>
}
```

This would simplify a lot of the code below

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                                    if property_name.name().ok()? == "type" {
Nit: Same as for the attribute. I would find this easier to read if it is split into two:

1. Finding a member called `type`
2. Testing if it is an allowed button type

What's the expected outcome for

```javascript
react.createElement('button', {
  type: "button",
  ...more,
})
```

Where it is unknown if `...more` overrides `type`. 

or 

```javascript
react.createElement('button', {
  type: "button",
  type: "rubbish",
}
```

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                                return Some(UseButtonTypeState::from(second_argument.clone()));
Why is it that it must return an error in the case the `type` is missing. My understanding is that `button` without a type is valid HTML.

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                                // we have return an error
```suggestion
                                // we have to return an error
```

Why?

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                "The default type of a button is "<Emphasis>"submit"</Emphasis>", which causes a page reload and is not a typical behavior in a React application."
This sounds as if `submit` should never be used but this isn't true. Not using `submit` results in degraded accessibility and it is better to prevent the default handler of the form. 

This message is also somewhat confusing where the help text proposes to use `submit`. Should I now use it or not?

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_syntax/src/jsx.rs
> +use rome_rowan::{SyntaxResult, SyntaxTokenText};
All other files implementing extensions use the `syntax_ext` pattern

2022-09-19 07:30 UTC, MichaReiser commented on crates/rome_js_syntax/src/jsx.rs
> +    /// Get the inner text of a string not including the quotes
Could you add a doctest example to the new API

2022-09-19 07:31 UTC, MichaReiser requested changes
Wrong button... How can I undo an approve and change it to comment xD

2022-09-19 08:51 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                                return Some(UseButtonTypeState::from(second_argument.clone()));
The rule is meant to **enforce** the use the of `type` on a `button` element. While doing `<button>Button</button>` is correct, most of the times is not what the user meant

2022-09-19 08:52 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                "The default type of a button is "<Emphasis>"submit"</Emphasis>", which causes a page reload and is not a typical behavior in a React application."
The message comes from Rome classic, so I assumed that the message was already vetted. Can you suggest some change please?

2022-09-19 09:18 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                "The default type of a button is "<Emphasis>"submit"</Emphasis>", which causes a page reload and is not a typical behavior in a React application."
I think there are two fundamental issues with the messaging:

a) It uses the same message for the case where there is no type and there's a potentially invalid type. We should split the two (e.g. the message seems out of place if I wrote `button type="rest"`)
b) What I pointed out before. that it sounds like `submit` is always the incorrect button type. Have you checked out the eslint plugin react?

2022-09-19 09:58 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                        }
The expected outcome for this rule is to work on a single prop only. The rule is not in charge of checking these cases:
1. a repeated property is broader issue, and maybe we could evaluate a rule for that case;
2. we don't have enough information to check  - **as for today** - the safety of `...rest`

2022-09-19 10:05 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                        }
> (using `find`)

I am not sure this will improve the readability. In order to find the correct attribute using `.find`, we have to manually **handle six `Option`** types without the try operator.

2022-09-19 10:42 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                "The default type of a button is "<Emphasis>"submit"</Emphasis>", which causes a page reload and is not a typical behavior in a React application."
> Have you checked out the eslint plugin react?

It's not as explicit as we are

2022-09-20 09:21 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                        }
You can use `find_map` and you can then use the `try` operator

2022-09-20 10:50 UTC, leops commented on crates/rome_js_analyze/src/react.rs
> +/// from the `"react"` module.
I couldn't find the point in the function where we check that the source of the import is "react", where does that happen ?

2022-09-20 10:50 UTC, leops commented on crates/rome_js_analyze/src/react.rs
> +                            maybe_from_react = binding_identifier.syntax().text_trimmed()
Looking only at the text of the identifier instead of its "semantic provenance" seems a bit fragile, while these are probably not common we could handle a few other cases such as:
```js
import OtherName from "react";
OtherName.createElement();
```
```js
import { createElement as otherName } from "react";
otherName();
```
And I think we should also have a test for this pattern:
```js
import * as React from "react";
React.createElement();
```

2022-09-20 10:51 UTC, ematipico commented on crates/rome_js_analyze/src/react.rs
> +/// from the `"react"` module.
This fix will be applied in https://github.com/rome/tools/pull/3256

2022-09-20 10:57 UTC, ematipico commented on crates/rome_js_analyze/src/react.rs
> +/// from the `"react"` module.
I am going to port the fix in this PR

2022-09-20 12:06 UTC, MichaReiser reviewed
The implementation looks good to me but I still think the rule is misleading and results in users favouring `button` over `submit` which results in a degraded accessibility.

2022-09-20 12:06 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_button_type.rs
> +                "The default  "<Emphasis>"type"</Emphasis>" of a button is "<Emphasis>"submit"</Emphasis>", which causes the submission of a form when placed inside a `form` element. "
Thanks for iterating on the message. 

I'm still conflicted by the rule. Using a button with type submit is exactly what you want inside of a form for accessibility reasons. However, this message incentivices users to not use `submit`.... 

To make it worse, this rule will be in direct conflict with an a11 rule that recommends having at least one `submit` button in every form.

2022-09-20 12:06 UTC, MichaReiser approved these changes

2022-09-20 12:25 UTC, ematipico commented
> The implementation looks good to me but I still think the rule is misleading and results in users favouring `button` over `submit` which results in a degraded accessibility.

Should we just remove the footer note?

2022-09-20 14:13 UTC, merged