feat(playground): enable nursery lint rules
rome/tools pull request #3242
Opened 2022-09-16 13:05 UTC by ematipico

## Summary

This PR adds a new checkbox to the playground to enable nursery rules. This allows us to debug these rules that are still in development. 

I didn't bother much about where to put that checkbox... I am sure we would need an overhaul of the UI, in a separate place.

## Test Plan

Play with the deployed background

2022-09-16 14:09 UTC, MichaReiser requested changes

2022-09-16 14:09 UTC, MichaReiser commented on website/playground/package.json
> +		"check": "cd ../../ && cargo rome-cli-dev check ./website/playground/src",
Why has it become necessary to traverse upwards?

2022-09-16 14:09 UTC, MichaReiser commented on website/playground/package.json
> -		"rome": "next",
What's the reason behind removing the `rome` dependency

2022-09-16 14:09 UTC, MichaReiser commented on website/playground/src/NurseryRules.tsx
> +export default function NurseryRules({
![image](https://user-images.githubusercontent.com/1203881/190657906-84975f7b-834a-4002-9f38-444af5f134db.png)

The check box isn't properly aligned with the other check boxes

2022-09-16 14:09 UTC, MichaReiser commented on website/playground/src/romeWorker.ts
>  						},
Is there no other way to enable all nursery rules? How to we prevent having to change this list with every new nursery rule that we add (or remove)?

2022-09-16 14:13 UTC, ematipico commented on website/playground/package.json
> +		"check": "cd ../../ && cargo rome-cli-dev check ./website/playground/src",
This is an existing bug we have in the resolution of the configuration. At the moment we are only able resolve the configuration file from the working directory.

I am already working on fixing the issue, but it requires some refactor on our file system. This is a temporary workaround to let the command to pick up the `rome.json` file

2022-09-16 14:13 UTC, ematipico commented on website/playground/package.json
> -		"rome": "next",
Because we don't use it

2022-09-16 14:16 UTC, ematipico commented on website/playground/src/romeWorker.ts
>  						},
Unfortunately, it's not possible at the moment. We can investigate how to solve this issue

2022-09-16 14:18 UTC, ematipico commented on website/playground/src/NurseryRules.tsx
> +export default function NurseryRules({
I am not an expert of tailwind. Do you know how to fix it?

2022-09-19 07:06 UTC, MichaReiser commented on website/playground/src/NurseryRules.tsx
> +export default function NurseryRules({
I have no prior experience with tailwind. I do think that our playground, being actively promoted on the website, is worth spending time on to ensure it looks decent, similar to diagnostics which we polish too.

2022-09-20 14:33 UTC, MichaReiser approved these changes
Nit: Maybe rename it to *nursery lint rules* to make it clear that it's about linting and not formatting.

2022-09-20 15:01 UTC, merged