feat(rome_js_semantic): Semantic Model support for closures
rome/tools pull request #3285
Opened 2022-09-27 14:22 UTC by xunilrj

## Summary

This PR introduces closures in the semantic model.
One interesting decision is what to do with:

```js
function f(c) {
    console.log(a);
    function g() {
        console.log(b, c);
    }
}
```

The implementations is returning that ```f``` captures ```a```, and it has a inner closure that captures ```b``` and ```c```. Which is closer to the code.

## Test Plan

```
cargo test -p rome_js_semantic -- ok_semantic_model_closure
```

2022-09-27 15:38 UTC, ematipico commented
I have few questions:
1. How can we use this feature? 
2. What's the difference between the concept of "closure" and the concept of "scope"?

2022-09-27 15:52 UTC, MichaReiser commented
> The implementations is returning that f captures a, and it has a inner closure that captures b and c. Which is closer to the code.

What are the alternatives you considered?

2022-09-27 15:59 UTC, MichaReiser commented on crates/rome_js_semantic/src/semantic_model.rs
> +    // Return all [Reference] this closure captures
I think it would be helpful to add examples of what `all_captures` means, particularly how it differs from` children`

2022-09-27 15:59 UTC, MichaReiser commented on crates/rome_js_semantic/src/semantic_model.rs
> +    pub fn children(&self) -> Vec<Closure> {
I think it would help to have an example here what child closures are.

2022-09-27 15:59 UTC, MichaReiser commented on crates/rome_js_semantic/src/semantic_model.rs
> +        closures
Would it be possible to return an `Iterator` rather than a `Vec`?

2022-09-27 15:59 UTC, MichaReiser commented on crates/rome_js_semantic/src/semantic_model.rs
> +        let mut r = vec![self.scope_id];
Can we use more telling names than `q` and `r` (It's unclear to me what `r` is used for)

2022-09-27 15:59 UTC, MichaReiser commented on crates/rome_js_semantic/src/semantic_model.rs
> +        r
I think this could potentially be implemented by an iterator that uses a `VecDequeue` to "queue" the scopes to process but avoids the allocation of a vector for `r`

2022-09-27 16:06 UTC, xunilrj commented
> What are the alternatives you considered?

Closure of ```f``` capturing everything: ```a```, ```b```, ```c```.

The bigger rationale was.

```js
const [a, setA] = useState(0);
const [b, setB] = useState(0);
const [c, setC] = useState(0);
useEffect(() => {
    const print = (x) => console.log(x, a);
    console.log(b, c);
}, [a,b,c]);
```

Look that print is never called.

If we always returns all captures, it is impossible to reason about nuances as the above. We will need to conclude that the dependency list is fine. It is listing all variables that are captured.

If we return just what is actually captured, we can make a finer analysis and come to the conclusion that ```b``` and ```c``` are not needed in the dependency list. Granted that this analysis would be very complex and not something we will do on v1. But at least this enables us to do it.

2022-09-29 13:35 UTC, ematipico requested changes

2022-09-29 13:35 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model.rs
> +struct ScopeReference {
Can we document this struct and what's it for?

2022-09-29 13:35 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model.rs
> +    write_references: Vec<ScopeReference>,
Can we document these two new fields?

2022-09-29 13:35 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model.rs
> +    /// this scope comes from a function or arrow function.
I think it's worth explaining what this function returns in cases where we call it from a node that is not inside a closure.

2022-09-29 13:35 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model.rs
> +    }
Shouldn't this return a `Option`? I mean, if we call `closure` on a node that is NOT inside a closure, shouldn't this be `None`?

2022-09-29 13:35 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +                | JsSyntaxKind::JS_ARROW_FUNCTION_EXPRESSION => {
I think we have to track `JsMethodClassMember` and `JsMethodObjectMember` too

2022-09-29 15:02 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model.rs
> +    }
That is why you can only pass ```Node```s that have closure using ```HasClosureAstNode```.

2022-09-29 15:03 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +                | JsSyntaxKind::JS_ARROW_FUNCTION_EXPRESSION => {
hum... you are right.

2022-09-29 15:13 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model.rs
> +    }
Ah, I see it now. It's like the other APIs.. it wasn't immediate. I understood the other APIs only by using them and understanding the error and navigated to the `impl IsDeclarationAstNode`

2022-09-30 07:26 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +}
We have the macro `declare_node_union`. Wouldn't that cover most of use cases you're having?

2022-09-30 07:26 UTC, ematipico approved these changes

2022-09-30 13:05 UTC, MichaReiser commented on crates/rome_js_semantic/src/semantic_model.rs
> +}
Nit: Implement `FusedIterator`

2022-09-30 13:06 UTC, MichaReiser commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +pub enum AnyHasClosureNode {
Would you mind adding documentation to all newly introduced public nodes

2022-10-05 14:36 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model.rs
> +    // Return all [Reference] this closure captures
Done.

2022-10-05 14:36 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model.rs
> +    pub fn children(&self) -> Vec<Closure> {
Done.

2022-10-05 14:37 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model.rs
> +        let mut r = vec![self.scope_id];
Done.

2022-10-05 14:39 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model.rs
> +    /// this scope comes from a function or arrow function.
Done.

2022-10-05 14:42 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +}
No, because I need to implement a specific trait.  
Nonetheless I created a macro to make this less horrible.

2022-10-05 14:44 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model.rs
> +}
Done.

2022-10-05 14:46 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +pub enum AnyHasClosureNode {
Done.

2022-10-05 14:55 UTC, merged