feat(rome_analyzer): add noPositiveTabindex rule
rome/tools pull request #3336
Opened 2022-10-05 10:52 UTC by kaioduarte

## Summary

Closes #3304 

## Test Plan

2022-10-05 11:00 UTC, kaioduarte reviewed
I'm opening a draft PR so we can discuss the implementation.

While implementing the rule, I noticed that the helper `inner_string_text` couldn't strip the quotes on `JsxSelfClosingElement`. Can you confirm this is working as intended, or is it a bug?

The same also happens when getting the value for `JsNumberLiteralExpression` and `JsStringLiteralExpression` on `React.createElement`.

Any help is appreciated!

2022-10-05 11:00 UTC, kaioduarte commented on crates/rome_js_analyze/tests/specs/nursery/noPositiveTabindex/invalidJsx.jsx
> +test = <div tabIndex="1" />;
The trailing space at the end is causing the issue:
```rust
Split(
    SplitInternal {
        start: 0,
        end: 4,
        matcher: StrSearcher {
            haystack: "\"1\" ", // note the trailing space here
        },
    },
)
```

2022-10-05 11:00 UTC, kaioduarte commented on crates/rome_js_analyze/tests/specs/nursery/noPositiveTabindex/invalidJsx.jsx
> +test = <div tabIndex="1" />;
cc @ematipico

2022-10-05 11:11 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/nursery/noPositiveTabindex/invalidJsx.jsx
> +test = <div tabIndex="1" />;
OK, see now that you meant. This is not a bug, it works as intended. That's because internally string literal are represented with two quotes, because we **preserve** them. Check the [playground](https://play.rome.tools/?code=%3Cinput+tabIndex%3D%221%22+%2F%3E&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&indentWidth=2&sourceType=module&enabledNurseryRules=true&typescript=false&jsx=false#PABpAG4AcAB1AHQAIAB0AGEAYgBJAG4AZABlAHgAPQAiADEAIgAgAC8APgA=)

The node that holds the value `"1"` keeps the quotes from source, and the function removes the first ones. So yes, it works as intended.

2022-10-05 11:37 UTC, kaioduarte commented on crates/rome_js_analyze/tests/specs/nursery/noPositiveTabindex/invalidJsx.jsx
> +test = <div tabIndex="1" />;
> From `"\"1\""` to `"1"`.

I'm actually getting `1" ` with the helper because of the Whitespace token, and this condition is never reached:
https://github.com/rome/tools/blob/main/crates/rome_js_syntax/src/jsx_ext.rs#L29

2022-10-05 12:26 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/nursery/noPositiveTabindex/invalidJsx.jsx
> +test = <div tabIndex="1" />;
I managed to replicate the issue locally, and yes, it's definitely a bug!

2022-10-05 13:52 UTC, kaioduarte commented on crates/rome_js_analyze/tests/specs/nursery/noPositiveTabindex/invalidJsx.jsx
> +test = <div tabIndex="1" />;
Will do, thanks for the quick fix!

2022-10-06 08:32 UTC, ematipico requested changes

2022-10-06 08:32 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +                let attribute = opening_element.find_attribute_by_name("tabIndex").ok()?;
Here you can use a second try operator `?`, because the logic of the rule has to continue only if the attribute exits.

```rs
let attribute = opening_element.find_attribute_by_name("tabIndex").ok()??;
```

Doing so, you can remove the next `if let Some()`, change the signature of `is_jsx_attribute_valid` and avoid the `unwrap` later

2022-10-06 08:32 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +                    .ok()?;
Same thing here, a second try operator `?` will simplify the code and avoid the unwrap

2022-10-06 08:32 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +                    if let Some(expression_value) = get_expression_value(&value) {
You can use the try operator `?` here so we don't need the `if let Some` anymore.

2022-10-06 08:32 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +                if let Some(prop) = tabindex_prop {
You can use the try operator `?` here so we don't need the `if let Some` anymore.

2022-10-06 08:32 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +fn get_expression_value(expression: &JsAnyExpression) -> Option<SyntaxTokenText> {
Could you add some documentation to this function, explaining what it's doing, please? The `JsAnyExpression` as input and `SyntaxTokenText` as output are really generic, so some explanation would help.

2022-10-06 08:32 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +        JsAnyExpression::JsUnaryExpression(unary_expression) => {
Since this function operates on a small of variants, maybe we can make it a bit more explicit using this pattern we use scattered across the repository:

```rs
use rome_js_syntax::{ 
	JsStringLiteralExpression,  
	JsNumberLiteralExpression, 
	JsUnaryExpression
};

/// Some documentation to explain
declare_node_union! {
	pub(crate) AnyNumberLikeExpression = JsStringLiteralExpression | JsNumberLiteralExpression | JsUnaryExpression
}

impl AnyNumberLikeExpression {
	pub(crate) fn value(&self) -> Option<SyntaxtTextToken> {}
}
```

Then, inside this function, you can do:

```rs
if let Some(number_like_expression) = AnyNumberLikeExpression::cast(expression.clone().syntaxt()) {
	number_like_expression.value()
} else {
	None
}
```

Doing so allows us to be more explicit over a subset of nodes, merge `AstNode` operations on the same enum and better document the operations.

2022-10-06 08:32 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +                ));
I am not sure using the mutation APIs in this place is the best fit.. Instead, why don't we to the transformation from string to number in this function?

2022-10-06 08:32 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +fn is_jsx_attribute_valid(jsx_attribute: &Option<JsxAttribute>) -> Option<bool> {
Could you add a bit of documentation here, please? The "Valid" word depends on the context, and here it's not provided. Also, I would change the name of the function too e.g. `is_jsx_attribute_valid_tabindex`, `attribute_has_valid_tabindex`, etc.

2022-10-06 08:32 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +            _ => return Some(true),
This function never returns `None` and it should. For example, here a `None` here makes sense because they are props that should never trigger the rule, e.g. `<div {...props} />`. And then, we change the usage of this function to use the try operator `is_jsx_attribute_valid(&attribute)?`, so we bounce back all the cases that should be ignored  by this rule.

2022-10-06 08:32 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +            let operator = unary_expression.operator_token().ok()?.token_text_trimmed();
We should ignore all the unary operators that don't fit the usage. For example `<div tabIndex={typeof e} />` is a correct code and `typeof e` is an unary operator. We should check the operator to be equals to `JsUnaryOperator::Plus` and `JsUnaryOperator::Minus`

2022-10-09 12:41 UTC, kaioduarte commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +        JsAnyExpression::JsUnaryExpression(unary_expression) => {
I addressed this on this commit [1584b43](https://github.com/rome/tools/pull/3336/commits/1584b439d4d40d43e095b0b1ef623372555cda40). Let me know if it looks good, and thanks for the feedbacks!

2022-10-10 08:34 UTC, ematipico requested changes
The implementation is way better now! I left few more suggestions, and we should fix the incorrectness of the diagnostic.

Also, it seems there are some conflicts to solve

2022-10-10 08:34 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +    ///
```suggestion
    /// Prevent the usage of positive integers on `tabIndex` property
    ///
    /// Avoid positive `tabIndex` property values to synchronize the flow of the page with keyboard tab order.
```

2022-10-10 08:34 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +    /// ## Examples
```suggestion
    /// ## Accessibility guidelines
    ///
    /// [WCAG 2.4.3](https://www.w3.org/WAI/WCAG21/Understanding/focus-order)
	///
    /// ## Examples
```

2022-10-10 08:34 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +    /// ### JsUnaryExpression &mdash; `+5` | `-5`
```suggestion
    /// - `JsStringLiteralExpression` &mdash; `"5"`
    /// - `JsNumberLiteralExpression` &mdash; `5`
    /// - `JsUnaryExpression` &mdash; `+5` | `-5`
```

2022-10-10 08:34 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +            "Elements with a positive tab index override natural page content order. This causes elements without a positive tab index to come last when navigating using a keyboard.",
```suggestion
            "Elements with a positive "<Emphasis>"tabIndex"</Emphasis> override natural page content order. This causes elements without a positive tab index to come last when navigating using a keyboard.",
```

2022-10-10 08:34 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/nursery/noPositiveTabindex/invalidJsx.jsx.snap
> +  > 2 │ 	<div tabIndex={1} />
The diagnostic shows that the error is `tabIndex`, while it should point `{1}` (or `1` if we want to be more precise, but that's a nitpick). If you pair this diagnostic with the phrase `Avoid positive values for the tabIndex prop.`, it can be misleading or lead to a bug.

2022-10-10 08:34 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_positive_tabindex.rs
> +}
Unless we decide to have a different message for attribute and member prop, there's actually not need to have the enum.

A better way to play with the state, it would be to accept a `TextRange` which is returned by `text_ranged_trimmed()`.

**If we find an incorrect attribute value**, we can do something like:

```rs
if let Some(invalid_attribute) = attribute_has_invalid_tabindex(&jsx_any_attribute_value) {
      return Some(invalid_attribute.syntaxt().text_range_trimmed());
}
// ...

if let Some(invalid_property) =  has_invallid_tabindex(&expression_value) {
    return Some(invalid_property.syntaxt().text_range_trimmed());
}
```

To not the change in name of the function: **attribute_has_invalid_tabindex** (`invalid`)

2022-10-10 08:47 UTC, leops approved these changes

2022-10-10 10:08 UTC, kaioduarte commented on crates/rome_js_analyze/tests/specs/nursery/noPositiveTabindex/invalidJsx.jsx.snap
> +  > 2 │ 	<div tabIndex={1} />
I updated this and the screenshots in the PR description as well.

2022-10-10 10:12 UTC, ematipico approved these changes

2022-10-10 10:15 UTC, kaioduarte commented
sorry, forgot to update doc files 😞

2022-10-10 10:24 UTC, ematipico commented
> sorry, forgot to update doc files 😞

No worries. To fix the CI issue, you need to run `cargo codegen-configuration`

2022-10-11 08:13 UTC, merged