feat(rome_js_analyze): exhaustive deps for React hooks
rome/tools pull request #3355
Opened 2022-10-06 14:47 UTC by xunilrj

## Summary

This PR implements the lint rule that will check React hooks are correctly specifying dependencies.
See https://github.com/rome/tools/discussions/3357#discussioncomment-3918418

Closes https://github.com/rome/tools/issues/3478

This PR implements 

- Missing dependencies;
- Extra dependencies;
- Consider some React hooks returns as stable;

## Test Plan

```
> cargo test -p rome_js_analyze -- react_extensive_dependencies
```

2022-10-10 14:16 UTC, xunilrj commented
!bench_analyzer

2022-10-12 19:17 UTC, xunilrj commented
!bench_analyzer

2022-10-12 19:45 UTC, MichaReiser commented
> ### Analyzer Benchmark Results
> ```
> group                     main                                   pr
> -----                     ----                                   --
> analyzer/css.js           1.00      2.3±0.01ms     5.1 MB/sec    1.01      2.3±0.01ms     5.0 MB/sec
> analyzer/index.js         1.00      6.5±0.01ms     5.0 MB/sec    1.01      6.6±0.01ms     4.9 MB/sec
> analyzer/lint.ts          1.00      3.0±0.01ms    13.8 MB/sec    1.00      3.0±0.01ms    13.8 MB/sec
> analyzer/parser.ts        1.00      7.5±0.01ms     6.5 MB/sec    1.01      7.6±0.02ms     6.4 MB/sec
> analyzer/router.ts        1.00      5.5±0.01ms    11.1 MB/sec    1.01      5.6±0.01ms    11.0 MB/sec
> analyzer/statement.ts     1.00      8.2±0.02ms     4.3 MB/sec    1.02      8.3±0.03ms     4.3 MB/sec
> analyzer/typescript.ts    1.00     12.9±0.06ms     4.2 MB/sec    1.02     13.2±0.14ms     4.1 MB/sec
> ```


Ema mentioned on an other PR that nursery rules are probably not run as part of our benchmarks. It probably makes sense to change that in a separate PR first to get clear signal on perf.

2022-10-13 14:06 UTC, ematipico reviewed
I skimmed a bit the PR, I will do a second pass later. There's one thing that I am struggling with. We use "capture" a lot... but this is concept I am not familiar with. Can we explain it somewhere? I checked the struct `Capture` and the explanation doesn't help me. Can we explain it better? I wouldn't be able to help if I don't understand the concept.

2022-10-13 14:06 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model.rs
> +    pub fn is_imported<T>(&self, node: &T) -> T::Result
Documentation?

2022-10-13 14:06 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +    /// Returns the [TextRange] of declaration of this capture
Sorry, I am having really hard time to understand this phrase...

2022-10-13 15:47 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/react_extensive_dependencies.rs
> +    ExtraDependency(TextRange, TextRange),
Nit: Rename `Problem` to `InvalidDependency` or `DependencyIssue` to be more specific than `Problem` (sounds bad... ey, do you have problem ;))

2022-10-13 15:47 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/react_extensive_dependencies.rs
> +                            JS_FUNCTION_DECLARATION
Does that mean it is OK to not define functions as dependencies even if they are defined inside of the component?

```javascript
function Component() {

  function compute() {... };

 let expensive = useMemo(() => {
   // some initialization work
  compute(data)
 }, [])
```

If so, 

- I think it would be good to add this as an example. 
- Does the implementation also capture any closures referenced by `compute`?

2022-10-13 15:47 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/react_extensive_dependencies.rs
> +            //TODO Search for dependencies not captured
TODO

2022-10-13 15:47 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/react_extensive_dependencies.rs
> +            for (text, capture) in captures.iter() {
Is it possible to have two captures that have the same name but reference different dependencies?

2022-10-19 11:43 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/react_extensive_dependencies.rs
> +        name: "reactExtensiveDependencies",
Done.

2022-10-19 11:44 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/react_extensive_dependencies.rs
> +    stables: HashSet<ReactHookStable>,
Done.

2022-10-19 11:44 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/react_extensive_dependencies.rs
> +    ExtraDependency(TextRange, TextRange),
Done.

2022-10-19 12:12 UTC, xunilrj commented on crates/rome_js_analyze/tests/specs/nursery/reactExtensiveDependencies/missingDependenciesInvalid.js
> +    });
I will do this in another PR, because we need a more sophisticated algo to support constants (and better diagnostics).

2022-10-19 12:12 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model.rs
> +    pub fn is_imported<T>(&self, node: &T) -> T::Result
Done.

2022-10-19 12:12 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +    /// Returns the [TextRange] of declaration of this capture
Done.

2022-10-19 12:12 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +// Iterate all immediate children closures of a specific closure
Done.

2022-10-19 12:12 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +// Iterate all descendents closures of a specific closure
Done.

2022-10-19 12:14 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/react_extensive_dependencies.rs
> +            //TODO Search for dependencies not captured
Done.

2022-10-19 12:19 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/react_extensive_dependencies.rs
> +            for (text, capture) in captures.iter() {
You mean the same name but different declarations? In theory yes, but not for this rule.

```js
let a = 1;
useEffect(() => {
    console.log(a);
    let a = 2;
    return () => {    
        console.log(a);
    }
});
```

But for the sake of this lint rule, the second "a" is not a capture from the "useEffect" perspective.

2022-10-19 12:19 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +pub(crate) struct ReactCallWithDependencyResult {
Done.

2022-10-19 12:19 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +    pub fn all_dependencies(&self) -> Vec<JsAnyExpression> {
Done.

2022-10-19 12:20 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +    pub fn all_captures(&self, model: &SemanticModel) -> Vec<Capture> {
Now that have more documentation. Is it more clear?

2022-10-19 12:20 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +pub fn is_stable_binding(
Done.

2022-10-19 12:21 UTC, xunilrj commented on crates/rome_js_analyze/tests/specs/nursery/reactExtensiveDependencies/missingDependenciesInvalid.js.snap
> +  ! This useEffect has missing dependencies
I changed the diagnostic text. What about now?

2022-10-19 12:21 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +pub struct ReactHookStable {
Done.

2022-10-19 16:41 UTC, ematipico commented
@xunilrj could you please update the summary and explain to us what case this rule covers or what cases **are not covered** from the original rule? How do we plan to keep track of the cases that we need to cover? Or even it covers all the cases... 

Did you use [their tests](https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js)? 

Please share some details with us to have some context/awareness.

2022-10-19 16:57 UTC, ematipico commented on crates/rome_diagnostics_categories/src/categories.rs
> +    "lint/nursery/reactExtensiveDependencies": "https://rome.tools/docs/lint/rules/reactExtensiveDependencies",
Remove this line

2022-10-19 16:57 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
> +    ///
We need examples, especially invalid ones. We could also add a link to the original rule, just in case (npm package page).

2022-10-19 16:57 UTC, ematipico commented on crates/rome_js_analyze/src/utils/react.rs
> +    pub fn all_captures(&self, model: &SemanticModel) -> Vec<Capture> {
Yes, thank you for that

2022-10-19 16:57 UTC, ematipico commented on crates/rome_js_analyze/src/utils/react.rs
> +// Get the i-th argument of a call expression
```suggestion
/// Get the n-th argument of a call expression, it that argument is an expression
```
The argument is called `n`. And there's a `as_js_any_expression`, which is important to track

2022-10-19 16:57 UTC, ematipico commented on crates/rome_js_analyze/src/utils/react.rs
> +/// return value. Stable return do not need to be specified
"Stable return"? I think there's some error.

Also, checking the example... is `name` also stable? (the test doesn't cover this case)

2022-10-19 16:57 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model.rs
> +        T: IsExportedCanBeQueried,
It's a bit weird to see function called "imported" being bound to a trait that is called "exported". Maybe we should rename the trait at this point? And update its documentation:
> /// Marker trait that groups all "AstNode" that can be exported

2022-10-19 16:57 UTC, ematipico commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +        let mut scopes = Vec::with_capacity(128);
What's the reason of using `128`?

2022-10-19 19:15 UTC, xunilrj commented
> @xunilrj could you please update the summary and explain to us what case this rule covers or what cases **are not covered** from the original rule? How do we plan to keep track of the cases that we need to cover? Or even it covers all the cases...

I have improved the summary and the original discussion with next steps.

> Did you use [their tests](https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js)?

Not extensively. I will do this in future PRs. We will need more sophisticated algo to pass some tests.

2022-10-19 19:16 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +        let mut scopes = Vec::with_capacity(128);
None. It could be anything to be honest.

2022-10-19 19:45 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model.rs
> +        T: IsExportedCanBeQueried,
True. I have renamed it.

2022-10-19 19:59 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +/// return value. Stable return do not need to be specified
The return value that is stable. "name" is not stable; "setName" is stable.  
I have improved the example. What about now?

2022-10-20 08:25 UTC, MichaReiser requested changes
There are some open comments on @ematipico  that should be addressed before merging and I would prefer to have some performance numbers too.

2022-10-20 08:25 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
> +                    captures.push(capture.clone());
How about creating the `AddDependency` signal directly instead of mutating `captures`. This would avoid checking if a dependency exists for the "missing captures" (and removes an entire loop)

2022-10-20 08:25 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
> +                    remove_deps.push(dep.1);
Same here. How about generating the `RemoveDependency` signal directly

2022-10-20 08:25 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/react.rs
> +    pub fn all_dependencies(&self) -> Vec<JsAnyExpression> {
Can we return a `impl Iterator<Item=JsAnyExpression>` here. The call-site is already collecting into a vector.

2022-10-20 08:25 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/react.rs
> +            captures
Nit:

```
let captures = descendents
                .next()
                .map(|closure| closure.all_captures())
                .into_iter()
                .flatten()
                .chain(
                    descendents
                        .flat_map(|closure| closure.all_captures())
                        .filter(|capture| capture.declaration_range().intersect(*range).is_none()),
                );

            captures.collect()
```

It should probably be possible to remove the `Vec` entirely but it may over complicate the implementation

2022-10-20 08:25 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
> +            ("useEffect".to_string(), (0, 1).into()),
The dependency argument always seems to be the `closure index + 1`. Maybe you can use this information to reduce storage and avoid calling `get_nth_argument` twice

2022-10-20 08:25 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/react.rs
> +        let index = binding.syntax().index() / 2;
What's the reason for dividing by two here? If this is to get the index into the separated list then this may not be safe in case a separator is missing.

2022-10-20 08:25 UTC, MichaReiser commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +        let mut scopes = Vec::with_capacity(128);
Is it necessary or can we remove it? If the size shows an improvement in performance then I suggest adding a comment explaining why

2022-10-20 13:27 UTC, xunilrj commented on crates/rome_diagnostics_categories/src/categories.rs
> +    "lint/nursery/reactExtensiveDependencies": "https://rome.tools/docs/lint/rules/reactExtensiveDependencies",
Argh! Rebase issues. Done.

2022-10-20 13:28 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +// Get the i-th argument of a call expression
Done.

2022-10-20 13:46 UTC, xunilrj commented on crates/rome_js_semantic/src/semantic_model/closure.rs
> +        let mut scopes = Vec::with_capacity(128);
I will remove it for now. I dont have numbers to back this up.

2022-10-20 14:00 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
> +                    captures.push(capture.clone());
But this "captures.push(...)" aggregate all references to the same variable.

```js
        403 │+```
        404 │+missingDependenciesInvalid.js:58:3 lint/nursery/useExhaustiveDependencies ━━━━━━━━━━━━━━━━━━━━━━━━━━
        405 │+
        406 │+  ! This hook do not specify all of its dependencies.
        407 │+
        408 │+    56 │ function MyComponent7() {
        409 │+    57 │   let a = 1;
        410 │+  > 58 │   useEffect(() => {
        411 │+       │   ^^^^^^^^^
        412 │+    59 │     console.log(a);
        413 │+    60 │     return () => console.log(a);
        414 │+
        415 │+  i This dependency is not specified in the hook dependency list.
        416 │+
        417 │+    57 │   let a = 1;
        418 │+    58 │   useEffect(() => {
        419 │+  > 59 │     console.log(a);
        420 │+       │                 ^
        421 │+    60 │     return () => console.log(a);
        422 │+    61 │   }, []);
        423 │+
        424 │+  i This dependency is not specified in the hook dependency list.
        425 │+
        426 │+    58 │   useEffect(() => {
        427 │+    59 │     console.log(a);
        428 │+  > 60 │     return () => console.log(a);
        429 │+       │                              ^
        430 │+    61 │   }, []);
        431 │+    62 │ }
        432 │+
        433 │+
        434 │+```
``` 

I aggregated them to generate the diagnostic only once (although I do show all references). If I generate the signal directly, I will flag each reference as a missing dependency.

2022-10-20 14:06 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
> +                    remove_deps.push(dep.1);
I made a small change to also aggregate RemoveDependency here. See https://github.com/rome/tools/pull/3355#discussion_r1000673881 on why I think it makes sense to do this way.

2022-10-20 16:38 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +            captures
Done.

2022-10-20 16:41 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +        let index = binding.syntax().index() / 2;
When the separator is missing, wouldn't the slot still be reserved?

```
[a b]
```

```
0: JS_ARRAY_EXPRESSION@0..5
    0: L_BRACK@0..1 "[" [] []
    1: JS_ARRAY_ELEMENT_LIST@1..4
        0: JS_IDENTIFIER_EXPRESSION@1..3
            0: JS_REFERENCE_IDENTIFIER@1..3
                0: IDENT@1..3 "a" [] [Whitespace(" ")]
        1: (empty)
        2: JS_IDENTIFIER_EXPRESSION@3..4
            0: JS_REFERENCE_IDENTIFIER@3..4
                0: IDENT@3..4 "b" [] []
    2: R_BRACK@4..5 "]" [] []
```

2022-10-20 16:42 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
> +            ("useEffect".to_string(), (0, 1).into()),
Not necessarily for custom hooks.
But I can try to optimize like we did for JSX attributes.

2022-10-21 21:28 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs
> +            ("useEffect".to_string(), (0, 1).into()),
Done.

2022-10-21 21:29 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/react_extensive_dependencies.rs
> +    ///
Done.

2022-10-21 21:43 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +use std::collections::{HashMap, HashSet};
Done.

2022-10-21 21:43 UTC, xunilrj commented on crates/rome_js_analyze/src/utils/react.rs
> +pub struct ReactHookClosureDependenciesPosition {
I changed the name of this struct.

2022-10-21 21:43 UTC, xunilrj commented on crates/rome_js_analyze/tests/specs/nursery/reactExtensiveDependencies/extraDependenciesInvalid.js.snap
> +  ! This useEffect has dependencies that were not captured
I improved the message now.

2022-10-25 09:28 UTC, ematipico commented
@MichaReiser could you give a second look to this PR? It would be great to have it merged for the `10.0.0` release

2022-10-25 12:24 UTC, MichaReiser approved these changes

2022-10-25 12:27 UTC, merged

2022-11-28 07:31 UTC, arendjr commented on crates/rome_js_analyze/src/react/hooks.rs
> +    /// none returns are stable
Doc issue: `[None]` if the entire return value is stable.