fix(rome_js_parser): permisive instantiation expression
rome/tools pull request #3359
Opened 2022-10-07 11:06 UTC by IWANABETHATGUY

## Summary

## Test Plan

2022-10-07 11:22 UTC, IWANABETHATGUY commented
!bench_parser

2022-10-10 13:09 UTC, IWANABETHATGUY commented
@MichaReiser, Would mind helping with reviewing the code?

2022-10-10 13:22 UTC, IWANABETHATGUY commented on crates/rome_js_parser/src/syntax/typescript/types.rs
> +        _ => is_binary_operator(p) || is_at_identifier(p),
This function is just porting from Typescript, I keep the same behavior as Typescript because this will not bring too much maintenance burden when Typescript changes next time.

2022-10-10 13:45 UTC, MichaReiser commented on crates/rome_js_parser/src/syntax/typescript/types.rs
> +        _ => is_binary_operator(p) || is_at_identifier(p),
The issue I see here is that the method tests if it is at the start of an expression which may not be true for a binary operator. It also introduces a lot of duplication with `is_at_expression`. 

I think it's ok to get inspiration from TypeScript but we should be careful with copying the implementation 1:1. Our parser works similar to TypeScript but isn't an exact rewrite in Rust. Thus, we should only inherit what we explicitly know is necessary.

2022-10-10 14:03 UTC, IWANABETHATGUY commented on crates/rome_js_parser/src/syntax/typescript/types.rs
> +fn is_start_of_expr(p: &mut Parser) -> bool {
`is_start_of_expr` has `JS_BIG_INT_LITERAL`, but `is_at_expression` don't. `is_start_of_expr` don't have `T![super]`

2022-10-10 14:10 UTC, IWANABETHATGUY commented on crates/rome_js_parser/src/syntax/typescript/types.rs
> +        _ => is_binary_operator(p) || is_at_identifier(p),
I have added the reason why we need to add `binary_operator`. We could merge this function but, it may be not good for reuse, what do you think? Other than that, the pattern match is just against `JS_SYNTAX_KIND` which should be only u8 under the hood, and it is pretty trivial according to the benchmark.

2022-10-10 14:21 UTC, IWANABETHATGUY commented on crates/rome_js_parser/src/syntax/typescript/types.rs
> +/// You could refer to https://github.com/microsoft/TypeScript/blob/42b1049aee8c655631cb4f0065de86ec1023d20a/src/compiler/parser.ts#L4475
I will add some doc about the implementation , but then add the reference link in Typescrip for people who want to see more details, what do you think?

2022-10-10 14:30 UTC, IWANABETHATGUY commented on crates/rome_js_parser/src/syntax/typescript/types.rs
> +fn is_start_of_expr(p: &mut Parser) -> bool {
[`is_at_expression`](https://vscode.com/github/IWANABETHATGUY/tools/blob/f3b3447bd853ccabbce3b81a32fbd25bbf4115d8/crates/rome_js_parser/src/syntax/typescript/types.rs#L1329-L1333), Also `is_start_of_expr` need `is_binary_operator` for better error recover. I am not sure if we need it too, becuase our error recover maybe different from *Typescript*

2022-10-10 18:04 UTC, Boshen commented on crates/rome_js_parser/src/syntax/typescript/types.rs
> +        _ => is_binary_operator(p) || is_at_identifier(p),
Just chiming in. 

The decision here is to whether parse a plain `&& rhs` to a missing lhs logical expression or not in Rome:

```
JsLogicalExpression {
    left: missing (required),
    operator_token: AMP2@2..5 "&&" [] [Whitespace(" ")],
    right: ...
}
```

But regardless of the final decision, it shouldn't be introduced in a feature PR because it needs separate tests.

Also note, almost every kind of expression is binary expression in TypeScript, so copying exact implementations from TypeScript will end up with a very different outcome.
(I just noticed the other day, assignments and sequence expressions are all binary expressions in TypeScript.)

2022-10-11 06:12 UTC, IWANABETHATGUY commented on crates/rome_js_parser/src/syntax/typescript/types.rs
> +        _ => is_binary_operator(p) || is_at_identifier(p),
@MichaReiser What do you think ? Do we need to rewrite the code, make it fixes this test case, and ignore the rest logic in Typescript, fix them one by one when we suffer them?

2022-10-11 06:17 UTC, MichaReiser commented on crates/rome_js_parser/src/syntax/typescript/types.rs
> +        _ => is_binary_operator(p) || is_at_identifier(p),
I think we need to understand what this logic accomplishes and if we need both `is_*_expression` method and if so why, document it and explain when to use which. 

My preferred solution would be to only have one (unparametrized) method in the end.

2022-10-11 06:19 UTC, MichaReiser requested changes
I think it's necessary to either make a very clear distinction between `is_start_of_expr` and `is_at_expression` but ideally, only have one. 

I think we should also be more explicit in the PR description explaining which new cases this PR handles that the parser currently does not and add positive and negative tests.

2022-11-13 11:17 UTC, closed without merging