feat: add useAltText lint rule for JSX expression
rome/tools pull request #3371
Opened 2022-10-08 18:53 UTC by b4s36t4

## Summary

## Test Plan

2022-10-10 08:25 UTC, leops approved these changes

2022-10-10 08:25 UTC, leops commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +    type Query = Semantic<UseAltTextQuery>;
The rule could query for `Syntax<UseAltTextQuery>` instead, since it only relies on the syntax tree and doesn't seem to make use of any information from the semantic model

2022-10-10 09:07 UTC, b4s36t4 commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +    type Query = Semantic<UseAltTextQuery>;
Which one it is?! 😅

2022-10-10 09:25 UTC, ematipico requested changes
Thank you for the contribution! I left some suggestion and correction to the cases covered

2022-10-10 09:25 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +    pub (crate) UseAltTextQuery = JsxSelfClosingElement  | JsCallExpression
I think we should limit ourselves only to `JsxSelfClosingElement` nodes. Which means that union is not needed anymore, and the `Query` will become:

```rs
type Query = Ast<JsxSelfClosingElement>;
```

2022-10-10 09:25 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +fn is_valid_tag(name: &JsxAnyElementName) -> Option<bool> {
Can we document this function? "Valid tag" is not clear, unless we look at the implementation of the function.

2022-10-10 09:25 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +fn is_valid_input(element: &JsxSelfClosingElement) -> Option<bool> {
Can we document this function? "Valid input" needs to have a context; we have to tell developers what a valid input means in this case.

Also, this function could be called `input_has_type_image`

2022-10-10 09:25 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +            ),
nit: you can `footer_note` function and pass only the text.

2022-10-10 09:25 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +    type State = UseAltTextState;
I think `State` can be a `TextRange`

```rust
type State = TextRange
```

And when you find a property that is incorrect, you just do 

```rust
return Some(element.syntaxt().text_range_trimmed())
```

And the `state` can be used inside the diagnostic. As you noticed the state is only used to retrieve the range.

2022-10-10 09:26 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +    type Query = Semantic<UseAltTextQuery>;
It's the second one :) just look for other rules that use `Ast<`

2022-10-17 18:41 UTC, b4s36t4 commented on crates/rome_js_analyze/tests/specs/nursery/useAltText/area.jsx.snap
> +	<area {...props} />
This applies to other tags as well?

2022-10-17 19:18 UTC, b4s36t4 commented
@ematipico I have updated the code, please check it. 
> Note: as part of skipping cases including `{...props}` spread items existing cases mentioned in the doc will became valid. > Please check the snapshots for more context.

2022-10-18 10:16 UTC, ematipico approved these changes

2022-10-18 10:16 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/nursery/useAltText/area.jsx
> +	<area alt={undefined} />
If we add a case for `undefined`, I think we should also add a case for `alt={null}`

2022-10-18 10:16 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/nursery/useAltText/img.jsx
> +	<img {...props} alt={undefined} /> {/* Skipping*/}
Can we remove these cases? It would be better to tackle spread props in a different PR (it's a feature missing in different rules, not just this one). And for example, the first and third cases are false positives.

2022-10-18 10:16 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +            "Provide "<Emphasis>"alt"</Emphasis>" when using "<Emphasis>"img"</Emphasis>", "<Emphasis>"area"</Emphasis>", "<Emphasis>"input type='image'"</Emphasis>""
```suggestion
            "Provide the attribute"<Emphasis>"alt"</Emphasis>" when using "<Emphasis>"img"</Emphasis>", "<Emphasis>"area"</Emphasis>" or "<Emphasis>"input type='image'"</Emphasis>""
```
You would need to regenerate the snapshots and documentation

2022-10-18 10:16 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +            RuleDiagnostic::new(rule_category!(), state, message).footer(
You can just use `footer_note`, so you don't need to pass `Severity`

2022-10-18 10:16 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> + */
```suggestion
/// This function checks for the attribute `type` for input element where we checking for the input type which is image.
```

We should use rust documentation comments

2022-10-18 10:16 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> + */
```suggestion
/// Function to check that the HTML/JSX tag is valid for the lint rule, which check if the tag should be `img`, `input type='image' and `area`.
```

We should use rust documentation comments

2022-10-18 10:16 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +            }
I think it's best, for now, to remove the check for spread props. It's a feature/functionality that is missing from various rules and the implementation should do more checks. It's OK to remove it, I will work on it later.

2022-10-18 10:17 UTC, ematipico commented on website/src/docs/lint/rules/UseAltText.md
> +---
This file seems incorrect. It should be called `useAltText.md`. Can you delete it and try to generate it again?

2022-10-18 10:18 UTC, ematipico requested changes

2022-10-18 10:18 UTC, ematipico commented on website/src/docs/lint/rules/index.md
> +=======
There's some issue with this file too... You should delete it and generate again

2022-10-19 12:48 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +fn is_valid_tag(name: &JsxAnyElementName) -> Option<bool> {
"text_trimmed"and the navigation are expensive methods. You can simplify this method, and its call to:

```rs
match name.as_jsx_name().map(|x| x.text_trimmed()) {
    Some("input") => {...}
    Some("img" | "area") => {...}
}
```

2022-10-19 17:28 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_alt_text.rs
> +            let alt_prop = element.find_attribute_by_name("alt").ok()?;
You may also look at: https://github.com/rome/tools/pull/3458. 
It will improve the code here.

2022-10-26 12:46 UTC, ematipico commented
Closing in favour of https://github.com/rome/tools/pull/3502

2022-10-26 12:46 UTC, closed without merging