feat(rome_js_analyze): rule `useKeyWithMouseEvents`
rome/tools pull request #3373
Opened 2022-10-09 14:17 UTC by mrkldshv

## Summary

Closes #3302.

## Test Plan

Added various test cases

2022-10-10 09:04 UTC, ematipico requested changes
Thank you for the contribution! I left some suggestion. I think there's some case that should not trigger.

2022-10-10 09:04 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
> +                .text_trimmed();
I might be wrong, but **I think** don't need to check against the text `"null"`. Having a `JsNullLiteralExpression` should be enough

2022-10-10 09:04 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/nursery/useKeyWithMouseEvents.jsx
> +<div onMouseOver={() => {}} {...props} />;
I think this should be **a valid case** for now. That's because we don't know if `props` contains `onBlur`/`onFocus`, and **it might**. Because of that, we don't have enough information, and we should not trigger the rule.

2022-10-10 09:49 UTC, mrkldshv commented on crates/rome_js_analyze/tests/specs/nursery/useKeyWithMouseEvents.jsx
> +<div onMouseOver={() => {}} {...props} />;
Hmm, I see. I was looking at eslint [tests](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/__tests__/src/rules/mouse-events-have-key-events-test.js) when implementing this rule. Do you think we should deviate from eslint here?

2022-10-10 09:51 UTC, mrkldshv commented on crates/rome_js_analyze/tests/specs/nursery/useKeyWithMouseEvents.jsx
> +<div onMouseOver={() => {}} {...props} />;
Hmm, I see. I was looking at eslint [tests](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/__tests__/src/rules/mouse-events-have-key-events-test.js) when implementing this rule. Do you think we should deviate from eslint here?

2022-10-10 09:52 UTC, mrkldshv commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
> +                .text_trimmed();
Good point. Will adjust it!

2022-10-10 10:18 UTC, mrkldshv commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
> +            JsxAnyElement::JsxSelfClosingElement(element) => {
Should we do `find_by_attribute` for `onFocus` only in case we find `onMouseOver` attribute?

2022-10-10 10:22 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
> +            JsxAnyElement::JsxSelfClosingElement(element) => {
We could, but that would repeat the code again. But I suppose that's fine, I leave it to your discretion :)

2022-10-10 13:43 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
> +            if expression.as_js_identifier_expression().is_some() {
You can use (that are other cases similar to this one)

```rust
if let Some(id) = expression.as_js_identifier_expression() {
    let name = id.name().ok()?.syntax().text_trimmed();
```

2022-10-10 16:20 UTC, mrkldshv commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
> +            JsxAnyElement::JsxSelfClosingElement(element) => {
I was thinking about the way how we share common code for this case. Because we have four attributes to find, it gets pretty repetitive with something like this:
```rs
let on_mouse_over_attribute = element.find_attribute_by_name("onMouseOver").ok()?;
let on_mouse_out_attribute = element.find_attribute_by_name("onMouseOut").ok()?;

match (&on_mouse_over_attribute, &on_mouse_out_attribute) {
    (Some(_), Some(_)) => (
        on_mouse_over_attribute,
        element.find_attribute_by_name("onFocus").ok()?,
        on_mouse_out_attribute,
        element.find_attribute_by_name("onBlur").ok()?,
    ),
    (Some(_), None) => (
        on_mouse_over_attribute,
        element.find_attribute_by_name("onFocus").ok()?,
        on_mouse_out_attribute,
        None,
    ),
    (None, Some(_)) => (
        on_mouse_over_attribute,
        None,
        on_mouse_out_attribute,
        element.find_attribute_by_name("onBlur").ok()?,
    ),
    (None, None) => (on_mouse_over_attribute, None, on_mouse_out_attribute, None),
}
```
I guess there should be a better way of doing it. Any suggestions?

2022-10-11 08:12 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
> +            JsxAnyElement::JsxSelfClosingElement(element) => {
Another suggestion would be to move the majority of the common functions inside the enum `JsxAnyElement`.

Some example:

```rs
impl JsxAnyElement {
	fn find_on_mouse_over_attribute() {}
	fn find_on_mouse_out_attribute() {}
	fn find_on_focus_attribute() {}
	fn find_on_blur_attribute() {}

	/// here we check the pair "onFocus" and "onMouseOver"
	fn has_focus_attributes() {
		let on_mouse_over = self.find_on_mouse_over_attribute();
		let on_focus = self.find_on_focus_attribute();
	}
    /// here we check the pair "onBlur" and "onMouseOut"
	fn has_blur_attributes() {
		let on_mouse_over = self.find_on_mouse_out_attribute();
		let on_focus = self.find_on_blur_attribute();
	}
}
```

Even though we have four attributes, they pair are fixed, so we don't need to do a matrix.

2022-10-14 09:48 UTC, mrkldshv commented
@ematipico @xunilrj Thanks for the review and your suggestions! I've addressed them in the last commits.

2022-10-14 13:14 UTC, ematipico approved these changes
Thank you! The code looks way better now! :) 
I just left few tiny improvements, but I think the rule can be merged as it is

2022-10-14 13:14 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
> +            return Some(true);
I _think_ the return here is not needed... it would go straight to the last `Some(true)`

2022-10-14 16:17 UTC, mrkldshv commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
> +            return Some(true);
Hmm, `rust-analyzer` tells me it's required in this case. Probably because it's early return.

2022-10-14 16:18 UTC, mrkldshv commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_key_with_mouse_events.rs
> +                .into_iter()
It seems that `JsxAttributeList` doesn't have `iter` method on it.

2022-10-14 16:42 UTC, merged