feat(rome_js_analyze): new rule `useFlatMap`
rome/tools pull request #3384
Opened 2022-10-10 15:09 UTC by ematipico

## Summary

Closes #3367 

The rule checks for usages like `arr.flat().map(function)` and suggests the replace it with `arr.flatMap(function)` instead.

Clippy marks the code action as safe, so I suppose we can do that too? Please let me know if you think that the code action should be suggested.

## Test Plan

Added some simple case.
The rule should not be triggered if at the function`flat` are [passed some argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#parameters).

2022-10-10 15:16 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +    /// arr.flat().map(Number);
Replacing this with `flatMap` doesn't yield the same result for me: 

```
arr.flatMap(Number);
Array(3) [ 1, 4, NaN ]
```

That's why using `flat` followed by `flatMap` may also be easier to write because it's otherwise necessarily to flat any nested arrays manually?

2022-10-10 15:19 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +    /// arr.flat(1).map(Number);
Why is this valid when `flat` isn't? `depth` defaults to 1.

2022-10-10 15:21 UTC, leops requested changes
I think the order of operations is reversed, the rule is searching for `.flat().map()` when it should be checking for `.map().flat()`

2022-10-10 15:21 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +            message: markup! {"Replace it with "<Emphasis>".flatMap()"</Emphasis>""}.to_owned(),
Nit: the empty `""` at the end of the markup can be removed since it doesn't print anything

2022-10-10 15:21 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +    /// arr.flat(1).map(Number);
With the correct order of operations `.map().flat(1)` should also be considered invalid by the rule (but not `.map().flat(2)`)

2022-10-10 15:24 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +    /// arr.flat(1).map(Number);
I suppose the rule should not be triggered if the `depth` is greater than `1`

2022-10-10 15:25 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +    /// arr.flat(1).map(Number);
Yes, I think so.

2022-10-10 15:26 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +    /// arr.flat().map(Number);
Ironically, my first implementation was around `map().flat()` 😆
Thank you for flatting it out

2022-10-11 14:26 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +                "The call chain "<Emphasis>".flat().map()"</Emphasis>" can be replaced with a simple "<Emphasis>".flatMap()"</Emphasis>"."
The message also needs to be updated to `.map().flat()`

2022-10-11 14:26 UTC, leops commented on crates/rome_js_analyze/tests/specs/nursery/useFlatMap.js.snap
> +  > 2 │ [0, [12]].map(Number).flat()
You should add a semicolon between the statements here, otherwise the second array gets parsed as a computed member expression (so the whole `[0, [12]].map(Number).flat()[0, [12], [[16]]].map(Number).flat(1)` becomes a single expression)

2022-10-12 08:13 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/nursery/useFlatMap.js.snap
> +  > 2 │ [0, [12]].map(Number).flat()
Are you suggesting that the mutation should do that or the code inside `useFlatMap.js` should have the semicolon?

2022-10-12 12:04 UTC, MichaReiser requested changes
Can you update the PR description to reflect that the rule is testing for `.map(...).flat()`

2022-10-12 12:04 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +        );
Nit: How about using `old_static_member_expression.with_member(JsAnyname::JsName(member))` because we're only changing the call member name but want to keep everything else as is.

2022-10-12 12:04 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +    fn action(ctx: &RuleContext<Self>, state: &Self::State) -> Option<JsRuleAction> {
Nit: It may be more understandable if `state` is called `flat_call` instead because that's what the state represents in the context of this rule (makes it clear what `callee` and `arguments` represents)

2022-10-12 12:04 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +        .build();
Nit: How about using flat_call.with_callee(new_member_expression)` instead?

2022-10-12 12:04 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +        let new_member_expression = js_static_member_expression(
Nit: Rename to `flat_map_member_expression`

2022-10-12 12:04 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +            message: markup! {"Replace it with "<Emphasis>".flatMap()"</Emphasis>"."}.to_owned(),
Nit
```suggestion
            message: markup! {"Replace the chain with "<Emphasis>".flatMap()"</Emphasis>"."}.to_owned(),
```

2022-10-12 12:07 UTC, MichaReiser approved these changes

2022-10-12 13:49 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +        );
Great tip! I was completely clueless I has these APIs at hand! Thank you

2022-10-12 14:19 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_flat_map.rs
> +        }
I added a part of the suggestion, I left

```rs
let first_argument = first_argument
    .as_js_any_expression()?
    .as_js_any_literal_expression()?
    .as_js_number_literal_expression()?;
```

I like it more 😆

2022-10-17 13:26 UTC, ematipico commented
@leops could you please review again the PR?

2022-10-17 13:29 UTC, leops approved these changes

2022-10-17 13:39 UTC, merged