fix(rome_cli): remove unsupported options in the `ci` help text
rome/tools pull request #3457
Opened 2022-10-19 15:57 UTC by lucasweng

## Summary

- Resolves #3456

- Per `apply_format_settings_from_cli`
https://github.com/rome/tools/blob/745464fb69d048de348b31b0b28e265b9e9fe0a8/crates/rome_cli/src/commands/ci.rs#L10
  `rome ci` supports the following options:

  ```
    --indent-style <tabs|space>              Change the indention character (default: tabs)
    --indent-size <number>                   If the indentation style is set to spaces, determine how many spaces should be used for indentation (default: 2)
    --line-width <number>                    Change how many characters the formatter is allowed to print in a single line (default: 80)
    --quote-style <single|double>            Changes the quotation character for strings (default: ")
    --quote-properties <as-needed|preserve>  Changes when properties in object should be quoted (default: as-needed)
    --trailing-comma <all|es5>               Changes trailing commas in multi-line comma-separated syntactic structures (default: all)
   ```

## Test Plan

- Running `cargo run --bin rome ci --help` should print out the supported options
  <img width="1541" alt="options" src="https://user-images.githubusercontent.com/30640930/196741684-e02bfd0a-aee9-4bf0-b333-e061501cd6fb.png">

2022-10-19 16:06 UTC, MichaReiser commented
Good catch that the `rome format `options are supported. 

Does this change also fix the issue that `rome ci` incorrectly refers to the `rome format` command when an argument is missing?

```
❯ cargo run --bin rome ci --quote-style="double" 
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/rome ci --quote-style=double`
Error: missing argument '<INPUT>'. Type 'rome format --help' for more information.
```

2022-10-19 16:29 UTC, lucasweng commented
> Good catch that the `rome format `options are supported.
> 
> Does this change also fix the issue that `rome ci` incorrectly refers to the `rome format` command when an argument is missing?
> 
> ```
> ❯ cargo run --bin rome ci --quote-style="double" 
>     Finished dev [unoptimized + debuginfo] target(s) in 0.08s
>      Running `target/debug/rome ci --quote-style=double`
> Error: missing argument '<INPUT>'. Type 'rome format --help' for more information.
> ```

Didn't catch that.. Thanks for pointing that out! Will fix the issue here

2022-10-19 18:12 UTC, lucasweng commented
hi @MichaReiser and @ematipico

After looking into it for a bit, we'll need to change these two error messages here
https://github.com/rome/tools/blob/745464fb69d048de348b31b0b28e265b9e9fe0a8/crates/rome_cli/src/termination.rs#L28-L40

I was thinking about adding a `subcommand` field like this
```rust
    /// Returned when a required argument is not present in the command line
    #[error(
        "missing argument '{argument}'. Type '{} {subcommand} --help' for more information.",
        command_name()
    )]
    MissingArgument {
        subcommand: &'static str,
        argument: &'static str,
    },
```

Though I couldn't find a way to get the `subcommand` from `session` in `traverse`
https://github.com/rome/tools/blob/745464fb69d048de348b31b0b28e265b9e9fe0a8/crates/rome_cli/src/traversal.rs#L56-L60

Or maybe we can open another PR to fix that error message because the changes seem to be out of the scope of the original issue. Would like to know your thoughts on this, thanks!

2022-10-20 08:12 UTC, ematipico approved these changes

2022-10-20 08:36 UTC, MichaReiser requested changes

2022-10-20 08:36 UTC, MichaReiser commented on crates/rome_cli/src/commands/help.rs
> +"
I would prefer it if we change `FORMAT_OPTIONS` to only contain the markup for the format options (without the `OPTIONS` header and then compose it in `format` and `rome ci`


```rust
const FORMAT_OPTIONS: Markup = markup! {
	"<Dim>"--indent-style <tabs|space>"</Dim>"              Change the indention character (default: tabs)
	"<Dim>"--indent-size <number>"</Dim>"                   If the indentation style is set to spaces, determine how many spaces should be used for indentation (default: 2)
	"<Dim>"--line-width <number>"</Dim>"                    Change how many characters the formatter is allowed to print in a single line (default: 80)
	"<Dim>"--quote-style <single|double>"</Dim>"            Changes the quotation character for strings (default: \")
	"<Dim>"--quote-properties <as-needed|preserve>"</Dim>"  Changes when properties in object should be quoted (default: as-needed)
	"<Dim>"--trailing-comma <all|es5>"</Dim>"               Changes trailing commas in multi-line comma-separated syntactic structures (default: all)
}
```

```suggestion
"<Emphasis>"OPTIONS:"</Emphasis>"
{FORMAT_OPTIONS}
"
```

and for `rome_format`

```rust
... 
"<Emphasis>"OPTIONS:"</Emphasis>""
	"<Dim>"--write"</Dim>"                                  Edit the files in place (beware!) instead of printing the diff to the console
	"<Dim>"--skip-errors"</Dim>" Skip over files containing syntax errors instead of emitting an error diagnostic.
    {FORMAT_OPTIONS}
	"<Dim>"--stdin-file-path <string>"</Dim>" A file name with its extension to pass when reading from standard in, e.g. echo 'let a;' | rome format --stdin-file-path file.js
};
```

This allows us to keep the format option documentation centralized.

2022-10-20 13:14 UTC, lucasweng commented on crates/rome_cli/src/commands/help.rs
> +"
https://github.com/rome/tools/pull/3457/commits/e5ab712ec59607d82b215046ec6a80978c9fda59 The formatting of the help text
<img width="1661" alt="rome format" src="https://user-images.githubusercontent.com/30640930/196958260-43d00b7e-857a-472f-8920-0774149064be.png">
<img width="1504" alt="rome ci" src="https://user-images.githubusercontent.com/30640930/196958267-38fa537c-0a94-4797-9675-fd59798d9241.png">

2022-10-20 14:43 UTC, ematipico approved these changes

2022-10-20 16:16 UTC, MichaReiser approved these changes

2022-10-20 16:17 UTC, MichaReiser commented
Perfect and thank you!

2022-10-20 16:17 UTC, merged