feat(rome_js_analyze): add `banType` rule
rome/tools pull request #3463
Opened 2022-10-20 11:52 UTC by kaioduarte

## Summary

Closes: 
- #3365 

## Test Plan

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/11046907/196940847-84023d43-647a-491e-a927-42047ecbd2af.png">
<img width="686" alt="image" src="https://user-images.githubusercontent.com/11046907/196940986-783ef1ac-d20f-439b-8e87-7c7cca250a8f.png">

2022-10-20 15:58 UTC, leops commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/ban_types.rs
> +				"The `Function` type accepts any function-like value.",
For longer, detailed explanations like this it would be better readability to use one or more detail advices rather than having everything in the diagnostic message

2022-10-22 11:14 UTC, kaioduarte commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/ban_types.rs
> +				"The `Function` type accepts any function-like value.",
I reworded the messages. Please let me know if it's good now.

2022-10-24 10:12 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_banned_types.rs
> +    /// Disallow certain types
I think we can provide a better documentation here. This explanation is not very beginner-friendly, because it doesn't say explain which types are banned and **why**. It's important that we explain the objective of the rules.

2022-10-24 10:28 UTC, ematipico requested changes

2022-10-24 10:28 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_banned_types.rs
> +    EmptyObject, // {}
Don't be afraid to use rust comments :) This could be a  `/// {}` comment

2022-10-27 09:51 UTC, kaioduarte commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_banned_types.rs
> +    type Query = Ast<TsBannedType>;
Oh, so I need to move the no_explicity_any rule too. 😅

I'll open a separate PR for that.

2022-10-27 10:24 UTC, kaioduarte commented on crates/rome_js_analyze/src/analyzers/nursery/no_banned_types.rs
> +    /// This rule bans specific types and can suggest alternatives. Note that it doesn't ban the corresponding runtime objects from being used.
This description is the same as the ESLint rule. Do we want to change it?

2022-10-27 10:59 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_banned_types.rs
> +    /// This rule bans specific types and can suggest alternatives. Note that it doesn't ban the corresponding runtime objects from being used.
I think it's fine, but I would make quote a markdown quote (using `>`) and add a link to the source

2022-10-27 11:01 UTC, ematipico approved these changes

2022-10-27 12:12 UTC, merged