feat(rome_js_analyze): promote rules
rome/tools pull request #3471
Opened 2022-10-21 12:47 UTC by ematipico

## Summary

## Test Plan

2022-10-25 12:32 UTC, MichaReiser commented
I think we should avoid framework-specific group naming for the same reason we avoided language-specific group naming. Our configuration should have a `framework` section instead where it is possible to configure the used frameworks and the analyzer then enables/disabled rules based on that configuration. 

For example: `noDangerouslySetInnerHtml` should be in the `security` group and can be generalized to `noHtmlInjection`. 

I do understand that we don't have the infrastructure to accomplish this today but that means we should prioritise adding the necessary capabilities to Rome because renaming rules is a confusing experience for our users.

2022-10-25 12:51 UTC, ematipico commented
> I think we should avoid framework-specific group naming for the same reason we avoided language-specific group naming.

How would you solve a possible issue where a rule that targets React goes in conflict with another library that uses JSX?

2022-10-25 12:55 UTC, MichaReiser commented
> > I think we should avoid framework-specific group naming for the same reason we avoided language-specific group naming.
> 
> How would you solve a possible issue where a rule that targets React goes in conflict with another library that uses JSX?

Our configuration should have a framework section instead where it is possible to configure the used frameworks. The analyzer then enables/disabled rules based on that configuration. For example. The react rules only get enabled if you configure the react framework (with an optional version) or, as an alternative, by setting a `javascript.jsxDialect` to `react`. 

The benefit of this approach is that transformation (and maybe even optimisations and bundling) must know about the used frameworks because the transformation may slightly differ.

2022-10-25 13:04 UTC, Boshen commented
I'll help out and test these promoted rules tomorrow (using internal code @ ByteDance).

2022-10-25 16:18 UTC, ematipico commented
@leops  and @xunilrj , could you please chime in and let us know what you think?

2022-10-26 07:53 UTC, MichaReiser commented
On the grouping: 

* noUselessFragments: How is this preventing bugs? In my view, this is more about writing idiomatic JSX and should thus be in the `style` group (or maybe `complexity`)
* useOptionalOperator: Same as for `noUselessFragements`. It isn't preventing bugs but helps you write more idiomatic JavaScript. I could otherwise see this being a `complexity` rule but I would favour `style` because using `?.` doesn't reduce complexity. Which is the case for clippys `?` [operator rule](https://rust-lang.github.io/rust-clippy/stable/index.html#question_mark)




https://github.com/rust-lang/rust-clippy

2022-10-26 09:14 UTC, ematipico commented
> useOptionalOperator: Same as for noUselessFragements. It isn't preventing bugs but helps you write more idiomatic JavaScript. I could otherwise see this being a complexity rule but I would favour style because using ?. doesn't reduce complexity. Which is the case for clippys ? [operator rule](https://rust-lang.github.io/rust-clippy/stable/index.html#question_mark)

I was on the fence on this one. Initially I thought about `style` but then thought that styling issue could be easily overlooked by the users because it cold be seen as "an opinionated set of rules", which a user might just turn off by default. But then I thought about my previous experiences where I encountered `cannot read of undefined` because of a missed a check (let's leave TS out of the equation). Having it in a `style` group feels like not giving enough importance... **but technically, it's a `style` rule**, ultimately.

2022-10-27 09:46 UTC, MichaReiser requested changes
Thanks for working out all the new groups. There's a merge issue in the codegen that must be resolved and I do have a question around the grouping of `noDebugger`:
What are the security concerns around `debugger`? I think if there's a security concern then the lint diagnostic should point that out. I lean towards `correctness` because its useless code in production or has the undesired effect of stopping execution all together

2022-10-27 09:46 UTC, MichaReiser commented on xtask/lintdoc/src/main.rs
> +                    "This group should includes those rules that are meant to prevent possible bugs and misuse of the language."
You have a merge issue here. It reverts my changes to have the `nurserey_rules` last and also reverts some of the wording changes that I made to `correctness`, `style`, and `nurserey`

2022-10-27 09:46 UTC, MichaReiser commented on xtask/lintdoc/src/main.rs
> +                },
Rules that detect potential security flaws.

2022-10-27 09:46 UTC, MichaReiser commented on xtask/lintdoc/src/main.rs
> +                    writeln!(index, "<h3 data-toc-exclude id=\"{rule}\">")?;
The code here also undoes my changes that ensure that lint rules show up in the TOC

2022-10-27 10:28 UTC, ematipico commented
> Thanks for working out all the new groups. There's a merge issue in the codegen that must be resolved and I do have a question around the grouping of `noDebugger`:
> What are the security concerns around `debugger`? I think if there's a security concern then the lint diagnostic should point that out. I lean towards `correctness` because its useless code in production or has the undesired effect of stopping execution all together


My concern is around the fact that deploying code with debugger, would inevitably trigger a breakpoint if someone opens the developer console or runs the debugger in a backend app. Imagine being a library author and a `debugger` gets published.

I don't consider the code useless because. Maybe a misuse of the language but it's also debatable.

2022-10-27 11:13 UTC, MichaReiser commented
> My concern is around the fact that deploying code with debugger, would inevitably trigger a breakpoint if someone opens the developer console or runs the debugger in a backend app. Imagine being a library author and a debugger gets published.

That's why I would consider this a bug/broken code. It is code with unintended effects. I share your sentiment that it doesn't perfectly falls into the `correctness` group but I don't see a security concern.

2022-10-27 11:26 UTC, ematipico commented
@MichaReiser merge conflicts fixed and `noDebugger` moved under `correctness`

2022-10-27 11:36 UTC, MichaReiser approved these changes
Looking good from a code perspective.

Should we re-consider promoting `noUnusedVariables` considering that it still reports a fast number of false positives? 

Do you plan to test the new rules on real projects before merging to verify that they meet our quality criteria?

2022-11-01 07:56 UTC, ematipico commented
> Looking good from a code perspective.
> 
> Should we reconsider promoting `noUnusedVariables` considering that it still reports a vast number of false positives?
> 

The current bugs have been closed. For now I moved it to a stable group and marked as *not recommended*. 

> Do you plan to test the new rules on real projects before merging to verify that they meet our quality criteria?

Yeah I did, and fixed some false positives in other PRs. We should be good to go.

2022-11-01 08:20 UTC, merged