fix(rome_js_analyzer): escape `${` properly for useTemplate rule
rome/tools pull request #3477
Opened 2022-10-23 08:29 UTC by nissy-dev

## Summary

Closes #3451

## Test Plan

I add two test cases and confirmed properly escaped `${`.

2022-10-24 07:35 UTC, MichaReiser requested changes

2022-10-24 07:35 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/correctness/use_template.rs
> +fn escape_dollar_sign(unescaped_string: &str) -> String {
Nit: It would be nice if the function returns a `Cow` to avoid the extra allocation if the string doesn't contain any `${` (which is the case for the majority of strings).

2022-10-24 07:35 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/correctness/use_template.rs
> +        } else if chars[i - 1] != '\\' {
Nice that you thought of that edge case! 

There is one more edge case. It is still necessary to add the `\` if the input is `"\\${"` where the first backslash escapes the second. 

This should be converted to `\\\${` where the third `\` escapes the `${`

2022-10-25 15:43 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/correctness/use_template.rs
> +        } else if chars[i - 1] != '\\' {
Good point. An alternative would be to not error on strings that contain backticks because it having a template literal with many escapes may as well be less readable than using `+` (which we probably can also say is true if the string contains any `${` 

It should be possible to implement this functionality without using the regex crate as it is only necessary to test for the presence of specific characters. We do something similar in `normalize_newlines` where we match on a set of characters and then push the result to a new string. The code doesn't allocate for the cases where the input string contains no new lines because an empty string doesn't allocate in Rust.

https://github.com/rome/tools/blob/293552643e5242282849ee6320f5e8156a1ae75e/crates/rome_formatter/src/format_element.rs#L176-L200

2022-10-25 18:30 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/correctness/use_template.rs
> +        } else if chars[i - 1] != '\\' {
I did a quick test here on a possible generic implementation. I have not spent to much time testing.

We can move this to a util folder and create an extension method for strings.

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=22da992e7b8c070cf54f508114e437ea  

````rust
fn escape<'a>(unescaped_string: &'a str, needs_escaping: &[&str], escaping_char: char) -> std::borrow::Cow<'a, str> {
    let mut  escaped = String::new();
    let mut iter = unescaped_string.char_indices();
    'unescaped: while let Some((idx, chr)) = iter.next() {
       'candidates: for candidate in needs_escaping {
            if unescaped_string[idx..].starts_with(candidate) {
                if escaped.is_empty() {
                    escaped.push_str(&unescaped_string[0..idx]);
                }
                escaped.push(escaping_char);
                escaped.push_str(candidate);
                for _ in candidate.chars().skip(1) {
                    let _ = iter.next();
                }
                continue 'unescaped;
            }
        }
        if !escaped.is_empty() {
            escaped.push(chr);
        }
   }
   
   if escaped.is_empty() {
       std::borrow::Cow::Borrowed(unescaped_string)
   } else {
       std::borrow::Cow::Owned(escaped)
   }
}
````

2022-10-29 12:15 UTC, nissy-dev commented
@xunilrj @MichaReiser Thanks you for your reviews and sorry for my late response! I refered to your comments  and reimplemented escape method. I would like you to review again.

2022-10-31 08:15 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/escape.rs
> +                continue 'candidates;
What's the reason why it is necessary to `continue` with `candiates` here. My understanding is that we've e.g. found a `\${` and skipped it. Shouldn't we now read the next character from the input string?

2022-10-31 08:15 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/escape.rs
> +                }
Can we use `iter.skip(candiate.len_utf8)` instead?

2022-10-31 08:15 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/escape.rs
> +pub fn escape<'a>(
Would you mind adding some documentation explaining what this function does? 

Ideally, with a doc test

2022-10-31 08:15 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/escape.rs
> +        }
The `escape_count` can be simplified to a `bool` because all we need to know is if we have seen an escape character before. 

```suggestion
        if chr == escaping_char {
           is_escaped = !is_escaped;
        }
```


I think it should even allow to simplify the `escape_count % 2 != 0`  by doing

```rust
  if chr == escaping_char {
	is_escaped = !is_escaped;
	continue;
  }

  for candidate in needs_escaping {
    if unescaped_string[idex..].starts_with(candidate) {
    	if !is_escaped {
			if escaped.is_empty() {
				...
			}
			...
		} else {
		}
    }
  }
```

2022-10-31 08:15 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/escape.rs
> +                for _ in candidate.chars().skip(1) {
Why is it necessary to skip `1` character here?

2022-10-31 12:26 UTC, MichaReiser approved these changes
This is looking good to me and we can get this merged after adding some documentation to `escape` and potential simplification of the `escape` implementation

2022-10-31 14:34 UTC, nissy-dev commented on crates/rome_js_analyze/src/utils/escape.rs
> +        }
I thought that we need to know how many escape character is there before characters needs escaping. If there are an odd number of escape characters, a new escape is necessary, but if there are an even number of escape characters, there is no need to add an escape character.

ex)

unescaped: `\${}`     escaped: `\${}`     → no need
unescaped: `\\${}`.   escaped: `\\\${}`.  → need to add `\`
unescaped: `\\\${}`.  escaped: `\\\${}`.  → no need

2022-10-31 14:39 UTC, nissy-dev commented on crates/rome_js_analyze/src/utils/escape.rs
> +                }
`candidate` is String, not char. I seem it is difficult.

2022-10-31 14:42 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/escape.rs
> +        }
I don't think we need the count (as `count % 2` shows). What we need to know is if it is escaped or not. 

* `\\\${` -> has one escaped `\` and one escaped `${` It's not that the escape count is 3 (to my understanding).

2022-10-31 16:02 UTC, nissy-dev commented on crates/rome_js_analyze/src/utils/escape.rs
> +pub fn escape<'a>(
I'll add tomorrow!

2022-10-31 16:05 UTC, nissy-dev commented on crates/rome_js_analyze/src/utils/escape.rs
> +        }
I understand 👍 I refactored and simplified the logic.

2022-10-31 16:07 UTC, nissy-dev commented on crates/rome_js_analyze/src/utils/escape.rs
> +                continue 'candidates;
I refactored and removed this logic.

2022-11-01 08:23 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/escape.rs
> +                    for _ in candidate.chars().skip(1) {
What's the reason that it is necessary to skip 1 in this loop?

2022-11-01 08:23 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/escape.rs
> +        assert_eq!(escape("abc", &["${"], '\\'), "abc");
Can we add a test for an invalid string: `escape(r#"abc\", ...)` I don't think the current implementation handles this correctly

2022-11-01 08:23 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/escape.rs
> +            is_escaped = !is_escaped;
I think we need to push the `escaping_char` here to make sure that we don't drop a final `\` (which is illegal, but something our parser might produce.


```suggestion
            is_escaped = !is_escaped;
            
	        if !escaped.is_empty() {
	            escaped.push(chr);
	        }
```

Or you change it to 

```
if char == escaping_char {
	is_escaped = !is_escaped
} else {
    for candidate in needs_escaping {
	...
}

if !escaped.is_empty() {
	escaped.push(char)
}
```

2022-11-01 08:23 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/escape.rs
> +                }
I think we can simplify this to `is_escaped = false`.

2022-11-01 15:15 UTC, nissy-dev commented on crates/rome_js_analyze/src/utils/escape.rs
> +                    for _ in candidate.chars().skip(1) {
When the condition `if unescaped_string[idx..].starts_with(candidate)` pass, the `idx` indicates the first character of `candidate`.  It means the first character of `candidate` has already iterated.  Therefore we need to skip the rest of `candidate` except the first character.

2022-11-01 15:16 UTC, nissy-dev commented on crates/rome_js_analyze/src/utils/escape.rs
> +                }
I fixed!

2022-11-01 15:17 UTC, nissy-dev commented on crates/rome_js_analyze/src/utils/escape.rs
> +            is_escaped = !is_escaped;
I fixed!

2022-11-01 15:17 UTC, nissy-dev commented on crates/rome_js_analyze/src/utils/escape.rs
> +        assert_eq!(escape("abc", &["${"], '\\'), "abc");
I add a test case!

2022-11-02 08:19 UTC, merged