fix(rome_analyze): move config to a more performant place
rome/tools pull request #3542
Opened 2022-10-31 23:00 UTC by xunilrj

## Summary

This PR does two things:

- Move the config deserialization to a more performant place;
- Allow custom code around the config of rules; In this specific case deserialize the config from a vec, for a more easi configuration schema, to a HashMap, a mor performant data structure.

## Test Plan

```
cargo test
```

2022-10-31 23:00 UTC, xunilrj commented
!bench_analyzer

2022-11-01 11:46 UTC, xunilrj commented
!bench_analyzer

2022-11-01 14:26 UTC, MichaReiser commented on crates/rome_analyze/src/context.rs
> -        options: &'a AnalyzerOptions,
Why must options be an `Arc` if all passes are only "reading" the options?

2022-11-01 15:10 UTC, xunilrj commented
!bench_analyzer

2022-11-03 11:53 UTC, xunilrj commented on crates/rome_analyze/src/context.rs
> -        options: &'a AnalyzerOptions,
This is outdated now.

2022-11-03 13:51 UTC, leops commented on crates/rome_analyze/src/services.rs
> +fn get_id_of(id: &impl Hash) -> u64 {
Using hashes as keys in the service bag opens the possibility of hash collision issues, as two services may be assigned the same key. This would be especially annoying to debug with `TypeId` since it's essentially a randomized value generated by the compiler on every build, making potential collisions hard to reproduce.
Instead of relying on the `Hash` trait to generate keys through a `H: Hash` generic type, we could continue using `TypeId` but allow a key type `K: 'static` to be decoupled from the service type `T`. This would allow us to declare a `struct RuleOption<R: Rule>(PhantomData<R>);` type to be used as the key for the "options service" of a given rule while relying on the compiler to generate unique keys without collision

2022-11-03 13:58 UTC, ematipico commented on crates/rome_js_analyze/src/lib.rs
> +    errors: Vec<OptionsDeserializationDiagnostic>,
nit: `diagnostics`?

2022-11-03 13:58 UTC, ematipico commented on crates/rome_js_analyze/tests/spec_tests.rs
> +    if let Ok(value) = std::env::var("ROME_TEST_RULE_OPTIONS") {
Where is `ROME_TEST_RULE_OPTIONS` coming from? Do we have it somewhere? If so, we should document it

2022-11-03 15:24 UTC, xunilrj commented on crates/rome_analyze/src/services.rs
> +fn get_id_of(id: &impl Hash) -> u64 {
I like it. Let me try.

2022-11-04 15:58 UTC, leops commented on crates/rome_analyze/src/context.rs
> +pub struct SericeBagRuleOptionsWrapper<R: Rule>(pub TypeId, pub R::Options);
Nit: typo `ServiceBagRuleOptionsWrapper`, also it doesn't look like the `TypeId` field is being used anywhere ?

2022-11-26 12:52 UTC, xunilrj commented on crates/rome_js_analyze/src/lib.rs
> +    errors: Vec<OptionsDeserializationDiagnostic>,
Done.

2022-11-26 14:08 UTC, xunilrj commented on crates/rome_js_analyze/tests/spec_tests.rs
> +    if let Ok(value) = std::env::var("ROME_TEST_RULE_OPTIONS") {
I am actually changing the implementation to allow the rule to be configured inside each test file. Makes more sense.

2022-11-26 14:09 UTC, xunilrj commented on crates/rome_analyze/src/context.rs
> +pub struct SericeBagRuleOptionsWrapper<R: Rule>(pub TypeId, pub R::Options);
The TypeId is to guarantee they will have different hashes. In theory two rules can use the same type as option.

2022-11-28 08:56 UTC, leops commented on crates/rome_analyze/src/context.rs
> +pub struct SericeBagRuleOptionsWrapper<R: Rule>(pub TypeId, pub R::Options);
I'm still not sure which hash we're talking about here since the options wrapper doesn't implement `Hash` ?

2022-11-28 10:32 UTC, xunilrj commented on crates/rome_analyze/src/context.rs
> +pub struct SericeBagRuleOptionsWrapper<R: Rule>(pub TypeId, pub R::Options);
hum.. You are right. I don't need it. TypeId will already be different.

2022-11-28 11:08 UTC, ematipico requested changes
Code looks good, but we should update the contribution guidelines

2022-11-28 11:08 UTC, ematipico commented on crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/malformedOptions.js
> +/* Options: {"hook": [["useMyEffect", 0, 1]]} */
What about a `.json` file instead? We use the [same approach in the formatter](https://github.com/rome/tools/blob/main/crates/rome_js_formatter/tests/specs/ts/object/options.json)

Also, would you mind updating the [contributions guidelines](https://github.com/rome/tools/blob/main/crates/rome_analyze/CONTRIBUTING.md#test-a-rule) to explain how to add options to rules?

2022-11-28 18:42 UTC, xunilrj commented on crates/rome_js_analyze/tests/specs/nursery/useExhaustiveDependencies/malformedOptions.js
> +/* Options: {"hook": [["useMyEffect", 0, 1]]} */
Done. Now we can configure each test with a special file.

2022-11-28 22:00 UTC, merged