feat(rome_js_analyze): Implement prefer-numeric-literals lint
rome/tools pull request #3558
Opened 2022-11-03 20:44 UTC by 95th

Implements:
* https://github.com/rome/tools/issues/3360

## Summary

Support prefer-numeric-literals lint rule

## Test Plan

added unit tests for lint.

2022-11-04 09:38 UTC, 95th commented
For some reason, the[ below case ](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgcHJlZmVyLW51bWVyaWMtbGl0ZXJhbHM6IFwiZXJyb3JcIiovXG5OdW1iZXJbYHBhcnNlSW50YF0oJzEyJywgOCkgPT09IDUwMzsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjpbImVycm9yIl0sImZvci1kaXJlY3Rpb24iOlsiZXJyb3IiXSwiZ2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjpbImVycm9yIl0sIm5vLWNhc2UtZGVjbGFyYXRpb25zIjpbImVycm9yIl0sIm5vLWNsYXNzLWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb21wYXJlLW5lZy16ZXJvIjpbImVycm9yIl0sIm5vLWNvbmQtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0LWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb25zdGFudC1jb25kaXRpb24iOlsiZXJyb3IiXSwibm8tY29udHJvbC1yZWdleCI6WyJlcnJvciJdLCJuby1kZWJ1Z2dlciI6WyJlcnJvciJdLCJuby1kZWxldGUtdmFyIjpbImVycm9yIl0sIm5vLWR1cGUtYXJncyI6WyJlcnJvciJdLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOlsiZXJyb3IiXSwibm8tZHVwZS1lbHNlLWlmIjpbImVycm9yIl0sIm5vLWR1cGUta2V5cyI6WyJlcnJvciJdLCJuby1kdXBsaWNhdGUtY2FzZSI6WyJlcnJvciJdLCJuby1lbXB0eSI6WyJlcnJvciJdLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOlsiZXJyb3IiXSwibm8tZW1wdHktcGF0dGVybiI6WyJlcnJvciJdLCJuby1leC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjpbImVycm9yIl0sIm5vLWV4dHJhLXNlbWkiOlsiZXJyb3IiXSwibm8tZmFsbHRocm91Z2giOlsiZXJyb3IiXSwibm8tZnVuYy1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZ2xvYmFsLWFzc2lnbiI6WyJlcnJvciJdLCJuby1pbXBvcnQtYXNzaWduIjpbImVycm9yIl0sIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6WyJlcnJvciJdLCJuby1pbnZhbGlkLXJlZ2V4cCI6WyJlcnJvciJdLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6WyJlcnJvciJdLCJuby1sb3NzLW9mLXByZWNpc2lvbiI6WyJlcnJvciJdLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOlsiZXJyb3IiXSwibm8tbmV3LXN5bWJvbCI6WyJlcnJvciJdLCJuby1ub25vY3RhbC1kZWNpbWFsLWVzY2FwZSI6WyJlcnJvciJdLCJuby1vYmotY2FsbHMiOlsiZXJyb3IiXSwibm8tb2N0YWwiOlsiZXJyb3IiXSwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjpbImVycm9yIl0sIm5vLXJlZGVjbGFyZSI6WyJlcnJvciJdLCJuby1yZWdleC1zcGFjZXMiOlsiZXJyb3IiXSwibm8tc2VsZi1hc3NpZ24iOlsiZXJyb3IiXSwibm8tc2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6WyJlcnJvciJdLCJuby1zcGFyc2UtYXJyYXlzIjpbImVycm9yIl0sIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjpbImVycm9yIl0sIm5vLXVuZGVmIjpbImVycm9yIl0sIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjpbImVycm9yIl0sIm5vLXVucmVhY2hhYmxlIjpbImVycm9yIl0sIm5vLXVuc2FmZS1maW5hbGx5IjpbImVycm9yIl0sIm5vLXVuc2FmZS1uZWdhdGlvbiI6WyJlcnJvciJdLCJuby11bnNhZmUtb3B0aW9uYWwtY2hhaW5pbmciOlsiZXJyb3IiXSwibm8tdW51c2VkLWxhYmVscyI6WyJlcnJvciJdLCJuby11bnVzZWQtdmFycyI6WyJlcnJvciJdLCJuby11c2VsZXNzLWJhY2tyZWZlcmVuY2UiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1jYXRjaCI6WyJlcnJvciJdLCJuby11c2VsZXNzLWVzY2FwZSI6WyJlcnJvciJdLCJuby13aXRoIjpbImVycm9yIl0sInJlcXVpcmUteWllbGQiOlsiZXJyb3IiXSwidXNlLWlzbmFuIjpbImVycm9yIl0sInZhbGlkLXR5cGVvZiI6WyJlcnJvciJdfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==)is not caught (perhaps due to another rule already being applied):

```
Number[`parseInt`]('12', 8);
```

2022-11-05 09:28 UTC, 95th commented
@MichaReiser I am getting the below error on the below test case. Can you please help?
```js
Number.parseInt('17', 8)in foo
```
Error:

```
thread 'specs::style::prefer_numeric_literals_js' panicked at 'There should be no errors in the file "/Users/gurwindersi/tools/crates/rome_js_analyze/tests/specs/style/preferNumericLiterals.js" but the following errors where present:
/Users/gurwindersi/tools/crates/rome_js_analyze/tests/specs/style/preferNumericLiterals.js:63:1 parse ━━━━━━━━━━

  × expected a statement but instead found '0b11in foo
    Number.parseInt('17', 8)in foo
    parseInt('A', 16)in foo
    parseInt('11', 2) in foo
    Number.parseInt('17', 8)/**/in foo
    (parseInt('A', 16))in foo
    /* comment */Number.parseInt('11', 2)'

    61 │ Number.parseInt('17', 8)+5
    62 │ parseInt('A', 16)+5
  > 63 │ 0b11in foo
       │ ^^^^^^^^^^
  > 64 │ Number.parseInt('17', 8)in foo
        ...
  > 68 │ (parseInt('A', 16))in foo
  > 69 │ /* comment */Number.parseInt('11', 2);
       │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    70 │ Number/**/.parseInt('11', 2);
```

2022-11-05 11:08 UTC, 95th commented on crates/rome_js_analyze/src/analyzers/nursery/use_numeric_literals.rs
> +        suggested = suggested.with_trailing_trivia(iter::once((TriviaPieceKind::Whitespace, " ")));
@MichaReiser I Tried adding the whitespace but doesn't seem to fix the issue.

2022-11-05 19:31 UTC, 95th commented on crates/rome_diagnostics_categories/src/categories.rs
> +    "lint/style/preferNumericLiterals": "https://rome.tools/docs/lint/rules/preferNumericLiterals",
👍 Moved

2022-11-05 19:31 UTC, 95th commented on crates/rome_js_analyze/src/analyzers/style/prefer_numeric_literals.rs
> +        version: "0.7.0",
👍 Updated

2022-11-05 19:31 UTC, 95th commented on crates/rome_js_analyze/src/analyzers/style/prefer_numeric_literals.rs
> +        recommended: true,
👍 Updated

2022-11-05 19:31 UTC, 95th commented on crates/rome_js_analyze/src/analyzers/style/prefer_numeric_literals.rs
> +        name: "preferNumericLiterals",
👍 Updated

2022-11-05 19:31 UTC, 95th commented on crates/rome_js_analyze/src/analyzers/style/prefer_numeric_literals.rs
> +        get_call_info(node)
👍 Updated

2022-11-05 19:31 UTC, 95th commented on crates/rome_js_analyze/src/analyzers/nursery/use_numeric_literals.rs
> +        suggested = suggested.with_trailing_trivia(iter::once((TriviaPieceKind::Whitespace, " ")));
Fixed

2022-11-07 09:01 UTC, MichaReiser requested changes
Nice work! 

We prefer to have extension methods on the AstNodes in `rome_js_syntax` rather than standalone utility methods to make them available to all creates using JavaScript nodes. Could you check if you can move some of the `ast_util` methods to extension methods?

We should refine the lint rule to only trigger on global `parseInt` calls. Yes, it's unlikely that someone rolls their own `parseInt`, but it's probably still worth safeguarding against it.

2022-11-07 16:47 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/use_numeric_literals.rs
> +            applicability: Applicability::Always,
We're generally very strict about the code actions having an applicability of `Always` since those represent "safe fixes" that can be automatically applied. As such we must be absolutely certain they do not change the semantics of the program, which is why very few rules mark their fix as safe for now (since correctly mutating the syntax tree is hard it also allows us to consider the fix unstable even if the rule and linter are stable).
If there's a risk that the code action produces a program with a different behavior, or even an invalid syntax tree if trivia is not handled correctly in some edge case, then the applicability should be set to `MaybeIncorrect` (we may eventually enforce this for rules in the `nursery` group since they're unstable by definition)

2022-11-08 14:20 UTC, 95th commented
>We should refine the lint rule to only trigger on global parseInt calls. Yes, it's unlikely that someone rolls their own parseInt, but it's probably still worth safeguarding against it.

Would it be possible using the `SemanticModel`?

2022-11-08 16:31 UTC, 95th commented on crates/rome_js_analyze/src/ast_utils.rs
> +            },
Updated

2022-11-08 16:31 UTC, 95th commented on crates/rome_js_analyze/src/ast_utils.rs
> +                }
Updated

2022-11-08 16:31 UTC, 95th commented on crates/rome_js_analyze/src/ast_utils.rs
> +    JsName::can_cast(syntax.kind()) && syntax.text_trimmed() == name
moved to expr_ext

2022-11-08 16:32 UTC, 95th commented on crates/rome_js_analyze/src/analyzers/correctness/no_async_promise_executor.rs
> +    let expr = ast_utils::remove_parentheses(expr.clone())?;
Updated

2022-11-08 16:32 UTC, 95th commented on crates/rome_js_analyze/src/analyzers/complexity/no_extra_boolean_cast.rs
> +    Some(ast_utils::is_ident_eq(&callee, "Boolean"))
Updated

2022-11-08 16:32 UTC, 95th commented on crates/rome_js_analyze/src/analyzers/nursery/use_numeric_literals.rs
> +    }
Would it be possible using the SemanticModel?

2022-11-08 18:36 UTC, 95th commented on crates/rome_js_analyze/src/analyzers/nursery/use_numeric_literals.rs
> +    }
Fixed.

2022-11-09 15:40 UTC, MichaReiser commented on crates/rome_js_analyze/src/react.rs
> +fn is_imported_from_react(
There are a few new helpers for test if something is a react call (`is_react_call_api` and `is_react_export`) when you rebase on main.

2022-11-09 18:58 UTC, 95th commented on crates/rome_js_analyze/src/ast_utils.rs
> +    if !token.kind().is_punct() && token.trailing_trivia().text().is_empty() {
I think text here is returning `&str` reference. `pieces` iter also seems to be doing some work (which looked more to me).

2022-11-10 08:17 UTC, 95th commented on crates/rome_js_syntax/src/expr_ext.rs
> +    }
Updated to return the reference identifier

2022-11-10 08:17 UTC, 95th commented on crates/rome_js_syntax/src/expr_ext.rs
> +    }
Updated.

2022-11-10 08:18 UTC, 95th commented on crates/rome_js_syntax/src/expr_ext.rs
> +    }
Done

2022-11-10 08:18 UTC, 95th commented on crates/rome_js_syntax/src/expr_ext.rs
> +        object: impl FnOnce(JsReferenceIdentifier) -> bool,
Updated to return the reference identifier

2022-11-10 08:19 UTC, 95th commented on crates/rome_js_syntax/src/expr_ext.rs
> +    }
Updated

2022-11-10 08:20 UTC, 95th commented on crates/rome_js_syntax/src/expr_ext.rs
> +    pub fn as_string_or_no_substitution_template(&self) -> Option<String> {
Updated

2022-11-10 08:20 UTC, 95th commented on crates/rome_js_syntax/src/expr_ext.rs
> +    pub fn is_string_or_no_substitution_template(&self, text: &str) -> bool {
Updated

2022-11-10 08:20 UTC, 95th commented on crates/rome_js_syntax/src/expr_ext.rs
> +impl JsAnyExpression {
Done

2022-11-10 08:20 UTC, 95th commented on crates/rome_js_analyze/src/react.rs
> +fn is_imported_from_react(
Updated

2022-11-10 08:24 UTC, 95th commented on crates/rome_js_analyze/src/ast_utils.rs
> +    if !token.kind().is_punct() && token.trailing_trivia().text().is_empty() {
Updated

2022-11-10 16:53 UTC, MichaReiser commented on crates/rome_js_syntax/src/expr_ext.rs
> +    pub fn get_object_reference_identifier(&self) -> Option<JsReferenceIdentifier> {
I'm a bit worried by all the added extension methods. We should avoid adding specific accessors for every possible expression and every field. It would result in too many methods that are also hard to name (and, because of that, hard to understand). 

I think some of them like `is_string_constant` are useful and best implemented on `JsAnyExpression` but others may be better placed elsewhere:

* If used rarely, I would recommend inlining them
* for member expressions: We can define a new `JsAnyMemberExpression` type (in `union_ext` using the `declare_node_union` macro: 

```
declare_node_union! {
    pub(crate) JsAnyMemberExpression = JsStaticMemberExpression | JsComputedMemberExpression
}
```

You can then move all the member expression helpers to that newly defined type. This new type behaves the same as any other AST Node: `JsAnyMemberExpression::cast(node.syntax())`

2022-11-12 05:07 UTC, 95th commented on crates/rome_js_syntax/src/expr_ext.rs
> +    pub fn get_object_reference_identifier(&self) -> Option<JsReferenceIdentifier> {
Yes. Agree. Updated.

2022-11-14 08:50 UTC, MichaReiser approved these changes

2022-11-14 08:51 UTC, MichaReiser commented
Thank you so much @95th for this contribution. Looking all good. Can you rebase your changes to resolve the merge conflicts, and we're good to

2022-11-14 11:01 UTC, merged