feat(rome_analyze): allow suppress rule via code actions
rome/tools pull request #3572
Opened 2022-11-06 13:56 UTC by ematipico

## Summary

## Test Plan

2022-11-15 11:47 UTC, ematipico commented
!bench_analyzer

2022-11-15 15:47 UTC, ematipico commented
> What happens if you add a suppression to a JSX node?
> 
> ```
> <div>
>   <>useless</> <- suppress this
> </div>
> ```

Uuuuuuh! Good question! I didn't think about this case! It will break for sure, because the insertion of the comment is hard coded. 

Considering the fact that this new feature is exclusively opt-in, I can remove the feature of `use_alt_text` for now, and fix it later once I improve the testing suite for these kind of actions.

2022-11-16 09:55 UTC, leops commented on crates/rome_lsp/src/handlers/analysis.rs
> +                        .map(is_suppression_action_kind)
This shouldn't be needed, ideally the `suppressRule` code action should be marked as a fix for the associated diagnostics

2022-11-16 09:55 UTC, leops commented on crates/rome_analyze/src/signals.rs
> +    fn actions(&self) -> Option<AnalyzerActionIter<L>>;
It would be more straightforward to simply return an iterator from `actions`, yielding an empty iterator when the signal has no action

2022-11-16 09:55 UTC, leops commented on crates/rome_analyze/src/rule.rs
> +    fn can_suppress(
I still think it would be possible to have this implemented by default for all rules (and retain the ability for some of them to opt-out by manually implementing this hook to return `None`) since the location at which the suppression comment should be emitted is generally derived from the primary `TextRange` of the emitted diagnostic independently of the query type:
https://github.com/rome/tools/blob/1837140418c44f25b17f577f8946987945464e9d/crates/rome_analyze/src/registry.rs#L356-L357

We can also easily avoid emitting this code action for non-lint rules by matching the value of `<<Self::Group>::Category>::CATEGORY` against `RuleCategory::Lint`

2022-11-16 10:28 UTC, ematipico commented on crates/rome_lsp/src/handlers/analysis.rs
> +                        .map(is_suppression_action_kind)
It's needed because the condition doesn't fit the use case:
- `fix_all_kind` is just a wrapper for `SourceActionKind::FixAll` which doesn't cover suppressions
- the action generated for a suppression action doesn't contain `diagnostics`

2022-11-16 11:17 UTC, leops commented on crates/rome_lsp/src/handlers/analysis.rs
> +                        .map(is_suppression_action_kind)
Sorry what I meant is that the second point shouldn't be true, the action should have a `diagnostics` pointing to the diagnostic it's suppressing

2022-11-18 15:13 UTC, leops commented on crates/rome_js_analyze/src/lib.rs
> +            let new_token = current_token.with_leading_trivia(vec![
We should try to keep the existing trivia here otherwise we could end up dropping comments the token may have had already

2022-11-18 15:16 UTC, leops commented on crates/rome_js_analyze/src/lib.rs
> +        find_token_with_newline(token)
Could we refactor this to use a loop instead of recursion, just to avoid overflowing the stack while processing a minified file with many tokens on the same line

2022-11-18 15:22 UTC, leops commented on crates/rome_js_analyze/src/utils/batch.rs
> +    fn add_jsx_element_after_element(
Could this function be made generic  for every `SyntaxList` instead of just `JsxChildList` ? We could then move it to `BatchMutation` directly

2022-11-18 15:23 UTC, leops commented on crates/rome_lsp/tests/server.rs
> +    suppression_changes.insert(lsp::Url::parse("test://workspace/document.js")?, vec![]);
That doesn't look correct, the changes shouldn't be empty

2022-11-18 15:24 UTC, leops commented on crates/rome_lsp/tests/server.rs
> +        is_preferred: Some(true),
I don't think we should mark the "Suppress rule" action as the preferred fix, since it's only silencing the issue and not really fixing it

2022-11-18 15:25 UTC, leops commented on crates/rome_rowan/src/ast/batch.rs
> +        self.replace_element_discard_trivia(prev_token.into(), next_token.into())
This `_transfer_trivia` function is calling `_discard_trivia` under the hood

2022-11-21 09:24 UTC, ematipico commented on crates/rome_analyze/src/signals.rs
> +impl<L: Language> AnalyzerSignal<L> for AnalyzerAction<L> {
Sorry about, this is old code that can be removed

2022-11-21 10:26 UTC, ematipico commented on crates/rome_js_analyze/src/lib.rs
> +        if let Some(element) = current_token.ancestors().find_map(|node| {
The whole function is likely wrong and I plan to change it in the next PR. There are a lot of cases we need to get right and this simple function is not enough. I will push a few changes, but I need to review it in a second pass.

2022-11-21 10:32 UTC, ematipico commented on crates/rome_js_analyze/src/utils/batch.rs
> +    fn add_jsx_element_after_element(
It will do it in the next PR. The work involved is bigger than I expected

2022-11-21 13:17 UTC, leops approved these changes

2022-11-22 07:36 UTC, MichaReiser requested changes

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_analyze/src/lib.rs
> +/// Convenient type that to mark a function that is responsible to create a mutation to add a suppression comment.
I don't understand this sentence and I don't see it hold a function. Is the comment for the `SuppressionCommentEmitter`?

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_analyze/src/matcher.rs
> +            |_| unreachable!(),
Why is this unreachable?

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_analyze/src/rule.rs
> +    /// has to return the node to which the suppression comment needs to be applied.
```suggestion
    /// returns the node to which the suppression comment is applied.
```

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_analyze/src/signals.rs
> +        }
No need to use a `vec` here
```suggestion
        if let Some(action) = (self.action)() {
            AnalyzerActionIter::new([action])
        } else {
            AnalyzerActionIter::new([])
        }
```

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_analyze/src/signals.rs
> +    pub fn new(actions: Vec<AnalyzerAction<L>>) -> Self {
Nit: Can we change this to accept any type that implements IntoIter
```suggestion
    pub fn new<I>(actions: I) -> Self where I: IntoIter<Item = AnalyzerAction<L>> {
```

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_js_analyze/src/lib.rs
> +        if let Some(element) = current_token.ancestors().find_map(JsxAnyChild::cast) {
We should avoid using `ancestors` whenever possible. This will "bleed" into nested JSX children

```
<button onClick={() =>  {
	console.log("test"); // <- Apply suppression here
  }
>
  content
</button>
```

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_js_analyze/src/lib.rs
> +            let new_token = current_token.with_leading_trivia(vec![
You can use an array instead of a vec
```suggestion
            let new_token = current_token.with_leading_trivia([
```

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_js_analyze/src/lib.rs
> +            let new_token = current_token.with_leading_trivia(vec![
Have you pending changes that you haven't pushed that this is market as resolved?

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/batch.rs
> +        let old_list = after_element.syntax().parent().and_then(JsxChildList::cast);
You can use
```suggestion
        let old_list = after_element.parent::<JsxChildList>();
```

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/batch.rs
> +                    let list = JsxChildList::cast(parent)?;
Isn't `list` the same as `old_list`?

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/batch.rs
> +                    let mut new_items = vec![];
Same as for the method above

2022-11-22 07:36 UTC, MichaReiser commented on crates/rome_rowan/src/ast/batch.rs
> +            .collect();
We could avoid calling `collect` here when we move the `chain_pieces` iterator to `rowan` 

https://github.com/rome/tools/blob/f17ace37b47a6ab02bae457851b950a7ec86faf0/crates/rome_js_formatter/src/syntax_rewriter.rs#L433-L528

2022-11-22 08:49 UTC, ematipico commented on crates/rome_analyze/src/matcher.rs
> +            |_| unreachable!(),
It's inside a test case, and that code is not triggered

2022-11-22 09:06 UTC, ematipico commented on crates/rome_rowan/src/ast/batch.rs
> +            .collect();
We had the function all along and I didn't know that?? Now things will get waaaay easier!

2022-11-22 09:20 UTC, ematipico commented on crates/rome_rowan/src/ast/batch.rs
> +            .collect();
I will move this function to my next PR, there's still some other changes I need to do in the batch APIs

2022-11-22 09:21 UTC, ematipico commented on crates/rome_js_analyze/src/lib.rs
> +        if let Some(element) = current_token.ancestors().find_map(JsxAnyChild::cast) {
As I pointed out in some other comment of mine, this function is not exhaustive and is likely broken. I will apply more changes in my next PR (together with proper tests)

2022-11-22 15:41 UTC, merged