feat(rome_js_formatter): jestEach template literals #3308
rome/tools pull request #3582
Opened 2022-11-08 08:11 UTC by denbezrukov

## Summary

Close https://github.com/rome/tools/issues/3308

## Test Plan

`cargo test -p rome_js_formatter`

2022-11-08 08:24 UTC, denbezrukov commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +                            text.push(' ');
I was wondering if we could use `space` instead of `' '`

2022-11-08 13:59 UTC, MichaReiser requested changes
Awesome work. I have some small nit comments. 

One thing we need to look into is guarding against skipped token trivia on elements that you remove. Because that would result in the skipped token trivia being emitted before the template. 

I recommend testing for skipped token trivia in the `is_test_each_pattern` and bail out if it has any. 

The alternative is to use the `FormatError::PoorLayout` and catch the template formatting error to fall back to the default formatting. I think explicitly testing is nicer and the overhead should be reasonable (considering the complexity of doing the formatting).

2022-11-08 13:59 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +        };
Is this something we test for in `is_test_each_pattern`? If not, it would probably be better to fall back to the default template formatting in that case.

2022-11-08 13:59 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +        f.context().comments().is_suppressed(header.syntax());
Nit: You can use `marked_suppressed` if you are not really interested in knowing if the node is suppressed but only want to mark it as handled. 

Or you can do `debug_assert!(!f.context().comments().is_suppressed(header.syntax()))`

to assert that the header never is suppressed in debug builds only

2022-11-08 13:59 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +                    f.context().comments().is_suppressed(element.syntax());
Nit: Use `mark_suppressed` or `debug_assert(!f.context()....)`

2022-11-08 13:59 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +                    let text = printed.into_code();
Printing to a string comes with some overhead. Would it be possible to instead keep hold of the `Vec<FormatElement>` and write that to the target buffer: `f.write_elements(elements)`. You can use `f.intern_vec(elements)` if `elements is huge to avoid copying too much data

2022-11-08 13:59 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +    }
Nit: You could change the implementation to a `EachTemplateBuilder` where `finish` consumes self and returns a `EachTemplate`. Doing so would make it clear what state is only necessary for building the table and ensures that `finish` is called exactly once.

2022-11-08 13:59 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +    columns_width: Vec<usize>,
Nit: You can use `TextSize` for the width because Rome only supports documents up to 4gb (which is massive :D)

2022-11-08 13:59 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +    columns_width: Vec<usize>,
Nit: Use `TextSize` instead of `usize`

```suggestion
    column_widths: Vec<usize>,
```

`columns_width` -> `column_widths` to make it clear its the widths of the columns and not the total width of all columsn

2022-11-08 13:59 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +                    let has_line_break = element.template_chunk_token()?.text().contains('\n');
I think we should use `text_trimmed` here to correctly handle skipped token trivia

2022-11-08 13:59 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +                            text = " ".to_string() + &text;
Nit: You can use `format!(" {text}")`

2022-11-08 13:59 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +                            text.push(' ');
`space` won't work because our printer de-duplicates spaces (`space(), space()` gets printed as a single space). 

You can try to use  `align` instead but I think using ' ' is fine.

2022-11-09 08:08 UTC, denbezrukov commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +                            text = " ".to_string() + &text;
Done.

2022-11-09 08:08 UTC, denbezrukov commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +                    let has_line_break = element.template_chunk_token()?.text().contains('\n');
Done

2022-11-09 08:09 UTC, denbezrukov commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +    columns_width: Vec<usize>,
done

2022-11-09 08:09 UTC, denbezrukov commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +    }
It's a great idea, I like it!

2022-11-09 08:10 UTC, denbezrukov commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +                    let text = printed.into_code();
We can't avoid it because we need to get a string width =(

2022-11-09 08:11 UTC, denbezrukov commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +                    f.context().comments().is_suppressed(element.syntax());
Done

2022-11-09 08:11 UTC, denbezrukov commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +        f.context().comments().is_suppressed(header.syntax());
Done

2022-11-09 08:11 UTC, denbezrukov commented on crates/rome_js_formatter/src/utils/test_each_pattern.rs
> +        };
Added this test in `is_test_each_pattern_elements` function.

2022-11-09 08:14 UTC, denbezrukov commented
> Awesome work. I have some small nit comments.
> 
> One thing we need to look into is guarding against skipped token trivia on elements that you remove. Because that would result in the skipped token trivia being emitted before the template.
> 
> I recommend testing for skipped token trivia in the `is_test_each_pattern` and bail out if it has any.
> 
> The alternative is to use the `FormatError::PoorLayout` and catch the template formatting error to fall back to the default formatting. I think explicitly testing is nicer and the overhead should be reasonable (considering the complexity of doing the formatting).

Thank you for your review!

I added `is_test_each_pattern_elements` function, where we test that each node we remove does not contain any trivia.

2022-11-09 14:23 UTC, MichaReiser approved these changes
Awesome work!

I'll merge it after we pushed the 10.0.1 patch release.

2022-11-09 14:23 UTC, MichaReiser commented on crates/rome_js_formatter/src/utils/test_call.rs
> +                }
Is this the test asserting if it has any skipped token trivia?

That's probably going to work but using `leading_trivia.has_skipped()` is more explicit and easier to understand to readers.

2022-11-09 14:24 UTC, MichaReiser commented
!bench_formatter

2022-11-09 14:40 UTC, denbezrukov commented on crates/rome_js_formatter/src/utils/test_call.rs
> +                }
Fixed.

2022-11-14 08:07 UTC, merged