chore(VSCode): publish extension to Open VSX
rome/tools pull request #3677
Opened 2022-11-11 20:48 UTC by sebmck

## Summary

Adds publishing to [Open VSX](https://open-vsx.org/) to our release actions.

## Test Plan

Not sure? cc @ematipico @leops for how I might test this. If the changes look okay then we can wait for the next release before publishing our first version.

2022-11-12 15:25 UTC, MichaReiser commented on .github/workflows/release_lsp.yml
> +        run: npx vsce publish --pre-release --packagePath rome_lsp-*.vsix
The command must be `ovsx` according to the documentation.

```
npx ovsx publish <file> -p <token>
```

We probably need to add it as a dependency too

2022-11-12 19:09 UTC, sebmck commented on .github/workflows/release_lsp.yml
> +        run: npx vsce publish --pre-release --packagePath rome_lsp-*.vsix
Oh oops. Adding it as a dependency isn't necessary as `npx` will install if it isn't already.

2022-11-12 22:32 UTC, sebmck commented
Fixed binary reference. I've also added the Open VSX PAT token to the `marketplace` environment so this should just work.

2022-11-13 11:13 UTC, MichaReiser commented
Looks good. Can you manually trigger an LSP workflow and then approve it to publish a nightly release to the marketplace? 

https://github.com/rome/tools/actions/workflows/release_lsp.yml

2022-11-14 07:34 UTC, MichaReiser requested changes
Please update the test plan with a run of the LSP action.

2022-11-14 07:38 UTC, ematipico commented
What's the documentation plan of this PR? I assume this needs to be documented somewhere on our website

2022-11-14 07:41 UTC, MichaReiser commented
> What's the plan to document this? I assume this needs to be documented somewhere on our website

We should mention it in the VS Code section

2022-11-14 11:15 UTC, ematipico commented
> > What's the plan to document this? I assume this needs to be documented somewhere on our website
> 
> We should mention it in the VS Code section

Sorry, I actually meant the real plan. There wasn't any issue to track documentation changes, so I wanted to know where/how we take note of this new change.

2022-11-16 09:12 UTC, MichaReiser commented
Test plan: https://github.com/rome/tools/actions/runs/3477745546/jobs/5814546845

2022-11-16 09:14 UTC, MichaReiser approved these changes

2022-11-16 09:14 UTC, merged