Use const
rome/tools pull request #3680
Opened 2022-11-11 21:50 UTC by 95th

## Summary

Implements eslint's [`prefer-const`](https://eslint.org/docs/latest/rules/prefer-const).

## Test Plan

Unit tests.

2022-11-14 08:42 UTC, MichaReiser requested changes

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_syntax/src/source_type.rs
> +            "json" | "jsonc" => SourceType::js_module(),
What is this change necessary for? 

It seems that the JSON addition is for test only, but this change also affects non-test code (and can result in Rome picking up JSON files and parsing them with the JS parser). Json files should be handled by our upcoming JSON parser.

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_analyze/Cargo.toml
> +json_comments = "0.2.1"
Can we make this a test only dependency

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +    /// // `i` is redefined (not reassigned) on each loop step.
`i` does not exist in this example. What's the difference between this test and the case below?

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +    /// ```
Can we add a test case for shadowed variables?

```
let a = 3;

{
	let a = 4;
	a = 2;
}
```

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +                signals.push(info);
Would it be possible to only push the bindings that need to be `const` vs pushing all of them? 

Writing data is expensive and it seems that `action` has to filter the data right after. 

```rust
let signals = Vec::from(
	declarator_bindings(&declarator).filter_map(|binding| 
		ConstantBinding::from_binding(binding, declaration, &declarator, model)
	)
);
```

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +    type Signals = Option<Self::State>;
Can `Signal` be `Self::State` if you use an empty vec to signal that there are no code actions.

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +    ///
Can we add a test for a declarator with multiple declarations

```
let a = 1, b = 2;

b = 3;
```

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +        }
Nit: We can move this to line 74 because this condition is true for all declarators

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +                .map_or(false, |it| it.kind() == JsSyntaxKind::LET_KW),
Nit: Make an extension method on `JsForVariableDeclaration`?

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +                    None
Nit: It may help future readers to document that this handles the case where:

```
if (a) b = 10
```

2022-11-14 08:42 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +}
Same as above. Using `descendents` here likely yields incorrect results if any variable has a function like initializer

2022-11-14 10:47 UTC, 95th commented on crates/rome_js_analyze/Cargo.toml
> +json_comments = "0.2.1"
It is already in `dev-dependencies`. Is there a separate section for test?

2022-11-14 10:52 UTC, MichaReiser commented on crates/rome_js_analyze/Cargo.toml
> +json_comments = "0.2.1"
Whoops, sorry

2022-11-14 11:08 UTC, 95th commented on crates/rome_js_syntax/src/source_type.rs
> +            "json" | "jsonc" => SourceType::js_module(),
It was needed for supporting multiple small scripts in Json format. I removed this from here and now passing it in spec_tests.

2022-11-14 11:08 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +    /// // `i` is redefined (not reassigned) on each loop step.
Updated var name. diff is `in` or `of` loop.

2022-11-14 11:08 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +    /// ```
Added

2022-11-14 11:09 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +                signals.push(info);
Now adding only bindings that need reporting.

2022-11-14 11:10 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +    type Signals = Option<Self::State>;
NA anymore.

2022-11-14 11:10 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +    ///
Added

2022-11-14 11:10 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +        }
Moved

2022-11-14 11:10 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +        decl: &VarDecl,
Updated

2022-11-14 11:13 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +                .map_or(false, |it| it.kind() == JsSyntaxKind::LET_KW),
Updated

2022-11-14 11:17 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +                    None
Updated

2022-11-14 15:47 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +            .filter_map(JsVariableDeclarator::cast)
One of them has declarators and the other has only one. I want to provide a uniform output.. Collecting to vec would be costly..
I have changed it to take a callback

2022-11-15 08:48 UTC, MichaReiser commented
!bench_analyzer

2022-11-15 15:52 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +}
Fixed with typed ast traversal

2022-11-15 15:52 UTC, 95th commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/use_const.rs
> +        .filter_map(JsIdentifierBinding::cast)
Fixed with typed ast traversal

2022-11-16 09:04 UTC, MichaReiser approved these changes

2022-11-16 09:04 UTC, merged

2022-11-16 09:05 UTC, MichaReiser commented
Very well done. Thank you for implementing this surprisingly complicated rule!