fix(rome_js_analyze): improve the detection of invalid cases in `noArrayIndexKey`
rome/tools pull request #3681
Opened 2022-11-11 22:35 UTC by lucasweng

## Summary

- Resolves https://github.com/rome/tools/issues/3670

## Test Plan

Added new test cases

2022-11-14 08:07 UTC, MichaReiser requested changes
Thanks for your PR. I think there are some more issues with the rule (unrelated to your changes) and it may be possible to simplify the finding of the closest call expression.

2022-11-14 08:07 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +        let syntax = self.syntax();
Isn't it possible to instead navigate upwards from the function like node as we know that the function must be the first argument of a call expression:

* Skip over parenthesized expressions: `self.syntax.ancestors().skip_while(|ancestor| JsParenthesizedExpression::can_cast(ancestor))`
* Skip over the `JsCallArgumentList` and `JsCallArguments` `....skip(2)`

then test if the next parent is a `JsCallExpression`
* `ancestors.next().and_then(JsCallExpression::cast)`


Using `find_map` is "dangerous" as it is very easy to accidentally navigate too far up in the tree (similar to recursion if you miss the base case)

2022-11-14 08:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +    let function_parent = function_like_node.find_caller_parent()?;
Unrelated to your change: It should be possible to speed up this rule by matching on `JsxAttribute` and `JsPropertyObjectMember` instead because the current rule matches on every element and then traverses all attributes, resulting in that the attributes are traversed twice (once by this rule and once by the traversal of the lint runner). 

Matching on the attributes /properties instead would avoid that

2022-11-14 22:28 UTC, lucasweng commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +
Agreed. I cannot think of some real-world use case where a `JsMethodClassMember` is inside `map`, though I think it's likely (def not good practice 😅) to have a `JsMethodObjectMember` inside `map`

```js
things.map((thing, index) => {
    const map = {
        foo(someAttr) {
            return <Component key={index} {...someAttr} />)
        }
        // ...
    }
    return map[thing.name](getAttr(thing))
})
```

2022-11-15 00:46 UTC, lucasweng commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +        let syntax = self.syntax();
Not sure if I understand your suggestion correctly. After changing `find_caller_parent` to the following
```rust
    fn find_caller_parent(&self) -> Option<JsCallExpression> {
        let ancestors = self
            .syntax()
            .ancestors()
            .skip_while(|ancestor| JsParenthesizedExpression::can_cast(ancestor.kind()));
        // Skip over the JsCallArgumentList and JsCallArguments
        let mut ancestors = ancestors.skip(2);
        ancestors.next().and_then(JsCallExpression::cast)
    }
```
all the snapshot tests for this rule are failing (`find_function_like_ancestor` and `FunctionLike` not modified yet)
🤔 But it should work according to the [AST](https://docs.rome.tools/playground/?code=YwBvAG4AcwB0ACAARgBvAG8AIAA9ACAAKAApACAAPQA%2BACAAdABoAGkAbgBnAHMALgBtAGEAcAAoACgAXwAsACAAaQBuAGQAZQB4ACkAIAA9AD4AIAA8AEMAbwBtAHAAbwBuAGUAbgB0ACAAawBlAHkAPQB7AGkAbgBkAGUAeAB9ACAALwA%2BACkAOwA%3D), no?

2022-11-15 07:14 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +        let syntax = self.syntax();
Oh, I think you have to add one additional `skip(1)` because `ancestors` returns all nodes starting from the current one.

```
let ancestors = self.syntax().ancestors().skip(1).skip_while(...)
```

2022-11-16 14:19 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +    JsMethodObjectMember, JsParameterList, JsParenthesizedExpression, JsPropertyObjectMember,
I'm sorry for commenting here but GitHub doesn't allow me to comment unchanged lines. 

We should use the semantic model to resolve where the expression assigned to `key` is declared. This replaces the `find_function_parent` call on line 135

```rust
        let Some(parameter) = model
            .declaration(&reference)
            .and_then(|declaration| declaration.syntax().parent())
            .and_then(JsFormalParameter::cast);

        let Some(function) = parameter
            .parent::<JsParameterList>()
            .and_then(|list| list.parent::<JsParameters>())
            .and_then(|parameters| parameters.parent::<JsAnyFunction>()) else { return None; };

        let Some(call_expression) = parameter
            .parent::<JsCallArgumentList>()
            .and_then(|arguments| arguments.parent::<JsCallArguments>())
            .and_then(|arguments| arguments.parent::<JsCallExpression>()) else { return None };
```

2022-11-16 14:19 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +    JsReferenceIdentifier, JsxAttribute, JsxOpeningElement, JsxSelfClosingElement,
The code in `find_react_children_function_argument` doesn't work correctly because it navigates all the way up until it finds the outmost `ExpressionStatement`. This will yield incorrect results if the `call expression` is e.g. nested in a conditional or a return statement.

Instead, the logic should simply navigate upwards, similar to what I recommend for resolving the binding

It should then no longer be necessary to use `FunctionLike` in this rule

2022-11-16 16:04 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +    JsMethodObjectMember, JsParameterList, JsParenthesizedExpression, JsPropertyObjectMember,
> Then traverse down to check if the declaration is the second argument of the function call to avoid false positive like the following

You can probably use `parameter.syntax().index()`. It gives you the index in the enclosing parameter list (you have to divide it by two because the list elements are `parameter`, comma, parameter2`.



> React.Children.forEach(this.props.children, (_, index) => {
  const obj = {key: index}
  // we don't know if the key above is used as `JsxAttribute`
  return notCloneElement(obj)
})

I'm not sure if I understand the question/problem here. I believe it should be sufficient to only detect calls to `cloneElement` where the object is the argument `cloneElement { key: index }`. 

The way I would expect `cloneElement` to work if you match on object member is that:

* You test if the object member name is `key`
* You navigate upwards from the object member until you find the enclosing call expression
* You test if it is a react API call 
* If that's the case, do the same as for JSX elements by resolving the binding for `index`
  * then finding the enclosing call expression
  * test if the call expression is an array method.

2022-11-18 01:15 UTC, lucasweng commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +    JsMethodObjectMember, JsParameterList, JsParenthesizedExpression, JsPropertyObjectMember,
https://github.com/rome/tools/pull/3681/commits/bc7a03c47b93f374874867021f488e4260997f94 now the rule is matching on `JsxAttribute` and `JsPropertyObjectMember`, and it will
1. Find if it's a key property
2. Retrieve the reference identifier from the key property,
3. Use the semantic model to find the declaration of the reference is a parameter in a function expression
4. Find the enclosing call expression
5. Check if the call expression is an array method and the parameter is the array index of that method
6. If it's matching on `JsPropertyObjectMember`, detect calls to `cloneElement`

Also, added tests for `flatMap` and `Array.from`

How do we test if the current implementation is faster than the previous one?

2022-11-18 01:57 UTC, lucasweng commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +    JsMethodObjectMember, JsParameterList, JsParenthesizedExpression, JsPropertyObjectMember,
Not sure if I can remove `ReactCloneElementCall::from_call_expression`, it's no longer used because of this refactor

2022-11-18 08:05 UTC, MichaReiser commented
!bench_analyzer

2022-11-18 08:06 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs
> +    JsMethodObjectMember, JsParameterList, JsParenthesizedExpression, JsPropertyObjectMember,
> `ReactCloneElementCall`

It's safe to remove the method as it is [no longer used](https://github.com/rome/tools/actions/runs/3493437886/jobs/5848268487).

2022-11-18 08:09 UTC, MichaReiser approved these changes
Awesome work! Nice to see how you managed to shorten the implementation by 100 lines of code!

2022-11-18 08:22 UTC, MichaReiser commented
And there are [now errors that Rome detects in the playground](https://github.com/rome/tools/actions/runs/3493437888/jobs/5848268626) because of your fixes :D Awesome job

2022-11-18 14:10 UTC, merged