feat(rome_cli): cli exit as error when no files are found
rome/tools pull request #3722
Opened 2022-11-14 11:30 UTC by xunilrj

## Summary

Closes https://github.com/rome/tools/issues/3645

This PR makes the cli exit as error if no files are found.

## Test Plan

```
> cd c:\Python310
> rome check .
Checked 0 files in 79ms
Error: no supported files were found in the specified folders.
> $LASTEXITCODE
1
```

2022-11-14 15:55 UTC, ematipico requested changes
Could you please add a new test case so we can snapshot the error message?

2022-11-14 15:55 UTC, ematipico commented on crates/rome_cli/src/termination.rs
> +    ZeroSupportedFilesFound,
nit: `NoSupportedFilesFound` ?

2022-11-15 22:09 UTC, ematipico approved these changes

2022-11-16 07:57 UTC, MichaReiser commented on crates/rome_cli/Cargo.toml
> +mktemp = "0.5.0"
What is the `mktemp` dependency used for?

2022-11-16 07:57 UTC, MichaReiser commented on crates/rome_cli/tests/snapshots/main_commands_check/no_supported_file_found.snap
> +no supported files were found in the specified folders.
Nit: 
```suggestion
no supported files were found in the specified paths.
```

2022-11-17 11:35 UTC, xunilrj commented on crates/rome_cli/src/termination.rs
> +    ZeroSupportedFilesFound,
Done. Actually went with `NoFilesWereProcessed`.

2022-11-17 11:54 UTC, xunilrj commented
@leops I changed the semantic of the processed variable. Are you ok with this change?

2022-11-17 11:54 UTC, xunilrj commented
> Could you please add a new test case so we can snapshot the error message?

Done.

2022-11-17 11:55 UTC, xunilrj commented on crates/rome_cli/Cargo.toml
> +mktemp = "0.5.0"
Removed.

2022-11-17 11:56 UTC, xunilrj commented on crates/rome_cli/tests/snapshots/main_commands_check/no_supported_file_found.snap
> +no supported files were found in the specified folders.
Done.

2022-11-17 17:36 UTC, ematipico approved these changes

2022-11-17 18:21 UTC, merged