feat(rome_js_analyze): noVar
rome/tools pull request #3765
Opened 2022-11-16 15:31 UTC by Conaclos

## Summary

Implement eslint's [no-var](https://eslint.org/docs/latest/rules/no-var).

## Test Plan

Test included.

2022-11-16 15:56 UTC, MichaReiser reviewed
Thanks for this contribution.

2022-11-16 15:56 UTC, MichaReiser commented on crates/rome_js_analyze/tests/specs/nursery/noVar.js
> +
Can you add a test for a case that uses restructuring:

```
var { a, b} = {};
```

2022-11-16 15:56 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_var.rs
> +            message: markup! { "Replace with "<Emphasis>"let"</Emphasis> }.to_owned(),
We have another rule that promotes `const` over `let`. Should we use the semantic model to figure out whether to use `let` or `const` (no writes)?

2022-11-16 18:05 UTC, Conaclos commented on crates/rome_js_analyze/tests/specs/nursery/noVar.js
> +
Sure.

2022-11-16 18:16 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_var.rs
> +            message: markup! { "Replace with "<Emphasis>"let"</Emphasis> }.to_owned(),
My reasoning was that this is covered by another rule and could be fixed in a second linting pass. This allows to keep the fix simple. Moreover, *var* is function-scoped, thus the fix is not safe (this explains why I chose *MaybeIncorrect* applicability).

2022-11-16 22:32 UTC, jeysal commented on crates/rome_js_analyze/src/analyzers/nursery/no_var.rs
> +            message: markup! { "Replace with "<Emphasis>"let"</Emphasis> }.to_owned(),
I think unless we automatically perform additional passes, the user experience would be quite clunky ("It's red again??"). But automatically performing more passes seems like a slower implementation than finding the right fixes straight away.
I think ideally we would extract high level utils as we get more and more lint rules that need to figure out the same thing (e.g. should this binding be a let or a const), and then at some point you have such a large collection of them that you're writing new lint rules mostly in calls to those abstractions. This should also keep the fixes simple but at the same time enable building the ideal fixes.
The semantic model is such a util/abstraction, so Micha's suggestion also sounds like the right way to me 👍

2022-11-17 17:23 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_var.rs
> +            message: markup! { "Replace with "<Emphasis>"let"</Emphasis> }.to_owned(),
That's makes sense. Rome should certainly emit valid code. I've made the change by reusing the code of `useConst`.

2022-11-20 17:33 UTC, jeysal approved these changes
Nice and clean

2022-11-20 17:33 UTC, jeysal commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_var.rs
> +                "Do not use "<Emphasis>"var"</Emphasis>"."
I think we could give a little more context here for JS beginners who might not know that and why let and const are used instead these days.

Something like
```
Do not use var. var makes it easy to access an uninitialized variable, among other issues. Use let or const instead.
```

(side note I know use let or const is already mentioned in the suggested action, but I think doesn't hurt to mention here so the user sees it e.g. in the editor on hover without the action menu)

2022-11-20 17:33 UTC, jeysal commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_var.rs
> +                "Do not use "<Emphasis>"var"</Emphasis>"."
We could perhaps even link a further explanation? Other tools like `rustc` or even libraries like `react` tend to do this in their messages.

cc @MichaReiser @ematipico idk if this is the direction we want to take things, it does seem consistent with the philosophy though

Quick search finds resources like this https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f

2022-11-20 17:40 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_var.rs
> +                "Do not use "<Emphasis>"var"</Emphasis>"."
Hi @jeysal, I am open to change it. However, if we add more details in the title, then others rules should certainly add also details. By the way, I noticed that it is possible to add details with `description`.

2022-11-20 17:42 UTC, jeysal commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_var.rs
> +                "Do not use "<Emphasis>"var"</Emphasis>"."
Yes, I think I used `.note` for some extended explanation. We can wait and see what others think the messaging should be like

2022-11-21 08:39 UTC, leops commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_var.rs
> +                "Do not use "<Emphasis>"var"</Emphasis>"."
Yes in general linter diagnostics shouldn't just state that a certain pattern is wrong, but also include an explanation of why this is wrong. This can be implemented using both the `.note` and `.description` APIs, as those have slightly different effect on presentation: the `note` and `warning` methods append a new "advice" to the diagnostic to be displayed on the CLI, while `description` changes the plain-text description of the issue that's displayed in the editor.
For more information about this you can read the diagnostics documentation for contributors here: https://github.com/rome/tools/blob/main/crates/rome_diagnostics/CONTRIBUTING.md

2022-11-21 12:11 UTC, ematipico requested changes
Would you mind adding some test cases that contain comments around the tokens that are replaced?

2022-11-21 12:11 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_var.rs
> +    /// Source: https://eslint.org/docs/latest/rules/no-var
Maybe we can move this text before the header `Examples`. The paragraph doesn't seem to be related to the examples.

2022-11-21 12:11 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_var.rs
> +                "Do not use "<Emphasis>"var"</Emphasis>"."
@Conaneed if you need to add more information to the CLI, you can use the `.note()` API and add whatever you want, even links: https://github.com/rome/tools/blob/main/crates/rome_js_analyze/src/semantic_analyzers/correctness/no_array_index_key.rs#L188-L192

Use `.description` in case you want to give a  different message to the editors. Editors don't support reach diagnostics. So if your original diagnostic is broken down into different parts, you could provide a better message only for editors.

2022-11-21 15:56 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_var.rs
> +                "Do not use "<Emphasis>"var"</Emphasis>"."
fixed

2022-11-21 15:57 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_var.rs
> +    /// Source: https://eslint.org/docs/latest/rules/no-var
fixed

2022-11-22 10:14 UTC, ematipico approved these changes

2022-11-22 12:22 UTC, Conaclos commented
I rebased the branch. It is ready for merge :)

2022-11-22 13:35 UTC, Conaclos commented
> CI still failing... probably need to run `cargo codegen-configuration`

Fixed.

2022-11-22 13:36 UTC, merged