WIP docs: repo integration guide
rome/tools pull request #3767
Opened 2022-11-16 17:38 UTC by jeysal

Resolves #3708

Took a little more time today to almost finish this, just gotta write a little bit about package manager workspaces/lerna.

I'm trying to make the guide very approachable with little knowledge about any tooling configuration whatsoever. I give copy paste replacements that work if you have done the basic setup recommended by Prettier/ESLint/Turborepo/... and would like to replace a tool with Rome. Of course this cannot cover complex setups and configuration in detail, but if users have done that, they probably have some experience with tooling and can figure out those remaining modifications afterwards.

At the same time, I try to nudge users to do things in a future-proof way. E.g. `ignore` instead of include patterns so that users will automatically benefit when we become capable of formatting additional file types. And using Rome directly in the root if possible because we'll have features for multi-package repos in the future.

2022-11-16 17:41 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++    "lint": "rome check ."
If we've shipped it in time, we should recommend `--force-colors` here. Otherwise the output looks shite calling through turbo lint in the root

2022-11-16 17:46 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++  "lint": "rome check --apply .",
This lint command is unfortunately not equivalent right now. If rome finds an error that has a suggested fix, it will print "skipped 1 suggested fix" and not highlight the problem and exit with 0. This seems unintuitive to me, does anyone know if this is intended or discussed in some issue?

2022-11-17 17:55 UTC, ematipico commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++    "lint": "rome check ."
That will be part of the next release :) https://github.com/rome/tools/pull/3625

2022-11-17 17:58 UTC, ematipico commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++  "lint": "rome check --apply .",
I think it's intentional. `rome check` is supposed to be command to make sure the code is correct. `--apply` and `--apply-suggested` are _volountary_ commands where the user decides to fix the code and **how** to fix it. It seems a bit redundant to show them diagnostics.

2022-11-17 18:02 UTC, SuperchupuDev commented on website/src/pages/guides/integrating-into-your-repository.mdx
> +If you have a CI pipeline, such as GitHub actions, we recommend that you check formatting and linting as part of it by adding the following command:
```suggestion
If you have a CI pipeline, such as GitHub Actions, we recommend that you check formatting and linting as part of it by adding the following command:
```

2022-11-20 17:59 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++    "lint": "rome check ."
Yup I saw, just not sure if that'll be out soon enough before this is merged

2022-11-20 18:02 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++  "lint": "rome check --apply .",
Okay. That still seems unintuitive to me to be honest, as flags usually only alter/augment the behavior of a command and this seems to be more like a completely different command (`rome apply`).
I think in this guide I can still leave it as a recommendation despite the different behavior, since I'm not recommending anyone to use this command for CI or anything dangerous like that.

2022-11-20 19:40 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> +		"ignore": ["build", "**/*.generated.js"]
This and similar code examples should likewise also be adapted when we ship `files.ignore`, again not sure if release will be before this doc merge

2022-11-20 20:17 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> +Do not quote a pattern like `**/*.ts`. Most modern package managers are able to handle it correctly on all platforms.
IIRC there's an issue to implement glob patterns in Rome. I think it would be useful to do that to reduce reliance on package managers here. Recommending to run through package manager scripts is generally a bit of an eyesore to me, because it's so much slower. It would be nice to have a better way that we can confidently recommend to people. In the meantime, any further dependency  on package managers such as for globbing would be good to avoid for future-proofing

2022-11-20 20:31 UTC, jeysal commented
Alright, happy with this first version. If we notice a significant amount of people struggling with a particular part, we can make optimizations / further expand there.

2022-11-21 10:40 UTC, ematipico commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++  "lint": "rome check --apply .",
It makes sense, thank you for the suggestion.

FYI we plan to remove `--apply-suggested` in the next months. This command was created as a quick workaround to allow users to apply also suggested fixes, but the correct way to do so would be to use a `rome check --review` argument that enables an interactive review where users can decide to:
- apply the suggested fix
- or suppress the rule

2022-11-21 10:46 UTC, ematipico requested changes

2022-11-21 10:46 UTC, ematipico commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++    "ci:format": "rome format .",
I don't think this is the correct transition, `rome format` doesn't return an error code here, while prettier does. The correct way to us to suggest the transition for CI environments should be:

```shell
rome ci --linter-enabled=false .
```

2022-11-21 10:46 UTC, ematipico commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++    "ci:format": "rome format **/*.ts",
Same here, `rome ci` command should be suggested

2022-11-21 10:46 UTC, ematipico commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++  "ci:lint": "rome check .",
`rome ci` should be suggested:

```shell
rome ci --formatter-enabled=false .
```

2022-11-22 16:28 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++    "ci:format": "rome format .",
Ohh that's true, I never looked at the exit code, only assumed it would exit 1 if it prints the formatter diff. I will change this for the guide.
Are you aware of discussion threads or so on the CLI design? There have been a few design decisions now that struck me as odd compared to existing JS tools and also other CLI tools, would be good to get more context or to get involved if there are still active discussions about potential changes

2022-11-22 16:29 UTC, jeysal commented
@sebmck @MichaReiser feel free to also leave a review on whether this is coherent and the suggestions made to users are good :sweat_smile:

2022-11-22 17:13 UTC, ematipico commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++    "ci:format": "rome format .",
There have been some issue around the unclearness/oddity of how error codes are returned from our commands. 
- https://github.com/rome/tools/issues/3168
- https://github.com/rome/tools/issues/3443

There haven't been talks between the staff team about using error codes in a better way (a la' prettier), and we do want to use this [Rust primitive](https://doc.rust-lang.org/std/process/struct.ExitCode.html), but we haven't had the time to look into it.

2022-11-22 17:15 UTC, ematipico commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++    "ci:format": "rome format .",
Feel free to start a github discussion if you have suggestions

2022-11-23 20:35 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++  "ci:lint": "rome check .",
For check, the exit code behavior appears to already be as expected (1 if any errors found, 0 otherwise)

2022-11-23 20:36 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++    "ci:format": "rome format .",
I commented on #3443 to keep it in one place. I think there's a good way forward.

2022-11-23 20:48 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++  "lint": "rome check --apply .",
https://github.com/rome/tools/discussions/3837

2022-11-23 20:50 UTC, jeysal commented
Probably best to wait with merging this until we have resolved the awkwardness of not having good replacements for `prettier --check` and `eslint --fix` (see review comment threads), and also would be nice to have things like `files.ignore` and `--force-colors` released already.
Then all the recommendations we give people for their setup will actually be solid.

2022-11-24 11:52 UTC, jeysal commented on website/src/pages/guides/integrating-into-your-repository.mdx
> ++    "ci:format": "rome format .",
Path forward for this and the other instances of it that I have in mind: We recommend an example like
```
"format": "rome format --write .",
"check:format": "rome format --check .",
"lint": "rome check --fix .",
"check:lint": "rome check ."
```
but add a CI section like at the start of the guide to clarify that CI should run not these but `rome ci` (if necessary with parts of Rome disabled via `rome.json`)

2022-12-03 01:05 UTC, elijaholmos commented on website/src/pages/guides/integrating-into-your-repository.mdx
> +If you have a CI pipeline, such as GitHub Actions, we recommend that you check formatting and linting as part of it by adding the following command:
I think it would be practical to include a guide on (or at the very least, a reference to) the Rome GitHub action & how it can be setup in a GitHub repository.

2023-03-29 13:34 UTC, closed without merging