feat(rome_js_parser): Improve parser error for generator function in an ambient context
rome/tools pull request #3778
Opened 2022-11-17 17:12 UTC by denbezrukov

## Summary

Add `Generators are not allowed in an ambient context.` error for generator functions in an ambient context.

[Typescript playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEBbA9sArhBByAHl+A3gFDzwg4AOyMALvKAGZQZ0NoB2YNAlsuwFTwaIAM40AFMgo8+ALnhR2ATwCU8gG7JuwIgF8i5KrXrhoceG04yBQ0RLXxN2gNxA)

For function overloading Rome has an error:
https://github.com/rome/tools/blob/4084d3e18e5d38b006e0dc99b3ce5975f9e01bf2/crates/rome_js_parser/src/syntax/function.rs#L280-L285

## Test Plan

`cargo test`

2022-11-17 17:53 UTC, ematipico approved these changes

2022-11-17 18:06 UTC, denbezrukov commented on crates/rome_js_parser/test_data/inline/err/ts_function_overload_generator.rast
> +        TsDeclareFunctionDeclaration {
Is this likely to be an expected change?

2022-11-17 20:39 UTC, denbezrukov commented on crates/rome_js_parser/test_data/inline/err/ts_declare_generator_function.rast
> +    1: TS_DECLARE_STATEMENT@31..94
Should be here also `JS_UNKNOWN_STATEMENT`?

2022-11-18 08:20 UTC, MichaReiser requested changes
The code changes look good but we should remove the `*` from the definitions in the ungram file.

2022-11-18 08:20 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	'*'?
We shouldn't add the `*` token if it isn't allowed in this context. The AST should only define valid children. The syntax factory will take care to automatically convert your node into an `UnknownNode` if it has any unexpected children. 

We could use skipped token trivia if we want to parse out a valid tree regardless of the incorrectly placed generator token.

2022-11-18 08:20 UTC, MichaReiser commented on crates/rome_js_parser/test_data/inline/err/ts_function_overload_generator.rast
> +        TsDeclareFunctionDeclaration {
It should be an `UNKNOWN_STATEMENT` as a `TsDeclareFunctionDeclaration` isn't supposed to have a `*` child. The syntax factory will take care of that if you remove the `*` token from the `TsDeclareFunctionDeclaration` definition in the `js.ungram`.

2022-11-18 08:20 UTC, MichaReiser commented on crates/rome_js_parser/test_data/inline/err/ts_declare_generator_function.rast
> +    1: TS_DECLARE_STATEMENT@31..94
Yes, see my other two comments (sorry, I started reviewing bottom up, or rather started reviewing the ungram file first)

2022-11-18 08:45 UTC, denbezrukov commented on crates/rome_js_parser/test_data/inline/err/ts_function_overload_generator.rast
> +        TsDeclareFunctionDeclaration {
fixed

2022-11-18 08:45 UTC, denbezrukov commented on crates/rome_js_parser/test_data/inline/err/ts_declare_generator_function.rast
> +    1: TS_DECLARE_STATEMENT@31..94
fixed

2022-11-18 08:46 UTC, denbezrukov commented on xtask/codegen/js.ungram
> +	'*'?
fixed

2022-11-18 08:50 UTC, MichaReiser approved these changes

2022-11-18 09:56 UTC, merged