feat(rome_js_analyze): noSetterReturn
rome/tools pull request #3783
Opened 2022-11-17 21:34 UTC by Conaclos

## Summary

This implements Deno Lint [noSetterReturn](https://lint.deno.land/?q=&all=on#no-setter-return).

## Test Plan

Unit tests included.

2022-11-18 08:13 UTC, MichaReiser approved these changes

2022-11-18 17:59 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_setter_return.rs
> +    type Query = Ast<JsSetterMember>;
Have you examples? If I understand well I can access ancestors via `node.syntax().ancestors()` and it should exists some method to attempt a conversion?

2022-11-19 10:54 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_setter_return.rs
> +    type Query = Ast<JsSetterMember>;
Thanks for the suggestion. The code is simpler in that way:)

2022-11-21 09:16 UTC, leops approved these changes

2022-11-21 09:16 UTC, leops commented on crates/rome_js_analyze/src/control_flow/visitor.rs
> +    pub JsAnyControlFlowRoot = JsModule
Nit: this could be `pub(crate)` rather than `pub`

2022-11-21 11:17 UTC, ematipico requested changes

2022-11-21 13:33 UTC, ematipico approved these changes

2022-11-22 22:20 UTC, Conaclos commented
@ematipico I rebased this branch on [noConstructorReturn](https://github.com/rome/tools/pull/3805). This should allow merging `noSetterReturn` this feature just after [noConstructorReturn](https://github.com/rome/tools/pull/3805).

2022-11-23 07:25 UTC, merged