refactor(rome_analyze): align the syntax of lint suppression with the corresponding diagnostic category
rome/tools pull request #3788
Opened 2022-11-18 11:18 UTC by leops

## Summary

Fixes #3446

This PR changes the syntax of lint suppression comments from `rome-ignore lint(group/rule)` to `rome-ignore lint/group/rule` to align with how lint categories are presented in diagnostics. I've tried to keep backwards compatibility by continuing to parse the previous syntax, and emitting a diagnostic with a safe fix when such a comment is encountered by the linter.

## Test Plan

I've extended the suppression comment tests in `rome_js_analyze` to check that both the new and old syntax remain supported, and that a diagnostic is correctly emitted for the deprecated syntax. Additionally I've also used a local build of the language server to apply the automatic fix to all the files with suppression comments that we have.

2022-11-18 13:51 UTC, ematipico requested changes
Could you please add a new snapshot test in the CLI that shows the new diagnostic emitted for old suppression comments?

2022-11-18 13:51 UTC, ematipico commented on crates/rome_analyze/src/lib.rs
> +            });
Here this diagnostics could have the tag `DiagnosticTags::DEPRECATED_CODE`. It doesn't make much sense to keep two different comment styles and should stick with one.

2022-11-18 13:51 UTC, ematipico commented on crates/rome_analyze/src/signals.rs
>  /// provided factory function
Can you update the documentation? It seems that this type does more things than before

2022-11-18 13:51 UTC, ematipico commented on crates/rome_analyze/src/diagnostics.rs
> +                DiagnosticKind::Raw(error.with_tags(DiagnosticTags::FIXABLE))
Are the final tags joined together with this function? Because diagnostics emitted for old suppression comments should deprecated and fixable.

2022-11-18 15:37 UTC, leops commented on crates/rome_analyze/src/lib.rs
> +            });
This is something I considered doing but I ended up not going with it as it made the editor highlight the suppression comment with the deprecated strike-through styling, this made it seem like the comment itself was deprecated which I thought could be confusing to some users.
![suppression_deprecated](https://user-images.githubusercontent.com/1895119/202742617-f7978fc3-99fe-4dd3-8ced-c312954bf1ec.png)

2022-11-18 15:38 UTC, leops commented on crates/rome_analyze/src/diagnostics.rs
> +                DiagnosticKind::Raw(error.with_tags(DiagnosticTags::FIXABLE))
Yes I've implemented the `.with_tags` combinator to return a new diagnostic that has both the tags of the inner diagnostics in addition to the ones passed in to the function

2022-11-18 16:23 UTC, ematipico approved these changes
Not a blocker, but I still think that these diagnostics should be tagged as deprecations.

Also, can these warnings block `rome ci`? If yes, we should demote them to simple info diagnostics. Otherwise, I think we can merge it!

2022-11-21 13:58 UTC, leops commented
> Also, can these warnings block `rome ci`? If yes, we should demote them to simple info diagnostics. Otherwise, I think we can merge it!

Warnings should not cause `rome ci` to fail, only error-level diagnostics will make the CLI return with a non-zero error code

2022-11-21 14:16 UTC, merged