feat(rome_js_analyze): useDefaultCaseLast
rome/tools pull request #3791
Opened 2022-11-18 17:44 UTC by Conaclos

## Summary

This implements ESLint's [default-case-last](https://eslint.org/docs/latest/rules/default-case-last).

## Test Plan

Unit test included.

2022-11-21 07:44 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_default_case_last.rs
> +    type Query = Ast<JsSwitchCaseList>;
It may be cheaper to only run the rule on the `JsDefaultClause` and use `clause.syntax().next_sibling()` to see if there is a case statement following.

2022-11-21 07:45 UTC, MichaReiser commented on crates/rome_js_analyze/tests/specs/nursery/useDefaultCaseLast/invalid.js.snap
> +
I thin it would be good to highlight the case statement following after the `default`

2022-11-21 11:33 UTC, ematipico requested changes
I think we can also provide a code action that moves the `default` statement to the last position. We can add the code action in another PR.

2022-11-21 11:33 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_default_case_last.rs
> +    type State = JsAnySwitchClause;
The state could be a `TextRange`

2022-11-21 11:33 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_default_case_last.rs
> +            default_clause.range(),
You need to use `text_trimmed_range` instead.

2022-11-21 11:33 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_default_case_last.rs
> +        let _case_after_default = it.next()?;
Better to use `.is_some`, otherwise we need to add a comment explaining why `_case_after_default` is not read.

2022-11-21 11:48 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_default_case_last.rs
> +            default_clause.range(),
The `AstNode.range` method calls `text_trimmed_range`. We should probably rename these methods at some point.

2022-11-22 22:40 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/use_default_case_last.rs
> +    type State = JsAnySwitchClause;
Is there advantages to use TextRange instead of JsAnySwitchClause?

2022-11-22 22:49 UTC, Conaclos commented
@ematipico 
> I think we can also provide a code action that moves the `default` statement to the last position. We can add the code action in another PR.

The difficulty is when a fallthrough is present. Like in the following code:

```js
switch (foo) {
  default:
    doSomethingIfNotZero();
  case 0:
    doSomethingAnyway();
}
```

This requires some logic to know whether the block return/break. Have you an idea how to implement this without exploring all descendants? Or we could just handle the case where a block statement ends with `return` or `break`. This looks fair.

In fact I - in constrast to ESLint - we could allow code with default clause that fallthrough (as the previous code). Another rule (noFallthrough) could reject this code. This could make useDefaultCaseLast less restrictive.

Also, I wonder if we should rename the rule "useDefaultCaseLast" to "useDefaultClauseLast" or "useDefaultSwitchClauseLast".

2022-11-23 07:05 UTC, MichaReiser commented
!bench_analyzer

2022-11-23 07:06 UTC, MichaReiser approved these changes

2022-11-23 07:07 UTC, ematipico approved these changes

2022-11-23 07:07 UTC, MichaReiser commented
> Also, I wonder if we should rename the rule "useDefaultCaseLast" to "useDefaultClauseLast" or "useDefaultSwitchClauseLast".

I'm in favor of renaming `Case` to `Clause` as this aligns with the terminology used in the diagnostics and `useDefaultSwitchClauseLast` goes well with our philosophy;

> Utilize verbosity when naming commands and flags. No unnecessary and confusing abbreviations.

2022-11-23 11:19 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_default_case_last.rs
> +    type State = JsAnySwitchClause;
Not particularly, simply less information to carry around :)

2022-11-23 11:22 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/nursery/use_default_case_last.rs
> +    type State = JsAnySwitchClause;
It is expensive to calculate range in some cases. Specially when you use the trimmed version that needs to skip trivia.

2022-11-23 11:35 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/use_default_case_last.rs
> +    type State = JsAnySwitchClause;
> It is expensive to calculate range in some cases. Specially when you use the trimmed version that needs to skip trivia.

Computing the range in `run` or in \diagnostic` has the same cost?

2022-11-23 21:51 UTC, Conaclos commented
@ematipico @MichaReiser 
Ready for merging.

I will open a new PR for the code action. This allows discussing about that in details.

Unfortunately, a commit in `main` causes a failure on the format check. Indeed, ` /home/runner/work/tools/tools/crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs` was not formatted with rustfmt.

2022-11-24 04:44 UTC, lucasweng commented
> Unfortunately, a commit in `main` causes a failure on the format check. Indeed, ` ./crates/rome_js_analyze/src/semantic_analyzers/nursery/use_exhaustive_dependencies.rs` was not formatted with _rustfmt_.

Fixed in https://github.com/rome/tools/pull/3840

2022-11-24 06:50 UTC, merged