feat(rome_js_analyze): add noHeaderScope rule
rome/tools pull request #3804
Opened 2022-11-20 17:27 UTC by kaioduarte

## Summary
Part of https://github.com/rome/tools/issues/3739

## Test Plan

Unit tests

2022-11-20 17:30 UTC, kaioduarte commented on crates/rome_js_analyze/src/analyzers/nursery/no_header_scope.rs
> +        mutation.remove_node(jsx_attr.clone());
This simple approach can leave some whitespaces in the JSX element, and I saw that we kinda handle it on the noAutoFocus rule, but I wonder if it's worth the effort here as the formatter can take care of it.

2022-11-21 09:14 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/no_header_scope.rs
> +        mutation.remove_node(jsx_attr.clone());
Since users may opt-out of using the formatter and only enable the linter we try to ensure that code actions don't do something completely wrong with trivia like removing all whitespace, but it doesn't have to handle every edge case perfectly either.

2022-11-21 09:14 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/no_header_scope.rs
> +    type Query = Ast<JsxAnyElement>;
It should be more efficient to match on `JsxAttribute`, check if its name is `scope`, then lookup the parent node to check the element isn't `th`

2022-11-21 11:54 UTC, ematipico requested changes

2022-11-21 11:54 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_header_scope.rs
> +    /// Enforce scope prop is only used on `th` elements.
```suggestion
    /// Check that the scope attribute is only used on `th` elements.
```

The old documentation was poorly worded... 😓

2022-11-21 11:54 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_header_scope.rs
> +                if jsx_name.text() != "th" {
You need to use `jsx_name.syntax().text_trimmed()` instead. The API `text()` allocates a new string, which is not what want here.

2022-11-21 11:54 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_header_scope.rs
> +                if jsx_name.text() != "th" {
You need to use `jsx_name.syntax().text_trimmed()` instead. The API `text()` allocates a new string, which is not what want here.

2022-11-21 14:14 UTC, leops approved these changes

2022-11-21 14:45 UTC, ematipico approved these changes

2022-11-21 14:45 UTC, merged