feat(rome_js_analyze): `noVoidTypeReturn`
rome/tools pull request #3806
Opened 2022-11-20 18:41 UTC by Conaclos

## Summary

This is an exclusive rule for Rome!
This disallows returning a value when the return-type of a function is `void`.

## Test Plan

Unit tests and doc-tests included

2022-11-21 07:24 UTC, MichaReiser reviewed
I see how this rule can be useful in catching bugs, but it may be controversial because using `return iReturnVoid()` can be useful. 

But I think we can add it as a nursery rule and see if users find it useful. 

I recommend adding support for the `void` operator that explicitly returns void. 


```js
function f(): void {
	return void 0;
}
```

2022-11-21 07:24 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_void_type_return.rs
> +    /// Only return without a value is allowed, as it’s a control flow statement.
```suggestion
    /// Disallow returning a value from a function with the return type 'void'
    ///
    /// 'void' signals the absence of value. The returned value is likely to be ignored by the caller.
    /// Thus, returning a value when the return type of function is 'void', is undoubtedly an error.
    ///
    /// Only returning without a value is allowed, as it’s a control flow statement.
```

2022-11-21 07:24 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_void_type_return.rs
> +}
You also want to handle getter and setter methods.

2022-11-21 07:24 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_void_type_return.rs
> +    }
Can we add a code frame to the diagnostic pointing to the function with the `void` return type?

2022-11-21 11:02 UTC, ematipico requested changes

2022-11-21 11:02 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_void_type_return.rs
> +        let _arg = ret.argument()?;
We should add `void 0` in consideration, as Micha suggested.

2022-11-21 13:31 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_void_type_return.rs
> +            .and_then(JsFunctionMethod::cast)?;
Using `JsFunctionMethod` and ancestor risks "bleeding" (overall, using `ancestors` and `descendants` should be used with extreme caution when navigating). 

```
function test() {
class Test {
  constructor() {
 		/// it will go past the constructor if you start from here and only stop at the function test which is not what we want.   
  }
}
```

2022-11-21 18:32 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_void_type_return.rs
> +    /// Only return without a value is allowed, as it’s a control flow statement.
I think we should not support `return void`. ESLint does not support this for [no-setter-return](https://eslint.org/docs/latest/rules/no-setter-return) and [no-constructor-return](https://eslint.org/docs/latest/rules/no-constructor-return). No one seems to complain about this restriction.

Moreover, in an expression, `void x` is considered as equivalent to `undefined`.

I could keep the restriction in place and see if users complain. Returning `void x` seems unfamiliar. The only interest is maybe for minifier? Do you have something in mind in terms of usage?

2022-11-21 21:43 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_void_type_return.rs
> +}
setters cannot be handled because they cannot be annotated with a return type. I added getters. I noted that getters have a different interface for the return type. Is this intentional?

2022-11-21 22:06 UTC, ematipico approved these changes

2022-11-22 07:09 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_void_type_return.rs
> +}
That's fair, but doesn't that mean that a return with a non-void argument in a setter is always an error?

>  I noted that getters have a different interface for the return type. Is this intentional?

The reason is that getters are more limited regarding the return type annotation.

2022-11-22 16:31 UTC, jeysal commented
> I see how this rule can be useful in catching bugs, but it may be controversial because using `return iReturnVoid()` can be useful.

I always find it a bit confusing in unfamiliar codebases if I don't know the function already. I'll check the tooltip of the function to see if it returns something despite having a name that sounds a lot like it returns void.

From the existing rules in Rome core and even in the recommended set I'd say there are more opinionated rules than that already. Plus style will at least be consistent across a large codebase and not sometimes `return voidFn()` and sometimes `voidFn(); return`.

So all in all would argue that's a good thing to forbid by default.

2022-11-22 17:39 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_void_type_return.rs
> +}
> That's fair, but doesn't that mean that a return with a non-void argument in a setter is always an error?

I suppose. This is why we have [noSetterReturn](https://github.com/rome/tools/pull/3783). Do you suggest to add the check of `noSetterReturn`, and certainly `noCOntrsutorReturn`, in this rule? I first hesitated. However, I think it is better to keep distinct rules : this one relies on type annotation, while the others rely on constructor identifier/set keyword.

> The reason is that getters are more limited regarding the return type annotation.

That's makes sense. However it is often simpler to handle types with uniform interfaces. I could open a discussion about that?

2022-11-22 17:51 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_void_type_return.rs
> +    /// Only return without a value is allowed, as it’s a control flow statement.
I opened #3827.

2022-11-23 11:33 UTC, Conaclos commented
@MichaReiser @ematipico 
Ready for merging :)

2022-11-23 18:07 UTC, merged