feat(rome_js_analyze): better JS suppressions
rome/tools pull request #3855
Opened 2022-11-25 13:18 UTC by ematipico

## Summary

## Test Plan

2022-11-28 17:19 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +            || current_token.text_trimmed().contains('\n')
This won't work on systems with `\r` line breaks.

2022-11-28 17:23 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +            }
Is it necessary to also test for templates here as they can contain new lines too?

2022-11-28 17:25 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +        match find_fist_token_with_newline(original_token.clone()) {
first?
```suggestion
        match find_first_token_with_newline(original_token.clone()) {
```

2022-11-28 17:25 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +                    first_token_with_newline.with_leading_trivia([
Does this replace any existing trivia on the token?

2022-11-29 11:00 UTC, ematipico commented on crates/rome_js_analyze/src/suppression_action.rs
> +                    first_token_with_newline.with_leading_trivia([
That's fixed and added a test case with existing comments.

2022-11-29 11:01 UTC, ematipico commented on crates/rome_js_analyze/src/suppression_action.rs
> +            }
I added a specific branch just for template literals, their logic is different. A test case has been added.

2022-11-29 11:02 UTC, ematipico commented on crates/rome_js_analyze/src/suppression_action.rs
> +            || current_token.text_trimmed().contains('\n')
I added a new check

2022-11-29 11:05 UTC, ematipico commented on crates/rome_js_analyze/tests/spec_tests.rs
> +                if check_action_type.is_suppression() {
Doing so will add the suggested actions to the snapshot of the suppressions, which is not what I wanted to avoid

2022-11-29 11:10 UTC, ematipico commented on crates/rome_js_analyze/src/suppression_action.rs
> +        } else if let Some(parent_token) = current_token
Very true! I removed the branch

2022-11-29 13:49 UTC, leops commented on crates/rome_js_analyze/tests/spec_tests.rs
> +                if check_action_type.is_suppression() {
Sorry I messed up factorizing the logic expression, I think it's actually `!(check_action_type.is_suppression() ^ action.is_suppression())`

2022-11-30 09:46 UTC, MichaReiser requested changes

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_rowan/src/syntax_rewriter.rs
> +/// assert_eq!(new_token, "LET_TOKEN@0..10 \"let\" [Whitespace(\"\\n\\t \"), Whitespace(\";\")] [Whitespace(\" \\t\\t\")]")
Using `unwrap` in dotests is discouraged because readers may end up copying the code including the `unwrap` calls. That's why it is recommended to wrap the test in a `main` function and hide these lines by prefixing them with `#`.

```suggestion
/// # use rome_rowan::raw_language::{RawLanguageKind, RawSyntaxTreeBuilder};
/// # use rome_rowan::{chain_pieces, TriviaPiece, TriviaPieceKind, SyntaxResult};
/// 
/// # fn main() -> SyntaxResult<()> {
/// let mut builder = RawSyntaxTreeBuilder::new();
///
/// let mut node = RawSyntaxTreeBuilder::wrap_with_node(RawLanguageKind::ROOT, |builder| {
///     builder.token_with_trivia(
///         RawLanguageKind::LET_TOKEN,
///         "\n\t let \t\t",
///         &[TriviaPiece::whitespace(3)],
///         &[TriviaPiece::whitespace(3)],
///     );
///     builder.token(RawLanguageKind::STRING_TOKEN, "a");
///     builder.token_with_trivia(
///         RawLanguageKind::SEMICOLON_TOKEN,
///         "; \t\t",
///         &[TriviaPiece::whitespace(1)],
///         &[TriviaPiece::whitespace(1)],
///     );
/// });
/// let mut tokens = node.tokens();
/// let first_token = tokens.next()?;
/// let second_token = tokens.next()?;
/// let third_token = tokens.next()?;
///
/// let leading_trivia = chain_pieces(
///     first_token.leading_trivia().pieces(),
///     third_token.leading_trivia().pieces()
/// );
///
/// let new_first_token = first_token.with_leading_trivia_pieces(leading_trivia);
///
/// let new_token = format!("{:?}", new_first_token);
/// assert_eq!(new_token, "LET_TOKEN@0..10 \"let\" [Whitespace(\"\\n\\t \"), Whitespace(\";\")] [Whitespace(\" \\t\\t\")]")
/// # Ok(())
/// # }
```

2022-11-30 09:46 UTC, MichaReiser commented on .cargo/config.toml
> +lint = "clippy --workspace --all-targets --verbose -- --deny warnings -W clippy::cargo -W clippy::dbg_macro -A clippy::cargo_common_metadata"
Nit: Unrelated to this PR

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/batch.rs
> +        new_element: &[AnyJsxChild],
Nit: `new_elements`

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/batch.rs
> +                        new_items.extend(new_element.to_vec());
`extend_from_slice(new_elements)`

OR: change `new_elements` to `impl Iterator<Item=AnyJsxChild>` and call it with `items.cloned()`

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/batch.rs
> +                        new_items.extend(new_elements.to_vec());
`extend_from_slice` 

OR: change `new_elements` to `impl Iterator<Item=AnyJsxChild>` and call it with `items.cloned()`

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/lib.rs
> +                    dbg!(&new_code);
Remove?

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +/// We now try to "guess" the token where to apply the suppression comment.
Can we add some documentation what the function does (it does more than just guessing?) 

```
Adds a suppression comment.

The implementation guesses the token to which it applies the suppression comment. 
```

Using `we` in documentatation can be confusing. It's not me and you doing the guessing but the implementation/algorithm.

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +fn peek_token_from_offset(
What's the meaning of `peek` in this function. `Peek` is commonly used with iterators to look ahead without (seemingly) progressing the iterator. 

This isn't the case for this function (it even consumes `TokenAtOffset`). How about naming it `get_closest_token_for_diagnostic(...)`

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +/// it peeks the previous token and recursively call itself.
/// Finds the first token, starting with the current token and traversing backwards, that has a leading newline trivia.

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +        {
This test isn't sufficient to handle all JS new line characters:

```
* `\n`
* `\r`
* `\r\n`
```

```suggestion
current_token.text_trimmed().contains(['\n', '\r'])
```


And can you add a test for multiline strings too:

```
"a b\
  cd"
```

I recommend scoping the check for newlines inside of the text to the few token kinds that allow newlines rather than applying it everywhere. The tokens that support newlines in the middle of the text are:

* string literal
* JsxText
* TEMPLATE_CHUNK

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +                .map(|p| JsTemplateElement::can_cast(p.kind()))
Is it necessary to also handle `TsTemplateElement`?

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +            if let Some(next_token) = current_token.next_token() {
Why is this path taking the `next_token`. The documentation mentions that the algorithm traverses backwards. 

Is there this path traverses forward and the next iteration traverses backwards again, resulting in an infinite loop?

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +            && current_token
Nit: `current_token.parent().kind() == Some(JsSyntaxKind::JS_TEMPATE_ELEMENT)`

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +    }
Nit:

There are a few unnecessary `continue` calls and explicitly returning a value from the loop can improve readabilty

```suggestion
    let should_insert_leading_newline = loop {
        let trivia = current_token.leading_trivia();
        if trivia.pieces().any(|trivia| trivia.is_newline())
            || current_token.text_trimmed().contains('\n')
            || current_token.text_trimmed().contains("\r\n")
        {
            break false;
        } else if matches!(current_token.kind(), JsSyntaxKind::DOLLAR_CURLY)
            && current_token
                .parent()
                .map(|p| JsTemplateElement::can_cast(p.kind()))
                .unwrap_or_default()
        {
            if let Some(next_token) = current_token.next_token() {
                current_token = next_token;
                break false;
            } 
        } else if let Some(token) = current_token.prev_token() {
            current_token = token;
        } else {
            break true;
        }
    }

```

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +        if trivia.pieces().any(|trivia| trivia.is_newline())
You explicitly handle multiline comments at the beginning of the file. Isn't it necessary to handle multiline comments here too, e.g. to support

```
if (/ ** some weird comment
    */ a == b) {

}
```

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/tests/suppression/correctness/noUndeclaredVariables.ts.snap
> +  > 1 │ export type Invalid<S extends number> = `Hello ${T}`
Can you try a multiline template and a regular JS template

```
let a = `Output of "rome rage":
  formatter enabled: ${formatter == true}
  linter: ${linter}
`;  
```

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/tests/suppression/correctness/noArrayIndexKey.jsx.snap
> +       17 │ + ········//·rome-ignore·lint/correctness/noArrayIndexKey:·suppressed·
This is incorrect. It places the suppression comment inside of the JsxText.

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/tests/suppression/correctness/noArrayIndexKey.jsx.snap
> +    19 20 │   });
Can we add an example of a multiline jsx element

```
<div 
  className="SomeManyClasses"
  onClick={(event) => {
    console.log(event.current.target);
  }}
  style="color: red"
  aria-role="button"
>
Some content
</div>
```

2022-11-30 09:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +            mutation.replace_token_transfer_trivia(first_token_with_newline, new_token);
The `replace_token_transfer_trivia` implementation looks incorrect. Isn't it applying the trivia of the `prev_token` (leading) and `next_token` (trailing) twice 

```
        let leading_trivia: Vec<_> = prev_token
            .leading_trivia()
            .pieces()
            .chain(prev_token.leading_trivia().pieces())
            .map(|piece| TriviaPiece::new(piece.kind(), TextSize::of(piece.text())))
            .collect();

        let trailing_trivia: Vec<_> = next_token
            .trailing_trivia()
            .pieces()
            .chain(next_token.trailing_trivia().pieces())
            .map(|piece| TriviaPiece::new(piece.kind(), TextSize::of(piece.text())))
            .collect();

```

Nit: replace_token_transfer_trivia can now use `chain_trivia_pieces`

2022-11-30 09:58 UTC, MichaReiser commented
Requesting changes because:
* It seems to me that the mutation adds the suppression comment as JSX Text for one of the test cases
* `replace_token_transfer_trivia` doesn't seem to be correctly implemented. Can you add tests for testing the path where trivia is merged (normal comments, multiline comments, etc)

2022-11-30 11:02 UTC, ematipico commented on crates/rome_js_analyze/tests/spec_tests.rs
> +                if check_action_type.is_suppression() {
Same result 😅

2022-11-30 13:16 UTC, ematipico commented on crates/rome_js_analyze/src/suppression_action.rs
> +            if let Some(next_token) = current_token.next_token() {
That's because we can't place a suppression comment **before** `${`, but we are forced to place the suppression comment **inside** template expression, and thus we need to pick the next token after `${`.

Theortelly, I think this will never go into a for an infinite `next_token()` that was actually processed in the previous iteration.

2022-11-30 13:18 UTC, ematipico commented on crates/rome_js_analyze/src/suppression_action.rs
> +            && current_token
I prefer the current code, `parent` might be misleading at first glance

2022-11-30 14:26 UTC, ematipico commented on crates/rome_js_analyze/tests/suppression/correctness/noArrayIndexKey.jsx.snap
> +       17 │ + ········//·rome-ignore·lint/correctness/noArrayIndexKey:·suppressed·
The comment is placed _inside_ `div` and before the `>` that goes to a new line. The syntax is correct (otherwise the test suite would have failed). I would argue that the placement of the comment is not ideal but:
- the source code is itself an edge case
- the placement of the comment is in line with how [suppression comments work](https://docs.rome.tools/playground/?lintRules=all&code=cwBvAG0AZQB0AGgAaQBuAGcALgBmAG8AcgBFAGEAYwBoACgAKABFAGwAZQBtAGUAbgB0ACwAIABpAG4AZABlAHgAKQAgAD0APgAgAHsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAPABMAGkAcwB0AAoAIAAgACAAIAAgACAAIAAgAC8ALwAgAHIAbwBtAGUALQBpAGcAbgBvAHIAZQAgAGwAaQBuAHQALwBjAG8AcgByAGUAYwB0AG4AZQBzAHMALwBuAG8AQQByAHIAYQB5AEkAbgBkAGUAeABLAGUAeQA6ACAAcwB1AHAAcAByAGUAcwBzAGUAZAAgAAoAPgA8AGQAaQB2ACAAawBlAHkAPQB7AGkAbgBkAGUAeAB9AD4AZgBvAG8APAAvAGQAaQB2AD4ACgAgACAAIAAgADwALwBMAGkAcwB0AD4AOwAKAH0AKQA%3D)

2022-11-30 14:33 UTC, ematipico commented on crates/rome_js_analyze/src/suppression_action.rs
> +            mutation.replace_token_transfer_trivia(first_token_with_newline, new_token);
This is done inside `replace_token_transfer_trivia` function. I added some other test cases to show that.

2022-12-02 08:44 UTC, MichaReiser commented on crates/rome_rowan/src/trivia.rs
> +//! Module that exports APIs to help working with trivia
I recommend to move the implementation into the existing `syntax/trivia` file

2022-12-02 08:52 UTC, MichaReiser commented on crates/rome_rowan/src/trivia.rs
> +///  });
Can we use `SyntaxToken::new_detached` instead

2022-12-02 08:52 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +/// it peeks the previous token and recursively call itself.
If you don't like the suggestion, replace the `it it` with `it`

2022-12-02 08:52 UTC, MichaReiser commented on crates/rome_js_analyze/tests/suppression/a11y/useKeyWithClickEvents.jsx.snap
> +</div>
Okay. that was a bad example on my side. I thought the rule would trigger on the `onClick` attribute and not on the whole element. 

Can you add a test for


```suggestion
<button
    className="SomeManyClasses"
    onClick={(event) => console.log(event.ctrlKey == true)}
    style="color: red"
>
    Some content
</button>
```

2022-12-02 08:53 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/batch.rs
> +        new_element: &[AnyJsxChild],
```suggestion
        new_elements: &[AnyJsxChild],
```

2022-12-02 08:55 UTC, MichaReiser commented on crates/rome_js_analyze/src/suppression_action.rs
> +                        ],
I recommend changing the `new_elements` argument of `add_jsx_elements_after_element` to `IntoIterator<Item=..>` instead because:

* It removes the need to pass a slice here (you can write `[AnyJsxChild::...]` directly without the need for the `&`
* It avoids cloning the elements inside of `add_jsx_elements_after_element`


Same for `add_jsx_elements_before_element`

2022-12-02 11:46 UTC, MichaReiser commented on crates/rome_js_analyze/src/utils/batch.rs
> +                    new_items.push(next_element);
Can't we push the peeked element instead so that we avoid the `unwrap` call 

```suggestion
                    new_items.push(next_element);
                    old_elements.next();
```

2022-12-02 11:48 UTC, MichaReiser approved these changes

2022-12-02 13:37 UTC, merged