fix(rome_js_analyze): fix noShoutyConstants with empty string
rome/tools pull request #3868
Opened 2022-11-26 16:03 UTC by rosslh

## Summary

Closes #3867

## Test Plan

> cargo test -p rome_js_analyze -- shouty

With some new test cases which were missing:

```
const Empty = "";
export const E = Empty

const NotMatching = "DoesNotMatch";
export const F = NotMatching

const matchingLowercase = "matchingLowercase"
export const G = matchingLowercase
```

2022-11-26 18:14 UTC, MichaReiser requested changes

2022-11-26 18:14 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs
>      for (from_id, from_literal) in id_text.chars().zip(literal_text.chars()) {
The problem is that `zip` returns `None` as soon as one of the iterator ends. So the lint rule reports `AL = ALPHA` even though the strings are not equal. 

This can be fixed by manually iterating over the chars

```
if id_text.len() != literal_text.len() {
  return None;
}

let mut id_iter = id_text.chars();
let mut literal_iter = literal_text.chars();

loop {
  match (id_iter.next(), literal_iter.next()) {
    (Some(id_char), Some(literal_char)) => {
		if id_char != literal_char || !id_char.is_lowercase() {
           return None;
        }
	},
   (None, None) => break,
	// Same byte length but different characters
    (Some(_), None)) | (None, Some(_)) => return None,
  }
}
```

2022-11-26 18:26 UTC, rosslh commented on crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs
>      for (from_id, from_literal) in id_text.chars().zip(literal_text.chars()) {
Good catch @MichaReiser. Correct me if I'm wrong, but I think this code should be enough to fix the problem:

```rust
if id_text.len() != literal_text.len() {
  return None;
}
```

If we make sure the strings are the same length, the `zip` code should work as expected, right?

2022-11-26 18:35 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs
>      for (from_id, from_literal) in id_text.chars().zip(literal_text.chars()) {
Yeah, I think you're right. I was worried about the case where one string uses unicode characters (that are multiple bytes) and the other does not but the chars would then be different.

2022-11-26 18:35 UTC, MichaReiser approved these changes

2022-11-26 18:35 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/style/no_shouty_constants.rs
>              return None;
Nit: We can remove one of the `is_lowercase` checks below. Either they are both lowercase or both are not.

2022-11-26 19:29 UTC, MichaReiser approved these changes

2022-11-28 08:40 UTC, MichaReiser commented
Thank you!

2022-11-28 08:40 UTC, merged