feat(semantic_analyzers): implement `NoRedundantUseStrict` rule
rome/tools pull request #3895
Opened 2022-11-29 08:46 UTC by mzbac

## Summary
There used to be a parse check of the "use strict" directive and an error would be thrown when encountering redundant "use strict" directives; however, it should be a linter error rather than a parser warning.

So this PR is for addressing that: -> https://github.com/rome/tools/issues/2678

## Test Plan
Tests are added as part of the implementation.

2022-11-29 08:55 UTC, mzbac commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +        for n in node.syntax().descendants() {
I am not sure if this is the most optimised way to check all the directives. If you know a better way to do this, please let me know.

2022-11-29 10:00 UTC, leops commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +        for n in node.syntax().descendants() {
This will iterate over all the nodes in the file which is quite a heavy operation. In addition since the loop collects all the `use strict` directives it encounters without checking the node hierarchy, the rule may return a false positive in a case like this:
```js
function foo() {
    "use strict";
}
function bar() {
    "use strict";
}
```
Instead it would probably be more efficient to query for `JsDirective` nodes, then visit its ancestors to find `AnyJsRoot` and `JsFunctionBody` nodes, and inspect their directive lists to detect duplicate directives

2022-11-29 11:34 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +    type State = Vec<JsDirective>;
It could help readability to use a struct here

```
struct State {
  first: JsDirective,
  redudant: Vec<JsDirective>
}
```

Doing so encodes the fact that:

* There's always at least one directive
* Which directives must be removed.

2022-11-29 11:34 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +            }
You can call `batch.remove_node(directive)`

2022-11-29 11:34 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +            applicability: Applicability::MaybeIncorrect,
What's the reason why this rule may be incorrect?

2022-11-29 11:34 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +        for n in node.syntax().descendants() {
We should also consider that functions inside [modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_modules) and [classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_classes) are strict by default.

TypeScript declaration files are non-strict even if they are modules. However, retrieving the source type isn't something a rule can query today

2022-11-29 11:50 UTC, Conaclos commented
The commit title should certainly start with `feat(rome_js_analyze)`.

2022-11-29 13:14 UTC, mzbac commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +        for n in node.syntax().descendants() {
> This will iterate over all the nodes in the file which is quite a heavy operation. In addition since the loop collects all the `use strict` directives it encounters without checking the node hierarchy, the rule may return a false positive in a case like this:
> 
> ```js
> function foo() {
>     "use strict";
> }
> function bar() {
>     "use strict";
> }
> ```
> 
> Instead it would probably be more efficient to query for `JsDirective` nodes, then visit its ancestors to find `AnyJsRoot` and `JsFunctionBody` nodes, and inspect their directive lists to detect duplicate directives

@leops 
I have tried your suggestion, but I encountered the issue that redundant directives will be reported multiple times if we set the query as `Ast<JsDirective>`.  The lint error will be like ⬇️ . Any thoughts?


---
source: crates/rome_js_analyze/tests/spec_tests.rs
assertion_line: 83
expression: invalid.js
---
# Input
```js
"use strict";

function test() {
	"use strict";
	function inner_a() {
		"use strict"; // redundant directive
	}
	function inner_b() {
		function inner_inner() {
			"use strict"; // additional redundant directive
		}
	}
}

```

# Diagnostics
```
invalid.js:1:1 lint/nursery/NoRedundantUseStrict  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ! Cannot have redundant directive of "use strict".
  
  > 1 │ "use strict";
      │ ^^^^^^^^^^^^^
    2 │ 
    3 │ function test() {
  
  i This is where the redundant "use strict" is declared.
  
    3 │ function test() {
  > 4 │ 	"use strict";
      │ 	^^^^^^^^^^^^^
    5 │ 	function inner_a() {
    6 │ 		"use strict"; // redundant directive
  
  i Suggested fix: Remove redundant use strict
  
     2  2 │   
     3  3 │   function test() {
     4    │ - → "use·strict";
     5    │ - → function·inner_a()·{
        4 │ + → function·inner_a()·{
     6  5 │   		"use strict"; // redundant directive
     7  6 │   	}
  

```

```
invalid.js:1:1 lint/nursery/NoRedundantUseStrict  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ! Cannot have redundant directive of "use strict".
  
  > 1 │ "use strict";
      │ ^^^^^^^^^^^^^
    2 │ 
    3 │ function test() {
  
  i This is where the redundant "use strict" is declared.
  
    3 │ function test() {
  > 4 │ 	"use strict";
      │ 	^^^^^^^^^^^^^
    5 │ 	function inner_a() {
    6 │ 		"use strict"; // redundant directive
  
  i This is where the redundant "use strict" is declared.
  
    4 │ 	"use strict";
    5 │ 	function inner_a() {
  > 6 │ 		"use strict"; // redundant directive
      │ 		^^^^^^^^^^^^^
    7 │ 	}
    8 │ 	function inner_b() {
  
  i Suggested fix: Remove redundant use strict
  
     2  2 │   
     3  3 │   function test() {
     4    │ - → "use·strict";
     5    │ - → function·inner_a()·{
     6    │ - → → "use·strict";·//·redundant·directive
        4 │ + → function·inner_a()·{
     7  5 │   	}
     8  6 │   	function inner_b() {
  

```

```
invalid.js:1:1 lint/nursery/NoRedundantUseStrict  FIXABLE  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ! Cannot have redundant directive of "use strict".
  
  > 1 │ "use strict";
      │ ^^^^^^^^^^^^^
    2 │ 
    3 │ function test() {
  
  i This is where the redundant "use strict" is declared.
  
    3 │ function test() {
  > 4 │ 	"use strict";
      │ 	^^^^^^^^^^^^^
    5 │ 	function inner_a() {
    6 │ 		"use strict"; // redundant directive
  
  i This is where the redundant "use strict" is declared.
  
     8 │ 	function inner_b() {
     9 │ 		function inner_inner() {
  > 10 │ 			"use strict"; // additional redundant directive
       │ 			^^^^^^^^^^^^^
    11 │ 		}
    12 │ 	}
  
  i Suggested fix: Remove redundant use strict
  
     2  2 │   
     3  3 │   function test() {
     4    │ - → "use·strict";
     5    │ - → function·inner_a()·{
        4 │ + → function·inner_a()·{
     6  5 │   		"use strict"; // redundant directive
     7  6 │   	}
     8  7 │   	function inner_b() {
     9  8 │   		function inner_inner() {
    10    │ - → → → "use·strict";·//·additional·redundant·directive
    11  9 │   		}
    12 10 │   	}
  

```

2022-11-29 13:21 UTC, leops commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +        for n in node.syntax().descendants() {
Yes I think that's expected, we should emit a separate diagnostic for each redundant directive that needs to be removed

2022-11-29 13:23 UTC, mzbac commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +            applicability: Applicability::MaybeIncorrect,
> What's the reason why this rule may be incorrect?
Kind of copy-pasted; however, with the suggestion from leops, it may cause some issues for the autofix.

2022-11-29 13:27 UTC, mzbac commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +            }
I tried the `remove_node` yesterday, but I am still getting an error. I'm not sure how to convert it to AstNode.
` batch.remove_node(js_directive);
    |                   ----------- ^^^^^^^^^^^^ the trait `AstNode` is not implemented for `&JsDirective`
    |                   |
    |                   required by a bound introduced by this call`

2022-11-29 13:32 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_use_strict.rs
> +        let ancestors = node.syntax().parent()?.parent()?.parent()?.ancestors();
You can use `ancestors()` directlly and then match on the kind and I then recommend you to declare a node `AnyNodeWithDirevices`

```
declare_node_union! {
  AnyNodeWithDirevices = JsFunctionBody | AnyJsRoot
}

impl AnyNodeWithDirevices {
 fn directives(&self) -> JsDirectiveList {
	match self {
		...
    }
  }
}
```

I also recommend generating a different diagnostic for every redundant directive rather than aggregating them together. 

You can then write

```suggestion
let mut outer_most: Option<JsDirective> = None;

for parent in node.syntax().ancestors().skip(1).filter_map(AnyNodeWithDirevices::cast) {
	for directive in parent.directives() {
		if directive.value_token().map_or(false, |t| matches!(t.text_trimmed(), "'use strict'" | "\"use strict\"")) {
			outer_most = Some(directive);
			break; // continue with next parent
		}
	 }
} 
```

2022-11-29 13:38 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_use_strict.rs
> +        let ancestors = node.syntax().parent()?.parent()?.parent()?.ancestors();
Additionally we may not necessarily want to skip the `JsDirectiveList` that contains the query node, we could also check it for duplicates to catch a case like this:
```js
"use strict";
"use strict";
```
I'm not sure that's really necessary though, it seems like an unlikely edge case ...

2022-11-29 13:39 UTC, mzbac commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_use_strict.rs
> +        let ancestors = node.syntax().parent()?.parent()?.parent()?.ancestors();
Thanks @MichaReiser, I was not aware of `declare_node_union!`. I will update the code based on your suggestion!

2022-11-29 13:43 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +            }
You must clone the directive to get an owned node. 

```
for js_directive in &state.redundant {
	batch.remove_node(js_directive.clone());
}
```

2022-11-29 14:17 UTC, mzbac commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +            }
Thanks.. didn't notice I am passing a reference...:cry

2022-11-29 14:25 UTC, mzbac commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +            applicability: Applicability::MaybeIncorrect,
@MichaReiser I changed it to `Applicability::Always`, please let me know if it is inappropriate.

2022-11-29 16:11 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_use_strict.rs
> +    redundant: JsDirective,
You don't actually need to store the redundant node, it can be accessed from `diagnostic` and `action` by calling `ctx.query()` again

2022-11-29 16:11 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_use_strict.rs
> +            state.first.range(),
The primary range of the diagnostic should be where the error happens, so this should point to `ctx.query().range()` with the detail advice pointing to `state.first.range()` instead

2022-11-29 16:11 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_use_strict.rs
> + /// "use strict";
These examples should be enclosed in ` ```js ` code blocks, with the invalid ones tagged with `expect_diagnostic` to have the documentation generator print a snapshot of the emitted diagnostic

2022-11-29 16:11 UTC, leops commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_use_strict.rs
> +     name: "NoRedundantUseStrict",
The name of the rule should start with a lowercase letter: `noRedundantUseStrict`

2022-11-29 17:44 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +            applicability: Applicability::MaybeIncorrect,
@MichaReiser generally, I have been suggesting to contributors to mark code actions - for new rules that are under `nurser` - as `Applicability::MaybeIncorrect` to better reflect the meaning of the `nursery` group: rules that are still under development. 

Once we decide to promote them, we can change their applicability if we feel like it.

2022-11-30 02:55 UTC, mzbac commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +        for n in node.syntax().descendants() {
> We should also consider that functions inside [modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_modules) and [classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_classes) are strict by default.
> 
> TypeScript declaration files are non-strict even if they are modules. However, retrieving the source type isn't something a rule can query today

@MichaReiser Do we need to implement those as part of the PR? I may need some help from you to see how to implement it..

2022-11-30 08:14 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redundant_use_strict.rs
> +            applicability: Applicability::MaybeIncorrect,
I think that's a good suggestion if the rule is known to not provide correct fixes yet because we are aware of unhandled cases. But I don't think it's necessary when the rule is "done" and only remains in the nursery group to collect feedback before promoting it.

2022-11-30 08:34 UTC, MichaReiser requested changes
There are a few simplifications that we can make and I don't think the rule handles the case where a function has two use strict directives correctly yet. 

We can merge this PR after these things have been changed and add support for classes and modules, where strict mode is enabled by default, separately.

2022-11-30 08:55 UTC, mzbac commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_use_strict.rs
> +            }
@MichaReiser  
The case is covered by current logic, but I think your suggestion is easier to read. I'm happy to change it as you suggested! thanks

```
function test() { "use strict"; "use strict"; }
```

2022-11-30 09:47 UTC, MichaReiser approved these changes

2022-11-30 15:12 UTC, ematipico approved these changes

2022-11-30 15:12 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_use_strict.rs
> + /// Prevents from having redundant \"use strict\"
```suggestion
 /// Prevents from having redundant `"use strict"`.
```

2022-11-30 15:12 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_use_strict.rs
> + /// Prevents from having redundant \"use strict\"
If you apply these suggestions, you would need to run again `cargo lintdoc`

2022-11-30 22:58 UTC, merged