chore(rome_js_analyze): noSwitchDeclarations
rome/tools pull request #3917
Opened 2022-12-01 18:22 UTC by Conaclos

## Summary

This implements ESLint's [no-case-declarations](https://eslint.org/docs/latest/rules/no-case-declarations) under the name `noSwitchDeclarations`.

In contrast to ESLint, this rule handles TypeScript declarations (enum, ...).

## Test Plan

Uni test and doc-tests included.

2022-12-02 07:39 UTC, MichaReiser reviewed
This rule has overlaps with the `UseSingleCaseStatement`. What's your recommendation on how these rules should (or should not) co-exist?

2022-12-02 07:39 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +        name: "noSwitchDeclarations",
What's your reasoning for using the name `noSwitchDeclaration` over ESLint's name?

2022-12-02 07:39 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +}
You can implement these helpers in `AnyJsSwitchClause` by moving it into `union_ext.rs`

2022-12-02 07:39 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +}
There's an existing `AnyJsDeclaration` node that you canuse instead

2022-12-02 09:49 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +}
I first used this abstraction. Unfortunately, `JsVariableStatement` is not part of it. Indeed, `AnyJsDeclaration` only includes `JsVariableDeclaration`. I am not sure if it is intentional. Indeed, a variable declaration is always part of a variable statement?  We should maybe use `JsVariableStatement` instead of `JsVariableDeclaration` in `AnyJsDeclaration`? `JsVariableStatement` and `JsVariableDeclaration` could even be merged?

For the purpose of this PR, I think we need to stick with this custom union.

2022-12-02 10:00 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +        name: "noSwitchDeclarations",
1. the rule applies to both any switch clauses (including default one)
2. It is not really declarations at the scope of case/default that are prohibited: it is at the scope of the switch

I first renamed to `noSwitchScopedDeclarations` (alternative could be `noSwitchHoistedDeclarations`). And then simplified it to `noSwitchDeclarations`.

By the way, I am not sure about the plural form.

2022-12-02 11:38 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +}
It's because `AnyJsDeclaration` is used for the declaration part of `export let a = 10`;  where `export` is the statement and the `JsVariableDeclaration` is the declaration (as the name suggests). 

What's the reason that you need `JsVariableStatement` in the union. Is it because you want to remove the whole statement? 
If that's the reason, then you could work around it by having a 👍 

```

function closest_statement(declaration: AnyJsDeclaration) -> Option<AnyJsModuleItem> {
  match declaration {
	AnyJsDeclaration::JsVariableDeclaration(declaration) => declaration.parent::<AnyJsModuleItem>(),
    declaration => AnyJsModuleItem::cast(declaration.into_syntax())
  }
}
```

2022-12-02 14:33 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +}
By replacing my union with AnyJsDeclarations, I got the following error:

```js
    analysis returned no diagnostics.
     code snippet:
     switch (foo) {
        case 0:
            const x = 1;
            break;
        case 2:
            x; // `x` can be used while it is not initialized
            break;
    }
```

Because `const x = 1;` is a `JsVariableStatement`.

2022-12-03 20:56 UTC, xunilrj commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +}
My major concern with the `declare_node_union!` is the code generation that you are not using.

A simple `match`, will be simpler I think.

```rust
ctx.query().consequent()
    .into_iter()
    .filter_map(|statement| {
        match statement {
            ...
        }
    })
    .collect()
```

This way is more explicit what is allowed or not. And any change to `AnyJsStatement` will give us a compilation error.

2022-12-04 12:49 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +}
An alternative could be to add `JsVariableStatement` to `AnyJsStatement`?

2022-12-05 10:16 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +}
`JsVariableStatement` is a variant of `AnyJsStatement`.

2022-12-07 22:13 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +}
> `JsVariableStatement` is a variant of `AnyJsStatement`.

Sorry, I updated my answer: I mean to make `JsVariableStatement` a variant of `AnyJsDeclaration` and potentially removing `JsVariableDeclaration`. Or merging `JsVariableStatement` and  `JsVariableDeclaration`.

It is certainly a discussion for another thread. I will integrate the proposition of @xunilrj.

2022-12-19 11:17 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +        name: "noSwitchDeclarations",
> By the way, I am not sure about the plural form.

It should be **singular**, in my opinion. The rule is triggered for discriminant inside the `switch`, not for the whole `switch`. I would suggest `noSwitchWithDeclarations`, which sounds better.

2022-12-19 11:20 UTC, ematipico commented
> I could also propose to eventually make useSingleCaseStatement obsolete

We could deprecate `useSingleCaseStatement` in this release cycle and suggest this new rule. This won't create breaking changes..

2022-12-19 12:07 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +        name: "noSwitchDeclarations",
`noDeclarationInSwitch` could be more consistent with existing rules? (`noAssignInExpressions`, ...)

2022-12-21 10:11 UTC, leops commented
> > I could also propose to eventually make useSingleCaseStatement obsolete
> 
> We could deprecate `useSingleCaseStatement` in this release cycle and suggest this new rule. This won't create breaking changes.

The `useSingleCaseStatement` rule has already been moved to the `style` group and removed from the recommended set in `11.0.0`. I don't think we should go as far as deprecating it since its use case (enforce that case clause are wrapped in a block) is somewhat different from what `noSwitchDeclaration` is enforcing (disallow declarations in case clause), and some users may want to keep both rules enabled.

2023-01-05 11:43 UTC, ematipico requested changes
While it's true that we render diagnostics as part of the documentation, we should also test in our test suite for many reasons:
- diagnostics can be seen as plain text, helping the reviewers;
- they help to catch regression tools - in fact if a rule changes group and we forget to change its group in the testing suite, a snapshot test change is triggered;

2023-01-05 11:43 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +            .take(2);
It could be useful documenting what's this 2 is and why we use 2.

2023-01-05 11:43 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +            },
This phrase could be reworded. When I read it, it doesn't explain **why** this is an error or what kind of error it could lead to. Remember that this is the only message that users can see in **editors**, so we should be very clear about the message's intent.

2023-01-05 18:41 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_switch_declarations.rs
> +            .take(2);
I integrated the proposal I made for in #4069 (adding `indentation_trivia` for all syntax tokens).

2023-02-13 20:50 UTC, merged