fix(rome_js_analyze): should handle read-only arrays
rome/tools pull request #3954
Opened 2022-12-05 12:01 UTC by unvalley

## Summary

## Test Plan

2022-12-10 11:40 UTC, MichaReiser requested changes
`readonly` is a type operation and is represented by the `TsTypeOperatorType` node. You can inspect the AST of an array with a readonly operation by opening [this playground](https://docs.rome.tools/playground/?indentStyle=space&trailingComma=none&code=dAB5AHAAZQAgAEEAIAA9ACAAcgBlAGEAZABvAG4AbAB5ACAAWwBzAHQAcgBpAG4AZwBdADsA). 

It's, therefore, not necessary to change the AST to support readonly arrays. Instead, the lint must create a new `TsTypeOperatorType` where the `operation_token` is `readonly` and `ty` is the array type

2022-12-13 17:54 UTC, unvalley commented
@MichaReiser Thanks, I've fixed to use `TsTypeOperatorType`. Please take a look.

2022-12-15 09:21 UTC, leops approved these changes

2022-12-15 09:21 UTC, leops commented on crates/rome_js_analyze/src/analyzers/style/use_shorthand_array_type.rs
> +                    let readonly_token = JsSyntaxToken::new_detached(
Nit: let's move this inside the `TsArrayKind::Readonly => {}` branch to avoid creating a token if it's not getting used

2022-12-15 09:24 UTC, MichaReiser approved these changes

2022-12-15 22:06 UTC, unvalley commented on crates/rome_js_analyze/src/analyzers/style/use_shorthand_array_type.rs
> +                    let readonly_token = JsSyntaxToken::new_detached(
Thanks, I'll fix.

2022-12-16 01:07 UTC, unvalley commented on crates/rome_js_analyze/src/analyzers/style/use_shorthand_array_type.rs
> +                    let readonly_token = JsSyntaxToken::new_detached(
@leops done at c310baa

2022-12-16 15:30 UTC, merged