Support extends constraints on infer type
rome/tools pull request #4018
Opened 2022-12-08 14:47 UTC by nissy-dev

## Summary

Part of #2400 

This PR is initial implementation for "extends constraints on infer type" released in TS.4.7.

## Test Plan

I add some parser tests and confirmed the prettier test almost passed.
The only following  case is not passed, so I'm currently thinking about how to pass it.

```ts
type X9<U, T> = T extends (infer U extends number ? U : T ) ? U : T
```

2022-12-09 16:51 UTC, MichaReiser requested changes
I found some [TypeScript test cases](https://deploy-preview-4018--docs-rometools.netlify.app/playground/?code=dAB5AHAAZQAgAFgAMQA1ADwAVAA%2BACAAPQAgAFQAIABlAHgAdABlAG4AZABzACAAewAgAFsAUAAgAGkAbgAgAGkAbgBmAGUAcgAgAFUAIABlAHgAdABlAG4AZABzACAAawBlAHkAbwBmACAAVAAgAD8AIAAxACAAOgAgADAAXQA6ACAAMQA7ACAAfQAgAD8AIAAxACAAOgAgADAAOwAgAC8ALwAgAG8AawAsACAAcABhAHIAcwBlAGQAIABhAHMAIABjAG8AbgBkAGkAdABpAG8AbgBhAGwACgB0AHkAcABlACAAWAAxADcAPABUAD4AIAA9ACAAVAAgAGUAeAB0AGUAbgBkAHMAIAB7ACAAWwBQACAAaQBuACAAawBlAHkAbwBmACAAVAAgAGEAcwAgAGkAbgBmAGUAcgAgAFUAIABlAHgAdABlAG4AZABzACAAUAAgAD8AIAAxACAAOgAgADAAXQA6ACAAMQA7ACAAfQAgAD8AIAAxACAAOgAgADAAOwAgAC8ALwAgAG8AawAsACAAcABhAHIAcwBlAGQAIABhAHMAIABjAG8AbgBkAGkAdABpAG8AbgBhAGwA) that the current implementation doesn't handle correctly


You can run `cargo coverage --language=ts` to run the typescript test cases (I hope our TS submodule is recent enough). Or you can paste the content of [this file](https://github.com/microsoft/TypeScript/blob/01b9a2d5b002298d7bb76e1f2c90dcf8a7908545/tests/baselines/reference/inferTypesWithExtends1.js) in the playground and see if it gets parsed correctly. 

I suspect that the issue is related to the fact that #48112 uses speculative parsing:

https://github.com/microsoft/TypeScript/blob/01b9a2d5b002298d7bb76e1f2c90dcf8a7908545/src/compiler/parser.ts#L3974-L3989

It only parses out the constraint if conditional types are disallowed or the current token after parsing the type isn't a `?` token.

2022-12-09 16:51 UTC, MichaReiser commented on xtask/codegen/js.ungram
> +	type_parameter: TsTypeParameter
My understanding is that `infer` doesn't allow a default type `infer S extends string = string` (it would defeat the purpose of `infer`). 

That's why I recommend not using `TsTypeParameter` and instead add the additional fields to `TsInferType` 

 ```suggestion
	name: TsTypeParameterName
	constraint: TsTypeConstraintClause?
```

2022-12-19 06:03 UTC, nissy-dev commented
@MichaReiser 
Thank you for your review! I updated codes based on your comments. Currently, I struggle with two edge case. The first case (EdgeCase1) is that it is not sufficient for the parser to check one token ahead. The second case (EdgeCase2) is that parse failed because of removing parentheses. I would appreciate if you could give me some advice.


```
type EdgeCase1<T> = T extends { [P in infer U extends keyof T ? 1 : 0]: 1; } ? 1 : 0;
type EdgeCase2<T> = T extends ((...a: any[]) => infer R extends string) ? R : never;
```


Log
```
  ✖ expected `?` but instead found `;`

  > 1 │ type EdgeCase2<T> = T extends (...a: any[]) => infer R extends string ? R : never;
      │                                                                            ^
    2 │
```

2022-12-20 10:50 UTC, MichaReiser commented
> @MichaReiser Thank you for your review! I updated codes based on your comments. Currently, I struggle with two edge case. The first case (EdgeCase1) is that it is not sufficient for the parser to check one token ahead. The second case (EdgeCase2) is that parse failed because of removing parentheses. I would appreciate if you could give me some advice.
> 
> ```ts
> type EdgeCase1<T> = T extends { [P in infer U extends keyof T ? 1 : 0]: 1; } ? 1 : 0;
> type EdgeCase2<T> = T extends ((...a: any[]) => infer R extends string) ? R : never;
> ```
> 
> Log
> 
> ```
>   ✖ expected `?` but instead found `;`
> 
>   > 1 │ type EdgeCase2<T> = T extends (...a: any[]) => infer R extends string ? R : never;
>       │                                                                            ^
>     2 │
> ```


I looked into this more closely because it wasn't clear to me why the parsing is failing, and I created a [draft PR](https://github.com/nissy-dev/tools/pull/5/) that uses `try_parse` and allows conditional places in a few more places. In my opinion it would be good to explore if the `DisallowConditionalTypes` flag would be moved into a new `TypesContext` that works similar to `ExpressionContext` and is passed down everywhere where we parse types. It makes it easier to debug and reason about the code (with the downside of it needing to be passed explicitly)

## Case 1

You can use the `try_parse` function for speculative parsing when a fixed lookahead isn't sufficient (as it is in this case because you need to look if the type is followed by a `?` token and the type could be of multiple tokens). 


## Case 2

Not entirely sure but I think the issue here is that you missed to allow conditional types.

2022-12-23 08:41 UTC, MichaReiser commented
!bench_parser

2022-12-23 08:51 UTC, MichaReiser commented
Thanks for updating the PR. 

Do you plan to refactor the code to use a `TypeContext` instead of extending the `ParserState`?

There are a few tests failing that should pass 

* `type Equals = A extends () => B extends C ? D : E ? F : G;`
* `type Equals<A, B, C, D, E, F, G> = A extends (x: B extends C ? D : E) => 0 ? F : G;` This one fails for typescript too but should be easy to fix by wrapping the `parse_ts_type` call in `parse_ts_parenthesized_type` with an `allow()`

2022-12-23 15:57 UTC, nissy-dev commented
@MichaReiser 
Thank you for your reviews and comments and i'm so sorry for a late response. I really appreciate the time you spent on this. I learned a lot about how to handle parser contexts and use try_parse from your PR.

I would like to do the refactoring and fix the failing tests if possible, but it will be the day after tomorrow before I can start.

2022-12-23 22:18 UTC, MichaReiser commented
> @MichaReiser 
> 
> Thank you for your reviews and i'm so sorry for a late response. I really appreciate the time you spent on this. I learned a lot about how to handle parser contexts and use try_parse from your PR.
> 
> 
> 
> I would like to do the refactoring and fix the failing tests if possible, but it will be the day after tomorrow before I can start. This task might have been a bit difficult for me. Therefore, I am willing to have you continue the task on your end. 

That's alright. We're all taking a few days off. Enjoy the holidays

2022-12-25 15:14 UTC, nissy-dev commented
> There are a few tests failing that should pass

I could fix these tests and pass all prettier tests! 

> Do you plan to refactor the code to use a TypeContext instead of extending the ParserState?

I tried to refactor in a few days, but it was difficult to me. I would like you to do the refactoring work if possible.

2022-12-26 00:45 UTC, nissy-dev commented on crates/rome_js_formatter/src/parentheses.rs
> +/// Tests if `node` is the extends type of a [TsConditionalType]
I referred to https://github.com/prettier/prettier/issues/13275

2022-12-26 00:46 UTC, nissy-dev commented on crates/rome_js_formatter/src/parentheses.rs
> +pub(crate) fn is_includes_inferred_return_types_with_extends_constraints(
I referred to https://github.com/prettier/prettier/issues/13275

2022-12-28 14:34 UTC, MichaReiser commented
> > There are a few tests failing that should pass
> 
> I could fix these tests and pass all prettier tests!
> 
> > Do you plan to refactor the code to use a TypeContext instead of extending the ParserState?
> 
> I tried to refactor in a few days and made PR [nissy-dev#6](https://github.com/nissy-dev/tools/pull/6). If the PR is not so different from your thought, I will merge it into this PR and continue to review.

This PR and your other PR looks good. The only thing that we need to be careful about is to make sure to pass `context` through correctly and only use `TypeContext::default` in positions where a type starts a complete new context (because it is parenthesized)

2022-12-29 15:43 UTC, nissy-dev commented
> The only thing that we need to be careful about is to make sure to pass context through correctly and only use TypeContext::default in positions where a type starts a complete new context (because it is parenthesized)


If the scope of the refactoring is up to making sure the context is passed correctly, I think it is better to separate PR about the refactoring task. This is because there are too many functions which the context should be passed and this refactoring affects many logic. 

And then, it is really hard for me to pass context through correctly. I tried, but I couldn't do that. I would like you to do  this refactoring on your end if possible.

2022-12-30 09:41 UTC, MichaReiser approved these changes

2022-12-30 09:42 UTC, MichaReiser commented
That sounds good to me. Thank you @nissy-dev for another excellent parser contribution!

2022-12-30 11:06 UTC, MichaReiser commented
!bench_parser

2022-12-30 11:33 UTC, merged