feat(rome_js_analyze): `noClassAssign` rule
rome/tools pull request #4033
Opened 2022-12-10 23:16 UTC by kaioduarte

## Summary

Closes #3970.

## Test Plan

```bash
cargo test -p rome_js_analyze -- no_class_assign
```

2022-12-12 08:41 UTC, ematipico commented
@kaioduarte could please comment on the PR so I can assign it to you? This will help to show the contributors that the issue is taken already

2022-12-12 09:25 UTC, leops commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_class_assign.rs
> +            ctx.query().range(),
The primary range of a diagnostic should be where the error happen, in this case it should point to the `Reference` that overwrites the binding while the identifier of the class should be the `detail` advice. This implies the rule should emit a diagnostic for each write, but that can be done easily by directly returning the content of the `binding.all_writes(model)` iterator from the `run` function

2022-12-12 09:25 UTC, leops commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_class_assign.rs
> +    type Query = Semantic<JsIdentifierBinding>;
It's not recommended to match on `JsIdentifierBinding` since that's a very common node, so it will execute the rule many times for a given file with only a few matches. It would be for performance to match on `AnyJsClass` and exit early from `run` if the class node doesn't have an identifier

2022-12-12 13:40 UTC, MichaReiser requested changes

2022-12-12 13:40 UTC, MichaReiser commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_class_assign.rs
> +    pub(crate) AnyClass = JsClassDeclaration | JsClassExpression
We should use `AnyJsClass` which ensures that you handle all classes.

2022-12-13 10:57 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_class_assign.rs
> +        if binding.all_writes(model).count() > 0 {
This will potentially iterate all references, depending on the iterator type.

You can more safely just look if `next()` is there or not.

```rust
binding.all_writes(model).next().map(|x| binding.clone())
```

2022-12-13 10:59 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_class_assign.rs
> +        Some(RuleDiagnostic::new(
I think it is also useful to show where the class is assigned. At least the first assignment.

2022-12-13 20:16 UTC, xunilrj commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_class_assign.rs
> +        if let Ok(Some(id)) = node.id() {
Nice!
Nit: feel free to ignore:

```rust
node.id().and_then(|id| {
    id?.as_js_identifier_binding()?.all_writes(model).collect()
}).unwrap_or_default()
```

You can avoid the `collect()` and the allocation with

```rust
type Signals = AllBindingsWriteReferenceIter;
```

2022-12-15 09:26 UTC, MichaReiser approved these changes

2022-12-16 10:11 UTC, ematipico approved these changes
I wonder if there's a way to avoid merge conflicts when merging rules :( 
PR looks good, but needs to rebased now and regenerate the files

2022-12-16 13:09 UTC, merged