feat(rome_js_analyze): `useYield` rule
rome/tools pull request #4037
Opened 2022-12-11 14:54 UTC by kaioduarte

## Summary
Closes #3994.

## Test Plan

```shell
cargo test -p rome_js_analyze -- use_yield
```

2022-12-12 11:29 UTC, MichaReiser requested changes

2022-12-12 11:29 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_yield.rs
> +            && !function_body_syntax.clone().into_list().is_empty()
Nit: I recommend returning the statement list from the match clause rather than the syntax node. It simplifies the match expression and makes it clear that this isn't an arbitrary node but a statement list

2022-12-12 11:29 UTC, MichaReiser commented on crates/rome_js_analyze/src/analyzers/nursery/use_yield.rs
> +}
My understanding is that this logic incorrectly traverses into nested functions. Would you mind adding a test case:

```
function* test() {
  function* nested() {
	yield 10;
  }

  return 5;
}
```

The outer node should be flagged by the rule, but not the inner. 

You can implement this using `preorder` instead and skip a subtree if it is a class or a function. 

```rust
let mut iter = self.syntax().preorder();

while let Some(event) = iter.next() {
    match event {
        WalkEvent::Enter(node) => {
            if AnyJsClass::can_cast(node.kind()) || AnyJsFunction::can_cast(node.kind()) {
                iter.skip_subtree();
                continue;
            }
            
            if JsYieldExpression::can_cast(node.kind()) {
                return true;
            }
        }
        WalkEvent::Leave(_) => {}
    }
}

return false;
```

The downside of doing this is that we'll traverse the body of all generator functions multiple times: Once by this rule and once by our linter infrastructure. @leops had an idea with a custom visitor to avoid traversing the tree multiple times. He can give you some hints on how to implement this.

2022-12-12 17:53 UTC, notmd commented on crates/rome_js_analyze/src/analyzers/nursery/use_yield.rs
> +}
PR #4012 also need this logic to check the body of a loop has yield expression (which I'm not implemented yet). It would be great if we can reuse it.

2022-12-12 21:00 UTC, xunilrj commented
Why not doing the inverse? Query `JsYieldExpression` and find its enclosing function.
You can navigate upwards with `ancestors()` until you find a function. Or you are at the global scope.

2022-12-29 13:16 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_yield.rs
> +    type Query = Ast<AnyFunctionLike>;
Now that we have custom visitors, I think this rule should be implemented using those: https://rustdocs.rome.tools/rome_analyze/index.html#custom-visitors

2022-12-30 08:42 UTC, kaioduarte commented on crates/rome_js_analyze/src/analyzers/nursery/use_yield.rs
> +    type Query = Ast<AnyFunctionLike>;
Sure, I'll try to update it by next week.

2023-01-04 10:42 UTC, ematipico approved these changes

2023-01-04 11:43 UTC, ematipico approved these changes

2023-01-04 11:43 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_yield.rs
> +                }
I think it's better to invert the two `if`. We have fewer chances to first check `JsYieldExpression`, and then we can get the `last_mut`.

2023-01-04 11:43 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_yield.rs
> +                        debug_assert_eq!(enter_node, exit_node);
I see now why you used the `assert`. I think you might want to use `if enter_node == exit_node {}` instead.

2023-01-05 11:54 UTC, merged