feat(rome_service): recycle the node cache across parsing sessions
rome/tools pull request #4138
Opened 2023-01-04 16:39 UTC by leops

## Summary

This PR aims at improving the performance of running multiple parsing session over the same document by allowing the green node cache to be stored in the workspace alongside the syntax tree and reused by each parser invocation.

As the cache is now long-lived, this requires the implementation of a cache eviction strategy to avoid having the in-memory caches of the open documents grow indefinitely. This behavior is implemented in the `TreeBuilder` with the help of a new `LiveSet` structure that tracks the set of tokens and nodes that were retrieved from the cache or inserted by a given instance of the builder, and drains the entries that have not been marked from the cache when `finish` is called on the builder. This strategy is sufficient as the workspace maintains a node cache per-document, so only the nodes that are part of the latest revision of the syntax tree for this document need to be retained.

## Test Plan

This is an internal change that should not have observable effects (in theory even if the behavior of the cache were incorrect the workspace and parsers should continue to work correctly, but their memory usage characteristics might become less efficient).
I don't expect this change to have a significant impact on benchmarks either as those are only run "cold" on an empty cache, and the set of live nodes doesn't get build in the initial parser run.

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

2023-01-04 16:51 UTC, MichaReiser commented on crates/rome_rowan/src/green/node_cache.rs
> +}
What's the added performance overhead for initial parsing? I worry that it is substantial as it is necessary to store every token and node in the `NodeCache` and the `LiveSet`. 

I wonder if the following approaches are cheaper (it may be worth researching other GC strategies):

* Storing a version on the `NodeCache` and with every `node`/`token` entry. The implementation bumps the cache version when building a new tree. The versions of the entries are bumped during reads.
* Cloning `nodes` and `tokens` at the start of building a tree and then evicting used entries. This has the advantage that it avoids re-hashing when new entries are inserted. The set then no longer represents the "live" entries but the "dead" entries.

2023-01-04 17:12 UTC, leops commented on crates/rome_rowan/src/green/node_cache.rs
> +}
I don't expect this change to significantly impact the initial parsing performance since the live set doesn't get built in that phase (since there would be no nodes or token to evict anyway), but I agree it's not the most efficient implementation of a garbage collection strategy either.
For the versioned approach I think the actual "version" could be represented as a boolean (since we only ever need to track the previous and next version), so if we have a spare bit somewhere in the cache entry data structure it may be implemented without increasing the memory requirements of the cache.
In both case I guess it might be useful to come up with a benchmarking strategy for the re-parsing case in addition to the initial parsing.

2023-01-05 09:31 UTC, ematipico commented
!bench_parser

2023-01-05 11:29 UTC, ematipico requested changes
Some documentation needs to be added to the new APIs.

Also, while this seems to be a chance under the hoods, we are adding a new caching system inside `rome_rowan` that is not being tested in this PR. Is it not possible to add some test cases inside `rome_rowan` to verify that the new cache works as expected?

2023-01-05 11:29 UTC, ematipico commented on crates/rome_js_parser/src/parse.rs
> +    parse_with_cache(text, file_id, source_type, &mut cache)
We should normalise the names: this one is called `parse_with_cache`, but the one we have in the JSON crate is called `parse_json_with_cache`.

We should either call both of them `parse_with_cache` or rename this to `parse_js_with_cache`,

2023-01-05 11:29 UTC, ematipico commented on crates/rome_js_parser/src/parse.rs
> +pub fn parse_with_cache(
I have mixed feelings about making this function public. This function entails:
- that there's a `parse_without_cache` somewhere, but there isn't;
- that the user/consumer of this API should know more about what a "node cache" is;

Although there isn't a way to parse a document "without" cache, which means, we should maybe revisit the implementation with these two options:
1. allow parsing a document without cache;
2. or hide the cache from the public API;

2023-01-05 11:29 UTC, ematipico commented on crates/rome_json_parser/src/lib.rs
> +pub fn parse_json_with_cache(source: &str, file_id: FileId, cache: &mut NodeCache) -> JsonParse {
As this function is now public, it needs some documentation

2023-01-05 11:29 UTC, ematipico commented on crates/rome_parser/src/tree_sink.rs
> +    pub fn with_cache(text: &'a str, trivia: &'a [Trivia], cache: &'a mut NodeCache) -> Self {
Documentation

2023-01-05 11:29 UTC, ematipico commented on crates/rome_rowan/src/green/node_cache.rs
> +/// parsing session.
```suggestion
/// The [LiveSet] tracks which nodes and tokens are reachable in the most
/// recent revision of the syntax tree. It is filled as the syntax tree gets
/// rebuilt and is used to evict unused entries from the cache at the end of a
/// parsing session.
```

I find the term "reachable" a bit vague/unclear. What does "reachable" mean in this context?
Also, would you mind explaining a bit more why **pointers** are stored in this data structure?

2023-01-05 14:33 UTC, MichaReiser commented on crates/rome_rowan/src/green/node_cache.rs
> +}
The question is what the cache is optimizing for. I mainly see the benefit that the cache reduces the number of (de-) allocations which can improve performance if the added overhead is lower than the overhead of `alloc` and `drop`/`free`. I'm undecided if this change increases or decreases heap fragmentation. Reusing allocations ensures that Rome requires less memory overall (ignoring the cost for the hash sets) but it may increase fragmentation assuming that nodes of the same generation are allocated closely together and re-using some means that only smaller blocks can be re-used by the allocator. 

If we want to optimise this implementation for performance then there are two aspects that are worth considering in my view:

1. The time spent hashing and re-hasing accounts for a significant part of the `TreeSink` time. That's why it would be better in my view to store additional data in the existing hash maps or by providing the hashed key to avoid re-computation. 
2. We may be able to optimize the solution by using knowledge about the problem at hand. In most cases, changes to a document are often local and only affect a small portion of the tree. That means, most of the nodes can be reused in a re-parse (this assumption is important because using a cache would otherwise make little sense). Now, that also means that most nodes will end up in the `LiveSet`. That's why it could be beneficial to track the dead nodes instead

2023-01-05 15:14 UTC, leops commented on crates/rome_js_parser/src/parse.rs
> +pub fn parse_with_cache(
There is a set of `parse_without_cache` functions, as the already-existing `parse` and `parse_json` functions. I opted not to rename them as that would imply change all the existing call locations for the parsers, and I felt it would have made the diff for the PR less clear.

2023-01-05 15:15 UTC, leops commented
!bench_parser

2023-01-09 09:11 UTC, ematipico reviewed
Is it possible to have some stats on the memory used by the program?

2023-01-09 09:11 UTC, ematipico commented on crates/rome_rowan/src/green/node_cache.rs
> +    B = 1,
Since you called generations as "previous" and "next", wouldn't make more sense to call the variants `Previous` and `Next`?

2023-01-09 09:11 UTC, ematipico commented on crates/rome_rowan/src/green/node_cache.rs
> +        unsafe { &*ptr }
`// SAFETY`?

2023-01-09 10:17 UTC, leops commented on crates/rome_rowan/src/green/node_cache.rs
> +    B = 1,
This would be confusing as these tags are used in an alternating manner: on even generations `A` is the previous and `B` is the next, while on odd generations `B` is the previous and `A` is the next. This is why I tried to use generic names that do no directly correlate to a specific ordering, although `A` and `B` could still be misunderstood as being sorted in alphabetic orders. I also thought of using colors but the `Red` and `Green` concept are already used for the layered representation of syntax nodes and cursors.

2023-01-09 16:43 UTC, MichaReiser commented
What are we optimizing for in this PR? It seems that the changes decrease initial parse time by 0-10%, and the cached performance ranges from regressing to improving (by up to 20%)

2023-01-10 10:37 UTC, ematipico approved these changes

2023-02-12 21:38 UTC, merged