fix(rome_fs): Allow to ignore patterns to symbolic links (symlinks)
rome/tools pull request #4166
Opened 2023-01-21 18:52 UTC by realtimetodie

Fixes an issue where Rome could not ignore patterns to symbolic links (symlinks) during traversal.

Example - A rome.json configuration file with the `files.ignore` option

```json
{
  "files": {
    "ignore": [
      "symlink/**/*.ts",
    ]
  }
}
```

This implementation works for simple use cases. It does not cover symbolic links inside of symbolic links. For performance reasons, only the last resolved symbolic link is preserved and not the entire path resolution tree.

Related

- https://github.com/rome/tools/pull/4158

2023-01-21 19:45 UTC, realtimetodie commented
I expanded the test case.

2023-01-23 17:21 UTC, realtimetodie commented
@leops

2023-02-14 11:15 UTC, ematipico requested changes

2023-02-21 15:22 UTC, realtimetodie commented on crates/rome_fs/src/fs/os.rs
> +    origin_path: Option<PathBuf>,
I need to smoke on this. I will have some time tonight.

2023-03-05 16:35 UTC, realtimetodie commented on crates/rome_fs/src/fs/os.rs
> +            RomePath::new(origin_path.join(path.file_name().unwrap()))
Yes you are right, the documentation for `file_name` is confusing. It says that it returns "the last part of a path", but a file name of `..` panics.

2023-03-05 17:40 UTC, realtimetodie commented on crates/rome_fs/src/fs/os.rs
> +    origin_path: Option<PathBuf>,
I documented the code. The problem why a struct would not improve the code quality here is that the origin_path argument appears in two separate functions that both take different type of arguments (`DirEntry` vs `Path`).

I will refactor the code in the future and transform the origin_path argument into a standalone struct `PathResolutionTree` to allow multi-level symbolic link ignore patterns (ignore patterns to symbolic links inside of symbolic links).

2023-03-05 17:40 UTC, realtimetodie commented on crates/rome_fs/src/fs/os.rs
> +    mut origin_path: Option<PathBuf>,
I documented the code including the test. Please let me know if this is sufficient.

2023-03-05 18:04 UTC, realtimetodie commented
@ematipico I documented the code and updated the test, now that #4158 was merged. Please let me know if this is sufficient.

2023-03-05 18:08 UTC, ematipico approved these changes
Looks good to me! Just a comment around the diagnostics

2023-03-05 18:08 UTC, ematipico commented on crates/rome_cli/tests/snapshots/main_commands_check/fs_files_ignore_symlink.snap
> +  no diagnostic message provided
We should provide a message here.

2023-03-05 18:19 UTC, realtimetodie commented on crates/rome_cli/tests/snapshots/main_commands_check/fs_files_ignore_symlink.snap
> +  no diagnostic message provided
I moved the rome.json configuration file to the top-level directory. 

The rome.json configuration file was linted here, because the test uses the new --config-path option and the file was in the src/ directory.

2023-03-05 18:35 UTC, merged