feat(rome_service): traverse upwards the fs to discover the config file
rome/tools pull request #4224
Opened 2023-02-21 11:58 UTC by ematipico

## Summary

This PR adds a way to discover `rome.json` by traversing the file system upwards. 

## Test Plan

I manually tested the feature using the CLI in our internal repository, and tested manually the VSCode extension.

Below a recording to demonstrate the feature:

https://user-images.githubusercontent.com/602478/220338807-cb241498-807a-4bba-a8d6-2b1644e17d1e.mov

## Documentation

- [x] The PR requires documentation
- [x] I will create a new PR to update the documentation

2023-02-21 13:09 UTC, ematipico commented
CI is failing on ubuntu... it seems the some code hits an infinite loop

2023-02-21 14:02 UTC, realtimetodie commented
I like this idea and I think this is useful, nonetheless I would appreciate it if this could become an optional opt-in feature, for example with a flag `--auto-search`. Traversing upwards breaks sandboxing in Bazel. This is a problem. For example, a rome.json configuration file in a parent directory would create false positives.

2023-02-21 14:11 UTC, realtimetodie commented on crates/rome_service/src/configuration/mod.rs
> +                Ok(Some(deserialized))
```suggestion
                if from_parent {
                  // Display a message that the rome.json configuration file was found using upwards-traversal (auto-search)
                }
                Ok(Some(deserialized))
```

2023-02-21 14:11 UTC, realtimetodie commented on crates/rome_service/src/configuration/mod.rs
> +                        configuration_path = path.join(config_name);
```suggestion
                        from_parent = true;
                        configuration_path = path.join(config_name);
```

2023-02-21 14:19 UTC, ematipico commented
> I like this idea and I think this is useful, nonetheless I would appreciate it if this could become an optional opt-in feature, for example with a flag `--auto-search`. Traversing upwards breaks sandboxing in Bazel. This is a problem. For example, a rome.json configuration file in a parent directory would create false positives.

Are you open to having the feature **opt-out? I made the feature like this because it's used by the LSP too, and this is a feature requested by **many** users. And, as far as I understood, the prettier/eslint VSCode extensions do the same.

What do you think?

2023-02-21 14:25 UTC, realtimetodie commented
Yes of course, opt-out is fine. In Bazel, the path to the rome.json configuration path is set explicitly using the new `--config-path` option.

2023-02-21 14:27 UTC, realtimetodie commented
Maybe auto-traversal could be disabled, when the `--option-path` option is used (`ConfigurationBasePath::FromUser(PathBuf)`). Then we would not need an opt-out option?

2023-02-21 14:40 UTC, ematipico commented
> Maybe auto-traversal could be disabled, when the `--config-path` option is used (`ConfigurationBasePath::FromUser(PathBuf)`). Then we would not need a separate opt-out option?

That's a good suggestion! I like it!

2023-02-22 22:49 UTC, realtimetodie requested changes

2023-02-23 08:17 UTC, ematipico commented on crates/rome_service/src/configuration/mod.rs
> +    let should_error = base_path.is_from_user();
The function is a `const`, the compiler will be able to optimize it ahead

2023-02-23 09:06 UTC, merged