feat(rome_js_parser): TS 5.0 `export type *`
rome/tools pull request #4228
Opened 2023-02-22 22:01 UTC by Conaclos

## Summary

Part of #4227.
This adds the support for `export type *`.

## Test Plan

Tests included.

## Documentation

No change.

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

2023-02-23 09:09 UTC, ematipico commented
@Conaclos actually, this PR requires some change in the documentation: https://docs.rome.tools/internals/language_support/#typescript-support

But I suppose we can change it once #4227 is closed.

2023-02-23 11:56 UTC, ematipico requested changes
I think we should add some tests in our formatter test suite

2023-02-24 23:16 UTC, Conaclos commented
> I think we should add some tests in our formatter test suite

Added :)

I made some minor refactoring to improve the code.

2023-02-24 23:49 UTC, Conaclos commented
> @Conaclos actually, this PR requires some change in the documentation: https://docs.rome.tools/internals/language_support/#typescript-support
> 
> But I suppose we can change it once #4227 is closed.

This is a good point!
#2400 has also to be resolved.

2023-02-25 10:57 UTC, ematipico approved these changes

2023-02-25 10:57 UTC, merged