feat(rome_js_analyze): noNamespace
rome/tools pull request #4283
Opened 2023-03-09 17:24 UTC by noftaly

## Summary

Add the `noNamespace` rule, to disallow the use of TypeScript's namespaces, in favour of ES Modules. akin http://typescript-eslint.io/rules/no-namespace/
Fixes #4274 

## Test Plan

```
cargo test --package rome_js_analyze --test spec_tests
```

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

As this is my first contribution to Rome, don't refrain from suggesting how it could be improved or what I should maybe do differently. I'm happy to discuss! :)

2023-03-09 22:04 UTC, Conaclos requested changes

2023-03-09 22:04 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_namespace.rs
> +    /// declare module foo {}
`declare module foo {}` should be a valid code since we wish the same behavior as the ESLint rule

2023-03-09 22:04 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_namespace.rs
> +    /// declare namespace foo {}
`declare namespace foo {}` should be a valid code since we wish the same behavior as the ESLint rule.

2023-03-09 22:04 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_namespace.rs
> +                    "Do not use TypeScript's namespaces."
This could be nice to have more context to understand why this is discouraged. Something like:

```suggestion
                    "TypeScript's namespaces are an oudated way to organize code."
```

2023-03-09 23:20 UTC, ematipico requested changes

2023-03-09 23:20 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_namespace.rs
> +    type Query = Semantic<TsModuleDeclaration>;
You're not using the semantic analyzer, so you can remove `Semantic` and use `Ast` instead

2023-03-09 23:20 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_namespace.rs
> +use crate::{semantic_services::Semantic, JsRuleAction};
You should move this file to the `analyzers` folder because this file doesn't use the semantic model

2023-03-09 23:20 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_namespace.rs
> +    }
You can remove this function

2023-03-10 08:14 UTC, noftaly commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_namespace.rs
> +    /// declare module foo {}
In the ESLint rule, `declare module foo` is reported by default, by saying you wish we had the same behavior, do you mean I should make it configurable ?

2023-03-10 08:17 UTC, noftaly commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_namespace.rs
> +    type Query = Semantic<TsModuleDeclaration>;
Oops, I wasn't sure which one it would be... I had a 50/50 chance i guess.
I'll commit the fix as soon as i have the chance to.

2023-03-10 08:25 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_namespace.rs
> +    type Query = Semantic<TsModuleDeclaration>;
That's okay, don't worry. We have different type of queries, so sometimes it's difficult to understand which one to use. That's what the reviews are for :)

2023-03-10 10:39 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_namespace.rs
> +    /// declare module foo {}
My bad. That's fine as is it. If users complain about the rule, then we will relax in another PR.

2023-03-10 10:41 UTC, Conaclos requested changes

2023-03-10 10:41 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_namespace.rs
> +    /// declare module foo {}
Could you separate the snippets?

````md
```ts,expect_diagnostic
module foo {}
```

```ts,expect_diagnostic
declare module foo {}
```
````

2023-03-10 10:41 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_namespace.rs
> +    /// declare namespace foo {}
Similar here. Could you separate the snippets?

2023-03-10 10:43 UTC, Conaclos requested changes

2023-03-10 11:18 UTC, Conaclos approved these changes

2023-03-10 11:45 UTC, ematipico approved these changes

2023-03-10 13:28 UTC, merged

2023-03-10 15:20 UTC, Conaclos commented
@noftaly  Thanks for your contribution! :)

2023-03-10 15:23 UTC, noftaly commented
No problem! Thanks for the guidance and the well-written contributing guide!
If I have time I'll try to add the few points that were missing in the contributing guides from my experience