fix(rome_js_analyze): noRedeclaration declaration merging
rome/tools pull request #4288
Opened 2023-03-10 15:17 UTC by Conaclos

## Summary

Fixes #4287.

While I was fixing the issue, I realized [noduplicateparameters](that https://docs.rome.tools/lint/rules/noduplicateparameters/) could be covered by `noRedeclaration`. We could merge these two rules in another PR?

## Test Plan

Extended.

## Documentation

Updated.

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

2023-03-10 17:42 UTC, ematipico requested changes

2023-03-10 17:42 UTC, ematipico commented on crates/rome_js_syntax/src/binding_ext.rs
> +    /// See: https://www.typescriptlang.org/docs/handbook/declaration-merging.html
We should make this rustdoc more in line with [the rest](https://github.com/rome/tools/blob/main/crates/rome_js_syntax/src/expr_ext.rs#L21-L30): an explanation of the function and a doctest to make sure the intended API works, with an example of usage.

For example, we should explain what "mergeable" means to the first time contributor.

2023-03-10 17:42 UTC, ematipico commented on crates/rome_js_syntax/src/binding_ext.rs
> +        fn inner(a: &AnyJsBindingDeclaration, b: &AnyJsBindingDeclaration) -> bool {
Any reason why this function is here rather than outside? Or you could even crate a private function inside  `AnyJsBindingDeclaration`

2023-03-10 18:00 UTC, Conaclos commented on crates/rome_js_syntax/src/binding_ext.rs
> +        fn inner(a: &AnyJsBindingDeclaration, b: &AnyJsBindingDeclaration) -> bool {
> Any reason why this function is here rather than outside?

Do you mean that we could move this function in the rule file?

> Or you could even crate a private function inside AnyJsBindingDeclaration

I do not understand what you mean...

2023-03-10 19:01 UTC, ematipico commented on crates/rome_js_syntax/src/binding_ext.rs
> +        fn inner(a: &AnyJsBindingDeclaration, b: &AnyJsBindingDeclaration) -> bool {
I meant something like

```rust
impl AnyJsBindingDeclaration {
	pub fn is_mergeable(&self, other: &AnyJsBindingDeclaration) -> bool {
		AnyJsBindingDeclaration::can_merge(self, other) || 
			AnyJsBindingDeclaration::can_merge(other, self) 
	}
	// this function won't be exposed as API
	fn can_merge(&a: AnyJsBindingDeclaration, &b: &AnyJsBindingDeclaration) -> bool {}
}
```

2023-03-10 21:31 UTC, Conaclos commented on crates/rome_js_syntax/src/binding_ext.rs
> +    /// namespace Order { ... }
Inside the code? Have you some pointers? I am not sure to understand how it is useful...

2023-03-10 21:48 UTC, ematipico commented on crates/rome_js_syntax/src/binding_ext.rs
> +    /// namespace Order { ... }
https://github.com/rome/tools/blob/main/crates/rome_js_syntax/src/jsx_ext.rs#L11-L21

This is another example. This is a doctest, the code inside code block is valid rust code, and works as test. It works as you would consuming the API, and the assertion is run by cargo when running the test suite.

This is how the Rust project writes their internal documentation and tests.

2023-03-13 22:17 UTC, Conaclos commented on crates/rome_js_syntax/src/binding_ext.rs
> +    /// namespace Order { ... }
Is there an easy way to produce an AST from a string?

2023-03-15 14:14 UTC, ematipico approved these changes

2023-03-15 14:14 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redeclaration.rs
> +type Redeclaration = (String, TextRange, TextRange);
We could document what each type represents.

2023-03-15 14:14 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_redeclaration.rs
> +    /// function f() {}
Could you add 
```js
let a;
let a;
```

To the list of invalid examples?

2023-03-15 14:15 UTC, ematipico commented
> While I was fixing the issue, I realized that [noDuplicateParameters](https://docs.rome.tools/lint/rules/noduplicateparameters/) and `noRedeclaration` have some intersections. We could merge these two rules in another PR?

The two rules have different scopes. `noRedeclaration` should catch cases like

```js
let a;
let a;
```
Which causes a different error (runtime).

2023-03-15 14:55 UTC, Conaclos commented
> Which causes a different error (runtime).

Good point.
It is a bit more complex than it. The rule also forbids `var` redeclaration that are not a runtime error.
However, it is a special case.

The rule must thus be reworked to avoid to report duplicate parameters.

2023-03-15 22:14 UTC, Conaclos commented
Note: the rule also checks for function redeclarations which are allowed in JavaScript.

2023-03-16 00:21 UTC, ematipico approved these changes

2023-03-16 00:21 UTC, ematipico commented on crates/rome_js_syntax/src/binding_ext.rs
> +    /// `can_merge` ise sensible to the order of arguments.
"is" sensible

2023-03-16 00:21 UTC, ematipico commented on crates/rome_js_syntax/src/binding_ext.rs
> +    fn can_merge(a: &AnyJsBindingDeclaration, b: &AnyJsBindingDeclaration) -> bool {
I think this function can be declared as a `const fn`

2023-03-16 00:21 UTC, ematipico commented on crates/rome_js_syntax/src/binding_ext.rs
> +    pub fn is_parameter_like(&self) -> bool {
I think this function can declared as a `const fn`

2023-03-16 12:09 UTC, merged