feat(rome_js_analyze): noRedundantRoles
rome/tools pull request #4293
Opened 2023-03-10 18:06 UTC by unvalley

## Summary

## Test Plan

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

2023-03-11 02:10 UTC, unvalley commented on crates/rome_aria/src/roles.rs
> +        // attributes: Node,
@ematipico 
Here, I want to receive `JsxAttributeList` actually but I think this crates is not only for jsx. What kind of type is suitable to check the element's attributes? or let me know if I'm going the wrong way.

2023-03-11 03:57 UTC, ematipico commented on crates/rome_aria/src/roles.rs
> +        // attributes: Node,
You're right, this crate is for ARIA things only. What you could pass is array of strings `&[&str]`, which will contain the names of the attributes of the current element. This means that inside the rule, you want to map the list of attributes into an array.

2023-03-11 05:07 UTC, unvalley commented on crates/rome_aria/src/roles.rs
> +        // attributes: Node,
Thanks! I got it. 
Looking at [this w3c page](https://www.w3.org/TR/html-aria/#docconformance) again, I realized that I need the name and value of the attribute to determine the implicit role. I think I will pass a `HashMap` or `tuple` with `&str` as the argument.

2023-03-20 14:16 UTC, ematipico requested changes

2023-03-20 14:16 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_roles.rs
> +    let role = role.first()?;
Could you explain this part of the code? There's no comment or documentation that explain why we are taking the first part of a split string.

2023-03-21 10:02 UTC, unvalley commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_roles.rs
> +    /// EsLint Equivalent: [no-redundant-roles](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-redundant-roles.md)
I described the equivalent is eslint-plugin-jsx-a11y at [fcae9ed](https://github.com/rome/tools/pull/4293/commits/fcae9ed661ad05ab0480c7cf2ecef42323dad2e6).


nits: And I'd like to update default declare_rule comment EsLint → ESLint in another PR.

2023-03-21 10:04 UTC, unvalley commented on crates/rome_js_analyze/tests/specs/nursery/noRedundantRoles/invalid.jsx
> +	<a href="#" role="link"></a>
I didn't notice the file! thanks, I'll fix the test case and logic.

2023-03-23 13:14 UTC, unvalley commented on crates/rome_js_analyze/src/aria_services.rs
> +    pub fn extract_defined_attributes(
I agree with all.
- renamed to `extract_attributes`
- add some detail to documentation
- add test for `extract_attributes` to show how to use (it's kinda long for rustdoc...)

2023-03-23 13:26 UTC, unvalley commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_roles.rs
> +    let role = role.first()?;
In my view, if a `role` attribute has multiple values, the first valid role will be used as role. Others are fallbacks.

> Platform accessibility APIs traditionally have had a finite set of predefined roles that are expected by assistive technologies on that platform and only one or two roles may be exposed. In contrast, WAI-ARIA allows multiple roles to be specified as an ordered set of space-separated valid role tokens. The additional roles are fallback roles similar to the concept of specifying multiple fonts in case the first choice font type is not supported. https://www.w3.org/TR/2014/REC-wai-aria-implementation-20140320/#mapping_role

I updated the logic to find first valid role with `find_map` and added a comment.

2023-03-23 13:28 UTC, unvalley commented on crates/rome_aria/src/roles.rs
> +        attributes: HashMap<String, Vec<String>>,
Thanks, I updated the argument.

2023-03-23 14:54 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_roles.rs
> +    let role = role.first()?;
Wow, that's a fantastic piece of information! That's great!

I wouldn't mind to add this in a code comment, so we don't lose it!

2023-03-23 16:28 UTC, unvalley commented on crates/rome_js_analyze/src/aria_analyzers/nursery/no_redundant_roles.rs
> +    // Check: https://www.w3.org/TR/2014/REC-wai-aria-implementation-20140320/#mapping_role
yes, I added about that here!

2023-03-23 16:29 UTC, unvalley commented on crates/rome_js_analyze/src/analyzers/nursery/no_redundant_roles.rs
> +    let role = role.first()?;
https://github.com/rome/tools/pull/4293#discussion_r1146459577

2023-03-27 13:45 UTC, ematipico approved these changes

2023-03-27 15:53 UTC, unvalley commented
sorry for making the changes after receiving approval, but I've implemented a suggestion fix.

2023-03-30 17:45 UTC, ematipico commented
@unvalley That's great! Could you please update the `CHANGELOG.md`? https://github.com/rome/tools/blob/main/CONTRIBUTING.md#writing-a-changelog-line

We recently updated the contribution guidelines.

I think something like

```md
- [noRedundantRoles](https://docs.rome.tools/linter/rules/noRedundantRoles)
```

Should be fine (please double check the link)

2023-03-30 18:39 UTC, unvalley commented
@ematipico Thanks, I updated CHANGELOG.md!

2023-03-30 22:21 UTC, merged