feat(rome_js_analyze): noConfusingArrow
rome/tools pull request #4321
Opened 2023-03-24 21:36 UTC by malobre

## Summary

Closes #3931.

## Test Plan

`just test-lintrule noConfusingArrow`

```
just _touch crates/rome_js_analyze/tests/spec_tests.rs
touch crates/rome_js_analyze/tests/spec_tests.rs
cargo test -p rome_js_analyze -- no_confusing_arrow
   Compiling rome_js_analyze v0.0.0 (/home/malobre/workspace/rust/tools/crates/rome_js_analyze)
    Finished test [unoptimized + debuginfo] target(s) in 6.94s
     Running unittests src/lib.rs (target/debug/deps/rome_js_analyze-f3cf2ebbd37dd529)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 46 filtered out; finished in 0.00s

     Running tests/spec_tests.rs (target/debug/deps/spec_tests-445dd1d975dfdf40)

running 2 tests
test specs::nursery::no_confusing_arrow::invalid_js ... ok
test specs::nursery::no_confusing_arrow::valid_js ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 334 filtered out; finished in 0.16s

   Doc-tests rome_js_analyze

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 7 filtered out; finished in 0.00s
```

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

2023-03-24 21:38 UTC, malobre commented
I have not implemented the [options](https://eslint.org/docs/latest/rules/no-confusing-arrow#options), should I also do that ?

If I should I might need some guidance on options deserialization (doc seems to be outdated since #4160).

2023-03-25 10:34 UTC, ematipico commented
> I have not implemented the [options](https://eslint.org/docs/latest/rules/no-confusing-arrow#options), should I also do that ?
> 
> If I should, I will need some guidance on options deserialization (doc seems to be outdated since #4160).

We can implement the rule without options for now. That part of the analyzer is still a bit unstable/subject to change

2023-03-25 11:48 UTC, Conaclos requested changes

2023-03-25 11:48 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_confusing_arrow.rs
> +    ///
I could be nice to add the description of ESLint:

```md
Arrow functions (`=>`) are similar in syntax to some comparison operators (`>`, `<`, `<=`, and `>=`).
This rule warns against using the arrow function syntax in places where it could be confused with a comparison operator.
```

2023-03-25 11:48 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_confusing_arrow.rs
> +    type Query = Semantic<JsArrowFunctionExpression>;
```suggestion
    type Query = Ast<JsArrowFunctionExpression>;
```

We have several query type. Since you don't use the semantic model, `Ast` is enough. By the way the rule should be moved from `semantic_analyzer/` folder to `analyzer/` folder.

2023-03-25 11:48 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_confusing_arrow.rs
> +        if arrow_fn.fat_arrow_token().is_err() {
What is the purpose of this check?

2023-03-25 11:48 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_confusing_arrow.rs
> +        match arrow_fn.body() {
A `if let` statement could be a better fit here.

2023-03-25 11:48 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_confusing_arrow.rs
> +                    .expect("We checked that a `fat_arrow_token` exists in `run`")
Now I see why you make this check in `run`.
In other rules, it is more common to turn the error into an option using `ok()`, and then to use `?` to return if there is an error.

```suggestion
                    .ok()?
```

2023-03-25 11:48 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_confusing_arrow.rs
> +                    "Ambiguous fat arrow."
I suggest adding a more detailed explanation:

```suggestion
                    "The fat arrow can be confused with a comparison operator such as "<Emphasis>"<="</Emphasis>"."
```

This allows to directly understand why this is problematic.
We could thus remove the note.

2023-03-25 11:48 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_confusing_arrow.rs
> +        };
```suggestion
        let body_expr = ctx.query().body().as_any_js_expression()?;
```

2023-03-25 11:48 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_confusing_arrow.rs
> +            message: markup! { "Wrap body in parenthesis." }.to_owned(),
I think `the` is missing. I am not sure about that (English is not my native language).

```suggestion
            message: markup! { "Wrap the function body in parenthesis." }.to_owned(),
```

2023-03-25 11:49 UTC, Conaclos commented
Thanks for your contribution! This looks good at first glance!

2023-03-25 12:40 UTC, ematipico commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_confusing_arrow.rs
> +        };
It should be `body().ok()?`

2023-03-25 13:59 UTC, Conaclos commented on crates/rome_js_analyze/src/semantic_analyzers/nursery/no_confusing_arrow.rs
> +        };
Suggestion fixed :)

2023-03-25 21:20 UTC, Conaclos requested changes

2023-03-25 21:20 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_confusing_arrow.rs
> +            applicability: Applicability::MaybeIncorrect,
The fix seems safe? This could then be changed to:

```suggestion
            applicability: Applicability::Always,
```

2023-03-25 21:20 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_confusing_arrow.rs
> +        recommended: false,
I think we can recommend this rule:

```suggestion
        recommended: true,
```

2023-03-26 20:45 UTC, Conaclos commented
Our CI check the rules against the code of the website.
A code is triggering the rule:

```
website/src/playground/Playground.tsx:75:30 lint/nursery/noConfusingArrow  FIXABLE  ━━━━━━━━━━━━━━━━

  × Fat arrows can be confused with some comparison operators (<, >, <=, >=).
  
    73 │ 	const onUpdate = useCallback((viewUpdate: ViewUpdate) => {
    74 │ 		const cursorPosition = viewUpdate.state.selection.ranges[0]?.from ?? 0;
  > 75 │ 		setPlaygroundState((state) =>
       │ 		                           ^^
    76 │ 			state.cursorPosition !== cursorPosition
    77 │ 				? {
  
  i Safe fix: Wrap the function body in parenthesis.
  
     74  74 │   		const cursorPosition = viewUpdate.state.selection.ranges[0]?.from ?? 0;
     75  75 │   		setPlaygroundState((state) =>
     76     │ - → → → state.cursorPosition·!==·cursorPosition
         76 │ + → → → (
         77 │ + → → → state.cursorPosition·!==·cursorPosition
     77  78 │   				? {
     78  79 │   						...state,
     79  80 │   						cursorPosition,
     80  81 │   				  }
     81     │ - → → → → :·state,
         82 │ + → → → → :·state),
     82  83 │   		);
     83  84 │   	}, []);
```

The PR should thus fix the code that triggers the rule.

2023-03-29 13:58 UTC, ematipico commented
> What I meant is that this lint suggests adding parenthesis while `rome format` removes them. The formatter needs to be updated to take this into consideration.

We are better off removing the code action for the time being.

2023-03-29 13:59 UTC, ematipico commented
@malobre We recently changed they way to make PRs. Particularly, now PRs need to add a changelog line: https://github.com/rome/tools/blob/main/CONTRIBUTING.md#changelog

2023-03-29 15:03 UTC, malobre commented
I commented out the action and reverted the changes to `Playground.tsx`.
Also messed up the rebase, but I think its good now.

2023-03-29 17:59 UTC, Conaclos commented
> Fixed the commit author, sorry for all the noise

No problem :)

The CI is still failing. Could you set `recommended` to false? Hopefully, this will solve the issue. Sorry about this...

2023-03-29 18:55 UTC, ematipico approved these changes

2023-03-30 10:03 UTC, Conaclos approved these changes

2023-03-30 10:04 UTC, merged