refactor(rome_js_parser):
rome/tools pull request #4342
Opened 2023-04-02 12:33 UTC by nissy-dev

## Summary

This PR introduces common logic for checking expression values based on #4073 and discussion. This is useful when implementing some aria rules that checks value of the JSX attributes.

After merge in this PR, I will refactor much more in the current codebases using this methods.

## Test Plan

I need to keep the current tests passed.
I updated `useNumericLiterals/invalid.js.snap` because the previous code didn't handle empty template string correctly.

## Changelog

- [ ] The PR requires a changelog line

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

2023-04-02 12:58 UTC, nissy-dev commented
@MichaReiser This PR is based on your comments in #4073, so I would appreciate if you could review.

2023-04-02 13:00 UTC, ematipico requested changes

2023-04-02 13:00 UTC, ematipico commented on crates/rome_js_syntax/src/static_value.rs
> +
We should document this API and add a doctest, like we do for other public APIs exposed by this crate.

2023-04-07 15:05 UTC, nissy-dev commented on CHANGELOG.md
> +- Refactor common logic for checking value of the JSX attributes or JS expressions [#4073](https://github.com/rome/tools/pull/4073)
I reverted the differences in CHANGELOG.md.

2023-04-07 15:05 UTC, nissy-dev commented on crates/rome_js_syntax/src/static_value.rs
> +
I added doctests for StaticValue and QuotedString.

2023-04-07 16:01 UTC, ematipico approved these changes

2023-04-07 16:02 UTC, merged