feat(rome_js_analyze): noUselessConstructor
rome/tools pull request #4385
Opened 2023-04-18 13:34 UTC by Conaclos

## Summary

This implements [no-useless-constructor](https://typescript-eslint.io/rules/no-useless-constructor) with two differences:

- We do not detectect useless constructors with a super-call that spreads the legacy `arguments`.
- We report all empty constructor marked with the `public` modifier. In contrast, TypeScript ESLint does not report empty constructor marked with the `public` modifier in a class that inherits of another class. 

## Test Plan

ESLint tests included.

## Changelog

- [x] The PR requires a changelog line

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

2023-04-18 15:14 UTC, ematipico requested changes
You might want to take in consideration [TypeScript constructor overload](https://docs.nestjs.com/modules#dependency-injection). Some frameworks use that feature

2023-04-18 15:33 UTC, Conaclos commented
> You might want to take in consideration [TypeScript constructor overload](https://docs.nestjs.com/modules#dependency-injection). Some frameworks use that feature

In the orivided link, the code uses a parameter property to initialize the injected service.
The rule does not report empty constructors with at least one parameter property.

2023-04-18 15:57 UTC, denbezrukov commented
I was wondering if you could implement fix for this rule.
Could we remove contructor?

2023-04-18 17:08 UTC, ematipico commented
> > You might want to take in consideration [TypeScript constructor overload](https://docs.nestjs.com/modules#dependency-injection). Some frameworks use that feature
> 
> In the orivided link, the code uses a parameter property to initialize the injected service.
> The rule does not report empty constructors with at least one parameter property.

Cool, would you mind add a test case for that?

2023-04-19 11:14 UTC, Conaclos commented
> I was wondering if you could implement a fix for this rule. Could we remove the constructor?
> 
> What do you about a case when we have comments inside the body?

What I suggest:

- safe fix when there is no comments in the body or jsdoc befire the constructor,
- suggested fix otherwise.

2023-04-19 11:54 UTC, Conaclos commented
> Cool, would you mind add a test case for that?

Done :)

2023-04-19 12:24 UTC, denbezrukov commented
* safe fix when there is no comments in the body or jsdoc befire the constructor

I like that!

2023-04-20 07:45 UTC, ematipico requested changes

2023-04-20 07:45 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +    /// As such, it is unnecessary to provide an empty constructor or one that simply delegates into its parent.
```suggestion
    /// _ES2015_ provides a default class constructor if one is not specified.
    /// As such, providing an empty constructor or one that delegates into its parent is unnecessary.
```

2023-04-20 07:45 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +        }
I believe it's more readable if we apply the following techniques, considering that there are a lot of branches:
- if-else to opt-out from the rules, e.g.
```rs
// I haven't tried the code, but that's the idea
let js_expr = first.as_js_expression_statement()  else {
	return None;
}
```
- Use only `return Some(())` or don't use it. Here we mix the two things: the top `if` doesn't use the `return` but inside the first branch of the `if` we use `return`. I think maybe we can use just one pattern

2023-04-20 20:59 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +                return None;
The linter does not like this pattern. It proposes to switch to `is_delegating_initialization(constructor, js_call)?`. However, this looks bad regarding the code style of _Rome_ (explicit return when it is part of the rule logic). A possible fix could be to change the type of `is_delegating_initialization`.

2023-04-21 04:17 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +                return None;
Another workaround could be to return the text range of the constructor, considering that this is the last check.

Another alternative, is the following:

```rs
let is_delegating = is_delegating()?;
if is_delegating {}
```

2023-04-21 06:07 UTC, ematipico approved these changes

2023-04-21 06:07 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +            };
Can't we group these?

```rs
let js_call = first
	.as_js_expression_statement()?
	.expression()
	.ok()?
	.as_js_call_expression()?;
```

2023-04-21 06:07 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +            constructor.syntax().text_trimmed_range(),
nit: `constructor.range()`

2023-04-21 06:07 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +/// This checks that constructors' parameters are passed to the super-call in the same order.
```suggestion
/// This checks that constructors' **all** parameters are passed to the super-call in the same order.
```

2023-04-21 06:07 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +    let parameters = constructor.parameters().ok()?.parameters().iter();
Another workaround to the clippy issue is using closures:

```rs
fn is_delegating_initialization(
    constructor: &JsConstructorClassMember,
    super_call: &JsCallExpression,
) -> bool {
	let result = move || {
		// put here all the logic of the function that you wrote
	};

	result().unwrap_or(false)
}
```

2023-04-21 10:26 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +            };
The reasoning was: use `?` only for errors. Otherwise, use explicit control flow. However, if you think it is ok I can do the change. By the way it is possible that the transformation is not possible because some value can go outside scope (borrow checker issues).

2023-04-21 10:46 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +    let parameters = constructor.parameters().ok()?.parameters().iter();
Nice! I like the clean function signature!

2023-04-21 14:16 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_useless_constructor.rs
> +            };
You can use the try operators to traverse the AST and get the node you need. Sure, sometimes you get lifetime issues, but it's a smooth solution that avoids to do too many matches or if let.

2023-04-21 14:17 UTC, ematipico approved these changes

2023-04-21 14:18 UTC, merged