Making every type optional via Option
rome/tools pull request #4406
Opened 2023-04-24 18:06 UTC by 2022H1030042G

## Summary

## Test Plan

## Changelog

- [ ] The PR requires a changelog line

## Documentation

- [ ] The PR requires documentation
- [ ] I will create a new PR to update the documentation

2023-04-25 08:00 UTC, ematipico commented on crates/rome_service/src/configuration/formatter.rs
> +    pub enabled: Option<bool>,
For each line where you added `Option`, you add the following line, for example:

```rs
#[serde(skip_serializing_if = "Option::is_none")]
pub enabled: Option<bool>,
```

2023-04-25 08:00 UTC, ematipico commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
You have to update this line too with `Some(match LineWith::try_from() {})`

2023-04-26 04:11 UTC, 2022H1030042G commented on crates/rome_service/src/configuration/formatter.rs
> +    pub enabled: Option<bool>,
> For each line where you added `Option`, you add the following line, for example:
> 
> ```rust
> #[serde(skip_serializing_if = "Option::is_none")]
> pub enabled: Option<bool>,
> ```

This #[serde(skip_serializing_if = "Option::is_none")] has to be exactly added for all the lines?

2023-04-26 04:12 UTC, 2022H1030042G commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
Do you mean line 47 has to be replaced with Some(match LineWith::try_from() {}) ?

2023-04-26 04:40 UTC, ematipico commented on crates/rome_service/src/configuration/formatter.rs
> +    pub enabled: Option<bool>,
Yes, for all the lines you added `Option`

2023-04-26 04:41 UTC, ematipico commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
No, line 49

2023-04-26 05:03 UTC, 2022H1030042G commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
![error](https://user-images.githubusercontent.com/17452290/234474393-6ebc0832-7508-4810-bc5b-45df60a2873d.png)
it gives this error.

2023-04-26 06:03 UTC, 2022H1030042G commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
even if I remove ` , it gives the error:

![error2](https://user-images.githubusercontent.com/17452290/234483523-62772361-54ad-49ae-b513-d8dcee8060d3.png)

2023-04-26 06:38 UTC, ematipico commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
Sorry, that was an example 😅 I didn't want to write all the code. You just need to take the existing code:

```rs
self.line_width = match LineWith::try_from() {/* existing code */}
```

To 

```rs
self.line_width = Some(match LineWith::try_from() {/* existing code */})
```

2023-04-26 06:50 UTC, 2022H1030042G commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
There are still about 18 errors

2023-04-26 08:33 UTC, 2022H1030042G commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
I did, how can I solve an error like this?: 
![error3](https://user-images.githubusercontent.com/17452290/234517877-c517c3f2-94bb-4167-bbb6-38d8b7b7bd0b.png)

2023-04-26 08:48 UTC, ematipico commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
Look for a function called `serialize_line_width` and `deserialize_line_width`. These two functions have `LineWidth` in their signatures. Change them to `Option<LineWidth>`. You will have some compiler errors. The compiler will suggest you how to fix them.

2023-04-26 10:12 UTC, 2022H1030042G commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
for line 8 shown above, what can be done?

2023-04-26 13:03 UTC, ematipico commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
Could you please push the latest changes? The error is probably somewhere else.

2023-04-26 13:15 UTC, 2022H1030042G commented on crates/rome_service/src/configuration/parse/json/formatter.rs
>                  self.line_width = match LineWidth::try_from(line_width) {
Sure

2023-04-26 13:35 UTC, ematipico requested changes

2023-04-26 13:35 UTC, ematipico commented on crates/rome_formatter/src/lib.rs
> +    Space(Option<u8>),
This doesn't need to change. You can revert the change

2023-04-26 13:35 UTC, ematipico commented on crates/rome_formatter/src/printer/printer_options/mod.rs
> +            IndentStyle::Space(Option<count>) => count,
You can revert the change here

2023-04-26 13:35 UTC, ematipico commented on crates/rome_formatter/src/format_element/document.rs
> +        IndentStyle::Space(Some(2))
You can revert the change

2023-04-26 13:35 UTC, ematipico commented on crates/rome_formatter/src/format_element/document.rs
> +            indent_style: IndentStyle::Space(Some(2)),
You can revert the change

2023-04-26 13:35 UTC, ematipico commented on crates/rome_service/src/configuration/formatter.rs
> +            Some(PlainIndentStyle::Space) => IndentStyle::Space(conf.indent_size),
```suggestion
            Some(PlainIndentStyle::Tab) => IndentStyle::Tab,
            Some(PlainIndentStyle::Space) => IndentStyle::Space(conf.indent_size),
            None => IndentStyle::Tab
```

2023-04-26 13:35 UTC, ematipico commented on crates/rome_service/src/configuration/formatter.rs
> +    Option::<LineWidth>::try_from(value).map_err(serde::de::Error::custom)
```suggestion
    let line_width = LineWidth::try_from(value).map_err(serde::de::Error::custom)?;
	Ok(Some(line_width))
```

2023-04-26 13:48 UTC, 2022H1030042G commented
After performing the above changes, there are still errors.

2023-04-26 14:45 UTC, ematipico commented
> After performing the above changes, there are still errors. PFA [errors.txt](https://github.com/rome/tools/files/11333629/errors.txt)

You can push the changes :) no need to attach any files!

2023-04-26 15:03 UTC, 2022H1030042G commented
> > After performing the above changes, there are still errors. PFA [errors.txt](https://github.com/rome/tools/files/11333629/errors.txt)
> 
> You can push the changes :) no need to attach any files!

Done.

2023-04-28 11:29 UTC, ematipico commented
Hi @2022H1030042G, I thought you had some basic knowledge of Rust. I needed this feature for #4405 and eventually did it myself there.

Thank you for your contribution. I am going to create some new good first issues that don't require priority from our end!

2023-04-28 11:29 UTC, closed without merging