Added support for ignoring unknown files
rome/tools pull request #4527
Opened 2023-05-23 08:41 UTC by gautamprikshit1

Fixes #4513

2023-05-23 13:36 UTC, gautamprikshit1 commented
My apologies I will do that

2023-05-24 10:43 UTC, ematipico requested changes
Thank you for your contribution! The PR is far from being complete :) here's a like of things missing:

- **tests**. These are important to understand if the feature is working. I noticed that in the template of the PR you didn't write anything. Could you write some tests and make sure that the feature works?
- You should add a [changelog line](https://github.com/rome/tools/blob/main/CONTRIBUTING.md#writing-a-changelog-line)
- Please also add some tests [here](https://github.com/rome/tools/tree/main/crates/rome_service/tests/invalid). Here we have **invalid** cases. We should try to have a configuration file that contains `"ignoreUnknown"` that is **not** a boolean

2023-05-24 10:43 UTC, ematipico commented on crates/rome_service/src/configuration/parse/json/files.rs
> +            "ignore_unknown" => {
In JSON files this will be called `"ignoreUnknown"`

2023-05-24 10:43 UTC, ematipico commented on crates/rome_service/src/settings.rs
> +            ignore_unknown_files: config.ignore_unknown.unwrap_or(false),
You can use `unwrap_or_default`

2023-05-24 10:43 UTC, ematipico commented on crates/rome_service/src/workspace.rs
> +    pub fn ignore_unknown_files(
You created this method, but it isn't used anywhere. 

The signature of this method should get `&mut self` instead.

2023-05-30 13:51 UTC, ematipico commented
@gautamprikshit1 are you still interested working on this feature?

2023-05-30 15:41 UTC, closed without merging