feat(rome_js_analyze): noFallthroughSwitchClause
rome/tools pull request #4626
Opened 2023-06-28 01:03 UTC by ddanielsantos

## Summary

Closes #3973 

## Test Plan

`cargo test -p rome_js_analyze -- no_nonoctal_decimal_escape`

2023-06-28 10:22 UTC, Conaclos requested changes

2023-06-28 10:22 UTC, Conaclos commented on crates/rome_js_analyze/src/analyzers/nursery/no_fallthrough_switch_clause.rs
> +            | JsThrowStatement::can_cast(node.kind())
We should also handle `continue` statement.

2023-06-28 10:39 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_fallthrough_switch_clause.rs
> +    }
I don't think `peekable` is needed. We can do 
```suggestion
    let children = case.consequent().syntax().children();

    if children.into_iter().count() == 0 {
        return false;
    }
```

2023-06-28 10:39 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_fallthrough_switch_clause.rs
> +                "Add a `break` statement to the end of this case to prevent fallthrough."
```suggestion
                "Add a `break` or `return` statement to the end of this case to prevent fallthrough."
```

2023-06-28 10:39 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/no_fallthrough_switch_clause.rs
> +    /// This rule disallows fallthrough of case statements.
```suggestion
    /// Disallow fallthrough of case statements.
    ///
    /// Case statements in switch statements fall through by default. This can lead to unexpected behavior when forgotten.
    /// This rule disallows the fallthrough of case statements.
```

2023-06-29 10:17 UTC, ematipico approved these changes
The code looks good! Thank you! You should rebase your branch and resolve the conflicts. Just use `just ready` and commit anything that gets generated.

2023-06-29 11:55 UTC, Conaclos approved these changes

2023-07-04 06:33 UTC, ematipico commented
@ddanielsantos, I believe something went wrong with your branch, probably when you merged or rebased. It seems you did both?. Your PR has code that is not related to it.

Would you mind looking at it?

2023-07-04 11:35 UTC, ddanielsantos commented
I ended up messing up some things, would it be better if I opened another PR with the valid contents of this one?

2023-07-04 11:35 UTC, ddanielsantos commented
I ended up messing up some things, would it be better if I opened another PR with the valid contents of this one?

2023-07-04 11:45 UTC, ematipico commented
You can still use this PR. You could rebase locally your branch and remove the last two commits. 

`git rebase -i HEAD~3` and **drop** the last two commits (and keep the third).

Then just do a merge. It should be fine.

If that doesn't go well, then you could create a new PR.

2023-07-04 11:56 UTC, Conaclos commented
You can also rename your current branch and create a new branch with the old name. By pushing this new branch you are likely to push on this PR.

2023-07-04 11:58 UTC, ddanielsantos commented
ok i will do it

2023-07-05 08:40 UTC, ematipico commented
@ddanielsantos, almost there! The CI found a small error

2023-07-07 06:20 UTC, merged

2023-07-07 09:23 UTC, ddanielsantos commented
Thanks for your patience guys!

2023-07-07 09:25 UTC, Conaclos commented
Thanks to you!