feat(rome_js_analyze): new lint rule: `useImportRestrictions`
rome/tools pull request #4700
Opened 2023-07-14 14:29 UTC by arendjr

## Summary

This PR implements the initial version of the new `useImportRestrictions` as discussed in https://github.com/rome/tools/issues/4678

I think I have taken all the feedback from the [previous PR](https://github.com/rome/tools/pull/4638/) into account now.

## Test Plan

Tests are included in the PR.

2023-07-15 12:49 UTC, arendjr commented on crates/rome_console/src/fmt.rs
> +            string = string.replace('\\', "/");
I'm having a bit of doubts on this one myself, but seeing the test failure on Windows before I applied this fix, I'm not sure what a better way out would be here. And realistically, I don't think any developer uses backslashes in `import` statements on Windows anyway... (but maybe that's a statement I would come to regret :sweat_smile:)

2023-07-17 10:01 UTC, ematipico requested changes
I left some suggestions around:
- documentation
- implementation

Documentation: it should be more beginner-friendly 
Implementation: using `PathBuf` add complexity that we don't need. I believe working with strings is a more suitable approach where we don't need to deal with OS specific stuff.

2023-07-18 17:53 UTC, arendjr commented on crates/rome_console/src/fmt.rs
> +            string = string.replace('\\', "/");
Yeah, as you mentioned later on, I agree the usage of `PathBuf` introduced more trouble than it was worth. I'll revert that change.

2023-07-18 17:58 UTC, arendjr commented on Cargo.toml
>  # Crates needed in the workspace
These seem to be the result of running `just ready`. Shouldn't those changes be checked in?

2023-07-18 18:24 UTC, ematipico commented on Cargo.toml
>  # Crates needed in the workspace
That's weird, they don't seem to be formatted correctly.

2023-07-18 18:31 UTC, arendjr commented on crates/rome_js_analyze/src/analyzers/nursery/use_import_restrictions.rs
> +    let mut path = PathBuf::from(module_path.text());
Agreed.

2023-07-18 18:44 UTC, arendjr commented on Cargo.toml
>  # Crates needed in the workspace
I'll revert them manually then.

2023-07-18 18:55 UTC, arendjr commented on Cargo.toml
>  # Crates needed in the workspace
On second thought, should I? CI is green even with the changed `Cargo.toml`, so I think it doesn't check the formatting of this file. But that could mean it's actually incorrect in `main`, since the changes in this PR are triggered by `just ready` and they correctly sort the dependencies. I'm happy to revert if it only happens on my machine for some odd reason, but I'm thinking this might actually be how the file *should* be formatted.

2023-07-18 18:56 UTC, arendjr commented
I think all the PR issues have been addressed, just need to know what to do with the `Cargo.toml` :)

2023-07-21 10:53 UTC, ematipico commented
> I think all the PR issues have been addressed, just need to know what to do with the `Cargo.toml` :)

Nothing, that's the tool doing its job. Thank you!

2023-07-21 11:02 UTC, ematipico approved these changes
A couple of suggestions, and then we can merge!

2023-07-21 11:02 UTC, ematipico commented on crates/rome_js_analyze/src/analyzers/nursery/use_import_restrictions.rs
> +const SOURCE_EXTENSIONS: &[&str] = &["js", "ts", "cjs", "cts", "mjs", "mts", "jsx", "tsx"];
Should we consider `.d.ts` too? Genuine question, I don't know it :)

2023-07-21 12:58 UTC, arendjr commented on crates/rome_js_analyze/src/analyzers/nursery/use_import_restrictions.rs
> +const SOURCE_EXTENSIONS: &[&str] = &["js", "ts", "cjs", "cts", "mjs", "mts", "jsx", "tsx"];
I don't think it makes sense to be honest, since you can't `import "some_file.d.ts"`.

2023-07-21 13:01 UTC, arendjr commented
All done :+1:

2023-07-21 13:25 UTC, merged