refactor(rome_rowan): rework `SyntaxTokenText`
rome/tools pull request #4721
Opened 2023-07-22 10:17 UTC by Conaclos

## Summary

This PR should address [some concerns of @ematipico](https://github.com/rome/tools/pull/4709#discussion_r1267958380).

All `inner_text` functions now return a `SyntaxTokenText`.
I thus removed `Quoted` and `StaticStringValue`.

I reworked `SyntaxTokenText` to hold an absolute range instead of a relative range. This seems more consistent: `SyntaxNodeText` uses also an absolute range. Moreover, `SyntaxTokenText` is used in high level API. The relative range was surprising from a user point of view.

Yet, I did not manage I completely remove the need of the previous abstraction in the formatter. Thus, I moved the old abstraction under the name `GreenTokenText`. I could appreciate some help.

## Test Plan

In progress...

2023-07-23 12:02 UTC, Conaclos commented on crates/rome_formatter/src/format_element.rs
> +static_assert!(std::mem::size_of::<crate::FormatElement>() == 32usize);
I don't understand why the size changed.
Moreover, I cannot reproduce this test locally.
Before and after this PR, the size of `FormatElement` is evaluated to 40 bytes on my machine.

2023-07-23 20:56 UTC, MichaReiser commented on crates/rome_formatter/src/format_element.rs
> +static_assert!(std::mem::size_of::<crate::FormatElement>() == 32usize);
Did you measure the size with a release build? Some elements contain debug only data

Regressing the size has negative consequences on overall performance and memory consumption

2023-07-23 21:21 UTC, Conaclos commented on crates/rome_formatter/src/format_element.rs
> +static_assert!(std::mem::size_of::<crate::FormatElement>() == 32usize);
I accept with your point. However, I just merged `SyntaxTokenTextSlice` into `SyntaxTokenText`. This should take the same space.

2023-07-23 21:36 UTC, Conaclos commented on crates/rome_formatter/src/format_element.rs
> +static_assert!(std::mem::size_of::<crate::FormatElement>() == 32usize);
> Did you measure the size with a release build? Some elements contain debug only data

You are right!

2023-07-23 22:13 UTC, ematipico commented
!bench_formatter

2023-07-23 22:23 UTC, ematipico commented on crates/rome_rowan/src/syntax_token_text.rs
> +    token_start: TextSize,
@Conaclos this is the reason why the `FormatElement` increased in size. 

`FormatElement` is an enum, and its size is equal to the biggest type among all variants. Which means that SyntaxTokenText is 32kb

2023-07-23 22:30 UTC, Conaclos commented on crates/rome_rowan/src/syntax_token_text.rs
> +    token_start: TextSize,
I just moved `source_position` from `SyntaxTokenTextSlice` to `SyntaxTokenText`:

```diff
struct SyntaxTokenText {
+   token_start: TextSize
    token: GreenToken
    range: TextRange
}
enum FormatElement {
-    SyntaxTokenTextSlice {
-        source_position: TextSize,
-        slice: SyntaxTokenText,
-    },
+    SyntaxTokenText(SyntaxTokenText),
}
```

`FormatElement::SyntaxTokenTextSlice` and `FormatElement::SyntaxTokenText` should have the same size?

2023-07-24 01:15 UTC, strager commented on crates/rome_formatter/src/format_element.rs
> +static_assert!(std::mem::size_of::<crate::FormatElement>() == 32usize);
Old layout of `format_element::FormatElement::SyntaxTokenTextSlice` (**24 bytes**):
```rust
#[repr(C)]
// alignment=8 size=24
struct FormatElement_SyntaxTokenTextSlice {
  variant: i8,          // which element of FormatElement is this?
  padding_0: [u8; 3],   // for text_size alignment
  text_size: u32,       // rome_text_size::TextSize::raw

  // Begin rome_rowan::SyntaxTokenText (alignment=8 size=16)
  green_token_ptr: u64, // rome_rowan::GreenToken::ptr (rome_rowan::ThinArc::ptr (pointer))
  range_start: u32,     // rome_text_size::TextRange::start (rome_text_size::TextSize::raw)
  range_end: u32,       // rome_text_size::TextRange::start (rome_text_size::TextSize::raw)
  // End rome_rowan::SyntaxTokenText (alignment=8 size=16)
}
```

New layout of `format_element::FormatElement::SyntaxTokenTextSlice` (**32 bytes**):
```rust
#[repr(C)]
// alignment=8 size=32
struct FormatElement_SyntaxTokenTextSlice {
  variant: i8,          // which element of FormatElement is this?
  padding_0: [u8; 7],   // for rome_rowan::SyntaxTokenText alignment

  // Begin rome_rowan::SyntaxTokenText (alignment=8 size=24)
  text_size: u32,       // rome_text_size::TextSize::raw
  padding_1: [u8; 4],   // for green_token_ptr alignment
  green_token_ptr: u64, // rome_rowan::GreenToken::ptr (rome_rowan::ThinArc::ptr (pointer))
  range_start: u32,     // rome_text_size::TextRange::start (rome_text_size::TextSize::raw)
  range_end: u32,       // rome_text_size::TextRange::start (rome_text_size::TextSize::raw)
  // End rome_rowan::SyntaxTokenText (alignment=8 size=24)
}
```

Before, the space between `format_element::FormatElement`'s discriminator and the `rome_rowan::SyntaxTokenText` was used to fit `text_size`. After, this space cannot be used. **+4 bytes**

After, `text_size` forces padding inside `rome_rowan::SyntaxTokenText`. The size of the members is 20 bytes, but because the struct needs to be 8-byte-aligned (because `rome_rowan::GreenToken` is 8-byte-aligned because pointers are 8-byte-aligned), 4 padding bytes are added. **+4 bytes**

+4 bytes + +4 bytes = +8 bytes

2023-07-24 06:46 UTC, ematipico commented on crates/rome_rowan/src/syntax_token_text.rs
> +    token_start: TextSize,
https://github.com/rome/tools/pull/4721#discussion_r1271621654

2023-07-24 09:42 UTC, ematipico commented
There are a couple of things that are not clear in this PR, and I would like to clarify them:
- what's the issue with `inner_string_text`? (please share an example so we can understand) 
- what's the issue with `SyntaxTokenText` not returning the range you need? (please share an example so we can understand)

Also, can you explain the relation between the two issues? 

If they are unrelated, we could open two different PRs.

2023-07-24 09:43 UTC, ematipico requested changes
We should avoid increasing memory, if the value we get in return is not enough

2023-07-24 09:43 UTC, ematipico commented on crates/rome_json_syntax/src/lib.rs
> +        let len = text.len() - TextSize::from(2);
This is unsafe because `text.len()` can be less than 2. You should use [`.saturing_sub`](https://doc.rust-lang.org/std/primitive.usize.html#method.saturating_sub)

2023-07-24 11:11 UTC, Conaclos commented on crates/rome_formatter/src/format_element.rs
> +static_assert!(std::mem::size_of::<crate::FormatElement>() == 32usize);
Thanks for the write-up!

I see two possibilities:

1. Replacing `TextRange` with a `SmallTextRange` struct in `SyntaxTokenText` to shrink `SyntaxTokenText` to 16 bytes.

3. Introducing `GreenTokenText` and reverting to the original layout of `FormatElement` (using `GreenTokenText`).

Any opinions?

2023-07-24 16:14 UTC, Conaclos commented
>     * what's the issue with `inner_string_text`? (please share an example so we can understand)

There is no issue except that code is duplicated in several places. I just renamed it to `inner_text`. However, we can keep the previous name...

> 
>     * what's the issue with `SyntaxTokenText` not returning the range you need? (please share an example so we can understand)

Let's me introduce some context to clarify the situation.

In some places, we need the text of a token, however, the borrow-checker requires allocating a new string. To avoid the allocation, `SyntaxTokenText` was introduced. 

`SyntaxTokenText` is used in high-level API of the JSON, JS and JSX linter and formatter. This is also used to return the inner text of a JSON string literal.

I expanded its uses to JS and JSX string literals to be more consistent with the JSON code base. This makes possible the deletion of `Quoted` and `StaticStringValue` utility types.

`SyntaxTokenText` offers a `range()` method. The prefix `Syntax` suggests that this range is absolute, similar to `SyntaxToken`, `SyntaxNode`, `SyntaxNodeText`, ...

However, it is not.
This is really misleading.
For instance, let's use the following example:

```js
let x;
``` 

The range of the token "x" is `(4,5)`.
The range of its token text is `(0,1)`.

This I think the method must either be removed or reworked to return an absolute range. I choose the second path because it is very convenient in high-level code
to have access to the absolute range of a text.
Otherwise, the user should fall back to `SyntaxToken` that is error-prone in the case where the token can be a string literal.

Moreover, there is the need to track the absolute range in other places like the formatter where a struct `SyntaxTokenTextSlice` and an enum variant `FormatElement::SyntaxTokenTextSlice` consisted of a `source_location` and a `SyntaxTokenText`. This looked like a good opportunity to merge `SyntaxTokenTextSlice` into `SyntaxTokenText`.

2023-07-24 16:22 UTC, Conaclos commented on crates/rome_json_syntax/src/lib.rs
> +        let len = text.len() - TextSize::from(2);
This should not be the case because it is a string literal?

2023-07-24 19:17 UTC, ematipico commented on crates/rome_json_syntax/src/lib.rs
> +        let len = text.len() - TextSize::from(2);
It's still an unsafe operation, which is done without the proper checks. If you think it's a safe operation, you should add a `// SAFETY` comment to explain why it's safe.

2023-07-24 19:37 UTC, ematipico commented
> There is no issue except that code is duplicated in several places. I just renamed it to inner_text. However, we can keep the previous name...

We can solve the repetition with a trait. Still, I think the changes can be moved into a separate PR. Doing so will allow to focus on what you're trying to solve.

> Otherwise, the user should fall back to `SyntaxToken` that is error-prone in the case where the token can be a string literal.

When you say "user", do you mean us developers? 

I'd like to propose another solution instead, where we remove the API that exposes the range of `SyntaxTokenText`. This is misleading, a developer should never rely on a range of substring in the first place. When dealing with string literals, the quotes should always be part of the range. 

If there's a particular case where we need to extract a sub-range of a string literal, in that case, it's up to the developer to compute it.

2023-07-27 14:33 UTC, closed without merging